// N2 Recovery — Day content provider: Vocabulary (50) + Quiz (20) per Day.
//
// Day 1 uses the owner's curated seed; other days are generated by Claude in
// the same rich shape and cached. Vocab is generated in two batches of 25 (to
// stay within reliable output sizes and avoid duplicates), quiz in one call.

import AsyncStorage from '@react-native-async-storage/async-storage';
import { getAnthropicApiKey } from './translate';
import { getN2Day } from '../constants/n2RecoveryCurriculum';
import { N2_DAY1_CONTENT } from '../constants/n2/day1Content';
import {
  ExTag,
  N2DayContent,
  N2QuizItem,
  N2VocabCard,
} from './n2DayContentTypes';

const ENDPOINT = 'https://api.anthropic.com/v1/messages';
const MODEL = 'claude-haiku-4-5';
const ANTHROPIC_VERSION = '2023-06-01';
const REQUEST_TIMEOUT_MS = 90000;
const CACHE_PREFIX = 'n2_daycontent_v1:';

export function isDayContentConfigured(): boolean {
  return Boolean(getAnthropicApiKey());
}

const SEEDS: Record<number, N2DayContent> = { 1: N2_DAY1_CONTENT };

export function hasSeed(day: number): boolean {
  return Boolean(SEEDS[day]);
}

function toAsciiJson(value: unknown): string {
  const s = JSON.stringify(value);
  let out = '';
  for (let i = 0; i < s.length; i++) {
    const code = s.charCodeAt(i);
    out += code < 128 ? s[i] : '\\u' + code.toString(16).padStart(4, '0');
  }
  return out;
}

function coerce(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function extractJson(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch {
    const a = text.indexOf('[');
    const b = text.lastIndexOf(']');
    if (a >= 0 && b > a) return JSON.parse(text.slice(a, b + 1));
    const c = text.indexOf('{');
    const d = text.lastIndexOf('}');
    if (c >= 0 && d > c) return JSON.parse(text.slice(c, d + 1));
    throw new Error('Claude không trả về JSON.');
  }
}

async function callClaude(system: string, user: unknown, maxTokens: number): Promise<string> {
  const apiKey = getAnthropicApiKey();
  if (!apiKey) throw new Error('not-configured');
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': ANTHROPIC_VERSION,
        'content-type': 'application/json',
      },
      body: toAsciiJson({
        model: MODEL,
        max_tokens: maxTokens,
        system,
        messages: [{ role: 'user', content: JSON.stringify(user) }],
      }),
      signal: controller.signal,
    });
    const json = (await res.json()) as {
      content?: Array<{ type: string; text?: string }>;
      error?: { message?: string };
    };
    if (!res.ok) throw new Error(json.error?.message || `Claude API lỗi HTTP ${res.status}`);
    const text = (json.content ?? [])
      .filter((b) => b.type === 'text' && b.text)
      .map((b) => b.text)
      .join('')
      .trim();
    if (!text) throw new Error('Claude trả về rỗng.');
    return text;
  } finally {
    clearTimeout(timer);
  }
}

const VOCAB_SYSTEM =
  'Bạn soạn từ vựng tiếng Nhật cho người Việt đã có N2, đang lấy lại năng lực để dùng ' +
  'trong công ty Nhật. Chỉ trả JSON thuần (không markdown), một MẢNG object đúng các khóa: ' +
  '{"jp": từ kèm cách đọc trong ngoặc vd 久しぶり（ひさしぶり）, ' +
  '"acc": pitch accent vd [5], "meta": "Nx ｜ loại từ ｜ ★★★ (tần suất)", ' +
  '"mean": nghĩa tiếng Việt, "nu": sắc thái tiếng Việt, "syn": từ đồng nghĩa, ' +
  '"ant": từ trái nghĩa (— nếu không có), "col": collocations, ' +
  '"use": "Daily◎ Business○ News△", "mis": lỗi người Việt hay mắc (tiếng Việt), ' +
  '"note": native note ngắn, ' +
  '"ex": [["D" hoặc "B" hoặc "N", câu ví dụ tiếng Nhật], ...] (2 ví dụ, tag D=Daily B=Business N=News)}. ' +
  'Từ phải sát chủ đề được cho, thực dụng, không trùng các từ trong danh sách "avoid".';

const QUIZ_SYSTEM =
  'Bạn soạn quiz trắc nghiệm tiếng Nhật cho người Việt N2 dựa trên các từ đã cho. ' +
  'Chỉ trả JSON thuần (không markdown), MẢNG 20 object: ' +
  '{"q": câu hỏi (tiếng Nhật hoặc Việt), "o": [4 lựa chọn], "a": chỉ số đáp án đúng 0-3}. ' +
  'Đa dạng: nghĩa, trợ từ, phân biệt sắc thái, mức dùng formal/casual.';

interface RawVocab {
  jp?: unknown;
  acc?: unknown;
  meta?: unknown;
  mean?: unknown;
  nu?: unknown;
  syn?: unknown;
  ant?: unknown;
  col?: unknown;
  use?: unknown;
  mis?: unknown;
  note?: unknown;
  ex?: unknown;
}

function parseVocabBatch(raw: string, startIndex: number): N2VocabCard[] {
  const parsed = extractJson(raw);
  if (!Array.isArray(parsed)) throw new Error('Vocab JSON không phải mảng.');
  return parsed.map((item, i): N2VocabCard => {
    const r = item as RawVocab;
    const ex: [ExTag, string][] = Array.isArray(r.ex)
      ? r.ex
          .map((e): [ExTag, string] => {
            const tag = Array.isArray(e) ? coerce(e[0]).toUpperCase() : '';
            const sentence = Array.isArray(e) ? coerce(e[1]) : '';
            const t: ExTag = tag === 'B' || tag === 'N' ? (tag as ExTag) : 'D';
            return [t, sentence];
          })
          .filter((e) => e[1])
      : [];
    return {
      id: `VOC${String(startIndex + i + 1).padStart(4, '0')}`,
      jp: coerce(r.jp),
      acc: coerce(r.acc),
      meta: coerce(r.meta),
      mean: coerce(r.mean),
      nu: coerce(r.nu),
      syn: coerce(r.syn) || '—',
      ant: coerce(r.ant) || '—',
      col: coerce(r.col),
      use: coerce(r.use),
      mis: coerce(r.mis),
      note: coerce(r.note),
      ex,
    };
  }).filter((v) => v.jp && v.mean);
}

function parseQuiz(raw: string): N2QuizItem[] {
  const parsed = extractJson(raw);
  if (!Array.isArray(parsed)) throw new Error('Quiz JSON không phải mảng.');
  return parsed
    .map((item): N2QuizItem => {
      const r = item as { q?: unknown; o?: unknown; a?: unknown };
      const o = Array.isArray(r.o) ? r.o.map(coerce).filter(Boolean) : [];
      const a = typeof r.a === 'number' && r.a >= 0 && r.a < o.length ? r.a : 0;
      return { q: coerce(r.q), o, a };
    })
    .filter((q) => q.q && q.o.length >= 2);
}

async function generateDayContent(day: number): Promise<N2DayContent> {
  const info = getN2Day(day);
  if (!info) throw new Error(`Không có Day ${day}.`);

  const vocab: N2VocabCard[] = [];
  for (let batch = 0; batch < 2; batch++) {
    const raw = await callClaude(
      VOCAB_SYSTEM,
      { theme: info.theme, topic: info.vocabTopic, count: 25, avoid: vocab.map((v) => v.jp) },
      8000
    );
    vocab.push(...parseVocabBatch(raw, vocab.length));
  }
  if (vocab.length === 0) throw new Error('Không sinh được từ vựng.');

  const quizRaw = await callClaude(
    QUIZ_SYSTEM,
    { theme: info.theme, words: vocab.slice(0, 30).map((v) => v.jp) },
    4096
  );
  const quiz = parseQuiz(quizRaw);

  return { day, vocab, quiz };
}

/** Get a Day's content: seed (Day 1), cache, or generate via Claude. */
export async function getDayContent(day: number): Promise<N2DayContent> {
  if (SEEDS[day]) return SEEDS[day];

  const key = `${CACHE_PREFIX}d${day}`;
  try {
    const cached = await AsyncStorage.getItem(key);
    if (cached) {
      const parsed = JSON.parse(cached) as N2DayContent;
      if (parsed.vocab?.length) return parsed;
    }
  } catch {
    // ignore cache read errors
  }

  const content = await generateDayContent(day);
  try {
    await AsyncStorage.setItem(key, JSON.stringify(content));
  } catch {
    // best-effort cache
  }
  return content;
}

/** Whether content is ready without a network call (seed or cached). */
export async function hasReadyDayContent(day: number): Promise<boolean> {
  if (SEEDS[day]) return true;
  try {
    return Boolean(await AsyncStorage.getItem(`${CACHE_PREFIX}d${day}`));
  } catch {
    return false;
  }
}
