import type { JapaneseWord } from '../../../types/content';

export const JAPANESE_WORDS: JapaneseWord[] = [
  {
    word: '在留カード',
    reading: 'ざいりゅうカード',
    romaji: 'zairyuu kaado',
    meaning: 'Thẻ cư trú',
    example: '在留カードを持っています。',
    exampleRomaji: 'Zairyuu kaado o motte imasu.',
    exampleMeaning: 'Tôi có mang theo thẻ cư trú.',
    culturalNote:
      'Nên luôn mang theo khi ra ngoài. Ngân hàng, nhà mạng, cơ quan và nhiều thủ tục sẽ yêu cầu thẻ này.',
  },
  {
    word: 'マイナンバーカード',
    reading: 'マイナンバーカード',
    romaji: 'mainanbaa kaado',
    meaning: 'Thẻ My Number',
    example: 'マイナンバーカードを申請しました。',
    exampleRomaji: 'Mainanbaa kaado o shinsei shimashita.',
    exampleMeaning: 'Tôi đã nộp đơn xin thẻ My Number.',
    culturalNote:
      'My Number khác với My Number Card. Có mã số không đồng nghĩa là bạn đã có thẻ vật lý.',
  },
  {
    word: '住民票',
    reading: 'じゅうみんひょう',
    romaji: 'juuminhyou',
    meaning: 'Giấy chứng nhận cư trú',
    example: '住民票を区役所でもらいました。',
    exampleRomaji: 'Juuminhyou o kuyakusho de moraimashita.',
    exampleMeaning: 'Tôi đã lấy giấy chứng nhận cư trú ở quận.',
  },
  {
    word: '保険証',
    reading: 'ほけんしょう',
    romaji: 'hokenshou',
    meaning: 'Thẻ bảo hiểm',
    example: '保険証を持ってきました。',
    exampleRomaji: 'Hokenshou o motte kimashita.',
    exampleMeaning: 'Tôi đã mang theo thẻ bảo hiểm.',
  },
  {
    word: '銀行口座',
    reading: 'ぎんこうこうざ',
    romaji: 'ginkou kouza',
    meaning: 'Tài khoản ngân hàng',
    example: '銀行口座を開設したいです。',
    exampleRomaji: 'Ginkou kouza o kaisetsu shitai desu.',
    exampleMeaning: 'Tôi muốn mở tài khoản ngân hàng.',
  },
  {
    word: '残業',
    reading: 'ざんぎょう',
    romaji: 'zangyou',
    meaning: 'Làm thêm giờ',
    example: '今日は残業があります。',
    exampleRomaji: 'Kyou wa zangyou ga arimasu.',
    exampleMeaning: 'Hôm nay có làm thêm giờ.',
  },
  {
    word: '定期券',
    reading: 'ていきけん',
    romaji: 'teikiken',
    meaning: 'Vé tháng',
    example: '定期券を買いたいです。',
    exampleRomaji: 'Teikiken o kaitai desu.',
    exampleMeaning: 'Tôi muốn mua vé tháng.',
  },
  {
    word: '乗り換え',
    reading: 'のりかえ',
    romaji: 'norikae',
    meaning: 'Chuyển tàu / đổi tuyến',
    example: 'ここで乗り換えです。',
    exampleRomaji: 'Koko de norikae desu.',
    exampleMeaning: 'Chuyển tàu ở đây.',
  },
  {
    word: '家賃',
    reading: 'やちん',
    romaji: 'yachin',
    meaning: 'Tiền thuê nhà',
    example: '家賃は毎月払います。',
    exampleRomaji: 'Yachin wa maitsuki haraimasu.',
    exampleMeaning: 'Tiền nhà được trả hàng tháng.',
  },
  {
    word: '有給休暇',
    reading: 'ゆうきゅうきゅうか',
    romaji: 'yuukyuu kyuuka',
    meaning: 'Nghỉ phép có lương',
    example: '有給休暇を取りたいです。',
    exampleRomaji: 'Yuukyuu kyuuka o toritai desu.',
    exampleMeaning: 'Tôi muốn xin nghỉ phép có lương.',
  },
  {
    word: '転入届',
    reading: 'てんにゅうとどけ',
    romaji: 'tennyuu todoke',
    meaning: 'Tờ khai chuyển đến',
    example: '転入届を出しに来ました。',
    exampleRomaji: 'Tennyuu todoke o dashi ni kimashita.',
    exampleMeaning: 'Tôi đến để nộp tờ khai chuyển đến.',
  },
  {
    word: '転出証明書',
    reading: 'てんしゅつしょうめいしょ',
    romaji: 'tenshutsu shoumeisho',
    meaning: 'Giấy chuyển đi',
    example: '転出証明書が必要ですか。',
    exampleRomaji: 'Tenshutsu shoumeisho ga hitsuyou desu ka.',
    exampleMeaning: 'Có cần giấy chuyển đi không?',
  },
  {
    word: '市役所',
    reading: 'しやくしょ',
    romaji: 'shiyakusho',
    meaning: 'Tòa thị chính / cơ quan phường',
    example: '市役所で手続きをします。',
    exampleRomaji: 'Shiyakusho de tetsuzuki o shimasu.',
    exampleMeaning: 'Tôi làm thủ tục ở cơ quan phường.',
  },
  {
    word: '区役所',
    reading: 'くやくしょ',
    romaji: 'kuyakusho',
    meaning: 'Ủy ban quận / ward office',
    example: '区役所は駅の近くです。',
    exampleRomaji: 'Kuyakusho wa eki no chikaku desu.',
    exampleMeaning: 'Ủy ban quận ở gần ga.',
  },
  {
    word: '健康保険',
    reading: 'けんこうほけん',
    romaji: 'kenkou hoken',
    meaning: 'Bảo hiểm y tế',
    example: '健康保険について確認したいです。',
    exampleRomaji: 'Kenkou hoken ni tsuite kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận về bảo hiểm y tế.',
  },
  {
    word: '国民健康保険',
    reading: 'こくみんけんこうほけん',
    romaji: 'kokumin kenkou hoken',
    meaning: 'Bảo hiểm y tế quốc dân',
    example: '国民健康保険に加入しました。',
    exampleRomaji: 'Kokumin kenkou hoken ni kanyuu shimashita.',
    exampleMeaning: 'Tôi đã tham gia bảo hiểm y tế quốc dân.',
  },
  {
    word: '年金',
    reading: 'ねんきん',
    romaji: 'nenkin',
    meaning: 'Lương hưu công / Nenkin',
    example: '年金の書類が届きました。',
    exampleRomaji: 'Nenkin no shorui ga todokimashita.',
    exampleMeaning: 'Giấy tờ Nenkin đã được gửi đến.',
  },
  {
    word: '国民年金',
    reading: 'こくみんねんきん',
    romaji: 'kokumin nenkin',
    meaning: 'Quốc dân niên kim',
    example: '国民年金の案内を読みました。',
    exampleRomaji: 'Kokumin nenkin no annai o yomimashita.',
    exampleMeaning: 'Tôi đã đọc hướng dẫn về quốc dân niên kim.',
  },
  {
    word: '厚生年金',
    reading: 'こうせいねんきん',
    romaji: 'kousei nenkin',
    meaning: 'Phúc lợi niên kim / pension qua công ty',
    example: '給与明細に厚生年金が載っています。',
    exampleRomaji: 'Kyuuyo meisai ni kousei nenkin ga notte imasu.',
    exampleMeaning: 'Trên phiếu lương có ghi khoản厚生年金.',
  },
  {
    word: '保険料',
    reading: 'ほけんりょう',
    romaji: 'hokenryou',
    meaning: 'Phí bảo hiểm',
    example: '保険料はいくらですか。',
    exampleRomaji: 'Hokenryou wa ikura desu ka.',
    exampleMeaning: 'Phí bảo hiểm là bao nhiêu?',
  },
  {
    word: '納付書',
    reading: 'のうふしょ',
    romaji: 'noufusho',
    meaning: 'Phiếu nộp tiền',
    example: '納付書で支払いました。',
    exampleRomaji: 'Noufusho de shiharaimashita.',
    exampleMeaning: 'Tôi đã thanh toán bằng phiếu nộp tiền.',
  },
  {
    word: '口座振替',
    reading: 'こうざふりかえ',
    romaji: 'kouza furikae',
    meaning: 'Trích tiền tự động qua tài khoản',
    example: '口座振替にしたいです。',
    exampleRomaji: 'Kouza furikae ni shitai desu.',
    exampleMeaning: 'Tôi muốn chuyển sang trích tiền tự động.',
  },
  {
    word: '送金',
    reading: 'そうきん',
    romaji: 'soukin',
    meaning: 'Chuyển tiền',
    example: '海外送金をしたいです。',
    exampleRomaji: 'Kaigai soukin o shitai desu.',
    exampleMeaning: 'Tôi muốn chuyển tiền ra nước ngoài.',
  },
  {
    word: '携帯電話',
    reading: 'けいたいでんわ',
    romaji: 'keitai denwa',
    meaning: 'Điện thoại di động',
    example: '携帯電話の契約をしたいです。',
    exampleRomaji: 'Keitai denwa no keiyaku o shitai desu.',
    exampleMeaning: 'Tôi muốn làm hợp đồng điện thoại di động.',
  },
  {
    word: 'SIMカード',
    reading: 'シムカード',
    romaji: 'SIM kaado',
    meaning: 'Thẻ SIM',
    example: 'SIMカードを入れ替えました。',
    exampleRomaji: 'SIM kaado o irekaemashita.',
    exampleMeaning: 'Tôi đã thay thẻ SIM.',
  },
  {
    word: '開通',
    reading: 'かいつう',
    romaji: 'kaitsuu',
    meaning: 'Kích hoạt / thông tuyến',
    example: '今日中に開通しますか。',
    exampleRomaji: 'Kyoujuu ni kaitsuu shimasu ka.',
    exampleMeaning: 'Hôm nay có kích hoạt xong không?',
  },
  {
    word: '本人確認書類',
    reading: 'ほんにんかくにんしょるい',
    romaji: 'honnin kakunin shorui',
    meaning: 'Giấy tờ xác minh danh tính',
    example: '本人確認書類を見せてください。',
    exampleRomaji: 'Honnin kakunin shorui o misete kudasai.',
    exampleMeaning: 'Xin hãy cho tôi xem giấy tờ xác minh danh tính.',
  },
  {
    word: '契約解除',
    reading: 'けいやくかいじょ',
    romaji: 'keiyaku kaijo',
    meaning: 'Hủy hợp đồng',
    example: '契約解除の条件を確認したいです。',
    exampleRomaji: 'Keiyaku kaijo no jouken o kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận điều kiện hủy hợp đồng.',
  },
  {
    word: '健康診断',
    reading: 'けんこうしんだん',
    romaji: 'kenkou shindan',
    meaning: 'Khám sức khỏe định kỳ',
    example: '健康診断の日程を確認しました。',
    exampleRomaji: 'Kenkou shindan no nittei o kakunin shimashita.',
    exampleMeaning: 'Tôi đã xác nhận lịch khám sức khỏe định kỳ.',
  },
  {
    word: '確定申告',
    reading: 'かくていしんこく',
    romaji: 'kakutei shinkoku',
    meaning: 'Khai thuế cuối kỳ',
    example: '確定申告が必要か確認したいです。',
    exampleRomaji: 'Kakutei shinkoku ga hitsuyou ka kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận xem có cần khai thuế cuối kỳ không.',
  },
  { word: '工場', reading: 'こうじょう', romaji: 'koujou', meaning: 'Nhà máy', example: '工場で働いています。', exampleRomaji: 'Koujou de hataraite imasu.', exampleMeaning: 'Tôi đang làm việc ở nhà máy.' },
  { word: 'ライン', reading: 'ライン', romaji: 'rain', meaning: 'Dây chuyền', example: '今日はラインに入ります。', exampleRomaji: 'Kyou wa rain ni hairimasu.', exampleMeaning: 'Hôm nay tôi vào dây chuyền.' },
  { word: '検品', reading: 'けんぴん', romaji: 'kenpin', meaning: 'Kiểm hàng', example: '出荷前に検品します。', exampleRomaji: 'Shukka mae ni kenpin shimasu.', exampleMeaning: 'Tôi kiểm hàng trước khi xuất.' },
  { word: '不良品', reading: 'ふりょうひん', romaji: 'furyouhin', meaning: 'Hàng lỗi', example: '不良品は別の箱に入れてください。', exampleRomaji: 'Furyouhin wa betsu no hako ni irete kudasai.', exampleMeaning: 'Xin hãy bỏ hàng lỗi vào thùng riêng.' },
  { word: '部品', reading: 'ぶひん', romaji: 'buhin', meaning: 'Linh kiện', example: '部品が足りません。', exampleRomaji: 'Buhin ga tarimasen.', exampleMeaning: 'Linh kiện không đủ.' },
  { word: '組み立て', reading: 'くみたて', romaji: 'kumitate', meaning: 'Lắp ráp', example: 'この工程は組み立てです。', exampleRomaji: 'Kono koutei wa kumitate desu.', exampleMeaning: 'Công đoạn này là lắp ráp.' },
  { word: '工程', reading: 'こうてい', romaji: 'koutei', meaning: 'Công đoạn', example: '次の工程へ運んでください。', exampleRomaji: 'Tsugi no koutei e hakonde kudasai.', exampleMeaning: 'Xin hãy chuyển sang công đoạn tiếp theo.' },
  { word: '出荷', reading: 'しゅっか', romaji: 'shukka', meaning: 'Xuất hàng', example: '午後の出荷に間に合わせます。', exampleRomaji: 'Gogo no shukka ni maniawasemasu.', exampleMeaning: 'Tôi sẽ kịp cho đợt xuất hàng buổi chiều.' },
  { word: '梱包', reading: 'こんぽう', romaji: 'konpou', meaning: 'Đóng gói', example: '梱包が終わったら知らせてください。', exampleRomaji: 'Konpou ga owattara shirasete kudasai.', exampleMeaning: 'Khi đóng gói xong hãy báo cho tôi.' },
  { word: '数量', reading: 'すうりょう', romaji: 'suuryou', meaning: 'Số lượng', example: '数量を確認しました。', exampleRomaji: 'Suuryou o kakunin shimashita.', exampleMeaning: 'Tôi đã kiểm tra số lượng.' },
  { word: '在庫', reading: 'ざいこ', romaji: 'zaiko', meaning: 'Tồn kho', example: '在庫が少なくなっています。', exampleRomaji: 'Zaiko ga sukunaku natte imasu.', exampleMeaning: 'Tồn kho đang ít đi.' },
  { word: '機械', reading: 'きかい', romaji: 'kikai', meaning: 'Máy móc', example: '機械を止めてください。', exampleRomaji: 'Kikai o tomete kudasai.', exampleMeaning: 'Xin hãy dừng máy.' },
  { word: '手袋', reading: 'てぶくろ', romaji: 'tebukuro', meaning: 'Găng tay', example: '手袋を着けてください。', exampleRomaji: 'Tebukuro o tsukete kudasai.', exampleMeaning: 'Xin hãy đeo găng tay.' },
  { word: '安全靴', reading: 'あんぜんぐつ', romaji: 'anzen gutsu', meaning: 'Giày bảo hộ', example: '安全靴は必ず履いてください。', exampleRomaji: 'Anzen gutsu wa kanarazu haite kudasai.', exampleMeaning: 'Nhất định phải mang giày bảo hộ.' },
  { word: '作業着', reading: 'さぎょうぎ', romaji: 'sagyougi', meaning: 'Đồng phục làm việc', example: '作業着に着替えます。', exampleRomaji: 'Sagyougi ni kigaemasu.', exampleMeaning: 'Tôi thay sang đồ làm việc.' },
  { word: '休憩', reading: 'きゅうけい', romaji: 'kyuukei', meaning: 'Nghỉ giải lao', example: '十時から休憩です。', exampleRomaji: 'Juuji kara kyuukei desu.', exampleMeaning: 'Nghỉ giải lao từ 10 giờ.' },
  { word: '残業代', reading: 'ざんぎょうだい', romaji: 'zangyoudai', meaning: 'Tiền làm thêm giờ', example: '残業代を確認したいです。', exampleRomaji: 'Zangyoudai o kakunin shitai desu.', exampleMeaning: 'Tôi muốn kiểm tra tiền làm thêm giờ.' },
  { word: '早退', reading: 'そうたい', romaji: 'soutai', meaning: 'Về sớm', example: '体調が悪いので早退したいです。', exampleRomaji: 'Taichou ga warui node soutai shitai desu.', exampleMeaning: 'Tôi muốn về sớm vì không khỏe.' },
  { word: '欠勤', reading: 'けっきん', romaji: 'kekkin', meaning: 'Nghỉ làm', example: '明日は欠勤します。', exampleRomaji: 'Ashita wa kekkin shimasu.', exampleMeaning: 'Ngày mai tôi nghỉ làm.' },
  { word: '交代', reading: 'こうたい', romaji: 'koutai', meaning: 'Đổi ca / thay ca', example: '午後のシフトと交代できますか。', exampleRomaji: 'Gogo no shifuto to koutai dekimasu ka.', exampleMeaning: 'Có thể đổi sang ca chiều không?' },

  { word: '建設現場', reading: 'けんせつげんば', romaji: 'kensetsu genba', meaning: 'Công trường xây dựng', example: '建設現場で働いています。', exampleRomaji: 'Kensetsu genba de hataraite imasu.', exampleMeaning: 'Tôi đang làm ở công trường xây dựng.' },
  { word: '足場', reading: 'あしば', romaji: 'ashiba', meaning: 'Giàn giáo', example: '足場では気をつけてください。', exampleRomaji: 'Ashiba de wa ki o tsukete kudasai.', exampleMeaning: 'Xin hãy cẩn thận trên giàn giáo.' },
  { word: 'ヘルメット', reading: 'ヘルメット', romaji: 'herumetto', meaning: 'Mũ bảo hộ', example: 'ヘルメットを着用してください。', exampleRomaji: 'Herumetto o chakuyou shite kudasai.', exampleMeaning: 'Xin hãy đội mũ bảo hộ.' },
  { word: '安全帯', reading: 'あんぜんたい', romaji: 'anzentai', meaning: 'Dây an toàn', example: '高い所では安全帯が必要です。', exampleRomaji: 'Takai tokoro de wa anzentai ga hitsuyou desu.', exampleMeaning: 'Làm ở chỗ cao cần dây an toàn.' },
  { word: '高所作業', reading: 'こうしょさぎょう', romaji: 'kousho sagyou', meaning: 'Làm việc trên cao', example: '今日は高所作業があります。', exampleRomaji: 'Kyou wa kousho sagyou ga arimasu.', exampleMeaning: 'Hôm nay có việc trên cao.' },
  { word: '危険', reading: 'きけん', romaji: 'kiken', meaning: 'Nguy hiểm', example: 'ここは危険です。', exampleRomaji: 'Koko wa kiken desu.', exampleMeaning: 'Chỗ này nguy hiểm.' },
  { word: '立入禁止', reading: 'たちいりきんし', romaji: 'tachiiri kinshi', meaning: 'Cấm vào', example: 'ここは立入禁止です。', exampleRomaji: 'Koko wa tachiiri kinshi desu.', exampleMeaning: 'Khu vực này cấm vào.' },
  { word: '工具', reading: 'こうぐ', romaji: 'kougu', meaning: 'Dụng cụ', example: '工具を片づけてください。', exampleRomaji: 'Kougu o katazukete kudasai.', exampleMeaning: 'Xin hãy cất dụng cụ đi.' },
  { word: '資材', reading: 'しざい', romaji: 'shizai', meaning: 'Vật liệu', example: '資材を運びます。', exampleRomaji: 'Shizai o hakobimasu.', exampleMeaning: 'Tôi sẽ chuyển vật liệu.' },
  { word: '搬入', reading: 'はんにゅう', romaji: 'hannyuu', meaning: 'Đưa vật liệu vào', example: '朝に資材を搬入します。', exampleRomaji: 'Asa ni shizai o hannyuu shimasu.', exampleMeaning: 'Buổi sáng sẽ đưa vật liệu vào.' },
  { word: '搬出', reading: 'はんしゅつ', romaji: 'hanshutsu', meaning: 'Đưa vật liệu ra', example: '午後に廃材を搬出します。', exampleRomaji: 'Gogo ni haizai o hanshutsu shimasu.', exampleMeaning: 'Buổi chiều sẽ chuyển phế liệu ra ngoài.' },
  { word: '図面', reading: 'ずめん', romaji: 'zumen', meaning: 'Bản vẽ', example: '図面を確認してください。', exampleRomaji: 'Zumen o kakunin shite kudasai.', exampleMeaning: 'Xin hãy kiểm tra bản vẽ.' },
  { word: '寸法', reading: 'すんぽう', romaji: 'sunpou', meaning: 'Kích thước', example: '寸法が違います。', exampleRomaji: 'Sunpou ga chigaimasu.', exampleMeaning: 'Kích thước bị sai.' },
  { word: '測る', reading: 'はかる', romaji: 'hakaru', meaning: 'Đo', example: 'もう一度測ってください。', exampleRomaji: 'Mou ichido hakatte kudasai.', exampleMeaning: 'Xin hãy đo lại lần nữa.' },
  { word: '休工', reading: 'きゅうこう', romaji: 'kyuukou', meaning: 'Tạm ngừng thi công', example: '雨で今日は休工です。', exampleRomaji: 'Ame de kyou wa kyuukou desu.', exampleMeaning: 'Hôm nay tạm ngừng thi công vì mưa.' },
  { word: '現場監督', reading: 'げんばかんとく', romaji: 'genba kantoku', meaning: 'Giám sát công trường', example: '現場監督に確認します。', exampleRomaji: 'Genba kantoku ni kakunin shimasu.', exampleMeaning: 'Tôi sẽ xác nhận với giám sát công trường.' },
  { word: '作業指示', reading: 'さぎょうしじ', romaji: 'sagyou shiji', meaning: 'Chỉ thị công việc', example: '朝礼で作業指示を聞きます。', exampleRomaji: 'Chourei de sagyou shiji o kikimasu.', exampleMeaning: 'Tôi nghe chỉ thị công việc ở buổi họp sáng.' },
  { word: '朝礼', reading: 'ちょうれい', romaji: 'chourei', meaning: 'Họp đầu giờ', example: '朝礼は七時半からです。', exampleRomaji: 'Chourei wa shichiji han kara desu.', exampleMeaning: 'Họp đầu giờ từ 7 giờ rưỡi.' },
  { word: '片付け', reading: 'かたづけ', romaji: 'katazuke', meaning: 'Dọn dẹp', example: '作業後に片付けをします。', exampleRomaji: 'Sagyougo ni katazuke o shimasu.', exampleMeaning: 'Sau khi làm xong sẽ dọn dẹp.' },
  { word: '報告', reading: 'ほうこく', romaji: 'houkoku', meaning: 'Báo cáo', example: '問題があればすぐ報告してください。', exampleRomaji: 'Mondai ga areba sugu houkoku shite kudasai.', exampleMeaning: 'Nếu có vấn đề hãy báo ngay.' },

  { word: '農場', reading: 'のうじょう', romaji: 'noujou', meaning: 'Nông trại', example: '農場で野菜を育てています。', exampleRomaji: 'Noujou de yasai o sodatete imasu.', exampleMeaning: 'Tôi đang trồng rau ở nông trại.' },
  { word: '畑', reading: 'はたけ', romaji: 'hatake', meaning: 'Ruộng / vườn', example: '畑に行ってきます。', exampleRomaji: 'Hatake ni itte kimasu.', exampleMeaning: 'Tôi ra ruộng đây.' },
  { word: '収穫', reading: 'しゅうかく', romaji: 'shuukaku', meaning: 'Thu hoạch', example: '今日はトマトを収穫します。', exampleRomaji: 'Kyou wa tomato o shuukaku shimasu.', exampleMeaning: 'Hôm nay tôi thu hoạch cà chua.' },
  { word: '苗', reading: 'なえ', romaji: 'nae', meaning: 'Cây giống', example: '苗を植えます。', exampleRomaji: 'Nae o uemasu.', exampleMeaning: 'Tôi trồng cây giống.' },
  { word: '種', reading: 'たね', romaji: 'tane', meaning: 'Hạt giống', example: '種をまく時期です。', exampleRomaji: 'Tane o maku jiki desu.', exampleMeaning: 'Đến lúc gieo hạt rồi.' },
  { word: '肥料', reading: 'ひりょう', romaji: 'hiryou', meaning: 'Phân bón', example: '肥料を入れてください。', exampleRomaji: 'Hiryou o irete kudasai.', exampleMeaning: 'Xin hãy bón phân.' },
  { word: '農薬', reading: 'のうやく', romaji: 'nouyaku', meaning: 'Thuốc nông nghiệp', example: '農薬を使う時は手袋が必要です。', exampleRomaji: 'Nouyaku o tsukau toki wa tebukuro ga hitsuyou desu.', exampleMeaning: 'Khi dùng thuốc nông nghiệp cần găng tay.' },
  { word: '水やり', reading: 'みずやり', romaji: 'mizuyari', meaning: 'Tưới nước', example: '朝に水やりをします。', exampleRomaji: 'Asa ni mizuyari o shimasu.', exampleMeaning: 'Buổi sáng tôi tưới nước.' },
  { word: '選別', reading: 'せんべつ', romaji: 'senbetsu', meaning: 'Phân loại', example: '大きさで選別します。', exampleRomaji: 'Ookisa de senbetsu shimasu.', exampleMeaning: 'Tôi phân loại theo kích cỡ.' },
  { word: '箱詰め', reading: 'はこづめ', romaji: 'hakodume', meaning: 'Đóng thùng', example: '収穫した野菜を箱詰めします。', exampleRomaji: 'Shuukaku shita yasai o hakodume shimasu.', exampleMeaning: 'Tôi đóng thùng rau đã thu hoạch.' },
  { word: '温室', reading: 'おんしつ', romaji: 'onshitsu', meaning: 'Nhà kính', example: '温室の温度を確認してください。', exampleRomaji: 'Onshitsu no ondo o kakunin shite kudasai.', exampleMeaning: 'Xin hãy kiểm tra nhiệt độ nhà kính.' },
  { word: '気温', reading: 'きおん', romaji: 'kion', meaning: 'Nhiệt độ không khí', example: '今日は気温が高いです。', exampleRomaji: 'Kyou wa kion ga takai desu.', exampleMeaning: 'Hôm nay nhiệt độ cao.' },
  { word: '長靴', reading: 'ながぐつ', romaji: 'nagagutsu', meaning: 'Ủng', example: '畑では長靴を履いてください。', exampleRomaji: 'Hatake de wa nagagutsu o haite kudasai.', exampleMeaning: 'Trong ruộng hãy mang ủng.' },
  { word: '雨具', reading: 'あまぐ', romaji: 'amagu', meaning: 'Đồ đi mưa', example: '雨具を持って行ってください。', exampleRomaji: 'Amagu o motte itte kudasai.', exampleMeaning: 'Xin hãy mang đồ đi mưa.' },
  { word: '休憩所', reading: 'きゅうけいじょ', romaji: 'kyuukeijo', meaning: 'Chỗ nghỉ', example: '休憩所で水を飲みましょう。', exampleRomaji: 'Kyuukeijo de mizu o nomimashou.', exampleMeaning: 'Hãy uống nước ở chỗ nghỉ.' },
  { word: '出荷場', reading: 'しゅっかじょう', romaji: 'shukkajou', meaning: 'Khu xuất hàng', example: '箱は出荷場に運びます。', exampleRomaji: 'Hako wa shukkajou ni hakobimasu.', exampleMeaning: 'Thùng sẽ được chuyển đến khu xuất hàng.' },
  { word: '台車', reading: 'だいしゃ', romaji: 'daisha', meaning: 'Xe đẩy', example: '台車を使ってください。', exampleRomaji: 'Daisha o tsukatte kudasai.', exampleMeaning: 'Xin hãy dùng xe đẩy.' },
  { word: '腰', reading: 'こし', romaji: 'koshi', meaning: 'Lưng', example: '腰が痛いです。', exampleRomaji: 'Koshi ga itai desu.', exampleMeaning: 'Tôi bị đau lưng.' },
  { word: '熱中症', reading: 'ねっちゅうしょう', romaji: 'necchuushou', meaning: 'Sốc nhiệt', example: '暑い日は熱中症に気をつけてください。', exampleRomaji: 'Atsui hi wa necchuushou ni ki o tsukete kudasai.', exampleMeaning: 'Ngày nóng hãy cẩn thận sốc nhiệt.' },
  { word: '休み希望', reading: 'やすみきぼう', romaji: 'yasumi kibou', meaning: 'Nguyện vọng nghỉ', example: '来週の休み希望を出してください。', exampleRomaji: 'Raishuu no yasumi kibou o dashite kudasai.', exampleMeaning: 'Xin hãy nộp nguyện vọng nghỉ tuần sau.' },

  { word: '飲食店', reading: 'いんしょくてん', romaji: 'inshokuten', meaning: 'Nhà hàng / quán ăn', example: '飲食店で働いています。', exampleRomaji: 'Inshokuten de hataraite imasu.', exampleMeaning: 'Tôi làm ở nhà hàng.' },
  { word: '注文', reading: 'ちゅうもん', romaji: 'chuumon', meaning: 'Gọi món / đơn gọi món', example: 'ご注文をお願いします。', exampleRomaji: 'Gochuumon o onegaishimasu.', exampleMeaning: 'Xin cho tôi nhận order.' },
  { word: '予約', reading: 'よやく', romaji: 'yoyaku', meaning: 'Đặt chỗ', example: '予約のお客様です。', exampleRomaji: 'Yoyaku no okyakusama desu.', exampleMeaning: 'Đây là khách đã đặt chỗ.' },
  { word: '満席', reading: 'まんせき', romaji: 'manseki', meaning: 'Hết chỗ', example: '今は満席です。', exampleRomaji: 'Ima wa manseki desu.', exampleMeaning: 'Hiện tại đã hết chỗ.' },
  { word: '厨房', reading: 'ちゅうぼう', romaji: 'chuubou', meaning: 'Bếp', example: '厨房に伝えます。', exampleRomaji: 'Chuubou ni tsutaemasu.', exampleMeaning: 'Tôi sẽ báo cho bếp.' },
  { word: '洗い場', reading: 'あらいば', romaji: 'araiba', meaning: 'Khu rửa chén', example: '洗い場を手伝ってください。', exampleRomaji: 'Araiba o tetsudatte kudasai.', exampleMeaning: 'Xin hãy phụ khu rửa chén.' },
  { word: 'テーブルの片付け', reading: 'テーブルのかたづけ', romaji: 'teeburu no katazuke', meaning: 'Dọn bàn / dọn dẹp bàn', example: 'テーブルを片付けます。', exampleRomaji: 'Teeburu o katazukemasu.', exampleMeaning: 'Tôi dọn bàn.' },
  { word: '会計', reading: 'かいけい', romaji: 'kaikei', meaning: 'Tính tiền', example: 'レジで会計します。', exampleRomaji: 'Reji de kaikei shimasu.', exampleMeaning: 'Tôi tính tiền ở quầy.' },
  { word: 'お釣り', reading: 'おつり', romaji: 'otsuri', meaning: 'Tiền thối lại', example: 'お釣りはこちらです。', exampleRomaji: 'Otsuri wa kochira desu.', exampleMeaning: 'Tiền thối đây ạ.' },
  { word: 'レジ', reading: 'レジ', romaji: 'reji', meaning: 'Quầy tính tiền', example: 'レジをお願いします。', exampleRomaji: 'Reji o onegaishimasu.', exampleMeaning: 'Xin phụ trách quầy thu ngân.' },
  { word: '取り皿', reading: 'とりざら', romaji: 'torizara', meaning: 'Đĩa nhỏ chia món', example: '取り皿をお持ちします。', exampleRomaji: 'Torizara o omochi shimasu.', exampleMeaning: 'Tôi sẽ mang đĩa nhỏ ra.' },
  { word: '箸', reading: 'はし', romaji: 'hashi', meaning: 'Đũa', example: 'お箸をお持ちします。', exampleRomaji: 'Ohashi o omochi shimasu.', exampleMeaning: 'Tôi sẽ mang đũa ra.' },
  { word: 'スプーン', reading: 'スプーン', romaji: 'supuun', meaning: 'Muỗng', example: 'スプーンは必要ですか。', exampleRomaji: 'Supuun wa hitsuyou desu ka.', exampleMeaning: 'Quý khách có cần muỗng không?' },
  { word: '持ち帰り', reading: 'もちかえり', romaji: 'mochikaeri', meaning: 'Mang về', example: '持ち帰りですか。', exampleRomaji: 'Mochikaeri desu ka.', exampleMeaning: 'Quý khách mang về phải không?' },
  { word: '店内', reading: 'てんない', romaji: 'tennai', meaning: 'Dùng tại quán', example: '店内でお召し上がりですか。', exampleRomaji: 'Tennai de omeshiagari desu ka.', exampleMeaning: 'Quý khách dùng tại quán phải không?' },
  { word: 'おすすめ', reading: 'おすすめ', romaji: 'osusume', meaning: 'Món gợi ý', example: '今日のおすすめはこちらです。', exampleRomaji: 'Kyou no osusume wa kochira desu.', exampleMeaning: 'Món gợi ý hôm nay là món này.' },
  { word: '品切れ', reading: 'しなぎれ', romaji: 'shinagire', meaning: 'Hết món', example: '申し訳ありませんが、品切れです。', exampleRomaji: 'Moushiwake arimasen ga, shinagire desu.', exampleMeaning: 'Xin lỗi, món này đã hết.' },
  { word: '配膳', reading: 'はいぜん', romaji: 'haizen', meaning: 'Phục vụ món', example: '料理を配膳します。', exampleRomaji: 'Ryouri o haizen shimasu.', exampleMeaning: 'Tôi mang món ra phục vụ.' },
  { word: '下げる', reading: 'さげる', romaji: 'sageru', meaning: 'Dọn bát đĩa xuống', example: '空いた皿を下げます。', exampleRomaji: 'Aita sara o sagemasu.', exampleMeaning: 'Tôi dọn đĩa trống xuống.' },
  { word: 'シフト', reading: 'シフト', romaji: 'shifuto', meaning: 'Ca làm', example: '来週のシフトを確認しました。', exampleRomaji: 'Raishuu no shifuto o kakunin shimashita.', exampleMeaning: 'Tôi đã kiểm tra ca làm tuần sau.' },
];
