export const Colors = {
  primary: '#185FA5',
  primaryLight: '#2272C3',
  primaryDark: '#0E3F6E',
  accent: '#E8F0FA',
  white: '#FFFFFF',
  background: '#F4F6FB',
  card: '#FFFFFF',
  border: '#E0E8F5',
  textPrimary: '#1A1A2E',
  textSecondary: '#5C6B8A',
  textMuted: '#9AAABF',
  success: '#27AE60',
  warning: '#F39C12',
  danger: '#E74C3C',
  dangerLight: '#FDECEA',
  warningLight: '#FEF9EC',
  successLight: '#EAF7EF',
  tagBlue: '#EBF3FF',
  tagGreen: '#E6F7EE',
  tagOrange: '#FFF3E6',
  tabBar: '#FFFFFF',
  shadow: '#000000',
};
