export const EMERGENCY_CONTACTS = [
  {
    id: '1',
    name: 'Cảnh sát / Cấp cứu',
    nameJp: '警察・救急',
    number: '110 / 119',
    icon: 'alert-circle',
    color: '#E74C3C',
  },
  {
    id: '2',
    name: 'Đường dây tư vấn người nước ngoài',
    nameJp: '外国人在留支援センター',
    number: '0570-011000',
    icon: 'phone',
    color: '#185FA5',
  },
  {
    id: '3',
    name: 'Đại sứ quán Việt Nam tại Nhật',
    nameJp: 'ベトナム大使館',
    number: '+81-3-3466-3313',
    icon: 'flag',
    color: '#27AE60',
  },
];

export const ALERTS = [
  {
    id: '1',
    title: 'Gia hạn thẻ cư trú sắp đến hạn',
    description: 'Thẻ cư trú của bạn sẽ hết hạn trong vòng 3 tháng. Hãy chuẩn bị hồ sơ sớm!',
    urgency: 'high' as const,
    daysLeft: 87,
    actionLabel: 'Xem hướng dẫn',
    actionScreen: 'Admin',
  },
  {
    id: '2',
    title: 'Đăng ký bảo hiểm y tế',
    description: 'Tất cả người nước ngoài ở Nhật trên 3 tháng đều phải có bảo hiểm y tế quốc gia.',
    urgency: 'medium' as const,
    actionLabel: 'Tìm hiểu thêm',
    actionScreen: 'Admin',
  },
];

export const ADMIN_GUIDES = [
  {
    id: 'residence-card',
    title: 'Gia hạn thẻ cư trú',
    titleJp: '在留カード更新',
    icon: 'card',
    color: '#185FA5',
    description: 'Hướng dẫn gia hạn thẻ cư trú (Zairyu Card) tại Cục quản lý xuất nhập cảnh',
    steps: [
      {
        step: 1,
        title: 'Chuẩn bị hồ sơ',
        description: 'Thu thập đầy đủ các giấy tờ cần thiết trước khi đến cục xuất nhập cảnh.',
        documents: [
          'Đơn xin gia hạn (mẫu tại cục hoặc tải online)',
          'Thẻ cư trú hiện tại (在留カード)',
          'Hộ chiếu còn hiệu lực',
          'Ảnh thẻ 4×3cm (chụp trong vòng 3 tháng)',
          'Giấy tờ chứng minh lý do lưu trú (hợp đồng lao động, giấy nhập học...)',
          'Lệ phí: 4,000 yên (tem thuế)',
        ],
        tip: 'Nên chuẩn bị hồ sơ trước ít nhất 3 tháng trước khi thẻ hết hạn',
      },
      {
        step: 2,
        title: 'Đến cục xuất nhập cảnh',
        description: 'Mang hồ sơ đến Cục quản lý xuất nhập cảnh (入国管理局) gần nhất.',
        documents: [],
        tip: 'Nên đến sớm vì thường có hàng dài. Mở cửa thứ 2–6, 9:00–16:00',
      },
      {
        step: 3,
        title: 'Nộp hồ sơ và nhận phiếu hẹn',
        description: 'Nộp hồ sơ tại quầy, nhận phiếu xác nhận và chờ kết quả qua bưu điện (khoảng 2–4 tuần).',
        documents: [],
        tip: 'Kiểm tra kỹ thông tin trên phiếu xác nhận trước khi rời đi',
      },
      {
        step: 4,
        title: 'Nhận thẻ mới',
        description: 'Khi nhận được thư thông báo, mang theo thẻ cũ và hộ chiếu đến nhận thẻ mới.',
        documents: [
          'Thư thông báo từ cục xuất nhập cảnh',
          'Thẻ cư trú cũ',
          'Hộ chiếu',
        ],
        tip: 'Thẻ mới sẽ được giao tại quầy trong ngày',
      },
    ],
  },
  {
    id: 'health-insurance',
    title: 'Đăng ký bảo hiểm y tế',
    titleJp: '国民健康保険加入',
    icon: 'heart',
    color: '#27AE60',
    description: 'Đăng ký bảo hiểm y tế quốc gia (Kokumin Kenkou Hoken) tại văn phòng phường/quận',
    steps: [
      {
        step: 1,
        title: 'Chuẩn bị giấy tờ',
        description: 'Thu thập các giấy tờ cần thiết để đăng ký bảo hiểm y tế.',
        documents: [
          'Thẻ cư trú (在留カード)',
          'Hộ chiếu',
          'Con dấu cá nhân (印鑑) nếu có',
          'Tài khoản ngân hàng (để đăng ký thanh toán tự động)',
        ],
        tip: 'Phí bảo hiểm tính theo thu nhập của năm trước, khoảng 2–10% thu nhập',
      },
      {
        step: 2,
        title: 'Đến văn phòng phường/quận',
        description: 'Đến quầy "国民健康保険" tại văn phòng phường (区役所/市役所) nơi bạn đăng ký hộ khẩu.',
        documents: [],
        tip: 'Mang theo thông dịch viên hoặc nhờ bạn bè nói tiếng Nhật đi cùng nếu cần',
      },
      {
        step: 3,
        title: 'Điền đơn và nộp hồ sơ',
        description: 'Điền mẫu đăng ký tại quầy và nộp cùng các giấy tờ đã chuẩn bị.',
        documents: [],
        tip: 'Thẻ bảo hiểm sẽ được cấp ngay trong ngày hoặc gửi qua bưu điện',
      },
      {
        step: 4,
        title: 'Nhận thẻ và bắt đầu sử dụng',
        description: 'Với thẻ bảo hiểm y tế, bạn chỉ trả 30% chi phí khám chữa bệnh tại bệnh viện.',
        documents: [],
        tip: 'Luôn mang thẻ bảo hiểm khi đi khám bệnh',
      },
    ],
  },
  {
    id: 'my-number',
    title: 'Đăng ký thẻ My Number',
    titleJp: 'マイナンバーカード申請',
    icon: 'id-card',
    color: '#9B59B6',
    description: 'Hướng dẫn đăng ký và nhận thẻ My Number (mã số cá nhân tại Nhật)',
    steps: [
      {
        step: 1,
        title: 'Nhận thông báo My Number',
        description: 'Sau khi đăng ký địa chỉ tại phường, bạn sẽ nhận được thư thông báo số My Number qua bưu điện.',
        documents: [
          'Thư thông báo My Number (通知カード hoặc マイナンバー通知書)',
        ],
        tip: 'Giữ cẩn thận số My Number, không chia sẻ với người lạ',
      },
      {
        step: 2,
        title: 'Đăng ký làm thẻ',
        description: 'Đăng ký làm thẻ My Number online qua QR code trên thư thông báo, hoặc đến văn phòng phường.',
        documents: [
          'Thư thông báo My Number',
          'Ảnh thẻ 4.5×3.5cm (chụp trong vòng 6 tháng)',
        ],
        tip: 'Đăng ký online nhanh và tiện hơn, làm tại trang web: https://mynumbercard.point.soumu.go.jp/',
      },
      {
        step: 3,
        title: 'Chờ thông báo nhận thẻ',
        description: 'Sau khi đăng ký, chờ khoảng 1–2 tháng để nhận thư thông báo đến nhận thẻ.',
        documents: [],
        tip: 'Thời gian chờ có thể lâu hơn vào cuối năm',
      },
      {
        step: 4,
        title: 'Đến nhận thẻ tại phường',
        description: 'Mang theo các giấy tờ để nhận thẻ My Number chính thức.',
        documents: [
          'Thư thông báo nhận thẻ',
          'Thẻ cư trú (在留カード)',
          'Hộ chiếu',
          'Thư thông báo My Number cũ',
        ],
        tip: 'Bạn sẽ được đặt mã PIN ngay tại quầy — nhớ ghi lại và bảo mật',
      },
    ],
  },
];

export const DAILY_LIFE_TOPICS = [
  {
    id: 'apartment',
    title: 'Thuê nhà / Căn hộ',
    titleJp: '賃貸住宅',
    icon: 'home',
    color: '#185FA5',
    description: 'Cách tìm và thuê căn hộ ở Nhật',
    prefilledQuestion: 'Hướng dẫn tôi cách thuê nhà/căn hộ ở Nhật Bản. Tôi cần biết về: quy trình, các loại phí ban đầu (敷金, 礼金, 仲介手数料), giấy tờ cần thiết, và những lưu ý quan trọng cho người Việt Nam.',
  },
  {
    id: 'trash',
    title: 'Phân loại rác',
    titleJp: 'ゴミの分別',
    icon: 'trash',
    color: '#27AE60',
    description: 'Hướng dẫn phân loại rác theo quy định Nhật',
    prefilledQuestion: 'Hướng dẫn tôi cách phân loại rác ở Nhật Bản. Các loại rác chính bao gồm gì? Quy định bỏ rác như thế nào? Hậu quả nếu không phân loại đúng? Cho tôi ví dụ cụ thể bằng tiếng Việt.',
  },
  {
    id: 'transportation',
    title: 'Giao thông / Suica & Pasmo',
    titleJp: '交通・Suica/Pasmo',
    icon: 'train',
    color: '#E74C3C',
    description: 'Cách sử dụng tàu điện và thẻ IC card',
    prefilledQuestion: 'Giải thích cho tôi cách sử dụng thẻ Suica và Pasmo ở Nhật Bản. Sự khác nhau giữa 2 loại thẻ này là gì? Cách mua, nạp tiền và sử dụng như thế nào? Có thể dùng để mua đồ ở convenience store không?',
  },
  {
    id: 'grocery',
    title: 'Mua sắm thực phẩm',
    titleJp: '食料品の買い物',
    icon: 'basket',
    color: '#F39C12',
    description: 'Siêu thị, giờ giảm giá và mẹo tiết kiệm',
    prefilledQuestion: 'Chia sẻ mẹo mua sắm thực phẩm tiết kiệm ở Nhật Bản. Giờ giảm giá ở siêu thị thường là khi nào? Tìm nguyên liệu nấu ăn Việt Nam ở đâu? Các chuỗi siêu thị rẻ nào nên biết? Hướng dẫn đọc nhãn hàng và ngày hết hạn bằng tiếng Nhật.',
  },
  {
    id: 'banking',
    title: 'Ngân hàng & Chuyển tiền',
    titleJp: '銀行・送金',
    icon: 'cash',
    color: '#9B59B6',
    description: 'Mở tài khoản và chuyển tiền về Việt Nam',
    prefilledQuestion: 'Hướng dẫn tôi mở tài khoản ngân hàng ở Nhật Bản và cách chuyển tiền về Việt Nam. Ngân hàng nào dễ mở tài khoản cho người nước ngoài? Cần giấy tờ gì? Dịch vụ chuyển tiền nào rẻ và an toàn nhất (Wise, Remitly, ngân hàng)?',
  },
];

export const JOBS_DATA = [
  {
    id: '1',
    title: 'Nhân viên phục vụ nhà hàng',
    titleJp: 'ホールスタッフ',
    company: 'Chuỗi nhà hàng Sakura Group',
    location: 'Shibuya, Tokyo',
    salary: '¥1,100/giờ',
    type: 'part-time' as const,
    category: 'restaurant' as const,
    tags: ['N4 trở lên', 'Part-time', 'Bảo hiểm'],
    japaneseLevel: 'N4',
    benefits: ['Bảo hiểm xã hội', 'Tàu xe được trả', 'Bữa ăn ca'],
    description: 'Phục vụ khách hàng tại nhà hàng Nhật truyền thống. Môi trường thân thiện, đồng nghiệp nhiều người Việt.',
    contact: 'Liên hệ qua Hello Work hoặc email',
  },
  {
    id: '2',
    title: 'Kỹ sư phần mềm (Backend)',
    titleJp: 'バックエンドエンジニア',
    company: 'TechViet Japan Co., Ltd.',
    location: 'Shinjuku, Tokyo',
    salary: '¥350,000–500,000/tháng',
    type: 'full-time' as const,
    category: 'it' as const,
    tags: ['N2 trở lên', 'Full-time', 'Visa hỗ trợ'],
    japaneseLevel: 'N2',
    benefits: ['Visa sponsored', 'Bảo hiểm đầy đủ', 'Thưởng tháng 13', 'Remote 2 ngày/tuần'],
    description: 'Phát triển API và hệ thống backend cho các ứng dụng fintech. Công ty người Việt, môi trường quốc tế.',
    contact: 'Nộp CV qua website công ty',
  },
  {
    id: '3',
    title: 'Công nhân sản xuất linh kiện',
    titleJp: '製造スタッフ',
    company: 'Yamamoto Electronics',
    location: 'Nagoya, Aichi',
    salary: '¥220,000/tháng',
    type: 'full-time' as const,
    category: 'manufacturing' as const,
    tags: ['Không cần tiếng Nhật', 'Full-time', 'Ký túc xá'],
    japaneseLevel: 'Không cần',
    benefits: ['Ký túc xá giá rẻ', 'Bảo hiểm đầy đủ', 'OT được tính thêm', 'Xe đưa đón'],
    description: 'Lắp ráp linh kiện điện tử theo dây chuyền. Không yêu cầu tiếng Nhật, có phiên dịch người Việt.',
    contact: 'Liên hệ qua phái cử lao động',
  },
  {
    id: '4',
    title: 'Nhân viên cửa hàng tiện lợi',
    titleJp: 'コンビニスタッフ',
    company: 'FamilyMart (Chi nhánh Osaka)',
    location: 'Namba, Osaka',
    salary: '¥1,050/giờ',
    type: 'part-time' as const,
    category: 'service' as const,
    tags: ['N3 trở lên', 'Part-time', 'Ca linh hoạt'],
    japaneseLevel: 'N3',
    benefits: ['Ca làm linh hoạt', 'Giảm giá đồ ăn 15%', 'Gần tàu điện'],
    description: 'Thu ngân, sắp xếp hàng hóa và phục vụ khách hàng tại cửa hàng tiện lợi FamilyMart.',
    contact: 'Đến trực tiếp cửa hàng để nộp đơn',
  },
  {
    id: '5',
    title: 'Kỹ sư IT (Fresher)',
    titleJp: 'ITエンジニア（新卒・第二新卒）',
    company: 'Pasona Tech',
    location: 'Marunouchi, Tokyo',
    salary: '¥250,000/tháng',
    type: 'full-time' as const,
    category: 'it' as const,
    tags: ['N2 trở lên', 'Full-time', 'Đào tạo'],
    japaneseLevel: 'N2',
    benefits: ['Đào tạo từ đầu', 'Bảo hiểm đầy đủ', 'Hỗ trợ học tiếng Nhật'],
    description: 'Chương trình tuyển dụng cho kỹ sư IT mới ra trường hoặc dưới 3 năm kinh nghiệm. Được đào tạo bài bản.',
    contact: 'Ứng tuyển qua cổng thông tin tuyển dụng',
  },
  {
    id: '6',
    title: 'Nhân viên bán hàng thời trang',
    titleJp: 'アパレル販売スタッフ',
    company: 'UNIQLO Ginza',
    location: 'Ginza, Tokyo',
    salary: '¥1,150/giờ',
    type: 'part-time' as const,
    category: 'service' as const,
    tags: ['N3 trở lên', 'Part-time', 'Discount sản phẩm'],
    japaneseLevel: 'N3',
    benefits: ['Giảm giá 30% nhân viên', 'Đồng phục miễn phí', 'Ca linh hoạt'],
    description: 'Tư vấn và bán hàng thời trang tại cửa hàng UNIQLO Ginza. Môi trường chuyên nghiệp, nhiều cơ hội thăng tiến.',
    contact: 'Ứng tuyển qua website UNIQLO',
  },
];

export const WORKER_RIGHTS = [
  {
    title: 'Lương tối thiểu',
    description: 'Mức lương tối thiểu tại Tokyo là ¥1,113/giờ (2024). Không ai được phép trả thấp hơn mức này.',
    icon: 'cash',
  },
  {
    title: 'Giờ làm thêm (OT)',
    description: 'OT từ giờ thứ 9 trở đi được tính thêm 25%. OT ban đêm (22:00–5:00) tính thêm 50%.',
    icon: 'time',
  },
  {
    title: 'Bảo hiểm lao động',
    description: 'Nếu làm trên 20 giờ/tuần, chủ lao động phải đăng ký bảo hiểm thất nghiệp và tai nạn lao động.',
    icon: 'shield',
  },
  {
    title: 'Nghỉ phép năm',
    description: 'Sau 6 tháng làm việc liên tục, bạn có quyền được hưởng tối thiểu 10 ngày nghỉ phép có lương.',
    icon: 'calendar',
  },
];

export const JAPANESE_WORDS = [
  {
    word: '在留カード',
    reading: 'ざいりゅうカード',
    romaji: 'Zairyu Kaado',
    meaning: 'Thẻ cư trú',
    example: '在留カードを更新する必要があります。',
    exampleRomaji: 'Zairyu kaado wo koushin suru hitsuyou ga arimasu.',
    exampleMeaning: 'Tôi cần gia hạn thẻ cư trú.',
  },
  {
    word: 'お疲れ様です',
    reading: 'おつかれさまです',
    romaji: 'Otsukaresama desu',
    meaning: 'Cảm ơn vì sự nỗ lực / Bạn đã làm việc vất vả',
    example: '今日もお疲れ様です！',
    exampleRomaji: 'Kyou mo otsukaresama desu!',
    exampleMeaning: 'Hôm nay bạn cũng đã vất vả rồi!',
  },
  {
    word: '宜しくお願いします',
    reading: 'よろしくおねがいします',
    romaji: 'Yoroshiku onegaishimasu',
    meaning: 'Xin hãy giúp đỡ tôi / Rất vui được hợp tác',
    example: '初めまして、よろしくお願いします。',
    exampleRomaji: 'Hajimemashite, yoroshiku onegaishimasu.',
    exampleMeaning: 'Rất vui được làm quen, mong bạn chỉ giáo.',
  },
];

export const ESSENTIAL_PHRASES = [
  {
    category: 'Chào hỏi',
    phrases: [
      { jp: 'おはようございます', romaji: 'Ohayou gozaimasu', vn: 'Chào buổi sáng' },
      { jp: 'こんにちは', romaji: 'Konnichiwa', vn: 'Xin chào (ban ngày)' },
      { jp: 'こんばんは', romaji: 'Konbanwa', vn: 'Chào buổi tối' },
      { jp: 'ありがとうございます', romaji: 'Arigatou gozaimasu', vn: 'Cảm ơn bạn rất nhiều' },
      { jp: 'すみません', romaji: 'Sumimasen', vn: 'Xin lỗi / Xin phép' },
    ],
  },
  {
    category: 'Tại nơi làm việc',
    phrases: [
      { jp: 'よろしくお願いします', romaji: 'Yoroshiku onegaishimasu', vn: 'Rất vui được hợp tác' },
      { jp: 'お疲れ様です', romaji: 'Otsukaresama desu', vn: 'Bạn đã vất vả rồi' },
      { jp: 'ちょっと待ってください', romaji: 'Chotto matte kudasai', vn: 'Xin hãy đợi một chút' },
      { jp: 'わかりました', romaji: 'Wakarimashita', vn: 'Tôi hiểu rồi' },
      { jp: 'もう一度言ってください', romaji: 'Mou ichido itte kudasai', vn: 'Xin hãy nói lại một lần nữa' },
    ],
  },
  {
    category: 'Khẩn cấp',
    phrases: [
      { jp: '助けてください', romaji: 'Tasukete kudasai', vn: 'Xin hãy giúp tôi!' },
      { jp: '救急車を呼んでください', romaji: 'Kyuukyuusha wo yonde kudasai', vn: 'Xin gọi xe cấp cứu' },
      { jp: '病院に行きたいです', romaji: 'Byouin ni ikitai desu', vn: 'Tôi muốn đến bệnh viện' },
      { jp: '日本語がわかりません', romaji: 'Nihongo ga wakarimasen', vn: 'Tôi không hiểu tiếng Nhật' },
    ],
  },
  {
    category: 'Hàng ngày',
    phrases: [
      { jp: 'これはいくらですか？', romaji: 'Kore wa ikura desu ka?', vn: 'Cái này giá bao nhiêu?' },
      { jp: 'トイレはどこですか？', romaji: 'Toire wa doko desu ka?', vn: 'Nhà vệ sinh ở đâu?' },
      { jp: '〜はありますか？', romaji: '〜 wa arimasu ka?', vn: 'Có ... không?' },
      { jp: 'レシートをください', romaji: 'Reshiito wo kudasai', vn: 'Xin cho tôi hóa đơn' },
    ],
  },
];
