export const StorageKeys = {
  bookmarks: 'bookmarks_v1',
  guideChecklistProgress: 'guide_checklist_progress_v1',
  importantDates: 'important_dates_v1',
  dailyLifeRecentTopics: 'daily_life_recent_topics_v1',
  japaneseRecentCategories: 'japanese_recent_categories_v1',
  laborHelpChecklistProgress: 'labor_help_checklist_progress_v1',
  laborResources: 'labor_resources_v1',
  journeyChecklistProgress: 'journey_checklist_progress_v1',
  japaneseAudioPreferences: 'japanese_audio_preferences_v1',
  bjtProgress: 'bjt_progress_v1',
  studyReminderEnabled: 'study_reminder_enabled_v1',
  userProfile: 'user_profile_v1',
  userProfilePromptDismissed: 'user_profile_prompt_dismissed_v1',
} as const;
