import type { AdminGuide } from '../../types/content';

export const ADMIN_GUIDE_SEARCH_KEYWORDS: Record<string, string[]> = {
  'residence-card': [
    'gia han visa',
    'gia han thoi han luu tru',
    'visa renewal',
    'zairyu kikan koshin',
    'koshin visa',
    'isa renewal',
  ],
  'residence-card-validity': [
    'gia han the cu tru',
    'the cu tru het han',
    'zairyu card koshin',
    'card validity',
    'permanent resident card',
    'hsp2 card',
  ],
  'address-change': [
    'doi dia chi',
    'chuyen nha',
    'address change',
    'tennyu todoke',
    'tenshutsu todoke',
    'city hall',
    '14 days',
  ],
  'residence-card-info-change': [
    'doi ten the cu tru',
    'doi quoc tich',
    'name change',
    'zairyu card info change',
    'personal info change',
  ],
  'job-change-notification': [
    'doi viec',
    'nghi viec',
    'job change notification',
    'contract organization',
    'ten shoku',
    '14 days',
  ],
  'permission-activity-outside-status': [
    'lam them',
    'baito',
    'shikakugai',
    'part time permit',
    '28 gio',
    'student work permit',
  ],
  're-entry': [
    'tam roi nhat',
    'tai nhap canh',
    're entry',
    're-entry permit',
    'minashi sainyukoku',
    'sainyukoku',
  ],
  'spouse-notification': [
    'ly hon',
    'vo chong mat',
    'spouse notification',
    'divorce visa',
    'haigusha notification',
    '14 days',
  ],
  'bank-account': [
    'mo tai khoan',
    'bank account',
    'ginko koza',
    'yucho',
    'salary account',
    'hanko bank',
  ],
  remittance: [
    'gui tien',
    'chuyen tien',
    'remit',
    'wise',
    'sbi remit',
    'seven bank',
    'my number transfer',
  ],
  'visa-status-overview': [
    'cac loai visa',
    'status of residence',
    'zairyu shikaku',
    'visa types',
    'work restrictions',
  ],
  'ssw-training-worker-2027': [
    'ssw',
    'ssw 2027',
    'tokutei ginou',
    'ikusei shuro',
    'technical intern',
    'new system 2027',
  ],
  'first-7-days-in-japan': [
    '7 ngay dau',
    'first week',
    'moving in',
    'city hall',
    'setup checklist',
  ],
  'first-30-days-work-study-japan': [
    '30 ngay dau',
    'first month',
    'work study',
    'pay day',
    'commuter route',
  ],
  'first-90-days-in-japan': [
    '90 ngay dau',
    'first 90 days',
    'tax insurance',
    'probation',
    'setup review',
  ],
  'family-stay-invitation': [
    'moi nguoi than',
    'family visit',
    'invitation letter',
    'guarantee letter',
    'short stay family',
  ],
  'short-stay-relative-visit': [
    'visa tham than',
    'short stay',
    'tan ki taizai',
    'relative visit',
    'temporary visitor',
  ],
  'japan-policy-update-2026-foreign-residents': [
    'policy 2026',
    'foreign residents',
    'immigration policy',
    'visa policy',
    '2026 update',
  ],
  'japan-policy-2026-action-by-user-type': [
    'policy action',
    'what to do',
    'user type',
    'visa 2026',
    'action checklist',
  ],
  'visa-highlights-2026': [
    'visa highlights',
    '2026 highlights',
    'policy summary',
    'immigration update',
  ],
  'parents-elderly-relatives': [
    'moi cha me',
    'elderly parents',
    'parents visa',
    'medical stay',
    'humanitarian',
  ],
  'baby-born-in-japan': [
    'sinh con o nhat',
    'baby born',
    'newborn residence',
    'birth notification',
    'zairyu baby',
  ],
  'nursery-kindergarten-guide': [
    'hoikuen',
    'yochien',
    'nursery',
    'kindergarten',
    'giu tre',
  ],
  'divorce-custody-name-residence': [
    'ly hon',
    'divorce',
    'custody',
    'quyen nuoi con',
    'name change',
    'residence status',
  ],
  'renting-and-buying-home': [
    'thue nha',
    'mua nha',
    'rent',
    'chintai',
    'guarantor',
    'shikikin',
    'key money',
  ],
  'tax-year-end-adjustment-filing': [
    'nenmatsu chosei',
    'year end adjustment',
    'tax filing',
    'gensen choshu',
    'khai thue cong ty',
  ],
  'pension-exemption-refund': [
    'nenkin',
    'pension exemption',
    'lump sum withdrawal',
    'datta ichijikin',
    'mien giam nenkin',
  ],
  'banking-remittance-anti-fraud': [
    'bank fraud',
    'transfer scam',
    'furikome sagi',
    'unauthorized transfer',
    'anti fraud',
  ],
  'status-of-residence-change': [
    'doi visa',
    'change status',
    'zairyu shikaku henko',
    'visa change',
    'change of status',
  ],
  'moving-in-notification': [
    'chuyen den',
    'tennyu todoke',
    'address registration',
    'city hall',
    '14 days',
  ],
  'my-number-card': [
    'my number card',
    'kojin bango card',
    'maina',
    'digital certificate',
    'mynaportal',
  ],
  'daily-law-basics': [
    'luat co ban',
    'daily law',
    'rules in japan',
    'contract',
    'police',
  ],
  'hanko-inkan': [
    'hanko',
    'inkan',
    'con dau',
    'seal',
    'jitsuin',
    'ginko in',
  ],
  'unemployment-benefits': [
    'shitsugyo kyufu',
    'unemployment benefits',
    'hello work',
    'mat viec',
    'job seeker',
  ],
  'return-to-vietnam-checklist': [
    've viet nam',
    'leave japan',
    'moving out',
    'nenkin refund',
    'cancel utilities',
  ],
  'myna-portal-digital': [
    'myna portal',
    'maina portal',
    'digital government',
    'online procedures',
    'my number app',
  ],
  'school-enrollment-children': [
    'nhap hoc cho con',
    'school enrollment',
    'shogakko',
    'chugakko',
    'chuyen truong',
  ],
  'juminzei-local-tax': [
    'juminzei',
    'resident tax',
    'thue cu tru',
    'local tax',
    'nozei shomei',
  ],
  'garbage-sorting-rules': [
    'phan loai rac',
    'gomi',
    'garbage',
    'sodai gomi',
    'recycle',
  ],
  'workplace-accident-rousai': [
    'rousai',
    'work accident',
    'tai nan lao dong',
    'workers compensation',
    'labor injury',
  ],
  'marriage-procedures-japan': [
    'ket hon',
    'marriage',
    'konin todoke',
    'giay doc than',
    'marriage registration',
  ],
  'permanent-residency-eijuu': [
    'eijuu',
    'vinh tru',
    'permanent residency',
    '5 year visa',
    'eijuu shinsei',
  ],
  'highly-skilled-professional': [
    'hsp',
    'highly skilled',
    'koudo jinzai',
    'point visa',
    '70 points',
    '80 points',
  ],
  'ginou-jisshu-to-tokutei-ginou': [
    'tts sang ssw',
    'ginou jisshu',
    'tokutei ginou',
    'ssw',
    'transfer ssw',
  ],
  'tokutei-katsudo-46-job-hunt': [
    'job hunt visa',
    'tokutei katsudo',
    'xin viec sau tot nghiep',
    'after graduation',
    'shushoku katsudo',
  ],
  'home-purchase-mortgage': [
    'mua nha',
    'vay mua nha',
    'mortgage',
    'jutaku loan',
    'home loan',
  ],
  'sole-proprietor-kojin-jigyo': [
    'kojin jigyo',
    'ca nhan kinh doanh',
    'sole proprietor',
    'blue return',
    'kaigyo todoke',
  ],
  'credit-card-for-foreigners': [
    'credit card',
    'the tin dung',
    'shinsa',
    'credit history',
    'rakuten card',
  ],
  'childcare-parental-leave': [
    'ikukyu',
    'childcare leave',
    'parental leave',
    'nghi nuoi con',
    'kyufu',
  ],
  'special-fraud-tokushu-sagi': [
    'tokushu sagi',
    'fraud',
    'lua dao',
    'scam',
    'suspicious call',
  ],
  'kakutei-shinkoku': [
    'kakutei shinkoku',
    'tax return',
    'khai thue',
    'final tax return',
    'e-tax',
  ],
  'payslip-reading': [
    'payslip',
    'kyuyo meisai',
    'bang luong',
    'salary slip',
    'deductions',
  ],
  'labor-rights-dispute': [
    'tranh chap lao dong',
    'labor dispute',
    'unpaid wage',
    'no luong',
    'overtime',
    'roudou',
  ],
  'naturalization-kika': [
    'kika',
    'nhap tich',
    'naturalization',
    'japanese citizenship',
    'kokuseki',
  ],
  'nisa-investment': [
    'nisa',
    'dau tu',
    'tsumitate',
    'investment',
    'tax free investment',
  ],
  'marriage-certificate-vn-japan': [
    'giay ket hon',
    'marriage certificate',
    'vietnam japan marriage',
    'consulate',
    'legalization',
  ],
};

export function getAdminGuideSearchKeywords(guide: Pick<AdminGuide, 'id' | 'searchKeywords'>) {
  return Array.from(
    new Set([
      ...(guide.searchKeywords ?? []),
      ...(ADMIN_GUIDE_SEARCH_KEYWORDS[guide.id] ?? []),
    ])
  );
}
