import type { ContentMetadata, DailyLifeTopic } from '../../types/content';

export const DAILY_LIFE_CONTENT_META: ContentMetadata = {
  lastUpdated: '2026-04-10',
  sources: [
    { label: '総務省', url: 'https://www.soumu.go.jp/' },
    { label: '国民生活センター', url: 'https://www.kokusen.go.jp/' },
    { label: '厚生労働省', url: 'https://www.mhlw.go.jp/' },
  ],
};

export const DAILY_LIFE_TOPICS: DailyLifeTopic[] = [
  {
    id: 'apartment',
    title: 'Thuê nhà / Căn hộ',
    titleJp: '賃貸住宅',
    icon: 'home',
    color: '#185FA5',
    description: 'Quy trình, phí ban đầu và lưu ý khi thuê nhà ở Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về thuê nhà ở Nhật Bản. Hãy tư vấn chi tiết hơn về quy trình, các loại phí, và kinh nghiệm thực tế.',
    sections: [
      {
        title: 'Các loại phí ban đầu cần biết',
        content: 'Khi thuê nhà ở Nhật, bạn thường phải trả một lúc nhiều khoản phí ngoài tiền thuê tháng đầu.',
        items: [
          '敷金 (Shikikin) — Tiền đặt cọc: thường 1–2 tháng tiền thuê, hoàn lại khi trả nhà (trừ tiền sửa chữa nếu có)',
          '礼金 (Reikin) — Tiền lễ/cảm ơn: 0–2 tháng, KHÔNG hoàn lại. Nhiều nhà mới không còn yêu cầu khoản này',
          '仲介手数料 (Chuukai tesuuryou) — Phí môi giới: thường 1 tháng tiền thuê + thuế 10%',
          '前家賃 (Mae yachin) — Tiền thuê tháng đầu (tháng tiếp theo)',
          'Tổng cộng ban đầu thường = 4–6 tháng tiền thuê',
        ],
        tip: 'Tìm nhà ghi "敷金・礼金ゼロ" (0 đặt cọc, 0 tiền lễ) để tiết kiệm chi phí ban đầu',
      },
      {
        title: 'Tìm nhà ở đâu',
        content: 'Các trang web tìm nhà phổ biến nhất tại Nhật Bản:',
        items: [
          'SUUMO (suumo.jp) — Lớn nhất Nhật, nhiều lựa chọn nhất',
          'AtHome (athome.co.jp) — Nhiều nhà giá rẻ',
          'Chintai (chintai.net) — Phổ biến với sinh viên và người đi làm',
          'UR賃貸 (ur-net.go.jp) — Nhà công của chính phủ, không cần bảo lãnh, không tiền lễ',
          'Sakura House / Leo Palace — Chuyên cho người nước ngoài, thủ tục đơn giản hơn',
        ],
        tip: 'UR賃貸 (nhà chính phủ) là lựa chọn tốt nhất cho người nước ngoài: không cần 保証人 (người bảo lãnh), không 礼金, thủ tục đơn giản',
      },
      {
        title: 'Giấy tờ cần chuẩn bị',
        content: 'Chủ nhà Nhật thường yêu cầu nhiều giấy tờ để xét duyệt hợp đồng thuê nhà.',
        items: [
          'Thẻ cư trú (在留カード) — bắt buộc',
          'Hộ chiếu',
          'Giấy chứng minh thu nhập: hợp đồng lao động, phiếu lương, hoặc giấy xác nhận từ công ty',
          '住民票 (Juuminhyou) — bản sao hộ khẩu từ UBND phường',
          '保証人 (Hoshounin) — người bảo lãnh (thường là người Nhật hoặc công ty bảo lãnh 保証会社)',
          'Con dấu cá nhân (印鑑) — nếu có',
        ],
        tip: 'Nếu không có người bảo lãnh Nhật, hãy dùng dịch vụ 保証会社 (công ty bảo lãnh). Phí khoảng 0.5–1 tháng tiền thuê/năm',
      },
      {
        title: 'Lưu ý quan trọng khi ở thuê',
        content: 'Những điều cần tuân thủ để tránh mất tiền đặt cọc và giữ quan hệ tốt với chủ nhà:',
        items: [
          'Phân loại rác đúng quy định của khu vực (xem mục Phân loại rác)',
          'Không tự ý đóng đinh hoặc sửa chữa nhà — cần xin phép chủ nhà',
          'Không nuôi thú cưng trừ khi hợp đồng cho phép (ペット可)',
          'Thông báo trước khi chuyển đi ít nhất 1 tháng (thường ghi trong hợp đồng)',
          'Chụp ảnh toàn bộ căn phòng ngay khi dọn vào làm bằng chứng tình trạng ban đầu',
        ],
        tip: 'Khi trả nhà, chủ nhà sẽ kiểm tra và trừ vào tiền đặt cọc các hư hỏng do bạn gây ra (ngoài hao mòn tự nhiên)',
      },
    ],
  },
  {
    id: 'trash',
    title: 'Phân loại rác',
    titleJp: 'ゴミの分別',
    icon: 'trash',
    color: '#27AE60',
    description: 'Hướng dẫn phân loại và bỏ rác đúng quy định tại Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về phân loại rác ở Nhật. Khu vực tôi đang ở có quy định đặc biệt gì không?',
    sections: [
      {
        title: '4 loại rác chính',
        content: 'Nhật Bản phân loại rác rất nghiêm ngặt. Bỏ sai loại hoặc sai ngày có thể bị phạt hoặc không được thu.',
        items: [
          '燃えるゴミ (Moeru gomi) — Rác đốt được: thức ăn thừa, giấy bẩn, quần áo cũ, cao su nhỏ. Thu 2–3 lần/tuần',
          '燃えないゴミ (Moenai gomi) — Rác không đốt được: đồ sứ, kính vỡ, đồ kim loại nhỏ. Thu 1–2 lần/tháng',
          '資源ゴミ (Shigen gomi) — Rác tái chế: chai nhựa PET, lon nhôm, thủy tinh, báo/hộp giấy. Thu 1 lần/tuần',
          '粗大ゴミ (Sodai gomi) — Đồ cồng kềnh: đồ nội thất, xe đạp, TV... Phải đặt lịch và mua tem trả phí trước',
        ],
        tip: 'Quy định chi tiết khác nhau theo từng quận/thành phố. Lấy lịch thu rác (ゴミカレンダー) tại UBND phường hoặc hỏi chủ nhà',
      },
      {
        title: 'Quy tắc bỏ rác',
        content: 'Tuân thủ đúng để tránh bị hàng xóm và ban quản lý khu phố nhắc nhở:',
        items: [
          'Bỏ rác đúng ngày quy định — không bỏ trước đêm hôm trước (trừ một số nơi cho phép sau 20:00)',
          'Đặt rác tại điểm tập kết (ゴミ集積所) của khu nhà, không bỏ bừa',
          'Chai nhựa PET: tháo nắp và nhãn ra riêng trước khi bỏ',
          'Lon và hộp: xả sạch, không để thức ăn thừa bên trong',
          'Báo và hộp giấy: buộc dây gọn gàng',
          'Pin và pin điện thoại: bỏ tại hộp thu pin ở siêu thị hoặc UBND — KHÔNG bỏ chung rác thường',
        ],
        tip: 'Vi phạm quy định rác có thể bị cảnh cáo bằng thư từ ban quản lý khu phố (自治会) và ảnh hưởng đến quan hệ với chủ nhà',
      },
      {
        title: 'Bỏ đồ cồng kềnh (粗大ゴミ)',
        content: 'Không thể tự bỏ như rác thường — phải đăng ký và trả phí:',
        items: [
          'Gọi điện hoặc đăng ký online cho dịch vụ thu gom 粗大ゴミ của thành phố',
          'Mua tem trả phí (粗大ごみ処理券) tại convenience store theo mức phí được thông báo',
          'Dán tem lên đồ vật và đặt tại điểm quy định vào ngày hẹn',
          'Phí tùy theo kích thước: ghế sofa ~400–2,000円, tủ lạnh ~1,000–3,000円',
        ],
        tip: 'Nhiều khu nhà có "Free Corner" — góc để đồ cũ còn dùng được cho người khác lấy miễn phí. Hãy tận dụng!',
      },
    ],
  },
  {
    id: 'transportation',
    title: 'Giao thông / Suica & Pasmo',
    titleJp: '交通・Suica/Pasmo',
    icon: 'train',
    color: '#E74C3C',
    description: 'Cách dùng tàu điện, thẻ IC và ứng dụng tra cứu tuyến đường',
    prefilledQuestion: 'Tôi muốn hỏi thêm về giao thông tại Nhật. Tuyến đường từ chỗ tôi đến nơi làm việc thì đi như thế nào?',
    sections: [
      {
        title: 'Suica và Pasmo — Thẻ IC card',
        content: 'Suica (JR East) và Pasmo (Metro/tư nhân) đều là thẻ IC dùng để đi tàu điện, bus và thanh toán tại cửa hàng. Hai thẻ có thể dùng thay thế nhau trên toàn quốc.',
        items: [
          'Mua tại máy tự động ở ga (vending machine): đặt cọc 500円 cho thẻ vật lý',
          'Nạp tiền (チャージ): tại máy tự động ở ga, ATM Seven Bank, hoặc convenience store',
          'Dùng để đi tàu, bus, taxi (một số), và mua đồ tại convenience store, siêu thị, máy bán hàng tự động',
          'Suica/Pasmo trên iPhone/Android: không cần thẻ vật lý, thêm vào Apple Wallet hoặc Google Pay',
          'Tiền trong thẻ không hết hạn — nhưng thẻ không dùng trong 10 năm sẽ bị xóa số dư',
        ],
        tip: 'Dùng Suica/Pasmo trên điện thoại tiện hơn thẻ vật lý: không cần lấy ra, chỉ cần chạm điện thoại vào cổng',
      },
      {
        title: 'Cách đi tàu điện',
        content: 'Hệ thống tàu điện Nhật rất đúng giờ và phức tạp. Sau vài lần đi sẽ quen:',
        items: [
          'Chạm thẻ IC vào cổng khi vào ga (入場) và ra ga (出場) — tự động trừ tiền',
          'Nếu số dư không đủ: dùng máy "精算機" (seisanki) tại cổng ra để nạp thêm',
          'Đứng đúng vạch chờ trên sàn (hàng thẳng, không chen lấn)',
          'Không nói chuyện điện thoại trong toa — gọi điện phải ra phần nối toa',
          'Ưu tiên ghế dành riêng (優先席) cho người cao tuổi, phụ nữ mang thai, người khuyết tật',
          'Toa phụ nữ (女性専用車両): chỉ dành cho phụ nữ vào giờ cao điểm sáng',
        ],
        tip: 'App tra tuyến đường tốt nhất: Yahoo!乗換案内 hoặc Google Maps. Nhập ga đi và ga đến → app chỉ tuyến, thời gian, giá vé',
      },
      {
        title: 'Di chuyển bằng xe đạp',
        content: 'Xe đạp rất phổ biến tại Nhật và tiện cho quãng đường ngắn:',
        items: [
          'Phải đăng ký xe đạp tại UBND phường (防犯登録) — phí ~500円, tránh bị nghi ngờ trộm cắp',
          'Đi trên đường dành cho xe đạp hoặc lề đường — không đi trên vỉa hè (trừ nơi có biển cho phép)',
          'Bắt buộc bật đèn vào ban đêm',
          'Dắt bộ xe đạp trên vỉa hè thay vì đạp',
          'Đỗ xe đúng bãi quy định — xe đỗ bừa sẽ bị tịch thu (phí lấy lại ~2,500円)',
        ],
        tip: 'Share bike (シェアサイクル) như docomo bike, HELLO CYCLING tiện nếu chỉ cần xe ngắn hạn. Giá từ ~165円/30 phút',
      },
    ],
  },
  {
    id: 'grocery',
    title: 'Mua sắm thực phẩm',
    titleJp: '食料品の買い物',
    icon: 'basket',
    color: '#F39C12',
    description: 'Siêu thị, giờ giảm giá và mẹo tiết kiệm khi mua đồ ăn tại Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về mua sắm thực phẩm tại Nhật. Tìm nguyên liệu nấu ăn Việt Nam ở đâu?',
    sections: [
      {
        title: 'Các chuỗi siêu thị phổ biến',
        content: 'Nhật có nhiều chuỗi siêu thị với mức giá và đặc điểm khác nhau:',
        items: [
          'AEON / イオン — Chuỗi lớn nhất, giá trung bình, nhiều chi nhánh, có AEON app tích điểm',
          'OK Supermarket — Rẻ nhất trong các siêu thị thông thường, không lấy túi',
          '業務スーパー (Gyomu Super) — Bán buôn số lượng lớn, giá rẻ — lý tưởng cho gia đình',
          'Costco — Rẻ nếu mua số lượng lớn, cần thẻ thành viên (~4,400円/năm)',
          'コンビニ (Convenience store) — 7-Eleven, FamilyMart, Lawson: tiện nhưng đắt hơn ~20–30%',
        ],
        tip: '業務スーパー là lựa chọn tiết kiệm nhất cho người Việt — bán nhiều thực phẩm đông lạnh và gia vị châu Á với giá rẻ',
      },
      {
        title: 'Mẹo mua đồ giảm giá',
        content: 'Siêu thị Nhật thường dán nhãn giảm giá (値引き) vào cuối ngày:',
        items: [
          '夕方割引 (Yuugata waribiki) — Giảm giá chiều tối: đồ sashimi, cơm hộp, bánh... giảm 20–50% sau 19:00–20:00',
          'Dấu hiệu nhận biết: nhãn màu vàng/đỏ dán đè lên giá gốc',
          'Rau củ và trái cây theo mùa (旬) rẻ hơn 30–50% so với trái vụ',
          'Thịt và cá gần hết hạn (当日中 hoặc 本日中) thường được giảm thêm',
          'Đăng ký app của siêu thị để nhận coupon và điểm thưởng',
        ],
        tip: 'Đến siêu thị vào 19:30–20:30 để săn đồ giảm giá tốt nhất. Tuy nhiên lựa chọn sẽ ít hơn',
      },
      {
        title: 'Tìm thực phẩm Việt Nam',
        content: 'Nguyên liệu nấu ăn Việt Nam có thể tìm tại:',
        items: [
          'Cửa hàng Việt Nam / châu Á: tìm trên Google Maps với từ khóa "ベトナム食材" hoặc "アジア食材"',
          'Khu Shin-Okubo (Tokyo), Tsuruhashi (Osaka) — khu phố châu Á có nhiều cửa hàng',
          'Don Quijote (ドン・キホーテ) — có khu thực phẩm châu Á',
          'Kaldiコーヒーファーム — Thực phẩm nhập khẩu từ nhiều nước',
          'Amazon.co.jp / Rakuten — Đặt online nhiều loại gia vị Việt Nam',
        ],
        tip: 'Nước mắm, bún, phở, tương hoisin... ngày càng có nhiều ở siêu thị AEON lớn (khu Nhật Bản有名な thực phẩm nước ngoài)',
      },
      {
        title: 'Đọc nhãn hàng tiếng Nhật',
        content: 'Những ký hiệu quan trọng cần biết:',
        items: [
          '賞味期限 (Shoumi kigen) — Hạn dùng tốt nhất: đồ đóng gói, có thể dùng sau ngày này nhưng chất lượng giảm',
          '消費期限 (Shouhi kigen) — Hạn sử dụng: đồ tươi sống, KHÔNG dùng sau ngày này',
          '原材料名 (Genざいりょうめい) — Danh sách thành phần',
          'アレルギー (Arerugii) — Thông tin dị ứng',
          '国産 (Kokusan) — Sản xuất trong nước Nhật',
          '有機 (Yuuki) / オーガニック — Hữu cơ',
        ],
        tip: 'Dùng app Google Translate chụp ảnh nhãn hàng để dịch nhanh khi không hiểu',
      },
    ],
  },
  {
    id: 'banking',
    title: 'Ngân hàng & Chuyển tiền',
    titleJp: '銀行・送金',
    icon: 'cash',
    color: '#9B59B6',
    description: 'Mở tài khoản và chuyển tiền về Việt Nam — xem thêm trong mục Thủ tục hành chính',
    prefilledQuestion: 'Tôi muốn hỏi thêm về ngân hàng và chuyển tiền tại Nhật. Hãy tư vấn chi tiết hơn.',
    sections: [
      {
        title: 'Hướng dẫn chi tiết',
        content: 'Mục này đã được hướng dẫn đầy đủ trong phần Thủ tục hành chính:',
        items: [
          '→ Mở tài khoản ngân hàng: xem "Mở tài khoản ngân hàng" trong tab Thủ tục',
          '→ Chuyển tiền về Việt Nam: xem "Chuyển tiền về Việt Nam" trong tab Thủ tục',
          'Cả hai hướng dẫn có đầy đủ giấy tờ, quy trình và link nguồn chính thức',
        ],
        tip: 'Vào tab Thủ tục → tìm kiếm "ngân hàng" hoặc "chuyển tiền" để xem hướng dẫn chi tiết',
      },
    ],
  },
  {
    id: 'hospital',
    title: 'Khám bệnh / Bệnh viện',
    titleJp: '病院・医療',
    icon: 'medical',
    color: '#E74C3C',
    description: 'Quy trình khám bệnh, chi phí và cách dùng bảo hiểm y tế tại Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về khám bệnh tại Nhật. Triệu chứng của tôi là... Tôi nên đến khoa nào?',
    sections: [
      {
        title: 'Trước khi đi khám',
        content: 'Hệ thống y tế Nhật chia làm 2 cấp: phòng khám nhỏ (クリニック/診療所) và bệnh viện lớn (病院). Nên đến phòng khám nhỏ trước — nhanh hơn, rẻ hơn, không cần đặt lịch trước (thường).',
        items: [
          'Mang theo: thẻ bảo hiểm y tế (健康保険証 hoặc マイナ保険証), thẻ cư trú',
          'Nếu có My Number Card đã liên kết bảo hiểm → dùng thay thẻ bảo hiểm',
          'Đăng ký (受付) tại quầy: điền tên, ngày sinh, triệu chứng',
          'Chờ được gọi tên — thường chờ 30 phút đến vài tiếng tại bệnh viện lớn',
          'Sau khám: nhận đơn thuốc (処方箋) và mang đến nhà thuốc (薬局) gần đó lấy thuốc',
        ],
        tip: 'Nhà thuốc (薬局) thường nằm ngay cạnh phòng khám. Mang đơn thuốc đến lấy — cũng dùng thẻ bảo hiểm để giảm chi phí',
      },
      {
        title: 'Chi phí và bảo hiểm',
        content: 'Với thẻ bảo hiểm y tế quốc gia (国民健康保険), bạn chỉ trả 30% chi phí:',
        items: [
          'Khám thông thường: tự trả ~500–3,000円 (đã trừ 70% bảo hiểm)',
          'Khám chuyên khoa tại bệnh viện lớn lần đầu: thêm phí 紹介状なし (~5,000–7,700円)',
          'Thuốc: tự trả 30% giá thuốc',
          'Nếu chưa có thẻ bảo hiểm: trả 100% — rất đắt, hãy đăng ký bảo hiểm ngay',
          '高額療養費制度 (Kougaku ryouyouhi): nếu chi phí vượt ngưỡng (~80,100円/tháng), phần vượt được hoàn lại',
        ],
        tip: 'Khi đi cấp cứu (救急), gọi 119. Xe cứu thương và cấp cứu MIỄN PHÍ tại Nhật — không lo về tiền khi cần',
      },
      {
        title: 'Tìm bác sĩ và phòng khám',
        content: 'Cách tìm cơ sở y tế phù hợp:',
        items: [
          'Google Maps: tìm "内科クリニック" (nội khoa), "歯科" (nha khoa), "皮膚科" (da liễu)...',
          'AMDA Đa ngôn ngữ: 03-6233-9266 — tư vấn bằng tiếng Việt, giới thiệu cơ sở y tế',
          'Himawari (Tokyo): 03-5285-8181 — hỗ trợ người nước ngoài tìm bác sĩ',
          'Mimi.care / Mediphone — app đặt lịch khám có hỗ trợ tiếng Anh',
          'Tìm "ベトナム語対応" hoặc "外国語対応" để tìm nơi có phiên dịch/hỗ trợ tiếng nước ngoài',
        ],
        tip: 'Đường dây hỗ trợ y tế khẩn cấp đa ngôn ngữ (có tiếng Việt): #7119 (tư vấn có nên gọi cấp cứu không)',
      },
    ],
  },
  {
    id: 'tax',
    title: 'Khai thuế thu nhập',
    titleJp: '確定申告',
    icon: 'receipt',
    color: '#D35400',
    description: 'Ai cần khai thuế, thời hạn, cách hoàn thuế và khai online',
    prefilledQuestion: 'Tôi muốn hỏi thêm về khai thuế tại Nhật. Thu nhập của tôi là... Tôi có cần tự khai không?',
    sections: [
      {
        title: 'Ai cần tự khai thuế?',
        content: 'Không phải ai cũng phải tự làm 確定申告 — phụ thuộc vào tình huống của bạn:',
        items: [
          'KHÔNG cần tự khai nếu: chỉ có 1 nơi làm việc và công ty đã làm 年末調整 (quyết toán thuế cuối năm) cho bạn',
          'CẦN tự khai nếu: làm thêm tại 2 nơi trở lên, thu nhập ngoài lương (freelance, bất động sản...) trên 200,000円/năm',
          'NÊN tự khai để hoàn thuế nếu: thay đổi công việc giữa năm, trả tiền học/y tế lớn, đóng tiền furusato nozei',
          'Người nước ngoài mới đến Nhật năm đó cũng có thể cần khai',
        ],
        tip: 'Nếu không chắc, hỏi bộ phận kế toán/nhân sự tại công ty — họ sẽ cho biết công ty có làm 年末調整 cho bạn không',
      },
      {
        title: 'Thời hạn và quy trình',
        content: 'Khai thuế cho năm trước (ví dụ: thu nhập 2024 → khai năm 2025):',
        items: [
          'Thời hạn: 16/02 – 15/03 hàng năm tại cục thuế (税務署)',
          'Khai online qua e-Tax (etax.nta.go.jp) — tiện nhất, có thể làm từ nhà',
          'Khai trực tiếp tại cục thuế: mang theo thẻ cư trú, My Number, giấy tờ thu nhập (源泉徴収票)',
          'Nguồn收 票 (Gensen choushuuhyou): phiếu tóm tắt thu nhập và thuế đã khấu trừ — nhận từ công ty vào tháng 1–2',
          'Cục thuế thường có nhân viên tư vấn miễn phí trong mùa khai thuế',
        ],
        tip: 'e-Tax với My Number Card là cách dễ nhất — điền thông tin online, ký số bằng thẻ, nộp điện tử. Hoàn thuế về tài khoản trong 3–6 tuần',
      },
      {
        title: 'Các khoản được giảm trừ',
        content: 'Những khoản có thể giảm thuế phải nộp hoặc được hoàn thuế thêm:',
        items: [
          '医療費控除 (Iryouhi koujo): chi phí y tế trong năm vượt 100,000円 — phần vượt được giảm trừ',
          'ふるさと納税 (Furusato nozei): đóng thuế cho địa phương khác, nhận quà tặng đặc sản, giảm thuế sau',
          '住宅ローン控除: lãi suất vay mua nhà',
          '扶養控除: có người phụ thuộc (cha mẹ ở Việt Nam cũng có thể tính nếu gửi tiền về hàng tháng)',
          '基礎控除 (Kiso koujo): 480,000円 miễn thuế cơ bản áp dụng cho tất cả',
        ],
        tip: 'Nếu gửi tiền về nuôi cha mẹ ở Việt Nam, có thể khai 扶養控除 (phụ thuộc quốc tế) — cần giấy tờ chứng minh quan hệ và chứng minh gửi tiền',
      },
    ],
  },
  {
    id: 'utilities',
    title: 'Điện, nước, internet',
    titleJp: '電気・水道・インターネット',
    icon: 'flash',
    color: '#F39C12',
    description: 'Đăng ký và quản lý điện, nước, gas, internet khi ở Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về đăng ký điện nước internet tại Nhật. Nhà cung cấp nào phù hợp với khu vực tôi đang ở?',
    sections: [
      {
        title: 'Đăng ký điện, nước, gas',
        content: 'Khi chuyển vào nhà mới, cần liên hệ nhà cung cấp để bật dịch vụ (thường kế thừa từ người thuê trước):',
        items: [
          'Điện (電気): liên hệ công ty điện khu vực (Tokyo Electric — TEPCO, Kansai Electric — KEPCO...). Đăng ký online hoặc qua điện thoại, cần số đồng hồ điện',
          'Nước (水道): liên hệ cục cấp nước thành phố (水道局). Thường đăng ký tại UBND phường',
          'Gas (ガス): liên hệ Tokyo Gas, Osaka Gas hoặc Toho Gas. Bắt buộc có nhân viên đến mở van — đặt lịch trước',
          'Tất cả có thể đăng ký online hoặc qua điện thoại. Nhiều công ty có hỗ trợ tiếng Anh',
          'Thanh toán: đăng ký 口座振替 (tự động trừ tài khoản) để không bị cắt điện/nước do quên nộp',
        ],
        tip: 'Đối với gas: bắt buộc phải có nhân viên đến kiểm tra và mở van lần đầu — đặt lịch sớm, có thể phải đợi vài ngày',
      },
      {
        title: 'Đăng ký internet',
        content: 'Có 2 loại internet phổ biến: cáp quang (光回線) tốc độ cao và home router (ポケットWi-Fi) tiện nhưng chậm hơn:',
        items: [
          'Cáp quang (光): NTT Flet\'s, SoftBank Hikari, auひかり — tốc độ 1Gbps, giá ~4,000–6,000円/tháng. Lắp đặt mất 1–4 tuần',
          'Home router (ホームルーター): docomo home 5G, Soft Bank Air — cắm là dùng ngay, ~4,000–5,000円/tháng. Không cần lắp đặt',
          'Pocket Wi-Fi: thiết bị di động mang theo người — phù hợp khi mới đến, giá ~2,000–3,500円/tháng',
          'Nhiều nhà cho thuê đã có internet sẵn (光インターネット無料) — kiểm tra hợp đồng thuê nhà',
        ],
        tip: 'Nếu mới đến Nhật: dùng Pocket Wi-Fi hoặc SIM data trước khi lắp cáp quang. Cáp quang nhanh và ổn định hơn nhưng phải đợi lắp đặt',
      },
      {
        title: 'Chi phí tiện ích trung bình',
        content: 'Ước tính chi phí hàng tháng cho 1 người (1K/1R):',
        items: [
          'Điện: ~3,000–6,000円/tháng (mùa hè dùng điều hòa nhiều hơn)',
          'Nước: ~1,000–2,000円/tháng (thường thu 2 tháng/lần)',
          'Gas: ~2,000–4,000円/tháng (mùa đông cao hơn)',
          'Internet cáp quang: ~4,000–6,000円/tháng',
          'Tổng: khoảng 10,000–18,000円/tháng',
        ],
        tip: 'Mùa hè (7–9) và mùa đông (12–2) tiền điện tăng mạnh do dùng điều hòa/sưởi. Đặt nhiệt độ 28°C mùa hè, 20°C mùa đông để tiết kiệm',
      },
    ],
  },
  {
    id: 'earthquake',
    title: 'Động đất & Thảm họa',
    titleJp: '地震・災害対策',
    icon: 'warning',
    color: '#C0392B',
    description: 'Cách ứng phó động đất, chuẩn bị túi khẩn cấp và tìm điểm sơ tán',
    prefilledQuestion: 'Tôi muốn hỏi thêm về ứng phó thảm họa tại Nhật. Khu vực tôi đang ở có nguy cơ đặc biệt gì không?',
    sections: [
      {
        title: 'Thang độ rung động đất Nhật (震度)',
        content: 'Nhật dùng thang 震度 (shindo) từ 0–7 để đánh giá mức độ rung tại nơi bạn đứng:',
        items: [
          '震度1–2: Rung nhẹ, chỉ người đứng yên mới cảm thấy → Bình thường, không cần làm gì',
          '震度3: Rung rõ, đồ vật lắc nhẹ → Chú ý, không cần sơ tán',
          '震度4: Rung mạnh, đồ vật đổ → Tránh xa cửa sổ, ẩn dưới bàn',
          '震度5弱–5強: Đứng khó vững, đồ nặng đổ, tủ có thể ngã → Chui xuống bàn, tắt bếp gas',
          '震度6弱–6強: Không thể đứng được, tường nứt, kính vỡ → Nằm sấp, bảo vệ đầu',
          '震度7: Cực mạnh, nhà có thể sụp → Thoát khỏi tòa nhà ngay khi an toàn',
        ],
        tip: 'App NHK World và Yahoo!防災 gửi cảnh báo động đất trước vài giây (緊急地震速報). Cài sẵn và bật thông báo',
      },
      {
        title: 'Việc cần làm ngay khi động đất',
        content: 'Phản xạ đúng trong vài giây đầu có thể cứu sống bạn:',
        items: [
          'Trong nhà: chui ngay dưới bàn chắc chắn, ôm đầu. Không chạy ra ngoài khi đang rung',
          'Trong bếp: tắt gas ngay lập tức nếu an toàn (hoặc tắt sau khi hết rung)',
          'Mở cửa thoát hiểm: động đất mạnh có thể làm cong khung cửa, mở cửa trước khi kẹt',
          'Ngoài đường: tránh xa tòa nhà, cột điện, biển quảng cáo. Di chuyển ra nơi trống',
          'Trong siêu thị/mall: cúi thấp, bảo vệ đầu bằng túi/tay, tránh xa kệ hàng',
          'Sau khi hết rung: kiểm tra gas, kiểm tra cầu dao điện, chú ý dư chấn',
        ],
        tip: 'Sau động đất lớn: KHÔNG dùng thang máy. Dùng cầu thang bộ để thoát nếu cần sơ tán',
      },
      {
        title: 'Túi khẩn cấp (非常用持ち出し袋)',
        content: 'Chuẩn bị sẵn túi để lấy ngay khi cần sơ tán (trong vòng 3 phút):',
        items: [
          'Nước uống: 500ml/người × ít nhất 3 ngày',
          'Thức ăn khô: bánh quy, cơm sấy khô, đồ hộp cho 3 ngày',
          'Giấy tờ tùy thân: bản sao hộ chiếu, thẻ cư trú, thẻ bảo hiểm (để trong túi chống nước)',
          'Tiền mặt: ít nhất 10,000–20,000円 (ATM có thể không hoạt động)',
          'Đèn pin + pin dự phòng điện thoại (sạc đầy)',
          'Áo mưa, băng gạc sơ cứu, thuốc thường dùng',
        ],
        tip: 'Tìm điểm sơ tán (避難場所) gần nhà trước — thường là trường học, công viên lớn. Xem bản đồ tại website UBND phường',
      },
    ],
  },
  {
    id: 'post-office',
    title: 'Bưu điện & Giao hàng',
    titleJp: '郵便局・宅配便',
    icon: 'mail',
    color: '#2980B9',
    description: 'Nhận bưu phẩm, gửi hàng và dịch vụ giao hàng tại Nhật',
    prefilledQuestion: 'Tôi muốn hỏi thêm về gửi hàng về Việt Nam từ Nhật. Dịch vụ nào rẻ và an toàn nhất?',
    sections: [
      {
        title: 'Khi nhận được phiếu "không có nhà" (不在票)',
        content: 'Đây là tình huống rất thường gặp — shipper đến giao lúc bạn không ở nhà:',
        items: [
          'Trên phiếu (不在票) ghi rõ: tên công ty giao hàng, ngày đến, số điện thoại để liên hệ',
          'Yamato (クロネコヤマト): gọi 0123-01-9625 hoặc đặt lại tại kuronekoyamato.co.jp',
          'Sagawa (佐川急便): đặt lại tại sagawa-exp.co.jp hoặc qua app e飛伝',
          'Japan Post (日本郵便): gọi 0800-0800-111 hoặc đặt tại japanpost.jp',
          'Hầu hết cho phép chọn lại ngày, khung giờ (sáng/chiều/tối), hoặc đến bưu cục/depot lấy',
          'Thời hạn giữ hàng: thường 7 ngày (Japan Post), 14 ngày (Yamato, Sagawa)',
        ],
        tip: 'Tải app của từng công ty giao hàng để quản lý đơn hàng và đặt lại lịch giao tiện hơn qua điện thoại',
      },
      {
        title: '3 công ty giao hàng lớn nhất',
        content: 'So sánh nhanh để biết đơn hàng của bạn đang ở đâu:',
        items: [
          'Yamato Transport (ヤマト運輸 / クロネコ): nhận dạng bằng logo mèo đen. Phổ biến nhất, giao nhanh, có dịch vụ giao cùng ngày',
          'Sagawa Express (佐川急便): giá rẻ hơn một chút, nhiều doanh nghiệp dùng. Nhận dạng logo chim bay',
          'Japan Post (日本郵便 / ゆうパック): của nhà nước, giao đến mọi địa chỉ kể cả vùng hẻo lánh. Tích hợp với bưu cục',
        ],
        tip: 'Khi mua hàng trên Amazon Nhật: chọn "置き配" (để trước cửa) nếu thường xuyên không có nhà — hàng sẽ được để tại cửa hoặc trong hộp thư lớn',
      },
      {
        title: 'Gửi hàng về Việt Nam',
        content: 'Các dịch vụ phổ biến để gửi hàng từ Nhật về Việt Nam:',
        items: [
          'EMS (Express Mail Service) — Japan Post: nhanh nhất (3–5 ngày), giá trung bình. Tối đa 30kg',
          'SAL (Surface Airlifted) — Japan Post: rẻ hơn EMS, chậm hơn (2–4 tuần)',
          'Hàng không thường (航空便): 1–2 tuần, giá trung bình',
          'Dịch vụ vận chuyển thương mại người Việt: rẻ nhất nếu gửi nhiều hàng, tìm qua cộng đồng người Việt tại Nhật',
          'Hải quan Việt Nam: hàng gửi về có thể phải đóng thuế nhập khẩu nếu vượt mức miễn thuế',
        ],
        tip: 'Gửi đồ về Việt Nam qua bưu điện Nhật: điền tờ khai hải quan (税関申告書) bằng tiếng Anh/Nhật, liệt kê rõ nội dung và giá trị',
      },
    ],
  },
];


