import type { GrammarPattern, JapaneseWord, PhraseCategory } from '../../types/content';

export const JAPANESE_WORDS: JapaneseWord[] = [
  {
    word: '在留カード',
    reading: 'ざいりゅうカード',
    romaji: 'zairyuu kaado',
    meaning: 'Thẻ cư trú',
    example: '在留カードを持っています。',
    exampleRomaji: 'Zairyuu kaado o motte imasu.',
    exampleMeaning: 'Tôi có mang theo thẻ cư trú.',
    culturalNote:
      'Nên luôn mang theo khi ra ngoài. Ngân hàng, nhà mạng, cơ quan và nhiều thủ tục sẽ yêu cầu thẻ này.',
  },
  {
    word: 'マイナンバーカード',
    reading: 'マイナンバーカード',
    romaji: 'mainanbaa kaado',
    meaning: 'Thẻ My Number',
    example: 'マイナンバーカードを申請しました。',
    exampleRomaji: 'Mainanbaa kaado o shinsei shimashita.',
    exampleMeaning: 'Tôi đã nộp đơn xin thẻ My Number.',
    culturalNote:
      'My Number khác với My Number Card. Có mã số không đồng nghĩa là bạn đã có thẻ vật lý.',
  },
  {
    word: '住民票',
    reading: 'じゅうみんひょう',
    romaji: 'juuminhyou',
    meaning: 'Giấy chứng nhận cư trú',
    example: '住民票を区役所でもらいました。',
    exampleRomaji: 'Juuminhyou o kuyakusho de moraimashita.',
    exampleMeaning: 'Tôi đã lấy giấy chứng nhận cư trú ở quận.',
  },
  {
    word: '保険証',
    reading: 'ほけんしょう',
    romaji: 'hokenshou',
    meaning: 'Thẻ bảo hiểm',
    example: '保険証を持ってきました。',
    exampleRomaji: 'Hokenshou o motte kimashita.',
    exampleMeaning: 'Tôi đã mang theo thẻ bảo hiểm.',
  },
  {
    word: '銀行口座',
    reading: 'ぎんこうこうざ',
    romaji: 'ginkou kouza',
    meaning: 'Tài khoản ngân hàng',
    example: '銀行口座を開設したいです。',
    exampleRomaji: 'Ginkou kouza o kaisetsu shitai desu.',
    exampleMeaning: 'Tôi muốn mở tài khoản ngân hàng.',
  },
  {
    word: '残業',
    reading: 'ざんぎょう',
    romaji: 'zangyou',
    meaning: 'Làm thêm giờ',
    example: '今日は残業があります。',
    exampleRomaji: 'Kyou wa zangyou ga arimasu.',
    exampleMeaning: 'Hôm nay có làm thêm giờ.',
  },
  {
    word: '定期券',
    reading: 'ていきけん',
    romaji: 'teikiken',
    meaning: 'Vé tháng',
    example: '定期券を買いたいです。',
    exampleRomaji: 'Teikiken o kaitai desu.',
    exampleMeaning: 'Tôi muốn mua vé tháng.',
  },
  {
    word: '乗り換え',
    reading: 'のりかえ',
    romaji: 'norikae',
    meaning: 'Chuyển tàu / đổi tuyến',
    example: 'ここで乗り換えです。',
    exampleRomaji: 'Koko de norikae desu.',
    exampleMeaning: 'Chuyển tàu ở đây.',
  },
  {
    word: '家賃',
    reading: 'やちん',
    romaji: 'yachin',
    meaning: 'Tiền thuê nhà',
    example: '家賃は毎月払います。',
    exampleRomaji: 'Yachin wa maitsuki haraimasu.',
    exampleMeaning: 'Tiền nhà được trả hàng tháng.',
  },
  {
    word: '有給休暇',
    reading: 'ゆうきゅうきゅうか',
    romaji: 'yuukyuu kyuuka',
    meaning: 'Nghỉ phép có lương',
    example: '有給休暇を取りたいです。',
    exampleRomaji: 'Yuukyuu kyuuka o toritai desu.',
    exampleMeaning: 'Tôi muốn xin nghỉ phép có lương.',
  },
  {
    word: '転入届',
    reading: 'てんにゅうとどけ',
    romaji: 'tennyuu todoke',
    meaning: 'Tờ khai chuyển đến',
    example: '転入届を出しに来ました。',
    exampleRomaji: 'Tennyuu todoke o dashi ni kimashita.',
    exampleMeaning: 'Tôi đến để nộp tờ khai chuyển đến.',
  },
  {
    word: '転出証明書',
    reading: 'てんしゅつしょうめいしょ',
    romaji: 'tenshutsu shoumeisho',
    meaning: 'Giấy chuyển đi',
    example: '転出証明書が必要ですか。',
    exampleRomaji: 'Tenshutsu shoumeisho ga hitsuyou desu ka.',
    exampleMeaning: 'Có cần giấy chuyển đi không?',
  },
  {
    word: '市役所',
    reading: 'しやくしょ',
    romaji: 'shiyakusho',
    meaning: 'Tòa thị chính / cơ quan phường',
    example: '市役所で手続きをします。',
    exampleRomaji: 'Shiyakusho de tetsuzuki o shimasu.',
    exampleMeaning: 'Tôi làm thủ tục ở cơ quan phường.',
  },
  {
    word: '区役所',
    reading: 'くやくしょ',
    romaji: 'kuyakusho',
    meaning: 'Ủy ban quận / ward office',
    example: '区役所は駅の近くです。',
    exampleRomaji: 'Kuyakusho wa eki no chikaku desu.',
    exampleMeaning: 'Ủy ban quận ở gần ga.',
  },
  {
    word: '健康保険',
    reading: 'けんこうほけん',
    romaji: 'kenkou hoken',
    meaning: 'Bảo hiểm y tế',
    example: '健康保険について確認したいです。',
    exampleRomaji: 'Kenkou hoken ni tsuite kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận về bảo hiểm y tế.',
  },
  {
    word: '国民健康保険',
    reading: 'こくみんけんこうほけん',
    romaji: 'kokumin kenkou hoken',
    meaning: 'Bảo hiểm y tế quốc dân',
    example: '国民健康保険に加入しました。',
    exampleRomaji: 'Kokumin kenkou hoken ni kanyuu shimashita.',
    exampleMeaning: 'Tôi đã tham gia bảo hiểm y tế quốc dân.',
  },
  {
    word: '年金',
    reading: 'ねんきん',
    romaji: 'nenkin',
    meaning: 'Lương hưu công / Nenkin',
    example: '年金の書類が届きました。',
    exampleRomaji: 'Nenkin no shorui ga todokimashita.',
    exampleMeaning: 'Giấy tờ Nenkin đã được gửi đến.',
  },
  {
    word: '国民年金',
    reading: 'こくみんねんきん',
    romaji: 'kokumin nenkin',
    meaning: 'Quốc dân niên kim',
    example: '国民年金の案内を読みました。',
    exampleRomaji: 'Kokumin nenkin no annai o yomimashita.',
    exampleMeaning: 'Tôi đã đọc hướng dẫn về quốc dân niên kim.',
  },
  {
    word: '厚生年金',
    reading: 'こうせいねんきん',
    romaji: 'kousei nenkin',
    meaning: 'Phúc lợi niên kim / pension qua công ty',
    example: '給与明細に厚生年金が載っています。',
    exampleRomaji: 'Kyuuyo meisai ni kousei nenkin ga notte imasu.',
    exampleMeaning: 'Trên phiếu lương có ghi khoản厚生年金.',
  },
  {
    word: '保険料',
    reading: 'ほけんりょう',
    romaji: 'hokenryou',
    meaning: 'Phí bảo hiểm',
    example: '保険料はいくらですか。',
    exampleRomaji: 'Hokenryou wa ikura desu ka.',
    exampleMeaning: 'Phí bảo hiểm là bao nhiêu?',
  },
  {
    word: '納付書',
    reading: 'のうふしょ',
    romaji: 'noufusho',
    meaning: 'Phiếu nộp tiền',
    example: '納付書で支払いました。',
    exampleRomaji: 'Noufusho de shiharaimashita.',
    exampleMeaning: 'Tôi đã thanh toán bằng phiếu nộp tiền.',
  },
  {
    word: '口座振替',
    reading: 'こうざふりかえ',
    romaji: 'kouza furikae',
    meaning: 'Trích tiền tự động qua tài khoản',
    example: '口座振替にしたいです。',
    exampleRomaji: 'Kouza furikae ni shitai desu.',
    exampleMeaning: 'Tôi muốn chuyển sang trích tiền tự động.',
  },
  {
    word: '送金',
    reading: 'そうきん',
    romaji: 'soukin',
    meaning: 'Chuyển tiền',
    example: '海外送金をしたいです。',
    exampleRomaji: 'Kaigai soukin o shitai desu.',
    exampleMeaning: 'Tôi muốn chuyển tiền ra nước ngoài.',
  },
  {
    word: '携帯電話',
    reading: 'けいたいでんわ',
    romaji: 'keitai denwa',
    meaning: 'Điện thoại di động',
    example: '携帯電話の契約をしたいです。',
    exampleRomaji: 'Keitai denwa no keiyaku o shitai desu.',
    exampleMeaning: 'Tôi muốn làm hợp đồng điện thoại di động.',
  },
  {
    word: 'SIMカード',
    reading: 'シムカード',
    romaji: 'SIM kaado',
    meaning: 'Thẻ SIM',
    example: 'SIMカードを入れ替えました。',
    exampleRomaji: 'SIM kaado o irekaemashita.',
    exampleMeaning: 'Tôi đã thay thẻ SIM.',
  },
  {
    word: '開通',
    reading: 'かいつう',
    romaji: 'kaitsuu',
    meaning: 'Kích hoạt / thông tuyến',
    example: '今日中に開通しますか。',
    exampleRomaji: 'Kyoujuu ni kaitsuu shimasu ka.',
    exampleMeaning: 'Hôm nay có kích hoạt xong không?',
  },
  {
    word: '本人確認書類',
    reading: 'ほんにんかくにんしょるい',
    romaji: 'honnin kakunin shorui',
    meaning: 'Giấy tờ xác minh danh tính',
    example: '本人確認書類を見せてください。',
    exampleRomaji: 'Honnin kakunin shorui o misete kudasai.',
    exampleMeaning: 'Xin hãy cho tôi xem giấy tờ xác minh danh tính.',
  },
  {
    word: '契約解除',
    reading: 'けいやくかいじょ',
    romaji: 'keiyaku kaijo',
    meaning: 'Hủy hợp đồng',
    example: '契約解除の条件を確認したいです。',
    exampleRomaji: 'Keiyaku kaijo no jouken o kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận điều kiện hủy hợp đồng.',
  },
  {
    word: '健康診断',
    reading: 'けんこうしんだん',
    romaji: 'kenkou shindan',
    meaning: 'Khám sức khỏe định kỳ',
    example: '健康診断の日程を確認しました。',
    exampleRomaji: 'Kenkou shindan no nittei o kakunin shimashita.',
    exampleMeaning: 'Tôi đã xác nhận lịch khám sức khỏe định kỳ.',
  },
  {
    word: '確定申告',
    reading: 'かくていしんこく',
    romaji: 'kakutei shinkoku',
    meaning: 'Khai thuế cuối kỳ',
    example: '確定申告が必要か確認したいです。',
    exampleRomaji: 'Kakutei shinkoku ga hitsuyou ka kakunin shitai desu.',
    exampleMeaning: 'Tôi muốn xác nhận xem có cần khai thuế cuối kỳ không.',
  },
];

export const ESSENTIAL_PHRASES: PhraseCategory[] = [
  {
    category: 'Chào hỏi cơ bản',
    icon: 'hand-left',
    color: '#185FA5',
    phrases: [
      { jp: 'おはようございます。', romaji: 'Ohayou gozaimasu.', vn: 'Chào buổi sáng.' },
      { jp: 'こんにちは。', romaji: 'Konnichiwa.', vn: 'Xin chào / chào buổi ngày.' },
      { jp: 'こんばんは。', romaji: 'Konbanwa.', vn: 'Chào buổi tối.' },
      { jp: 'ありがとうございます。', romaji: 'Arigatou gozaimasu.', vn: 'Cảm ơn.' },
      { jp: 'すみません。', romaji: 'Sumimasen.', vn: 'Xin lỗi / làm phiền.' },
      { jp: 'よろしくお願いします。', romaji: 'Yoroshiku onegaishimasu.', vn: 'Mong được giúp đỡ.' },
    ],
  },
  {
    category: 'Khi không hiểu',
    icon: 'chatbubbles',
    color: '#2980B9',
    phrases: [
      { jp: '分かりました。', romaji: 'Wakarimashita.', vn: 'Tôi hiểu rồi.' },
      { jp: '分かりません。', romaji: 'Wakarimasen.', vn: 'Tôi chưa hiểu.' },
      { jp: 'もう一度お願いします。', romaji: 'Mou ichido onegaishimasu.', vn: 'Xin nói lại một lần nữa.' },
      { jp: 'ゆっくり話してください。', romaji: 'Yukkuri hanashite kudasai.', vn: 'Xin hãy nói chậm hơn.' },
      { jp: '書いていただけますか。', romaji: 'Kaite itadakemasu ka.', vn: 'Bạn có thể viết ra giúp tôi không?' },
      { jp: '少し日本語が分かります。', romaji: 'Sukoshi nihongo ga wakarimasu.', vn: 'Tôi hiểu một ít tiếng Nhật.' },
    ],
  },
  {
    category: 'Combini và mua sắm',
    icon: 'basket',
    color: '#E67E22',
    phrases: [
      { jp: 'これをください。', romaji: 'Kore o kudasai.', vn: 'Cho tôi món này.' },
      { jp: '袋はいりません。', romaji: 'Fukuro wa irimasen.', vn: 'Tôi không cần túi.' },
      { jp: 'レシートをください。', romaji: 'Reshiito o kudasai.', vn: 'Cho tôi xin hóa đơn.' },
      { jp: '温めてもらえますか。', romaji: 'Atatamete moraemasu ka.', vn: 'Bạn có thể hâm nóng giúp tôi không?' },
      { jp: 'カードで払えますか。', romaji: 'Kaado de haraemasu ka.', vn: 'Có thể thanh toán bằng thẻ không?' },
      { jp: 'これはいくらですか。', romaji: 'Kore wa ikura desu ka.', vn: 'Món này bao nhiêu tiền?' },
    ],
    dialogue: {
      situation: 'Mua cơm hộp ở combini',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。このお弁当を温めてもらえますか。',
          romaji: 'Sumimasen. Kono obentou o atatamete moraemasu ka.',
          vn: 'Xin lỗi, bạn có thể hâm nóng hộp cơm này giúp tôi không?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: 'はい。お支払いはどうされますか。',
          romaji: 'Hai. Oshiharai wa dou saremasu ka.',
          vn: 'Vâng. Bạn muốn thanh toán bằng cách nào ạ?',
        },
      ],
    },
  },
  {
    category: 'Tàu điện và đi lại',
    icon: 'train',
    color: '#16A085',
    phrases: [
      { jp: '新宿駅まで行きたいです。', romaji: 'Shinjuku eki made ikitai desu.', vn: 'Tôi muốn đi đến ga Shinjuku.' },
      { jp: '乗り換えはどこですか。', romaji: 'Norikae wa doko desu ka.', vn: 'Chuyển tàu ở đâu?' },
      { jp: 'この電車は渋谷に止まりますか。', romaji: 'Kono densha wa Shibuya ni tomarimasu ka.', vn: 'Tàu này có dừng ở Shibuya không?' },
      { jp: 'チャージしたいです。', romaji: 'Chaaji shitai desu.', vn: 'Tôi muốn nạp tiền vào thẻ.' },
      { jp: '遅延証明書はどこでもらえますか。', romaji: 'Chien shoumeisho wa doko de moraemasu ka.', vn: 'Lấy giấy xác nhận tàu trễ ở đâu?' },
      { jp: '定期券を買いたいです。', romaji: 'Teikiken o kaitai desu.', vn: 'Tôi muốn mua vé tháng.' },
    ],
  },
  {
    category: 'Đi khám và bệnh viện',
    icon: 'medical',
    color: '#C0392B',
    phrases: [
      { jp: '具合が悪いです。', romaji: 'Guai ga warui desu.', vn: 'Tôi cảm thấy không khỏe.' },
      { jp: '熱があります。', romaji: 'Netsu ga arimasu.', vn: 'Tôi bị sốt.' },
      { jp: 'のどが痛いです。', romaji: 'Nodo ga itai desu.', vn: 'Tôi bị đau họng.' },
      { jp: '保険証を持っています。', romaji: 'Hokenshou o motte imasu.', vn: 'Tôi có mang thẻ bảo hiểm.' },
      { jp: '予約しています。', romaji: 'Yoyaku shite imasu.', vn: 'Tôi đã đặt lịch.' },
      { jp: '今日は診てもらえますか。', romaji: 'Kyou wa mite moraemasu ka.', vn: 'Hôm nay tôi có thể được khám không?' },
    ],
    dialogue: {
      situation: 'Tại quầy tiếp nhận phòng khám',
      lines: [
        {
          speaker: 'B',
          speakerLabel: 'Lễ tân',
          jp: '今日はどうされましたか。',
          romaji: 'Kyou wa dou saremashita ka.',
          vn: 'Hôm nay bạn bị làm sao ạ?',
        },
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '熱があって、のどが痛いです。',
          romaji: 'Netsu ga atte, nodo ga itai desu.',
          vn: 'Tôi bị sốt và đau họng.',
        },
      ],
    },
  },
  {
    category: 'Công việc và hợp đồng',
    icon: 'briefcase',
    color: '#8E44AD',
    phrases: [
      { jp: 'この契約書を確認したいです。', romaji: 'Kono keiyakusho o kakunin shitai desu.', vn: 'Tôi muốn kiểm tra hợp đồng này.' },
      { jp: '残業代の計算方法を教えてください。', romaji: 'Zangyoudai no keisan houhou o oshiete kudasai.', vn: 'Xin cho tôi biết cách tính tiền làm thêm.' },
      { jp: '給料日はいつですか。', romaji: 'Kyuuryoubi wa itsu desu ka.', vn: 'Ngày lĩnh lương là khi nào?' },
      { jp: '有給休暇を取りたいです。', romaji: 'Yuukyuu kyuuka o toritai desu.', vn: 'Tôi muốn xin nghỉ phép có lương.' },
      { jp: '仕事内容をもう一度説明してください。', romaji: 'Shigoto naiyou o mou ichido setsumei shite kudasai.', vn: 'Xin giải thích lại nội dung công việc.' },
      { jp: '今日すぐ返事せず、確認してから連絡したいです。', romaji: 'Kyou sugu henji sezu, kakunin shite kara renraku shitai desu.', vn: 'Hôm nay tôi chưa trả lời ngay, tôi muốn kiểm tra rồi liên lạc lại.' },
    ],
  },
  {
    category: 'Xin nghỉ, đi trễ và đổi ca',
    icon: 'time',
    color: '#9B59B6',
    phrases: [
      { jp: '今日は体調が悪くて休みたいです。', romaji: 'Kyou wa taichou ga warukute yasumitai desu.', vn: 'Hôm nay tôi không khỏe và muốn xin nghỉ.' },
      { jp: '電車が遅れていて、少し遅れます。', romaji: 'Densha ga okurete ite, sukoshi okuremasu.', vn: 'Tàu đang trễ nên tôi sẽ đến muộn một chút.' },
      { jp: '今日は出勤が難しいです。', romaji: 'Kyou wa shukkin ga muzukashii desu.', vn: 'Hôm nay tôi khó có thể đi làm.' },
      { jp: 'シフトを相談したいです。', romaji: 'Shifuto o soudan shitai desu.', vn: 'Tôi muốn trao đổi về ca làm.' },
      { jp: '有給を使えるか確認したいです。', romaji: 'Yuukyuu o tsukaeru ka kakunin shitai desu.', vn: 'Tôi muốn xác nhận xem có thể dùng phép năm không.' },
      { jp: '何時ごろ着きそうですか。', romaji: 'Nanji goro tsukisou desu ka.', vn: 'Bạn dự kiến sẽ đến lúc mấy giờ?' },
    ],
    dialogue: {
      situation: 'Báo đi trễ với công ty',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'おはようございます。電車が遅れていて、10分ほど遅れます。',
          romaji: 'Ohayou gozaimasu. Densha ga okurete ite, juppun hodo okuremasu.',
          vn: 'Chào buổi sáng. Tàu đang trễ nên tôi sẽ đến muộn khoảng 10 phút.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '分かりました。着いたら連絡してください。',
          romaji: 'Wakarimashita. Tsuitara renraku shite kudasai.',
          vn: 'Đã rõ. Khi đến nơi thì báo lại nhé.',
        },
      ],
    },
  },
  {
    category: 'Bị hỏi giấy tờ hoặc thông tin cá nhân',
    icon: 'card',
    color: '#1F618D',
    phrases: [
      { jp: '在留カードは持っています。', romaji: 'Zairyuu kaado wa motte imasu.', vn: 'Tôi có mang thẻ cư trú.' },
      { jp: 'パスポートも必要ですか。', romaji: 'Pasupooto mo hitsuyou desu ka.', vn: 'Có cần cả hộ chiếu không?' },
      { jp: '住所確認の書類はこれで大丈夫ですか。', romaji: 'Juusho kakunin no shorui wa kore de daijoubu desu ka.', vn: 'Giấy xác nhận địa chỉ này đã đủ chưa?' },
      { jp: 'コピーではなく原本が必要ですか。', romaji: 'Kopii de wa naku genpon ga hitsuyou desu ka.', vn: 'Có cần bản gốc chứ không phải bản copy đúng không?' },
      { jp: '今日は足りない書類だけ確認したいです。', romaji: 'Kyou wa tarinai shorui dake kakunin shitai desu.', vn: 'Hôm nay tôi chỉ muốn xác nhận những giấy tờ còn thiếu.' },
      { jp: '持ってくるものをメモしてもいいですか。', romaji: 'Motte kuru mono o memo shite mo ii desu ka.', vn: 'Tôi ghi lại những thứ cần mang tới có được không?' },
    ],
    dialogue: {
      situation: 'Khi bị yêu cầu bổ sung giấy tờ',
      lines: [
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: '住所確認の書類をお願いします。',
          romaji: 'Juusho kakunin no shorui o onegaishimasu.',
          vn: 'Xin vui lòng cho tôi giấy xác nhận địa chỉ.',
        },
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '住民票で大丈夫ですか。',
          romaji: 'Juuminhyou de daijoubu desu ka.',
          vn: 'Giấy cư trú có được không?',
        },
      ],
    },
  },
  {
    category: 'Phiếu lương và làm thêm giờ',
    icon: 'receipt',
    color: '#7D3C98',
    phrases: [
      { jp: '今月の給料を確認したいです。', romaji: 'Kongetsu no kyuuryou o kakunin shitai desu.', vn: 'Tôi muốn kiểm tra lương tháng này.' },
      { jp: 'この控除は何ですか。', romaji: 'Kono koujo wa nan desu ka.', vn: 'Khoản khấu trừ này là gì?' },
      { jp: '残業時間が合っているか確認したいです。', romaji: 'Zangyou jikan ga atte iru ka kakunin shitai desu.', vn: 'Tôi muốn kiểm tra xem số giờ làm thêm có đúng không.' },
      { jp: '明細をもう一度説明してください。', romaji: 'Meisai o mou ichido setsumei shite kudasai.', vn: 'Xin giải thích lại phiếu lương cho tôi.' },
      { jp: '交通費は含まれていますか。', romaji: 'Koutsuuhi wa fukumarete imasu ka.', vn: 'Tiền đi lại đã được tính vào chưa?' },
      { jp: '書面でもらえますか。', romaji: 'Shomen de moraemasu ka.', vn: 'Tôi có thể nhận bằng văn bản không?' },
    ],
    dialogue: {
      situation: 'Hỏi lại phiếu lương',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'この控除について説明していただけますか。',
          romaji: 'Kono koujo ni tsuite setsumei shite itadakemasu ka.',
          vn: 'Anh/chị có thể giải thích khoản khấu trừ này giúp tôi không?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Kế toán',
          jp: 'はい。こちらは社会保険料です。',
          romaji: 'Hai. Kochira wa shakai hokenryou desu.',
          vn: 'Vâng. Đây là tiền bảo hiểm xã hội.',
        },
      ],
    },
  },
  {
    category: 'Trễ tàu, lạc ga và đi nhầm tuyến',
    icon: 'alert-circle',
    color: '#D35400',
    phrases: [
      { jp: '電車が遅れています。', romaji: 'Densha ga okurete imasu.', vn: 'Tàu đang bị trễ.' },
      { jp: '道に迷いました。', romaji: 'Michi ni mayoimashita.', vn: 'Tôi bị lạc đường.' },
      { jp: '反対方向に乗ってしまいました。', romaji: 'Hantai houkou ni notte shimaimashita.', vn: 'Tôi đã lên nhầm chiều.' },
      { jp: 'このホームで合っていますか。', romaji: 'Kono hoomu de atte imasu ka.', vn: 'Đứng ở sân ga này có đúng không?' },
      { jp: '次はどこで降りればいいですか。', romaji: 'Tsugi wa doko de orireba ii desu ka.', vn: 'Tiếp theo tôi nên xuống ở đâu?' },
      { jp: '遅延証明書をもらいたいです。', romaji: 'Chien shoumeisho o moraitai desu.', vn: 'Tôi muốn lấy giấy xác nhận tàu trễ.' },
    ],
    dialogue: {
      situation: 'Hỏi nhân viên nhà ga khi đi nhầm tuyến',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。反対方向に乗ってしまいました。',
          romaji: 'Sumimasen. Hantai houkou ni notte shimaimashita.',
          vn: 'Xin lỗi, tôi đã lên nhầm chiều tàu.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên ga',
          jp: '次の駅で降りて、向かい側のホームに行ってください。',
          romaji: 'Tsugi no eki de orite, mukai gawa no hoomu ni itte kudasai.',
          vn: 'Hãy xuống ở ga tiếp theo rồi sang sân ga đối diện nhé.',
        },
      ],
    },
  },
  {
    category: 'Cơ quan và giấy tờ',
    icon: 'business',
    color: '#117A65',
    phrases: [
      { jp: '住所変更の手続きをしたいです。', romaji: 'Juusho henkou no tetsuzuki o shitai desu.', vn: 'Tôi muốn làm thủ tục đổi địa chỉ.' },
      { jp: '住民票を一通ください。', romaji: 'Juuminhyou o ittuu kudasai.', vn: 'Cho tôi xin một bản giấy cư trú.' },
      { jp: 'マイナンバーカードについて聞きたいです。', romaji: 'Mainanbaa kaado ni tsuite kikitai desu.', vn: 'Tôi muốn hỏi về thẻ My Number.' },
      { jp: '国民健康保険に入りたいです。', romaji: 'Kokumin kenkou hoken ni hairitai desu.', vn: 'Tôi muốn tham gia bảo hiểm y tế quốc dân.' },
      { jp: '何番の窓口ですか。', romaji: 'Nanban no madoguchi desu ka.', vn: 'Là quầy số mấy?' },
      { jp: '今日中に終わりますか。', romaji: 'Kyoujuu ni owarimasu ka.', vn: 'Hôm nay có làm xong trong ngày không?' },
    ],
    dialogue: {
      situation: 'Đổi địa chỉ tại cơ quan phường',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '引っ越したので、住所変更をしたいです。',
          romaji: 'Hikkoshita node, juusho henkou o shitai desu.',
          vn: 'Tôi vừa chuyển nhà nên muốn đổi địa chỉ.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: '在留カードとマイナンバーカードはお持ちですか。',
          romaji: 'Zairyuu kaado to mainanbaa kaado wa omochi desu ka.',
          vn: 'Bạn có mang theo thẻ cư trú và thẻ My Number không?',
        },
      ],
    },
  },
  {
    category: 'Ngân hàng và chuyển tiền',
    icon: 'wallet',
    color: '#1ABC9C',
    phrases: [
      { jp: '口座を開設したいです。', romaji: 'Kouza o kaisetsu shitai desu.', vn: 'Tôi muốn mở tài khoản.' },
      { jp: '必要な書類を教えてください。', romaji: 'Hitsuyou na shorui o oshiete kudasai.', vn: 'Xin cho tôi biết cần những giấy tờ gì.' },
      { jp: '海外送金をしたいです。', romaji: 'Kaigai soukin o shitai desu.', vn: 'Tôi muốn chuyển tiền ra nước ngoài.' },
      { jp: '審査にどのくらいかかりますか。', romaji: 'Shinsa ni dono kurai kakarimasu ka.', vn: 'Xét duyệt mất khoảng bao lâu?' },
      { jp: '今日は申し込みだけできますか。', romaji: 'Kyou wa moushikomi dake dekimasu ka.', vn: 'Hôm nay tôi chỉ làm bước đăng ký trước có được không?' },
      { jp: '理由を教えていただけますか。', romaji: 'Riyuu o oshiete itadakemasu ka.', vn: 'Anh/chị có thể cho tôi biết lý do được không?' },
    ],
    dialogue: {
      situation: 'Bị yêu cầu bổ sung giấy tờ khi mở tài khoản',
      lines: [
        {
          speaker: 'B',
          speakerLabel: 'Ngân hàng',
          jp: '追加で住所確認書類が必要です。',
          romaji: 'Tsuika de juusho kakunin shorui ga hitsuyou desu.',
          vn: 'Chúng tôi cần bổ sung giấy xác nhận địa chỉ.',
        },
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '住民票を持ってくれば大丈夫ですか。',
          romaji: 'Juuminhyou o motte kureba daijoubu desu ka.',
          vn: 'Nếu tôi mang giấy cư trú tới thì có được không?',
        },
      ],
    },
  },
  {
    category: 'Điện thoại và internet',
    icon: 'wifi',
    color: '#2874A6',
    phrases: [
      { jp: 'SIMを契約したいです。', romaji: 'SIM o keiyaku shitai desu.', vn: 'Tôi muốn làm hợp đồng SIM.' },
      { jp: '月額料金はいくらですか。', romaji: 'Getsugaku ryoukin wa ikura desu ka.', vn: 'Cước hàng tháng là bao nhiêu?' },
      { jp: '解約金はありますか。', romaji: 'Kaiyakukin wa arimasu ka.', vn: 'Có phí hủy hợp đồng không?' },
      { jp: 'インターネットがつながりません。', romaji: 'Intaanetto ga tsunagarimasen.', vn: 'Internet không kết nối được.' },
      { jp: '工事の日程を確認したいです。', romaji: 'Kouji no nittei o kakunin shitai desu.', vn: 'Tôi muốn xác nhận lịch lắp đặt.' },
      { jp: '本人確認書類は何が必要ですか。', romaji: 'Honnin kakunin shorui wa nani ga hitsuyou desu ka.', vn: 'Cần giấy tờ gì để xác minh danh tính?' },
    ],
    dialogue: {
      situation: 'Hỏi nhà mạng khi đăng ký SIM',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'SIMを契約したいです。必要な書類を教えてください。',
          romaji: 'SIM o keiyaku shitai desu. Hitsuyou na shorui o oshiete kudasai.',
          vn: 'Tôi muốn đăng ký SIM. Xin cho tôi biết cần những giấy tờ gì.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: '在留カードと銀行口座が分かるものをお願いします。',
          romaji: 'Zairyuu kaado to ginkou kouza ga wakaru mono o onegaishimasu.',
          vn: 'Xin vui lòng mang thẻ cư trú và giấy tờ thể hiện tài khoản ngân hàng.',
        },
      ],
    },
  },
  {
    category: 'Bưu điện và nhận hàng',
    icon: 'mail',
    color: '#A04000',
    phrases: [
      { jp: '再配達をお願いしたいです。', romaji: 'Saihaitatsu o onegai shitai desu.', vn: 'Tôi muốn yêu cầu giao lại hàng.' },
      { jp: '追跡番号はこちらです。', romaji: 'Tsuiseki bangou wa kochira desu.', vn: 'Mã theo dõi ở đây.' },
      { jp: '荷物はいつ届きますか。', romaji: 'Nimotsu wa itsu todokimasu ka.', vn: 'Khi nào hàng sẽ tới?' },
      { jp: '不在票が入っていました。', romaji: 'Fuzaihyou ga haitte imashita.', vn: 'Tôi có phiếu báo vắng nhà.' },
      { jp: '窓口で受け取れますか。', romaji: 'Madoguchi de uketoremasu ka.', vn: 'Tôi có thể nhận ở quầy không?' },
      { jp: '時間帯を変更したいです。', romaji: 'Jikantai o henkou shitai desu.', vn: 'Tôi muốn đổi khung giờ giao.' },
    ],
    dialogue: {
      situation: 'Yêu cầu giao lại hàng',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '不在票が入っていました。再配達をお願いしたいです。',
          romaji: 'Fuzaihyou ga haitte imashita. Saihaitatsu o onegai shitai desu.',
          vn: 'Tôi có phiếu báo vắng nhà. Tôi muốn yêu cầu giao lại hàng.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Bưu điện',
          jp: 'ご希望の時間帯はありますか。',
          romaji: 'Gokibou no jikantai wa arimasu ka.',
          vn: 'Bạn muốn giao lại vào khung giờ nào?',
        },
      ],
    },
  },
  {
    category: 'Nói tự nhiên hơn trong đời sống',
    icon: 'language',
    color: '#5D6D7E',
    phrases: [
      { jp: '大丈夫です。', romaji: 'Daijoubu desu.', vn: 'Không sao / ổn rồi.' },
      { jp: 'ちょっと確認します。', romaji: 'Chotto kakunin shimasu.', vn: 'Để tôi kiểm tra lại một chút.' },
      { jp: 'あとで連絡します。', romaji: 'Ato de renraku shimasu.', vn: 'Tôi sẽ liên lạc lại sau.' },
      { jp: '今は難しいです。', romaji: 'Ima wa muzukashii desu.', vn: 'Hiện tại thì khó.' },
      { jp: '少し考えさせてください。', romaji: 'Sukoshi kangae sasete kudasai.', vn: 'Cho tôi suy nghĩ thêm một chút.' },
      { jp: '確認してから返事します。', romaji: 'Kakunin shite kara henji shimasu.', vn: 'Tôi sẽ kiểm tra rồi trả lời.' },
    ],
  },
  {
    category: 'Câu nên tránh hoặc nên đổi cách nói',
    icon: 'warning',
    color: '#B9770E',
    phrases: [
      { jp: '無理です。', romaji: 'Muri desu.', vn: 'Câu này khá gắt. Thường nên đổi thành “今は難しいです”.' },
      { jp: '知りません。', romaji: 'Shirimasen.', vn: 'Dễ tạo cảm giác cộc. Nên dùng “ちょっと分かりません”.' },
      { jp: 'できません。', romaji: 'Dekimasen.', vn: 'Nếu cần mềm hơn, dùng “今は難しいです” hoặc “確認します”.' },
      { jp: '違います。', romaji: 'Chigaimasu.', vn: 'Nếu muốn lịch sự hơn, nói “少し違うと思います”.' },
    ],
  },
  {
    category: 'Gọi điện cho bệnh viện hoặc phòng khám',
    icon: 'call',
    color: '#C0392B',
    phrases: [
      { jp: '今日受診できますか。', romaji: 'Kyou jushin dekimasu ka.', vn: 'Hôm nay tôi có thể đến khám không?' },
      { jp: '初診です。', romaji: 'Shoshin desu.', vn: 'Tôi khám lần đầu.' },
      { jp: '保険証を持っています。', romaji: 'Hokenshou o motte imasu.', vn: 'Tôi có mang thẻ bảo hiểm.' },
      { jp: '何を持っていけばいいですか。', romaji: 'Nani o motte ikeba ii desu ka.', vn: 'Tôi cần mang theo gì?' },
      { jp: '日本語があまり上手ではありません。', romaji: 'Nihongo ga amari jouzu de wa arimasen.', vn: 'Tiếng Nhật của tôi chưa tốt lắm.' },
    ],
    dialogue: {
      situation: 'Gọi điện đặt lịch khám',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'もしもし、今日受診できますか。熱があります。',
          romaji: 'Moshi moshi, kyou jushin dekimasu ka. Netsu ga arimasu.',
          vn: 'Alo, hôm nay tôi có thể đến khám không? Tôi đang bị sốt.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Phòng khám',
          jp: 'はい。保険証を持って、午後3時に来てください。',
          romaji: 'Hai. Hokenshou o motte, gogo sanji ni kite kudasai.',
          vn: 'Vâng. Hãy mang theo thẻ bảo hiểm và đến lúc 3 giờ chiều.',
        },
      ],
    },
  },
  {
    category: 'Gọi công ty để báo vắng hoặc báo trễ',
    icon: 'call',
    color: '#8E44AD',
    phrases: [
      { jp: '本日お休みをいただきたいです。', romaji: 'Honjitsu oyasumi o itadakitai desu.', vn: 'Hôm nay tôi muốn xin nghỉ.' },
      { jp: '電車の遅延で少し遅れます。', romaji: 'Densha no chien de sukoshi okuremasu.', vn: 'Tôi sẽ đến muộn một chút vì tàu bị trễ.' },
      { jp: '病院に行ってから連絡します。', romaji: 'Byouin ni itte kara renraku shimasu.', vn: 'Tôi sẽ đi bệnh viện rồi liên lạc lại.' },
      { jp: '必要であれば診断書を提出します。', romaji: 'Hitsuyou de areba shindansho o teishutsu shimasu.', vn: 'Nếu cần, tôi sẽ nộp giấy chứng nhận y tế.' },
      { jp: '担当者にお伝えください。', romaji: 'Tantousha ni otsutae kudasai.', vn: 'Xin nhắn lại với người phụ trách giúp tôi.' },
    ],
    dialogue: {
      situation: 'Gọi báo nghỉ trong ngày',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'おはようございます。体調が悪いため、本日お休みをいただきたいです。',
          romaji: 'Ohayou gozaimasu. Taichou ga warui tame, honjitsu oyasumi o itadakitai desu.',
          vn: 'Chào buổi sáng. Vì sức khỏe không tốt nên hôm nay tôi muốn xin nghỉ.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '分かりました。落ち着いたら連絡してください。',
          romaji: 'Wakarimashita. Ochitsuitara renraku shite kudasai.',
          vn: 'Đã rõ. Khi ổn hơn thì báo lại cho công ty nhé.',
        },
      ],
    },
  },
  {
    category: 'Gọi nhà mạng, quản lý nhà hoặc bưu điện',
    icon: 'call',
    color: '#2874A6',
    phrases: [
      { jp: 'インターネットが使えません。', romaji: 'Intaanetto ga tsukaemasen.', vn: 'Internet không dùng được.' },
      { jp: '契約内容を確認したいです。', romaji: 'Keiyaku naiyou o kakunin shitai desu.', vn: 'Tôi muốn kiểm tra nội dung hợp đồng.' },
      { jp: '設備が故障しています。', romaji: 'Setsubi ga koshou shite imasu.', vn: 'Thiết bị đang bị hỏng.' },
      { jp: '再配達をお願いします。', romaji: 'Saihaitatsu o onegaishimasu.', vn: 'Xin giao lại hàng giúp tôi.' },
      { jp: '受付番号を教えてください。', romaji: 'Uketsuke bangou o oshiete kudasai.', vn: 'Xin cho tôi mã tiếp nhận.' },
    ],
    dialogue: {
      situation: 'Gọi báo internet bị lỗi',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'インターネットがつながらないので、確認をお願いしたいです。',
          romaji: 'Intaanetto ga tsunagaranai node, kakunin o onegai shitai desu.',
          vn: 'Internet không kết nối được nên tôi muốn nhờ kiểm tra giúp.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhà mạng',
          jp: 'ご契約者名と電話番号をお願いします。',
          romaji: 'Gokeiyakusha mei to denwa bangou o onegaishimasu.',
          vn: 'Xin cho tôi tên người đứng hợp đồng và số điện thoại.',
        },
      ],
    },
  },
];

const INDUSTRY_JAPANESE_WORDS: JapaneseWord[] = [
  { word: '工場', reading: 'こうじょう', romaji: 'koujou', meaning: 'Nhà máy', example: '工場で働いています。', exampleRomaji: 'Koujou de hataraite imasu.', exampleMeaning: 'Tôi đang làm việc ở nhà máy.' },
  { word: 'ライン', reading: 'ライン', romaji: 'rain', meaning: 'Dây chuyền', example: '今日はラインに入ります。', exampleRomaji: 'Kyou wa rain ni hairimasu.', exampleMeaning: 'Hôm nay tôi vào dây chuyền.' },
  { word: '検品', reading: 'けんぴん', romaji: 'kenpin', meaning: 'Kiểm hàng', example: '出荷前に検品します。', exampleRomaji: 'Shukka mae ni kenpin shimasu.', exampleMeaning: 'Tôi kiểm hàng trước khi xuất.' },
  { word: '不良品', reading: 'ふりょうひん', romaji: 'furyouhin', meaning: 'Hàng lỗi', example: '不良品は別の箱に入れてください。', exampleRomaji: 'Furyouhin wa betsu no hako ni irete kudasai.', exampleMeaning: 'Xin hãy bỏ hàng lỗi vào thùng riêng.' },
  { word: '部品', reading: 'ぶひん', romaji: 'buhin', meaning: 'Linh kiện', example: '部品が足りません。', exampleRomaji: 'Buhin ga tarimasen.', exampleMeaning: 'Linh kiện không đủ.' },
  { word: '組み立て', reading: 'くみたて', romaji: 'kumitate', meaning: 'Lắp ráp', example: 'この工程は組み立てです。', exampleRomaji: 'Kono koutei wa kumitate desu.', exampleMeaning: 'Công đoạn này là lắp ráp.' },
  { word: '工程', reading: 'こうてい', romaji: 'koutei', meaning: 'Công đoạn', example: '次の工程へ運んでください。', exampleRomaji: 'Tsugi no koutei e hakonde kudasai.', exampleMeaning: 'Xin hãy chuyển sang công đoạn tiếp theo.' },
  { word: '出荷', reading: 'しゅっか', romaji: 'shukka', meaning: 'Xuất hàng', example: '午後の出荷に間に合わせます。', exampleRomaji: 'Gogo no shukka ni maniawasemasu.', exampleMeaning: 'Tôi sẽ kịp cho đợt xuất hàng buổi chiều.' },
  { word: '梱包', reading: 'こんぽう', romaji: 'konpou', meaning: 'Đóng gói', example: '梱包が終わったら知らせてください。', exampleRomaji: 'Konpou ga owattara shirasete kudasai.', exampleMeaning: 'Khi đóng gói xong hãy báo cho tôi.' },
  { word: '数量', reading: 'すうりょう', romaji: 'suuryou', meaning: 'Số lượng', example: '数量を確認しました。', exampleRomaji: 'Suuryou o kakunin shimashita.', exampleMeaning: 'Tôi đã kiểm tra số lượng.' },
  { word: '在庫', reading: 'ざいこ', romaji: 'zaiko', meaning: 'Tồn kho', example: '在庫が少なくなっています。', exampleRomaji: 'Zaiko ga sukunaku natte imasu.', exampleMeaning: 'Tồn kho đang ít đi.' },
  { word: '機械', reading: 'きかい', romaji: 'kikai', meaning: 'Máy móc', example: '機械を止めてください。', exampleRomaji: 'Kikai o tomete kudasai.', exampleMeaning: 'Xin hãy dừng máy.' },
  { word: '手袋', reading: 'てぶくろ', romaji: 'tebukuro', meaning: 'Găng tay', example: '手袋を着けてください。', exampleRomaji: 'Tebukuro o tsukete kudasai.', exampleMeaning: 'Xin hãy đeo găng tay.' },
  { word: '安全靴', reading: 'あんぜんぐつ', romaji: 'anzen gutsu', meaning: 'Giày bảo hộ', example: '安全靴は必ず履いてください。', exampleRomaji: 'Anzen gutsu wa kanarazu haite kudasai.', exampleMeaning: 'Nhất định phải mang giày bảo hộ.' },
  { word: '作業着', reading: 'さぎょうぎ', romaji: 'sagyougi', meaning: 'Đồng phục làm việc', example: '作業着に着替えます。', exampleRomaji: 'Sagyougi ni kigaemasu.', exampleMeaning: 'Tôi thay sang đồ làm việc.' },
  { word: '休憩', reading: 'きゅうけい', romaji: 'kyuukei', meaning: 'Nghỉ giải lao', example: '十時から休憩です。', exampleRomaji: 'Juuji kara kyuukei desu.', exampleMeaning: 'Nghỉ giải lao từ 10 giờ.' },
  { word: '残業', reading: 'ざんぎょう', romaji: 'zangyou', meaning: 'Làm thêm giờ', example: '今日は残業があります。', exampleRomaji: 'Kyou wa zangyou ga arimasu.', exampleMeaning: 'Hôm nay có tăng ca.' },
  { word: '早退', reading: 'そうたい', romaji: 'soutai', meaning: 'Về sớm', example: '体調が悪いので早退したいです。', exampleRomaji: 'Taichou ga warui node soutai shitai desu.', exampleMeaning: 'Tôi muốn về sớm vì không khỏe.' },
  { word: '欠勤', reading: 'けっきん', romaji: 'kekkin', meaning: 'Nghỉ làm', example: '明日は欠勤します。', exampleRomaji: 'Ashita wa kekkin shimasu.', exampleMeaning: 'Ngày mai tôi nghỉ làm.' },
  { word: '交代', reading: 'こうたい', romaji: 'koutai', meaning: 'Đổi ca / thay ca', example: '午後のシフトと交代できますか。', exampleRomaji: 'Gogo no shifuto to koutai dekimasu ka.', exampleMeaning: 'Có thể đổi sang ca chiều không?' },

  { word: '建設現場', reading: 'けんせつげんば', romaji: 'kensetsu genba', meaning: 'Công trường xây dựng', example: '建設現場で働いています。', exampleRomaji: 'Kensetsu genba de hataraite imasu.', exampleMeaning: 'Tôi đang làm ở công trường xây dựng.' },
  { word: '足場', reading: 'あしば', romaji: 'ashiba', meaning: 'Giàn giáo', example: '足場では気をつけてください。', exampleRomaji: 'Ashiba de wa ki o tsukete kudasai.', exampleMeaning: 'Xin hãy cẩn thận trên giàn giáo.' },
  { word: 'ヘルメット', reading: 'ヘルメット', romaji: 'herumetto', meaning: 'Mũ bảo hộ', example: 'ヘルメットを着用してください。', exampleRomaji: 'Herumetto o chakuyou shite kudasai.', exampleMeaning: 'Xin hãy đội mũ bảo hộ.' },
  { word: '安全帯', reading: 'あんぜんたい', romaji: 'anzentai', meaning: 'Dây an toàn', example: '高い所では安全帯が必要です。', exampleRomaji: 'Takai tokoro de wa anzentai ga hitsuyou desu.', exampleMeaning: 'Làm ở chỗ cao cần dây an toàn.' },
  { word: '高所作業', reading: 'こうしょさぎょう', romaji: 'kousho sagyou', meaning: 'Làm việc trên cao', example: '今日は高所作業があります。', exampleRomaji: 'Kyou wa kousho sagyou ga arimasu.', exampleMeaning: 'Hôm nay có việc trên cao.' },
  { word: '危険', reading: 'きけん', romaji: 'kiken', meaning: 'Nguy hiểm', example: 'ここは危険です。', exampleRomaji: 'Koko wa kiken desu.', exampleMeaning: 'Chỗ này nguy hiểm.' },
  { word: '立入禁止', reading: 'たちいりきんし', romaji: 'tachiiri kinshi', meaning: 'Cấm vào', example: 'ここは立入禁止です。', exampleRomaji: 'Koko wa tachiiri kinshi desu.', exampleMeaning: 'Khu vực này cấm vào.' },
  { word: '工具', reading: 'こうぐ', romaji: 'kougu', meaning: 'Dụng cụ', example: '工具を片づけてください。', exampleRomaji: 'Kougu o katazukete kudasai.', exampleMeaning: 'Xin hãy cất dụng cụ đi.' },
  { word: '資材', reading: 'しざい', romaji: 'shizai', meaning: 'Vật liệu', example: '資材を運びます。', exampleRomaji: 'Shizai o hakobimasu.', exampleMeaning: 'Tôi sẽ chuyển vật liệu.' },
  { word: '搬入', reading: 'はんにゅう', romaji: 'hannyuu', meaning: 'Đưa vật liệu vào', example: '朝に資材を搬入します。', exampleRomaji: 'Asa ni shizai o hannyuu shimasu.', exampleMeaning: 'Buổi sáng sẽ đưa vật liệu vào.' },
  { word: '搬出', reading: 'はんしゅつ', romaji: 'hanshutsu', meaning: 'Đưa vật liệu ra', example: '午後に廃材を搬出します。', exampleRomaji: 'Gogo ni haizai o hanshutsu shimasu.', exampleMeaning: 'Buổi chiều sẽ chuyển phế liệu ra ngoài.' },
  { word: '図面', reading: 'ずめん', romaji: 'zumen', meaning: 'Bản vẽ', example: '図面を確認してください。', exampleRomaji: 'Zumen o kakunin shite kudasai.', exampleMeaning: 'Xin hãy kiểm tra bản vẽ.' },
  { word: '寸法', reading: 'すんぽう', romaji: 'sunpou', meaning: 'Kích thước', example: '寸法が違います。', exampleRomaji: 'Sunpou ga chigaimasu.', exampleMeaning: 'Kích thước bị sai.' },
  { word: '測る', reading: 'はかる', romaji: 'hakaru', meaning: 'Đo', example: 'もう一度測ってください。', exampleRomaji: 'Mou ichido hakatte kudasai.', exampleMeaning: 'Xin hãy đo lại lần nữa.' },
  { word: '休工', reading: 'きゅうこう', romaji: 'kyuukou', meaning: 'Tạm ngừng thi công', example: '雨で今日は休工です。', exampleRomaji: 'Ame de kyou wa kyuukou desu.', exampleMeaning: 'Hôm nay tạm ngừng thi công vì mưa.' },
  { word: '現場監督', reading: 'げんばかんとく', romaji: 'genba kantoku', meaning: 'Giám sát công trường', example: '現場監督に確認します。', exampleRomaji: 'Genba kantoku ni kakunin shimasu.', exampleMeaning: 'Tôi sẽ xác nhận với giám sát công trường.' },
  { word: '作業指示', reading: 'さぎょうしじ', romaji: 'sagyou shiji', meaning: 'Chỉ thị công việc', example: '朝礼で作業指示を聞きます。', exampleRomaji: 'Chourei de sagyou shiji o kikimasu.', exampleMeaning: 'Tôi nghe chỉ thị công việc ở buổi họp sáng.' },
  { word: '朝礼', reading: 'ちょうれい', romaji: 'chourei', meaning: 'Họp đầu giờ', example: '朝礼は七時半からです。', exampleRomaji: 'Chourei wa shichiji han kara desu.', exampleMeaning: 'Họp đầu giờ từ 7 giờ rưỡi.' },
  { word: '片付け', reading: 'かたづけ', romaji: 'katazuke', meaning: 'Dọn dẹp', example: '作業後に片付けをします。', exampleRomaji: 'Sagyougo ni katazuke o shimasu.', exampleMeaning: 'Sau khi làm xong sẽ dọn dẹp.' },
  { word: '報告', reading: 'ほうこく', romaji: 'houkoku', meaning: 'Báo cáo', example: '問題があればすぐ報告してください。', exampleRomaji: 'Mondai ga areba sugu houkoku shite kudasai.', exampleMeaning: 'Nếu có vấn đề hãy báo ngay.' },

  { word: '農場', reading: 'のうじょう', romaji: 'noujou', meaning: 'Nông trại', example: '農場で野菜を育てています。', exampleRomaji: 'Noujou de yasai o sodatete imasu.', exampleMeaning: 'Tôi đang trồng rau ở nông trại.' },
  { word: '畑', reading: 'はたけ', romaji: 'hatake', meaning: 'Ruộng / vườn', example: '畑に行ってきます。', exampleRomaji: 'Hatake ni itte kimasu.', exampleMeaning: 'Tôi ra ruộng đây.' },
  { word: '収穫', reading: 'しゅうかく', romaji: 'shuukaku', meaning: 'Thu hoạch', example: '今日はトマトを収穫します。', exampleRomaji: 'Kyou wa tomato o shuukaku shimasu.', exampleMeaning: 'Hôm nay tôi thu hoạch cà chua.' },
  { word: '苗', reading: 'なえ', romaji: 'nae', meaning: 'Cây giống', example: '苗を植えます。', exampleRomaji: 'Nae o uemasu.', exampleMeaning: 'Tôi trồng cây giống.' },
  { word: '種', reading: 'たね', romaji: 'tane', meaning: 'Hạt giống', example: '種をまく時期です。', exampleRomaji: 'Tane o maku jiki desu.', exampleMeaning: 'Đến lúc gieo hạt rồi.' },
  { word: '肥料', reading: 'ひりょう', romaji: 'hiryou', meaning: 'Phân bón', example: '肥料を入れてください。', exampleRomaji: 'Hiryou o irete kudasai.', exampleMeaning: 'Xin hãy bón phân.' },
  { word: '農薬', reading: 'のうやく', romaji: 'nouyaku', meaning: 'Thuốc nông nghiệp', example: '農薬を使う時は手袋が必要です。', exampleRomaji: 'Nouyaku o tsukau toki wa tebukuro ga hitsuyou desu.', exampleMeaning: 'Khi dùng thuốc nông nghiệp cần găng tay.' },
  { word: '水やり', reading: 'みずやり', romaji: 'mizuyari', meaning: 'Tưới nước', example: '朝に水やりをします。', exampleRomaji: 'Asa ni mizuyari o shimasu.', exampleMeaning: 'Buổi sáng tôi tưới nước.' },
  { word: '選別', reading: 'せんべつ', romaji: 'senbetsu', meaning: 'Phân loại', example: '大きさで選別します。', exampleRomaji: 'Ookisa de senbetsu shimasu.', exampleMeaning: 'Tôi phân loại theo kích cỡ.' },
  { word: '箱詰め', reading: 'はこづめ', romaji: 'hakodume', meaning: 'Đóng thùng', example: '収穫した野菜を箱詰めします。', exampleRomaji: 'Shuukaku shita yasai o hakodume shimasu.', exampleMeaning: 'Tôi đóng thùng rau đã thu hoạch.' },
  { word: '温室', reading: 'おんしつ', romaji: 'onshitsu', meaning: 'Nhà kính', example: '温室の温度を確認してください。', exampleRomaji: 'Onshitsu no ondo o kakunin shite kudasai.', exampleMeaning: 'Xin hãy kiểm tra nhiệt độ nhà kính.' },
  { word: '気温', reading: 'きおん', romaji: 'kion', meaning: 'Nhiệt độ không khí', example: '今日は気温が高いです。', exampleRomaji: 'Kyou wa kion ga takai desu.', exampleMeaning: 'Hôm nay nhiệt độ cao.' },
  { word: '長靴', reading: 'ながぐつ', romaji: 'nagagutsu', meaning: 'Ủng', example: '畑では長靴を履いてください。', exampleRomaji: 'Hatake de wa nagagutsu o haite kudasai.', exampleMeaning: 'Trong ruộng hãy mang ủng.' },
  { word: '雨具', reading: 'あまぐ', romaji: 'amagu', meaning: 'Đồ đi mưa', example: '雨具を持って行ってください。', exampleRomaji: 'Amagu o motte itte kudasai.', exampleMeaning: 'Xin hãy mang đồ đi mưa.' },
  { word: '休憩所', reading: 'きゅうけいじょ', romaji: 'kyuukeijo', meaning: 'Chỗ nghỉ', example: '休憩所で水を飲みましょう。', exampleRomaji: 'Kyuukeijo de mizu o nomimashou.', exampleMeaning: 'Hãy uống nước ở chỗ nghỉ.' },
  { word: '出荷場', reading: 'しゅっかじょう', romaji: 'shukkajou', meaning: 'Khu xuất hàng', example: '箱は出荷場に運びます。', exampleRomaji: 'Hako wa shukkajou ni hakobimasu.', exampleMeaning: 'Thùng sẽ được chuyển đến khu xuất hàng.' },
  { word: '台車', reading: 'だいしゃ', romaji: 'daisha', meaning: 'Xe đẩy', example: '台車を使ってください。', exampleRomaji: 'Daisha o tsukatte kudasai.', exampleMeaning: 'Xin hãy dùng xe đẩy.' },
  { word: '腰', reading: 'こし', romaji: 'koshi', meaning: 'Lưng', example: '腰が痛いです。', exampleRomaji: 'Koshi ga itai desu.', exampleMeaning: 'Tôi bị đau lưng.' },
  { word: '熱中症', reading: 'ねっちゅうしょう', romaji: 'necchuushou', meaning: 'Sốc nhiệt', example: '暑い日は熱中症に気をつけてください。', exampleRomaji: 'Atsui hi wa necchuushou ni ki o tsukete kudasai.', exampleMeaning: 'Ngày nóng hãy cẩn thận sốc nhiệt.' },
  { word: '休み希望', reading: 'やすみきぼう', romaji: 'yasumi kibou', meaning: 'Nguyện vọng nghỉ', example: '来週の休み希望を出してください。', exampleRomaji: 'Raishuu no yasumi kibou o dashite kudasai.', exampleMeaning: 'Xin hãy nộp nguyện vọng nghỉ tuần sau.' },

  { word: '飲食店', reading: 'いんしょくてん', romaji: 'inshokuten', meaning: 'Nhà hàng / quán ăn', example: '飲食店で働いています。', exampleRomaji: 'Inshokuten de hataraite imasu.', exampleMeaning: 'Tôi làm ở nhà hàng.' },
  { word: '注文', reading: 'ちゅうもん', romaji: 'chuumon', meaning: 'Gọi món / đơn gọi món', example: 'ご注文をお願いします。', exampleRomaji: 'Gochuumon o onegaishimasu.', exampleMeaning: 'Xin cho tôi nhận order.' },
  { word: '予約', reading: 'よやく', romaji: 'yoyaku', meaning: 'Đặt chỗ', example: '予約のお客様です。', exampleRomaji: 'Yoyaku no okyakusama desu.', exampleMeaning: 'Đây là khách đã đặt chỗ.' },
  { word: '満席', reading: 'まんせき', romaji: 'manseki', meaning: 'Hết chỗ', example: '今は満席です。', exampleRomaji: 'Ima wa manseki desu.', exampleMeaning: 'Hiện tại đã hết chỗ.' },
  { word: '厨房', reading: 'ちゅうぼう', romaji: 'chuubou', meaning: 'Bếp', example: '厨房に伝えます。', exampleRomaji: 'Chuubou ni tsutaemasu.', exampleMeaning: 'Tôi sẽ báo cho bếp.' },
  { word: '洗い場', reading: 'あらいば', romaji: 'araiba', meaning: 'Khu rửa chén', example: '洗い場を手伝ってください。', exampleRomaji: 'Araiba o tetsudatte kudasai.', exampleMeaning: 'Xin hãy phụ khu rửa chén.' },
  { word: '片付け', reading: 'かたづけ', romaji: 'katazuke', meaning: 'Dọn bàn / dọn dẹp', example: 'テーブルを片付けます。', exampleRomaji: 'Teeburu o katazukemasu.', exampleMeaning: 'Tôi dọn bàn.' },
  { word: '会計', reading: 'かいけい', romaji: 'kaikei', meaning: 'Tính tiền', example: 'レジで会計します。', exampleRomaji: 'Reji de kaikei shimasu.', exampleMeaning: 'Tôi tính tiền ở quầy.' },
  { word: 'お釣り', reading: 'おつり', romaji: 'otsuri', meaning: 'Tiền thối lại', example: 'お釣りはこちらです。', exampleRomaji: 'Otsuri wa kochira desu.', exampleMeaning: 'Tiền thối đây ạ.' },
  { word: 'レジ', reading: 'レジ', romaji: 'reji', meaning: 'Quầy tính tiền', example: 'レジをお願いします。', exampleRomaji: 'Reji o onegaishimasu.', exampleMeaning: 'Xin phụ trách quầy thu ngân.' },
  { word: '取り皿', reading: 'とりざら', romaji: 'torizara', meaning: 'Đĩa nhỏ chia món', example: '取り皿をお持ちします。', exampleRomaji: 'Torizara o omochi shimasu.', exampleMeaning: 'Tôi sẽ mang đĩa nhỏ ra.' },
  { word: '箸', reading: 'はし', romaji: 'hashi', meaning: 'Đũa', example: 'お箸をお持ちします。', exampleRomaji: 'Ohashi o omochi shimasu.', exampleMeaning: 'Tôi sẽ mang đũa ra.' },
  { word: 'スプーン', reading: 'スプーン', romaji: 'supuun', meaning: 'Muỗng', example: 'スプーンは必要ですか。', exampleRomaji: 'Supuun wa hitsuyou desu ka.', exampleMeaning: 'Quý khách có cần muỗng không?' },
  { word: '持ち帰り', reading: 'もちかえり', romaji: 'mochikaeri', meaning: 'Mang về', example: '持ち帰りですか。', exampleRomaji: 'Mochikaeri desu ka.', exampleMeaning: 'Quý khách mang về phải không?' },
  { word: '店内', reading: 'てんない', romaji: 'tennai', meaning: 'Dùng tại quán', example: '店内でお召し上がりですか。', exampleRomaji: 'Tennai de omeshiagari desu ka.', exampleMeaning: 'Quý khách dùng tại quán phải không?' },
  { word: 'おすすめ', reading: 'おすすめ', romaji: 'osusume', meaning: 'Món gợi ý', example: '今日のおすすめはこちらです。', exampleRomaji: 'Kyou no osusume wa kochira desu.', exampleMeaning: 'Món gợi ý hôm nay là món này.' },
  { word: '品切れ', reading: 'しなぎれ', romaji: 'shinagire', meaning: 'Hết món', example: '申し訳ありませんが、品切れです。', exampleRomaji: 'Moushiwake arimasen ga, shinagire desu.', exampleMeaning: 'Xin lỗi, món này đã hết.' },
  { word: '配膳', reading: 'はいぜん', romaji: 'haizen', meaning: 'Phục vụ món', example: '料理を配膳します。', exampleRomaji: 'Ryouri o haizen shimasu.', exampleMeaning: 'Tôi mang món ra phục vụ.' },
  { word: '下げる', reading: 'さげる', romaji: 'sageru', meaning: 'Dọn bát đĩa xuống', example: '空いた皿を下げます。', exampleRomaji: 'Aita sara o sagemasu.', exampleMeaning: 'Tôi dọn đĩa trống xuống.' },
  { word: 'シフト', reading: 'シフト', romaji: 'shifuto', meaning: 'Ca làm', example: '来週のシフトを確認しました。', exampleRomaji: 'Raishuu no shifuto o kakunin shimashita.', exampleMeaning: 'Tôi đã kiểm tra ca làm tuần sau.' },
];

const INDUSTRY_PHRASES: PhraseCategory[] = [
  {
    category: 'Công việc nhà máy',
    icon: 'construct',
    color: '#34495E',
    phrases: [
      { jp: '今日はラインに入ります。', romaji: 'Kyou wa rain ni hairimasu.', vn: 'Hôm nay tôi vào dây chuyền.' },
      { jp: '不良品は別にしてください。', romaji: 'Furyouhin wa betsu ni shite kudasai.', vn: 'Xin hãy tách hàng lỗi ra riêng.' },
      { jp: '数量をもう一度確認します。', romaji: 'Suuryou o mou ichido kakunin shimasu.', vn: 'Tôi sẽ kiểm tra lại số lượng một lần nữa.' },
      { jp: 'この機械を止めてもいいですか。', romaji: 'Kono kikai o tomete mo ii desu ka.', vn: 'Tôi có thể dừng máy này không?' },
      { jp: '休憩の後で梱包を始めます。', romaji: 'Kyuukei no ato de konpou o hajimemasu.', vn: 'Sau giờ nghỉ tôi sẽ bắt đầu đóng gói.' },
      { jp: '残業できません。予定があります。', romaji: 'Zangyou dekimasen. Yotei ga arimasu.', vn: 'Tôi không thể tăng ca. Tôi có việc.' },
    ],
    dialogue: {
      situation: 'Báo với quản lý chuyền về hàng lỗi',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません。不良品がありました。確認をお願いします。', romaji: 'Sumimasen. Furyouhin ga arimashita. Kakunin o onegaishimasu.', vn: 'Xin lỗi, có hàng lỗi. Nhờ anh/chị kiểm tra giúp.' },
        { speaker: 'B', speakerLabel: 'Quản lý', jp: 'わかりました。箱を止めて、こちらに持ってきてください。', romaji: 'Wakarimashita. Hako o tomete, kochira ni motte kite kudasai.', vn: 'Đã rõ. Hãy dừng thùng đó lại rồi mang qua đây.' },
      ],
    },
  },
  {
    category: 'Công việc xây dựng',
    icon: 'hammer',
    color: '#D35400',
    phrases: [
      { jp: 'ヘルメットと安全帯を着けてください。', romaji: 'Herumetto to anzentai o tsukete kudasai.', vn: 'Xin hãy đội mũ và đeo dây an toàn.' },
      { jp: 'この場所は危険です。', romaji: 'Kono basho wa kiken desu.', vn: 'Vị trí này nguy hiểm.' },
      { jp: '図面を見ながら寸法を確認します。', romaji: 'Zumen o minagara sunpou o kakunin shimasu.', vn: 'Tôi vừa xem bản vẽ vừa kiểm tra kích thước.' },
      { jp: '資材を二階へ運びます。', romaji: 'Shizai o nikai e hakobimasu.', vn: 'Tôi chuyển vật liệu lên tầng 2.' },
      { jp: '雨なので今日は休工です。', romaji: 'Ame na node kyou wa kyuukou desu.', vn: 'Hôm nay nghỉ thi công vì mưa.' },
      { jp: '朝礼の後で作業指示を確認しましょう。', romaji: 'Chourei no ato de sagyou shiji o kakunin shimashou.', vn: 'Sau họp sáng hãy xác nhận chỉ thị công việc.' },
    ],
    dialogue: {
      situation: 'Xin xác nhận an toàn trước khi làm trên cao',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: '高所作業の前に安全帯を確認したいです。', romaji: 'Kousho sagyou no mae ni anzentai o kakunin shitai desu.', vn: 'Trước khi làm trên cao tôi muốn kiểm tra dây an toàn.' },
        { speaker: 'B', speakerLabel: 'Giám sát', jp: 'いいです。足場の状態も一緒に見てください。', romaji: 'Ii desu. Ashiba no joutai mo issho ni mite kudasai.', vn: 'Được. Hãy kiểm tra luôn cả tình trạng giàn giáo.' },
      ],
    },
  },
  {
    category: 'Công việc nông nghiệp',
    icon: 'leaf',
    color: '#27AE60',
    phrases: [
      { jp: '今日はトマトを収穫します。', romaji: 'Kyou wa tomato o shuukaku shimasu.', vn: 'Hôm nay tôi thu hoạch cà chua.' },
      { jp: '苗を植える前に土を確認してください。', romaji: 'Nae o ueru mae ni tsuchi o kakunin shite kudasai.', vn: 'Xin hãy kiểm tra đất trước khi trồng cây giống.' },
      { jp: '朝のうちに水やりをします。', romaji: 'Asa no uchi ni mizuyari o shimasu.', vn: 'Tôi sẽ tưới nước trong buổi sáng.' },
      { jp: '大きさごとに選別してください。', romaji: 'Ookisa goto ni senbetsu shite kudasai.', vn: 'Xin hãy phân loại theo từng cỡ.' },
      { jp: '暑いので熱中症に気をつけましょう。', romaji: 'Atsui node necchuushou ni ki o tsukemashou.', vn: 'Trời nóng nên hãy cẩn thận sốc nhiệt.' },
      { jp: '箱詰めが終わったら出荷場へ運びます。', romaji: 'Hakodume ga owattara shukkajou e hakobimasu.', vn: 'Đóng thùng xong thì chuyển đến khu xuất hàng.' },
    ],
    dialogue: {
      situation: 'Báo đau lưng và xin đổi việc nặng',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません。少し腰が痛いので、軽い作業に変えてもいいですか。', romaji: 'Sumimasen. Sukoshi koshi ga itai node, karui sagyou ni kaete mo ii desu ka.', vn: 'Xin lỗi, tôi hơi đau lưng nên có thể đổi sang việc nhẹ hơn không?' },
        { speaker: 'B', speakerLabel: 'Quản lý', jp: 'わかりました。今日は選別をお願いします。', romaji: 'Wakarimashita. Kyou wa senbetsu o onegaishimasu.', vn: 'Được. Hôm nay bạn làm phần phân loại nhé.' },
      ],
    },
  },
  {
    category: 'Công việc nhà hàng',
    icon: 'restaurant',
    color: '#8E44AD',
    phrases: [
      { jp: 'ご注文をお伺いします。', romaji: 'Gochuumon o oukagai shimasu.', vn: 'Em xin nhận món ạ.' },
      { jp: '申し訳ありません。本日は満席です。', romaji: 'Moushiwake arimasen. Honjitsu wa manseki desu.', vn: 'Xin lỗi, hôm nay quán đã hết chỗ.' },
      { jp: '店内ですか、持ち帰りですか。', romaji: 'Tennai desu ka, mochikaeri desu ka.', vn: 'Quý khách dùng tại quán hay mang về ạ?' },
      { jp: 'おすすめはこちらです。', romaji: 'Osusume wa kochira desu.', vn: 'Món gợi ý là món này ạ.' },
      { jp: '品切れのため、別の料理をお願いします。', romaji: 'Shinagire no tame, betsu no ryouri o onegaishimasu.', vn: 'Vì món đó đã hết, xin quý khách chọn món khác ạ.' },
      { jp: 'お会計はこちらでお願いします。', romaji: 'Okaikei wa kochira de onegaishimasu.', vn: 'Xin thanh toán tại đây ạ.' },
    ],
    dialogue: {
      situation: 'Xác nhận order tại nhà hàng',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ご注文はラーメン一つと餃子一つでよろしいですか。', romaji: 'Gochuumon wa raamen hitotsu to gyouza hitotsu de yoroshii desu ka.', vn: 'Em xin xác nhận, mình gọi 1 ramen và 1 gyoza đúng không ạ?' },
        { speaker: 'B', speakerLabel: 'Khách', jp: 'はい。あと水をお願いします。', romaji: 'Hai. Ato mizu o onegaishimasu.', vn: 'Vâng. Và cho tôi thêm nước nhé.' },
      ],
    },
  },
];

JAPANESE_WORDS.push(...INDUSTRY_JAPANESE_WORDS);
ESSENTIAL_PHRASES.push(...INDUSTRY_PHRASES);

export const GRAMMAR_PATTERNS: GrammarPattern[] = [
  {
    pattern: '〜です',
    meaning: 'Là / Đây là (câu lịch sự, khẳng định)',
    example_jp: '私はベトナム人です。',
    example_romaji: 'Watashi wa Betonamu-jin desu.',
    example_vn: 'Tôi là người Việt Nam.',
    notes: 'Dùng cuối câu để khẳng định lịch sự. Phủ định: 〜ではありません / 〜じゃないです.',
  },
  {
    pattern: '〜ます / 〜ません',
    meaning: 'Làm / Không làm (động từ lịch sự)',
    example_jp: '毎日日本語を勉強します。',
    example_romaji: 'Mainichi Nihongo o benkyou shimasu.',
    example_vn: 'Tôi học tiếng Nhật mỗi ngày.',
    notes: '〜ます (khẳng định) / 〜ません (phủ định) / 〜ましたか (câu hỏi quá khứ).',
  },
  {
    pattern: '〜てください',
    meaning: 'Xin hãy làm 〜 (yêu cầu lịch sự)',
    example_jp: 'ここに名前を書いてください。',
    example_romaji: 'Koko ni namae o kaite kudasai.',
    example_vn: 'Xin hãy viết tên vào đây.',
    notes: 'Dùng khi nhờ ai đó làm gì. Thêm 〜ていただけますか để lịch sự hơn.',
  },
  {
    pattern: '〜たいです',
    meaning: 'Muốn làm 〜',
    example_jp: '日本語が上手になりたいです。',
    example_romaji: 'Nihongo ga jouzu ni naritai desu.',
    example_vn: 'Tôi muốn giỏi tiếng Nhật.',
    notes: 'Gốc động từ + たい. Phủ định: 〜たくないです. Không dùng cho mong muốn của người khác.',
  },
  {
    pattern: '〜ています',
    meaning: 'Đang làm 〜 / Trạng thái hiện tại',
    example_jp: '今、工場で働いています。',
    example_romaji: 'Ima, koujou de hataraite imasu.',
    example_vn: 'Tôi đang làm việc ở nhà máy.',
    notes: 'Dùng cho hành động đang diễn ra hoặc trạng thái kéo dài (ví dụ: 結婚しています = đã kết hôn).',
  },
  {
    pattern: '〜てもいいですか',
    meaning: 'Có được phép làm 〜 không?',
    example_jp: 'ここで写真を撮ってもいいですか。',
    example_romaji: 'Koko de shashin o totte mo ii desu ka.',
    example_vn: 'Tôi có thể chụp ảnh ở đây không?',
    notes: 'Xin phép lịch sự. Trả lời cho phép: はい、どうぞ. Từ chối: ちょっと….',
  },
  {
    pattern: '〜なければなりません',
    meaning: 'Phải làm 〜 (bắt buộc)',
    example_jp: '毎月税金を払わなければなりません。',
    example_romaji: 'Maitsuki zeikin o harawanakereba narimasen.',
    example_vn: 'Mỗi tháng tôi phải đóng thuế.',
    notes: 'Dạng nói thân mật hơn: 〜なきゃ / 〜ないといけない. Dùng nhiều trong ngữ cảnh công việc, thủ tục.',
  },
  {
    pattern: '〜ないでください',
    meaning: 'Xin đừng làm 〜',
    example_jp: 'ここでタバコを吸わないでください。',
    example_romaji: 'Koko de tabako o suwanaide kudasai.',
    example_vn: 'Xin đừng hút thuốc ở đây.',
    notes: 'Phủ định của 〜てください. Thường thấy trên bảng hiệu hoặc khi nhắc nhở lịch sự.',
  },
];
