import type { JapaneseWord, PhraseCategory } from '../../types/content';

export const JAPANESE_WORDS: JapaneseWord[] = [
  {
    word: '在留カード',
    reading: 'ざいりゅうカード',
    romaji: 'Zairyu Kaado',
    meaning: 'Thẻ cư trú',
    example: '在留カードを更新する必要があります。',
    exampleRomaji: 'Zairyu kaado wo koushin suru hitsuyou ga arimasu.',
    exampleMeaning: 'Tôi cần gia hạn thẻ cư trú.',
    culturalNote: 'Phải mang theo người mọi lúc. Nếu cảnh sát kiểm tra mà không có → có thể bị phạt đến ¥200,000. Gia hạn trước 3 tháng khi sắp hết hạn.',
  },
  {
    word: 'マイナンバー',
    reading: 'マイナンバー',
    romaji: 'Mainanbaа',
    meaning: 'Mã số cá nhân (My Number)',
    example: 'マイナンバーカードを申請しました。',
    exampleRomaji: 'Mainanbaа kaado wo shinsei shimashita.',
    exampleMeaning: 'Tôi đã đăng ký thẻ My Number.',
    culturalNote: 'Từ tháng 4/2026 bắt buộc dùng マイナ保険証 (thẻ My Number tích hợp bảo hiểm) khi đi khám bệnh. Giữ bí mật số này — không được gửi ảnh qua mạng.',
  },
  {
    word: '住民票',
    reading: 'じゅうみんひょう',
    romaji: 'Juuminhyou',
    meaning: 'Giấy xác nhận cư trú',
    example: '住民票を区役所でもらいました。',
    exampleRomaji: 'Juuminhyou wo kuyakusho de moraimashita.',
    exampleMeaning: 'Tôi đã lấy giấy xác nhận cư trú tại UBND quận.',
    culturalNote: 'Cần khi mở tài khoản ngân hàng, đăng ký điện thoại, thuê nhà. Lấy tại コンビニ (7-Eleven, FamilyMart) bằng máy tự động chỉ mất ¥200–300 — nhanh hơn đến phường.',
  },
  {
    word: 'お疲れ様です',
    reading: 'おつかれさまです',
    romaji: 'Otsukaresama desu',
    meaning: 'Bạn đã làm việc vất vả',
    example: '今日もお疲れ様です！',
    exampleRomaji: 'Kyou mo otsukaresama desu!',
    exampleMeaning: 'Hôm nay bạn cũng đã vất vả!',
    culturalNote: 'Câu chào quan trọng nhất khi kết thúc ngày làm. Nói với đồng nghiệp và cấp trên. Không nói với khách hàng — dùng "ありがとうございました" cho khách.',
  },
  {
    word: '宜しくお願いします',
    reading: 'よろしくおねがいします',
    romaji: 'Yoroshiku onegaishimasu',
    meaning: 'Mong bạn chỉ giáo / Rất vui được hợp tác',
    example: '初めまして、よろしくお願いします。',
    exampleRomaji: 'Hajimemashite, yoroshiku onegaishimasu.',
    exampleMeaning: 'Rất vui được làm quen, mong bạn chỉ giáo.',
    culturalNote: 'Câu đa năng nhất tiếng Nhật — dùng khi gặp lần đầu, khi nhờ giúp đỡ, khi bắt đầu email, khi giao bài. Cúi đầu nhẹ khi nói câu này.',
  },
  {
    word: '残業',
    reading: 'ざんぎょう',
    romaji: 'Zangyou',
    meaning: 'Làm thêm giờ (OT)',
    example: '今日は残業があります。',
    exampleRomaji: 'Kyou wa zangyou ga arimasu.',
    exampleMeaning: 'Hôm nay có làm thêm giờ.',
    culturalNote: 'Luật giới hạn tối đa 45 giờ OT/tháng và 360 giờ/năm. OT phải trả thêm ít nhất 25%. Nếu công ty ép OT không trả tiền → liên hệ 労働基準監督署 (0120-811-610).',
  },
  {
    word: '有給休暇',
    reading: 'ゆうきゅうきゅうか',
    romaji: 'Yuukyuu kyuuka',
    meaning: 'Nghỉ phép có lương',
    example: '有給休暇を取りたいです。',
    exampleRomaji: 'Yuukyuu kyuuka wo toritai desu.',
    exampleMeaning: 'Tôi muốn xin nghỉ phép có lương.',
    culturalNote: 'Sau 6 tháng làm liên tục được 10 ngày phép. Đây là quyền lợi hợp pháp — không cần giải thích lý do. Chủ lao động không được từ chối hoàn toàn, chỉ có thể đề nghị đổi ngày.',
  },
  {
    word: '給料',
    reading: 'きゅうりょう',
    romaji: 'Kyuuryou',
    meaning: 'Tiền lương',
    example: '給料日はいつですか？',
    exampleRomaji: 'Kyuuryoubi wa itsu desu ka?',
    exampleMeaning: 'Ngày lãnh lương là khi nào?',
    culturalNote: 'Nhật thường trả lương tháng (25 hoặc 末日 cuối tháng). Kiểm tra 給与明細 (bảng lương) mỗi tháng — có 税金 (thuế), 社会保険料 (bảo hiểm xã hội) bị khấu trừ.',
  },
  {
    word: '病院',
    reading: 'びょういん',
    romaji: 'Byouin',
    meaning: 'Bệnh viện',
    example: '病院に行かなければなりません。',
    exampleRomaji: 'Byouin ni ikanakereba narimasen.',
    exampleMeaning: 'Tôi phải đi bệnh viện.',
    culturalNote: 'Phòng khám nhỏ (診療所/クリニック) phù hợp bệnh thường — không cần giấy giới thiệu và rẻ hơn. Bệnh viện lớn (大病院) cần 紹介状 (referral) từ bác sĩ nhỏ, nếu không có bị thu thêm phí.',
  },
  {
    word: '保険証',
    reading: 'ほけんしょう',
    romaji: 'Hokenshou',
    meaning: 'Thẻ bảo hiểm y tế',
    example: '保険証を忘れずに持ってきてください。',
    exampleRomaji: 'Hokenshou wo wasurezu ni motte kite kudasai.',
    exampleMeaning: 'Đừng quên mang thẻ bảo hiểm.',
    culturalNote: 'Thẻ giấy truyền thống (紙の保険証) hết hiệu lực từ tháng 12/2024. Hiện cần dùng マイナ保険証 hoặc 資格確認書. Không mang → phải trả 100% chi phí rồi xin hoàn lại sau.',
  },
  {
    word: '電車',
    reading: 'でんしゃ',
    romaji: 'Densha',
    meaning: 'Tàu điện',
    example: '電車で通勤しています。',
    exampleRomaji: 'Densha de tsuukin shite imasu.',
    exampleMeaning: 'Tôi đi làm bằng tàu điện.',
    culturalNote: 'Tàu Nhật nổi tiếng đúng giờ đến từng giây. Trễ 1 phút đã là tin tức. Nếu tàu trễ, lấy 遅延証明書 (giấy chứng nhận tàu trễ) tại cửa ga — miễn phí, hợp lệ báo sếp.',
  },
  {
    word: '乗り換え',
    reading: 'のりかえ',
    romaji: 'Norikae',
    meaning: 'Đổi tàu / Chuyển tuyến',
    example: '渋谷で乗り換えてください。',
    exampleRomaji: 'Shibuya de norikae te kudasai.',
    exampleMeaning: 'Hãy đổi tàu tại Shibuya.',
    culturalNote: 'Dùng app Yahoo!乗換案内 hoặc Google Maps để tìm đường đổi tàu. Thẻ IC (Suica/ICOCA) tự tính phí qua các tuyến — tiện hơn mua vé từng chặng.',
  },
  {
    word: '定期券',
    reading: 'ていきけん',
    romaji: 'Teikiken',
    meaning: 'Vé tháng (tàu/xe bus)',
    example: '定期券を購入しました。',
    exampleRomaji: 'Teikiken wo konyuu shimashita.',
    exampleMeaning: 'Tôi đã mua vé tháng.',
    culturalNote: 'Nhiều công ty trả 交通費 (phụ cấp đi lại). Hỏi HR về 通勤手当. Vé tháng thường mua 1, 3, hoặc 6 tháng — 6 tháng rẻ nhất tính theo ngày.',
  },
  {
    word: '家賃',
    reading: 'やちん',
    romaji: 'Yachin',
    meaning: 'Tiền thuê nhà',
    example: '家賃は毎月払います。',
    exampleRomaji: 'Yachin wa maitsuки haraimasu.',
    exampleMeaning: 'Tiền thuê nhà phải trả hàng tháng.',
    culturalNote: 'Ngoài gia tiền còn có 敷金 (tiền đặt cọc, 1-2 tháng), 礼金 (tiền cảm ơn chủ nhà, không hoàn lại). Cộng thêm 仲介手数料 (hoa hồng môi giới) = chi phí ban đầu rất lớn.',
  },
  {
    word: 'ゴミ',
    reading: 'ゴミ',
    romaji: 'Gomi',
    meaning: 'Rác',
    example: 'ゴミは月・木に出してください。',
    exampleRomaji: 'Gomi wa getsu/moku ni dashite kudasai.',
    exampleMeaning: 'Vui lòng đổ rác vào thứ 2 và thứ 5.',
    culturalNote: 'Vi phạm phân loại rác có thể bị hàng xóm phàn nàn hoặc rác không được thu. Mỗi quận có lịch và quy tắc khác nhau — nhận tờ rơi từ chủ nhà hoặc phường khi mới chuyển đến.',
  },
  {
    word: '口座',
    reading: 'こうざ',
    romaji: 'Kouza',
    meaning: 'Tài khoản ngân hàng',
    example: '銀行口座を開設したいです。',
    exampleRomaji: 'Ginkou kouza wo kaisetsu shitai desu.',
    exampleMeaning: 'Tôi muốn mở tài khoản ngân hàng.',
    culturalNote: 'Nhiều ngân hàng yêu cầu ở Nhật ít nhất 6 tháng. Dễ mở nhất là ゆうちょ銀行 (ngân hàng bưu điện) hoặc セブン銀行. Mang: thẻ cư trú + マイナンバー + con dấu (inkan) nếu có.',
  },
  {
    word: '振込',
    reading: 'ふりこみ',
    romaji: 'Furikomi',
    meaning: 'Chuyển khoản ngân hàng',
    example: '給料は振込で支払います。',
    exampleRomaji: 'Kyuuryou wa furikomi de shiharaimasu.',
    exampleMeaning: 'Lương sẽ được trả qua chuyển khoản.',
    culturalNote: 'Chuyển khoản tại ATM trong cùng ngân hàng miễn phí. Khác ngân hàng thường mất phí ¥110-440. Gửi tiền về Việt Nam qua Wise/SBI Remit/ゆうちょ rẻ hơn ngân hàng truyền thống.',
  },
  {
    word: '履歴書',
    reading: 'りれきしょ',
    romaji: 'Rirekisho',
    meaning: 'CV / Hồ sơ xin việc',
    example: '履歴書を書いています。',
    exampleRomaji: 'Rirekisho wo kaite imasu.',
    exampleMeaning: 'Tôi đang viết CV.',
    culturalNote: 'CV Nhật theo mẫu cố định (JIS規格), phải dán ảnh 4×3cm chụp trong 3 tháng, mặc trang trọng. Viết tay được đánh giá cao hơn đánh máy trong nhiều trường hợp.',
  },
  {
    word: '面接',
    reading: 'めんせつ',
    romaji: 'Mensetsu',
    meaning: 'Phỏng vấn',
    example: '明日面接があります。',
    exampleRomaji: 'Ashita mensetsu ga arimasu.',
    exampleMeaning: 'Ngày mai tôi có phỏng vấn.',
    culturalNote: 'Đến sớm 5 phút (không phải 10-15 phút). Tắt điện thoại hoặc im lặng. Cúi đầu khi vào và ra. Mặc suit tối màu nếu phỏng vấn công ty lớn. Kết thúc nói "よろしくお願いいたします".',
  },
  {
    word: '確定申告',
    reading: 'かくていしんこく',
    romaji: 'Kakutei shinkoku',
    meaning: 'Khai thuế thu nhập',
    example: '確定申告は3月15日までです。',
    exampleRomaji: 'Kakutei shinkoku wa sangatsu juugo nichi made desu.',
    exampleMeaning: 'Hạn nộp khai thuế là ngày 15/3.',
    culturalNote: 'Nhân viên văn phòng thường do công ty khai hộ (年末調整). Làm nhiều nơi cùng lúc, có thu nhập phụ, hoặc freelance → phải tự khai từ 16/2 đến 15/3. Khai qua e-Tax online tiện nhất.',
  },
];

export const ESSENTIAL_PHRASES: PhraseCategory[] = [
  {
    category: 'Chào hỏi cơ bản',
    icon: 'hand-left',
    color: '#185FA5',
    phrases: [
      { jp: 'おはようございます', romaji: 'Ohayou gozaimasu', vn: 'Chào buổi sáng (trang trọng)' },
      { jp: 'こんにちは', romaji: 'Konnichiwa', vn: 'Xin chào (ban ngày)' },
      { jp: 'こんばんは', romaji: 'Konbanwa', vn: 'Chào buổi tối' },
      { jp: 'ありがとうございます', romaji: 'Arigatou gozaimasu', vn: 'Cảm ơn bạn rất nhiều' },
      { jp: 'すみません', romaji: 'Sumimasen', vn: 'Xin lỗi / Xin phép / Gọi người' },
      { jp: 'どうぞよろしくお願いします', romaji: 'Douzo yoroshiku onegaishimasu', vn: 'Rất vui được làm quen' },
      { jp: 'お名前は何ですか？', romaji: 'Onamae wa nan desu ka?', vn: 'Tên bạn là gì?' },
      { jp: 'ベトナム人です', romaji: 'Betonamu jin desu', vn: 'Tôi là người Việt Nam' },
    ],
    dialogue: {
      situation: '🏢 Ngày đầu đi làm — gặp đồng nghiệp',
      lines: [
        { speaker: 'B', speakerLabel: 'Đồng nghiệp', jp: 'おはようございます！新しいスタッフの方ですか？', romaji: 'Ohayou gozaimasu! Atarashii sutaffu no kata desu ka?', vn: 'Chào buổi sáng! Bạn là nhân viên mới phải không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、今日からお世話になります。グエンと申します。', romaji: 'Hai, kyou kara osewa ni narimasu. Nguyen to moushimasu.', vn: 'Vâng, từ hôm nay tôi nhờ mọi người chỉ bảo. Tôi tên là Nguyễn.' },
        { speaker: 'B', speakerLabel: 'Đồng nghiệp', jp: 'こちらこそ、よろしくお願いします！どこから来ましたか？', romaji: 'Kochirakoso, yoroshiku onegaishimasu! Doko kara kimashita ka?', vn: 'Rất vui được làm quen! Bạn đến từ đâu vậy?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ベトナムから来ました。日本語はまだ勉強中です。', romaji: 'Betonamu kara kimashita. Nihongo wa mada benkyou chuu desu.', vn: 'Tôi đến từ Việt Nam. Tôi vẫn đang học tiếng Nhật.' },
        { speaker: 'B', speakerLabel: 'Đồng nghiệp', jp: 'すごいですね！何かわからないことがあれば聞いてください。', romaji: 'Sugoi desu ne! Nanika wakaranai koto ga areba kiite kudasai.', vn: 'Giỏi quá! Nếu có gì không hiểu cứ hỏi nhé.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ありがとうございます。よろしくお願いします！', romaji: 'Arigatou gozaimasu. Yoroshiku onegaishimasu!', vn: 'Cảm ơn bạn. Mong bạn giúp đỡ!' },
      ],
    },
  },
  {
    category: 'Giao tiếp cơ bản',
    icon: 'chatbubbles',
    color: '#2980B9',
    phrases: [
      { jp: 'わかりました', romaji: 'Wakarimashita', vn: 'Tôi hiểu rồi' },
      { jp: 'わかりません', romaji: 'Wakarimasen', vn: 'Tôi không hiểu' },
      { jp: 'もう一度言ってください', romaji: 'Mou ichido itte kudasai', vn: 'Xin hãy nói lại một lần nữa' },
      { jp: 'ゆっくり話してください', romaji: 'Yukkuri hanashite kudasai', vn: 'Xin hãy nói chậm hơn' },
      { jp: '日本語が少しわかります', romaji: 'Nihongo ga sukoshi wakarimasu', vn: 'Tôi hiểu tiếng Nhật một chút' },
      { jp: '日本語があまりうまくありません', romaji: 'Nihongo ga amari umaku arimasen', vn: 'Tiếng Nhật của tôi chưa tốt lắm' },
      { jp: '書いていただけますか？', romaji: 'Kaite itadakemasu ka?', vn: 'Bạn có thể viết ra được không?' },
      { jp: 'はい / いいえ', romaji: 'Hai / Iie', vn: 'Vâng / Không' },
    ],
    dialogue: {
      situation: '📋 Khi sếp giao nhiệm vụ nhưng không hiểu rõ',
      lines: [
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'このレポートを明日の午前中までに仕上げておいてください。', romaji: 'Kono repooto wo ashita no gozenchuu made ni shiagete oite kudasai.', vn: 'Hãy hoàn thiện báo cáo này trước buổi sáng ngày mai.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、もう一度ゆっくり言っていただけますか？', romaji: 'Sumimasen, mou ichido yukkuri itte itadakemasu ka?', vn: 'Xin lỗi, bạn có thể nói lại chậm hơn không?' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'レポートを…明日の午前中までに…完成させてください。', romaji: 'Repooto wo... ashita no gozenchuu made ni... kansei sasete kudasai.', vn: 'Báo cáo này... trước buổi sáng ngày mai... hoàn thành.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、書いていただけますか？日本語がまだ難しくて…', romaji: 'Sumimasen, kaite itadakemasu ka? Nihongo ga mada muzukashikute...', vn: 'Xin lỗi, bạn có thể viết ra không? Tiếng Nhật vẫn còn khó với tôi...' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'もちろん。はい、これを見てください。わかりましたか？', romaji: 'Mochiron. Hai, kore wo mite kudasai. Wakarimashita ka?', vn: 'Tất nhiên. Đây, nhìn cái này. Hiểu rồi chưa?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、わかりました。ありがとうございます！', romaji: 'Hai, wakarimashita. Arigatou gozaimasu!', vn: 'Vâng, tôi hiểu rồi. Cảm ơn bạn!' },
      ],
    },
  },
  {
    category: 'Mua sắm / Convenience store',
    icon: 'basket',
    color: '#E67E22',
    phrases: [
      { jp: 'これはいくらですか？', romaji: 'Kore wa ikura desu ka?', vn: 'Cái này giá bao nhiêu?' },
      { jp: 'カードで払えますか？', romaji: 'Kaado de haraemasu ka?', vn: 'Tôi có thể trả bằng thẻ không?' },
      { jp: '袋はいりません', romaji: 'Fukuro wa irimasen', vn: 'Không cần túi' },
      { jp: 'レシートをください', romaji: 'Reshiito wo kudasai', vn: 'Xin cho tôi hóa đơn' },
      { jp: '温めてもらえますか？', romaji: 'Atatamete moraemasu ka?', vn: 'Hâm nóng giúp tôi được không?' },
      { jp: 'ポイントカードはありますか？', romaji: 'Pointo kaado wa arimasu ka?', vn: 'Bạn có thẻ tích điểm không?' },
      { jp: '〜はどこですか？', romaji: '〜 wa doko desu ka?', vn: '... ở đâu ạ?' },
      { jp: 'PayPayで払います', romaji: 'PayPay de haraimasu', vn: 'Tôi trả bằng PayPay' },
    ],
    dialogue: {
      situation: '🏪 Tại 7-Eleven — mua弁当 buổi trưa',
      lines: [
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'いらっしゃいませ！', romaji: 'Irasshaimase!', vn: 'Chào mừng quý khách!' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、この弁当を温めてもらえますか？', romaji: 'Sumimasen, kono bentou wo atatamete moraemasu ka?', vn: 'Xin lỗi, làm ơn hâm nóng cơm hộp này giúp tôi.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'はい、少々お待ちください。お支払いはどうされますか？', romaji: 'Hai, shoushou omachi kudasai. Oshiharai wa dou saremasu ka?', vn: 'Vâng, xin chờ một chút. Bạn thanh toán thế nào?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'PayPayで払います。袋はいりません。', romaji: 'PayPay de haraimasu. Fukuro wa irimasen.', vn: 'Tôi trả bằng PayPay. Không cần túi đựng.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'ポイントカードはお持ちですか？', romaji: 'Pointo kaado wa omochi desu ka?', vn: 'Bạn có thẻ tích điểm không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'いいえ、大丈夫です。レシートもいりません。', romaji: 'Iie, daijoubu desu. Reshiito mo irimasen.', vn: 'Không, không cần. Cũng không cần hóa đơn.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'ありがとうございました！またお越しください。', romaji: 'Arigatou gozaimashita! Mata okoshi kudasai.', vn: 'Cảm ơn quý khách! Hẹn gặp lại.' },
      ],
    },
  },
  {
    category: 'Nhà hàng / Quán ăn',
    icon: 'restaurant',
    color: '#C0392B',
    phrases: [
      { jp: '一人です', romaji: 'Hitori desu', vn: 'Một người' },
      { jp: '二人です', romaji: 'Futari desu', vn: 'Hai người' },
      { jp: 'これをください', romaji: 'Kore wo kudasai', vn: 'Cho tôi cái này' },
      { jp: 'おすすめは何ですか？', romaji: 'Osusume wa nan desu ka?', vn: 'Món gì bạn giới thiệu?' },
      { jp: 'アレルギーがあります', romaji: 'Arerugii ga arimasu', vn: 'Tôi bị dị ứng' },
      { jp: '辛くしないでください', romaji: 'Karakunishinaide kudasai', vn: 'Xin đừng cho cay' },
      { jp: 'お会計をお願いします', romaji: 'Okaikei wo onegaishimasu', vn: 'Xin tính tiền' },
      { jp: '別々に払います', romaji: 'Betsubetsu ni haraimasu', vn: 'Chúng tôi trả riêng' },
    ],
    dialogue: {
      situation: '🍜 Tại quán ramen — gọi đồ và trả tiền',
      lines: [
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'いらっしゃいませ！何名様ですか？', romaji: 'Irasshaimase! Nanmei sama desu ka?', vn: 'Xin chào! Bao nhiêu người ạ?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '二人です。', romaji: 'Futari desu.', vn: 'Hai người.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'こちらへどうぞ。ご注文はお決まりですか？', romaji: 'Kochira e douzo. Gochuumon wa okimari desu ka?', vn: 'Mời vào đây. Bạn đã chọn món chưa?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'おすすめは何ですか？辛くないものがいいです。', romaji: 'Osusume wa nan desu ka? Karakunai mono ga ii desu.', vn: 'Món nào bạn giới thiệu? Tôi muốn món không cay.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: '醤油ラーメンがおすすめです。辛くないですよ。', romaji: 'Shouyu raamen ga osusume desu. Karakunai desu yo.', vn: 'Ramen nước tương là món tôi giới thiệu. Không cay đâu.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'じゃあ、二つください。あと、お会計をお願いします。', romaji: 'Jaa, futatsu kudasai. Ato, okaikei wo onegaishimasu.', vn: 'Vậy cho tôi hai tô. Và cho tôi tính tiền luôn nhé.' },
      ],
    },
  },
  {
    category: 'Tại ga / Tàu điện',
    icon: 'train',
    color: '#2980B9',
    phrases: [
      { jp: '〜駅まで行きたいです', romaji: '〜 eki made ikitai desu', vn: 'Tôi muốn đến ga ...' },
      { jp: 'この電車は〜に止まりますか？', romaji: 'Kono densha wa 〜 ni tomarimasu ka?', vn: 'Tàu này có dừng tại ... không?' },
      { jp: '乗り換えはどこですか？', romaji: 'Norikae wa doko desu ka?', vn: 'Điểm đổi tàu ở đâu?' },
      { jp: 'チャージをしたいです', romaji: 'Chaaji wo shitai desu', vn: 'Tôi muốn nạp tiền thẻ Suica/ICOCA' },
      { jp: '終電は何時ですか？', romaji: 'Shuden wa nanji desu ka?', vn: 'Chuyến tàu cuối lúc mấy giờ?' },
      { jp: '遅延証明書をください', romaji: 'Chien shoumeisho wo kudasai', vn: 'Xin cấp giấy chứng nhận tàu trễ' },
      { jp: '優先席があります', romaji: 'Yuusen seki ga arimasu', vn: 'Có ghế ưu tiên (nhường người cao tuổi, bầu)' },
    ],
    dialogue: {
      situation: '🚉 Tại cổng soát vé — tàu bị trễ, cần giấy chứng nhận',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、電車が遅れていますか？', romaji: 'Sumimasen, densha ga okurete imasu ka?', vn: 'Xin lỗi, tàu có bị trễ không?' },
        { speaker: 'B', speakerLabel: 'Nhân viên ga', jp: 'はい、信号トラブルで15分ほど遅れております。', romaji: 'Hai, shingou toraburu de juugofun hodo okurete orimasu.', vn: 'Vâng, do sự cố tín hiệu, tàu trễ khoảng 15 phút.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'わかりました。遅延証明書をいただけますか？', romaji: 'Wakarimashita. Chien shoumeisho wo itadakemasu ka?', vn: 'Tôi hiểu rồi. Tôi có thể xin giấy chứng nhận tàu trễ không?' },
        { speaker: 'B', speakerLabel: 'Nhân viên ga', jp: 'もちろんです。こちらをどうぞ。', romaji: 'Mochiron desu. Kochira wo douzo.', vn: 'Tất nhiên. Đây là giấy cho bạn.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ありがとうございます。新宿行きはどのホームですか？', romaji: 'Arigatou gozaimasu. Shinjuku yuki wa dono hoomu desu ka?', vn: 'Cảm ơn. Tàu đi Shinjuku ở sân ga nào?' },
        { speaker: 'B', speakerLabel: 'Nhân viên ga', jp: '3番線です。乗り換えは渋谷でしてください。', romaji: 'San banchi desu. Norikae wa Shibuya de shite kudasai.', vn: 'Sân ga số 3. Đổi tàu tại Shibuya nhé.' },
      ],
    },
  },
  {
    category: 'Tại bệnh viện',
    icon: 'medical',
    color: '#E74C3C',
    phrases: [
      { jp: '具合が悪いです', romaji: 'Guai ga warui desu', vn: 'Tôi cảm thấy không khỏe' },
      { jp: 'ここが痛いです', romaji: 'Koko ga itai desu', vn: 'Chỗ này đau' },
      { jp: '熱があります', romaji: 'Netsu ga arimasu', vn: 'Tôi bị sốt' },
      { jp: 'お腹が痛いです', romaji: 'Onaka ga itai desu', vn: 'Tôi bị đau bụng' },
      { jp: '初診です', romaji: 'Shoshin desu', vn: 'Đây là lần đầu tôi khám tại đây' },
      { jp: 'マイナ保険証を持ってきました', romaji: 'Maina hokenshou wo motte kimashita', vn: 'Tôi đã mang thẻ bảo hiểm My Number' },
      { jp: 'アレルギーがあります', romaji: 'Arerugii ga arimasu', vn: 'Tôi bị dị ứng' },
      { jp: '通訳をお願いできますか？', romaji: 'Tsuuyaku wo onegai dekimasu ka?', vn: 'Tôi có thể nhờ phiên dịch không?' },
    ],
    dialogue: {
      situation: '🏥 Tại phòng khám — đăng ký khám lần đầu',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、初診なんですが…', romaji: 'Sumimasen, shoshin nan desu ga...', vn: 'Xin lỗi, đây là lần đầu tôi đến khám...' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: 'はい、こちらに保険証をお願いします。初診票に記入してください。', romaji: 'Hai, kochira ni hokenshou wo onegaishimasu. Shoshin hyou ni kinyuu shite kudasai.', vn: 'Vâng, xin cho tôi xem thẻ bảo hiểm. Vui lòng điền vào phiếu khám lần đầu.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'マイナ保険証を持ってきました。日本語が苦手なのですが…', romaji: 'Maina hokenshou wo motte kimashita. Nihongo ga nigate na no desu ga...', vn: 'Tôi có mang thẻ My Number bảo hiểm. Nhưng tiếng Nhật của tôi chưa giỏi...' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: '大丈夫ですよ。通訳サービスもありますよ。どうぞ。', romaji: 'Daijoubu desu yo. Tsuuyaku saabisu mo arimasu yo. Douzo.', vn: 'Không sao đâu. Chúng tôi có dịch vụ phiên dịch. Mời vào.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ありがとうございます。熱があって、お腹も痛いです。', romaji: 'Arigatou gozaimasu. Netsu ga atte, onaka mo itai desu.', vn: 'Cảm ơn. Tôi bị sốt và đau bụng.' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: 'わかりました。少しお待ちください。', romaji: 'Wakarimashita. Sukoshi omachi kudasai.', vn: 'Tôi hiểu rồi. Xin chờ một chút.' },
      ],
    },
  },
  {
    category: 'Tại nơi làm việc',
    icon: 'briefcase',
    color: '#9B59B6',
    phrases: [
      { jp: 'よろしくお願いします', romaji: 'Yoroshiku onegaishimasu', vn: 'Rất vui được hợp tác' },
      { jp: 'お疲れ様です', romaji: 'Otsukaresama desu', vn: 'Bạn đã làm việc vất vả (lời chào cuối ngày)' },
      { jp: 'ただいま戻りました', romaji: 'Tadaima modorimashita', vn: 'Tôi vừa quay lại rồi' },
      { jp: 'お先に失礼します', romaji: 'Osakini shitsurei shimasu', vn: 'Tôi xin phép về trước' },
      { jp: 'ちょっと確認します', romaji: 'Chotto kakunin shimasu', vn: 'Để tôi xác nhận lại một chút' },
      { jp: '報告があります', romaji: 'Houkoku ga arimasu', vn: 'Tôi có việc cần báo cáo' },
      { jp: '〜についてご相談があります', romaji: '〜 ni tsuite gousoudan ga arimasu', vn: 'Tôi muốn trao đổi về vấn đề ...' },
    ],
    dialogue: {
      situation: '🏬 Kết thúc ngày làm — chào về trước đồng nghiệp',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、本日の作業が終わりました。お先に失礼します。', romaji: 'Sumimasen, honjitsu no sagyou ga owarimashita. Osakini shitsurei shimasu.', vn: 'Xin lỗi, hôm nay tôi đã xong việc. Tôi xin phép về trước.' },
        { speaker: 'B', speakerLabel: 'Đồng nghiệp', jp: 'お疲れ様でした！明日もよろしくお願いします。', romaji: 'Otsukaresama deshita! Ashita mo yoroshiku onegaishimasu.', vn: 'Bạn đã vất vả! Ngày mai tiếp tục nhờ bạn nhé.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、明日もよろしくお願いします。お疲れ様です！', romaji: 'Hai, ashita mo yoroshiku onegaishimasu. Otsukaresama desu!', vn: 'Vâng, ngày mai cũng nhờ mọi người. Mọi người đã vất vả!' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'ちょっと待って。明日の会議の資料は準備できていますか？', romaji: 'Chotto matte. Ashita no kaigi no shiryou wa junbi dekite imasu ka?', vn: 'Chờ một chút. Tài liệu cuộc họp ngày mai đã chuẩn bị xong chưa?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、もう送りました。ご確認をお願いします。', romaji: 'Hai, mou okurimashita. Gokakunin wo onegaishimasu.', vn: 'Vâng, tôi đã gửi rồi. Phiền bạn kiểm tra giúp nhé.' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'わかった。お疲れ！', romaji: 'Wakatta. Otsukare!', vn: 'Biết rồi. Về nghỉ đi!' },
      ],
    },
  },
  {
    category: 'Xin việc / Phỏng vấn',
    icon: 'person',
    color: '#16A085',
    phrases: [
      { jp: '〜に応募したいです', romaji: '〜 ni oubo shitai desu', vn: 'Tôi muốn ứng tuyển vào vị trí ...' },
      { jp: '面接の日程を教えていただけますか？', romaji: 'Mensetsu no nittei wo oshiete itadakemasu ka?', vn: 'Bạn có thể cho tôi biết lịch phỏng vấn không?' },
      { jp: '自己紹介をします', romaji: 'Jiko shoukai wo shimasu', vn: 'Tôi xin tự giới thiệu' },
      { jp: 'ベトナム出身です', romaji: 'Betonamu shusshin desu', vn: 'Tôi đến từ Việt Nam' },
      { jp: '日本語能力はN3レベルです', romaji: 'Nihongo nouryoku wa N3 reberu desu', vn: 'Năng lực tiếng Nhật của tôi ở mức N3' },
      { jp: '御社で働きたいと思っております', romaji: 'Osha de hatarakitai to omotte orimasu', vn: 'Tôi rất muốn được làm việc tại công ty bạn' },
      { jp: '給与はいくらですか？', romaji: 'Kyuuyo wa ikura desu ka?', vn: 'Mức lương là bao nhiêu?' },
      { jp: 'よろしくお願いいたします', romaji: 'Yoroshiku onegai itashimasu', vn: 'Mong quý công ty xem xét (lời kết phỏng vấn)' },
    ],
    dialogue: {
      situation: '💼 Phỏng vấn xin việc tại công ty sản xuất',
      lines: [
        { speaker: 'B', speakerLabel: 'Nhà tuyển dụng', jp: 'では、自己紹介をお願いします。', romaji: 'Dewa, jiko shoukai wo onegaishimasu.', vn: 'Vậy, xin hãy tự giới thiệu bản thân.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい。グエン・ヴァン・アンと申します。ベトナム出身で、製造の経験が3年あります。', romaji: 'Hai. Nguyen Van An to moushimasu. Betonamu shusshin de, seizou no keiken ga sannen arimasu.', vn: 'Vâng. Tôi tên là Nguyễn Văn An. Tôi đến từ Việt Nam và có 3 năm kinh nghiệm trong sản xuất.' },
        { speaker: 'B', speakerLabel: 'Nhà tuyển dụng', jp: '日本語はどのくらいできますか？', romaji: 'Nihongo wa dono kurai dekimasu ka?', vn: 'Bạn tiếng Nhật đến mức nào?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'N3レベルです。仕事での会話は問題ありません。', romaji: 'N3 reberu desu. Shigoto de no kaiwa wa mondai arimasen.', vn: 'Tôi ở mức N3. Giao tiếp trong công việc không có vấn đề.' },
        { speaker: 'B', speakerLabel: 'Nhà tuyển dụng', jp: 'わかりました。最後に何か質問はありますか？', romaji: 'Wakarimashita. Saigo ni nanika shitsumon wa arimasu ka?', vn: 'Tôi hiểu. Cuối cùng bạn có câu hỏi gì không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '給与と残業についてお聞きしてもよいですか？本日はよろしくお願いいたします。', romaji: 'Kyuuyo to zangyou ni tsuite okiki shite mo yoi desu ka? Honjitsu wa yoroshiku onegai itashimasu.', vn: 'Tôi có thể hỏi về lương và OT không? Hôm nay cảm ơn bạn đã dành thời gian.' },
      ],
    },
  },
  {
    category: 'Ngân hàng / ATM',
    icon: 'card',
    color: '#1ABC9C',
    phrases: [
      { jp: '口座を開設したいです', romaji: 'Kouza wo kaisetsu shitai desu', vn: 'Tôi muốn mở tài khoản' },
      { jp: '振込をしたいです', romaji: 'Furikomi wo shitai desu', vn: 'Tôi muốn chuyển khoản' },
      { jp: '海外送金をしたいです', romaji: 'Kaigai soukin wo shitai desu', vn: 'Tôi muốn gửi tiền ra nước ngoài' },
      { jp: '暗証番号を忘れました', romaji: 'Anshou bangou wo wasuremashita', vn: 'Tôi quên mã PIN rồi' },
      { jp: 'カードが使えません', romaji: 'Kaado ga tsukaemasen', vn: 'Thẻ của tôi không dùng được' },
      { jp: '残高を確認したいです', romaji: 'Zandaka wo kakunin shitai desu', vn: 'Tôi muốn kiểm tra số dư' },
    ],
    dialogue: {
      situation: '🏦 Tại ngân hàng ゆうちょ — mở tài khoản lần đầu',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、口座を開設したいのですが…', romaji: 'Sumimasen, kouza wo kaisetsu shitai no desu ga...', vn: 'Xin lỗi, tôi muốn mở tài khoản...' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'はい。在留カードとマイナンバーカードはお持ちですか？', romaji: 'Hai. Zairyu kaado to Mainanbaа kaado wa omochi desu ka?', vn: 'Vâng. Bạn có mang thẻ cư trú và thẻ My Number không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、持ってきました。日本に来て半年です。', romaji: 'Hai, motte kimashita. Nihon ni kite hantoshi desu.', vn: 'Vâng, tôi có mang. Tôi đến Nhật được nửa năm rồi.' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'わかりました。こちらの用紙に記入してください。印鑑はありますか？', romaji: 'Wakarimashita. Kochira no youshi ni kinyuu shite kudasai. Inkan wa arimasu ka?', vn: 'Tôi hiểu. Xin điền vào mẫu này. Bạn có con dấu không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '印鑑はありません。サインでも大丈夫ですか？', romaji: 'Inkan wa arimasen. Sain demo daijoubu desu ka?', vn: 'Tôi không có con dấu. Ký tên thay được không?' },
        { speaker: 'B', speakerLabel: 'Nhân viên', jp: 'ゆうちょはサインでも開設できますよ。大丈夫です。', romaji: 'Yuucho wa sain demo kaisetsu dekimasu yo. Daijoubu desu.', vn: 'Ở ゆうちょ bạn có thể mở tài khoản bằng chữ ký. Không sao.' },
      ],
    },
  },
  {
    category: 'Thuê nhà',
    icon: 'home',
    color: '#8E44AD',
    phrases: [
      { jp: '部屋を借りたいです', romaji: 'Heya wo karitai desu', vn: 'Tôi muốn thuê phòng' },
      { jp: '家賃はいくらですか？', romaji: 'Yachin wa ikura desu ka?', vn: 'Tiền thuê nhà là bao nhiêu?' },
      { jp: 'ペットを飼っていいですか？', romaji: 'Petto wo katte ii desu ka?', vn: 'Tôi có thể nuôi thú cưng không?' },
      { jp: 'エアコンが壊れています', romaji: 'Eakon ga kowarete imasu', vn: 'Máy lạnh bị hỏng rồi' },
      { jp: '水道が漏れています', romaji: 'Suidou ga morete imasu', vn: 'Ống nước bị rò rỉ' },
      { jp: '退去の手続きをしたいです', romaji: 'Taikyo no tetsuzuki wo shitai desu', vn: 'Tôi muốn làm thủ tục trả nhà' },
    ],
    dialogue: {
      situation: '🏠 Tại công ty môi giới — hỏi về phòng trống',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、1Kの部屋を探しているのですが…', romaji: 'Sumimasen, ichi K no heya wo sagashite iru no desu ga...', vn: 'Xin lỗi, tôi đang tìm phòng 1K...' },
        { speaker: 'B', speakerLabel: 'Môi giới', jp: 'はい、ご予算はどのくらいですか？', romaji: 'Hai, goyosan wa dono kurai desu ka?', vn: 'Vâng, ngân sách của bạn khoảng bao nhiêu?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '家賃は6万円以内がいいです。駅から近いほうがいいです。', romaji: 'Yachin wa roku man en inai ga ii desu. Eki kara chikai hou ga ii desu.', vn: 'Tôi muốn tiền thuê dưới 60,000 yên. Gần ga tàu càng tốt.' },
        { speaker: 'B', speakerLabel: 'Môi giới', jp: 'こちらはいかがですか？駅から徒歩5分、家賃5万8千円です。', romaji: 'Kochira wa ikaga desu ka? Eki kara toho gofun, yachin goman hassen en desu.', vn: 'Cái này thế nào? Cách ga 5 phút đi bộ, tiền thuê 58,000 yên.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'いいですね。外国人でも借りられますか？', romaji: 'Ii desu ne. Gaikokujin demo kariraremasu ka?', vn: 'Tốt đấy. Người nước ngoài cũng thuê được không?' },
        { speaker: 'B', speakerLabel: 'Môi giới', jp: 'はい、大丈夫です。在留カードと保証人が必要です。', romaji: 'Hai, daijoubu desu. Zairyu kaado to hoshounin ga hitsuyou desu.', vn: 'Vâng, được. Cần thẻ cư trú và người bảo lãnh.' },
      ],
    },
  },
  {
    category: 'Hỏi đường',
    icon: 'navigate',
    color: '#27AE60',
    phrases: [
      { jp: '〜はどこですか？', romaji: '〜 wa doko desu ka?', vn: '... ở đâu ạ?' },
      { jp: 'ここはどこですか？', romaji: 'Koko wa doko desu ka?', vn: 'Đây là đâu?' },
      { jp: '歩いて何分ですか？', romaji: 'Aruite nannpun desu ka?', vn: 'Đi bộ mất bao nhiêu phút?' },
      { jp: '地図を見せてもらえますか？', romaji: 'Chizu wo misete moraemasu ka?', vn: 'Bạn có thể chỉ bản đồ cho tôi không?' },
      { jp: '右/左に曲がってください', romaji: 'Migi/Hidari ni magatte kudasai', vn: 'Rẽ phải / Rẽ trái' },
      { jp: 'まっすぐ行ってください', romaji: 'Massugu itte kudasai', vn: 'Đi thẳng' },
    ],
    dialogue: {
      situation: '📮 Hỏi đường đến bưu điện gần nhất',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、郵便局はどこですか？', romaji: 'Sumimasen, yuubinkyoku wa doko desu ka?', vn: 'Xin lỗi, bưu điện ở đâu ạ?' },
        { speaker: 'B', speakerLabel: 'Người dân', jp: 'あ、まっすぐ行って、信号を右に曲がってください。', romaji: 'A, massugu itte, shingou wo migi ni magatte kudasai.', vn: 'Ồ, đi thẳng rồi rẽ phải tại đèn giao thông.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ありがとうございます。歩いて何分くらいですか？', romaji: 'Arigatou gozaimasu. Aruite nannpun kurai desu ka?', vn: 'Cảm ơn. Đi bộ mất khoảng bao nhiêu phút?' },
        { speaker: 'B', speakerLabel: 'Người dân', jp: '5分くらいです。コンビニの隣にありますよ。', romaji: 'Gofun kurai desu. Konbini no tonari ni arimasu yo.', vn: 'Khoảng 5 phút. Nó nằm cạnh convenience store đấy.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'わかりました。どうもありがとうございます！', romaji: 'Wakarimashita. Doumo arigatou gozaimasu!', vn: 'Tôi hiểu rồi. Cảm ơn bạn rất nhiều!' },
        { speaker: 'B', speakerLabel: 'Người dân', jp: 'どういたしまして。お気をつけて。', romaji: 'Douitashimashite. Oki wo tsukete.', vn: 'Không có gì. Đi cẩn thận nhé.' },
      ],
    },
  },
  {
    category: 'Tại nơi làm việc (nâng cao)',
    icon: 'trending-up',
    color: '#D35400',
    phrases: [
      { jp: '有給休暇を取りたいです', romaji: 'Yuukyuu kyuuka wo toritai desu', vn: 'Tôi muốn xin nghỉ phép có lương' },
      { jp: '残業できません', romaji: 'Zangyou dekimasen', vn: 'Tôi không thể làm thêm giờ hôm nay' },
      { jp: '体調が悪いので休みます', romaji: 'Taichou ga warui node yasumimasu', vn: 'Tôi xin nghỉ vì sức khỏe không tốt' },
      { jp: '給料明細を確認したいです', romaji: 'Kyuuryou meisai wo kakunin shitai desu', vn: 'Tôi muốn kiểm tra bảng lương' },
      { jp: '確認をお願いします', romaji: 'Kakunin wo onegaishimasu', vn: 'Phiền bạn xác nhận giúp tôi' },
      { jp: '〜について教えていただけますか？', romaji: '〜 ni tsuite oshiete itadakemasu ka?', vn: 'Bạn có thể giải thích về ... không?' },
      { jp: '報告・連絡・相談 (ほうれんそう)', romaji: 'Houkoku, Renraku, Soudan', vn: 'Báo cáo, Liên lạc, Thảo luận — 3 nguyên tắc làm việc Nhật' },
    ],
    dialogue: {
      situation: '📅 Xin nghỉ phép có lương với sếp',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: '課長、少しよろしいですか？有給休暇の件でご相談があります。', romaji: 'Kachou, sukoshi yoroshii desu ka? Yuukyuu kyuuka no ken de gousoudan ga arimasu.', vn: 'Trưởng phòng ơi, bạn có chút thời gian không? Tôi muốn xin ý kiến về nghỉ phép.' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'はい、何ですか？', romaji: 'Hai, nan desu ka?', vn: 'Vâng, có chuyện gì?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '来月の15日と16日に有給を取りたいのですが、よろしいでしょうか？', romaji: 'Raigetsu no juugonichi to juurokunichi ni yuukyuu wo toritai no desu ga, yoroshii deshou ka?', vn: 'Tôi muốn xin nghỉ phép ngày 15 và 16 tháng sau, được không ạ?' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: '理由を聞いていいですか？', romaji: 'Riyuu wo kiite ii desu ka?', vn: 'Tôi có thể hỏi lý do không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '個人的な用件があります。仕事の引き継ぎはきちんとします。', romaji: 'Kojinteki na youken ga arimasu. Shigoto no hikitsugi wa kichinto shimasu.', vn: 'Tôi có việc cá nhân. Tôi sẽ bàn giao công việc đầy đủ.' },
        { speaker: 'B', speakerLabel: 'Sếp', jp: 'わかりました。申請書を出してください。', romaji: 'Wakarimashita. Shinseisho wo dashite kudasai.', vn: 'Được rồi. Hãy nộp đơn xin phép nhé.' },
      ],
    },
  },
  {
    category: 'Số đếm / Thời gian',
    icon: 'time',
    color: '#5C6B8A',
    phrases: [
      { jp: '一、二、三、四、五', romaji: 'Ichi, ni, san, shi, go', vn: 'Một, hai, ba, bốn, năm' },
      { jp: '六、七、八、九、十', romaji: 'Roku, nana, hachi, kyuu, juu', vn: 'Sáu, bảy, tám, chín, mười' },
      { jp: '今何時ですか？', romaji: 'Ima nanji desu ka?', vn: 'Bây giờ là mấy giờ?' },
      { jp: '〜時〜分です', romaji: '〜 ji 〜 fun desu', vn: '... giờ ... phút' },
      { jp: '今日 / 明日 / 昨日', romaji: 'Kyou / Ashita / Kinou', vn: 'Hôm nay / Ngày mai / Hôm qua' },
      { jp: '月曜日〜日曜日', romaji: 'Getsuyoubi〜Nichiyoubi', vn: 'Thứ Hai → Chủ Nhật' },
      { jp: '〜月〜日', romaji: '〜 gatsu 〜 nichi', vn: 'Tháng ... ngày ...' },
    ],
    dialogue: {
      situation: '📞 Đặt lịch hẹn qua điện thoại',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、診察の予約をしたいのですが。', romaji: 'Sumimasen, shinsatsu no yoyaku wo shitai no desu ga.', vn: 'Xin lỗi, tôi muốn đặt lịch khám bệnh.' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: 'はい、いつがご希望ですか？', romaji: 'Hai, itsu ga gokibou desu ka?', vn: 'Vâng, bạn muốn ngày nào?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '来週の水曜日か木曜日はいかがですか？', romaji: 'Raishuu no suiyoubi ka mokuyoubi wa ikaga desu ka?', vn: 'Thứ Tư hoặc Thứ Năm tuần sau được không?' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: '水曜日の午後2時はいかがですか？', romaji: 'Suiyoubi no gogo niji wa ikaga desu ka?', vn: 'Thứ Tư lúc 2 giờ chiều được không?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'はい、大丈夫です。何時まで受け付けていますか？', romaji: 'Hai, daijoubu desu. Nanji made uketsukete imasu ka?', vn: 'Vâng, được. Nhận bệnh đến mấy giờ?' },
        { speaker: 'B', speakerLabel: 'Lễ tân', jp: '午後5時までです。お名前とお電話番号をどうぞ。', romaji: 'Gogo goji made desu. Onamae to odenwa bangou wo douzo.', vn: 'Đến 5 giờ chiều. Cho tôi xin tên và số điện thoại.' },
      ],
    },
  },
  {
    category: 'Khẩn cấp',
    icon: 'warning',
    color: '#E74C3C',
    phrases: [
      { jp: '助けてください！', romaji: 'Tasukete kudasai!', vn: 'Cứu tôi với!' },
      { jp: '救急車を呼んでください', romaji: 'Kyuukyuusha wo yonde kudasai', vn: 'Xin hãy gọi xe cấp cứu (119)' },
      { jp: '警察を呼んでください', romaji: 'Keisatsu wo yonde kudasai', vn: 'Xin hãy gọi cảnh sát (110)' },
      { jp: '火事です！', romaji: 'Kaji desu!', vn: 'Cháy! / Hỏa hoạn!' },
      { jp: '地震です！机の下に隠れてください', romaji: 'Jishin desu! Tsukue no shita ni kakurete kudasai', vn: 'Động đất! Hãy ẩn xuống gầm bàn!' },
      { jp: '日本語があまりできません', romaji: 'Nihongo ga amari dekimasen', vn: 'Tôi không nói được tiếng Nhật nhiều' },
    ],
    dialogue: {
      situation: '🚨 Gọi cấp cứu 119 khi đồng nghiệp ngã',
      lines: [
        { speaker: 'B', speakerLabel: 'Tổng đài 119', jp: '119番、火事ですか？救急ですか？', romaji: 'Hyaku juukyuu ban, kaji desu ka? Kyuukyuu desu ka?', vn: 'Tổng đài 119, cháy hay cấp cứu?' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '救急です！友達が倒れました！', romaji: 'Kyuukyuu desu! Tomodachi ga taoremashita!', vn: 'Cấp cứu! Bạn tôi bị ngã!' },
        { speaker: 'B', speakerLabel: 'Tổng đài 119', jp: '住所を教えてください。', romaji: 'Juusho wo oshiete kudasai.', vn: 'Cho tôi địa chỉ của bạn.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: '東京都渋谷区〜です。日本語があまりできません。', romaji: 'Tokyo to Shibuya ku 〜 desu. Nihongo ga amari dekimasen.', vn: 'Tôi ở Shibuya, Tokyo... Tôi không nói được tiếng Nhật nhiều.' },
        { speaker: 'B', speakerLabel: 'Tổng đài 119', jp: '大丈夫です。今、救急車が向かっています。電話を切らないでください。', romaji: 'Daijoubu desu. Ima, kyuukyuusha ga mukatte imasu. Denwa wo kiranaide kudasai.', vn: 'Không sao. Xe cấp cứu đang đến. Đừng cúp máy nhé.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'わかりました。ありがとうございます！', romaji: 'Wakarimashita. Arigatou gozaimasu!', vn: 'Tôi hiểu. Cảm ơn!' },
      ],
    },
  },
  {
    category: 'Phân loại rác',
    icon: 'trash',
    color: '#27AE60',
    phrases: [
      { jp: '燃えるゴミ', romaji: 'Moeru gomi', vn: 'Rác đốt được (thức ăn thừa, giấy...)' },
      { jp: '燃えないゴミ', romaji: 'Moenai gomi', vn: 'Rác không đốt được (kim loại, sứ...)' },
      { jp: 'ペットボトル', romaji: 'Petto botoru', vn: 'Chai nhựa PET (để riêng, bỏ nắp)' },
      { jp: '缶・びん', romaji: 'Kan / Bin', vn: 'Lon nhôm / Chai thủy tinh' },
      { jp: '粗大ゴミ', romaji: 'Sodai gomi', vn: 'Rác cồng kềnh (cần đặt lịch trước)' },
      { jp: 'ゴミを正しく分けてください', romaji: 'Gomi wo tadashiku wakete kudasai', vn: 'Xin hãy phân loại rác đúng cách' },
    ],
    dialogue: {
      situation: '🗑️ Hỏi hàng xóm về lịch đổ rác',
      lines: [
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'すみません、このアパートのゴミの出し方を教えていただけますか？', romaji: 'Sumimasen, kono apaato no gomi no dashikata wo oshiete itadakemasu ka?', vn: 'Xin lỗi, bạn có thể chỉ cho tôi cách đổ rác ở tòa nhà này không?' },
        { speaker: 'B', speakerLabel: 'Hàng xóm', jp: 'もちろんですよ。燃えるゴミは月曜と木曜の朝8時までに出してください。', romaji: 'Mochiron desu yo. Moeru gomi wa getsuyou to mokuyou no asa hachiji made ni dashite kudasai.', vn: 'Tất nhiên. Rác đốt được để trước 8 giờ sáng thứ Hai và thứ Năm.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ペットボトルはいつですか？', romaji: 'Petto botoru wa itsu desu ka?', vn: 'Chai nhựa thì bao giờ?' },
        { speaker: 'B', speakerLabel: 'Hàng xóm', jp: '水曜日です。ラベルをはがして、つぶしてから出してください。', romaji: 'Suiyoubi desu. Raberu wo hagashite, tsubushite kara dashite kudasai.', vn: 'Thứ Tư. Bóc nhãn ra, bóp dẹt rồi mới bỏ nhé.' },
        { speaker: 'A', speakerLabel: 'Bạn', jp: 'ありがとうございます。粗大ゴミはどうすればいいですか？', romaji: 'Arigatou gozaimasu. Sodai gomi wa dou sureba ii desu ka?', vn: 'Cảm ơn. Rác cồng kềnh thì làm thế nào?' },
        { speaker: 'B', speakerLabel: 'Hàng xóm', jp: '市役所に電話して事前に申し込みが必要ですよ。有料です。', romaji: 'Shiyakusho ni denwa shite jizen ni moushikomi ga hitsuyou desu yo. Yuuryou desu.', vn: 'Phải gọi điện đến UBND thành phố đặt lịch trước. Có tính phí đấy.' },
      ],
    },
  },
];
