import type { JapaneseWord, PhraseCategory } from '../../types/content';

export const JAPANESE_WORDS: JapaneseWord[] = [
  {
    word: '在留カード',
    reading: 'ざいりゅうカード',
    romaji: 'Zairyuu kaado',
    meaning: 'Thẻ cư trú',
    example: '在留カードを更新する必要があります。',
    exampleRomaji: 'Zairyuu kaado o koushin suru hitsuyou ga arimasu.',
    exampleMeaning: 'Tôi cần gia hạn thẻ cư trú.',
    culturalNote: 'Nên mang theo khi ra ngoài. Ngân hàng, nhà mạng, city hall và nhiều thủ tục sẽ hỏi giấy này.',
  },
  {
    word: 'マイナンバー',
    reading: 'マイナンバー',
    romaji: 'Mainanbaa',
    meaning: 'Mã số cá nhân / My Number',
    example: 'マイナンバーカードを申請しました。',
    exampleRomaji: 'Mainanbaa kaado o shinsei shimashita.',
    exampleMeaning: 'Tôi đã đăng ký thẻ My Number.',
    culturalNote: 'My Number khác với My Number Card. Nhiều người mới rất hay nhầm hai khái niệm này.',
  },
  {
    word: '住民票',
    reading: 'じゅうみんひょう',
    romaji: 'Juuminhyou',
    meaning: 'Giấy xác nhận cư trú',
    example: '住民票を区役所でもらいました。',
    exampleRomaji: 'Juuminhyou o kuyakusho de moraimashita.',
    exampleMeaning: 'Tôi đã lấy giấy xác nhận cư trú ở quận.',
  },
  {
    word: '残業',
    reading: 'ざんぎょう',
    romaji: 'Zangyou',
    meaning: 'Làm thêm giờ',
    example: '今日は残業があります。',
    exampleRomaji: 'Kyou wa zangyou ga arimasu.',
    exampleMeaning: 'Hôm nay có làm thêm giờ.',
  },
  {
    word: '保険証',
    reading: 'ほけんしょう',
    romaji: 'Hokenshou',
    meaning: 'Thẻ bảo hiểm y tế',
    example: '保険証を持ってきてください。',
    exampleRomaji: 'Hokenshou o motte kite kudasai.',
    exampleMeaning: 'Xin hãy mang theo thẻ bảo hiểm.',
  },
  {
    word: '銀行口座',
    reading: 'ぎんこうこうざ',
    romaji: 'Ginkou kouza',
    meaning: 'Tài khoản ngân hàng',
    example: '銀行口座を開設したいです。',
    exampleRomaji: 'Ginkou kouza o kaisetsu shitai desu.',
    exampleMeaning: 'Tôi muốn mở tài khoản ngân hàng.',
  },
  {
    word: '定期券',
    reading: 'ていきけん',
    romaji: 'Teikiken',
    meaning: 'Vé tháng / định kỳ đi lại',
    example: '定期券を買いたいです。',
    exampleRomaji: 'Teikiken o kaitai desu.',
    exampleMeaning: 'Tôi muốn mua vé tháng.',
  },
  {
    word: '乗り換え',
    reading: 'のりかえ',
    romaji: 'Norikae',
    meaning: 'Đổi tàu / chuyển tuyến',
    example: '渋谷で乗り換えてください。',
    exampleRomaji: 'Shibuya de norikaete kudasai.',
    exampleMeaning: 'Hãy đổi tàu ở Shibuya.',
  },
  {
    word: '家賃',
    reading: 'やちん',
    romaji: 'Yachin',
    meaning: 'Tiền thuê nhà',
    example: '家賃は毎月払います。',
    exampleRomaji: 'Yachin wa maitsuki haraimasu.',
    exampleMeaning: 'Tiền thuê nhà được trả hằng tháng.',
  },
  {
    word: '有給休暇',
    reading: 'ゆうきゅうきゅうか',
    romaji: 'Yuukyuu kyuuka',
    meaning: 'Nghỉ phép có lương',
    example: '有給休暇を取りたいです。',
    exampleRomaji: 'Yuukyuu kyuuka o toritai desu.',
    exampleMeaning: 'Tôi muốn xin nghỉ phép có lương.',
  },
];

export const ESSENTIAL_PHRASES: PhraseCategory[] = [
  {
    category: 'Chào hỏi cơ bản',
    icon: 'hand-left',
    color: '#185FA5',
    phrases: [
      { jp: 'おはようございます', romaji: 'Ohayou gozaimasu', vn: 'Chào buổi sáng' },
      { jp: 'こんにちは', romaji: 'Konnichiwa', vn: 'Xin chào / chào buổi ngày' },
      { jp: 'こんばんは', romaji: 'Konbanwa', vn: 'Chào buổi tối' },
      { jp: 'ありがとうございます', romaji: 'Arigatou gozaimasu', vn: 'Cảm ơn' },
      { jp: 'すみません', romaji: 'Sumimasen', vn: 'Xin lỗi / làm phiền' },
      { jp: 'よろしくお願いします', romaji: 'Yoroshiku onegaishimasu', vn: 'Mong được giúp đỡ' },
    ],
  },
  {
    category: 'Khi không hiểu',
    icon: 'chatbubbles',
    color: '#2980B9',
    phrases: [
      { jp: '分かりました', romaji: 'Wakarimashita', vn: 'Tôi hiểu rồi' },
      { jp: '分かりません', romaji: 'Wakarimasen', vn: 'Tôi chưa hiểu' },
      { jp: 'もう一度言ってください', romaji: 'Mou ichido itte kudasai', vn: 'Xin hãy nói lại một lần nữa' },
      { jp: 'ゆっくり話してください', romaji: 'Yukkuri hanashite kudasai', vn: 'Xin hãy nói chậm hơn' },
      { jp: '書いていただけますか', romaji: 'Kaite itadakemasu ka', vn: 'Bạn có thể viết ra được không?' },
      { jp: '少し日本語が分かります', romaji: 'Sukoshi nihongo ga wakarimasu', vn: 'Tôi hiểu một chút tiếng Nhật' },
    ],
  },
  {
    category: 'Combini và mua sắm',
    icon: 'basket',
    color: '#E67E22',
    phrases: [
      { jp: 'これをください', romaji: 'Kore o kudasai', vn: 'Cho tôi cái này' },
      { jp: '袋はいりません', romaji: 'Fukuro wa irimasen', vn: 'Tôi không cần túi' },
      { jp: 'レシートをください', romaji: 'Reshiito o kudasai', vn: 'Xin cho tôi hóa đơn' },
      { jp: '温めてもらえますか', romaji: 'Atatamete moraemasu ka', vn: 'Bạn có thể hâm nóng giúp tôi không?' },
      { jp: 'カードで払えますか', romaji: 'Kaado de haraemasu ka', vn: 'Tôi có thể trả bằng thẻ không?' },
      { jp: 'これはいくらですか', romaji: 'Kore wa ikura desu ka', vn: 'Cái này bao nhiêu tiền?' },
    ],
    dialogue: {
      situation: 'Mua đồ ở combini',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません、このお弁当を温めてもらえますか。',
          romaji: 'Sumimasen, kono obentou o atatamete moraemasu ka.',
          vn: 'Xin lỗi, bạn có thể hâm nóng hộp cơm này giúp tôi không?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: 'はい。お支払いはどうされますか。',
          romaji: 'Hai. Oshiharai wa dou saremasu ka.',
          vn: 'Vâng. Bạn sẽ thanh toán bằng cách nào ạ?',
        },
      ],
    },
  },
  {
    category: 'Tàu điện và đi lại',
    icon: 'train',
    color: '#16A085',
    phrases: [
      { jp: '新宿駅まで行きたいです', romaji: 'Shinjuku eki made ikitai desu', vn: 'Tôi muốn đi tới ga Shinjuku' },
      { jp: '乗り換えはどこですか', romaji: 'Norikae wa doko desu ka', vn: 'Đổi tàu ở đâu?' },
      { jp: 'この電車は渋谷に止まりますか', romaji: 'Kono densha wa Shibuya ni tomarimasu ka', vn: 'Tàu này có dừng ở Shibuya không?' },
      { jp: 'チャージをしたいです', romaji: 'Chaaji o shitai desu', vn: 'Tôi muốn nạp tiền vào thẻ' },
      { jp: '遅延証明書はどこでもらえますか', romaji: 'Chien shoumeisho wa doko de moraemasu ka', vn: 'Lấy giấy xác nhận tàu trễ ở đâu?' },
      { jp: '定期券を買いたいです', romaji: 'Teikiken o kaitai desu', vn: 'Tôi muốn mua vé tháng' },
    ],
  },
  {
    category: 'Đi khám và sức khỏe',
    icon: 'medical',
    color: '#C0392B',
    phrases: [
      { jp: '具合が悪いです', romaji: 'Guai ga warui desu', vn: 'Tôi thấy không khỏe' },
      { jp: '熱があります', romaji: 'Netsu ga arimasu', vn: 'Tôi bị sốt' },
      { jp: 'のどが痛いです', romaji: 'Nodo ga itai desu', vn: 'Tôi đau họng' },
      { jp: '保険証を持っています', romaji: 'Hokenshou o motte imasu', vn: 'Tôi có mang thẻ bảo hiểm' },
      { jp: '予約しています', romaji: 'Yoyaku shite imasu', vn: 'Tôi đã đặt lịch trước' },
    ],
    dialogue: {
      situation: 'Ở quầy tiếp nhận phòng khám',
      lines: [
        {
          speaker: 'B',
          speakerLabel: 'Lễ tân',
          jp: '今日はどうされましたか。',
          romaji: 'Kyou wa dou saremashita ka.',
          vn: 'Hôm nay bạn bị làm sao ạ?',
        },
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: '熱があって、のどが痛いです。',
          romaji: 'Netsu ga atte, nodo ga itai desu.',
          vn: 'Tôi bị sốt và đau họng.',
        },
      ],
    },
  },
  {
    category: 'Công việc và hợp đồng',
    icon: 'briefcase',
    color: '#8E44AD',
    phrases: [
      { jp: 'この契約書を確認したいです', romaji: 'Kono keiyakusho o kakunin shitai desu', vn: 'Tôi muốn kiểm tra hợp đồng này' },
      { jp: '残業代の計算方法を教えてください', romaji: 'Zangyoudai no keisan houhou o oshiete kudasai', vn: 'Xin hãy cho tôi biết cách tính tiền làm thêm' },
      { jp: '給料日はいつですか', romaji: 'Kyuuryoubi wa itsu desu ka', vn: 'Ngày nhận lương là khi nào?' },
      { jp: '有給休暇を取りたいです', romaji: 'Yuukyuu kyuuka o toritai desu', vn: 'Tôi muốn xin nghỉ phép có lương' },
      { jp: '今日は返事をせず、確認してから連絡したいです', romaji: 'Kyou wa henji o sezu, kakunin shite kara renraku shitai desu', vn: 'Hôm nay tôi chưa trả lời ngay, tôi muốn kiểm tra rõ rồi sẽ liên lạc lại' },
    ],
  },
  {
    category: 'Xin nghỉ, đi trễ và đổi ca',
    icon: 'time',
    color: '#9B59B6',
    phrases: [
      { jp: '今日は体調が悪くて休みたいです', romaji: 'Kyou wa taichou ga warukute yasumitai desu', vn: 'Hôm nay tôi không khỏe và muốn xin nghỉ' },
      { jp: '電車が遅れていて、少し遅れます', romaji: 'Densha ga okurete ite, sukoshi okuremasu', vn: 'Tàu đang trễ nên tôi sẽ đến muộn một chút' },
      { jp: '今日は出勤が難しいです', romaji: 'Kyou wa shukkin ga muzukashii desu', vn: 'Hôm nay tôi khó có thể đi làm được' },
      { jp: 'シフトを相談したいです', romaji: 'Shifuto o soudan shitai desu', vn: 'Tôi muốn trao đổi về ca làm' },
      { jp: '有給を使えるか確認したいです', romaji: 'Yuukyuu o tsukaeru ka kakunin shitai desu', vn: 'Tôi muốn xác nhận xem có thể dùng nghỉ phép có lương không' },
      { jp: '何時ごろ着きそうですか', romaji: 'Nanji goro tsukisou desu ka', vn: 'Có vẻ bạn sẽ tới khoảng mấy giờ?' },
    ],
    dialogue: {
      situation: 'Báo đi trễ hoặc xin nghỉ với công ty',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'おはようございます。電車が遅れていて、10分ほど遅れます。',
          romaji: 'Ohayou gozaimasu. Densha ga okurete ite, juppun hodo okuremasu.',
          vn: 'Chào buổi sáng. Tàu đang bị trễ nên tôi sẽ đến muộn khoảng 10 phút.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '分かりました。着いたら連絡してください。',
          romaji: 'Wakarimashita. Tsuitara renraku shite kudasai.',
          vn: 'Đã rõ. Khi tới nơi thì hãy báo lại.',
        },
      ],
    },
  },
  {
    category: 'Bị hỏi giấy tờ hoặc thông tin cá nhân',
    icon: 'card',
    color: '#1F618D',
    phrases: [
      { jp: '在留カードは持っています', romaji: 'Zairyuu kaado wa motte imasu', vn: 'Tôi có mang thẻ cư trú' },
      { jp: 'パスポートも必要ですか', romaji: 'Pasupooto mo hitsuyou desu ka', vn: 'Có cần cả hộ chiếu nữa không?' },
      { jp: '住所確認の書類はこれで大丈夫ですか', romaji: 'Juusho kakunin no shorui wa kore de daijoubu desu ka', vn: 'Giấy xác nhận địa chỉ này đã đủ chưa?' },
      { jp: 'コピーではなく原本が必要ですか', romaji: 'Kopii de wa naku genpon ga hitsuyou desu ka', vn: 'Cần bản gốc chứ không phải bản copy đúng không?' },
      { jp: '今日は足りない書類だけ確認したいです', romaji: 'Kyou wa tarinai shorui dake kakunin shitai desu', vn: 'Hôm nay tôi muốn xác nhận rõ chỉ những giấy tờ còn thiếu' },
      { jp: '持ってくるものをメモしてもいいですか', romaji: 'Motte kuru mono o memo shite mo ii desu ka', vn: 'Tôi ghi chú lại những thứ cần mang tới có được không?' },
    ],
    dialogue: {
      situation: 'Ở ngân hàng, city hall hoặc nhà mạng khi bị hỏi thêm giấy tờ',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Nhân viên',
          jp: '住所確認の書類がもう一つ必要です。',
          romaji: 'Juusho kakunin no shorui ga mou hitotsu hitsuyou desu.',
          vn: 'Bạn cần thêm một giấy xác nhận địa chỉ nữa.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Bạn',
          jp: '何が足りないか、書いていただけますか。',
          romaji: 'Nani ga tarinai ka, kaite itadakemasu ka.',
          vn: 'Bạn có thể viết giúp tôi cụ thể còn thiếu gì không?',
        },
      ],
    },
  },
  {
    category: 'Hỏi phiếu lương và tiền làm thêm',
    icon: 'cash',
    color: '#16A085',
    phrases: [
      { jp: 'この控除は何ですか', romaji: 'Kono koujo wa nan desu ka', vn: 'Khoản khấu trừ này là gì?' },
      { jp: '残業時間を一緒に確認したいです', romaji: 'Zangyou jikan o issho ni kakunin shitai desu', vn: 'Tôi muốn kiểm tra lại số giờ làm thêm cùng với công ty' },
      { jp: '交通費は含まれていますか', romaji: 'Koutsuuhi wa fukumarete imasu ka', vn: 'Tiền đi lại đã được tính vào chưa?' },
      { jp: '給料明細の見方を教えてください', romaji: 'Kyuuryou meisai no mikata o oshiete kudasai', vn: 'Xin hãy chỉ cho tôi cách đọc phiếu lương' },
      { jp: '振込日は毎月いつですか', romaji: 'Furikomi bi wa maitsuki itsu desu ka', vn: 'Ngày chuyển lương mỗi tháng là khi nào?' },
      { jp: '来月分に調整されますか', romaji: 'Raigetsu bun ni chousei saremasu ka', vn: 'Khoản này sẽ được điều chỉnh vào tháng sau chứ?' },
    ],
    dialogue: {
      situation: 'Hỏi lại phiếu lương mà không nói quá gắt',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。この控除と残業時間を一緒に確認したいです。',
          romaji: 'Sumimasen. Kono koujo to zangyou jikan o issho ni kakunin shitai desu.',
          vn: 'Xin lỗi. Tôi muốn kiểm tra lại cùng anh/chị khoản khấu trừ này và số giờ làm thêm.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '分かりました。明細を見ながら説明します。',
          romaji: 'Wakarimashita. Meisai o minagara setsumei shimasu.',
          vn: 'Được. Tôi sẽ giải thích trong lúc cùng xem phiếu lương.',
        },
      ],
    },
  },
  {
    category: 'Trễ tàu, lạc ga và đi nhầm tuyến',
    icon: 'train',
    color: '#2980B9',
    phrases: [
      { jp: '電車が止まっています', romaji: 'Densha ga tomatte imasu', vn: 'Tàu đang dừng hoặc không chạy' },
      { jp: '別の行き方はありますか', romaji: 'Betsu no ikikata wa arimasu ka', vn: 'Có cách đi khác không?' },
      { jp: 'この電車は急行ですか', romaji: 'Kono densha wa kyuukou desu ka', vn: 'Tàu này là tàu nhanh phải không?' },
      { jp: '各駅停車に乗りたいです', romaji: 'Kakueki teisha ni noritai desu', vn: 'Tôi muốn đi tàu dừng mọi ga' },
      { jp: '反対方向に乗ってしまいました', romaji: 'Hantai houkou ni notte shimaimashita', vn: 'Tôi lỡ đi nhầm hướng rồi' },
      { jp: '遅延証明書はどこでもらえますか', romaji: 'Chien shoumeisho wa doko de moraemasu ka', vn: 'Tôi có thể lấy giấy xác nhận tàu trễ ở đâu?' },
    ],
    dialogue: {
      situation: 'Hỏi nhân viên ga khi bị trễ hoặc đi nhầm',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。反対方向に乗ってしまいました。新宿へ行くにはどうしたらいいですか。',
          romaji: 'Sumimasen. Hantai houkou ni notte shimaimashita. Shinjuku e iku ni wa dou shitara ii desu ka.',
          vn: 'Xin lỗi. Tôi lỡ đi nhầm hướng rồi. Muốn đi Shinjuku thì tôi nên làm thế nào?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên ga',
          jp: '次の駅で降りて、反対側のホームに乗り換えてください。',
          romaji: 'Tsugi no eki de orite, hantai gawa no hoomu ni norikaete kudasai.',
          vn: 'Hãy xuống ở ga tiếp theo rồi đổi sang sân ga phía đối diện.',
        },
      ],
    },
  },
  {
    category: 'Đi làm thêm, xin nghỉ học và báo vắng với trường',
    icon: 'school',
    color: '#2E86C1',
    phrases: [
      { jp: 'アルバイトを探しています', romaji: 'Arubaito o sagashite imasu', vn: 'Tôi đang tìm việc làm thêm' },
      { jp: '資格外活動許可は取っています', romaji: 'Shikakugai katsudou kyoka wa totte imasu', vn: 'Tôi đã có giấy phép làm thêm ngoài tư cách lưu trú' },
      { jp: '今日は学校を休みます', romaji: 'Kyou wa gakkou o yasumimasu', vn: 'Hôm nay tôi xin nghỉ học' },
      { jp: '体調が悪いので欠席します', romaji: 'Taichou ga warui node kesseki shimasu', vn: 'Tôi không khỏe nên sẽ vắng mặt' },
      { jp: '遅刻しそうです', romaji: 'Chikoku shisou desu', vn: 'Có vẻ tôi sẽ đến muộn' },
      { jp: '必要なら診断書を出します', romaji: 'Hitsuyou nara shindansho o dashimasu', vn: 'Nếu cần tôi sẽ nộp giấy khám hoặc giấy xác nhận của bác sĩ' },
    ],
    dialogue: {
      situation: 'Báo vắng với trường hoặc lớp tiếng Nhật',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'おはようございます。体調が悪いので、今日は学校を休みます。',
          romaji: 'Ohayou gozaimasu. Taichou ga warui node, kyou wa gakkou o yasumimasu.',
          vn: 'Chào buổi sáng. Hôm nay tôi không khỏe nên xin nghỉ học.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhà trường',
          jp: '分かりました。必要なら後で診断書を提出してください。',
          romaji: 'Wakarimashita. Hitsuyou nara ato de shindansho o teishutsu shite kudasai.',
          vn: 'Đã rõ. Nếu cần thì sau đó hãy nộp giấy xác nhận của bác sĩ.',
        },
      ],
    },
  },
  {
    category: 'Khi bị bệnh, gọi bệnh viện, nhà thuốc và hỏi cấp cứu',
    icon: 'medkit',
    color: '#C0392B',
    phrases: [
      { jp: '今日診てもらえますか', romaji: 'Kyou mite moraemasu ka', vn: 'Hôm nay tôi có thể được khám không?' },
      { jp: '予約なしでも大丈夫ですか', romaji: 'Yoyaku nashi demo daijoubu desu ka', vn: 'Không có hẹn trước thì có khám được không?' },
      { jp: '近くの内科を探しています', romaji: 'Chikaku no naika o sagashite imasu', vn: 'Tôi đang tìm phòng khám nội khoa gần đây' },
      { jp: 'この薬はいつ飲めばいいですか', romaji: 'Kono kusuri wa itsu nomeba ii desu ka', vn: 'Thuốc này nên uống khi nào?' },
      { jp: '食後ですか、食前ですか', romaji: 'Shokugo desu ka, shokuzen desu ka', vn: 'Uống sau ăn hay trước ăn?' },
      { jp: '救急車を呼んだほうがいいですか', romaji: 'Kyuukyuusha o yonda hou ga ii desu ka', vn: 'Có nên gọi xe cấp cứu không?' },
    ],
    dialogue: {
      situation: 'Gọi phòng khám hoặc nhà thuốc để hỏi nhanh',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。今日診てもらえますか。熱があります。',
          romaji: 'Sumimasen. Kyou mite moraemasu ka. Netsu ga arimasu.',
          vn: 'Xin lỗi. Hôm nay tôi có thể được khám không? Tôi đang bị sốt.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Phòng khám',
          jp: '保険証を持って来てください。予約がなければ少しお待ちいただくかもしれません。',
          romaji: 'Hokenshou o motte kite kudasai. Yoyaku ga nakereba sukoshi omachi itadaku kamoshiremasen.',
          vn: 'Hãy mang theo thẻ bảo hiểm. Nếu không có hẹn trước thì có thể bạn sẽ phải chờ một chút.',
        },
      ],
    },
  },
  {
    category: 'City hall theo từng thủ tục cụ thể',
    icon: 'business',
    color: '#1F618D',
    phrases: [
      { jp: '住所変更の手続きをしたいです', romaji: 'Juusho henkou no tetsuzuki o shitai desu', vn: 'Tôi muốn làm thủ tục đổi địa chỉ' },
      { jp: '住民票を一通ください', romaji: 'Juuminhyou o ittsuu kudasai', vn: 'Xin cho tôi một bản giấy cư trú' },
      { jp: 'マイナンバーカードの受け取り予約を確認したいです', romaji: 'Mainanbaa kaado no uketori yoyaku o kakunin shitai desu', vn: 'Tôi muốn xác nhận lịch hẹn nhận thẻ My Number' },
      { jp: '国民健康保険の加入手続きをしたいです', romaji: 'Kokumin kenkou hoken no kanyuu tetsuzuki o shitai desu', vn: 'Tôi muốn làm thủ tục tham gia bảo hiểm y tế quốc dân' },
      { jp: '何階の何番窓口ですか', romaji: 'Nankai no nanban madoguchi desu ka', vn: 'Là quầy số mấy ở tầng mấy?' },
      { jp: '今日中に終わりますか', romaji: 'Kyoujuu ni owarimasu ka', vn: 'Việc này có xong trong hôm nay không?' },
    ],
    dialogue: {
      situation: 'Hỏi đúng quầy ở city hall để không đi lòng vòng',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。住所変更と国民健康保険の手続きをしたいです。何番窓口ですか。',
          romaji: 'Sumimasen. Juusho henkou to kokumin kenkou hoken no tetsuzuki o shitai desu. Nanban madoguchi desu ka.',
          vn: 'Xin lỗi. Tôi muốn làm thủ tục đổi địa chỉ và bảo hiểm y tế quốc dân. Là quầy số mấy ạ?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Nhân viên',
          jp: 'まず2番窓口で住所変更をしてください。その後、4番窓口へお願いします。',
          romaji: 'Mazu niban madoguchi de juusho henkou o shite kudasai. Sono ato, yonban madoguchi e onegaishimasu.',
          vn: 'Trước hết hãy làm đổi địa chỉ ở quầy số 2. Sau đó sang quầy số 4.',
        },
      ],
    },
  },
  {
    category: 'Ngân hàng, SIM và internet khi bị hỏi thêm hoặc bị từ chối',
    icon: 'wifi',
    color: '#117A65',
    phrases: [
      { jp: '今日は口座を開けませんか', romaji: 'Kyou wa kouza o hirakemasen ka', vn: 'Hôm nay tôi không thể mở tài khoản được sao?' },
      { jp: '理由を教えていただけますか', romaji: 'Riyuu o oshiete itadakemasu ka', vn: 'Bạn có thể cho tôi biết lý do không?' },
      { jp: '追加で必要な書類は何ですか', romaji: 'Tsuika de hitsuyou na shorui wa nan desu ka', vn: 'Cần bổ sung thêm giấy tờ gì?' },
      { jp: '後日もう一度来れば大丈夫ですか', romaji: 'Gojitsu mou ichido kureba daijoubu desu ka', vn: 'Hôm khác tôi quay lại lần nữa thì có được không?' },
      { jp: 'この住所では契約できませんか', romaji: 'Kono juusho de wa keiyaku dekimasen ka', vn: 'Với địa chỉ này thì không thể ký hợp đồng sao?' },
      { jp: '審査にはどれぐらいかかりますか', romaji: 'Shinsa ni wa dore gurai kakarimasu ka', vn: 'Xét duyệt sẽ mất khoảng bao lâu?' },
    ],
    dialogue: {
      situation: 'Bị từ chối mở tài khoản hoặc đăng ký SIM',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Nhân viên',
          jp: '今日は口座開設ができません。',
          romaji: 'Kyou wa kouza kaisetsu ga dekimasen.',
          vn: 'Hôm nay bạn chưa thể mở tài khoản được.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Bạn',
          jp: '理由と、追加で必要な書類を教えていただけますか。',
          romaji: 'Riyuu to, tsuika de hitsuyou na shorui o oshiete itadakemasu ka.',
          vn: 'Bạn có thể cho tôi biết lý do và những giấy tờ cần bổ sung không?',
        },
      ],
    },
  },
  {
    category: 'Chuyển nhà, báo hỏng nhà và hỏi 退去費',
    icon: 'home',
    color: '#E67E22',
    phrases: [
      { jp: '引っ越しの予定があります', romaji: 'Hikkoshi no yotei ga arimasu', vn: 'Tôi có kế hoạch chuyển nhà' },
      { jp: '退去の連絡はいつまでに必要ですか', romaji: 'Taikyo no renraku wa itsu made ni hitsuyou desu ka', vn: 'Cần báo trả nhà chậm nhất tới khi nào?' },
      { jp: 'この傷は入居時からありました', romaji: 'Kono kizu wa nyuukyooji kara arimashita', vn: 'Vết này đã có từ lúc tôi vào ở' },
      { jp: '写真を確認してください', romaji: 'Shashin o kakunin shite kudasai', vn: 'Xin hãy kiểm tra ảnh giúp tôi' },
      { jp: '退去費の内訳を説明してください', romaji: 'Taikyohi no uchiwake o setsumei shite kudasai', vn: 'Xin hãy giải thích chi tiết khoản phí trả nhà' },
      { jp: 'この請求は原状回復ガイドラインに沿っていますか', romaji: 'Kono seikyuu wa genjou kaifuku gaidorain ni sotte imasu ka', vn: 'Khoản yêu cầu này có theo guideline về khôi phục hiện trạng không?' },
    ],
    dialogue: {
      situation: 'Tranh luận phí trả nhà nhưng vẫn giữ bình tĩnh',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'この傷は入居時からありました。写真もありますので、確認してください。',
          romaji: 'Kono kizu wa nyuukyooji kara arimashita. Shashin mo arimasu node, kakunin shite kudasai.',
          vn: 'Vết này đã có từ khi tôi vào ở. Tôi cũng có ảnh, xin hãy kiểm tra giúp.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Quản lý nhà',
          jp: '分かりました。写真と請求内容を照らし合わせます。',
          romaji: 'Wakarimashita. Shashin to seikyuu naiyou o terashi awasemasu.',
          vn: 'Được. Tôi sẽ đối chiếu ảnh với nội dung yêu cầu thanh toán.',
        },
      ],
    },
  },
  {
    category: 'Lao động nhạy cảm: nợ lương, giữ giấy tờ, khấu trừ khó hiểu',
    icon: 'alert-circle',
    color: '#C0392B',
    phrases: [
      { jp: 'まだ給料が振り込まれていません', romaji: 'Mada kyuuryou ga furikomarete imasen', vn: 'Lương của tôi vẫn chưa được chuyển' },
      { jp: 'この控除の理由を確認したいです', romaji: 'Kono koujo no riyuu o kakunin shitai desu', vn: 'Tôi muốn xác nhận lý do của khoản khấu trừ này' },
      { jp: '在留カードとパスポートは自分で保管します', romaji: 'Zairyuu kaado to pasupooto wa jibun de hokan shimasu', vn: 'Thẻ cư trú và hộ chiếu tôi sẽ tự giữ' },
      { jp: '原本は渡せませんが、必要ならコピーを出します', romaji: 'Genpon wa watasemasen ga, hitsuyou nara kopii o dashimasu', vn: 'Tôi không thể giao bản gốc, nhưng nếu cần tôi sẽ nộp bản copy' },
      { jp: '書面で説明をいただけますか', romaji: 'Shomen de setsumei o itadakemasu ka', vn: 'Bạn có thể giải thích cho tôi bằng văn bản được không?' },
      { jp: '確認のため、今日の内容をメモしたいです', romaji: 'Kakunin no tame, kyou no naiyou o memo shitai desu', vn: 'Để xác nhận lại, hôm nay tôi muốn ghi chú nội dung trao đổi' },
    ],
    dialogue: {
      situation: 'Hỏi lương chậm hoặc phản hồi khi công ty muốn giữ giấy tờ',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'まだ給料が振り込まれていません。確認していただけますか。',
          romaji: 'Mada kyuuryou ga furikomarete imasen. Kakunin shite itadakemasu ka.',
          vn: 'Lương của tôi vẫn chưa được chuyển. Anh/chị có thể kiểm tra giúp tôi không?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '確認します。少しお待ちください。',
          romaji: 'Kakunin shimasu. Sukoshi omachi kudasai.',
          vn: 'Tôi sẽ kiểm tra. Xin vui lòng chờ một chút.',
        },
      ],
    },
  },
  {
    category: 'Gọi điện cho bệnh viện hoặc phòng khám',
    icon: 'call',
    color: '#C0392B',
    phrases: [
      { jp: '予約を取りたいです', romaji: 'Yoyaku o toritai desu', vn: 'Tôi muốn đặt lịch hẹn' },
      { jp: '今日診てもらえますか', romaji: 'Kyou mite moraemasu ka', vn: 'Hôm nay tôi có thể được khám không?' },
      { jp: '保険証を持っています', romaji: 'Hokenshou o motte imasu', vn: 'Tôi có mang thẻ bảo hiểm' },
      { jp: '初めてですが、大丈夫ですか', romaji: 'Hajimete desu ga, daijoubu desu ka', vn: 'Tôi khám lần đầu, có được không?' },
      { jp: '日本語があまり得意ではありません', romaji: 'Nihongo ga amari tokui de wa arimasen', vn: 'Tôi không giỏi tiếng Nhật lắm' },
      { jp: '持ち物を教えてください', romaji: 'Mochimono o oshiete kudasai', vn: 'Xin hãy cho tôi biết cần mang theo gì' },
    ],
    dialogue: {
      situation: 'Gọi điện đặt lịch khám',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'もしもし、今日診てもらえますか。熱があります。',
          romaji: 'Moshi moshi, kyou mite moraemasu ka. Netsu ga arimasu.',
          vn: 'A lô, hôm nay tôi có thể được khám không? Tôi đang bị sốt.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Phòng khám',
          jp: 'はい。保険証を持って来てください。午後3時なら空いています。',
          romaji: 'Hai. Hokenshou o motte kite kudasai. Gogo sanji nara aite imasu.',
          vn: 'Vâng. Hãy mang theo thẻ bảo hiểm. Nếu là 3 giờ chiều thì còn chỗ.',
        },
      ],
    },
  },
  {
    category: 'Gọi công ty để báo vắng hoặc báo trễ',
    icon: 'call',
    color: '#8E44AD',
    phrases: [
      { jp: '本日お休みをいただきたいです', romaji: 'Honjitsu oyasumi o itadakitai desu', vn: 'Hôm nay tôi muốn xin nghỉ' },
      { jp: '電車の遅延で少し遅れます', romaji: 'Densha no chien de sukoshi okuremasu', vn: 'Do tàu trễ nên tôi sẽ đến muộn một chút' },
      { jp: '到着したら連絡します', romaji: 'Touchaku shitara renraku shimasu', vn: 'Khi tới nơi tôi sẽ báo lại' },
      { jp: '体調不良で病院に行きます', romaji: 'Taichou furyou de byouin ni ikimasu', vn: 'Tôi không khỏe nên sẽ đi bệnh viện' },
      { jp: '必要なら診断書を提出します', romaji: 'Hitsuyou nara shindansho o teishutsu shimasu', vn: 'Nếu cần tôi sẽ nộp giấy xác nhận của bác sĩ' },
      { jp: '担当の方にお伝えいただけますか', romaji: 'Tantou no kata ni otsutae itadakemasu ka', vn: 'Bạn có thể nhắn lại với người phụ trách giúp tôi không?' },
    ],
    dialogue: {
      situation: 'Gọi báo vắng đầu giờ sáng',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'おはようございます。本日、体調不良でお休みをいただきたいです。',
          romaji: 'Ohayou gozaimasu. Honjitsu, taichou furyou de oyasumi o itadakitai desu.',
          vn: 'Chào buổi sáng. Hôm nay tôi không khỏe nên muốn xin nghỉ.',
        },
        {
          speaker: 'B',
          speakerLabel: 'Công ty',
          jp: '分かりました。必要なら後で診断書を提出してください。',
          romaji: 'Wakarimashita. Hitsuyou nara ato de shindansho o teishutsu shite kudasai.',
          vn: 'Đã rõ. Nếu cần thì sau đó hãy nộp giấy xác nhận của bác sĩ.',
        },
      ],
    },
  },
  {
    category: 'Gọi nhà mạng, quản lý nhà hoặc bưu điện',
    icon: 'call',
    color: '#E67E22',
    phrases: [
      { jp: 'インターネットがつながりません', romaji: 'Intaanetto ga tsunagarimasen', vn: 'Internet không kết nối được' },
      { jp: '契約内容を確認したいです', romaji: 'Keiyaku naiyou o kakunin shitai desu', vn: 'Tôi muốn kiểm tra lại nội dung hợp đồng' },
      { jp: '再配達をお願いしたいです', romaji: 'Saihaitatsu o onegai shitai desu', vn: 'Tôi muốn yêu cầu giao lại' },
      { jp: '部屋の設備が壊れています', romaji: 'Heya no setsubi ga kowarete imasu', vn: 'Thiết bị trong phòng đang bị hỏng' },
      { jp: 'いつ修理に来られますか', romaji: 'Itsu shuuri ni koraremasu ka', vn: 'Khi nào bên bạn có thể tới sửa?' },
      { jp: '受付番号を教えてください', romaji: 'Uketsuke bangou o oshiete kudasai', vn: 'Xin cho tôi biết mã tiếp nhận hoặc mã hồ sơ' },
    ],
    dialogue: {
      situation: 'Gọi báo internet hỏng hoặc thiết bị nhà ở bị lỗi',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Bạn',
          jp: 'すみません。インターネットが昨日からつながりません。確認をお願いできますか。',
          romaji: 'Sumimasen. Intaanetto ga kinou kara tsunagarimasen. Kakunin o onegai dekimasu ka.',
          vn: 'Xin lỗi. Từ hôm qua internet không kết nối được. Bạn có thể kiểm tra giúp tôi không?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Hỗ trợ',
          jp: '承知しました。契約者名と住所を確認させてください。',
          romaji: 'Shouchi shimashita. Keiyakusha mei to juusho o kakunin sasete kudasai.',
          vn: 'Đã rõ. Xin hãy cho tôi xác nhận tên người ký hợp đồng và địa chỉ.',
        },
      ],
    },
  },
  {
    category: 'City hall và giấy tờ',
    icon: 'business',
    color: '#1F618D',
    phrases: [
      { jp: '住所変更をしたいです', romaji: 'Juusho henkou o shitai desu', vn: 'Tôi muốn đổi địa chỉ' },
      { jp: '住民票が欲しいです', romaji: 'Juuminhyou ga hoshii desu', vn: 'Tôi muốn xin giấy cư trú' },
      { jp: '必要な書類は何ですか', romaji: 'Hitsuyou na shorui wa nan desu ka', vn: 'Cần những giấy tờ gì?' },
      { jp: 'マイナンバーカードを受け取りたいです', romaji: 'Mainanbaa kaado o uketoritai desu', vn: 'Tôi muốn nhận thẻ My Number' },
      { jp: 'どの窓口ですか', romaji: 'Dono madoguchi desu ka', vn: 'Là quầy nào vậy?' },
    ],
  },
  {
    category: 'Ngân hàng và chuyển tiền',
    icon: 'card',
    color: '#117A65',
    phrases: [
      { jp: '銀行口座を開設したいです', romaji: 'Ginkou kouza o kaisetsu shitai desu', vn: 'Tôi muốn mở tài khoản ngân hàng' },
      { jp: '海外送金はできますか', romaji: 'Kaigai soukin wa dekimasu ka', vn: 'Có thể chuyển tiền quốc tế không?' },
      { jp: '必要な書類を教えてください', romaji: 'Hitsuyou na shorui o oshiete kudasai', vn: 'Xin hãy cho tôi biết giấy tờ cần thiết' },
      { jp: 'アプリの使い方が分かりません', romaji: 'Apuri no tsukaikata ga wakarimasen', vn: 'Tôi chưa biết cách dùng ứng dụng' },
      { jp: 'ATMの手数料はいくらですか', romaji: 'ATM no tesuuryou wa ikura desu ka', vn: 'Phí ATM là bao nhiêu?' },
    ],
  },
  {
    category: 'Điện thoại và internet',
    icon: 'phone-portrait',
    color: '#AF7AC5',
    phrases: [
      { jp: 'SIMを契約したいです', romaji: 'SIM o keiyaku shitai desu', vn: 'Tôi muốn đăng ký SIM' },
      { jp: '月額料金はいくらですか', romaji: 'Getsugaku ryoukin wa ikura desu ka', vn: 'Phí hằng tháng là bao nhiêu?' },
      { jp: '解約手数料はありますか', romaji: 'Kaiyaku tesuuryou wa arimasu ka', vn: 'Có phí hủy hợp đồng không?' },
      { jp: 'インターネットがつながりません', romaji: 'Intaanetto ga tsunagarimasen', vn: 'Internet không kết nối được' },
      { jp: '住所確認の書類が必要ですか', romaji: 'Juusho kakunin no shorui ga hitsuyou desu ka', vn: 'Có cần giấy xác nhận địa chỉ không?' },
    ],
  },
  {
    category: 'Bưu điện và nhận hàng',
    icon: 'mail',
    color: '#D35400',
    phrases: [
      { jp: '再配達をお願いしたいです', romaji: 'Saihaitatsu o onegai shitai desu', vn: 'Tôi muốn yêu cầu giao lại' },
      { jp: '追跡番号があります', romaji: 'Tsuiseki bangou ga arimasu', vn: 'Tôi có mã theo dõi' },
      { jp: '郵便局で受け取りたいです', romaji: 'Yuubinkyoku de uketoritai desu', vn: 'Tôi muốn nhận tại bưu điện' },
      { jp: '転居届を出したいです', romaji: 'Tenkyo todoke o dashitai desu', vn: 'Tôi muốn nộp đơn chuyển tiếp thư' },
      { jp: 'この荷物を送りたいです', romaji: 'Kono nimotsu o okuritai desu', vn: 'Tôi muốn gửi kiện hàng này' },
    ],
  },
  {
    category: 'Nói tự nhiên hơn trong đời sống',
    icon: 'chatbox-ellipses',
    color: '#6C5CE7',
    phrases: [
      { jp: '大丈夫です', romaji: 'Daijoubu desu', vn: 'Dùng rất nhiều trong đời sống: “không sao”, “ổn”, “không cần” tùy ngữ cảnh.' },
      { jp: '少し考えてから連絡します', romaji: 'Sukoshi kangaete kara renraku shimasu', vn: 'Tự nhiên hơn câu từ chối gấp: “Để tôi nghĩ thêm rồi sẽ liên lạc lại.”' },
      { jp: '確認してからお返事します', romaji: 'Kakunin shite kara ohenji shimasu', vn: 'An toàn khi chưa chắc: “Tôi sẽ kiểm tra lại rồi trả lời.”' },
      { jp: 'もう少しやさしい日本語でお願いします', romaji: 'Mou sukoshi yasashii nihongo de onegaishimasu', vn: 'Lịch sự và thực dụng hơn chỉ nói “tôi không hiểu”.' },
      { jp: 'ゆっくりで大丈夫です', romaji: 'Yukkuri de daijoubu desu', vn: 'Khi muốn đối phương nói chậm, không cần quá căng.' },
      { jp: 'あとでアプリで確認します', romaji: 'Ato de apuri de kakunin shimasu', vn: 'Tự nhiên khi nói về ngân hàng, tàu điện, giao hàng hoặc hóa đơn.' },
    ],
    dialogue: {
      situation: 'Bạn chưa muốn trả lời ngay tại quầy hoặc với nhân viên',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Nhân viên',
          jp: '今日ここで申し込みますか。',
          romaji: 'Kyou koko de moushikomimasu ka.',
          vn: 'Hôm nay bạn đăng ký luôn tại đây chứ?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Bạn',
          jp: '少し考えてから連絡します。',
          romaji: 'Sukoshi kangaete kara renraku shimasu.',
          vn: 'Để tôi cân nhắc thêm rồi tôi sẽ liên lạc lại.',
        },
      ],
    },
  },
  {
    category: 'Câu nên tránh hoặc nên đổi cách nói',
    icon: 'warning',
    color: '#E17055',
    phrases: [
      { jp: 'だめです', romaji: 'Dame desu', vn: 'Không sai ngữ pháp nhưng dễ gắt. Trong dịch vụ nên đổi sang: “今回はやめておきます” hoặc “必要ありません”.' },
      { jp: '知らないです', romaji: 'Shiranai desu', vn: 'Nghe thô trong nhiều tình huống. Tự nhiên hơn: “ちょっと分からないです”.' },
      { jp: 'できない', romaji: 'Dekinai', vn: 'Nói trống không dễ cụt. Với công ty/trường nên nói: “今日は難しいです” hoặc “対応できません”.' },
      { jp: 'いいです', romaji: 'Ii desu', vn: 'Rất dễ gây hiểu nhầm vì có thể là “được” hoặc “không cần”. Khi từ chối nên nói rõ: “大丈夫です” hoặc “今回は不要です”.' },
      { jp: '無理です', romaji: 'Muri desu', vn: 'Không phải lúc nào cũng sai, nhưng dễ nặng. Nếu muốn mềm hơn: “少し難しいです”.' },
      { jp: '違います', romaji: 'Chigaimasu', vn: 'Khi sửa nhầm thông tin nên thêm ngữ cảnh: “住所はここではありません” hoặc “名前の漢字が違います”.' },
    ],
    dialogue: {
      situation: 'Từ chối dịch vụ hoặc món hàng mà vẫn giữ lịch sự',
      lines: [
        {
          speaker: 'A',
          speakerLabel: 'Nhân viên',
          jp: '袋はご利用になりますか。',
          romaji: 'Fukuro wa goriyou ni narimasu ka.',
          vn: 'Bạn có dùng túi không ạ?',
        },
        {
          speaker: 'B',
          speakerLabel: 'Bạn',
          jp: '大丈夫です。袋はいりません。',
          romaji: 'Daijoubu desu. Fukuro wa irimasen.',
          vn: 'Không cần ạ. Tôi không cần túi.',
        },
      ],
    },
  },
];
