import { Story } from '../../types/story';

// Fixed: Each paragraph now has exactly 1 sentence with full tokenization
// This ensures audio text = visual text (no mismatch)

export const SAMPLE_STORIES: Story[] = [
  {
    id: 'story-001-morning',
    title: '朝の準備',
    titleJp: '朝の準備',
    description: '毎日の朝の準備についての話です。短くて簡単な話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 350,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-001-001',
        storyId: 'story-001-morning',
        order: 1,
        text: '私は毎日朝6時に起きます。',
        translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.',
        sentences: [
          {
            id: 'sent-001-001',
            paragraphId: 'para-001-001',
            order: 1,
            text: '私は毎日朝6時に起きます。',
            translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.',
            tokens: [
              { id: 't1', sentenceId: 'sent-001-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-001-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-001-001', order: 3, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-001-001', order: 4, word: '朝', reading: 'あさ', pos: 'NOUN', meaning: 'sáng', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-001-001', order: 5, word: '6時', reading: 'ろくじ', pos: 'NOUN', meaning: '6 giờ', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-001-001', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-001-001', order: 7, word: '起きます', reading: 'おきます', pos: 'VERB', meaning: 'thức dậy', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-002',
        storyId: 'story-001-morning',
        order: 2,
        text: '最初にトイレに行きます。',
        translation: 'Đầu tiên, tôi đi vệ sinh.',
        sentences: [
          {
            id: 'sent-001-002',
            paragraphId: 'para-001-002',
            order: 1,
            text: '最初にトイレに行きます。',
            translation: 'Đầu tiên, tôi đi vệ sinh.',
            tokens: [
              { id: 't8', sentenceId: 'sent-001-002', order: 1, word: '最初', reading: 'さいしょ', pos: 'NOUN', meaning: 'đầu tiên', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-001-002', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-001-002', order: 3, word: 'トイレ', reading: 'トイレ', pos: 'NOUN', meaning: 'phòng vệ sinh', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-001-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-001-002', order: 5, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-003',
        storyId: 'story-001-morning',
        order: 3,
        text: 'その後、シャワーを浴びます。',
        translation: 'Sau đó, tôi tắm.',
        sentences: [
          {
            id: 'sent-001-003',
            paragraphId: 'para-001-003',
            order: 1,
            text: 'その後、シャワーを浴びます。',
            translation: 'Sau đó, tôi tắm.',
            tokens: [
              { id: 't13', sentenceId: 'sent-001-003', order: 1, word: 'その後', reading: 'そのご', pos: 'NOUN', meaning: 'sau đó', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-001-003', order: 2, word: 'シャワー', reading: 'シャワー', pos: 'NOUN', meaning: 'vòi tắm', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-001-003', order: 3, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-001-003', order: 4, word: '浴びます', reading: 'あびます', pos: 'VERB', meaning: 'tắm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-004',
        storyId: 'story-001-morning',
        order: 4,
        text: '次に、朝食を食べます。',
        translation: 'Tiếp theo, tôi ăn sáng.',
        sentences: [
          {
            id: 'sent-001-004',
            paragraphId: 'para-001-004',
            order: 1,
            text: '次に、朝食を食べます。',
            translation: 'Tiếp theo, tôi ăn sáng.',
            tokens: [
              { id: 't17', sentenceId: 'sent-001-004', order: 1, word: '次', reading: 'つぎ', pos: 'NOUN', meaning: 'tiếp theo', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-001-004', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-001-004', order: 3, word: '朝食', reading: 'ちょうしょく', pos: 'NOUN', meaning: 'bữa sáng', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-001-004', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-001-004', order: 5, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-002-school',
    title: '学校の友達',
    titleJp: '学校の友達',
    description: '学校で友達と一緒に時間を過ごす話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 380,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-002-001',
        storyId: 'story-002-school',
        order: 1,
        text: '私は毎日学校に行きます。',
        translation: 'Tôi đi học mỗi ngày.',
        sentences: [
          {
            id: 'sent-002-001',
            paragraphId: 'para-002-001',
            order: 1,
            text: '私は毎日学校に行きます。',
            translation: 'Tôi đi học mỗi ngày.',
            tokens: [
              { id: 't1', sentenceId: 'sent-002-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-002-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-002-001', order: 3, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-002-001', order: 4, word: '学校', reading: 'がっこう', pos: 'NOUN', meaning: 'trường học', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-002-001', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-002-001', order: 6, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-002-002',
        storyId: 'story-002-school',
        order: 2,
        text: '学校では友達と一緒に勉強します。',
        translation: 'Tại trường, tôi học với bạn bè.',
        sentences: [
          {
            id: 'sent-002-002',
            paragraphId: 'para-002-002',
            order: 1,
            text: '学校では友達と一緒に勉強します。',
            translation: 'Tại trường, tôi học với bạn bè.',
            tokens: [
              { id: 't7', sentenceId: 'sent-002-002', order: 1, word: '学校', reading: 'がっこう', pos: 'NOUN', meaning: 'trường học', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-002-002', order: 2, word: 'では', reading: 'では', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-002-002', order: 3, word: '友達', reading: 'ともだち', pos: 'NOUN', meaning: 'bạn bè', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-002-002', order: 4, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-002-002', order: 5, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-002-002', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-002-002', order: 7, word: '勉強', reading: 'べんきょう', pos: 'NOUN', meaning: 'học tập', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-002-002', order: 8, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-002-003',
        storyId: 'story-002-school',
        order: 3,
        text: 'お昼は食堂で昼食を食べます。',
        translation: 'Lúc trưa, chúng tôi ăn cơm ở căn tin.',
        sentences: [
          {
            id: 'sent-002-003',
            paragraphId: 'para-002-003',
            order: 1,
            text: 'お昼は食堂で昼食を食べます。',
            translation: 'Lúc trưa, chúng tôi ăn cơm ở căn tin.',
            tokens: [
              { id: 't15', sentenceId: 'sent-002-003', order: 1, word: 'お昼', reading: 'おひる', pos: 'NOUN', meaning: 'trưa', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-002-003', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-002-003', order: 3, word: '食堂', reading: 'しょくどう', pos: 'NOUN', meaning: 'căn tin', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-002-003', order: 4, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-002-003', order: 5, word: '昼食', reading: 'ちゅうしょく', pos: 'NOUN', meaning: 'bữa trưa', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-002-003', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-002-003', order: 7, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-003-family',
    title: '家族との時間',
    titleJp: '家族との時間',
    description: '家族と一緒に過ごす時間の話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-003-001',
        storyId: 'story-003-family',
        order: 1,
        text: '私の家族は5人です。',
        translation: 'Gia đình tôi có 5 người.',
        sentences: [
          {
            id: 'sent-003-001',
            paragraphId: 'para-003-001',
            order: 1,
            text: '私の家族は5人です。',
            translation: 'Gia đình tôi có 5 người.',
            tokens: [
              { id: 't1', sentenceId: 'sent-003-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-003-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-003-001', order: 3, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-003-001', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-003-001', order: 5, word: '5人', reading: 'ごにん', pos: 'NOUN', meaning: '5 người', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-003-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-003-002',
        storyId: 'story-003-family',
        order: 2,
        text: '父、母、兄、妹、そして私です。',
        translation: 'Bố, mẹ, anh trai, em gái, và tôi.',
        sentences: [
          {
            id: 'sent-003-002',
            paragraphId: 'para-003-002',
            order: 1,
            text: '父、母、兄、妹、そして私です。',
            translation: 'Bố, mẹ, anh trai, em gái, và tôi.',
            tokens: [
              { id: 't7', sentenceId: 'sent-003-002', order: 1, word: '父', reading: 'ちち', pos: 'NOUN', meaning: 'bố', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-003-002', order: 2, word: '母', reading: 'はは', pos: 'NOUN', meaning: 'mẹ', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-003-002', order: 3, word: '兄', reading: 'あに', pos: 'NOUN', meaning: 'anh trai', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-003-002', order: 4, word: '妹', reading: 'いもうと', pos: 'NOUN', meaning: 'em gái', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-003-002', order: 5, word: 'そして', reading: 'そして', pos: 'CONJUNCTION', meaning: 'và', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-003-002', order: 6, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-003-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-003-003',
        storyId: 'story-003-family',
        order: 3,
        text: '毎日、夜に一緒に晩ごはんを食べます。',
        translation: 'Mỗi tối, chúng tôi ăn cơm chiều cùng nhau.',
        sentences: [
          {
            id: 'sent-003-003',
            paragraphId: 'para-003-003',
            order: 1,
            text: '毎日、夜に一緒に晩ごはんを食べます。',
            translation: 'Mỗi tối, chúng tôi ăn cơm chiều cùng nhau.',
            tokens: [
              { id: 't14', sentenceId: 'sent-003-003', order: 1, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-003-003', order: 2, word: '夜', reading: 'よる', pos: 'NOUN', meaning: 'tối', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-003-003', order: 3, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-003-003', order: 4, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-003-003', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-003-003', order: 6, word: '晩ごはん', reading: 'ばんごはん', pos: 'NOUN', meaning: 'cơm tối', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-003-003', order: 7, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-003-003', order: 8, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-004-weekend',
    title: '週末のこと',
    titleJp: '週末のこと',
    description: '週末に家族と公園に行く話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 300,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-004-001',
        storyId: 'story-004-weekend',
        order: 1,
        text: '週末、私は公園に行きます。',
        translation: 'Cuối tuần, tôi đi công viên.',
        sentences: [
          {
            id: 'sent-004-001',
            paragraphId: 'para-004-001',
            order: 1,
            text: '週末、私は公園に行きます。',
            translation: 'Cuối tuần, tôi đi công viên.',
            tokens: [
              { id: 't1', sentenceId: 'sent-004-001', order: 1, word: '週末', reading: 'しゅうまつ', pos: 'NOUN', meaning: 'cuối tuần', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-004-001', order: 2, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-004-001', order: 3, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-004-001', order: 4, word: '公園', reading: 'こうえん', pos: 'NOUN', meaning: 'công viên', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-004-001', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-004-001', order: 6, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-004-002',
        storyId: 'story-004-weekend',
        order: 2,
        text: '家族と一緒に花を見ます。',
        translation: 'Tôi xem hoa cùng gia đình.',
        sentences: [
          {
            id: 'sent-004-002',
            paragraphId: 'para-004-002',
            order: 1,
            text: '家族と一緒に花を見ます。',
            translation: 'Tôi xem hoa cùng gia đình.',
            tokens: [
              { id: 't7', sentenceId: 'sent-004-002', order: 1, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-004-002', order: 2, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-004-002', order: 3, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-004-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-004-002', order: 5, word: '花', reading: 'はな', pos: 'NOUN', meaning: 'hoa', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-004-002', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-004-002', order: 7, word: '見ます', reading: 'みます', pos: 'VERB', meaning: 'xem', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-004-003',
        storyId: 'story-004-weekend',
        order: 3,
        text: 'とても楽しい時間です。',
        translation: 'Đó là thời gian rất vui.',
        sentences: [
          {
            id: 'sent-004-003',
            paragraphId: 'para-004-003',
            order: 1,
            text: 'とても楽しい時間です。',
            translation: 'Đó là thời gian rất vui.',
            tokens: [
              { id: 't14', sentenceId: 'sent-004-003', order: 1, word: 'とても', reading: 'とても', pos: 'ADVERB', meaning: 'rất', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-004-003', order: 2, word: '楽しい', reading: 'たのしい', pos: 'ADJECTIVE', meaning: 'vui', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-004-003', order: 3, word: '時間', reading: 'じかん', pos: 'NOUN', meaning: 'thời gian', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-004-003', order: 4, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-005-food',
    title: '食べ物が好きです',
    titleJp: '食べ物が好きです',
    description: '食べ物が好きな話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 280,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-005-001',
        storyId: 'story-005-food',
        order: 1,
        text: '私は食べ物が好きです。',
        translation: 'Tôi thích ăn.',
        sentences: [
          {
            id: 'sent-005-001',
            paragraphId: 'para-005-001',
            order: 1,
            text: '私は食べ物が好きです。',
            translation: 'Tôi thích ăn.',
            tokens: [
              { id: 't1', sentenceId: 'sent-005-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-005-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-005-001', order: 3, word: '食べ物', reading: 'たべもの', pos: 'NOUN', meaning: 'thực phẩm', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-005-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-005-001', order: 5, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-005-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-005-002',
        storyId: 'story-005-food',
        order: 2,
        text: '特に、寿司とラーメンが好きです。',
        translation: 'Đặc biệt, tôi thích sushi và mì ramen.',
        sentences: [
          {
            id: 'sent-005-002',
            paragraphId: 'para-005-002',
            order: 1,
            text: '特に、寿司とラーメンが好きです。',
            translation: 'Đặc biệt, tôi thích sushi và mì ramen.',
            tokens: [
              { id: 't7', sentenceId: 'sent-005-002', order: 1, word: '特に', reading: 'とくに', pos: 'ADVERB', meaning: 'đặc biệt', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-005-002', order: 2, word: '寿司', reading: 'すし', pos: 'NOUN', meaning: 'sushi', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-005-002', order: 3, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-005-002', order: 4, word: 'ラーメン', reading: 'ラーメン', pos: 'NOUN', meaning: 'mì ramen', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-005-002', order: 5, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-005-002', order: 6, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-005-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-005-003',
        storyId: 'story-005-food',
        order: 3,
        text: '毎週金曜日に家族で新しい店に行きます。',
        translation: 'Mỗi thứ Sáu, tôi đi nhà hàng với gia đình.',
        sentences: [
          {
            id: 'sent-005-003',
            paragraphId: 'para-005-003',
            order: 1,
            text: '毎週金曜日に家族で新しい店に行きます。',
            translation: 'Mỗi thứ Sáu, tôi đi nhà hàng với gia đình.',
            tokens: [
              { id: 't14', sentenceId: 'sent-005-003', order: 1, word: '毎週', reading: 'まいしゅう', pos: 'NOUN', meaning: 'mỗi tuần', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-005-003', order: 2, word: '金曜日', reading: 'きんようび', pos: 'NOUN', meaning: 'thứ sáu', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-005-003', order: 3, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-005-003', order: 4, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-005-003', order: 5, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-005-003', order: 6, word: '新しい', reading: 'あたらしい', pos: 'ADJECTIVE', meaning: 'mới', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-005-003', order: 7, word: '店', reading: 'みせ', pos: 'NOUN', meaning: 'cửa hàng', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-005-003', order: 8, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't22', sentenceId: 'sent-005-003', order: 9, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-006-shopping',
    title: 'お買い物',
    titleJp: 'お買い物',
    description: 'スーパーでお買い物をする話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 290,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-006-001',
        storyId: 'story-006-shopping',
        order: 1,
        text: '私はスーパーに行きます。',
        translation: 'Tôi đi siêu thị.',
        sentences: [
          {
            id: 'sent-006-001',
            paragraphId: 'para-006-001',
            order: 1,
            text: '私はスーパーに行きます。',
            translation: 'Tôi đi siêu thị.',
            tokens: [
              { id: 't1', sentenceId: 'sent-006-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-006-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-006-001', order: 3, word: 'スーパー', reading: 'スーパー', pos: 'NOUN', meaning: 'siêu thị', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-006-001', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-006-001', order: 5, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-006-002',
        storyId: 'story-006-shopping',
        order: 2,
        text: 'バナナ、牛乳、パンを買います。',
        translation: 'Tôi mua chuối, sữa, và bánh mì.',
        sentences: [
          {
            id: 'sent-006-002',
            paragraphId: 'para-006-002',
            order: 1,
            text: 'バナナ、牛乳、パンを買います。',
            translation: 'Tôi mua chuối, sữa, và bánh mì.',
            tokens: [
              { id: 't6', sentenceId: 'sent-006-002', order: 1, word: 'バナナ', reading: 'バナナ', pos: 'NOUN', meaning: 'chuối', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-006-002', order: 2, word: '牛乳', reading: 'ぎゅうにゅう', pos: 'NOUN', meaning: 'sữa', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-006-002', order: 3, word: 'パン', reading: 'パン', pos: 'NOUN', meaning: 'bánh mì', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-006-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-006-002', order: 5, word: '買います', reading: 'かいます', pos: 'VERB', meaning: 'mua', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-006-003',
        storyId: 'story-006-shopping',
        order: 3,
        text: 'レジに行って、支払います。',
        translation: 'Tôi đi đến quầy thu ngân và thanh toán.',
        sentences: [
          {
            id: 'sent-006-003',
            paragraphId: 'para-006-003',
            order: 1,
            text: 'レジに行って、支払います。',
            translation: 'Tôi đi đến quầy thu ngân và thanh toán.',
            tokens: [
              { id: 't11', sentenceId: 'sent-006-003', order: 1, word: 'レジ', reading: 'レジ', pos: 'NOUN', meaning: 'quầy thu ngân', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-006-003', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-006-003', order: 3, word: '行って', reading: 'いって', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-006-003', order: 4, word: '支払います', reading: 'しはらいます', pos: 'VERB', meaning: 'thanh toán', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-007-pets',
    title: '私のペット',
    titleJp: '私のペット',
    description: 'ペットとの生活についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-007-001',
        storyId: 'story-007-pets',
        order: 1,
        text: '私は犬を飼っています。',
        translation: 'Tôi nuôi một chú chó.',
        sentences: [
          {
            id: 'sent-007-001',
            paragraphId: 'para-007-001',
            order: 1,
            text: '私は犬を飼っています。',
            translation: 'Tôi nuôi một chú chó.',
            tokens: [
              { id: 't1', sentenceId: 'sent-007-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-007-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-007-001', order: 3, word: '犬', reading: 'いぬ', pos: 'NOUN', meaning: 'chó', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-007-001', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-007-001', order: 5, word: '飼っています', reading: 'かっています', pos: 'VERB', meaning: 'nuôi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-007-002',
        storyId: 'story-007-pets',
        order: 2,
        text: '犬の名前はハチです。',
        translation: 'Tên chó của tôi là Hachi.',
        sentences: [
          {
            id: 'sent-007-002',
            paragraphId: 'para-007-002',
            order: 1,
            text: '犬の名前はハチです。',
            translation: 'Tên chó của tôi là Hachi.',
            tokens: [
              { id: 't6', sentenceId: 'sent-007-002', order: 1, word: '犬', reading: 'いぬ', pos: 'NOUN', meaning: 'chó', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-007-002', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-007-002', order: 3, word: '名前', reading: 'なまえ', pos: 'NOUN', meaning: 'tên', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-007-002', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-007-002', order: 5, word: 'ハチ', reading: 'ハチ', pos: 'NOUN', meaning: 'Hachi', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-007-002', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-007-003',
        storyId: 'story-007-pets',
        order: 3,
        text: 'ハチは優しくて、愛らしいです。',
        translation: 'Hachi rất hiền lành và dễ thương.',
        sentences: [
          {
            id: 'sent-007-003',
            paragraphId: 'para-007-003',
            order: 1,
            text: 'ハチは優しくて、愛らしいです。',
            translation: 'Hachi rất hiền lành và dễ thương.',
            tokens: [
              { id: 't12', sentenceId: 'sent-007-003', order: 1, word: 'ハチ', reading: 'ハチ', pos: 'NOUN', meaning: 'Hachi', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-007-003', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-007-003', order: 3, word: '優しい', reading: 'やさしい', pos: 'ADJECTIVE', meaning: 'hiền lành', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-007-003', order: 4, word: '愛らしい', reading: 'あいらしい', pos: 'ADJECTIVE', meaning: 'dễ thương', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-007-003', order: 5, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-008-cooking',
    title: 'お料理',
    titleJp: 'お料理',
    description: 'キッチンで料理を作る話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-008-001',
        storyId: 'story-008-cooking',
        order: 1,
        text: '私はキッチンで料理を作ります。',
        translation: 'Tôi nấu ăn ở nhà bếp.',
        sentences: [
          {
            id: 'sent-008-001',
            paragraphId: 'para-008-001',
            order: 1,
            text: '私はキッチンで料理を作ります。',
            translation: 'Tôi nấu ăn ở nhà bếp.',
            tokens: [
              { id: 't1', sentenceId: 'sent-008-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-008-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-008-001', order: 3, word: 'キッチン', reading: 'キッチン', pos: 'NOUN', meaning: 'nhà bếp', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-008-001', order: 4, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-008-001', order: 5, word: '料理', reading: 'りょうり', pos: 'NOUN', meaning: 'nấu ăn', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-008-001', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-008-001', order: 7, word: '作ります', reading: 'つくります', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-008-002',
        storyId: 'story-008-cooking',
        order: 2,
        text: '今日はカレーを作ります。',
        translation: 'Hôm nay tôi nấu cà ri.',
        sentences: [
          {
            id: 'sent-008-002',
            paragraphId: 'para-008-002',
            order: 1,
            text: '今日はカレーを作ります。',
            translation: 'Hôm nay tôi nấu cà ri.',
            tokens: [
              { id: 't8', sentenceId: 'sent-008-002', order: 1, word: '今日', reading: 'きょう', pos: 'NOUN', meaning: 'hôm nay', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-008-002', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-008-002', order: 3, word: 'カレー', reading: 'カレー', pos: 'NOUN', meaning: 'cà ri', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-008-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-008-002', order: 5, word: '作ります', reading: 'つくります', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-008-003',
        storyId: 'story-008-cooking',
        order: 3,
        text: 'おいしいカレーが好きです。',
        translation: 'Tôi thích cà ri ngon.',
        sentences: [
          {
            id: 'sent-008-003',
            paragraphId: 'para-008-003',
            order: 1,
            text: 'おいしいカレーが好きです。',
            translation: 'Tôi thích cà ri ngon.',
            tokens: [
              { id: 't13', sentenceId: 'sent-008-003', order: 1, word: 'おいしい', reading: 'おいしい', pos: 'ADJECTIVE', meaning: 'ngon', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-008-003', order: 2, word: 'カレー', reading: 'カレー', pos: 'NOUN', meaning: 'cà ri', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-008-003', order: 3, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-008-003', order: 4, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-008-003', order: 5, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-009-summer',
    title: '夏の思い出',
    titleJp: '夏の思い出',
    description: '夏の楽しい思い出についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 300,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-009-001',
        storyId: 'story-009-summer',
        order: 1,
        text: '夏は大好きです。',
        translation: 'Tôi rất thích mùa hè.',
        sentences: [
          {
            id: 'sent-009-001',
            paragraphId: 'para-009-001',
            order: 1,
            text: '夏は大好きです。',
            translation: 'Tôi rất thích mùa hè.',
            tokens: [
              { id: 't1', sentenceId: 'sent-009-001', order: 1, word: '夏', reading: 'なつ', pos: 'NOUN', meaning: 'hè', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-009-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-009-001', order: 3, word: '大好き', reading: 'だいすき', pos: 'ADJECTIVE', meaning: 'rất thích', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-009-001', order: 4, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-009-002',
        storyId: 'story-009-summer',
        order: 2,
        text: '去年の夏、海に行きました。',
        translation: 'Năm ngoái, tôi đi biển.',
        sentences: [
          {
            id: 'sent-009-002',
            paragraphId: 'para-009-002',
            order: 1,
            text: '去年の夏、海に行きました。',
            translation: 'Năm ngoái, tôi đi biển.',
            tokens: [
              { id: 't5', sentenceId: 'sent-009-002', order: 1, word: '去年', reading: 'きょねん', pos: 'NOUN', meaning: 'năm ngoái', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-009-002', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-009-002', order: 3, word: '夏', reading: 'なつ', pos: 'NOUN', meaning: 'hè', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-009-002', order: 4, word: '海', reading: 'うみ', pos: 'NOUN', meaning: 'biển', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-009-002', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-009-002', order: 6, word: '行きました', reading: 'いきました', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-009-003',
        storyId: 'story-009-summer',
        order: 3,
        text: '水がとても気持ちいいでした。',
        translation: 'Nước thật thoải mái.',
        sentences: [
          {
            id: 'sent-009-003',
            paragraphId: 'para-009-003',
            order: 1,
            text: '水がとても気持ちいいでした。',
            translation: 'Nước thật thoải mái.',
            tokens: [
              { id: 't11', sentenceId: 'sent-009-003', order: 1, word: '水', reading: 'みず', pos: 'NOUN', meaning: 'nước', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-009-003', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-009-003', order: 3, word: 'とても', reading: 'とても', pos: 'ADVERB', meaning: 'rất', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-009-003', order: 4, word: '気持ちいい', reading: 'きもちいい', pos: 'ADJECTIVE', meaning: 'thoải mái', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-009-003', order: 5, word: 'でした', reading: 'でした', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-010-hobby',
    title: '私の趣味',
    titleJp: '私の趣味',
    description: '好きな趣味についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-010-001',
        storyId: 'story-010-hobby',
        order: 1,
        text: '私の趣味は読書です。',
        translation: 'Sở thích của tôi là đọc sách.',
        sentences: [
          {
            id: 'sent-010-001',
            paragraphId: 'para-010-001',
            order: 1,
            text: '私の趣味は読書です。',
            translation: 'Sở thích của tôi là đọc sách.',
            tokens: [
              { id: 't1', sentenceId: 'sent-010-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-010-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-010-001', order: 3, word: '趣味', reading: 'しゅみ', pos: 'NOUN', meaning: 'sở thích', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-010-001', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-010-001', order: 5, word: '読書', reading: 'どくしょ', pos: 'NOUN', meaning: 'đọc sách', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-010-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-010-002',
        storyId: 'story-010-hobby',
        order: 2,
        text: '毎日、本を読みます。',
        translation: 'Mỗi ngày tôi đọc sách.',
        sentences: [
          {
            id: 'sent-010-002',
            paragraphId: 'para-010-002',
            order: 1,
            text: '毎日、本を読みます。',
            translation: 'Mỗi ngày tôi đọc sách.',
            tokens: [
              { id: 't7', sentenceId: 'sent-010-002', order: 1, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-010-002', order: 2, word: '本', reading: 'ほん', pos: 'NOUN', meaning: 'sách', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-010-002', order: 3, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-010-002', order: 4, word: '読みます', reading: 'よみます', pos: 'VERB', meaning: 'đọc', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-010-003',
        storyId: 'story-010-hobby',
        order: 3,
        text: '面白い本が好きです。',
        translation: 'Tôi thích những cuốn sách hay.',
        sentences: [
          {
            id: 'sent-010-003',
            paragraphId: 'para-010-003',
            order: 1,
            text: '面白い本が好きです。',
            translation: 'Tôi thích những cuốn sách hay.',
            tokens: [
              { id: 't11', sentenceId: 'sent-010-003', order: 1, word: '面白い', reading: 'おもしろい', pos: 'ADJECTIVE', meaning: 'hay', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-010-003', order: 2, word: '本', reading: 'ほん', pos: 'NOUN', meaning: 'sách', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-010-003', order: 3, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-010-003', order: 4, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-010-003', order: 5, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-011-birthday',
    title: 'お誕生日',
    titleJp: 'お誕生日',
    description: '誕生日のお祝いについての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 290,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-011-001',
        storyId: 'story-011-birthday',
        order: 1,
        text: '今月は私の誕生日です。',
        translation: 'Tháng này là sinh nhật của tôi.',
        sentences: [
          {
            id: 'sent-011-001',
            paragraphId: 'para-011-001',
            order: 1,
            text: '今月は私の誕生日です。',
            translation: 'Tháng này là sinh nhật của tôi.',
            tokens: [
              { id: 't1', sentenceId: 'sent-011-001', order: 1, word: '今月', reading: 'こんげつ', pos: 'NOUN', meaning: 'tháng này', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-011-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-011-001', order: 3, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-011-001', order: 4, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-011-001', order: 5, word: '誕生日', reading: 'たんじょうび', pos: 'NOUN', meaning: 'sinh nhật', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-011-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-011-002',
        storyId: 'story-011-birthday',
        order: 2,
        text: '友達がケーキをくれました。',
        translation: 'Bạn của tôi tặng tôi một chiếc bánh.',
        sentences: [
          {
            id: 'sent-011-002',
            paragraphId: 'para-011-002',
            order: 1,
            text: '友達がケーキをくれました。',
            translation: 'Bạn của tôi tặng tôi một chiếc bánh.',
            tokens: [
              { id: 't7', sentenceId: 'sent-011-002', order: 1, word: '友達', reading: 'ともだち', pos: 'NOUN', meaning: 'bạn bè', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-011-002', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-011-002', order: 3, word: 'ケーキ', reading: 'ケーキ', pos: 'NOUN', meaning: 'bánh', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-011-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-011-002', order: 5, word: 'くれました', reading: 'くれました', pos: 'VERB', meaning: 'tặng', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-011-003',
        storyId: 'story-011-birthday',
        order: 3,
        text: 'とてもおいしかったです。',
        translation: 'Nó thật ngon.',
        sentences: [
          {
            id: 'sent-011-003',
            paragraphId: 'para-011-003',
            order: 1,
            text: 'とてもおいしかったです。',
            translation: 'Nó thật ngon.',
            tokens: [
              { id: 't12', sentenceId: 'sent-011-003', order: 1, word: 'とても', reading: 'とても', pos: 'ADVERB', meaning: 'rất', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-011-003', order: 2, word: 'おいしかった', reading: 'おいしかった', pos: 'ADJECTIVE', meaning: 'ngon', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-011-003', order: 3, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-012-weather',
    title: 'お天気',
    titleJp: 'お天気',
    description: '天気についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 280,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-012-001',
        storyId: 'story-012-weather',
        order: 1,
        text: '今日はいい天気です。',
        translation: 'Hôm nay thời tiết rất tốt.',
        sentences: [
          {
            id: 'sent-012-001',
            paragraphId: 'para-012-001',
            order: 1,
            text: '今日はいい天気です。',
            translation: 'Hôm nay thời tiết rất tốt.',
            tokens: [
              { id: 't1', sentenceId: 'sent-012-001', order: 1, word: '今日', reading: 'きょう', pos: 'NOUN', meaning: 'hôm nay', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-012-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-012-001', order: 3, word: 'いい', reading: 'いい', pos: 'ADJECTIVE', meaning: 'tốt', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-012-001', order: 4, word: '天気', reading: 'てんき', pos: 'NOUN', meaning: 'thời tiết', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-012-001', order: 5, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-012-002',
        storyId: 'story-012-weather',
        order: 2,
        text: '太陽がとても明るいです。',
        translation: 'Mặt trời rất sáng.',
        sentences: [
          {
            id: 'sent-012-002',
            paragraphId: 'para-012-002',
            order: 1,
            text: '太陽がとても明るいです。',
            translation: 'Mặt trời rất sáng.',
            tokens: [
              { id: 't6', sentenceId: 'sent-012-002', order: 1, word: '太陽', reading: 'たいよう', pos: 'NOUN', meaning: 'mặt trời', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-012-002', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-012-002', order: 3, word: 'とても', reading: 'とても', pos: 'ADVERB', meaning: 'rất', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-012-002', order: 4, word: '明るい', reading: 'あかるい', pos: 'ADJECTIVE', meaning: 'sáng', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-012-002', order: 5, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-012-003',
        storyId: 'story-012-weather',
        order: 3,
        text: '明日も雨がふりません。',
        translation: 'Ngày mai cũng không mưa.',
        sentences: [
          {
            id: 'sent-012-003',
            paragraphId: 'para-012-003',
            order: 1,
            text: '明日も雨がふりません。',
            translation: 'Ngày mai cũng không mưa.',
            tokens: [
              { id: 't11', sentenceId: 'sent-012-003', order: 1, word: '明日', reading: 'あした', pos: 'NOUN', meaning: 'ngày mai', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-012-003', order: 2, word: 'も', reading: 'も', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-012-003', order: 3, word: '雨', reading: 'あめ', pos: 'NOUN', meaning: 'mưa', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-012-003', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-012-003', order: 5, word: 'ふりません', reading: 'ふりません', pos: 'VERB', meaning: 'không mưa', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-013-sports',
    title: 'スポーツ',
    titleJp: 'スポーツ',
    description: 'スポーツ活動についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-013-001',
        storyId: 'story-013-sports',
        order: 1,
        text: '私はスポーツが好きです。',
        translation: 'Tôi thích thể thao.',
        sentences: [
          {
            id: 'sent-013-001',
            paragraphId: 'para-013-001',
            order: 1,
            text: '私はスポーツが好きです。',
            translation: 'Tôi thích thể thao.',
            tokens: [
              { id: 't1', sentenceId: 'sent-013-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-013-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-013-001', order: 3, word: 'スポーツ', reading: 'スポーツ', pos: 'NOUN', meaning: 'thể thao', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-013-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-013-001', order: 5, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-013-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-013-002',
        storyId: 'story-013-sports',
        order: 2,
        text: '特にサッカーとバスケが好きです。',
        translation: 'Đặc biệt, tôi thích bóng đá và bóng rổ.',
        sentences: [
          {
            id: 'sent-013-002',
            paragraphId: 'para-013-002',
            order: 1,
            text: '特にサッカーとバスケが好きです。',
            translation: 'Đặc biệt, tôi thích bóng đá và bóng rổ.',
            tokens: [
              { id: 't7', sentenceId: 'sent-013-002', order: 1, word: '特に', reading: 'とくに', pos: 'ADVERB', meaning: 'đặc biệt', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-013-002', order: 2, word: 'サッカー', reading: 'サッカー', pos: 'NOUN', meaning: 'bóng đá', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-013-002', order: 3, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-013-002', order: 4, word: 'バスケ', reading: 'バスケ', pos: 'NOUN', meaning: 'bóng rổ', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-013-002', order: 5, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-013-002', order: 6, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-013-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-013-003',
        storyId: 'story-013-sports',
        order: 3,
        text: '毎週日曜日にスポーツをします。',
        translation: 'Mỗi chủ nhật tôi chơi thể thao.',
        sentences: [
          {
            id: 'sent-013-003',
            paragraphId: 'para-013-003',
            order: 1,
            text: '毎週日曜日にスポーツをします。',
            translation: 'Mỗi chủ nhật tôi chơi thể thao.',
            tokens: [
              { id: 't14', sentenceId: 'sent-013-003', order: 1, word: '毎週', reading: 'まいしゅう', pos: 'NOUN', meaning: 'mỗi tuần', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-013-003', order: 2, word: '日曜日', reading: 'にちようび', pos: 'NOUN', meaning: 'chủ nhật', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-013-003', order: 3, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-013-003', order: 4, word: 'スポーツ', reading: 'スポーツ', pos: 'NOUN', meaning: 'thể thao', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-013-003', order: 5, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-013-003', order: 6, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-014-music',
    title: '音楽が好きです',
    titleJp: '音楽が好きです',
    description: '音楽についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 300,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-014-001',
        storyId: 'story-014-music',
        order: 1,
        text: '私は音楽が大好きです。',
        translation: 'Tôi rất thích âm nhạc.',
        sentences: [
          {
            id: 'sent-014-001',
            paragraphId: 'para-014-001',
            order: 1,
            text: '私は音楽が大好きです。',
            translation: 'Tôi rất thích âm nhạc.',
            tokens: [
              { id: 't1', sentenceId: 'sent-014-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-014-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-014-001', order: 3, word: '音楽', reading: 'おんがく', pos: 'NOUN', meaning: 'âm nhạc', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-014-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-014-001', order: 5, word: '大好き', reading: 'だいすき', pos: 'ADJECTIVE', meaning: 'rất thích', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-014-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-014-002',
        storyId: 'story-014-music',
        order: 2,
        text: 'ギターを弾くのが好きです。',
        translation: 'Tôi thích chơi guitar.',
        sentences: [
          {
            id: 'sent-014-002',
            paragraphId: 'para-014-002',
            order: 1,
            text: 'ギターを弾くのが好きです。',
            translation: 'Tôi thích chơi guitar.',
            tokens: [
              { id: 't7', sentenceId: 'sent-014-002', order: 1, word: 'ギター', reading: 'ギター', pos: 'NOUN', meaning: 'guitar', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-014-002', order: 2, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-014-002', order: 3, word: '弾く', reading: 'ひく', pos: 'VERB', meaning: 'chơi', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-014-002', order: 4, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-014-002', order: 5, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-014-002', order: 6, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-014-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-014-003',
        storyId: 'story-014-music',
        order: 3,
        text: 'コンサートにも行きます。',
        translation: 'Tôi cũng đi xem liveshow.',
        sentences: [
          {
            id: 'sent-014-003',
            paragraphId: 'para-014-003',
            order: 1,
            text: 'コンサートにも行きます。',
            translation: 'Tôi cũng đi xem liveshow.',
            tokens: [
              { id: 't14', sentenceId: 'sent-014-003', order: 1, word: 'コンサート', reading: 'コンサート', pos: 'NOUN', meaning: 'liveshow', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-014-003', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-014-003', order: 3, word: 'も', reading: 'も', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-014-003', order: 4, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-015-travel',
    title: '旅行',
    titleJp: '旅行',
    description: '旅行についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-015-001',
        storyId: 'story-015-travel',
        order: 1,
        text: '私は旅行が好きです。',
        translation: 'Tôi thích du lịch.',
        sentences: [
          {
            id: 'sent-015-001',
            paragraphId: 'para-015-001',
            order: 1,
            text: '私は旅行が好きです。',
            translation: 'Tôi thích du lịch.',
            tokens: [
              { id: 't1', sentenceId: 'sent-015-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-015-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-015-001', order: 3, word: '旅行', reading: 'りょこう', pos: 'NOUN', meaning: 'du lịch', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-015-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-015-001', order: 5, word: '好き', reading: 'すき', pos: 'ADJECTIVE', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-015-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-015-002',
        storyId: 'story-015-travel',
        order: 2,
        text: 'よく飛行機で遠い所に行きます。',
        translation: 'Tôi thường đi những nơi xa bằng máy bay.',
        sentences: [
          {
            id: 'sent-015-002',
            paragraphId: 'para-015-002',
            order: 1,
            text: 'よく飛行機で遠い所に行きます。',
            translation: 'Tôi thường đi những nơi xa bằng máy bay.',
            tokens: [
              { id: 't7', sentenceId: 'sent-015-002', order: 1, word: 'よく', reading: 'よく', pos: 'ADVERB', meaning: 'thường', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-015-002', order: 2, word: '飛行機', reading: 'ひこうき', pos: 'NOUN', meaning: 'máy bay', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-015-002', order: 3, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-015-002', order: 4, word: '遠い', reading: 'とおい', pos: 'ADJECTIVE', meaning: 'xa', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-015-002', order: 5, word: '所', reading: 'ところ', pos: 'NOUN', meaning: 'nơi', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-015-002', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-015-002', order: 7, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-015-003',
        storyId: 'story-015-travel',
        order: 3,
        text: '毎回新しい経験ができます。',
        translation: 'Mỗi lần tôi có những trải nghiệm mới.',
        sentences: [
          {
            id: 'sent-015-003',
            paragraphId: 'para-015-003',
            order: 1,
            text: '毎回新しい経験ができます。',
            translation: 'Mỗi lần tôi có những trải nghiệm mới.',
            tokens: [
              { id: 't14', sentenceId: 'sent-015-003', order: 1, word: '毎回', reading: 'まいかい', pos: 'NOUN', meaning: 'mỗi lần', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-015-003', order: 2, word: '新しい', reading: 'あたらしい', pos: 'ADJECTIVE', meaning: 'mới', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-015-003', order: 3, word: '経験', reading: 'けいけん', pos: 'NOUN', meaning: 'trải nghiệm', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-015-003', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-015-003', order: 5, word: 'できます', reading: 'できます', pos: 'VERB', meaning: 'có thể', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
];

