// Sample N5 stories for testing
// 5 short stories, each 300-500 words, suitable for N5 learners

import { Story } from '../../types/story';

export const SAMPLE_STORIES: Story[] = [
  {
    id: 'story-001-morning',
    title: '朝の準備',
    titleJp: '朝の準備',
    description: '毎日の朝の準備についての話です。短くて簡単な話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 350,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-001-001',
        storyId: 'story-001-morning',
        order: 1,
        text: '私は毎日朝6時に起きます。最初にトイレに行きます。',
        translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày. Đầu tiên, tôi đi vệ sinh.',
        sentences: [
          {
            id: 'sent-001-001',
            paragraphId: 'para-001-001',
            order: 1,
            text: '私は毎日朝6時に起きます。',
            translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.',
            tokens: [
              { id: 't1', sentenceId: 'sent-001-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-001-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-001-001', order: 3, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-001-001', order: 4, word: '朝', reading: 'あさ', pos: 'NOUN', meaning: 'sáng', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-001-001', order: 5, word: '6時', reading: 'ろくじ', pos: 'NOUN', meaning: '6 giờ', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-001-001', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-001-001', order: 7, word: '起きます', reading: 'おきます', pos: 'VERB', meaning: 'thức dậy', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-001-002',
            paragraphId: 'para-001-001',
            order: 2,
            text: '最初にトイレに行きます。',
            translation: 'Đầu tiên, tôi đi vệ sinh.',
            tokens: [
              { id: 't8', sentenceId: 'sent-001-002', order: 1, word: '最初', reading: 'さいしょ', pos: 'NOUN', meaning: 'đầu tiên', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-001-002', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-001-002', order: 3, word: 'トイレ', reading: 'トイレ', pos: 'NOUN', meaning: 'phòng vệ sinh', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-001-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-001-002', order: 5, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-002',
        storyId: 'story-001-morning',
        order: 2,
        text: 'その後、シャワーを浴びます。水が気持ちいいです。',
        translation: 'Sau đó, tôi tắm. Nước thật thoải mái.',
        sentences: [
          {
            id: 'sent-001-003',
            paragraphId: 'para-001-002',
            order: 1,
            text: 'その後、シャワーを浴びます。',
            translation: 'Sau đó, tôi tắm.',
            tokens: [
              { id: 't13', sentenceId: 'sent-001-003', order: 1, word: 'その後', reading: 'そのご', pos: 'NOUN', meaning: 'sau đó', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-001-003', order: 2, word: 'シャワー', reading: 'シャワー', pos: 'NOUN', meaning: 'vòi tắm', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-001-003', order: 3, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-001-003', order: 4, word: '浴びます', reading: 'あびます', pos: 'VERB', meaning: 'tắm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-003',
        storyId: 'story-001-morning',
        order: 3,
        text: '次に、朝食を食べます。パンとコーヒーです。いつも同じです。',
        translation: 'Tiếp theo, tôi ăn sáng. Là bánh mì và cà phê. Lúc nào cũng như vậy.',
        sentences: [
          {
            id: 'sent-001-004',
            paragraphId: 'para-001-003',
            order: 1,
            text: '次に、朝食を食べます。',
            translation: 'Tiếp theo, tôi ăn sáng.',
            tokens: [
              { id: 't17', sentenceId: 'sent-001-004', order: 1, word: '次', reading: 'つぎ', pos: 'NOUN', meaning: 'tiếp theo', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-001-004', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-001-004', order: 3, word: '朝食', reading: 'ちょうしょく', pos: 'NOUN', meaning: 'bữa sáng', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-001-004', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-001-004', order: 5, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-002-school',
    title: '学校の友達',
    titleJp: '学校の友達',
    description: '学校で友達と一緒に時間を過ごす話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 380,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-002-001',
        storyId: 'story-002-school',
        order: 1,
        text: '私は毎日学校に行きます。学校では友達と一緒に勉強します。',
        translation: 'Tôi đi học mỗi ngày. Tại trường, tôi học với bạn bè.',
        sentences: [
          {
            id: 'sent-002-001',
            paragraphId: 'para-002-001',
            order: 1,
            text: '私は毎日学校に行きます。',
            translation: 'Tôi đi học mỗi ngày.',
            tokens: [],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-003-family',
    title: '家族との時間',
    titleJp: '家族との時間',
    description: '家族と一緒に過ごす時間の話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-003-001',
        storyId: 'story-003-family',
        order: 1,
        text: '私の家族は5人です。父、母、兄、妹、そして私です。',
        translation: 'Gia đình tôi có 5 người. Bố, mẹ, anh trai, em gái, và tôi.',
        sentences: [
          {
            id: 'sent-003-001',
            paragraphId: 'para-003-001',
            order: 1,
            text: '私の家族は5人です。',
            translation: 'Gia đình tôi có 5 người.',
            tokens: [],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-004-weekend',
    title: '週末の過ごし方',
    titleJp: '週末の過ごし方',
    description: '週末をどのように過ごすかの話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 340,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-004-001',
        storyId: 'story-004-weekend',
        order: 1,
        text: '週末は家族と一緒に公園に行きます。',
        translation: 'Cuối tuần, tôi đi công viên với gia đình.',
        sentences: [
          {
            id: 'sent-004-001',
            paragraphId: 'para-004-001',
            order: 1,
            text: '週末は家族と一緒に公園に行きます。',
            translation: 'Cuối tuần, tôi đi công viên với gia đình.',
            tokens: [],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-005-favorite',
    title: '好きな食べ物',
    titleJp: '好きな食べ物',
    description: '好きな食べ物についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-005-001',
        storyId: 'story-005-favorite',
        order: 1,
        text: '私は食べ物が大好きです。特に、寿司とラーメンが好きです。',
        translation: 'Tôi yêu thích ăn uống. Đặc biệt, tôi thích sushi và mì ramen.',
        sentences: [
          {
            id: 'sent-005-001',
            paragraphId: 'para-005-001',
            order: 1,
            text: '私は食べ物が大好きです。',
            translation: 'Tôi yêu thích ăn uống.',
            tokens: [],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
];
