// Sample N5 stories for testing
// 15 short stories, each 300-500 words, suitable for N5 learners

import { Story } from '../../types/story';

export const SAMPLE_STORIES: Story[] = [
  {
    id: 'story-001-morning',
    title: '朝の準備',
    titleJp: '朝の準備',
    description: '毎日の朝の準備についての話です。短くて簡単な話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 350,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-001-001',
        storyId: 'story-001-morning',
        order: 1,
        text: '私は毎日朝6時に起きます。最初にトイレに行きます。',
        translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày. Đầu tiên, tôi đi vệ sinh.',
        sentences: [
          {
            id: 'sent-001-001',
            paragraphId: 'para-001-001',
            order: 1,
            text: '私は毎日朝6時に起きます。',
            translation: 'Tôi thức dậy lúc 6 giờ sáng mỗi ngày.',
            tokens: [
              { id: 't1', sentenceId: 'sent-001-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-001-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-001-001', order: 3, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-001-001', order: 4, word: '朝', reading: 'あさ', pos: 'NOUN', meaning: 'sáng', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-001-001', order: 5, word: '6時', reading: 'ろくじ', pos: 'NOUN', meaning: '6 giờ', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-001-001', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-001-001', order: 7, word: '起きます', reading: 'おきます', pos: 'VERB', meaning: 'thức dậy', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-001-002',
            paragraphId: 'para-001-001',
            order: 2,
            text: '最初にトイレに行きます。',
            translation: 'Đầu tiên, tôi đi vệ sinh.',
            tokens: [
              { id: 't8', sentenceId: 'sent-001-002', order: 1, word: '最初', reading: 'さいしょ', pos: 'NOUN', meaning: 'đầu tiên', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-001-002', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-001-002', order: 3, word: 'トイレ', reading: 'トイレ', pos: 'NOUN', meaning: 'phòng vệ sinh', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-001-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-001-002', order: 5, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-002',
        storyId: 'story-001-morning',
        order: 2,
        text: 'その後、シャワーを浴びます。水が気持ちいいです。',
        translation: 'Sau đó, tôi tắm. Nước thật thoải mái.',
        sentences: [
          {
            id: 'sent-001-003',
            paragraphId: 'para-001-002',
            order: 1,
            text: 'その後、シャワーを浴びます。',
            translation: 'Sau đó, tôi tắm.',
            tokens: [
              { id: 't13', sentenceId: 'sent-001-003', order: 1, word: 'その後', reading: 'そのご', pos: 'NOUN', meaning: 'sau đó', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-001-003', order: 2, word: 'シャワー', reading: 'シャワー', pos: 'NOUN', meaning: 'vòi tắm', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-001-003', order: 3, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-001-003', order: 4, word: '浴びます', reading: 'あびます', pos: 'VERB', meaning: 'tắm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-001-003',
        storyId: 'story-001-morning',
        order: 3,
        text: '次に、朝食を食べます。パンとコーヒーです。いつも同じです。',
        translation: 'Tiếp theo, tôi ăn sáng. Là bánh mì và cà phê. Lúc nào cũng như vậy.',
        sentences: [
          {
            id: 'sent-001-004',
            paragraphId: 'para-001-003',
            order: 1,
            text: '次に、朝食を食べます。',
            translation: 'Tiếp theo, tôi ăn sáng.',
            tokens: [
              { id: 't17', sentenceId: 'sent-001-004', order: 1, word: '次', reading: 'つぎ', pos: 'NOUN', meaning: 'tiếp theo', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-001-004', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-001-004', order: 3, word: '朝食', reading: 'ちょうしょく', pos: 'NOUN', meaning: 'bữa sáng', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-001-004', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-001-004', order: 5, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-002-school',
    title: '学校の友達',
    titleJp: '学校の友達',
    description: '学校で友達と一緒に時間を過ごす話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 380,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-002-001',
        storyId: 'story-002-school',
        order: 1,
        text: '私は毎日学校に行きます。学校では友達と一緒に勉強します。',
        translation: 'Tôi đi học mỗi ngày. Tại trường, tôi học với bạn bè.',
        sentences: [
          {
            id: 'sent-002-001',
            paragraphId: 'para-002-001',
            order: 1,
            text: '私は毎日学校に行きます。',
            translation: 'Tôi đi học mỗi ngày.',
            tokens: [
              { id: 't1', sentenceId: 'sent-002-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-002-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-002-001', order: 3, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-002-001', order: 4, word: '学校', reading: 'がっこう', pos: 'NOUN', meaning: 'trường học', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-002-001', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-002-001', order: 6, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-002-002',
            paragraphId: 'para-002-001',
            order: 2,
            text: '学校では友達と一緒に勉強します。',
            translation: 'Tại trường, tôi học với bạn bè.',
            tokens: [
              { id: 't7', sentenceId: 'sent-002-002', order: 1, word: '学校', reading: 'がっこう', pos: 'NOUN', meaning: 'trường học', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-002-002', order: 2, word: 'では', reading: 'では', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-002-002', order: 3, word: '友達', reading: 'ともだち', pos: 'NOUN', meaning: 'bạn bè', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-002-002', order: 4, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-002-002', order: 5, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-002-002', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-002-002', order: 7, word: '勉強', reading: 'べんきょう', pos: 'NOUN', meaning: 'học tập', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-002-002', order: 8, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-002-002',
        storyId: 'story-002-school',
        order: 2,
        text: 'お昼は食堂で昼食を食べます。皆で一緒に食べるのは楽しいです。',
        translation: 'Lúc trưa, chúng tôi ăn cơm ở căn tin. Ăn cùng nhau rất vui.',
        sentences: [
          {
            id: 'sent-002-003',
            paragraphId: 'para-002-002',
            order: 1,
            text: 'お昼は食堂で昼食を食べます。',
            translation: 'Lúc trưa, chúng tôi ăn cơm ở căn tin.',
            tokens: [
              { id: 't15', sentenceId: 'sent-002-003', order: 1, word: 'お昼', reading: 'おひる', pos: 'NOUN', meaning: 'trưa', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-002-003', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-002-003', order: 3, word: '食堂', reading: 'しょくどう', pos: 'NOUN', meaning: 'căn tin', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-002-003', order: 4, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-002-003', order: 5, word: '昼食', reading: 'ちゅうしょく', pos: 'NOUN', meaning: 'bữa trưa', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-002-003', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-002-003', order: 7, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-003-family',
    title: '家族との時間',
    titleJp: '家族との時間',
    description: '家族と一緒に過ごす時間の話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-003-001',
        storyId: 'story-003-family',
        order: 1,
        text: '私の家族は5人です。父、母、兄、妹、そして私です。',
        translation: 'Gia đình tôi có 5 người. Bố, mẹ, anh trai, em gái, và tôi.',
        sentences: [
          {
            id: 'sent-003-001',
            paragraphId: 'para-003-001',
            order: 1,
            text: '私の家族は5人です。',
            translation: 'Gia đình tôi có 5 người.',
            tokens: [
              { id: 't1', sentenceId: 'sent-003-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-003-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-003-001', order: 3, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-003-001', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-003-001', order: 5, word: '5人', reading: 'ごにん', pos: 'NOUN', meaning: '5 người', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-003-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-003-002',
            paragraphId: 'para-003-001',
            order: 2,
            text: '父、母、兄、妹、そして私です。',
            translation: 'Bố, mẹ, anh trai, em gái, và tôi.',
            tokens: [
              { id: 't7', sentenceId: 'sent-003-002', order: 1, word: '父', reading: 'ちち', pos: 'NOUN', meaning: 'bố', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-003-002', order: 2, word: '母', reading: 'はは', pos: 'NOUN', meaning: 'mẹ', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-003-002', order: 3, word: '兄', reading: 'あに', pos: 'NOUN', meaning: 'anh trai', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-003-002', order: 4, word: '妹', reading: 'いもうと', pos: 'NOUN', meaning: 'em gái', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-003-002', order: 5, word: 'そして', reading: 'そして', pos: 'CONJUNCTION', meaning: 'và', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-003-002', order: 6, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-003-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-003-002',
        storyId: 'story-003-family',
        order: 2,
        text: '毎日、夜に一緒に晩ごはんを食べます。いろいろな話をします。楽しいです。',
        translation: 'Mỗi tối, chúng tôi ăn cơm chiều cùng nhau. Chúng tôi nói chuyện về nhiều điều. Rất vui.',
        sentences: [
          {
            id: 'sent-003-003',
            paragraphId: 'para-003-002',
            order: 1,
            text: '毎日、夜に一緒に晩ごはんを食べます。',
            translation: 'Mỗi tối, chúng tôi ăn cơm chiều cùng nhau.',
            tokens: [
              { id: 't14', sentenceId: 'sent-003-003', order: 1, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-003-003', order: 2, word: '夜', reading: 'よる', pos: 'NOUN', meaning: 'tối', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-003-003', order: 3, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-003-003', order: 4, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-003-003', order: 5, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-003-003', order: 6, word: '晩', reading: 'ばん', pos: 'NOUN', meaning: 'tối', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-003-003', order: 7, word: 'ごはん', reading: 'ごはん', pos: 'NOUN', meaning: 'cơm', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-003-003', order: 8, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't22', sentenceId: 'sent-003-003', order: 9, word: '食べます', reading: 'たべます', pos: 'VERB', meaning: 'ăn', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-004-weekend',
    title: '週末の過ごし方',
    titleJp: '週末の過ごし方',
    description: '週末をどのように過ごすかの話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 340,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-004-001',
        storyId: 'story-004-weekend',
        order: 1,
        text: '週末は家族と一緒に公園に行きます。',
        translation: 'Cuối tuần, tôi đi công viên với gia đình.',
        sentences: [
          {
            id: 'sent-004-001',
            paragraphId: 'para-004-001',
            order: 1,
            text: '週末は家族と一緒に公園に行きます。',
            translation: 'Cuối tuần, tôi đi công viên với gia đình.',
            tokens: [
              { id: 't1', sentenceId: 'sent-004-001', order: 1, word: '週末', reading: 'しゅうまつ', pos: 'NOUN', meaning: 'cuối tuần', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-004-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-004-001', order: 3, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-004-001', order: 4, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-004-001', order: 5, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-004-001', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-004-001', order: 7, word: '公園', reading: 'こうえん', pos: 'NOUN', meaning: 'công viên', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-004-001', order: 8, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-004-001', order: 9, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-004-002',
        storyId: 'story-004-weekend',
        order: 2,
        text: '公園では花を見たり、野球をしたりします。天気がいい日は最高です。',
        translation: 'Ở công viên, chúng tôi xem hoa, chơi bóng chày. Những ngày thời tiết đẹp là tuyệt nhất.',
        sentences: [
          {
            id: 'sent-004-002',
            paragraphId: 'para-004-002',
            order: 1,
            text: '公園では花を見たり、野球をしたりします。',
            translation: 'Ở công viên, chúng tôi xem hoa, chơi bóng chày.',
            tokens: [
              { id: 't10', sentenceId: 'sent-004-002', order: 1, word: '公園', reading: 'こうえん', pos: 'NOUN', meaning: 'công viên', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-004-002', order: 2, word: 'では', reading: 'では', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-004-002', order: 3, word: '花', reading: 'はな', pos: 'NOUN', meaning: 'hoa', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-004-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-004-002', order: 5, word: '見たり', reading: 'みたり', pos: 'VERB', meaning: 'xem', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-004-002', order: 6, word: '野球', reading: 'やきゅう', pos: 'NOUN', meaning: 'bóng chày', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-004-002', order: 7, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-004-002', order: 8, word: 'したり', reading: 'したり', pos: 'VERB', meaning: 'chơi', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-004-002', order: 9, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-005-favorite',
    title: '好きな食べ物',
    titleJp: '好きな食べ物',
    description: '好きな食べ物についての話です。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-005-001',
        storyId: 'story-005-favorite',
        order: 1,
        text: '私は食べ物が大好きです。特に、寿司とラーメンが好きです。',
        translation: 'Tôi yêu thích ăn uống. Đặc biệt, tôi thích sushi và mì ramen.',
        sentences: [
          {
            id: 'sent-005-001',
            paragraphId: 'para-005-001',
            order: 1,
            text: '私は食べ物が大好きです。',
            translation: 'Tôi yêu thích ăn uống.',
            tokens: [
              { id: 't1', sentenceId: 'sent-005-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-005-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-005-001', order: 3, word: '食べ物', reading: 'たべもの', pos: 'NOUN', meaning: 'đồ ăn', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-005-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-005-001', order: 5, word: '大好き', reading: 'だいすき', pos: 'NOUN', meaning: 'rất yêu', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-005-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-005-002',
            paragraphId: 'para-005-001',
            order: 2,
            text: '特に、寿司とラーメンが好きです。',
            translation: 'Đặc biệt, tôi thích sushi và mì ramen.',
            tokens: [
              { id: 't7', sentenceId: 'sent-005-002', order: 1, word: '特に', reading: 'とくに', pos: 'ADVERB', meaning: 'đặc biệt', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-005-002', order: 2, word: '寿司', reading: 'すし', pos: 'NOUN', meaning: 'sushi', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-005-002', order: 3, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-005-002', order: 4, word: 'ラーメン', reading: 'ラーメン', pos: 'NOUN', meaning: 'mì ramen', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-005-002', order: 5, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-005-002', order: 6, word: '好き', reading: 'すき', pos: 'NOUN', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-005-002', order: 7, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-005-002',
        storyId: 'story-005-favorite',
        order: 2,
        text: '毎週金曜日は家族でレストランに行きます。新しいお店も試してみます。',
        translation: 'Mỗi thứ Sáu, gia đình tôi đi nhà hàng. Chúng tôi thử các quán mới.',
        sentences: [
          {
            id: 'sent-005-003',
            paragraphId: 'para-005-002',
            order: 1,
            text: '毎週金曜日は家族でレストランに行きます。',
            translation: 'Mỗi thứ Sáu, gia đình tôi đi nhà hàng.',
            tokens: [
              { id: 't14', sentenceId: 'sent-005-003', order: 1, word: '毎週', reading: 'まいしゅう', pos: 'NOUN', meaning: 'mỗi tuần', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-005-003', order: 2, word: '金曜日', reading: 'きんようび', pos: 'NOUN', meaning: 'thứ Sáu', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-005-003', order: 3, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-005-003', order: 4, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-005-003', order: 5, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-005-003', order: 6, word: 'レストラン', reading: 'レストラン', pos: 'NOUN', meaning: 'nhà hàng', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-005-003', order: 7, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-005-003', order: 8, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-006-shopping',
    title: 'お買い物',
    titleJp: 'お買い物',
    description: 'スーパーで買い物をする話です。毎日の生活に必要な物を買います。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 360,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-006-001',
        storyId: 'story-006-shopping',
        order: 1,
        text: '私は週に2回スーパーに行きます。野菜や果物を買います。',
        translation: 'Tôi đi siêu thị 2 lần một tuần. Tôi mua rau và trái cây.',
        sentences: [
          {
            id: 'sent-006-001',
            paragraphId: 'para-006-001',
            order: 1,
            text: '私は週に2回スーパーに行きます。',
            translation: 'Tôi đi siêu thị 2 lần một tuần.',
            tokens: [
              { id: 't1', sentenceId: 'sent-006-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-006-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-006-001', order: 3, word: '週', reading: 'しゅう', pos: 'NOUN', meaning: 'tuần', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-006-001', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-006-001', order: 5, word: '2回', reading: 'にかい', pos: 'NOUN', meaning: '2 lần', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-006-001', order: 6, word: 'スーパー', reading: 'スーパー', pos: 'NOUN', meaning: 'siêu thị', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-006-001', order: 7, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-006-001', order: 8, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-006-002',
            paragraphId: 'para-006-001',
            order: 2,
            text: '野菜や果物を買います。',
            translation: 'Tôi mua rau và trái cây.',
            tokens: [
              { id: 't9', sentenceId: 'sent-006-002', order: 1, word: '野菜', reading: 'やさい', pos: 'NOUN', meaning: 'rau', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-006-002', order: 2, word: 'や', reading: 'や', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-006-002', order: 3, word: '果物', reading: 'くだもの', pos: 'NOUN', meaning: 'trái cây', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-006-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-006-002', order: 5, word: '買います', reading: 'かいます', pos: 'VERB', meaning: 'mua', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-007-pet',
    title: 'ペットの犬',
    titleJp: 'ペットの犬',
    description: 'ペットの犬と一緒に生活する話です。毎日の散歩が楽しみです。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 350,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-007-001',
        storyId: 'story-007-pet',
        order: 1,
        text: '私は犬を飼っています。名前はポチです。毎日散歩に行きます。',
        translation: 'Tôi nuôi một con chó. Tên của nó là Pochi. Tôi dắt nó đi dạo mỗi ngày.',
        sentences: [
          {
            id: 'sent-007-001',
            paragraphId: 'para-007-001',
            order: 1,
            text: '私は犬を飼っています。',
            translation: 'Tôi nuôi một con chó.',
            tokens: [
              { id: 't1', sentenceId: 'sent-007-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-007-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-007-001', order: 3, word: '犬', reading: 'いぬ', pos: 'NOUN', meaning: 'chó', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-007-001', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-007-001', order: 5, word: '飼っています', reading: 'かっています', pos: 'VERB', meaning: 'nuôi', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-007-002',
            paragraphId: 'para-007-001',
            order: 2,
            text: '名前はポチです。',
            translation: 'Tên của nó là Pochi.',
            tokens: [
              { id: 't6', sentenceId: 'sent-007-002', order: 1, word: '名前', reading: 'なまえ', pos: 'NOUN', meaning: 'tên', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-007-002', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-007-002', order: 3, word: 'ポチ', reading: 'ポチ', pos: 'NOUN', meaning: 'Pochi', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-007-002', order: 4, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-007-003',
            paragraphId: 'para-007-001',
            order: 3,
            text: '毎日散歩に行きます。',
            translation: 'Tôi dắt nó đi dạo mỗi ngày.',
            tokens: [
              { id: 't10', sentenceId: 'sent-007-003', order: 1, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-007-003', order: 2, word: '散歩', reading: 'さんぽ', pos: 'NOUN', meaning: 'dạo phố', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-007-003', order: 3, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-007-003', order: 4, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-008-cooking',
    title: '料理をします',
    titleJp: '料理をします',
    description: 'キッチンで料理をする話です。簡単な料理を作るのが好きです。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 340,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-008-001',
        storyId: 'story-008-cooking',
        order: 1,
        text: '私は週に3回料理をします。野菜と肉を使います。',
        translation: 'Tôi nấu ăn 3 lần một tuần. Tôi sử dụng rau và thịt.',
        sentences: [
          {
            id: 'sent-008-001',
            paragraphId: 'para-008-001',
            order: 1,
            text: '私は週に3回料理をします。',
            translation: 'Tôi nấu ăn 3 lần một tuần.',
            tokens: [
              { id: 't1', sentenceId: 'sent-008-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-008-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-008-001', order: 3, word: '週', reading: 'しゅう', pos: 'NOUN', meaning: 'tuần', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-008-001', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-008-001', order: 5, word: '3回', reading: 'さんかい', pos: 'NOUN', meaning: '3 lần', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-008-001', order: 6, word: '料理', reading: 'りょうり', pos: 'NOUN', meaning: 'nấu ăn', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-008-001', order: 7, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-008-001', order: 8, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-008-002',
            paragraphId: 'para-008-001',
            order: 2,
            text: '野菜と肉を使います。',
            translation: 'Tôi sử dụng rau và thịt.',
            tokens: [
              { id: 't9', sentenceId: 'sent-008-002', order: 1, word: '野菜', reading: 'やさい', pos: 'NOUN', meaning: 'rau', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-008-002', order: 2, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-008-002', order: 3, word: '肉', reading: 'にく', pos: 'NOUN', meaning: 'thịt', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-008-002', order: 4, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-008-002', order: 5, word: '使います', reading: 'つかいます', pos: 'VERB', meaning: 'sử dụng', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-009-summer',
    title: '夏休み',
    titleJp: '夏休み',
    description: '夏休みを楽しく過ごす話です。海に行ったり、友達と遊んだりします。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 370,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-009-001',
        storyId: 'story-009-summer',
        order: 1,
        text: '夏休みは2ヶ月間あります。海や山に行きます。',
        translation: 'Kỳ nghỉ hè kéo dài 2 tháng. Tôi đi biển hoặc núi.',
        sentences: [
          {
            id: 'sent-009-001',
            paragraphId: 'para-009-001',
            order: 1,
            text: '夏休みは2ヶ月間あります。',
            translation: 'Kỳ nghỉ hè kéo dài 2 tháng.',
            tokens: [
              { id: 't1', sentenceId: 'sent-009-001', order: 1, word: '夏休み', reading: 'なつやすみ', pos: 'NOUN', meaning: 'kỳ nghỉ hè', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-009-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-009-001', order: 3, word: '2ヶ月', reading: 'にかげつ', pos: 'NOUN', meaning: '2 tháng', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-009-001', order: 4, word: '間', reading: 'かん', pos: 'NOUN', meaning: 'khoảng thời gian', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-009-001', order: 5, word: 'あります', reading: 'あります', pos: 'VERB', meaning: 'có', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-009-002',
            paragraphId: 'para-009-001',
            order: 2,
            text: '海や山に行きます。',
            translation: 'Tôi đi biển hoặc núi.',
            tokens: [
              { id: 't6', sentenceId: 'sent-009-002', order: 1, word: '海', reading: 'うみ', pos: 'NOUN', meaning: 'biển', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-009-002', order: 2, word: 'や', reading: 'や', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-009-002', order: 3, word: '山', reading: 'やま', pos: 'NOUN', meaning: 'núi', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-009-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-009-002', order: 5, word: '行きます', reading: 'いきます', pos: 'VERB', meaning: 'đi', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-010-hobby',
    title: '私の趣味',
    titleJp: '私の趣味',
    description: '趣味についての話です。読書と写真を撮るのが好きです。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 330,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-010-001',
        storyId: 'story-010-hobby',
        order: 1,
        text: '私の趣味は読書と写真です。毎週末、本を読んだり写真を撮ったりします。',
        translation: 'Sở thích của tôi là đọc sách và chụp ảnh. Vào cuối tuần, tôi đọc sách hoặc chụp ảnh.',
        sentences: [
          {
            id: 'sent-010-001',
            paragraphId: 'para-010-001',
            order: 1,
            text: '私の趣味は読書と写真です。',
            translation: 'Sở thích của tôi là đọc sách và chụp ảnh.',
            tokens: [
              { id: 't1', sentenceId: 'sent-010-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-010-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-010-001', order: 3, word: '趣味', reading: 'しゅみ', pos: 'NOUN', meaning: 'sở thích', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-010-001', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-010-001', order: 5, word: '読書', reading: 'どくしょ', pos: 'NOUN', meaning: 'đọc sách', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-010-001', order: 6, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-010-001', order: 7, word: '写真', reading: 'しゃしん', pos: 'NOUN', meaning: 'ảnh', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-010-001', order: 8, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-010-002',
            paragraphId: 'para-010-001',
            order: 2,
            text: '毎週末、本を読んだり写真を撮ったりします。',
            translation: 'Vào cuối tuần, tôi đọc sách hoặc chụp ảnh.',
            tokens: [
              { id: 't9', sentenceId: 'sent-010-002', order: 1, word: '毎週末', reading: 'まいしゅうまつ', pos: 'NOUN', meaning: 'mỗi cuối tuần', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-010-002', order: 2, word: '本', reading: 'ほん', pos: 'NOUN', meaning: 'sách', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-010-002', order: 3, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-010-002', order: 4, word: '読んだり', reading: 'よんだり', pos: 'VERB', meaning: 'đọc', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-010-002', order: 5, word: '写真', reading: 'しゃしん', pos: 'NOUN', meaning: 'ảnh', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-010-002', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-010-002', order: 7, word: '撮ったり', reading: 'とったり', pos: 'VERB', meaning: 'chụp', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-010-002', order: 8, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-011-birthday',
    title: 'お誕生日',
    titleJp: 'お誕生日',
    description: '誕生日をお祝いする話です。友達とケーキを食べます。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 320,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-011-001',
        storyId: 'story-011-birthday',
        order: 1,
        text: '来月は私の誕生日です。友達がお祝いしてくれます。',
        translation: 'Tháng tới là sinh nhật của tôi. Bạn bè của tôi sẽ chúc mừng tôi.',
        sentences: [
          {
            id: 'sent-011-001',
            paragraphId: 'para-011-001',
            order: 1,
            text: '来月は私の誕生日です。',
            translation: 'Tháng tới là sinh nhật của tôi.',
            tokens: [
              { id: 't1', sentenceId: 'sent-011-001', order: 1, word: '来月', reading: 'らいげつ', pos: 'NOUN', meaning: 'tháng tới', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-011-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-011-001', order: 3, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-011-001', order: 4, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-011-001', order: 5, word: '誕生日', reading: 'たんじょうび', pos: 'NOUN', meaning: 'sinh nhật', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-011-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-011-002',
            paragraphId: 'para-011-001',
            order: 2,
            text: '友達がお祝いしてくれます。',
            translation: 'Bạn bè của tôi sẽ chúc mừng tôi.',
            tokens: [
              { id: 't7', sentenceId: 'sent-011-002', order: 1, word: '友達', reading: 'ともだち', pos: 'NOUN', meaning: 'bạn bè', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-011-002', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-011-002', order: 3, word: 'お祝い', reading: 'おいわい', pos: 'NOUN', meaning: 'chúc mừng', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-011-002', order: 4, word: 'してくれます', reading: 'してくれます', pos: 'VERB', meaning: 'sẽ làm cho', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-012-weather',
    title: 'お天気',
    titleJp: 'お天気',
    description: 'お天気についての話です。雨の日と晴れた日のことを話します。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 300,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-012-001',
        storyId: 'story-012-weather',
        order: 1,
        text: '今日は晴れています。太陽が明るいです。気持ちがいいです。',
        translation: 'Hôm nay trời nắng. Mặt trời sáng. Tôi cảm thấy thoải mái.',
        sentences: [
          {
            id: 'sent-012-001',
            paragraphId: 'para-012-001',
            order: 1,
            text: '今日は晴れています。',
            translation: 'Hôm nay trời nắng.',
            tokens: [
              { id: 't1', sentenceId: 'sent-012-001', order: 1, word: '今日', reading: 'きょう', pos: 'NOUN', meaning: 'hôm nay', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-012-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-012-001', order: 3, word: '晴れ', reading: 'はれ', pos: 'NOUN', meaning: 'nắng', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-012-001', order: 4, word: 'ています', reading: 'ています', pos: 'VERB', meaning: 'đang', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-012-002',
            paragraphId: 'para-012-001',
            order: 2,
            text: '太陽が明るいです。',
            translation: 'Mặt trời sáng.',
            tokens: [
              { id: 't5', sentenceId: 'sent-012-002', order: 1, word: '太陽', reading: 'たいよう', pos: 'NOUN', meaning: 'mặt trời', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-012-002', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-012-002', order: 3, word: '明るい', reading: 'あかるい', pos: 'ADJECTIVE', meaning: 'sáng', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-012-002', order: 4, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-012-003',
            paragraphId: 'para-012-001',
            order: 3,
            text: '気持ちがいいです。',
            translation: 'Tôi cảm thấy thoải mái.',
            tokens: [
              { id: 't9', sentenceId: 'sent-012-003', order: 1, word: '気持ち', reading: 'きもち', pos: 'NOUN', meaning: 'cảm giác', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-012-003', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-012-003', order: 3, word: 'いい', reading: 'いい', pos: 'ADJECTIVE', meaning: 'tốt', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-012-003', order: 4, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-013-sports',
    title: 'スポーツ',
    titleJp: 'スポーツ',
    description: 'スポーツについての話です。サッカーとテニスが好きです。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 310,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-013-001',
        storyId: 'story-013-sports',
        order: 1,
        text: '私はスポーツが大好きです。特に、サッカーとテニスをします。',
        translation: 'Tôi yêu thích thể thao. Đặc biệt, tôi chơi bóng đá và quần vợt.',
        sentences: [
          {
            id: 'sent-013-001',
            paragraphId: 'para-013-001',
            order: 1,
            text: '私はスポーツが大好きです。',
            translation: 'Tôi yêu thích thể thao.',
            tokens: [
              { id: 't1', sentenceId: 'sent-013-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-013-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-013-001', order: 3, word: 'スポーツ', reading: 'スポーツ', pos: 'NOUN', meaning: 'thể thao', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-013-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-013-001', order: 5, word: '大好き', reading: 'だいすき', pos: 'NOUN', meaning: 'rất yêu', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-013-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-013-002',
            paragraphId: 'para-013-001',
            order: 2,
            text: '特に、サッカーとテニスをします。',
            translation: 'Đặc biệt, tôi chơi bóng đá và quần vợt.',
            tokens: [
              { id: 't7', sentenceId: 'sent-013-002', order: 1, word: '特に', reading: 'とくに', pos: 'ADVERB', meaning: 'đặc biệt', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-013-002', order: 2, word: 'サッカー', reading: 'サッカー', pos: 'NOUN', meaning: 'bóng đá', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-013-002', order: 3, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-013-002', order: 4, word: 'テニス', reading: 'テニス', pos: 'NOUN', meaning: 'quần vợt', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-013-002', order: 5, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-013-002', order: 6, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-014-music',
    title: '音楽が好きです',
    titleJp: '音楽が好きです',
    description: '音楽についての話です。毎日音楽を聞きます。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 300,
    estimatedReadTime: 7,
    paragraphs: [
      {
        id: 'para-014-001',
        storyId: 'story-014-music',
        order: 1,
        text: '私は音楽が好きです。毎日ヘッドフォンで音楽を聞きます。ポップとジャズが好きです。',
        translation: 'Tôi thích âm nhạc. Tôi nghe nhạc qua tai nghe mỗi ngày. Tôi thích nhạc pop và jazz.',
        sentences: [
          {
            id: 'sent-014-001',
            paragraphId: 'para-014-001',
            order: 1,
            text: '私は音楽が好きです。',
            translation: 'Tôi thích âm nhạc.',
            tokens: [
              { id: 't1', sentenceId: 'sent-014-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-014-001', order: 2, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-014-001', order: 3, word: '音楽', reading: 'おんがく', pos: 'NOUN', meaning: 'âm nhạc', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-014-001', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-014-001', order: 5, word: '好き', reading: 'すき', pos: 'NOUN', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-014-001', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-014-002',
            paragraphId: 'para-014-001',
            order: 2,
            text: '毎日ヘッドフォンで音楽を聞きます。',
            translation: 'Tôi nghe nhạc qua tai nghe mỗi ngày.',
            tokens: [
              { id: 't7', sentenceId: 'sent-014-002', order: 1, word: '毎日', reading: 'まいにち', pos: 'NOUN', meaning: 'mỗi ngày', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-014-002', order: 2, word: 'ヘッドフォン', reading: 'ヘッドフォン', pos: 'NOUN', meaning: 'tai nghe', jlptLevel: 'N5' },
              { id: 't9', sentenceId: 'sent-014-002', order: 3, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-014-002', order: 4, word: '音楽', reading: 'おんがく', pos: 'NOUN', meaning: 'âm nhạc', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-014-002', order: 5, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-014-002', order: 6, word: '聞きます', reading: 'ききます', pos: 'VERB', meaning: 'nghe', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-014-003',
            paragraphId: 'para-014-001',
            order: 3,
            text: 'ポップとジャズが好きです。',
            translation: 'Tôi thích nhạc pop và jazz.',
            tokens: [
              { id: 't13', sentenceId: 'sent-014-003', order: 1, word: 'ポップ', reading: 'ポップ', pos: 'NOUN', meaning: 'nhạc pop', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-014-003', order: 2, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't15', sentenceId: 'sent-014-003', order: 3, word: 'ジャズ', reading: 'ジャズ', pos: 'NOUN', meaning: 'jazz', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-014-003', order: 4, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-014-003', order: 5, word: '好き', reading: 'すき', pos: 'NOUN', meaning: 'thích', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-014-003', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-015-travel',
    title: '旅行の計画',
    titleJp: '旅行の計画',
    description: '旅行の計画についての話です。家族と一緒に日本を訪問します。',
    level: 'N5',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 350,
    estimatedReadTime: 8,
    paragraphs: [
      {
        id: 'para-015-001',
        storyId: 'story-015-travel',
        order: 1,
        text: '家族と一緒に日本に旅行します。東京と京都に行きたいです。',
        translation: 'Tôi sẽ du lịch đến Nhật Bản với gia đình. Tôi muốn đi Tokyo và Kyoto.',
        sentences: [
          {
            id: 'sent-015-001',
            paragraphId: 'para-015-001',
            order: 1,
            text: '家族と一緒に日本に旅行します。',
            translation: 'Tôi sẽ du lịch đến Nhật Bản với gia đình.',
            tokens: [
              { id: 't1', sentenceId: 'sent-015-001', order: 1, word: '家族', reading: 'かぞく', pos: 'NOUN', meaning: 'gia đình', jlptLevel: 'N5' },
              { id: 't2', sentenceId: 'sent-015-001', order: 2, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't3', sentenceId: 'sent-015-001', order: 3, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng nhau', jlptLevel: 'N5' },
              { id: 't4', sentenceId: 'sent-015-001', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't5', sentenceId: 'sent-015-001', order: 5, word: '日本', reading: 'にほん', pos: 'NOUN', meaning: 'Nhật Bản', jlptLevel: 'N5' },
              { id: 't6', sentenceId: 'sent-015-001', order: 6, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't7', sentenceId: 'sent-015-001', order: 7, word: '旅行', reading: 'りょこう', pos: 'NOUN', meaning: 'du lịch', jlptLevel: 'N5' },
              { id: 't8', sentenceId: 'sent-015-001', order: 8, word: 'します', reading: 'します', pos: 'VERB', meaning: 'làm', jlptLevel: 'N5' },
            ],
          },
          {
            id: 'sent-015-002',
            paragraphId: 'para-015-001',
            order: 2,
            text: '東京と京都に行きたいです。',
            translation: 'Tôi muốn đi Tokyo và Kyoto.',
            tokens: [
              { id: 't9', sentenceId: 'sent-015-002', order: 1, word: '東京', reading: 'とうきょう', pos: 'NOUN', meaning: 'Tokyo', jlptLevel: 'N5' },
              { id: 't10', sentenceId: 'sent-015-002', order: 2, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't11', sentenceId: 'sent-015-002', order: 3, word: '京都', reading: 'きょうと', pos: 'NOUN', meaning: 'Kyoto', jlptLevel: 'N5' },
              { id: 't12', sentenceId: 'sent-015-002', order: 4, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't13', sentenceId: 'sent-015-002', order: 5, word: '行きたい', reading: 'いきたい', pos: 'VERB', meaning: 'muốn đi', jlptLevel: 'N5' },
              { id: 't14', sentenceId: 'sent-015-002', order: 6, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
      {
        id: 'para-015-002',
        storyId: 'story-015-travel',
        order: 2,
        text: 'いろいろな神社と寺院を見たいです。日本の文化を学びたいです。',
        translation: 'Tôi muốn xem nhiều đền thờ và chùa. Tôi muốn học về văn hóa Nhật Bản.',
        sentences: [
          {
            id: 'sent-015-003',
            paragraphId: 'para-015-002',
            order: 1,
            text: 'いろいろな神社と寺院を見たいです。',
            translation: 'Tôi muốn xem nhiều đền thờ và chùa.',
            tokens: [
              { id: 't15', sentenceId: 'sent-015-003', order: 1, word: 'いろいろ', reading: 'いろいろ', pos: 'NOUN', meaning: 'nhiều loại', jlptLevel: 'N5' },
              { id: 't16', sentenceId: 'sent-015-003', order: 2, word: 'な', reading: 'な', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't17', sentenceId: 'sent-015-003', order: 3, word: '神社', reading: 'じんじゃ', pos: 'NOUN', meaning: 'đền thờ', jlptLevel: 'N5' },
              { id: 't18', sentenceId: 'sent-015-003', order: 4, word: 'と', reading: 'と', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't19', sentenceId: 'sent-015-003', order: 5, word: '寺院', reading: 'じいん', pos: 'NOUN', meaning: 'chùa', jlptLevel: 'N5' },
              { id: 't20', sentenceId: 'sent-015-003', order: 6, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N5' },
              { id: 't21', sentenceId: 'sent-015-003', order: 7, word: '見たい', reading: 'みたい', pos: 'VERB', meaning: 'muốn xem', jlptLevel: 'N5' },
              { id: 't22', sentenceId: 'sent-015-003', order: 8, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N5' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-016-n4-job',
    title: '仕事の経験',
    titleJp: '仕事の経験',
    description: 'N4: 初めての仕事についての話です。いろいろな経験をしました。',
    level: 'N4',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 420,
    estimatedReadTime: 10,
    paragraphs: [
      {
        id: 'para-016-001',
        storyId: 'story-016-n4-job',
        order: 1,
        text: '大学を卒業してから、私は会社で働き始めました。最初の日は緊張しましたが、先輩たちが優しく教えてくれました。',
        translation: 'Sau khi tốt nghiệp đại học, tôi bắt đầu làm việc tại công ty. Ngày đầu tiên tôi rất lo lắng, nhưng các anh chị ở công ty đã hướng dẫn tôi một cách chu đáo.',
        sentences: [
          {
            id: 'sent-016-001',
            paragraphId: 'para-016-001',
            order: 1,
            text: '大学を卒業してから、私は会社で働き始めました。',
            translation: 'Sau khi tốt nghiệp đại học, tôi bắt đầu làm việc tại công ty.',
            tokens: [
              { id: 't1', sentenceId: 'sent-016-001', order: 1, word: '大学', reading: 'だいがく', pos: 'NOUN', meaning: 'đại học', jlptLevel: 'N4' },
              { id: 't2', sentenceId: 'sent-016-001', order: 2, word: 'を', reading: 'を', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't3', sentenceId: 'sent-016-001', order: 3, word: '卒業', reading: 'そつぎょう', pos: 'NOUN', meaning: 'tốt nghiệp', jlptLevel: 'N4' },
              { id: 't4', sentenceId: 'sent-016-001', order: 4, word: 'してから', reading: 'してから', pos: 'VERB', meaning: 'sau khi', jlptLevel: 'N4' },
              { id: 't5', sentenceId: 'sent-016-001', order: 5, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N4' },
              { id: 't6', sentenceId: 'sent-016-001', order: 6, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't7', sentenceId: 'sent-016-001', order: 7, word: '会社', reading: 'かいしゃ', pos: 'NOUN', meaning: 'công ty', jlptLevel: 'N4' },
              { id: 't8', sentenceId: 'sent-016-001', order: 8, word: 'で', reading: 'で', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't9', sentenceId: 'sent-016-001', order: 9, word: '働き始めました', reading: 'はたらきはじめました', pos: 'VERB', meaning: 'bắt đầu làm việc', jlptLevel: 'N4' },
            ],
          },
          {
            id: 'sent-016-002',
            paragraphId: 'para-016-001',
            order: 2,
            text: '最初の日は緊張しましたが、先輩たちが優しく教えてくれました。',
            translation: 'Ngày đầu tiên tôi rất lo lắng, nhưng các anh chị ở công ty đã hướng dẫn tôi một cách chu đáo.',
            tokens: [
              { id: 't10', sentenceId: 'sent-016-002', order: 1, word: '最初', reading: 'さいしょ', pos: 'NOUN', meaning: 'đầu tiên', jlptLevel: 'N4' },
              { id: 't11', sentenceId: 'sent-016-002', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't12', sentenceId: 'sent-016-002', order: 3, word: '日', reading: 'ひ', pos: 'NOUN', meaning: 'ngày', jlptLevel: 'N4' },
              { id: 't13', sentenceId: 'sent-016-002', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't14', sentenceId: 'sent-016-002', order: 5, word: '緊張', reading: 'きんちょう', pos: 'NOUN', meaning: 'lo lắng', jlptLevel: 'N4' },
              { id: 't15', sentenceId: 'sent-016-002', order: 6, word: 'しました', reading: 'しました', pos: 'VERB', meaning: 'đã', jlptLevel: 'N4' },
              { id: 't16', sentenceId: 'sent-016-002', order: 7, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't17', sentenceId: 'sent-016-002', order: 8, word: '先輩', reading: 'せんぱい', pos: 'NOUN', meaning: 'anh chị', jlptLevel: 'N4' },
              { id: 't18', sentenceId: 'sent-016-002', order: 9, word: 'たち', reading: 'たち', pos: 'PARTICLE', meaning: 'các', jlptLevel: 'N4' },
              { id: 't19', sentenceId: 'sent-016-002', order: 10, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't20', sentenceId: 'sent-016-002', order: 11, word: '優しく', reading: 'やさしく', pos: 'ADVERB', meaning: 'chu đáo', jlptLevel: 'N4' },
              { id: 't21', sentenceId: 'sent-016-002', order: 12, word: '教えてくれました', reading: 'おしえてくれました', pos: 'VERB', meaning: 'đã dạy', jlptLevel: 'N4' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-017-n4-trip',
    title: '海外旅行',
    titleJp: '海外旅行',
    description: 'N4: 初めての海外旅行についての話です。いろいろな文化を経験しました。',
    level: 'N4',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 400,
    estimatedReadTime: 10,
    paragraphs: [
      {
        id: 'para-017-001',
        storyId: 'story-017-n4-trip',
        order: 1,
        text: '今年の夏、私は初めてベトナムに行きました。飛行機に乗ることが怖かったですが、友達が一緒にいてくれたので、安心できました。',
        translation: 'Mùa hè năm nay, tôi đã đi Việt Nam lần đầu tiên. Tôi sợ bay máy bay, nhưng vì bạn bè ở cùng tôi, nên tôi cảm thấy yên tâm.',
        sentences: [
          {
            id: 'sent-017-001',
            paragraphId: 'para-017-001',
            order: 1,
            text: '今年の夏、私は初めてベトナムに行きました。',
            translation: 'Mùa hè năm nay, tôi đã đi Việt Nam lần đầu tiên.',
            tokens: [
              { id: 't1', sentenceId: 'sent-017-001', order: 1, word: '今年', reading: 'ことし', pos: 'NOUN', meaning: 'năm nay', jlptLevel: 'N4' },
              { id: 't2', sentenceId: 'sent-017-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't3', sentenceId: 'sent-017-001', order: 3, word: '夏', reading: 'なつ', pos: 'NOUN', meaning: 'mùa hè', jlptLevel: 'N4' },
              { id: 't4', sentenceId: 'sent-017-001', order: 4, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N4' },
              { id: 't5', sentenceId: 'sent-017-001', order: 5, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't6', sentenceId: 'sent-017-001', order: 6, word: '初めて', reading: 'はじめて', pos: 'ADVERB', meaning: 'lần đầu tiên', jlptLevel: 'N4' },
              { id: 't7', sentenceId: 'sent-017-001', order: 7, word: 'ベトナム', reading: 'ベトナム', pos: 'NOUN', meaning: 'Việt Nam', jlptLevel: 'N4' },
              { id: 't8', sentenceId: 'sent-017-001', order: 8, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't9', sentenceId: 'sent-017-001', order: 9, word: '行きました', reading: 'いきました', pos: 'VERB', meaning: 'đã đi', jlptLevel: 'N4' },
            ],
          },
          {
            id: 'sent-017-002',
            paragraphId: 'para-017-001',
            order: 2,
            text: '飛行機に乗ることが怖かったですが、友達が一緒にいてくれたので、安心できました。',
            translation: 'Tôi sợ bay máy bay, nhưng vì bạn bè ở cùng tôi, nên tôi cảm thấy yên tâm.',
            tokens: [
              { id: 't10', sentenceId: 'sent-017-002', order: 1, word: '飛行機', reading: 'ひこうき', pos: 'NOUN', meaning: 'máy bay', jlptLevel: 'N4' },
              { id: 't11', sentenceId: 'sent-017-002', order: 2, word: 'に', reading: 'に', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't12', sentenceId: 'sent-017-002', order: 3, word: '乗る', reading: 'のる', pos: 'VERB', meaning: 'lên', jlptLevel: 'N4' },
              { id: 't13', sentenceId: 'sent-017-002', order: 4, word: 'ことが', reading: 'ことが', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't14', sentenceId: 'sent-017-002', order: 5, word: '怖かった', reading: 'こわかった', pos: 'ADJECTIVE', meaning: 'sợ', jlptLevel: 'N4' },
              { id: 't15', sentenceId: 'sent-017-002', order: 6, word: 'ですが', reading: 'ですが', pos: 'VERB', meaning: 'nhưng', jlptLevel: 'N4' },
              { id: 't16', sentenceId: 'sent-017-002', order: 7, word: '友達', reading: 'ともだち', pos: 'NOUN', meaning: 'bạn bè', jlptLevel: 'N4' },
              { id: 't17', sentenceId: 'sent-017-002', order: 8, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't18', sentenceId: 'sent-017-002', order: 9, word: '一緒', reading: 'いっしょ', pos: 'NOUN', meaning: 'cùng', jlptLevel: 'N4' },
              { id: 't19', sentenceId: 'sent-017-002', order: 10, word: 'にいてくれた', reading: 'にいてくれた', pos: 'VERB', meaning: 'đã ở cùng', jlptLevel: 'N4' },
              { id: 't20', sentenceId: 'sent-017-002', order: 11, word: 'ので', reading: 'ので', pos: 'PARTICLE', meaning: 'vì', jlptLevel: 'N4' },
              { id: 't21', sentenceId: 'sent-017-002', order: 12, word: '安心', reading: 'あんしん', pos: 'NOUN', meaning: 'yên tâm', jlptLevel: 'N4' },
              { id: 't22', sentenceId: 'sent-017-002', order: 13, word: 'できました', reading: 'できました', pos: 'VERB', meaning: 'được', jlptLevel: 'N4' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-018-n4-health',
    title: '病気と健康',
    titleJp: '病気と健康',
    description: 'N4: 健康管理についての話です。病気を予防することが大切です。',
    level: 'N4',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 380,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-018-001',
        storyId: 'story-018-n4-health',
        order: 1,
        text: '去年、私は大きな病気になってしまいました。病院で一ヶ月間入院しましたが、医者と看護婦さんのおかげで元気になりました。',
        translation: 'Năm ngoái, tôi đã bị bệnh nặng. Tôi nằm viện một tháng, nhưng nhờ bác sĩ và y tá, tôi đã khỏe mạnh trở lại.',
        sentences: [
          {
            id: 'sent-018-001',
            paragraphId: 'para-018-001',
            order: 1,
            text: '去年、私は大きな病気になってしまいました。',
            translation: 'Năm ngoái, tôi đã bị bệnh nặng.',
            tokens: [
              { id: 't1', sentenceId: 'sent-018-001', order: 1, word: '去年', reading: 'きょねん', pos: 'NOUN', meaning: 'năm ngoái', jlptLevel: 'N4' },
              { id: 't2', sentenceId: 'sent-018-001', order: 2, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N4' },
              { id: 't3', sentenceId: 'sent-018-001', order: 3, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't4', sentenceId: 'sent-018-001', order: 4, word: '大きな', reading: 'おおきな', pos: 'ADJECTIVE', meaning: 'to lớn', jlptLevel: 'N4' },
              { id: 't5', sentenceId: 'sent-018-001', order: 5, word: '病気', reading: 'びょうき', pos: 'NOUN', meaning: 'bệnh', jlptLevel: 'N4' },
              { id: 't6', sentenceId: 'sent-018-001', order: 6, word: 'になってしまいました', reading: 'になってしまいました', pos: 'VERB', meaning: 'đã bị', jlptLevel: 'N4' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-019-n4-tech',
    title: 'スマートフォン',
    titleJp: 'スマートフォン',
    description: 'N4: スマートフォンが生活を変えたについての話です。',
    level: 'N4',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 360,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-019-001',
        storyId: 'story-019-n4-tech',
        order: 1,
        text: 'スマートフォンが出てきてから、私たちの生活は大きく変わりました。誰でも簡単に連絡できるようになったし、分からないことがあればすぐに調べることができます。',
        translation: 'Kể từ khi điện thoại thông minh xuất hiện, cuộc sống của chúng tôi đã thay đổi rất nhiều. Mọi người có thể liên lạc dễ dàng, và nếu có điều gì không hiểu, có thể tìm kiếm ngay.',
        sentences: [
          {
            id: 'sent-019-001',
            paragraphId: 'para-019-001',
            order: 1,
            text: 'スマートフォンが出てきてから、私たちの生活は大きく変わりました。',
            translation: 'Kể từ khi điện thoại thông minh xuất hiện, cuộc sống của chúng tôi đã thay đổi rất nhiều.',
            tokens: [
              { id: 't1', sentenceId: 'sent-019-001', order: 1, word: 'スマートフォン', reading: 'スマートフォン', pos: 'NOUN', meaning: 'điện thoại thông minh', jlptLevel: 'N4' },
              { id: 't2', sentenceId: 'sent-019-001', order: 2, word: 'が', reading: 'が', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't3', sentenceId: 'sent-019-001', order: 3, word: '出てきてから', reading: 'でてきてから', pos: 'VERB', meaning: 'kể từ khi xuất hiện', jlptLevel: 'N4' },
              { id: 't4', sentenceId: 'sent-019-001', order: 4, word: '私たち', reading: 'わたしたち', pos: 'NOUN', meaning: 'chúng tôi', jlptLevel: 'N4' },
              { id: 't5', sentenceId: 'sent-019-001', order: 5, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't6', sentenceId: 'sent-019-001', order: 6, word: '生活', reading: 'せいかつ', pos: 'NOUN', meaning: 'cuộc sống', jlptLevel: 'N4' },
              { id: 't7', sentenceId: 'sent-019-001', order: 7, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't8', sentenceId: 'sent-019-001', order: 8, word: '大きく', reading: 'おおきく', pos: 'ADVERB', meaning: 'rất nhiều', jlptLevel: 'N4' },
              { id: 't9', sentenceId: 'sent-019-001', order: 9, word: '変わりました', reading: 'かわりました', pos: 'VERB', meaning: 'đã thay đổi', jlptLevel: 'N4' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
  {
    id: 'story-020-n4-dream',
    title: '夢と目標',
    titleJp: '夢と目標',
    description: 'N4: 夢をかなえるための努力についての話です。',
    level: 'N4',
    category: 'slice-of-life',
    author: 'Anonymous',
    wordCount: 370,
    estimatedReadTime: 9,
    paragraphs: [
      {
        id: 'para-020-001',
        storyId: 'story-020-n4-dream',
        order: 1,
        text: '私の夢は日本語の先生になることです。そのために毎日勉強しています。難しいこともありますが、頑張り続けたいと思っています。',
        translation: 'Giấc mơ của tôi là trở thành giáo viên tiếng Nhật. Để thực hiện điều đó, tôi học tập mỗi ngày. Mặc dù có những điều khó khăn, tôi muốn tiếp tục cố gắng.',
        sentences: [
          {
            id: 'sent-020-001',
            paragraphId: 'para-020-001',
            order: 1,
            text: '私の夢は日本語の先生になることです。',
            translation: 'Giấc mơ của tôi là trở thành giáo viên tiếng Nhật.',
            tokens: [
              { id: 't1', sentenceId: 'sent-020-001', order: 1, word: '私', reading: 'わたし', pos: 'NOUN', meaning: 'tôi', jlptLevel: 'N4' },
              { id: 't2', sentenceId: 'sent-020-001', order: 2, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't3', sentenceId: 'sent-020-001', order: 3, word: '夢', reading: 'ゆめ', pos: 'NOUN', meaning: 'giấc mơ', jlptLevel: 'N4' },
              { id: 't4', sentenceId: 'sent-020-001', order: 4, word: 'は', reading: 'は', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't5', sentenceId: 'sent-020-001', order: 5, word: '日本語', reading: 'にほんご', pos: 'NOUN', meaning: 'tiếng Nhật', jlptLevel: 'N4' },
              { id: 't6', sentenceId: 'sent-020-001', order: 6, word: 'の', reading: 'の', pos: 'PARTICLE', meaning: '(particle)', jlptLevel: 'N4' },
              { id: 't7', sentenceId: 'sent-020-001', order: 7, word: '先生', reading: 'せんせい', pos: 'NOUN', meaning: 'giáo viên', jlptLevel: 'N4' },
              { id: 't8', sentenceId: 'sent-020-001', order: 8, word: 'になること', reading: 'になること', pos: 'VERB', meaning: 'trở thành', jlptLevel: 'N4' },
              { id: 't9', sentenceId: 'sent-020-001', order: 9, word: 'です', reading: 'です', pos: 'VERB', meaning: 'là', jlptLevel: 'N4' },
            ],
          },
        ],
      },
    ],
    createdAt: '2026-05-05',
    lastUpdated: '2026-05-05',
  },
];
