import type { AdminGuide } from '../../../../types/content';

const creditCardForForeigners: AdminGuide = {
    id: 'credit-card-for-foreigners',
    category: 'money',
    lastVerified: '2026-08-21',
    priority: 'normal',
    title: 'Làm thẻ tín dụng tại Nhật',
    titleJp: 'クレジットカード申請・信用情報の作り方',
    icon: 'card',
    color: '#6C3483',
    description: 'Người nước ngoài mới sang Nhật thường bị từ chối thẻ tín dụng vì chưa có lịch sử tín dụng (信用情報) tại Nhật. Guide này giải thích cách bắt đầu đúng, thẻ nào dễ được duyệt nhất và cách xây dựng tín dụng để mở rộng quyền lợi về sau.',
    searchKeywords: [
      'thẻ tín dụng',
      'làm thẻ credit',
      'credit card Nhật',
      'クレジットカード',
      'credit card Japan',
      '信用情報',
      'shinyou jouhou',
      'credit bureau Japan',
      'CIC',
      'JICC',
      'KSC',
      '全国銀行個人信用情報センター',
      '本人確認',
      '審査',
      'shinsa',
      'duyệt thẻ',
      '与信',
      '口座振替',
      'kouza furikae',
      'auto-debit',
      'リボ払い',
      'リボ',
      'rebo',
      'revolving payment',
      'キャッシング',
      'cash advance',
      '年収',
      '住宅ローン',
      'lịch sử tín dụng',
      'bị từ chối thẻ tín dụng',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Phát hành thẻ tín dụng + quản lý 信用情報 (credit data) chịu điều chỉnh bởi 割賦販売法 (Installment Sales Act) + 個人情報保護法. 3 cơ quan tín dụng chính: CIC (CIC), JICC (JICC), 全国銀行個人信用情報センター (KSC) — đều có nghĩa vụ cấp 開示 (xem lịch sử) cho chính chủ. Mỗi công ty thẻ có tiêu chí xét duyệt riêng — guide chỉ định hướng, KHÔNG đảm bảo được duyệt.',
      sourceVerifiedAt: '2026-08-21',
      nextReviewAt: '2026-12-01',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Bị từ chối nhiều thẻ liên tiếp mà không hiểu lý do → khai示 信用情報 từ CIC/JICC/KSC trước, có thể có lỗi data — gọi 国民生活センター 188 nếu có tranh chấp.',
        'Đang nợ thẻ quá hạn / được gọi 督促 từ thu nợ → hỏi 国民生活センター hoặc 法テラス (legal aid); không trốn — nợ quá hạn ảnh hưởng visa/vĩnh trú.',
        'Nghi bị lừa đảo / phishing dùng thẻ → KHÔNG xử lý 1 mình, gọi cấp tốc số dịch vụ khẩn cấp thẻ + 警察 #9110 (cyber).',
        'Có nợ リボ払い lớn không trả nổi → tham vấn 弁護士 / 司法書士 về 任意整理 hoặc 個人再生 trước khi để 自己破産.',
      ],
    },
    quickAction: {
      deadline: 'Không có hạn cố định. Tuy nhiên: sau 3-6 tháng có tài khoản ngân hàng + lương ổn định = thời điểm tốt nhất xin thẻ đầu tiên. Nộp dồn dập nhiều thẻ trong 1-2 tháng = phản tác dụng (bị ghi nhiều lần "申込" vào 信用情報).',
      office: 'Website / app công ty thẻ (Rakuten Card, Epos, Aeon, viettin với ngân hàng đang có TK). Khai示 信用情報: trực tiếp tại CIC/JICC/KSC online hoặc bưu điện.',
      doNow: [
        'Đảm bảo có: tài khoản ngân hàng Nhật ≥ 3-6 tháng + số điện thoại Nhật + 在留カード còn hạn ≥ 1 năm.',
        'Chọn 1 thẻ phù hợp người mới (Rakuten Card / Epos / Aeon Card / thẻ từ ngân hàng đang dùng) — KHÔNG nộp nhiều thẻ cùng lúc.',
        'Điền hồ sơ online: tên romaji KHỚP 在留カード + địa chỉ tiếng Nhật KHỚP 住民票 + 在留カード số + tư cách lưu trú + 年収.',
        'Sai 1 chữ trong tên/địa chỉ = từ chối tự động — xác minh kỹ trước khi submit.',
        'Đợi 1-2 tuần kết quả. Bị từ chối: KHÔNG nộp lại trong 6 tháng — chờ ổn định hồ sơ.',
        'Được duyệt: dùng đều mỗi tháng + thanh toán 全額 đúng hạn để xây dựng 信用情報.',
      ],
      bring: [
        '在留カード còn hiệu lực (số + tư cách + ngày hết hạn)',
        'Số tài khoản ngân hàng Nhật + tên chi nhánh',
        'Số điện thoại Nhật',
        'Địa chỉ tiếng Nhật khớp 住民票',
        '年収 ước tính (lương năm trước thuế)',
        'Email Nhật',
      ],
      ifLate: 'Trễ thanh toán 1 lần: ghi vào 信用情報 (異動) 5 năm — ảnh hưởng xin thẻ khác hoặc vay 住宅ローン. Trễ nhiều lần / bị 督促状: nguy hiểm hơn — báo cho 信用情報 6-7 năm + có thể bị 強制解約. Cách xử lý: gọi công ty thẻ NGAY khi biết sẽ trễ + xin 分割払い hoặc 一時的猶予 trước khi quá hạn. KHÔNG bỏ ngơ.',
      officialSourceLabels: ['信用情報とは — CIC'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_credit-card_hero.jpg'),
    heroImageCaption: 'クレジットカード - xây dựng 信用情報 từng bước khi mới sang Nhật',
    whoIsThisFor: [
      'Người mới sang Nhật và muốn làm thẻ tín dụng nhưng chưa biết bắt đầu từ đâu.',
      'Người đã bị từ chối thẻ tín dụng và muốn hiểu lý do, cách cải thiện.',
      'Người muốn xây dựng 信用情報 để sau này dễ vay 住宅ローン hoặc xe ô tô.',
    ],
    whenToDo: [
      'Sau khi có tài khoản ngân hàng Nhật và đã cư trú ít nhất 3–6 tháng — nhiều công ty thẻ yêu cầu tài khoản ngân hàng Nhật để trích nợ tự động (口座振替).',
      'Không nên nộp đơn xin nhiều thẻ cùng lúc — mỗi lần xin bị ghi vào 信用情報 và nhiều lần từ chối liên tiếp làm xấu hồ sơ.',
    ],
    whereToDo: [
      'Website/app của công ty thẻ hoặc ngân hàng: nộp đơn xin thẻ và đăng ký 口座振替.',
      'Ngân hàng nơi bạn nhận lương: hỏi thẻ credit/debit phù hợp với hồ sơ hiện tại.',
      'CIC/JICC/KSC: kiểm tra 信用情報 của chính mình nếu bị từ chối nhiều lần hoặc nghi có lỗi dữ liệu.',
      'Municipal office/bưu điện: xác nhận địa chỉ và tên hiển thị trên giấy tờ nếu hồ sơ bị lệch thông tin.',
    ],
    documentsChecklist: [
      { label: '在留カード còn hiệu lực', required: true },
      { label: 'Tài khoản ngân hàng Nhật để trích nợ tự động', required: true },
      { label: 'Số điện thoại Nhật', required: true },
      { label: 'Địa chỉ hiện tại khớp 住民票/在留カード', required: true },
      { label: 'Thông tin việc làm và thu nhập năm', required: true },
      { label: 'My Number hoặc giấy tờ bổ sung', required: false, note: 'Một số tổ chức tài chính yêu cầu trong quy trình xác minh.' },
    ],
    commonMistakes: [
      'Nộp nhiều thẻ liên tiếp trong thời gian ngắn sau khi bị từ chối.',
      'Điền tên/địa chỉ không khớp giấy tờ Nhật, làm hệ thống xác minh tự động thất bại.',
      'Dùng リボ払い vì thấy số tiền trả hàng tháng thấp, nhưng không hiểu lãi cao và dư nợ kéo dài.',
      'Trả chậm tiền điện thoại trả góp hoặc thẻ tín dụng, khiến 信用情報 bị ảnh hưởng.',
      'Không kiểm tra lại 信用情報 khi nghi có sai sót hoặc bị từ chối bất thường.',
    ],
    faq: [
      {
        question: 'Bị từ chối thẻ có nghĩa là hồ sơ xấu không?',
        answer: 'Không nhất thiết. Với người mới ở Nhật, lý do thường là hồ sơ tín dụng còn mỏng, thời hạn lưu trú ngắn, thông tin xác minh chưa ổn hoặc tiêu chuẩn riêng của công ty thẻ. Nên chờ một thời gian, ổn định thu nhập và không nộp dồn dập.',
      },
      {
        question: 'Debit card có giúp xây 信用情報 không?',
        answer: 'Thường không. Debit card trừ tiền trực tiếp từ tài khoản nên không tạo lịch sử vay/trả như credit card. Nó hữu ích để thanh toán, nhưng không thay thế credit history.',
      },
      {
        question: 'Có thể tự xem 信用情報 của mình không?',
        answer: 'Có. CIC, JICC và 全国銀行個人信用情報センター đều có thủ tục khai示 cho chính người đó. Hãy kiểm tra cách nộp, giấy tờ và phí hiện hành trên trang chính thức từng tổ chức.',
      },
    ],
    counterPhrases: [
      {
        jp: 'クレジットカードを申し込みたいです。',
        romaji: 'Kurejitto kaado o moushikomitai desu.',
        vn: 'Tôi muốn nộp đơn xin thẻ tín dụng.',
        note: 'Tại quầy ngân hàng đang có tài khoản — họ có thể cấp thẻ liên kết.',
      },
      {
        jp: '審査に通らなかった理由を教えていただけますか。',
        romaji: 'Shinsa ni tooranakatta riyuu o oshiete itadakemasu ka.',
        vn: 'Cho tôi biết lý do bị từ chối được không?',
        note: 'Công ty thẻ thường KHÔNG nói lý do cụ thể (luật bảo mật) — nhưng có thể khai示 信用情報 ở CIC/JICC để tự kiểm tra.',
      },
      {
        jp: '今月の支払いを分割払いにできますか。',
        romaji: 'Kongetsu no shiharai o bunkatsu barai ni dekimasu ka.',
        vn: 'Có thể chia kỳ thanh toán tháng này không?',
        note: 'Gọi công ty thẻ TRƯỚC khi đến hạn — đỡ hơn nhiều so với để trễ.',
      },
      {
        jp: 'リボ払いの解除をお願いします。',
        romaji: 'Ribo barai no kaijo o onegai shimasu.',
        vn: 'Tôi muốn huỷ chế độ trả góp リボ.',
        note: 'リボ là chế độ rất tốn tiền (15-18%/năm). Huỷ qua app/website hoặc gọi điện thoại.',
      },
      {
        jp: '紛失したカードを止めてください。',
        romaji: 'Funshitsu shita kaado o tomete kudasai.',
        vn: 'Xin khoá thẻ bị mất.',
        note: 'Gọi số khẩn cấp 24h của công ty thẻ ngay — số in trên website chính thức (KHÔNG gọi qua link Google).',
      },
    ],
    keyTerms: [
      {
        term: '信用情報',
        reading: 'しんようじょうほう',
        meaningVi: 'lịch sử tín dụng (do CIC/JICC/KSC quản lý)',
        noteVi: 'Hồ sơ ghi mọi lần xin thẻ + vay + thanh toán + trễ hạn. 5-7 năm. Công ty thẻ tra trước khi duyệt. KHÔNG có 信用情報 không phải xấu — chỉ là "薄い信用情報" (thin file). Tự xem được qua 開示請求 (~1,000円 mỗi nơi).',
      },
      {
        term: '審査',
        reading: 'しんさ',
        meaningVi: 'xét duyệt (đơn xin thẻ)',
        noteVi: 'Mỗi công ty thẻ có tiêu chí riêng. Yếu tố ảnh hưởng: 年収 + nghề + thời gian làm + hạn 在留 + lịch sử thanh toán. Người mới sang Nhật: 6-12 tháng có lương ổn định + tài khoản ngân hàng dùng đều là điểm cộng. KHÔNG ai biết công thức chính xác — không "chắc đậu".',
      },
      {
        term: '口座振替',
        reading: 'こうざふりかえ',
        meaningVi: 'trừ tự động từ tài khoản',
        noteVi: 'Phương thức thanh toán mặc định cho credit card ở Nhật. Trừ tiền vào ngày cố định mỗi tháng (10, 15, 27 tuỳ thẻ) từ tài khoản đăng ký. Số dư không đủ = bị 引落不能 → ghi vào 信用情報. Luôn để dư tiền trước ngày trừ.',
      },
      {
        term: 'リボ払い',
        reading: 'リボばらい',
        meaningVi: 'chế độ trả nhỏ giọt hàng tháng (lãi suất cao)',
        noteVi: 'Tên đầy đủ: リボルビング払い. Bạn chọn 1 số tiền cố định/tháng (vd ¥5,000) → công ty thẻ thu số đó + lãi (15-18%/năm). Dư nợ kéo dài năm, lãi rất nặng. Thường được set MẶC ĐỊNH trên 1 số thẻ (vd JCB) — kiểm tra + huỷ ngay. Khác với 分割払い (chia số kỳ cố định).',
      },
      {
        term: '全額払い',
        reading: 'ぜんがくばらい',
        meaningVi: 'thanh toán toàn bộ trong 1 lần',
        noteVi: 'Cách dùng credit card đúng. Trả 100% số đã chi trong tháng vào ngày 引落. KHÔNG có lãi. Hiển thị trong setting thanh toán là "1回払い" hoặc "翌月一括". Là mặc định an toàn nhất — đừng đổi sang リボ.',
      },
      {
        term: 'キャッシング',
        reading: 'キャッシング',
        meaningVi: 'rút tiền mặt từ thẻ tín dụng (lãi suất rất cao)',
        noteVi: 'Tính năng vay tiền mặt qua thẻ tín dụng. Lãi 18%/năm + có thể có phí. CHỈ DÙNG khi cấp cứu — nợ tiêu dùng thông thường nên dùng 銀行カードローン rẻ hơn. Hiển thị giới hạn キャッシング riêng trên thẻ — có thể set về 0円 để tránh dùng nhầm.',
      },
      {
        term: 'CIC / JICC / KSC',
        reading: 'シーアイシー / ジェイアイシーシー / ケーエスシー',
        meaningVi: '3 cơ quan tín dụng cá nhân của Nhật',
        noteVi: 'CIC (信販系 — Rakuten/JCB/AEON), JICC (消費者金融系 — Aiful/Promise), KSC (銀行系 — ngân hàng + 住宅ローン). Mỗi nơi có hồ sơ khác. Tự xem được qua 開示請求 — phí ~1,000円/nơi (online qua điện thoại + クレカ), hoặc bưu điện. Đọc ký hiệu: $ = trả đúng, A = trễ, P = trả 1 phần, 異動 = báo nợ xấu (5 năm).',
      },
      {
        term: '年収',
        reading: 'ねんしゅう',
        meaningVi: 'thu nhập năm (trước thuế)',
        noteVi: 'Tổng lương 12 tháng + bonus + side income. Hỏi trong đơn xin thẻ — KHÔNG cần chứng từ khi đăng ký online (chỉ tự khai). Người mới chưa làm đủ 1 năm: ước tính dựa trên lương tháng × 12 + ghi rõ là "見込み" (dự kiến). KHÔNG khai khống — công ty thẻ có thể đối chiếu sau qua マイナンバー.',
      },
    ],
    officialLinks: [
      { label: '信用情報とは — CIC', url: 'https://www.cic.co.jp/confidence/index.html' },
      { label: '情報開示とは — CIC', url: 'https://www.cic.co.jp/mydata/index.html' },
      { label: '信用情報について — JICC', url: 'https://www.jicc.co.jp/aboutus/credit-info' },
      { label: '全国銀行個人信用情報センター — 全国銀行協会', url: 'https://www.zenginkyo.or.jp/pcic/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Hiểu tại sao người nước ngoài dễ bị từ chối',
        description: 'Nhật Bản dùng hệ thống 信用情報 (credit bureau) quản lý bởi 3 tổ chức chính: CIC, JICC và 全国銀行個人信用情報センター (KSC). Khi mới sang Nhật, bạn không có hồ sơ trong hệ thống này — gọi là "薄い信用情報" (thin file). Công ty thẻ không thể đánh giá rủi ro nên từ chối.\n\nNgoài ra, các yếu tố làm khó thêm:\n• Thời hạn lưu trú ngắn còn lại trên 在留カード.\n• Chưa có hợp đồng lao động ổn định hoặc thu nhập thấp.\n• Địa chỉ thay đổi nhiều lần trong thời gian ngắn.\n• Chưa có tài khoản ngân hàng Nhật đủ lâu.',
        documents: [],
        tip: 'Không cần lo lắng quá — đây là tình trạng bình thường với bất kỳ người nào mới đến một quốc gia mới, kể cả người Nhật khi sang Mỹ lần đầu. Giải pháp là xây dựng từng bước, không phải chờ đợi.',
      },
      {
        step: 2,
        title: 'Bắt đầu với thẻ dễ được duyệt nhất',
        description: 'Theo thứ tự ưu tiên cho người mới:\n\n1. **Thẻ debit có chức năng Visa/Mastercard**: không cần xét duyệt tín dụng — mở cùng tài khoản ngân hàng. Dùng để thanh toán trực tuyến và tích điểm, nhưng thường không xây dựng 信用情報.\n\n2. **Thẻ tín dụng từ ngân hàng bạn đang có tài khoản**: dễ kiểm tra thông tin hơn vì ngân hàng đã có lịch sử giao dịch của bạn.\n\n3. **Thẻ từ cửa hàng hoặc dịch vụ bạn dùng thường xuyên**: đôi khi phù hợp hơn thẻ ngân hàng truyền thống, nhưng vẫn tùy tiêu chuẩn xét duyệt từng công ty.\n\n4. **Thẻ từ ngân hàng lớn hoặc thẻ premium**: thường phù hợp hơn sau khi đã có 6-12 tháng lịch sử tín dụng tại Nhật.',
        documents: [],
        tip: 'Không có thẻ nào "chắc chắn đậu". Chọn một thẻ phù hợp hồ sơ hiện tại, điền thông tin thật chính xác, rồi chờ kết quả thay vì nộp hàng loạt.',
      },
      {
        step: 3,
        title: 'Chuẩn bị hồ sơ xin thẻ',
        description: 'Thông tin cần cung cấp khi đăng ký (thường online, mất 10–15 phút):\n\n• Họ tên (romaji khớp với 在留カード và hộ chiếu)\n• Địa chỉ hiện tại (tiếng Nhật, chính xác theo 住民票)\n• Ngày sinh, quốc tịch\n• Tình trạng việc làm và thu nhập năm (年収)\n• Thông tin 在留カード: số thẻ, tư cách lưu trú, ngày hết hạn\n• Tài khoản ngân hàng Nhật để thanh toán tự động\n• Số điện thoại Nhật (bắt buộc cho xác thực)\n\nThẻ vật lý gửi về nhà sau 1–2 tuần nếu được duyệt.',
        documents: [
          '在留カード (số thẻ, tư cách lưu trú, ngày hết hạn)',
          'Tài khoản ngân hàng Nhật (số tài khoản và tên ngân hàng)',
          'Số điện thoại Nhật',
          'Thu nhập năm ước tính (年収) — không cần chứng từ khi đăng ký online',
        ],
        tip: 'Điền tên và địa chỉ chính xác 100% như trên 在留カード — sai một chữ có thể bị từ chối tự động. Tư cách lưu trú và ngày hết hạn là thông tin công ty thẻ kiểm tra kỹ nhất.',
      },
      {
        step: 4,
        title: 'Xây dựng 信用情報 để nâng hạn mức và mở rộng quyền lợi',
        description: 'Sau khi có thẻ đầu tiên, dùng đúng cách để xây dựng hồ sơ tín dụng:\n\n• Dùng đều hàng tháng: thanh toán điện, gas, điện thoại, Netflix qua thẻ — tạo lịch sử giao dịch đều đặn.\n• Thanh toán đầy đủ (全額払い) đúng hạn hàng tháng — không trả trễ dù chỉ 1 lần, vì ghi vào 信用情報 ngay.\n• Không dùng quá 30% hạn mức: nếu hạn mức 30 vạn yên, giữ số dư dưới 9 vạn yên tại bất kỳ thời điểm nào.\n• Sau 6–12 tháng: có thể xin nâng hạn mức hoặc xin thêm thẻ từ công ty khác.\n\nTránh: trả trả góp (リボ払い) — lãi suất 15–18%/năm, rất cao; và dịch vụ キャッシング (rút tiền mặt từ thẻ tín dụng) trừ trường hợp khẩn cấp.',
        documents: [],
        tip: 'Sau 1–2 năm có lịch sử tín dụng tốt, bạn có thể yêu cầu khai示 信用情報 tại CIC/JICC/KSC để biết hồ sơ mình ra sao trước khi xin vay lớn như 住宅ローン. Kiểm tra phí và cách nộp hiện hành trên trang chính thức.',
      },
    ],
  };

export default creditCardForForeigners;
