import type { AdminGuide } from '../../../../types/content';

const divorceCustodyNameResidence: AdminGuide = {
    id: 'divorce-custody-name-residence',
    category: 'daily-law',
    lastVerified: '2026-05-16',
    priority: 'high',
    title: 'Ly hôn, nuôi con và giấy tờ cư trú',
    titleJp: '離婚・親権・氏名変更・在留手続き',
    icon: 'document-attach',
    color: '#7F8C8D',
    description: 'Guide thực tế cho người nước ngoài ở Nhật khi hôn nhân đổ vỡ: nộp 離婚届, con ở với ai, đổi họ của con, đổi tên trên giấy tờ và ảnh hưởng đến visa/cư trú. Nhiều mốc pháp lý ngắn (14 ngày báo ISA, 10 ngày nộp 裁判離婚). Luật mới về 親権 hiệu lực 01/04/2026. Đây là tài liệu tham khảo — KHÔNG thay thế tư vấn luật sư cá nhân; trường hợp có DV / tranh chấp con / visa rủi ro phải tham vấn 弁護士 / 法テラス ngay.',
    searchKeywords: [
      'ly hôn ở Nhật',
      'ly hôn người nước ngoài',
      '離婚',
      'rikon',
      '離婚届',
      'rikon todoke',
      '協議離婚',
      'kyougi rikon',
      '裁判離婚',
      'saiban rikon',
      '親権',
      'shinken',
      'parental authority',
      '共同親権',
      'kyoudou shinken',
      '養育費',
      'youikuhi',
      'child support',
      '面会交流',
      'menkai kouryuu',
      '子の氏の変更',
      'đổi họ con',
      '配偶者ビザ ly hôn',
      'spouse visa divorce',
      '14 ngày báo ISA ly hôn',
      'DV ly hôn',
      'domestic violence',
      '家庭裁判所',
      '調停離婚',
    ],
    legalScope: {
      jurisdiction: 'mixed',
      jurisdictionNote: '離婚 do 民法 + 戸籍法 + 家事事件手続法 quản lý toàn quốc. SỬA ĐỔI LỚN có hiệu lực 01/04/2026: 民法 cho phép 共同親権 (cả hai cha mẹ giữ 親権) sau ly hôn — trước đó chỉ một bên. ISA quản lý visa-related notification theo 入管法 §19-16. 家庭裁判所 (Family Court) xét tranh chấp 親権 / 養育費 / 面会交流 + 子の氏の変更許可. Quyết định cá nhân phụ thuộc tổng thể hoàn cảnh + lợi ích trẻ + đánh giá tòa — KHÔNG có công thức. Người nước ngoài còn phải xem luật của nước mang quốc tịch (Việt Nam: Luật Hôn nhân Gia đình 2014) — vấn đề song pháp lý phức tạp, cần 弁護士 chuyên 国際家事.',
      sourceVerifiedAt: '2026-05-16',
      nextReviewAt: '2026-10-31',
      riskLevel: 'high',
      whenToAskExpert: [
        'Có DV / bạo lực gia đình / đe doạ / bị giữ giấy tờ → KHÔNG tự xử lý. Liên hệ ngay 配偶者暴力相談支援センター 0570-0-55210, hoặc gọi 110 / 警察 #9110 (cyber stalking). Trung tâm hỗ trợ phụ nữ VN tại Nhật cũng có thể giới thiệu shelter.',
        'Có tranh chấp 親権 / 養育費 / 面会交流 → KHÔNG ký 離婚届 vội. Tham vấn 弁護士 chuyên 家事 hoặc nộp 調停 (mediation) tại 家庭裁判所 trước.',
        'Đang ở diện 家族滞在 / 日本人の配偶者等 / 永住者の配偶者等 → cần 弁護士 / 行政書士 chuyên 入管 đánh giá khả năng chuyển sang diện khác (vd 定住者 nếu có con Nhật + nuôi dưỡng thực tế) TRƯỚC khi nộp 離婚届.',
        'Hôn nhân có yếu tố nước ngoài (vợ/chồng/con khác quốc tịch) → 弁護士 chuyên 国際家事 + Đại sứ quán Việt Nam phối hợp. Hague Convention on Child Abduction áp dụng khi đưa con qua biên giới.',
        'Thu nhập thấp / không đủ tiền thuê luật sư → 法テラス 0570-078374 (Japan Legal Support Center) tư vấn miễn phí lần đầu + có thể trả góp phí luật sư.',
        'Con sinh trước đăng ký kết hôn (婚外子) / 認知 chưa làm → tham vấn 弁護士 vì quyền của cha-con phụ thuộc 認知 status, không phải tự động.',
      ],
    },
    quickAction: {
      deadline: '14 ngày báo ISA khi ly hôn (cho diện 家族滞在 / 日本人の配偶者等 / 永住者の配偶者等). 14 ngày đổi 在留カード khi tên hợp pháp đổi. 10 ngày nộp 離婚届 sau khi 裁判離婚 có hiệu lực. 協議離婚: nộp 離婚届 bất kỳ lúc nào sau khi 2 bên + 2 nhân chứng ký.',
      office: '市役所 / 区役所 (cho 離婚届 + 戸籍 + 住民票). 家庭裁判所 (Family Court — cho 調停 / 親権 / 養育費 / 子の氏の変更). ISA (cho visa notification + tư cách lưu trú thay đổi). 法テラス 0570-078374 (Japan Legal Support Center). 配偶者暴力相談支援センター 0570-0-55210 (DV hotline 24/7).',
      doNow: [
        'TRƯỚC khi ký 離婚届: nếu có con / tài sản / visa rủi ro → tham vấn 弁護士 (法テラス nếu thu nhập thấp). KHÔNG để cảm xúc thúc đẩy ký nhanh.',
        'Có DV / đe doạ: KHÔNG ký ở nhà. Liên hệ 配偶者暴力相談支援センター ngay — họ giúp shelter + tư vấn pháp lý + bảo mật giấy tờ.',
        'Chuẩn bị giấy tờ: 戸籍謄本, 住民票, 在留カード, hộ chiếu, hợp đồng nhà, thông tin tài chính 2 bên, giấy khai sinh con.',
        'Quyết định loại ly hôn: (a) 協議離婚 — 2 bên đồng ý + 2 nhân chứng ký 離婚届; (b) 調停離婚 — qua 家庭裁判所 hoà giải khi không thoả thuận được; (c) 裁判離婚 — kiện ra tòa.',
        'Sau khi ly hôn: trong 14 ngày → nộp 配偶者に関する届出 cho ISA; cập nhật 在留カード nếu tên đổi; cập nhật 住民票 + 戸籍; báo công ty + ngân hàng + trường con.',
        'Nếu cần đổi họ con: nộp 子の氏の変更許可申立 tại 家庭裁判所 (¥800 tem/trẻ). Sau khi tòa duyệt → cập nhật 戸籍 tại 市役所.',
        'Nếu visa hiện tại gắn hôn nhân: tham vấn 行政書士 / 弁護士 SỚM về khả năng đổi sang 定住者 (nếu có con Nhật + nuôi dưỡng thực tế) hoặc visa khác phù hợp.',
      ],
      bring: [
        '離婚届 (form 市役所 phát, có chỗ ký 2 nhân chứng)',
        '戸籍謄本 mới (≤ 3 tháng)',
        '在留カード + hộ chiếu',
        'Hộ chiếu / 戸籍 của vợ/chồng (nếu là người Nhật)',
        'Giấy khai sinh con (cho thủ tục 親権)',
        '判決書 / 調停調書 (cho 裁判 / 調停離婚)',
        'Con dấu / chữ ký mẫu',
        'Tài liệu DV nếu có (ảnh, sao kê y tế, ghi âm) — KHÔNG đem vào nhà nếu nguy hiểm',
      ],
      ifLate: 'Quá 14 ngày báo ISA: vi phạm 入管法 §19-16 — có thể ảnh hưởng đánh giá khi gia hạn / đổi visa. Đến ISA giải trình ngay + mang lý do hợp lý nếu có. Quá 10 ngày 裁判離婚 nộp 離婚届: 市役所 vẫn nhận nhưng có thể bị phạt hành chính theo 戸籍法. Không cập nhật 在留カード sau đổi tên: KHÔNG dùng được thẻ cho ngân hàng / hợp đồng + có thể bị Nyukan nhắc nhở. Tham vấn 弁護士 / 行政書士 nếu lo về visa.',
      officialSourceLabels: ['離婚届 — 法務省', '離婚を考えている方へ — 法務省', '配偶者に関する届出 — 出入国在留管理庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_divorce_hero.jpg'),
    heroImageCaption: 'Ly hôn tại Nhật - kiểm tra 離婚届, quyền nuôi con và thay đổi giấy tờ cư trú',
    whoIsThisFor: [
      'Người nước ngoài ở Nhật đang chuẩn bị ly hôn hoặc vừa ly hôn.',
      'Gia đình có con chung và cần hiểu sau ly hôn phải quyết định gì cho con.',
      'Người đang ở diện spouse/dependent và lo ảnh hưởng tới cư trú sau khi ly hôn.',
    ],
    whenToDo: [
      'Trước khi ký và nộp 離婚届, đặc biệt nếu có con, tài sản chung hoặc đang ở diện visa gắn với hôn nhân.',
      'Ngay sau khi ly hôn hoặc ly thân thực tế, để không trễ các mốc thông báo cư trú và đổi giấy tờ.',
      'Càng cần đọc sớm nếu vụ việc có bạo lực gia đình, đe dọa, kiểm soát giấy tờ hoặc tranh chấp đưa con đi.',
    ],
    whereToDo: [
      'City hall / ward office: 離婚届, hộ tịch, địa chỉ cư trú và một số thay đổi dân cư liên quan.',
      '家庭裁判所: tranh chấp về con, nuôi con, thay đổi họ của con, điều chỉnh sau ly hôn khi không tự thỏa thuận được.',
      'ISA: thông báo ly hôn trong 14 ngày đối với một số diện cư trú và xử lý thay đổi tư cách lưu trú nếu cần.',
      'Ngân hàng, công ty, bảo hiểm, trường học của con: cập nhật tên, địa chỉ, tài khoản nhận trợ cấp và người giám hộ.',
    ],
    estimatedTime: 'Không có một timeline chung cho mọi gia đình. Nhưng về thủ tục, thường có 3 lớp việc phải tách rõ: nộp hồ sơ ly hôn/hộ tịch, quyết định và giấy tờ liên quan đến con, và xử lý ngay ảnh hưởng lên cư trú/visa trong 14 ngày nếu thuộc diện phải thông báo.',
    fees: [
      '協議離婚 nộp 離婚届 tại city hall không phải là một thủ tục tòa án tiêu chuẩn, nhưng có thể phát sinh chi phí bản sao, dịch thuật hoặc chứng nhận giấy tờ.',
      'Nếu cần xin 子の氏の変更許可 tại 家庭裁判所, trang Tòa án nêu lệ phí là 800 yên tiền tem mỗi trẻ, cộng bưu phí theo từng tòa.',
      'Thay đổi tên trên giấy tờ cư trú hoặc xử lý hồ sơ cư trú sau ly hôn có thể phát sinh chi phí ảnh, chuyển phát, dịch thuật hoặc hồ sơ phụ trợ.',
    ],
    documentsChecklist: [
      { label: 'Xác định rõ đang là 協議離婚 hay 裁判離婚', required: true },
      { label: 'Giấy tờ nhân thân, thẻ cư trú, hộ chiếu, địa chỉ cư trú hiện tại', required: true },
      { label: 'Nếu có con: thỏa thuận hoặc quyết định về 親権, 養育費, 親子交流', required: false, note: 'Từ 01/04/2026 luật đã thay đổi, cần nhìn kỹ phần quyền của con và quyền của cha mẹ sau ly hôn.' },
      { label: 'Nếu cần đổi họ của con: hồ sơ 子の氏の変更許可', required: false },
      { label: 'Nếu tên hợp pháp của bạn thay đổi: hồ sơ đổi thông tin trên 在留カード trong 14 ngày', required: false },
      { label: 'Nếu đang ở diện spouse/dependent: kế hoạch xử lý visa hoặc tư cách lưu trú sau ly hôn', required: false },
    ],
    commonMistakes: [
      'Nghĩ nộp 離婚届 xong là mọi giấy tờ của con và cư trú sẽ tự chạy theo.',
      'Không hiểu rằng sau ly hôn, visa gắn với quan hệ hôn nhân có thể bị ảnh hưởng rất lớn.',
      'Quên thông báo cho ISA trong 14 ngày nếu thuộc diện phải báo ly hôn hoặc tử biệt với vợ/chồng.',
      'Tưởng con sống với mẹ là tự động đổi họ/move hộ tịch theo mẹ mà không cần thủ tục riêng.',
      'Nhầm giữa quyền nuôi con thực tế, 親権, 養育費, 面会交流 và giấy tờ cư trú.',
      'Không cập nhật tên/địa chỉ mới cho ngân hàng, bảo hiểm, công ty, trường của con sau khi tình trạng gia đình thay đổi.',
    ],
    faq: [
      {
        question: 'Ly hôn ở Nhật có phải lúc nào cũng ra tòa không?',
        answer: 'Không. 法務省 nêu rõ 協議離婚 có thể nộp 離婚届 tại city hall khi hai bên thỏa thuận được. Riêng 裁判離婚 thì phải nộp theo kết quả bản án, điều đình, hòa giải hoặc quyết định của tòa, và thủ tục nộp có mốc riêng.',
      },
      {
        question: 'Luật mới năm 2026 thay đổi gì lớn về con sau ly hôn?',
        answer: 'Theo 法務省, sửa đổi lớn về nuôi dưỡng con sau ly hôn có hiệu lực từ ngày 01/04/2026. Từ mốc này, sau ly hôn có thể xác định một bên hoặc cả hai bên là người có 親権, thay vì mặc định chỉ một bên như trước đây. Nhưng việc áp dụng luôn phải nhìn theo lợi ích của trẻ và hoàn cảnh từng vụ việc.',
      },
      {
        question: 'Con ở với mẹ thì có tự đổi họ sang mẹ không?',
        answer: 'Không tự động. Trang Tòa án nêu rõ nếu họ của con khác với cha hoặc mẹ sau ly hôn, muốn đổi theo họ của cha hoặc mẹ thì phải xin 子の氏の変更許可 tại 家庭裁判所 rồi mới làm tiếp thủ tục hộ tịch liên quan.',
      },
      {
        question: 'Tôi đang ở visa spouse hoặc dependent, ly hôn xong có sao không?',
        answer: 'Có thể ảnh hưởng rất lớn. ISA yêu cầu một số diện như 家族滞在, 日本人の配偶者等, 永住者の配偶者等 phải thông báo ly hôn hoặc tử biệt với vợ/chồng trong vòng 14 ngày. Việc có tiếp tục ở Nhật được hay không là câu chuyện khác với việc chỉ nộp thông báo; nhiều trường hợp cần đổi sang tư cách lưu trú khác càng sớm càng tốt.',
      },
      {
        question: 'Nếu sau ly hôn tên hợp pháp của tôi đổi thì có phải đổi trên thẻ cư trú không?',
        answer: 'Có. ISA nêu rõ khi họ tên, ngày sinh, giới tính hoặc quốc tịch/vùng lãnh thổ thay đổi thì trung dài hạn cư trú phải nộp thay đổi thông tin ngoài địa chỉ trên 在留カード trong vòng 14 ngày.',
      },
    ],
    counterPhrases: [
      {
        jp: '離婚届を出したいのですが、必要な書類を教えてください。',
        romaji: 'Rikon todoke o dashitai no desu ga, hitsuyou na shorui o oshiete kudasai.',
        vn: 'Tôi muốn nộp 離婚届, cho tôi biết giấy tờ cần thiết.',
        note: 'Câu mở đầu tại quầy 戸籍課 trong 市役所.',
      },
      {
        jp: '弁護士に相談したいです。法テラスを紹介してください。',
        romaji: 'Bengoshi ni soudan shitai desu. Houterasu o shoukai shite kudasai.',
        vn: 'Tôi muốn tham vấn luật sư. Xin giới thiệu 法テラス.',
        note: 'Hotline 0570-078374 cho người thu nhập thấp. Quan trọng nhất khi có tranh chấp con / visa / DV.',
      },
      {
        jp: '配偶者ビザですが、離婚後の在留資格について教えてください。',
        romaji: 'Haiguusha biza desu ga, rikon-go no zairyuu shikaku ni tsuite oshiete kudasai.',
        vn: 'Tôi đang ở visa vợ/chồng, cho tôi biết về tư cách lưu trú sau ly hôn.',
        note: 'Hỏi Nyukan hoặc 行政書士 chuyên 入管 — có thể chuyển sang 定住者 nếu có con Nhật + nuôi dưỡng thực tế.',
      },
      {
        jp: '子の氏の変更許可を申し立てたいです。',
        romaji: 'Ko no shi no henkou kyoka o moushitatetai desu.',
        vn: 'Tôi muốn nộp đơn xin đổi họ cho con.',
        note: 'Tại 家庭裁判所. Phí ¥800 tem/trẻ. Sau khi tòa duyệt mới làm tiếp thủ tục 戸籍 tại 市役所.',
      },
      {
        jp: '家庭内暴力の相談をしたいです。',
        romaji: 'Kateinai bouryoku no soudan o shitai desu.',
        vn: 'Tôi muốn tư vấn về bạo lực gia đình.',
        note: 'Hotline 配偶者暴力相談支援センター 0570-0-55210 (24/7, có thông dịch). 警察 #9110 cho stalking / threats. KHÔNG gọi từ điện thoại bị theo dõi — dùng điện thoại an toàn hoặc shelter.',
      },
    ],
    keyTerms: [
      {
        term: '協議離婚',
        reading: 'きょうぎりこん',
        meaningVi: 'ly hôn theo thoả thuận (không qua tòa)',
        noteVi: 'Hai bên đồng ý → ký 離婚届 + 2 nhân chứng → nộp 市役所. Đa số ly hôn ở Nhật theo cách này (~88%). KHÔNG cần ra tòa nhưng các vấn đề con / tài sản / 養育費 nên đưa vào 公正証書 (giấy công chứng) để có hiệu lực thực thi. Người nước ngoài: cũng có thể dùng 協議離婚 nếu luật nước quốc tịch chấp nhận.',
      },
      {
        term: '裁判離婚',
        reading: 'さいばんりこん',
        meaningVi: 'ly hôn theo phán quyết tòa (khi không thoả thuận được)',
        noteVi: 'Quy trình: 調停 (mediation) tại 家庭裁判所 trước → nếu không thoả thuận được → 訴訟 (kiện). Lý do được chấp nhận theo 民法 §770: ngoại tình, bỏ nhà ác ý, mất tích 3+ năm, mất khả năng tinh thần, hoặc lý do nghiêm trọng khác. Cần 弁護士. Nộp 離婚届 trong 10 ngày sau phán quyết.',
      },
      {
        term: '親権',
        reading: 'しんけん',
        meaningVi: 'quyền nuôi dưỡng + đại diện pháp lý cho con',
        noteVi: 'Bao gồm: quyết định nơi ở, học tập, y tế, ký hợp đồng cho con. TRƯỚC 01/04/2026: sau ly hôn CHỈ 1 bên có 親権. TỪ 01/04/2026: có thể 単独親権 (1 bên) HOẶC 共同親権 (cả 2 bên) tuỳ thoả thuận hoặc quyết định tòa, dựa trên lợi ích trẻ. Tranh chấp → 家庭裁判所 xét. Người mang 親権 thường nhưng KHÔNG luôn là người sống cùng con.',
      },
      {
        term: '共同親権',
        reading: 'きょうどうしんけん',
        meaningVi: 'cùng giữ 親権 sau ly hôn (mới từ 01/04/2026)',
        noteVi: 'Sửa đổi 民法 mới. Áp dụng khi 2 cha mẹ thoả thuận hoặc tòa quyết định lợi ích trẻ. Quyết định lớn (chuyển trường, phẫu thuật, đổi nơi ở dài hạn) cần đồng ý CẢ 2 bên. Quyết định hàng ngày người chăm trực tiếp tự quyết. Không áp dụng nếu có DV / nguy cơ cho trẻ — tòa giữ 単独親権 cho bên an toàn.',
      },
      {
        term: '養育費',
        reading: 'よういくひ',
        meaningVi: 'tiền nuôi dưỡng con (do bên không sống cùng trả)',
        noteVi: 'Bên không sống cùng con trả cho bên nuôi trực tiếp. Mức theo bảng 養育費算定表 của 家庭裁判所 dựa trên thu nhập cả 2 bên + tuổi con. Để bảo đảm thực thi: ghi vào 公正証書 hoặc 調停調書 — KHÔNG ghi giấy thường = khó kiện. Không trả: bên nhận có thể yêu cầu 差押 (siết tài sản) qua tòa.',
      },
      {
        term: '面会交流',
        reading: 'めんかいこうりゅう',
        meaningVi: 'quyền gặp con (cho bên không sống cùng)',
        noteVi: 'Quyền của trẻ chứ KHÔNG chỉ quyền của cha mẹ. Tần suất + cách thức do 2 bên thoả thuận hoặc tòa quyết. Đặc biệt quan trọng với cha mẹ người nước ngoài bị giữ con ở Nhật — có thể nộp 面会交流調停 tại 家庭裁判所. Trường hợp DV: tòa có thể giới hạn / cấm để bảo vệ trẻ.',
      },
      {
        term: '子の氏の変更許可',
        reading: 'このうじのへんこうきょか',
        meaningVi: 'phép đổi họ của con (qua 家庭裁判所)',
        noteVi: 'Sau ly hôn, con tự động giữ họ cũ. Muốn đổi sang họ cha hoặc mẹ khác → nộp 申立書 tại 家庭裁判所. Phí ¥800 tem/trẻ + bưu phí. Sau khi tòa duyệt → đem 審判書 tới 市役所 cập nhật 戸籍. KHÔNG tự động — nhiều người nhầm "con sống với mẹ tự đổi họ mẹ".',
      },
      {
        term: '配偶者ビザ ly hôn',
        reading: 'はいぐうしゃビザ りこん',
        meaningVi: 'tư cách lưu trú gắn hôn nhân khi ly hôn',
        noteVi: 'Diện 家族滞在 / 日本人の配偶者等 / 永住者の配偶者等 — phải báo ISA trong 14 ngày khi ly hôn (入管法 §19-16). KHÔNG tự động bị thu hồi nhưng phải chuyển sang diện phù hợp. Có thể: (a) đổi sang 定住者 nếu có con Nhật + nuôi dưỡng thực tế; (b) đổi sang work visa nếu có job offer phù hợp; (c) đổi sang 留学 nếu vào trường. Tham vấn 行政書士 chuyên 入管 SỚM.',
      },
    ],
    officialLinks: [
      { label: '離婚届 — 法務省', url: 'https://www.moj.go.jp/ONLINE/FAMILYREGISTER/5-3.html' },
      { label: '離婚を考えている方へ — 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00011.html' },
      { label: '親権者 — 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00015.html' },
      { label: '子どもに関する事項（子育ての計画）— 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00014.html' },
      { label: '養育費 — 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00016' },
      { label: '親子交流（面会交流）— 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00017.html' },
      { label: '民法等の一部を改正する法律〔令和8年4月1日施行〕— 法務省', url: 'https://www.moj.go.jp/MINJI/minji07_00357.html' },
      { label: '子の氏の変更許可 — 裁判所', url: 'https://www.courts.go.jp/saiban/syurui/syurui_kazi/kazi_06_07/index.html' },
      { label: '配偶者に関する届出 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00016.html' },
      { label: '住居地以外の在留カード記載事項の変更届出 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00009.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Tách 4 chuyện khác nhau: ly hôn, con, tên, cư trú',
        description: 'Ngay từ đầu hãy tách riêng bốn câu hỏi: làm sao nộp ly hôn, con sẽ ở với ai và ai có quyền gì, ai cần đổi tên/họ trên giấy tờ, và cư trú/visa có bị ảnh hưởng không. Nếu trộn bốn việc này thành một, bạn rất dễ bỏ sót mốc 14 ngày của ISA hoặc thủ tục của con ở 家庭裁判所.',
        documents: [
          'Tình trạng hôn nhân hiện tại',
          'Có con chung hay không',
          'Tư cách lưu trú hiện tại của mỗi người',
        ],
        tip: 'Đây không phải lúc “giải quyết dần cũng được”. Một số mốc là mốc pháp lý rất ngắn.',
      },
      {
        step: 2,
        title: 'Nộp 離婚届 đúng loại',
        description: 'Pháp務省 nêu rõ 協議離婚 có thể nộp bất kỳ lúc nào tại city hall theo nơi có hộ tịch gốc hoặc nơi đang ở; còn 裁判離婚 phải nộp trong vòng 10 ngày kể từ ngày phán quyết hoặc quyết định có hiệu lực. Nếu là người nước ngoài, song song với giấy tờ Nhật còn có thể phải xem yêu cầu của nước mang quốc tịch của mình.',
        documents: [
          'Mẫu 離婚届',
          'Giấy tờ tùy thân',
          'Tài liệu của tòa nếu là 裁判離婚',
        ],
        tip: 'Ly hôn có hiệu lực trong hộ tịch không có nghĩa là cư trú của người nước ngoài đã tự ổn. Hai lớp thủ tục này khác nhau.',
        image: require('../../../../../assets/content/daily-life/ag_divorce_s2.jpg'),
        imageCaption: 'Điền 離婚届 tại municipal office — cần chữ ký 2 người và 2 nhân chứng',
      },
      {
        step: 3,
        title: 'Nếu có con: chốt 親権, 養育費, 親子交流',
        description: 'Pháp務省 nhấn mạnh khi có con thì cha mẹ cần chốt ít nhất ba nhóm việc: ai có 親権, ai trả 養育費 và kế hoạch 親子交流. Từ ngày 01/04/2026, luật đã thay đổi để cho phép sau ly hôn có thể là một bên hoặc cả hai bên có 親権, nhưng tiêu chí cốt lõi vẫn là lợi ích của trẻ.',
        documents: [
          'Thỏa thuận hoặc tài liệu từ tòa về con',
          'Kế hoạch chăm sóc và nơi ở của con',
          'Thông tin thu nhập và chi phí nuôi con nếu bàn về 養育費',
        ],
        tip: 'Đừng xem đây là phần “nói miệng sau”. Càng ít giấy trắng mực đen, rủi ro tranh chấp về sau càng lớn.',
      },
      {
        step: 4,
        title: 'Nếu con cần theo họ của cha hoặc mẹ: làm thủ tục riêng',
        description: 'Trang Tòa án nêu rõ khi con có họ khác với cha hoặc mẹ sau ly hôn, muốn đổi theo họ của cha hoặc mẹ thì phải xin 子の氏の変更許可 ở 家庭裁判所. Sau 01/04/2026, nếu con dưới 15 tuổi và là trường hợp共同親権 thì nguyên tắc còn phải chú ý việc cha mẹ cùng đứng tên hoặc người có quyền hành xử cụ thể theo quyết định của tòa.',
        documents: [
          '戸籍謄本 của con',
          '戸籍謄本 của cha và mẹ có ghi việc ly hôn',
          'Giấy tờ từ tòa nếu có chỉ định người thực hiện quyền',
        ],
        tip: 'Con sống với mẹ không tự động đồng nghĩa con đã mang họ mẹ. Đây là chỗ rất nhiều người hiểu nhầm.',
      },
      {
        step: 5,
        title: 'Xử lý cư trú ngay nếu đang ở diện spouse/dependent',
        description: 'ISA nêu rõ người có một số tư cách như 家族滞在, 日本人の配偶者等, 永住者の配偶者等 phải thông báo ly hôn hoặc tử biệt với vợ/chồng trong vòng 14 ngày. Sau đó, nếu tư cách lưu trú đang dựa vào hôn nhân hoặc phụ thuộc, cần đánh giá rất sớm xem có phải đổi sang diện khác hay không.',
        documents: [
          'Thẻ cư trú',
          'Thông tin ngày ly hôn',
          'Kế hoạch cư trú tiếp theo nếu đang ở diện gắn với hôn nhân',
        ],
        tip: 'Nộp thông báo 14 ngày không phải là “gia hạn” quyền ở lại. Đó chỉ là nghĩa vụ báo tin; phần cư trú tiếp theo phải xử lý riêng.',
        image: require('../../../../../assets/content/daily-life/ag_divorce_s5.jpg'),
        imageCaption: 'Nộp hồ sơ đổi tư cách lưu trú tại ISA sau khi không còn diện 家族滞在',
      },
      {
        step: 6,
        title: 'Nếu tên hoặc địa chỉ đổi: cập nhật tất cả giấy tờ nối theo',
        description: 'Nếu sau ly hôn tên hợp pháp của bạn đổi, hoặc bạn chuyển nhà cùng con, đừng chỉ đổi ở một nơi. ISA yêu cầu đổi thông tin ngoài địa chỉ trên 在留カード trong 14 ngày khi tên hợp pháp thay đổi; ngoài ra còn phải cập nhật địa chỉ, ngân hàng, bảo hiểm, công ty, trường của con và nơi nhận trợ cấp.',
        documents: [
          'Giấy tờ chứng minh tên mới hoặc thay đổi hộ tịch',
          '在留カード',
          'Danh sách nơi cần cập nhật thông tin',
        ],
        tip: 'Sau ly hôn, lỗi vận hành thường gặp nhất không nằm ở luật mà ở giấy tờ không đồng bộ giữa city hall, ISA, ngân hàng và trường của con.',
      },
    ],
  };

export default divorceCustodyNameResidence;
