import type { AdminGuide } from '../../../../types/content';

const driversLicense: AdminGuide = {
    id: 'drivers-license',
    category: 'license',
    lastVerified: '2026-05-07',
    priority: 'normal',
    title: 'Đổi bằng lái xe',
    titleJp: '外国免許切替（外免切替）',
    icon: 'car',
    color: '#E74C3C',
    searchKeywords: [
      'doi bang',
      'doi bang lai',
      'bang lai viet nam',
      'gaimen',
      'gaiten',
      'JAF',
      'dich bang',
      'foreign license conversion',
      '外免切替',
      '外国免許切替',
      '運転免許センター',
    ],
    description: 'Đổi bằng lái xe Việt Nam sang bằng lái Nhật tại Trung tâm cấp phép lái xe. Từ 01/10/2025, giấy tờ địa chỉ và phần kiểm tra kiến thức/kỹ năng đã bị siết chặt; quy định và lịch hẹn vẫn khác nhau theo tỉnh/thành.',
    legalScope: {
      appliesFrom: '2025-10-01',
      jurisdiction: 'mixed',
      jurisdictionNote: 'Sửa đổi thủ tục là toàn quốc, nhưng lịch hẹn, cách nộp và hướng dẫn chi tiết do từng trung tâm cấp phép lái xe/tỉnh thành công bố.',
      sourceVerifiedAt: '2026-05-07',
      nextReviewAt: '2026-10-01',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Bạn không có đủ hộ chiếu cũ/dấu xuất nhập cảnh để chứng minh 3 tháng sau ngày cấp bằng.',
        'Bạn không thuộc 住民基本台帳 hoặc giấy tờ địa chỉ không giống hướng dẫn của trung tâm.',
        'Bạn từng bị từ chối hồ sơ hoặc có bằng lái đã hết hạn/đổi nhiều lần.',
      ],
    },
    quickAction: {
      deadline: 'Không có hạn chung, nhưng nên làm trước khi bằng Việt Nam hết hạn và trước khi cần lái xe tại Nhật.',
      office: '運転免許センター hoặc trung tâm cấp phép lái xe nơi bạn cư trú theo 住民票.',
      doNow: [
        'Kiểm tra trang police/driver license center của tỉnh đang sống, không dùng mỗi kinh nghiệm Tokyo.',
        'Xin bản dịch bằng lái qua JAF hoặc cơ quan được chấp nhận.',
        'Rà hộ chiếu cũ/mới để chứng minh đã ở Việt Nam đủ 3 tháng sau ngày cấp bằng.',
      ],
      bring: ['Bằng lái Việt Nam bản gốc', 'Bản dịch tiếng Nhật', 'Hộ chiếu cũ/mới', '住民票 theo yêu cầu mới', 'Thẻ cư trú', 'Ảnh thẻ'],
      ifLate: 'Nếu bằng Việt Nam hết hạn hoặc không chứng minh được điều kiện, hỏi trung tâm trước khi đặt lịch vì có thể không đủ điều kiện 外免切替.',
      officialSourceLabels: ['外国の運転免許をお持ちの方 — 警察庁', 'Trung tâm cấp phép Tokyo — 警視庁', '改正道路交通法施行規則 2025-10-01 — 警視庁', 'Dịch bằng lái — JAF'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_drivers-license_hero.jpg'),
    heroImageCaption: '運転免許証 — bằng lái xe Nhật Bản, đổi từ bằng nước ngoài qua thủ tục 外免切替',
    whoIsThisFor: [
      'Người có bằng lái Việt Nam còn hiệu lực và đang cư trú tại Nhật.',
      'Người cần lái xe đi làm, sinh hoạt hoặc chuẩn bị mua/thuê xe tại Nhật.',
      'Người muốn đổi bằng qua 外免切替 thay vì học lái lại từ đầu tại Nhật.',
    ],
    whenToDo: [
      'Khi có đủ giấy tờ chứng minh đã ở Việt Nam tổng cộng ít nhất 3 tháng sau ngày được cấp bằng.',
      'Trước khi bằng Việt Nam hết hạn hoặc trước khi cần lái xe tại Nhật.',
      'Sau khi có địa chỉ cư trú ổn định vì thường nộp tại trung tâm cấp phép của tỉnh/thành nơi ở.',
    ],
    whereToDo: [
      '運転免許センター hoặc trung tâm cấp phép lái xe của tỉnh/thành nơi bạn cư trú.',
      'JAF hoặc cơ quan được chấp nhận để lấy bản dịch tiếng Nhật của bằng lái.',
    ],
    estimatedTime: 'Có thể mất nhiều buổi vì cần đặt lịch, kiểm tra hồ sơ, kiểm tra kiến thức và kỹ năng lái. Lịch hẹn tùy tỉnh/thành.',
    fees: [
      'Phí dịch bằng, phí nộp hồ sơ, phí thi/kiểm tra và phí cấp bằng phụ thuộc cơ quan/tỉnh/thành.',
      'JAF công bố phí dịch riêng; hãy kiểm tra trang chính thức trước khi nộp vì phí có thể thay đổi.',
    ],
    documentsChecklist: [
      { label: 'Bằng lái Việt Nam bản gốc còn hiệu lực', required: true },
      { label: 'Bản dịch tiếng Nhật của bằng lái', required: true, note: 'Do JAF hoặc cơ quan được chấp nhận cấp.' },
      { label: 'Hộ chiếu cũ/mới', required: true, note: 'Dùng để chứng minh thời gian ở Việt Nam sau khi được cấp bằng.' },
      { label: '住民票', required: true, note: 'Lấy tại municipal office, thường cần bản không ghi My Number.' },
      { label: 'Thẻ cư trú', required: true },
      { label: 'Ảnh thẻ đúng kích thước', required: true },
    ],
    commonMistakes: [
      'Không chứng minh được đã ở Việt Nam đủ 3 tháng sau khi được cấp bằng.',
      'Dùng bản dịch không được trung tâm chấp nhận.',
      'Thiếu hộ chiếu cũ có dấu xuất nhập cảnh.',
      'Áp dụng thông tin của Tokyo cho tỉnh/thành khác.',
      'Dùng kinh nghiệm cũ trước 01/10/2025: Tokyo đã đổi yêu cầu 住民票/giấy tờ địa chỉ và bài kiến thức từ 10 câu sang 50 câu.',
      'Tập lái theo thói quen Việt Nam mà không luyện sa hình/quy tắc Nhật trước khi thi kỹ năng.',
    ],
    faq: [
      {
        question: 'Bằng Việt Nam có được miễn thi lái không?',
        answer: 'Người có bằng Việt Nam thường vẫn cần kiểm tra kiến thức và kỹ năng lái khi đổi bằng. Điều kiện cụ thể do trung tâm cấp phép xác nhận.',
      },
      {
        question: 'Không có hộ chiếu cũ thì sao?',
        answer: 'Có thể khó chứng minh thời gian ở Việt Nam sau ngày cấp bằng. Hãy hỏi trung tâm cấp phép xem họ chấp nhận giấy tờ thay thế nào.',
      },
      {
        question: 'Có thể nộp ở tỉnh khác nơi đang sống không?',
        answer: 'Thông thường nộp tại trung tâm cấp phép nơi bạn cư trú theo 住民票. Hãy kiểm tra với trung tâm trước khi đặt lịch.',
      },
    ],
    officialLinks: [
      { label: '外国の運転免許をお持ちの方 — 警察庁', url: 'https://www.npa.go.jp/policies/application/license_renewal/have_DL_issed_another_country.html' },
      { label: 'Trung tâm cấp phép Tokyo — 警視庁', url: 'https://www.keishicho.metro.tokyo.lg.jp/menkyo/menkyo/kokugai/kokugai05.html' },
      { label: '改正道路交通法施行規則 2025-10-01 — 警視庁', url: 'https://www.keishicho.metro.tokyo.lg.jp/menkyo/oshirase/low.html' },
      { label: 'Dịch bằng lái — JAF', url: 'https://english.jaf.or.jp/driving-in-japan/drive-in-japan/switch-to-japanese-license' },
      { label: 'Cách xin bản dịch — JAF', url: 'https://english.jaf.or.jp/driving-in-japan/drive-in-japan/about-dltas' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra điều kiện & chuẩn bị',
        description: 'Điều kiện cơ bản: bằng lái nước ngoài còn hiệu lực, chứng minh đã ở quốc gia cấp bằng tổng cộng ít nhất 3 tháng sau khi được cấp bằng, và có địa chỉ cư trú/địa chỉ tạm trú được trung tâm chấp nhận. Người có bằng Việt Nam thường cần kiểm tra kiến thức và kỹ năng lái.',
        documents: [],
        tip: 'Từ 01/10/2025, Tokyo yêu cầu giấy tờ địa chỉ chặt hơn: người thuộc 住民基本台帳 cần 住民票 có các mục đặc định; người không thuộc diện này cần giấy tờ thân phận/địa chỉ theo hướng dẫn.',
      },
      {
        step: 2,
        title: 'Lấy bản dịch bằng lái & giấy tờ',
        description: 'Cần bản dịch tiếng Nhật của bằng lái do cơ quan được chấp nhận như JAF hoặc đại sứ quán/lãnh sự quán. JAF đã chuyển sang đăng ký dịch online; từ 01/04/2026 phí dịch là 6,000 yên/bản.',
        documents: [
          'Bằng lái xe Việt Nam — bản gốc',
          'Bản dịch tiếng Nhật của bằng lái — do ĐSQ Việt Nam hoặc JAF cấp',
          'Hộ chiếu — bản gốc, phải có dấu xuất nhập cảnh chứng minh 3 tháng ở VN sau khi lấy bằng',
          '住民票 — lấy tại UBND, trong vòng 6 tháng',
          'Ảnh thẻ 3.0×2.4cm — chụp trong 6 tháng gần đây',
          'Thẻ cư trú hoặc giấy tờ xác minh danh tính theo yêu cầu của trung tâm',
        ],
        tip: 'JAF không còn nhận hồ sơ dịch tại quầy/bưu điện từ 31/03/2025; hãy dùng online application.',
        image: require('../../../../../assets/content/daily-life/ag_drivers-license_s2.jpg'),
        imageCaption: 'JAF — cơ quan dịch bằng lái xe được chấp nhận khi làm thủ tục 外免切替',
      },
      {
        step: 3,
        title: 'Đặt lịch hẹn tại Trung tâm cấp phép lái xe',
        description: 'Gọi điện hoặc đặt lịch theo hướng dẫn của 運転免許センター tại tỉnh/thành nơi cư trú. Một số nơi chỉ nhận hồ sơ theo lịch hẹn.',
        documents: [],
        tip: 'Không tự áp dụng giờ tiếp nhận của Tokyo cho tỉnh khác. Mỗi trung tâm có lịch và cách đặt hẹn riêng.',
      },
      {
        step: 4,
        title: 'Nộp hồ sơ, thi kiến thức & thi lái xe',
        description: 'Đến trung tâm theo lịch hẹn để kiểm tra hồ sơ, xác nhận quá trình lấy bằng, kiểm tra thị lực/thính lực, làm bài kiểm tra kiến thức và kiểm tra kỹ năng lái nếu thuộc diện phải kiểm tra. Theo trang Tokyo về sửa đổi 01/10/2025, phần kiến thức chuyển từ 10 câu sang 50 câu và cần đạt 45/50; phần kỹ năng cũng bổ sung/siết tiêu chí như xử lý qua vạch người đi bộ.',
        documents: [],
        tip: 'Phí, số câu hỏi, ngôn ngữ hỗ trợ và nội dung kiểm tra có thể thay đổi theo thời điểm và tỉnh/thành. Xác nhận trực tiếp với trung tâm trước ngày thi.',
        image: require('../../../../../assets/content/daily-life/ag_drivers-license_s4.jpg'),
        imageCaption: '運転免許センター — trung tâm cấp phép lái xe, nơi thi kiến thức và kỹ năng lái 外免切替',
      },
    ],
  };

export default driversLicense;
