import type { AdminGuide } from '../../../../types/content';

const employmentCrisisVisaJobLossLayoff: AdminGuide = {
    id: 'employment-crisis-visa-job-loss-layoff',
    category: 'immigration',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Bị đuổi việc / công ty phá sản — visa sẽ thế nào?',
    titleJp: '解雇・会社倒産と就労ビザの対応',
    icon: 'alert-circle',
    color: '#E74C3C',
    description: 'Quyền và nghĩa vụ visa khi bị đuổi việc hoặc công ty phá sản. KHÔNG có "thời gian đệm tự động" — luật 入管法 §19-16-2 BẮT BUỘC báo Nyukan trong 14 ngày khi hợp đồng kết thúc. Có thể xin 特定活動 (job-search) 6 tháng nhưng Nyukan đánh giá TỪNG CASE, không tự động duyệt. Cần phân biệt rõ 会社都合 (công ty đuổi) vs 自己都合 (tự thôi) — ảnh hưởng quyền lợi visa + bảo hiểm thất nghiệp.',
    searchKeywords: [
      'bi duoi viec',
      'bi sa thai',
      'cong ty pha san',
      'cong ty dong cua',
      'mat viec o nhat',
      'thoi viec visa',
      'kaiko visa',
      'kaisha tousan',
      'tokutei katsudo job seeking',
      'visa tim viec sau sa thai',
      'visa 6 thang tim viec',
      'job-seeking status',
      'hello work',
      'haroo waaku',
      'bao hiem that nghiep nhat',
      'unemployment insurance japan',
      'koyou hoken',
      'rishokuhyou',
      '14 ngay bao Nyukan',
      'keiyaku kikan henkou',
      '会社都合',
      '自己都合',
      '解雇',
      'かいこ',
      '解雇予告通知書',
      '雇用終了証明書',
      '倒産',
      'とうさん',
      '特定活動',
      '求職活動',
      '離職票',
      '雇用保険',
      'ハローワーク',
      '契約機関に関する届出',
      '整理解雇',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Khi work visa holder bị mất hợp đồng (sa thải / công ty phá sản / hết hợp đồng) → bắt buộc nộp 契約機関に関する届出 cho 出入国在留管理庁 trong 14 ngày theo 入管法 §19-16-2. Không báo = vi phạm + ảnh hưởng tư cách lưu trú. 特定活動 (求職活動) là tư cách Bộ Tư pháp cấp tùy quyết định — KHÔNG phải quyền tự động sau sa thải; Nyukan đánh giá từng case dựa trên: lý do sa thải (会社都合 / 自己都合), nỗ lực tìm việc, tài chính, lịch sử lưu trú. Bảo hiểm thất nghiệp (雇用保険) do 厚生労働省 / ハローワーク xử lý — KHÁC tư cách lưu trú, là hai cơ quan riêng biệt.',
      sourceVerifiedAt: '2026-05-17',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Công ty muốn ghi "tự xin thôi" (自己都合) thay vì "công ty đuổi" (会社都合) — đây là sự lệch lạc có thể ảnh hưởng quyền lợi của bạn. Tham vấn 労働基準監督署 hoặc luật sư lao động.',
        'Bị 整理解雇 (sa thải kinh tế) nhưng nghi ngờ 4 điều kiện luật định không thoả mãn (lý do kinh tế, nỗ lực giảm thiểu, lựa chọn người sa thải hợp lý, quy trình thông báo) → 労働基準監督署 hoặc luật sư.',
        'Đã quá 14 ngày chưa báo Nyukan về kết thúc hợp đồng → đến Nyukan giải trình ngay, kèm tài liệu lý do (bệnh, không nhận thông báo, etc.) — KHÔNG đợi.',
        'Visa hiện tại sắp hết hạn (<1 tháng) cùng lúc bị sa thải → cần xử lý song song 在留期間更新 + 特定活動 → 行政書士 chuyên 入管.',
        'Công ty không cấp 解雇予告通知書 hoặc 雇用終了証明書 → 労働基準監督署 (cấp huyện) bắt buộc công ty phải cấp theo 労働基準法 §22.',
        'Đang trong 特定活動 (job-search) gần hết 6 tháng + chưa có offer → cân nhắc đổi tư cách khác (留学, 配偶者, 家族滞在) hoặc chuẩn bị rời Nhật. Tham vấn 行政書士.',
      ],
    },
    quickAction: {
      deadline: 'NỘP 契約機関に関する届出 trong 14 ngày từ ngày kết thúc hợp đồng (入管法 §19-16-2). Xin 特定活動 (job-search) càng sớm càng tốt — Nyukan không tự cấp, phải nộp đơn. ハローワーク: đăng ký thất nghiệp NGAY trong tuần đầu để được tính 失業手当 sớm (nếu có 雇用保険 ≥12 tháng).',
      office: 'Nyukan có thẩm quyền theo nơi cư trú (cho 特定活動 + 契約機関 届出). ハローワーク gần nhà (cho 失業手当 + tìm việc). 労働基準監督署 cấp huyện (cho tranh chấp lao động). Số tư vấn 出入国在留管理庁: 0570-013904.',
      doNow: [
        'Yêu cầu công ty cấp 解雇予告通知書 (thông báo sa thải, 30 ngày trước theo 労働基準法 §20) HOẶC 解雇予告手当 (1 tháng lương thay thế).',
        'Sau ngày cuối làm việc: xin 雇用終了証明書 ghi rõ "会社都合" (NẾU bị sa thải) — KHÔNG ký bất kỳ giấy nào ghi "自己都合" nếu thực tế là bị đuổi.',
        'Nộp 契約機関に関する届出 cho Nyukan trong 14 ngày: online qua e-Gov hoặc trực tiếp tại Nyukan. Miễn phí.',
        'Đến ハローワーク đăng ký thất nghiệp + xin 離職票 (do công ty cấp + bạn nộp HW) → kích hoạt 失業手当 nếu đủ điều kiện (雇用保険 ≥12 tháng).',
        'Quyết định: nếu cần ở lại tìm việc → nộp 在留資格変更許可申請 sang 特定活動 (求職活動). Cần 解雇 evidence + 履歴書 + 求職活動計画書.',
        'Nếu đang có offer mới → chuyển thẳng sang 在留資格変更 (cùng tư cách hoặc khác). KHÔNG cần qua 特定活動.',
      ],
      bring: [
        'Hộ chiếu + 在留カード',
        '解雇予告通知書 (thông báo sa thải)',
        '雇用終了証明書 ghi rõ 会社都合',
        '離職票 (Hello Work form 1+2 do công ty cấp)',
        '雇用保険被保険者証 (thẻ bảo hiểm thất nghiệp — nếu có)',
        '履歴書 + 職務経歴書 (CV + lịch sử công việc)',
        '求職活動計画書 (kế hoạch tìm việc) — cho đơn 特定活動',
        'Sao kê ngân hàng (chứng minh tài chính cho 6 tháng tìm việc)',
      ],
      ifLate: 'Quá 14 ngày chưa báo Nyukan = vi phạm 入管法 §19-16-2 — có thể ảnh hưởng đánh giá khi xin 特定活動 hoặc gia hạn visa sau này. Đến Nyukan giải trình NGAY + mang tài liệu y tế / khách quan nếu có. KHÔNG trốn — bị truy ra muộn hơn = hậu quả nặng hơn nhiều. Tham vấn 行政書士 / 弁護士 nếu lo về visa.',
      officialSourceLabels: [
        'ISA — 特定活動 (Job-Seeking Status)',
        '労働基準監督署 — Dispute Mediation',
        '出入国在留管理庁 — 在留資格 inquiry 0570-013904',
      ],
    },
    whoIsThisFor: [
      'Người vừa được thông báo sẽ bị sa thải hoặc công ty phá sản.',
      'Người muốn biết có bao lâu để tìm việc mới trên work visa.',
      'Người muốn hiểu khác biệt giữa \"công ty đuổi\" vs \"tự xin thôi\".',
    ],
    whenToDo: [
      'Ngay khi được thông báo sẽ bị sa thải — liên hệ ISA hoặc 行政書士 để tìm hiểu tùy chọn.',
      'Trước khi ngày cuối cùng làm việc — hỏi công ty xin giấy xác nhận bị sa thải (会社都合による雇用終了証明書).',
      'Trong 14 ngày sau ngày sa thải — nộp đơn xin 特定活動 (job-seeking status) tại ISA.',
      'Nếu không làm gì: khi work visa hết hạn, phải rời Nhật.',
    ],
    whereToDo: [
      'ISA — cục công an nhập cảnh. Nộp đơn xin 特定活動 (job-seeking status).',
      'Công ty: xin giấy xác nhận bị sa thải (xứ sứ công ty hoặc phòng HR).',
      '労働基準監督署 (labor standards bureau) — nếu công ty có vi phạm lao động (wage theft, unsafe conditions).',
    ],
    estimatedTime: '14 ngày để nộp đơn. 1-2 tuần để ISA phê duyệt 特定活動. Thời gian job-seeking: 6 tháng (có thể được gia hạn trong trường hợp đặc biệt).',
    commonMistakes: [
      'Tự xin thôi việc — khi đó không được 特定活動, phải tìm việc trước khi work visa hết.',
      'Quên xin giấy xác nhận bị sa thải từ công ty — ISA sẽ cần để verify.',
      'Quá 14 ngày sau sa thải mới nộp đơn — có thể không được 特定活動 (hạn chế).',
      'Làm black market/part-time mà không xin 資格外活動許可 — không được phép khi trên job-seeking status.',
      'Không tìm việc chủ động — ISA có thể kiểm tra, nếu chẳng làm gì = bị từ chối gia hạn.',
    ],
    faq: [
      {
        question: '特定活動 (job-seeking status) là gì?',
        answer: 'Là visa tạm thời cho những người bị sa thải bởi công ty, cho phép ở Nhật 6 tháng để tìm việc mới. Sau 6 tháng, phải (1) tìm được việc mới (đổi visa), hoặc (2) rời Nhật.',
      },
      {
        question: 'Có lợi gì khi bị sa thải (会社都合) vs tự xin thôi (自己都合)?',
        answer: 'Rất khác. Nếu **bị sa thải (công ty lỗi)**: được 特定活動 6 tháng để tìm việc. Nếu **tự xin thôi**: không được 特定活動, phải tìm việc trước khi work visa hết (thường vài tháng). Vì vậy nên ghi rõ \"bị sa thải\" khi xin đơn từ công ty, không nên tự ý resign.',
      },
      {
        question: 'Công ty tự đóng cửa — tôi có được 特定活動 không?',
        answer: 'Có. Nếu công ty phá sản (倒産) hoặc đóng cửa, bạn được coi là \"bị sa thải do công ty\". Xin giấy xác nhận từ công ty (hoặc từ phòng xử lý tình trạng công ty). ISA sẽ cấp 特定活動 để bạn tìm việc.',
      },
      {
        question: 'Trong 特定活動 6 tháng, tôi có thể làm part-time không?',
        answer: 'Có thể làm part-time (up to 20 hours/week hoặc phụ thuộc ISA hướng dẫn). Tuy nhiên, phải xin 資格外活動許可 riêng nếu part-time là \"business\". Nếu part-time ở cửa hàng = không cần phép riêng, chỉ cần báo ISA.',
      },
      {
        question: 'Nếu tìm được việc mới trong 6 tháng thì sao?',
        answer: 'Khi tìm được công ty mới, nộp đơn xin đổi visa sang work visa mới cùng cách như bình thường (change of status). Công ty mới phải chuẩn bị tài liệu support. Sau khi được phê duyệt, bạn sẽ có work visa mới từ công ty mới.',
      },
      {
        question: 'Nếu 6 tháng rồi vẫn không tìm được việc thì sao?',
        answer: '特定活動 sẽ hết. Bạn phải rời Nhật. Tuy nhiên, có thể xin gia hạn 特定活動 nếu có lý do chính đáng (ví dụ: đang interview, offer sắp tới). ISA sẽ xem xét từng trường hợp.',
      },
    ],
    counterPhrases: [
      {
        jp: '解雇予告通知書をいただけますか。会社都合での雇用終了であることを明記してください。',
        romaji: 'Kaiko yokoku tsuuchisho o itadakemasu ka. Kaisha tsugou de no koyou shuuryou de aru koto o meiki shite kudasai.',
        vn: 'Anh/chị cho tôi 解雇予告通知書 được không? Vui lòng ghi rõ là 会社都合 (do công ty).',
        note: 'Yêu cầu công ty cấp giấy. Nhấn mạnh ghi 会社都合 — ảnh hưởng quyền 特定活動 + 失業手当.',
      },
      {
        jp: '契約機関に関する届出を提出したいです。会社が倒産しました。',
        romaji: 'Keiyaku kikan ni kansuru todokede o teishutsu shitai desu. Kaisha ga tousan shimashita.',
        vn: 'Tôi muốn nộp 契約機関に関する届出. Công ty đã phá sản.',
        note: 'Câu mở đầu tại Nyukan để nộp báo cáo bắt buộc 14 ngày.',
      },
      {
        jp: '特定活動（求職活動）への在留資格変更を希望します。',
        romaji: 'Tokutei katsudou (kyuushoku katsudou) e no zairyuu shikaku henkou o kibou shimasu.',
        vn: 'Tôi muốn đổi tư cách lưu trú sang 特定活動 (tìm việc).',
        note: 'KHÔNG nói "xin 6 tháng" — Nyukan quyết định thời hạn theo case. Để Nyukan tự cấp.',
      },
      {
        jp: '求職活動の計画と最近の応募履歴を持ってきました。',
        romaji: 'Kyuushoku katsudou no keikaku to saikin no oubo rireki o motte kimashita.',
        vn: 'Tôi mang theo kế hoạch tìm việc + lịch sử ứng tuyển gần đây.',
        note: 'Bằng chứng tìm việc thật giúp tăng xác suất Nyukan duyệt. CV + email từ công ty đã ứng tuyển.',
      },
      {
        jp: 'ハローワークの紹介状はどうやって取りますか。離職票も必要ですか。',
        romaji: 'Haroowaaku no shoukaijou wa douyatte torimasu ka. Rishokuhyou mo hitsuyou desu ka.',
        vn: 'Lấy giấy giới thiệu từ Hello Work thế nào? Tôi có cần 離職票 không?',
        note: '離職票 do công ty cấp + bạn nộp Hello Work để kích hoạt 失業手当 (nếu có 雇用保険 ≥12 tháng).',
      },
      {
        jp: '特定活動中にアルバイトはできますか。資格外活動許可は必要ですか。',
        romaji: 'Tokutei katsudou-chuu ni arubaito wa dekimasu ka. Shikakugai katsudou kyoka wa hitsuyou desu ka.',
        vn: 'Trong 特定活動 tôi có thể làm baito không? Có cần xin 資格外活動許可 không?',
        note: 'Trong 特定活動 (求職) thường được phép baito 28h/tuần — nhưng PHẢI xin 資格外活動 riêng, KHÔNG tự động.',
      },
    ],
    keyTerms: [
      {
        term: '契約機関に関する届出',
        reading: 'けいやくきかんにかんするとどけで',
        meaningVi: 'báo cáo bắt buộc về cơ quan hợp đồng (Nyukan)',
        noteVi: 'Theo 入管法 §19-16-2: work visa holder PHẢI báo Nyukan trong 14 ngày khi (1) ký hợp đồng mới, (2) hợp đồng kết thúc, (3) cơ quan hợp đồng thay đổi tên/địa chỉ. KHÔNG báo = vi phạm + ảnh hưởng đánh giá visa sau. Nộp online qua e-Gov hoặc tại Nyukan, miễn phí.',
      },
      {
        term: '会社都合 vs 自己都合',
        reading: 'かいしゃつごう vs じこつごう',
        meaningVi: 'lý do công ty đuổi vs lý do cá nhân tự thôi',
        noteVi: 'Phân biệt CỰC KỲ quan trọng. 会社都合 (sa thải / phá sản / 整理解雇): được 特定活動 + 失業手当 sớm hơn (7 ngày chờ). 自己都合 (tự xin thôi): KHÔNG được 特定活動 + 失業手当 chờ 2-3 tháng. Công ty đôi khi ép ghi 自己都合 để giảm bồi thường — KHÔNG ký nếu thực tế là bị đuổi.',
      },
      {
        term: '解雇予告通知書',
        reading: 'かいこよこくつうちしょ',
        meaningVi: 'thông báo trước về sa thải',
        noteVi: 'Theo 労働基準法 §20: công ty PHẢI thông báo sa thải trước 30 ngày HOẶC trả 解雇予告手当 (1 tháng lương thay thế). Giấy này ghi rõ: ngày kết thúc + lý do (kinh tế / năng lực / vi phạm) + công ty đóng dấu. CẦN cho Nyukan + Hello Work + 失業手当.',
      },
      {
        term: '雇用終了証明書',
        reading: 'こようしゅうりょうしょうめいしょ',
        meaningVi: 'giấy chứng nhận kết thúc lao động',
        noteVi: 'Cấp SAU ngày cuối làm việc (khác 解雇予告通知書 cấp TRƯỚC). Theo 労働基準法 §22: nếu nhân viên yêu cầu, công ty BẮT BUỘC cấp trong 2-3 tuần. Nội dung: ngày làm + ngày nghỉ + lý do (会社都合 / 自己都合). Đây là tài liệu quyết định để Nyukan xét 特定活動.',
      },
      {
        term: '特定活動 (求職活動)',
        reading: 'とくていかつどう (きゅうしょくかつどう)',
        meaningVi: 'visa Hoạt động Đặc định để tìm việc',
        noteVi: 'Tư cách lưu trú đặc biệt cho người mất việc tìm việc mới. Thường 6 tháng, có thể gia hạn 1 lần tổng 1 năm trong điều kiện đặc biệt. Nyukan đánh giá TỪNG CASE — KHÔNG phải quyền tự động. Cần: 会社都合 evidence + bằng chứng tìm việc thật + chứng minh tài chính. Có thể baito 28h/tuần nếu xin 資格外活動 riêng.',
      },
      {
        term: '離職票',
        reading: 'りしょくひょう',
        meaningVi: 'giấy xác nhận thôi việc (cho Hello Work)',
        noteVi: '2 trang: 離職票-1 (do công ty cấp, 10 ngày sau ngày cuối) + 離職票-2 (ghi lương trung bình 6 tháng cuối). Bạn nộp Hello Work để kích hoạt 失業手当. KHÁC 雇用終了証明書 — cái này cho Hello Work, không phải Nyukan. Nếu công ty chậm cấp, Hello Work có thể cấp 仮の離職票 tạm.',
      },
      {
        term: '雇用保険 / 失業手当',
        reading: 'こようほけん / しつぎょうてあて',
        meaningVi: 'bảo hiểm thất nghiệp / trợ cấp thất nghiệp',
        noteVi: 'Đóng tự động qua công ty (0.6% lương). Điều kiện hưởng: đã đóng ≥12 tháng trong 2 năm cuối (≥6 tháng cho 会社都合). Mức: ~50-80% lương cũ. 会社都合: chờ 7 ngày → bắt đầu nhận. 自己都合: chờ 2-3 tháng. Tham khảo guide [[overstaying-illegal-stay-procedures]] để tránh nhầm visa & bảo hiểm xã hội.',
      },
      {
        term: '整理解雇',
        reading: 'せいりかいこ',
        meaningVi: 'sa thải kinh tế (economic layoff)',
        noteVi: 'Theo tiền lệ tư pháp: 4 điều kiện bắt buộc — (1) cần thiết kinh tế thực sự, (2) công ty đã nỗ lực tránh sa thải, (3) lựa chọn người sa thải hợp lý, (4) quy trình thông báo + thảo luận. Nếu công ty không thoả 4 điều kiện = sa thải bất hợp pháp → có thể kiện đòi 復職 / bồi thường. Tham vấn 労働基準監督署 / 弁護士 lao động.',
      },
    ],
    officialLinks: [
      { label: 'ISA — 特定活動 (Job-Seeking Status)', url: 'https://www.moj.go.jp/isa/applications/status/designatedactivities04.html' },
      { label: '労働基準監督署 — Dispute Mediation', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/index.html' },
      { label: '契約機関に関する届出 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00014.html' },
      { label: 'ハローワーク — 失業手当 / 求職', url: 'https://www.hellowork.mhlw.go.jp/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Công ty thông báo sẽ sa thải — hành động ngay',
        description: 'Khi công ty nói \"bạn sẽ bị sa thải\" hoặc \"công ty sắp đóng cửa\":\n\n**Hỏi ngay:**\n- Ngày cuối cùng làm việc khi nào?\n- Tôi có được severance pay không? Bao nhiêu?\n- Tôi có xin giấy xác nhận bị sa thải (解雇予告通知書 hoặc 雇用終了証明書) không?\n\n**Xin giấy chứng minh rõ ràng:**\n- **解雇予告通知書** (announcement letter — nói rõ ngày, lý do)\n- **雇用終了証明書** (employment termination certificate — sau khi có hiệu lực)\n\nGiấy này rất quan trọng — ISA sẽ cần để verify bạn bị sa thải (không phải tự resign).',
        documents: ['Hợp đồng lao động', 'Thông báo sa thải từ công ty'],
        tip: 'Nếu công ty từ chối xin giấy hoặc muốn \"cải thiện\" bằng cách gọi đó là \"voluntary resignation\" — từ chối. Bạn cần giấy ghi rõ \"company-caused\" (会社都合).',
      },
      {
        step: 2,
        title: 'Liên hệ ISA trong vòng 14 ngày sau sa thải',
        description: 'Sau khi bị sa thải, bạn có **14 ngày** để báo ISA và nộp đơn xin 特定活動 (job-seeking status).\n\n**Báo ISA:**\n- Trực tiếp: đến cục công an nhập cảnh nơi cư trú\n- Nói: \"Tôi vừa bị sa thải từ công ty ngày [ngày]. Tôi muốn xin 特定活動 để tìm việc.\"\n- Mang theo: hộ chiếu, thẻ cư trú, giấy xác nhận bị sa thải\n\nISA sẽ giải thích quy trình và cho form xin 特定活動.',
        documents: ['Hộ chiếu', 'Thẻ cư trú', 'Giấy xác nhận bị sa thải từ công ty'],
        tip: 'Đừng trì hoãn — 14 ngày là deadline. Nếu quá hạn, ISA có thể không cấp 特定活動 hoặc hạn chế.',
      },
      {
        step: 3,
        title: 'Nộp đơn xin 特定活動 (Job-Seeking Status)',
        description: '**Chuẩn bị:**\n- **Đơn xin 特定活動** (在留資格変更許可申請 — job-seeking purpose) — in từ ISA website\n- **Hộ chiếu + thẻ cư trú**\n- **Giấy xác nhận bị sa thải từ công ty** (rất quan trọng)\n- **Lý do giải trình** (理由書): \"Công ty [tên] thông báo sẽ sa thải tôi vào [ngày]. Tôi muốn ở lại Nhật 6 tháng để tìm việc mới phù hợp với tư cách lưu trú hiện tại.\"\n- **Bằng chứng tìm việc** (nếu có): CV, offer letter từ công ty khác, hoặc planning letter nói rõ cách tìm việc\n\n**Nộp:**\n- Trực tiếp tại ISA hoặc trực tuyến (nếu áp dụng)\n- Phí: 0 (miễn phí)\n\n**Thời gian phê duyệt:** 1-2 tuần',
        documents: ['Đơn xin 特定活動 (in từ ISA)', 'Hộ chiếu', 'Thẻ cư trú', 'Giấy xác nhận bị sa thải', 'Lý do giải trình', 'CV/planning letter (nếu có)'],
        tip: 'Giấy xác nhận bị sa thải là chìa khóa — nếu không có, ISA có thể không duyệt. Hãy đảm bảo nó rõ ràng ghi \"会社都合\" (company-caused).',
      },
      {
        step: 4,
        title: 'Được phê duyệt 特定活動 — bắt đầu tìm việc',
        description: 'Nếu được phê duyệt:\n\n- Bạn sẽ nhận **thẻ cư trú mới** với status **特定活動** (job-seeking)\n- Ngày hết hạn sẽ là **6 tháng** từ ngày phê duyệt\n- Trên thẻ sẽ ghi: \"Designated Activity - Job Seeking\" hoặc tương tự\n\n**Bây giờ bạn có 6 tháng để:**\n\n✅ **Làm:**\n- Tìm việc (interview, submit CV, network)\n- Làm part-time/temp job (nên xin phép 資格外活動許可 nếu là business)\n- Tham gia job fair, training khóc học để tăng kỹ năng\n- Liên hệ 行政書士 hoặc recruitment agency để hỗ trợ\n\n❌ **Không nên:**\n- Tụt dốc—không làm gì & chỉ chơi\n- Làm black market mà không báo\n- Bỏ cuộc quá sớm\n\n**Nếu tìm được việc:**\n- Công ty mới sẽ chuẩn bị tài liệu untuk change of status\n- Bạn nộp đơn xin change sang work visa (từ 特定活動 → 技術・人文知識・国際業務 hoặc loại khác)\n- Thông thường phê duyệt trong 2-4 tuần',
        documents: ['Thẻ cư trú mới', 'Job offer từ công ty mới'],
        tip: 'Hãy chủ động tìm việc — nếu ISA phát hiện bạn không làm gì trong 6 tháng, gia hạn 特定活動 sẽ khó.',
      },
      {
        step: 5,
        title: 'Nếu không tìm được việc trong 6 tháng',
        description: 'Khi 特定活動 sắp hết (gần deadline 6 tháng):\n\n**Lựa chọn 1: Xin gia hạn 特定活動**\n- Nếu bạn có job offer sắp confirm (2-4 tuần nữa), đang ở vòng interview cuối, hoặc lý do chính đáng khác\n- ISA có thể gia hạn thêm 1-3 tháng\n- Tuy nhiên, tỷ lệ duyệt không cao — ISA muốn chắc bạn thực sự gần xong\n\n**Lựa chọn 2: Chuyển sang visa khác (nếu đủ điều kiện)**\n- Visa du học (nếu có nhập học offer)\n- Spouse visa (nếu kết hôn)\n- Dependent visa (nếu có người Nhật bảo lãnh tài chính)\n- Nông thôn visa (nếu muốn ở lại vùng nông thôn Nhật)\n\n**Lựa chọn 3: Rời Nhật**\n- 特定活動 hết = phải rời\n- Công ty cũ (nếu còn hoạt động) có thể hỗ trợ thủ tục rời (trả lương cuối, hạch toán thuế)\n- Nếu muốn quay lại Nhật sau này, có thể làm visa mới từ Việt Nam',
        documents: ['Giấy xác nhận job offer hoặc interview schedule', 'Hộ chiếu'],
        tip: 'Nếu đang ở tình trạng khó khăn — tìm người bạn/gia đình bảo lãnh hoặc hỏi ngành ngoại giao Việt Nam xem có biện pháp hỗ trợ nào không.',
      },
    ],
  };

export default employmentCrisisVisaJobLossLayoff;
