import type { AdminGuide } from '../../../../types/content';

const freelanceSideJobWorkVisaRules: AdminGuide = {
    id: 'freelance-side-job-work-visa-rules',
    category: 'immigration',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Freelance, side job, YouTube monetize — được không trên work visa?',
    titleJp: 'フリーランス・副業・YouTubeの就労ビザでの可否',
    icon: 'briefcase',
    color: '#F39C12',
    description: 'Quy tắc visa + thuế khi làm freelance / side job / content creator trên work visa. 4 khái niệm tách bạch: 副業 (side job), 業務委託 (contract), 個人事業主 (sole proprietor), 資格外活動 (Nyukan permission). KHÔNG có "freelance = auto OK" — mọi hoạt động ngoài phạm vi 在留資格 chính ĐỀU cần 資格外活動許可 trước, kể cả part-time / arubaito. Tax obligations song song nhưng riêng biệt với visa. Nyukan đánh giá từng case — KHÔNG có "lách bằng freelance".',
    searchKeywords: [
      'freelance o nhat',
      'freelance work visa',
      'side job nhat',
      'side hustle japan',
      'sokugyou',
      'fukugyou',
      'lam them tren visa lao dong',
      'youtube monetize visa',
      'content creator visa',
      'kinh doanh ca nhan nhat',
      'kojin jigyounushi',
      'kaigyou todoke',
      'business owner visa',
      'gyoumu itaku',
      'contract work japan',
      'business consigning',
      'shikakugai katsudou',
      'shikakugai katsudou kyoka',
      'kakutei shinkoku',
      'invoice seido',
      'gensen choushuu',
      'fukugyou kinshi',
      'tax visa mismatch',
      '副業',
      'ふくぎょう',
      '業務委託',
      'ぎょうむいたく',
      '個人事業主',
      'こじんじぎょうぬし',
      '資格外活動',
      '資格外活動許可',
      '開業届',
      'かいぎょうとどけ',
      '確定申告',
      'かくていしんこく',
      'インボイス制度',
      '源泉徴収',
      '副業禁止',
      '20万円ルール',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Hoạt động ngoài phạm vi 在留資格 (work visa chính) BẮT BUỘC phải có 資格外活動許可 từ 出入国在留管理庁 theo 入管法 §19. Áp dụng cho mọi loại: arubaito / part-time / 副業 / 業務委託 / 個人事業 / YouTube monetize / Etsy bán hàng. 在留資格 dạng "技術・人文知識・国際業務" và tương tự CHỈ cho phép hoạt động đúng nội dung visa đó — mọi thứ khác cần phép riêng. Tax obligations là CƠ QUAN RIÊNG (税務署 / 厚生労働省) — KHÁC Nyukan, không liên thông tự động. Có 資格外活動 hợp lệ ≠ tự động OK về thuế; ngược lại đăng ký thuế đầy đủ ≠ tự động OK về visa. Cả hai phải đúng SONG SONG.',
      sourceVerifiedAt: '2026-05-17',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Muốn làm 業務委託 (contract work) cho nhiều client + 開業届 sang 個人事業主 trong khi giữ work visa — Nyukan đánh giá xem có "ngoài phạm vi 在留資格 chính" không. Tham vấn 行政書士 chuyên 入管 + 税理士.',
        'Hợp đồng lao động có điều khoản 副業禁止 (cấm side job) — vi phạm là vấn đề dân sự với công ty (có thể bị sa thải), KHÔNG phải vấn đề visa. Tham vấn 弁護士 lao động nếu lo bị 解雇.',
        'YouTube/blog/Twitch monetize ≥¥10 万円/năm — phải vào 開業届 + 確定申告; ≥¥1 千万円/năm phải đăng ký インボイス制度. Tham vấn 税理士.',
        'Lỡ làm freelance / side job mà CHƯA xin 資格外活動許可 — đến Nyukan tự thú + xin permission ngay. KHÔNG đợi đến lúc gia hạn visa.',
        'Side job income > ¥20 万円/năm + KHÔNG khai 確定申告 — vi phạm luật thuế độc lập với vi phạm visa. Tham vấn 税理士 + 確定申告 hồi tố nếu cần.',
        'Bị Nyukan phát hiện freelance không phép khi xin gia hạn — KHÔNG có "lách". Tham vấn 行政書士 / 弁護士 trước khi đến gặp Nyukan tiếp.',
      ],
    },
    quickAction: {
      deadline: 'Xin 資格外活動許可 TRƯỚC khi bắt đầu hoạt động — KHÔNG sau. Nếu lỡ làm rồi: xin NGAY, ISA không phạt hồi tố nếu chủ động báo nhưng đánh giá có thể bất lợi khi gia hạn. 開業届 (cho 個人事業主): nộp 税務署 trong 1 tháng từ ngày bắt đầu kinh doanh. 確定申告: tháng 2-3 năm sau cho năm trước.',
      office: 'Nyukan có thẩm quyền theo nơi cư trú (cho 資格外活動許可). 税務署 cấp huyện (cho 開業届 + 確定申告). Số tư vấn 出入国在留管理庁: 0570-013904. Tư vấn thuế miễn phí: 国税局電話相談センター hoặc 税理士 (5,000-15,000 yên/buổi).',
      doNow: [
        'Phân loại CHÍNH XÁC hoạt động: arubaito part-time (1 nơi) / 副業 (nhiều nơi) / 業務委託 (contract independent) / 個人事業主 (sole proprietor có 開業届) / YouTube monetize / 投資 thuần. Mỗi loại có quy định khác.',
        'Đọc hợp đồng lao động chính — kiểm điều khoản 副業禁止 hoặc 競業避止 (non-compete). Vi phạm = rủi ro 解雇 (vấn đề dân sự, KHÁC vấn đề visa).',
        'Xin 資格外活動許可 tại Nyukan TRƯỚC khi bắt đầu. Form 様式第28号. Nộp kèm: 在留カード + 業務委託契約書 hoặc mô tả hoạt động + 履歴書 + 申請理由書 (giải trình tại sao + ảnh hưởng đến 本業 không).',
        'Nếu 個人事業主: sau khi có 資格外活動許可 → nộp 開業届 tại 税務署 (trong 1 tháng). Miễn phí. KHÔNG yêu cầu 資格外活動 trước nhưng KHÔNG có ý nghĩa nếu không có phép Nyukan.',
        'Lưu MỌI: 業務委託契約書, 請求書 (invoice), 領収書 (receipt), email với client, chuyển khoản ngân hàng. Cần cho 確定申告 + chứng minh với Nyukan khi gia hạn.',
        'Cuối năm tài chính (12/31): nếu thu nhập side ≥ ¥20 万円/năm → BẮT BUỘC 確定申告 (tháng 2-3 năm sau). Trên ¥1 千万円 → cân nhắc đăng ký インボイス制度.',
      ],
      bring: [
        '在留カード + Hộ chiếu',
        '資格外活動許可申請書 (様式第28号 — download trang Nyukan)',
        '業務委託契約書 / hợp đồng với client (nếu có)',
        'Mô tả hoạt động dự kiến + thời gian + thu nhập ước tính',
        '申請理由書 (lý do giải trình)',
        '在職証明書 + 給与明細 (chứng minh 本業)',
        'Hợp đồng lao động chính (kiểm tra điều khoản 副業禁止)',
      ],
      ifLate: 'Đã làm freelance / side job mà KHÔNG có 資格外活動許可 → đến Nyukan tự thú + xin phép ngay + mang tài liệu chứng minh hoạt động đến nay. ISA thường cấp permission tính từ ngày xin (KHÔNG hồi tố), nhưng có thể đánh giá bất lợi khi gia hạn visa sau. Nếu Nyukan phát hiện trước khi bạn báo = nặng hơn nhiều (từ chối gia hạn, có thể yêu cầu rời Nhật). KHÔNG có "lách" — kết quả tuỳ Nyukan đánh giá.',
      officialSourceLabels: [
        'ISA — 資格外活動許可 (Permission for Activities Outside Status)',
        'ISA — Freelance & Work Visa',
      ],
    },
    whoIsThisFor: [
      'Freelancer/contractor muốn làm việc trên work visa ở Nhật.',
      'Content creator muốn monetize YouTube/Etsy/stream khi trên work visa.',
      'Lao động muốn làm thêm part-time hoặc side hustle ngoài công việc chính.',
      'Người tự hỏi: Tôi có cần 資格外活動許可 không?',
    ],
    whenToDo: [
      'Trước khi bắt đầu freelance/side job — hãy xin 資格外活動許可 (permission for activities outside status) nếu cần.',
      'Nếu không chắc — hỏi ISA hoặc công ty của bạn trước. Hỏi trước luôn an toàn hơn.',
      'Nếu đang làm rồi nhưng chưa xin phép — xin ngay, không bao giờ quá muộn.',
    ],
    whereToDo: [
      'ISA — cục công an nhập cảnh. Nộp đơn xin 資格外活動許可申請.',
      'Trực tiếp hoặc trực tuyến (nếu áp dụng).',
      'Thời gian: ~1-2 tuần để phê duyệt.',
    ],
    estimatedTime: '1-2 tuần để ISA phê duyệt 資格外活動許可. Phí: 0 (miễn phí).',
    commonMistakes: [
      'Làm freelance/side job mà không xin phép — ISA phát hiện có thể từ chối gia hạn visa hoặc có hình phạt.',
      'Không phân biệt được "kinh doanh" (business) và "việc làm thêm part-time" — quy tắc xin phép khác nhau.',
      'Làm YouTube/Etsy mà lấy tiền quảng cáo/bán hàng mà không xin phép — đây là "business" nên cần 資格外活動許可.',
      'Công ty không biết bạn làm side job — có thể vi phạm hợp đồng hoặc chính sách công ty.',
      'Không báo cáo side income với thuế/bảo hiểm — bị phát hiện sẽ có vấn đề pháp lý.',
    ],
    faq: [
      {
        question: '資格外活動許可 là gì?',
        answer: 'Là phép ISA cấp khi bạn muốn làm hoạt động kinh doanh (business/freelance) ngoài phạm vi tư cách visa hiện tại. Nếu không xin phép mà làm = vi phạm pháp luật.',
      },
      {
        question: 'Khi nào cần 資格外活動許可?',
        answer: 'Cần khi: (1) Freelance/contractor nhận từ khách hàng khác (multiple clients), (2) Content creator monetize (YouTube ads, Etsy sales, streaming), (3) Bán hàng online (Amazon, Yahoo Auctions), (4) Kinh doanh cá nhân (個人事業主). Không cần khi: (1) Part-time job với 1 công ty/cửa hàng (có hợp đồng), (2) Gift/hobby không lấy tiền, (3) Hoạt động trong phạm vi tư cách hiện tại.',
      },
      {
        question: 'Tôi xin part-time job phụ — cần 資格外活動許可 không?',
        answer: 'Nếu part-time job ở cửa hàng/công ty nào đó (có hợp đồng) = không cần 資格外活動許可, chỉ cần báo công ty chính biết (xem hợp đồng). Tuy nhiên, nên báo ISA khi gia hạn visa để họ biết tình huống.',
      },
      {
        question: 'YouTube monetize cần 資格外活動許可 không?',
        answer: 'Có. YouTube monetize = bạn lấy doanh thu quảng cáo (business income) từ Google AdSense. Đây là kinh doanh nên cần 資格外活動許可. Nếu chỉ upload video không kiếm tiền = không cần.',
      },
      {
        question: 'Tôi đang làm freelance rồi, giờ phát hiện cần phép — mình bị sao?',
        answer: 'Xin phép ngay. ISA thường cấp 資格外活動許可 tính từ ngày bạn xin (không phạt ngược về quá khứ nếu bạn chủ động báo). Tuy nhiên đừng trì hoãn — vi phạm càng lâu càng bị xem là cố tình.',
      },
      {
        question: 'Nếu bị phát hiện không xin phép mà làm freelance thì sao?',
        answer: 'ISA có thể: (1) Từ chối gia hạn visa, (2) Yêu cầu ngừng hoạt động, (3) Phạt tiền hoặc ở mức nặng là buộc rời Nhật. Vì vậy nên xin phép sớm.',
      },
    ],
    counterPhrases: [
      {
        jp: '資格外活動許可を申請したいです。フリーランスの業務委託の予定です。',
        romaji: 'Shikakugai katsudou kyoka o shinsei shitai desu. Furiiransu no gyoumu itaku no yotei desu.',
        vn: 'Tôi muốn xin 資格外活動許可. Dự định làm freelance theo hợp đồng 業務委託.',
        note: 'Câu mở đầu tại Nyukan. Nói rõ loại hình (業務委託 ≠ employment) để Nyukan đánh giá đúng.',
      },
      {
        jp: '本業の在留資格は「技術・人文知識・国際業務」です。副業の内容は〇〇です。',
        romaji: 'Hongyou no zairyuu shikaku wa gijutsu jinbun chishiki kokusai gyoumu desu. Fukugyou no naiyou wa marumaru desu.',
        vn: 'Visa chính tôi là 技人国. Nội dung side job là 〇〇.',
        note: 'Nyukan cần biết visa chính + nội dung side job để xét có "ngoài phạm vi" hay không.',
      },
      {
        jp: '業務委託の場合、資格外活動の範囲はどう判断されますか。',
        romaji: 'Gyoumu itaku no baai, shikakugai katsudou no han\'i wa dou handan saremasu ka.',
        vn: 'Trường hợp 業務委託, phạm vi 資格外活動 được đánh giá thế nào?',
        note: '業務委託 (contract) xét theo nội dung công việc, KHÔNG theo số giờ như arubaito (28h/tuần rule).',
      },
      {
        jp: '個人事業主として開業届を出したいですが、先に資格外活動許可が必要ですか。',
        romaji: 'Kojin jigyounushi to shite kaigyou todoke o dashitai desu ga, saki ni shikakugai katsudou kyoka ga hitsuyou desu ka.',
        vn: 'Tôi muốn nộp 開業届 thành 個人事業主, có cần xin 資格外活動許可 trước không?',
        note: '開業届 ở 税務署 KHÔNG yêu cầu 資格外活動 trước. NHƯNG mở kinh doanh mà chưa có phép Nyukan = vi phạm visa.',
      },
      {
        jp: '副業の収入が年20万円を超えた場合、確定申告が必要ですか。',
        romaji: 'Fukugyou no shuunyuu ga nen 20-man en o koeta baai, kakutei shinkoku ga hitsuyou desu ka.',
        vn: 'Thu nhập side >¥200,000/năm có cần 確定申告 không?',
        note: 'YES. 20万円ルール — luật thuế độc lập với visa. Khai báo thuế ở 税務署, KHÁC Nyukan.',
      },
      {
        jp: '本業の会社の契約に副業禁止と書いてありますが、これは入管法と関係ありますか。',
        romaji: 'Hongyou no kaisha no keiyaku ni fukugyou kinshi to kaite arimasu ga, kore wa nyuukan-hou to kankei arimasu ka.',
        vn: 'Hợp đồng công ty chính có điều khoản cấm side job, có liên quan đến 入管法 không?',
        note: 'KHÔNG liên quan visa. 副業禁止 là vấn đề dân sự với công ty (rủi ro 解雇 nếu vi phạm), nhưng Nyukan KHÔNG ép thực thi.',
      },
    ],
    keyTerms: [
      {
        term: '副業',
        reading: 'ふくぎょう',
        meaningVi: 'side job / công việc phụ (khái niệm chung)',
        noteVi: 'Thuật ngữ phổ thông cho mọi hoạt động kiếm thu nhập NGOÀI 本業 (công việc chính). KHÔNG phải định nghĩa pháp lý chính xác. Có thể là arubaito part-time, 業務委託, 個人事業, đầu tư. Hợp đồng lao động Nhật thường có điều khoản 副業禁止 hoặc 副業届出義務 — kiểm tra TRƯỚC khi làm. KHÔNG phải mọi 副業 đều cần 資格外活動 — phụ thuộc xem hoạt động đó CÓ trong phạm vi 在留資格 chính hay không.',
      },
      {
        term: '業務委託',
        reading: 'ぎょうむいたく',
        meaningVi: 'hợp đồng giao việc / contract work (B2B, không phải employment)',
        noteVi: 'Quan hệ KINH DOANH giữa người làm và client — KHÔNG phải quan hệ lao động (雇用関係). Người làm là contractor độc lập, tự lo thuế, không có 雇用保険 / 厚生年金 từ client. Trên work visa, 業務委託 luôn cần 資格外活動許可 (vì hoạt động NGOÀI nội dung 在留資格). Khác arubaito part-time — không tính theo 28h/tuần mà theo nội dung công việc.',
      },
      {
        term: '個人事業主',
        reading: 'こじんじぎょうぬし',
        meaningVi: 'sole proprietor / chủ kinh doanh cá nhân',
        noteVi: 'Tư cách thuế (KHÔNG phải tư cách lưu trú). Đăng ký bằng cách nộp 開業届 tại 税務署 trong 1 tháng từ ngày bắt đầu. Cho phép: lập 屋号 (tên kinh doanh), 青色申告 (giảm 65 vạn yên thuế), khai chi phí hoạt động. CẢNH BÁO: trên work visa, có 個人事業主 status thuế KHÔNG có nghĩa OK về visa — vẫn cần 資格外活動許可. Nếu muốn LIVE từ kinh doanh cá nhân hoàn toàn → cần 経営・管理 visa (hoàn toàn khác work visa).',
      },
      {
        term: '資格外活動許可',
        reading: 'しかくがいかつどうきょか',
        meaningVi: 'giấy phép hoạt động ngoài phạm vi tư cách lưu trú',
        noteVi: 'Cấp bởi 出入国在留管理庁 theo 入管法 §19. BẮT BUỘC TRƯỚC khi làm bất kỳ hoạt động kiếm tiền nào ngoài 在留資格 chính. 2 loại: (1) 包括許可 cho 留学/家族滞在 — 28h/tuần arubaito; (2) 個別許可 cho work visa làm 副業/業務委託 — theo từng hợp đồng. Miễn phí, mất ~1-2 tuần. Có hiệu lực 1 năm hoặc đến khi visa hết — phải gia hạn cùng visa.',
      },
      {
        term: '開業届',
        reading: 'かいぎょうとどけ',
        meaningVi: 'đăng ký mở kinh doanh (tại 税務署)',
        noteVi: 'Form đăng ký 個人事業主 tại 税務署 — nộp trong 1 tháng từ ngày bắt đầu kinh doanh. Miễn phí. Sau khi nộp có thể chọn 青色申告 (giảm 65 vạn yên thuế) bằng 青色申告承認申請書. KHÁC với 資格外活動 — đăng ký thuế và đăng ký visa là 2 cơ quan riêng. Nộp 開業届 không tự động làm visa hợp lệ.',
      },
      {
        term: '確定申告',
        reading: 'かくていしんこく',
        meaningVi: 'tờ khai thuế thu nhập cá nhân hàng năm',
        noteVi: 'Bắt buộc nếu: (1) 個人事業主 (mọi mức thu nhập); (2) lao động + side income >¥20 万円/năm; (3) lao động có lương >¥2 千万円/năm. Nộp tại 税務署 trong tháng 2-3 năm sau (kỳ thuế 1/1-12/31). KHÔNG khai = vi phạm luật thuế (重加算税 đến 35%) — độc lập với vi phạm visa. Có 2 dạng: 白色 (đơn giản) hoặc 青色 (giảm thuế nhiều hơn).',
      },
      {
        term: 'インボイス制度',
        reading: 'インボイスせいど',
        meaningVi: 'hệ thống Invoice Qualified Registration (từ 10/2023)',
        noteVi: 'Cải cách thuế tiêu dùng (消費税) áp dụng từ 01/10/2023. Freelance bán B2B với thu nhập >¥1 千万円/năm BẮT BUỘC đăng ký 適格請求書発行事業者 (qualified invoice issuer) để client được khấu trừ 消費税. Đăng ký = phải nộp 消費税 hàng năm (~10% doanh thu). Freelance nhỏ (<¥1 千万円/năm) có thể KHÔNG đăng ký nhưng client lớn có thể từ chối hợp tác.',
      },
      {
        term: '源泉徴収',
        reading: 'げんせんちょうしゅう',
        meaningVi: 'khấu trừ thuế tại nguồn',
        noteVi: 'Client trả tiền freelance THƯỜNG khấu trừ 10.21% trước khi trả (cho writing/design/translation/lecture). Đây là thuế thu nhập tạm trả thay bạn; bạn lấy lại phần thừa khi 確定申告. Client cấp 支払調書 (報酬支払調書) cuối năm ghi tổng tiền trả + thuế đã khấu trừ. Lưu giấy này — cần cho 確定申告.',
      },
      {
        term: '副業禁止',
        reading: 'ふくぎょうきんし',
        meaningVi: 'cấm side job (điều khoản hợp đồng lao động)',
        noteVi: 'Điều khoản DÂN SỰ trong hợp đồng lao động (就業規則) — KHÔNG phải luật. Vi phạm = công ty có quyền 戒告 / 減給 / 解雇. Tuy nhiên Bộ Lao động (厚生労働省) khuyến khích cho phép 副業 từ 2018 — nhiều công ty đã bỏ điều khoản này. Đọc kỹ hợp đồng + 就業規則 TRƯỚC. KHÁC vấn đề Nyukan — Nyukan không ép thực thi 副業禁止, nhưng bạn vẫn cần 資格外活動許可.',
      },
    ],
    officialLinks: [
      { label: 'ISA — 資格外活動許可 (Permission for Activities Outside Status)', url: 'https://www.moj.go.jp/isa/applications/procedures/16-8.html' },
      { label: 'ISA — Freelance & Work Visa', url: 'https://www.moj.go.jp/isa/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Xác định loại hoạt động của bạn',
        description: '**Hoạt động nào cần 資格外活動許可?**\n\n| Loại hoạt động | Cần phép? | Ghi chú |\n|---|---|---|\n| Freelance (nhận từ khách khác) | ✅ CÓ | Client > 1, kiếm tiền = business |\n| Part-time job (1 công ty/shop) | ❌ KHÔNG | Nhưng nên báo công ty & ISA |\n| YouTube monetize (ads, Patreon) | ✅ CÓ | Lấy doanh thu = business |\n| Etsy/Amazon/Yahoo Auctions bán hàng | ✅ CÓ | Bán = business |\n| Content creator (tiền người tài trợ) | ✅ CÓ | Kiếm tiền từ content |\n| Đầu tư chứng khoán/crypto | ❌ KHÔNG | Nhưng vẫn phải khai thuế |\n| Hoạt động không kiếm tiền | ❌ KHÔNG | Blog, podcast miễn phí không được tiền |\n| Công việc trong phạm vi tư cách visa | ❌ KHÔNG | Ví dụ: engineer làm thêm project cho công ty = trong phạm vi|\n\nNếu không chắc = xin phép để an toàn.',
        documents: ['Mô tả hoạt động của bạn'],
        tip: 'Khi nghi ngờ, hỏi ISA — họ sẽ giải thích rõ ràng hoạt động của bạn cần phép hay không.',
      },
      {
        step: 2,
        title: 'Xin 資格外活動許可 tại ISA',
        description: '**Chuẩn bị:**\n- Đơn xin 資格外活動許可申請書 (in từ ISA website)\n- Hộ chiếu + thẻ cư trú\n- Giấy tờ mô tả hoạt động (proposal, portfolio, client list, hoặc mô tả chi tiết)\n- Lý do giải trình (tại sao bạn muốn làm thêm, ảnh hưởng đến visa hiện tại không)\n\n**Nộp tại ISA:**\n- Trực tiếp tại cục công an nhập cảnh nơi cư trú\n- Hoặc trực tuyến (nếu áp dụng)\n\n**Phí:** 0 (miễn phí)\n\n**Thời gian phê duyệt:** 1-2 tuần\n\n**Nếu được phê duyệt:**\n- Bạn sẽ nhận giấy chứng nhận 資格外活動許可 hoặc dấu trên thẻ cư trú\n- Giấy phép sẽ ghi: loại hoạt động, thời hạn (thường 1 năm), hạn chế (nếu có)\n- Bạn có thể bắt đầu hoạt động ngay từ ngày được phê duyệt',
        documents: ['Đơn xin (in từ ISA)', 'Hộ chiếu', 'Thẻ cư trú', 'Giấy tờ mô tả hoạt động'],
        tip: 'Giấy phép chỉ có hiệu lực 1 năm — khi gia hạn visa lần sau, hãy xin gia hạn 資格外活動許可 nữa.',
      },
      {
        step: 3,
        title: 'Báo cáo với công ty & bảo hiểm / thuế',
        description: '**Báo với công ty chính (nếu có):**\n- Kiểm tra hợp đồng xem có cấm side job không\n- Nếu cấm: cân nhắc từ bỏ side job hoặc tìm công ty khác\n- Nếu cho phép: báo rõ ràng scope hoạt động side job để không xung đột lợi ích\n\n**Báo cáo thuế & bảo hiểm:**\n- Nếu side income > một số tiền nào đó (thường ¥200,000/năm), phải báo cáo với 税務署 (tax office)\n- Nếu bạn là 個人事業主 (kinh doanh cá nhân), cần nộp 開業届 (đăng ký mở kinh doanh) tại 税務署\n- Bảo hiểm y tế: side income không ảnh hưởng (vẫn thông qua bảo hiểm công ty)\n- Bảo hiểm lao động (労災): nếu làm freelance, bạn tự bảo vệ (công ty không cover)',
        documents: ['Hợp đồng lao động với công ty chính', 'Giấy chứng nhận 資格外活動許可 từ ISA'],
        tip: 'Không nên che giấu side income từ thuế — phát hiện sẽ bị phạt + tiền lãi. Nên tìm tư vấn từ 税理士 (tax accountant) nếu side income lớn.',
      },
      {
        step: 4,
        title: 'Duy trì & gia hạn phép khi cần',
        description: '**Lưu ý khi làm freelance/side job:**\n\n- Giữ bản sao hợp đồng, hóa đơn, email từ client — để chứng minh hoạt động nếu ISA hỏi\n- Báo cáo thuế hàng năm (確定申告) vào tháng 2-3 năm sau\n- Khi gia hạn visa: ISA có thể hỏi về side job — hãy chuẩn bị tài liệu chứng minh\n- Nếu 資格外活動許可 sắp hết (thường 1 năm), xin gia hạn trước khi hết\n\n**Nếu muốn dừng:**\n- Báo ISA (không cần form chính thức, chỉ cần mô tả)\n- Công ty cần biết để cập nhật hợp đồng\n- Không ảnh hưởng đến visa hiện tại',
        documents: ['Hợp đồng, hóa đơn, email từ client', 'Giấy gia hạn 資格外活動許可 (nếu cần)'],
        tip: 'Luôn giữ tài liệu — ISA có thể kiểm tra khi gia hạn visa để chắc bạn thực sự làm hoạt động đó (không phải giả mạo).',
      },
    ],
  };

export default freelanceSideJobWorkVisaRules;
