import type { AdminGuide } from '../../../../types/content';

const ginouJisshuToTokuteiGinou: AdminGuide = {
    id: 'ginou-jisshu-to-tokutei-ginou',
    category: 'visa',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Chuyển từ 技能実習 sang 特定技能',
    titleJp: '技能実習から特定技能への移行手続き',
    icon: 'swap-horizontal',
    color: '#1E8449',
    description: 'Hướng dẫn thực tế các bước chuyển đổi tư cách lưu trú từ 技能実習 sang 特定技能1号 — bao gồm điều kiện miễn thi, quy trình hồ sơ và thời điểm nộp. Khác với guide tổng quan về luật 育成就労 (xem guide riêng). Điều kiện cụ thể có thể khác theo ngành nghề và từng năm — nên xác nhận thông tin mới nhất với công ty tiếp nhận và 出入国在留管理庁.',
    searchKeywords: [
      'titp to ssw',
      'jisshu sang dac dinh',
      'thuc tap sinh sang dac dinh',
      'chuyen visa thuc tap',
      'visa dac dinh ky nang',
      'visa ky nang dac dinh',
      'ginou jisshu',
      'tokutei ginou',
      'specified skilled worker',
      'mien thi ky nang',
      'mien thi tieng nhat',
      'JLPT N4',
      'JFT-Basic',
      '16 nganh dac dinh',
      'thuc tap sinh het han',
      'tu cach dac dinh 1',
      'tu cach dac dinh 2',
      '5 nam visa dac dinh',
      'ssw 5 nam',
      'ssw 2 vinh tru',
      'doi cong ty dac dinh',
      'shien keikaku',
      'toroku shien kikan',
      '技能実習',
      '技能実習2号',
      '特定技能',
      '特定技能1号',
      '特定技能2号',
      '技能評価試験',
      '支援計画書',
      '登録支援機関',
      '修了証明書',
      '育成就労',
      '分野別協議会',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Chuyển sang 特定技能 là thủ tục ISA; điều kiện ngành, kỳ thi và hỗ trợ phụ thuộc chế độ 特定技能 và cơ quan/tổ chức của từng lĩnh vực.',
      sourceVerifiedAt: '2026-05-06',
      nextReviewAt: '2026-10-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Ngành/công việc 技能実習 đã hoàn thành không khớp với công việc 特定技能 dự kiến.',
        'Visa 技能実習 sắp hết hạn nhưng công ty tiếp nhận chưa có 支援計画 hoặc hồ sơ phía công ty.',
        'Bạn muốn dùng 特定活動 tạm thời trong thời gian chuẩn bị chuyển 特定技能.',
      ],
    },
    quickAction: {
      deadline: 'Chuẩn bị trước khi 技能実習 hết hạn, thực tế nên bắt đầu ít nhất 3-4 tháng trước ngày hết hạn.',
      office: 'Công ty tiếp nhận/登録支援機関 chuẩn bị hồ sơ hỗ trợ; ISA xét 在留資格変更; tổ chức thi từng ngành xử lý kỳ thi.',
      doNow: [
        'Đối chiếu ngành 技能実習 đã hoàn thành với lĩnh vực 特定技能 muốn chuyển.',
        'Xác nhận có được miễn thi kỹ năng/tiếng Nhật hay phải thi.',
        'Yêu cầu công ty tiếp nhận chuẩn bị hợp đồng, 支援計画 và tài liệu phía công ty trước khi nộp ISA.',
      ],
      bring: ['Hộ chiếu và thẻ cư trú', 'Hợp đồng 特定技能', '支援計画書', '修了証明書 nếu dùng miễn thi', 'Kết quả thi kỹ năng/tiếng Nhật nếu cần'],
      ifLate: 'Nếu còn ít ngày đến hạn visa, ưu tiên hỏi ISA ngay về phương án nộp/chờ kết quả; không tự ý làm việc ngoài phạm vi tư cách hiện tại.',
      officialSourceLabels: [
        '特定技能制度 — 出入国在留管理庁',
        '技能実習から特定技能への移行 — 出入国在留管理庁',
        '在留資格「特定技能」— 出入国在留管理庁',
      ],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_titp-ssw_hero.jpg'),
    heroImageCaption: '技能実習から特定技能へ - kiểm tra điều kiện chuyển tư cách trước khi hết hạn',
    whoIsThisFor: [
      'Thực tập sinh 技能実習 đang chuẩn bị hết hợp đồng và muốn tiếp tục ở lại Nhật làm việc.',
      'Người đã hoàn thành 技能実習2号 hoặc 3号 và đủ điều kiện chuyển sang 特定技能1号 mà không cần thi.',
      'Thực tập sinh muốn hiểu cụ thể mình cần thi gì, nộp gì và nộp ở đâu — không chỉ biết "có thể chuyển được".',
    ],
    whenToDo: [
      'Nộp đơn trước khi 技能実習 hết hạn — không được để hết hạn rồi mới chuyển.',
      'Nên chuẩn bị hồ sơ ít nhất 3–4 tháng trước ngày 技能実習 hết hạn để có đủ thời gian thi và xử lý hồ sơ ISA.',
      'Nếu đã hoàn thành 技能実習2号 cùng ngành, có thể nộp ngay — không cần đợi hết thêm thời gian.',
    ],
    whereToDo: [
      'Công ty tiếp nhận 特定技能 hoặc 登録支援機関: xác nhận hợp đồng, kế hoạch hỗ trợ và hồ sơ phía công ty.',
      'Cục xuất nhập cảnh (ISA) có thẩm quyền theo nơi cư trú: nộp 在留資格変更許可申請.',
      'Tổ chức thi của từng ngành 特定技能: đăng ký thi kỹ năng nếu không được miễn.',
      'Đơn vị quản lý/監理団体 hoặc công ty thực tập cũ: xin giấy chứng minh đã hoàn thành 技能実習 nếu cần.',
    ],
    documentsChecklist: [
      { label: '在留資格変更許可申請書', required: true },
      { label: 'Hộ chiếu, 在留カード và ảnh thẻ', required: true },
      { label: 'Hợp đồng lao động với công ty tiếp nhận 特定技能', required: true },
      { label: '支援計画書', required: true, note: 'Thường do công ty tiếp nhận hoặc 登録支援機関 chuẩn bị.' },
      { label: '修了証明書 hoặc giấy tờ chứng minh hoàn thành 技能実習', required: false, note: 'Cần nếu dùng điều kiện miễn thi.' },
      { label: 'Kết quả thi kỹ năng và tiếng Nhật', required: false, note: 'Cần nếu không thuộc diện miễn theo ngành/công việc tương ứng.' },
      { label: 'Tài liệu phía công ty theo checklist ISA/特定技能', required: true, note: 'Khác nhau theo ngành và loại hồ sơ.' },
    ],
    commonMistakes: [
      'Tưởng hoàn thành 技能実習 là tự động được chuyển, dù ngành/công việc 特定技能 không khớp.',
      'Để 技能実習 hết hạn rồi mới chuẩn bị hồ sơ chuyển tư cách.',
      'Ký hợp đồng với công ty chưa chuẩn bị được 支援計画 hoặc hồ sơ tiếp nhận.',
      'Đổi công ty tiếp nhận trong thời gian chuẩn bị nhưng không kiểm tra lại hồ sơ ISA.',
      'Tưởng 特定活動 6 tháng để chuẩn bị chuyển 特定技能 là quyền tự động; đây cũng là hồ sơ phải được ISA cho phép và có điều kiện.',
    ],
    faq: [
      {
        question: 'Hoàn thành 技能実習2号 thì có được miễn thi không?',
        answer: 'Có thể được miễn nếu công việc/ngành chuyển sang 特定技能1号 tương ứng với nội dung 技能実習 đã hoàn thành. Nếu không khớp, thường phải thi kỹ năng và chứng minh tiếng Nhật theo yêu cầu ngành.',
      },
      {
        question: 'Có được tiếp tục làm việc khi hồ sơ chuyển đang xét không?',
        answer: 'Chỉ được làm trong phạm vi tư cách lưu trú hoặc 指定書 hiện có cho phép. Nếu cần dùng 特定活動 6 tháng để chuẩn bị chuyển 特定技能1号, phải nộp và được ISA cho phép theo điều kiện riêng.',
      },
      {
        question: '特定技能1号 có ở Nhật vô thời hạn được không?',
        answer: 'Không. 特定技能1号 có giới hạn tổng thời gian lưu trú theo quy định của chế độ này. Muốn tiếp tục lâu dài cần kiểm tra đường sang 特定技能2号 hoặc tư cách lưu trú khác phù hợp.',
      },
    ],
    counterPhrases: [
      {
        jp: '技能実習2号を修了したので、特定技能1号に変更したいです。',
        romaji: 'Ginou jisshuu 2-gou o shuuryou shita node, tokutei ginou 1-gou ni henkou shitai desu.',
        vn: 'Tôi đã hoàn thành 技能実習2号 nên muốn đổi sang 特定技能1号.',
        note: 'Câu mở đầu khi gặp Nyukan hoặc công ty mới.',
      },
      {
        jp: '同じ分野なので、技能評価試験と日本語試験は免除されるはずです。',
        romaji: 'Onaji bunya nano de, ginou hyouka shiken to nihongo shiken wa menjo sareru hazu desu.',
        vn: 'Cùng ngành nên tôi nên được miễn thi kỹ năng và thi tiếng Nhật.',
        note: 'Câu xác nhận trường hợp miễn cả 2 bài thi. "Cùng ngành" do 分野別協議会 quyết định — KHÔNG tự kết luận.',
      },
      {
        jp: '修了証明書はもう監理団体からもらいました。',
        romaji: 'Shuuryou shoumeisho wa mou kanri dantai kara moraimashita.',
        vn: '修了証明書 tôi đã xin từ 監理団体 (đơn vị quản lý) rồi.',
        note: '修了証明書 là tài liệu CẦN cho miễn thi. Nếu 監理団体 chậm cấp → hỏi công ty thực tập cũ.',
      },
      {
        jp: '受け入れ会社は登録支援機関と契約しています。支援計画書も準備中です。',
        romaji: 'Ukeire kaisha wa touroku shien kikan to keiyaku shite imasu. Shien keikakusho mo junbi-chuu desu.',
        vn: 'Công ty tiếp nhận đã ký với 登録支援機関 rồi, kế hoạch hỗ trợ cũng đang chuẩn bị.',
        note: 'Công ty 特定技能 PHẢI có 支援計画 — hoặc tự lập (nếu đủ năng lực) hoặc thuê 登録支援機関.',
      },
      {
        jp: '技能実習の在留期限まであと3か月です。間に合いますか。',
        romaji: 'Ginou jisshuu no zairyuu kigen made ato 3-kagetsu desu. Maniaimasu ka.',
        vn: 'Hạn 技能実習 còn 3 tháng. Kịp xử lý không ạ?',
        note: 'Thời gian xét 1-2 tháng. Nếu 技能実習 hết hạn trong khi chờ → có thể được cấp 特定活動 tạm thời (4 tháng).',
      },
      {
        jp: '5年経った後、特定技能2号に変更できる条件は何ですか。',
        romaji: '5-nen tatta ato, tokutei ginou 2-gou ni henkou dekiru jouken wa nan desu ka.',
        vn: 'Sau 5 năm, điều kiện đổi sang 特定技能2号 là gì?',
        note: '特定技能2号 yêu cầu cao hơn (kỹ năng + lương + thời gian). Chỉ một số ngành áp dụng — xác nhận với 分野別協議会 ngành đang làm.',
      },
    ],
    keyTerms: [
      {
        term: '技能実習2号',
        reading: 'ぎのうじっしゅう2ごう',
        meaningVi: 'Thực tập kỹ năng giai đoạn 2 (cộng dồn ~3 năm)',
        noteVi: 'Hoàn thành 技能実習2号 thường mở đường miễn thi khi chuyển 特定技能1号 (nếu cùng ngành). Bạn cần 修了証明書 từ 監理団体 hoặc công ty thực tập cũ. KHÁC 技能実習3号 (thêm 2 năm).',
      },
      {
        term: '特定技能1号',
        reading: 'とくていぎのう1ごう',
        meaningVi: 'visa Kỹ năng Đặc định cấp 1',
        noteVi: 'Tư cách lao động cho 16 ngành thiếu nhân lực. Tổng thời gian tối đa 5 năm (cộng dồn). KHÔNG cho bảo lãnh gia đình ở giai đoạn này. Chuyển công ty trong cùng ngành thường được phép — phải làm 在留資格変更.',
      },
      {
        term: '特定技能2号',
        reading: 'とくていぎのう2ごう',
        meaningVi: 'visa Kỹ năng Đặc định cấp 2 (không giới hạn thời gian)',
        noteVi: 'Bước nâng cấp sau 特定技能1号. Thời hạn 1-3 năm + gia hạn không giới hạn — có thể mở đường 永住. Cho phép bảo lãnh gia đình. Yêu cầu kỹ năng cao + thường cần 2+ năm kinh nghiệm quản lý trong 1号. Không phải mọi ngành đều có 2号 — kiểm tra với 分野別協議会.',
      },
      {
        term: '技能評価試験',
        reading: 'ぎのうひょうかしけん',
        meaningVi: 'kỳ thi đánh giá kỹ năng nghề',
        noteVi: 'Thi kỹ năng cho từng ngành (vd JAC cho 建設, FPA cho thực phẩm). Đề thường tiếng Nhật + minh hoạ. Tổ chức tại Nhật + nhiều nước (gồm VN). Đăng ký qua trang ngành — chỗ thi có giới hạn nên đăng ký sớm.',
      },
      {
        term: 'JFT-Basic',
        reading: 'JFT-ベーシック',
        meaningVi: 'Kỳ thi tiếng Nhật cơ bản cho 特定技能',
        noteVi: 'Do Japan Foundation tổ chức, mức A2 (tương đương N4). Dễ hơn JLPT N4 vì tập trung tiếng Nhật thực tế. Tổ chức nhiều lần/năm. Có JFT-Basic = đủ điều kiện tiếng Nhật cho 特定技能1号 (không cần JLPT). Nhưng vẫn phải thi 技能評価試験 nếu không miễn.',
      },
      {
        term: '支援計画書',
        reading: 'しえんけいかくしょ',
        meaningVi: 'kế hoạch hỗ trợ người lao động đặc định',
        noteVi: 'Tài liệu BẮT BUỘC do công ty tiếp nhận (hoặc 登録支援機関 ủy quyền) lập. Mô tả 10 mục hỗ trợ: đón sân bay, hỗ trợ thuê nhà, dạy tiếng Nhật, tư vấn cuộc sống, v.v. Không có 支援計画 = công ty KHÔNG được nhận 特定技能.',
      },
      {
        term: '登録支援機関',
        reading: 'とうろくしえんきかん',
        meaningVi: 'tổ chức đăng ký hỗ trợ',
        noteVi: 'Đơn vị do 出入国在留管理庁 cấp phép để hỗ trợ người 特定技能 thay công ty tiếp nhận. Nếu công ty không đủ năng lực tự hỗ trợ → phải thuê 登録支援機関. Khác 監理団体 (đơn vị quản lý cho 技能実習).',
      },
      {
        term: '育成就労',
        reading: 'いくせいしゅうろう',
        meaningVi: 'chế độ mới Đào tạo - Lao động (từ 2027)',
        noteVi: 'Chế độ thay thế 技能実習 dự kiến áp dụng từ 01/04/2027. Mục tiêu rõ ràng là đào tạo + chuyển 特定技能 sau 3 năm. Người đang 技能実習 hiện nay KHÔNG ảnh hưởng — vẫn theo quy trình cũ. Theo dõi thông báo 出入国在留管理庁 khi gần mốc 2027.',
      },
    ],
    officialLinks: [
      { label: '特定技能制度 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/ssw/index.html' },
      { label: '技能実習から特定技能への移行 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/ssw/10_00025.html' },
      { label: '在留資格「特定技能」— 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/status/specifiedskilledworker.html' },
      { label: '登録支援機関一覧 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/policies/ssw/seido/touroku_list.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra bạn có được miễn thi không',
        description: 'ISA và 厚生労働省 quy định hai trường hợp miễn thi kỹ năng và tiếng Nhật khi chuyển sang 特定技能1号:\n\nTrường hợp 1 — Miễn cả hai bài thi: Đã hoàn thành 技能実習2号 CÙNG ngành/công việc sẽ làm ở 特定技能1号. "Cùng ngành" được xác định theo danh sách đối chiếu chính thức của từng ngành (分野別協議会).\n\nTrường hợp 2 — Miễn thi tiếng Nhật: Có chứng chỉ JLPT N4 trở lên hoặc JFT-Basic đạt A2. Vẫn phải thi kỹ năng nghề nếu không thuộc trường hợp 1.\n\nNếu không thuộc cả hai: phải thi đủ cả kỹ năng nghề (技能評価試験) lẫn tiếng Nhật.',
        documents: [],
        tip: 'Kiểm tra danh sách lĩnh vực 特定技能1号 chính thức trước khi thi hoặc ký hợp đồng. Từ 2026, hệ thống 特定技能1号 có 16 lĩnh vực, gồm 介護, ビルクリーニング, 工業製品製造業, 建設, 造船・舶用工業, 自動車整備, 航空, 宿泊, 自動車運送業, 鉄道, 農業, 漁業, 飲食料品製造業, 外食業, 林業 và 木材産業.',
      },
      {
        step: 2,
        title: 'Thi kỹ năng và tiếng Nhật (nếu cần)',
        description: 'Thi kỹ năng nghề (技能評価試験): tổ chức bởi cơ quan của từng ngành, lịch thi và địa điểm khác nhau. Đăng ký qua trang chính thức của ngành (ví dụ: FPA cho thực phẩm, JAC cho xây dựng). Thi thường bằng tiếng Nhật — một số ngành có hỗ trợ tiếng Việt trong phòng thi.\n\nThi tiếng Nhật: JFT-Basic (Japan Foundation — dễ hơn) hoặc JLPT N4 trở lên. JFT-Basic được tổ chức nhiều lần/năm tại nhiều địa điểm, bao gồm Việt Nam.',
        documents: [
          'Giấy tờ tùy thân (thẻ cư trú hoặc passport) khi dự thi',
        ],
        tip: 'JFT-Basic và JLPT là hai bài thi độc lập — đỗ một bài không đồng nghĩa đỗ bài kia. Lịch thi JFT-Basic công bố trên trang Japan Foundation; đăng ký sớm vì chỗ thi có giới hạn.',
      },
      {
        step: 3,
        title: 'Chuẩn bị hồ sơ chuyển đổi tư cách',
        description: 'Hồ sơ nộp tại ISA gồm:\n• Đơn 在留資格変更許可申請\n• Hợp đồng lao động mới với công ty tiếp nhận 特定技能 (đã đăng ký với cơ quan liên quan)\n• Kế hoạch hỗ trợ (支援計画書) — do công ty hoặc tổ chức đăng ký hỗ trợ (登録支援機関) lập\n• Bằng chứng hoàn thành 技能実習2号 (giấy 修了証明書) hoặc kết quả thi kỹ năng + tiếng Nhật\n• Thẻ cư trú và hộ chiếu\n• Giấy tờ từ phía công ty: đăng ký doanh nghiệp, hồ sơ tài chính v.v. (công ty chuẩn bị)',
        documents: [
          'Đơn 在留資格変更許可申請',
          'Hợp đồng lao động với công ty tiếp nhận 特定技能',
          '支援計画書',
          '修了証明書 (nếu hoàn thành 技能実習2号) hoặc kết quả thi kỹ năng + tiếng Nhật',
          'Thẻ cư trú và hộ chiếu',
        ],
        tip: 'Công ty tiếp nhận 特定技能 phải là công ty đã được cơ quan ngành liên quan xác nhận — không thể chuyển sang công ty ngẫu nhiên. Nếu công ty cũ muốn chuyển bạn sang 特定技能, họ cần làm thủ tục đăng ký trước.',
      },
      {
        step: 4,
        title: 'Nộp hồ sơ và quản lý thời hạn',
        description: 'Nộp tại ISA khi 技能実習 còn hiệu lực. Thời gian xử lý thường 1–2 tháng. Nếu 技能実習 hết hạn trong khi đang chờ ISA xử lý, bạn nhận được 特定活動 tạm thời (giấy 指定書 ghi rõ) cho phép tiếp tục làm việc hợp pháp trong thời gian chờ kết quả.\n\n特定技能1号 có tổng thời hạn tối đa 5 năm (cộng dồn), không gia hạn vô hạn. Để tiếp tục sau 5 năm: phải đủ điều kiện 特定技能2号 (yêu cầu cao hơn, không giới hạn thời gian) hoặc chuyển sang tư cách khác như 永住.',
        documents: [],
        tip: 'Từ năm 2027 với hệ thống 育成就労, người hoàn thành 育成就労 cùng ngành sẽ chuyển sang 特定技能1号 theo quy trình mới — theo dõi thông báo ISA để cập nhật khi đến gần mốc 01/04/2027.',
      },
    ],
  };

export default ginouJisshuToTokuteiGinou;
