import type { AdminGuide } from '../../../../types/content';

const kokuhoReduction: AdminGuide = {
    id: 'kokuho-reduction',
    category: 'health',
    lastVerified: '2026-08-21',
    priority: 'high',
    title: 'Giảm phí bảo hiểm y tế quốc dân',
    titleJp: '国民健康保険料（税）の軽減・減額申請',
    icon: 'medkit',
    color: '#27AE60',
    description: 'Khi thu nhập thấp hoặc mất việc, phí 国民健康保険 có thể được giảm tự động hoặc theo đơn xin — nhiều người không biết và bỏ lỡ quyền lợi này.',
    searchKeywords: [
      'bảo hiểm y tế quốc dân',
      'giảm phí bảo hiểm',
      'thu nhập thấp xin giảm',
      '国民健康保険',
      'kokumin kenkou hoken',
      '国保',
      'kokuho',
      '保険料軽減',
      'hoken ryou keigen',
      '均等割軽減',
      '7割軽減',
      '5割軽減',
      '2割軽減',
      '非自発的失業者',
      'hijihatsu teki shitsugyousha',
      'sa thải xin giảm bảo hiểm',
      'mất việc giảm 国保',
      '雇用保険受給資格者証',
      '離職理由コード',
      '住民税申告',
      'zero income filing',
      'khai thu nhập 0',
      'nghỉ việc bảo hiểm cao',
      'phí 国保 cao bất ngờ',
      'kokuho reduction',
      'unemployment health insurance',
    ],
    legalScope: {
      jurisdiction: 'mixed',
      jurisdictionNote: '国民健康保険 do 国民健康保険法 (Luật BHYT Quốc dân) quản lý cấp quốc gia, nhưng phí + cách giảm thực tế do 市町村 tính riêng. Giảm 均等割軽減 (tự động) theo ngưỡng quốc gia (7割/5割/2割 cho 令和8年度). 非自発的失業者の国保軽減 (giảm khi mất việc không tự nguyện) áp dụng toàn quốc theo mã 離職理由 trên 雇用保険受給資格者証. 減免 hoàn cảnh đặc biệt do từng 市 tự quy định.',
      sourceVerifiedAt: '2026-08-21',
      nextReviewAt: '2026-12-31',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Bị từ chối giảm phí mà không rõ lý do → đến 市役所 hỏi văn bản giải thích; nếu vẫn không thoả → 国民健康保険審査会 (Hội đồng thẩm tra).',
        'Đang nợ phí 国保 nhiều tháng + có thư 督促状 → KHÔNG bỏ ngơ, đến 市役所 ngay xin 分割払い hoặc xét 減免; nợ 国保 ảnh hưởng visa/vĩnh trú.',
        'Đang ở tình trạng 滞納 (nợ phí) + bị cấp 短期被保険者証 thay vì thẻ thường → tới 市役所 + có thể cần 社会福祉協議会 hỗ trợ.',
        'Nghỉ việc do bệnh / thai sản / 介護 nhưng không có mã 離職理由 thuộc nhóm 非自発的 → vẫn có thể xin 減免 hoàn cảnh đặc biệt — hỏi 市役所.',
      ],
    },
    quickAction: {
      deadline: 'Giảm tự động (7割/5割/2割): áp dụng từ đầu năm tài khóa (T4) sau khi khai 住民税 hạn 31/5. 非自発的失業者軽減: nộp trong 1 năm kể từ ngày nghỉ — tốt nhất ngay sau khi nhận 雇用保険受給資格者証.',
      office: '市役所 / 区役所 phòng 保険年金課 / 国民健康保険担当. Không làm online được — phải đến quầy.',
      doNow: [
        'Kiểm tra hộ gia đình đã ai khai 住民税 / 確定申告 năm trước chưa — chưa khai = không được giảm tự động.',
        'Nếu thu nhập 0 hoặc không có lương: đến 市役所 khai 住民税申告 (0円申告) trước 31/5.',
        'Nếu vừa nghỉ việc: xin 離職票 từ công ty cũ → đến ハローワーク đăng ký 雇用保険 → nhận 雇用保険受給資格者証 → kiểm tra mã 離職理由.',
        'Mang 雇用保険受給資格者証 + 在留カード + 国保証 đến 市役所 quầy 国保 → nói "非自発的失業者の軽減を申請したいです".',
        'Nhân viên kiểm tra mã 離職理由 → nếu thuộc nhóm (11/12/21/22/23/31/32/33/34) → áp dụng giảm phí.',
        'Nhận thông báo phí mới (kéo dài đến hết năm tài khóa tiếp theo).',
      ],
      bring: [
        '雇用保険受給資格者証 (bản gốc) — nếu xin 非自発的',
        '在留カード',
        '国民健康保険証',
        'マイナンバー (12 chữ số) hộ gia đình',
        '源泉徴収票 hoặc 確定申告控え năm trước (nếu có)',
        'Sổ ngân hàng (cho 口座振替 trừ tự động)',
      ],
      ifLate: 'Quá 1 năm sau ngày nghỉ việc → mất quyền 非自発的失業者軽減. Vẫn có thể xin 一般軽減 (theo thu nhập) — đến 市役所 hỏi. Đã đóng phí cao rồi mới biết được giảm: theo quy định thông thường KHÔNG hoàn lại phần đã đóng, chỉ áp dụng từ tháng nộp đơn — nên nộp càng sớm càng tốt.',
      officialSourceLabels: ['国民健康保険の保険料・保険税について — 厚生労働省'],
      deadlineMonths: [4, 5, 6],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_kokuho-reduction_hero.jpg'),
    heroImageCaption: 'Xin giảm phí 国民健康保険 khi thu nhập thấp',
    whoIsThisFor: [
      'Người thuộc 国民健康保険 (tự đóng, không qua công ty) với thu nhập thấp hoặc không có thu nhập.',
      'Người vừa nghỉ việc, bị sa thải hoặc công ty phá sản và chuyển sang 国保.',
      'Du học sinh hoặc người mới sang Nhật với thu nhập thấp trong năm đầu.',
    ],
    whenToDo: [
      'Ngay khi nhận thông báo phí 国保 có vẻ cao so với thu nhập thực tế.',
      'Ngay khi nghỉ việc không tự nguyện (bị sa thải, hợp đồng không gia hạn, công ty phá sản) — giảm phí đặc biệt áp dụng từ ngày hôm sau ngày nghỉ.',
      'Nếu thu nhập năm trước thấp, kiểm tra xem có thuộc diện giảm tự động không — không cần nộp đơn nhưng cần khai báo thu nhập đúng.',
    ],
    whereToDo: [
      '市区町村役場 — quầy 国民健康保険 hoặc 保険年金課.',
      'Không thể làm online hoặc qua bưu điện — bắt buộc đến quầy.',
    ],
    estimatedTime: 'Nộp tại quầy: 20–40 phút. Giảm phí thường áp dụng ngay trong tháng nộp hoặc hồi tố từ đầu năm tài khóa.',
    fees: ['Không mất phí — đây là chương trình hỗ trợ của nhà nước.'],
    documentsChecklist: [
      { label: 'Thẻ 国民健康保険', required: true },
      { label: 'Thẻ cư trú (在留カード)', required: true },
      { label: '雇用保険受給資格者証 hoặc 雇用保険受給資格通知', required: false, note: 'Chỉ cần khi xin giảm phí đặc biệt do nghỉ việc không tự nguyện.' },
      { label: 'Giấy tờ thu nhập năm trước (源泉徴収票, 確定申告の控え)', required: false, note: 'Để xác nhận thu nhập nếu chưa khai báo với municipal office.' },
      { label: 'My Number Card hoặc giấy tờ xác nhận danh tính', required: true },
    ],
    commonMistakes: [
      'Nghĩ phí 国保 cố định và không thể thay đổi — thực ra có thể giảm đáng kể nếu đủ điều kiện.',
      'Không khai báo thu nhập với municipal office — nếu không khai, hệ thống không biết thu nhập thấp và không tự động giảm.',
      'Xin giảm phí đặc biệt quá 1 năm sau ngày nghỉ việc — hết hạn và mất quyền hồi tố.',
      'Đóng phí đầy đủ rồi mới xin giảm — giảm phí áp dụng cho phần chưa đóng, phần đã đóng không được hoàn lại theo quy định thông thường.',
    ],
    faq: [
      {
        question: 'Giảm phí tự động có cần nộp đơn không?',
        answer: 'Giảm tự động theo thu nhập (均等割軽減) không cần nộp đơn riêng, nhưng cần đảm bảo municipal office đã có dữ liệu thu nhập của bạn — thông qua khai báo 住民税 hàng năm (5/31). Nếu chưa khai, hãy đến khai để hệ thống tự tính giảm.',
      },
      {
        question: 'Giảm đặc biệt do thất nghiệp áp dụng bao lâu?',
        answer: 'Áp dụng từ ngày hôm sau ngày nghỉ việc đến hết năm tài khóa tiếp theo (離職日の翌日の属する年度の翌年度の末日まで, theo MHLW). Ví dụ nghỉ tháng 8/2025 (令和7年度) → giảm áp dụng đến 3/2027 (令和8年度末). Nhưng phải nộp trong vòng 1 năm kể từ ngày nghỉ.',
      },
      {
        question: 'Du học sinh có được giảm phí không?',
        answer: 'Có thể được giảm tự động nếu thu nhập thấp. Du học sinh thường thuộc diện 7割 hoặc 5割 nếu không có thu nhập đáng kể. Cần đảm bảo đã khai báo thu nhập 0 hoặc thực tế qua 住民税申告.',
      },
      {
        question: 'Phí 国保 tính như thế nào để biết mình có bị giảm không?',
        answer: '国保 gồm 2 phần: 所得割 (tỷ lệ theo thu nhập) và 均等割 (cố định theo đầu người). Giảm phí tự động tác động vào phần 均等割. Mỗi municipality có mức phí khác nhau — tra cứu trang web thành phố/quận hoặc hỏi trực tiếp tại quầy.',
      },
    ],
    counterPhrases: [
      {
        jp: '国民健康保険料の軽減を申請したいです。',
        romaji: 'Kokumin kenkou hokenryou no keigen o shinsei shitai desu.',
        vn: 'Tôi muốn xin giảm phí bảo hiểm y tế quốc dân.',
        note: 'Câu mở đầu tại quầy 保険年金課.',
      },
      {
        jp: '非自発的失業者の軽減はできますか。',
        romaji: 'Hijihatsuteki shitsugyousha no keigen wa dekimasu ka.',
        vn: 'Tôi có được giảm phí dành cho người mất việc không tự nguyện không?',
        note: 'Khi bị sa thải / hợp đồng không gia hạn / công ty phá sản — kiểm tra mã 離職理由.',
      },
      {
        jp: '収入が0なので、住民税の申告をしたいです。',
        romaji: 'Shuunyuu ga zero na node, juuminzei no shinkoku o shitai desu.',
        vn: 'Tôi không có thu nhập, muốn khai báo 住民税 0円申告.',
        note: 'Bước nền tảng để được giảm tự động. Cần làm trước 31/5 hàng năm.',
      },
      {
        jp: '分割払いにできますか。',
        romaji: 'Bunkatsu barai ni dekimasu ka.',
        vn: 'Tôi có thể chia nhỏ kỳ đóng không?',
        note: 'Khi gặp khó khăn tài chính + chưa đủ điều kiện giảm — hỏi 市役所 phương án chia kỳ.',
      },
      {
        jp: '保険料の計算方法を教えてください。',
        romaji: 'Hokenryou no keisan houhou o oshiete kudasai.',
        vn: 'Cho tôi biết cách tính phí bảo hiểm.',
        note: 'Mỗi 市 có cách tính khác — hỏi để biết phần 所得割 + 均等割 + 平等割 trong trường hợp của mình.',
      },
    ],
    keyTerms: [
      {
        term: '国民健康保険',
        reading: 'こくみんけんこうほけん',
        meaningVi: 'bảo hiểm y tế quốc dân (cho người không thuộc 社保)',
        noteVi: 'Viết tắt 国保 (こくほ). Áp dụng cho: tự doanh, freelance, sinh viên, thất nghiệp, người làm part-time không đủ giờ vào 社会保険. Trả 70% chi phí khám-chữa khi mang thẻ đi bệnh viện. Đóng theo 市役所, không qua công ty.',
      },
      {
        term: '均等割',
        reading: 'きんとうわり',
        meaningVi: 'phần phí cố định (mỗi người trong hộ đóng như nhau)',
        noteVi: 'Khoản cố định ~30,000-60,000円/người/năm (tùy 市). Đây là phần CHỦ YẾU được giảm bởi 7割/5割/2割軽減. Trên 通知書 ghi rõ "均等割: XXX,XXX円". Khác với 所得割 (theo thu nhập).',
      },
      {
        term: '所得割',
        reading: 'しょとくわり',
        meaningVi: 'phần phí tính theo thu nhập (% thu nhập năm trước)',
        noteVi: 'Phần tính theo "% × thu nhập chịu thuế năm trước". Tỉ lệ ~5-10% tùy 市. Người mới sang Nhật năm đầu thường = 0 vì chưa có thu nhập năm trước.',
      },
      {
        term: '7割軽減',
        reading: 'ななわりけいげん',
        meaningVi: 'giảm 70% phần 均等割 (nhóm thu nhập thấp nhất)',
        noteVi: 'Áp dụng tự động nếu thu nhập hộ ≤ 43万円 (令和8年度). KHÔNG cần nộp đơn riêng, NHƯNG hộ phải đã khai báo thu nhập (kể cả thu nhập 0) trước 31/5 năm đó.',
      },
      {
        term: '非自発的失業者の国保軽減',
        reading: 'ひじはつてきしつぎょうしゃのこくほけいげん',
        meaningVi: 'giảm phí 国保 đặc biệt khi mất việc không tự nguyện',
        noteVi: 'Coi thu nhập lương năm trước CHỈ TÍNH 30% (giảm mạnh 所得割). Điều kiện: dưới 65 tuổi + mã 離職理由 trên 雇用保険受給資格者証 thuộc nhóm 11/12/21/22/23/31/32/33/34. Áp dụng từ hôm sau nghỉ → hết năm tài khóa tiếp theo.',
      },
      {
        term: '離職理由コード',
        reading: 'りしょくりゆうコード',
        meaningVi: 'mã lý do nghỉ việc (trên 雇用保険受給資格者証)',
        noteVi: 'In ở mặt trước hoặc dưới sổ 受給資格者証. Mã 11 = 解雇 (sa thải), 12 = 重責解雇, 21 = 倒産 (công ty phá sản), 22 = 解雇 (期間満了, hợp đồng hết hạn), 23 = 雇い止め, 31-34 = 自己都合 nhưng có lý do bất khả kháng (パワハラ, セクハラ, 介護, 病気…). Đây là mã QUYẾT ĐỊNH bạn có được giảm hay không.',
      },
      {
        term: '雇用保険受給資格者証',
        reading: 'こようほけんじゅきゅうしかくしゃしょう',
        meaningVi: 'sổ chứng nhận được nhận bảo hiểm thất nghiệp',
        noteVi: 'Nhận tại ハローワーク sau khi đăng ký 雇用保険 + dự lớp giới thiệu. Vừa là giấy thông hành nhận tiền 失業手当, vừa là tài liệu BẮT BUỘC để xin giảm 国保. GIỮ KỸ — mất thì xin cấp lại ở ハローワーク (mất 1-2 tuần).',
      },
      {
        term: '住民税申告',
        reading: 'じゅうみんぜいしんこく',
        meaningVi: 'khai báo 住民税 ở 市役所 (kể cả khi thu nhập 0)',
        noteVi: 'Bước nền tảng nhưng nhiều người bỏ qua. Nếu công ty đã 年末調整 + nộp 給与支払報告書 sang 市役所 → tự động có. Nhưng: thất nghiệp / sinh viên / không đi làm phải tự đến 市役所 trước 31/5 khai "0円申告". KHÔNG khai = hệ thống không biết thu nhập = KHÔNG được 軽減.',
      },
    ],
    officialLinks: [
      { label: '国民健康保険の保険料・保険税について — 厚生労働省', url: 'https://www.mhlw.go.jp/stf/newpage_21517.html' },
      { label: '非自発的失業者の国保軽減 — 渋谷区（例）', url: 'https://www.city.shibuya.tokyo.jp/kurashi/kokuho/kenkohokenryo/hokenryo_hijihatsu.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra bạn có thuộc diện giảm tự động không',
        description: 'Nhà nước tự động giảm phần **均等割** (cố định theo đầu người) nếu thu nhập cả hộ gia đình thấp. Ngưỡng **令和8年度** (từ 4/2026):\n\n| Mức giảm | Điều kiện thu nhập hộ gia đình |\n|---|---|\n| **7割減** (giảm 70%) | ≤ 43万円 (*) |\n| **5割減** (giảm 50%) | ≤ 43万円 + **31万円 × số người tham gia 国保** (*) |\n| **2割減** (giảm 20%) | ≤ 43万円 + **57万円 × số người tham gia 国保** (*) |\n\n(*) Cộng thêm 10万円 nếu trong hộ có ≥2 người đi làm có lương (給与所得者等).\n\n⚠️ Đây là thu nhập theo nghĩa "所得" sau các khoản khấu trừ, không phải tổng tiền nhận — người không có thu nhập tính là 0, không phải "thiếu dữ liệu". Phải khai báo thu nhập 0 mới được tính.',
        documents: ['Thông báo 国保 có ghi mức phí hiện tại', 'Giấy khai báo thu nhập hoặc xác nhận thu nhập 0'],
        image: require('../../../../../assets/content/daily-life/ag_kokuho-reduction_s1.jpg'),
        imageCaption: '国民健康保険料通知書 - kiểm tra mức phí và phần giảm tự động nếu thu nhập thấp',
        tip: 'Nếu bạn là người duy nhất trong hộ, tham gia 国保 một mình không có thu nhập → Thu nhập hộ = 0 ≤ 43万円 → thuộc diện 7割減. Nhưng cần đã khai báo thu nhập 0 với municipal office.',
      },
      {
        step: 2,
        title: 'Nếu vừa mất việc không tự nguyện — xin giảm phí đặc biệt',
        description: 'Chương trình **非自発的失業者の国保軽減** (giảm phí đặc biệt khi thất nghiệp không tự nguyện):\n\n**Điều kiện:**\n- Thuộc 国民健康保険\n- Dưới 65 tuổi\n- Có 雇用保険受給資格者証 với mã 離職理由 thuộc nhóm: 11, 12, 21, 22, 23, 31, 32, 33, 34 (bị sa thải, hợp đồng không gia hạn, công ty phá sản...)\n\n**Cách giảm:** Municipal office tính lại phí bằng cách coi **thu nhập làm lương năm trước chỉ tính 30%** (phần còn lại 70% bị bỏ qua). Giảm đáng kể phần 所得割.\n\n**Thời hạn:** Áp dụng từ ngày sau ngày nghỉ việc đến hết năm tài khóa tiếp theo. Phải nộp trong vòng 1 năm từ ngày nghỉ.\n\n**Hồ sơ:**\n| Giấy tờ | Ghi chú |\n|---|---|\n| 雇用保険受給資格者証 | Bản gốc + bản sao, xác nhận mã 離職理由 |\n| 在留カード | Bản gốc |\n| 国民健康保険証 | Thẻ bảo hiểm hiện tại |\n| My Number Card hoặc giấy tờ tùy thân | |\n\nForm **nhận tại quầy** municipal office — không có form quốc gia để tải trước.',
        documents: ['雇用保険受給資格者証 (bản gốc)', '在留カード', '国民健康保険証'],
        image: require('../../../../../assets/content/daily-life/ag_kokuho-reduction_s2.jpg'),
        imageCaption: '雇用保険受給資格者証 - mã 離職理由 dùng để xin giảm phí 国保 khi mất việc không tự nguyện',
        tip: 'Mã 離職理由 in trên 雇用保険受給資格者証. Các mã 11 (会社都合解雇), 23 (雇い止め), 33 (上司のパワハラ) v.v. đều thuộc diện. Nếu không rõ mã của mình, hỏi nhân viên quầy.',
      },
      {
        step: 3,
        title: 'Nếu gặp khó khăn tài chính đặc biệt — xin giảm/miễn theo hoàn cảnh',
        description: 'Ngoài 2 chương trình trên, nhiều municipal office có chương trình **減免** (giảm/miễn) riêng theo hoàn cảnh khó khăn cụ thể:\n\n- Thiên tai, hỏa hoạn ảnh hưởng tài sản\n- Thu nhập giảm đột ngột do tai nạn, bệnh tật\n- Khó khăn kinh tế khác theo quyết định của municipality\n\nCác chương trình này **không chuẩn hóa toàn quốc** — tên, điều kiện và mức giảm khác nhau mỗi nơi. Hỏi trực tiếp quầy 保険年金課 để biết municipality của bạn có chương trình nào phù hợp.',
        documents: [],
        tip: 'Nếu đang khó khăn nhưng không chắc có đủ điều kiện không, cứ đến quầy hỏi — nhân viên sẽ tự kiểm tra và tư vấn phương án phù hợp nhất cho hoàn cảnh của bạn.',
      },
      {
        step: 4,
        title: 'Khai báo thu nhập đúng hạn — bước nền tảng',
        description: 'Cả giảm tự động và nhiều chương trình giảm khác đều dựa trên **dữ liệu thu nhập** mà municipal office có. Nếu bạn không khai báo, hệ thống không biết và không giảm.\n\n**Cách khai:**\n- Nếu đi làm: công ty khấu trừ thuế và báo cáo cho cơ quan thuế — dữ liệu tự động có.\n- Nếu không đi làm / thu nhập 0: phải tự đến khai báo 住民税の申告 trước 31/5 hàng năm tại municipal office.\n- Nếu đã nộp 確定申告: dữ liệu tự động có.\n\n⚠️ Không khai báo = hệ thống coi bạn có thu nhập không xác định → không được giảm tự động.',
        documents: ['源泉徴収票 (nếu có)', 'Hoặc tự khai báo thu nhập 0 tại municipal office'],
        tip: 'Ngay cả khi không có thu nhập, đến khai báo 住民税 (0円申告) trước 31/5 là bước quan trọng để được hưởng giảm 国保 và 住民税 đúng mức.',
      },
    ],
  };

export default kokuhoReduction;
