import type { AdminGuide } from '../../../../types/content';

const nurseryKindergartenGuide: AdminGuide = {
    id: 'nursery-kindergarten-guide',
    category: 'daily-law',
    lastVerified: '2026-05-16',
    priority: 'high',
    title: 'Nhà trẻ, mẫu giáo và chỗ gửi trẻ ở Nhật',
    titleJp: '保育園・幼稚園・こども園の選び方と申込み',
    icon: 'school',
    color: '#16A085',
    description: 'Guide thực tế về hoikuen, youchien, kodomoen, taikuen, giấy tờ đi làm của phụ huynh, miễn giảm học phí và thay đổi đáng chú ý từ năm tài khóa 2026.',
    heroImage: require('../../../../../assets/content/daily-life/ag_nursery_hero.jpg'),
    heroImageCaption: 'Tìm hiểu hoikuen, youchien và hệ thống giữ trẻ tại Nhật',
    searchKeywords: [
      'nhà trẻ',
      'mẫu giáo',
      'gửi trẻ',
      '保育園',
      'hoikuen',
      '幼稚園',
      'youchien',
      'こども園',
      'kodomoen',
      'nintei kodomoen',
      '認可保育園',
      'ninka hoikuen',
      '認可外',
      'ninkagai',
      '就労証明書',
      'shuurou shoumeisho',
      'giấy chứng nhận đi làm',
      '保育の必要性',
      'hoiku no hitsuyousei',
      '利用調整',
      'riyou chousei',
      '待機児童',
      'taikuen',
      'đăng ký nhà trẻ',
      'miễn học phí',
      '無償化',
      'mushouka',
      'こども誰でも通園制度',
      'daredemo tsuuen',
      'nursery in Japan',
    ],
    legalScope: {
      jurisdiction: 'mixed',
      jurisdictionNote:
        '子ども・子育て支援法 (Child and Childcare Support Act) + 児童福祉法 §39 do こども家庭庁 quản lý cấp quốc gia. 認可保育所 do 市町村 vận hành thực tế qua 利用調整 (xếp hạng điểm 保育の必要性) — không phải "ai nộp trước được nhận trước". 幼稚園 thuộc 学校教育法 (文部科学省). 幼児教育・保育の無償化 (miễn học phí 3–5 tuổi từ 10/2019) áp dụng cho cơ sở thuộc 制度 — KHÔNG đồng nghĩa miễn 100% chi phí (tiền ăn, đồng phục, 延長保育 vẫn còn). こども誰でも通園制度 triển khai toàn quốc từ 年度2026 — chế độ mới, không thay thế hoikuen dài hạn.',
      sourceVerifiedAt: '2026-05-16',
      nextReviewAt: '2026-12-31',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Bị từ chối hoikuen nhiều lần dù có 就労証明書 → hỏi 市役所 cách tính điểm 利用調整 + xin văn bản giải thích.',
        'Cha/mẹ làm part-time / 自営業 / chưa có hợp đồng cố định → hỏi city hall cách chứng minh thay thế 就労証明書 (bảng giờ làm, sổ thu nhập).',
        'Con cần hỗ trợ đặc biệt (障害, allergy nặng, chậm phát triển) → hỏi 保健センター + 児童発達支援センター trước khi nộp hoikuen.',
        'Tranh chấp với cơ sở 認可外 về phí + hoàn tiền → 消費生活センター 188 hoặc 国民生活センター.',
      ],
    },
    quickAction: {
      deadline:
        'Đợt nhập học tháng 4 (chính): hồ sơ thường mở từ 10–11 năm trước, hạn cuối thường tháng 11–12. Đợt giữa năm: theo lịch riêng từng 市. Quá hạn = đợi đợt sau hoặc xếp 待機児童.',
      office:
        '市役所 / 区役所 — phòng 保育課 / 子育て支援課 / こども政策課 (tên tùy 市). Một số 市 có online qua マイナポータル.',
      doNow: [
        'Xác định loại hình cần: hoikuen (cả ngày, cần 保育の必要性) hay youchien (3+ tuổi, học giáo dục).',
        'Hỏi 市役所 lịch tuyển + danh sách trường trong khu (一覧表).',
        'Đặt lịch tham quan 3–5 trường tốp đầu (見学) — ghi chú giờ nhận-trả + bữa ăn + ngày nghỉ.',
        'Xin 就労証明書 từ công ty (mẫu 市 phát hoặc mẫu chuẩn こども家庭庁). Cha + mẹ đều xin nếu cả hai đi làm.',
        'Liệt kê 5–10 nguyện vọng theo thứ tự (đừng chỉ 1–2 trường — rủi ro 待機).',
        'Nộp hồ sơ tại 市役所 trước hạn — kèm 就労証明書 cả 2 cha/mẹ + giấy tờ hộ gia đình.',
        'Đợi 利用調整 → kết quả 2–3 tháng sau (thường tháng 1–2 cho đợt tháng 4).',
      ],
      bring: [
        '入所申込書 (form do 市役所 phát)',
        '就労証明書 của cha + mẹ (cả hai)',
        '在留カード + マイナンバー của cha/mẹ + con',
        '健康保険証 của cha/mẹ + con',
        'Giấy xác nhận thu nhập (源泉徴収票 / 課税証明書)',
        '母子健康手帳 (lịch tiêm chủng + sức khỏe của con)',
        'Sổ ngân hàng (cho phí ăn / xe nếu có)',
        'Giấy tờ hoàn cảnh đặc biệt (single parent / con cần hỗ trợ đặc biệt) nếu có',
      ],
      ifLate:
        'Quá hạn đợt chính: chuyển sang đợt giữa năm (空き = chỗ trống) hoặc xếp 待機児童リスト. Thực tế ở khu đông (Tokyo 23 区, Saitama, Kanagawa) có thể đợi 6–18 tháng. Phương án tạm: 認可外保育園 / 一時保育 (giữ trẻ ngày) / べビーシッター — tốn hơn nhưng có chỗ ngay. Quay lại nộp lần tiếp theo + nâng điểm 保育の必要性 (vd: xác nhận quay lại làm full-time).',
      officialSourceLabels: ['こども家庭庁', '文部科学省'],
    },
    keyTerms: [
      {
        term: '保育園',
        reading: 'ほいくえん',
        meaningVi: 'nhà trẻ (cả ngày, cho gia đình có 保育の必要性)',
        noteVi: 'Còn gọi 保育所. Khác 幼稚園 (chỉ giáo dục, không yêu cầu cha mẹ đi làm). 保育園 chia 2 loại: 認可 (vào qua 市役所 với 利用調整) và 認可外 (nộp thẳng trường, đắt hơn nhưng dễ vào).',
      },
      {
        term: '保育の必要性',
        reading: 'ほいくのひつようせい',
        meaningVi: '"điều kiện cần phải gửi trẻ"',
        noteVi: 'Logic cốt lõi để vào 認可保育園. Lý do được chấp nhận: đi làm (≥48 giờ/tháng) / tìm việc / mang thai-sau sinh / bệnh tật / chăm người nhà / học. Mỗi lý do quy ra "điểm" — càng cao càng ưu tiên trong 利用調整.',
      },
      {
        term: '就労証明書',
        reading: 'しゅうろうしょうめいしょ',
        meaningVi: 'giấy chứng nhận đi làm (do công ty cấp)',
        noteVi: 'Giấy quan trọng nhất cho hồ sơ 認可保育園. Ghi rõ: giờ làm/tuần, loại hợp đồng, lương, ngày bắt đầu. こども家庭庁 có mẫu chuẩn nhưng 市 có thể yêu cầu mẫu riêng. Tự doanh / part-time: hỏi city hall cách chứng minh thay thế (bảng giờ, sổ thu nhập, hóa đơn).',
      },
      {
        term: '利用調整',
        reading: 'りようちょうせい',
        meaningVi: '"điều chỉnh sử dụng" — quá trình xếp hạng điểm để phân chỗ',
        noteVi: 'Không phải "ai nộp trước được nhận trước". 市役所 chấm điểm hồ sơ (giờ làm cha/mẹ, hoàn cảnh đặc biệt, anh chị em đang học) → xếp hạng → phân chỗ. Quyết định thường ra tháng 1–2 cho đợt tháng 4.',
      },
      {
        term: '待機児童',
        reading: 'たいきじどう',
        meaningVi: 'trẻ chờ chỗ (chưa được phân vào trường nào)',
        noteVi: 'Không phải "loại trường" — là tình trạng. Sau 利用調整 chưa có chỗ → vào danh sách 待機リスト, chờ đợt sau hoặc 空き giữa năm. Khu đông có thể chờ 6–18 tháng. Trong lúc chờ thường dùng 認可外 / 一時保育.',
      },
    ],
    counterPhrases: [
      {
        jp: '保育園の申込みをしたいです。',
        romaji: 'Hoikuen no moushikomi o shitai desu.',
        vn: 'Tôi muốn nộp hồ sơ vào nhà trẻ.',
        note: 'Câu mở đầu tại quầy 保育課 / 子育て支援課.',
      },
      {
        jp: '就労証明書の書式をください。',
        romaji: 'Shuurou shoumeisho no shoshiki o kudasai.',
        vn: 'Cho tôi mẫu giấy chứng nhận đi làm.',
        note: 'Lấy mẫu để đưa công ty điền. Đa số 市 phát mẫu riêng.',
      },
      {
        jp: '見学の予約をしたいです。',
        romaji: 'Kengaku no yoyaku o shitai desu.',
        vn: 'Tôi muốn đặt lịch tham quan trường.',
        note: 'Gọi thẳng trường để đặt lịch — thường miễn phí + nên đi trước khi nộp hồ sơ.',
      },
      {
        jp: '入れる保育園の一覧はありますか。',
        romaji: 'Haireru hoikuen no ichiran wa arimasu ka.',
        vn: 'Có danh sách các nhà trẻ có thể nộp không?',
        note: '市役所 thường có pamphlet liệt kê tất cả trường trong khu.',
      },
      {
        jp: '結果はいつわかりますか。',
        romaji: 'Kekka wa itsu wakarimasu ka.',
        vn: 'Khi nào có kết quả?',
        note: 'Hỏi sau khi nộp hồ sơ — biết để lên kế hoạch quay lại làm.',
      },
    ],
    whoIsThisFor: [
      'Gia đình có con nhỏ đang cần gửi trẻ để đi làm hoặc chuẩn bị cho con vào mẫu giáo.',
      'Người chưa phân biệt được hoikuen, youchien, nintei kodomoen và cơ sở ngoài hệ thống công nhận.',
      'Gia đình đang lo cảnh đợi chỗ, thiếu giấy tờ công việc hoặc bị từ chối vì không đủ điều kiện 保育の必要性.',
    ],
    whenToDo: [
      'Trước đợt nhận hồ sơ chính của địa phương, thường nhiều tháng trước tháng 4 nhập học.',
      'Ngay khi gia đình biết sẽ quay lại làm việc, chuyển việc, hết nghỉ sinh hoặc cần gửi trẻ dài hạn.',
      'Nếu con đã đến tuổi mẫu giáo nhưng gia đình chưa cần gửi cả ngày, nên tìm hiểu sớm sự khác nhau giữa youchien và hoikuen thay vì chỉ hỏi chung “trường mầm non”.',
    ],
    whereToDo: [
      'City hall / ward office: hồ sơ vào 認可保育所, 認定こども園 và đánh giá 保育の必要性.',
      'Trực tiếp với trường hoặc hệ thống hướng dẫn của địa phương: lịch open day, tham quan, xếp nguyện vọng và thông báo kết quả.',
      'Doanh nghiệp nơi cha/mẹ làm việc: xin 就労証明書 theo mẫu địa phương hoặc mẫu chuẩn do こども家庭庁 công bố.',
      'Riêng 幼稚園 hoặc một số cơ sở ngoài hệ thống công nhận: quy trình có thể đi thẳng với trường, nhưng vẫn phải kiểm tra điều kiện hỗ trợ học phí và 預かり保育.',
    ],
    estimatedTime: 'Thời gian chuẩn bị thường dài hơn người mới sang Nhật nghĩ. Thực tế nhiều gia đình phải bắt đầu từ khâu tham quan, xin giấy xác nhận việc làm, nộp hồ sơ, chờ利用調整 rồi mới biết có chỗ hay không. Nếu nhắm kỳ nhập học tháng 4, nhiều địa phương mở hồ sơ từ mùa thu năm trước.',
    fees: [
      'Theo こども家庭庁, từ 01/10/2019, học phí đối với trẻ 3-5 tuổi tại hoikuen, youchien, nintei kodomoen thuộc phạm vi áp dụng đã được miễn. Trẻ 0-2 tuổi chỉ được miễn nếu hộ thuộc diện住民税非課税.',
      'Miễn học phí không đồng nghĩa miễn toàn bộ chi phí. Nhiều nơi vẫn còn tiền ăn, đồ dùng, đồng phục, xe đưa đón, hoạt động ngoại khóa hoặc 延長保育.',
      '預かり保育 ở 幼稚園 hoặc 認可外保育 muốn được hỗ trợ cũng thường cần 保育の必要性の認定 theo điều kiện của địa phương.',
      'Chi phí cơ sở ngoài hệ thống công nhận và mức hỗ trợ thực nhận có thể chênh lớn tùy địa phương và loại cơ sở.',
    ],
    documentsChecklist: [
      { label: 'Xác định loại hình muốn nộp: hoikuen, youchien, kodomoen hay cơ sở ngoài hệ thống', required: true },
      { label: 'Giấy tờ chứng minh 保育の必要性', required: true, note: 'Ví dụ: đi làm, tìm việc, mang thai/sau sinh, bệnh tật, chăm người thân... theo tiêu chí của địa phương.' },
      { label: '就労証明書 của cha/mẹ đi làm', required: false, note: 'Thường là giấy cực quan trọng với hồ sơ hoikuen và利用調整.' },
      { label: 'Giấy tờ cư trú, My Number, thông tin hộ gia đình', required: true },
      { label: 'Danh sách nguyện vọng và kết quả tham quan trường', required: false },
      { label: 'Giấy tờ về thu nhập/thuế nếu địa phương yêu cầu để tính phí hoặc hỗ trợ', required: false },
      { label: 'Giấy tờ đặc biệt nếu gia đình có hoàn cảnh riêng', required: false, note: 'Ví dụ: single parent, con cần hỗ trợ đặc biệt, cha/mẹ đang nghỉ sinh, đang tìm việc.' },
    ],
    commonMistakes: [
      'Gọi tất cả là “trường mầm non” nên nộp sai chỗ: hoikuen và youchien có logic rất khác nhau.',
      'Nghĩ cứ có con nhỏ là đương nhiên vào được hoikuen, trong khi hệ thống này gắn với 保育の必要性 và利用調整 của địa phương.',
      'Chỉ chọn 1-2 nguyện vọng vì thích trường đẹp, rồi rơi vào cảnh không có chỗ.',
      'Nộp muộn 就労証明書 hoặc giấy tờ đi làm không khớp thực tế.',
      'Hiểu nhầm “miễn học phí” là không còn bất kỳ khoản nào phải đóng.',
      'Không biết từ năm tài khóa 2026 có `こども誰でも通園制度`, rồi nhầm nó với hoikuen chính thức cả ngày.',
    ],
    faq: [
      {
        question: 'Hoikuen và youchien khác nhau ở điểm nào dễ hiểu nhất?',
        answer: 'Hoikuen chủ yếu là cơ sở bảo育 cho gia đình có 保育の必要性 như đi làm, ốm đau, hoàn cảnh chăm sóc; còn youchien là trường học cho trẻ từ 3 tuổi đến trước tiểu học, không mặc định đòi lý do đi làm giống hoikuen. Đây là nhầm lẫn lớn nhất của nhiều gia đình mới sang Nhật.',
      },
      {
        question: 'Taikuen là gì?',
        answer: 'Taikuen thường được dùng để chỉ trẻ đang chờ chỗ vào cơ sở保育 dù gia đình muốn sử dụng. Đây không phải một “loại trường”, mà là tình trạng chưa được sắp chỗ sau利用調整.',
      },
      {
        question: 'Tôi đang nghỉ sinh hoặc sắp quay lại làm, có thể nộp hoikuen không?',
        answer: 'Có thể, nhưng điều kiện và cách chấm điểm phụ thuộc địa phương. Nhiều nơi xem xét thời điểm quay lại làm, giấy xác nhận của công ty và kế hoạch sử dụng dịch vụ保育. Đừng chờ tới sát ngày đi làm mới hỏi city hall.',
      },
      {
        question: 'Miễn học phí 3-5 tuổi có áp dụng cho mọi nơi không?',
        answer: 'Không theo nghĩa tuyệt đối. こども家庭庁 nêu nguyên tắc miễn đối với các cơ sở thuộc phạm vi制度; nhưng tiền ăn, đồng phục, đưa đón, giờ kéo dài và nhiều chi phí phụ khác vẫn có thể còn. Với 預かり保育 hay 認可外, điều kiện hỗ trợ còn phụ thuộc 保育の必要性 và mức trần hỗ trợ.',
      },
      {
        question: 'こども誰でも通園制度 năm 2026 có thay thế hoikuen không?',
        answer: 'Không. こども家庭庁 nêu đây là chế độ mới triển khai toàn quốc từ năm tài khóa 2026 cho phép mọi gia đình sử dụng một lượng giờ nhất định mà không cần điều kiện đi làm. Nó không phải bản thay thế cho hoikuen dài hạn cả ngày theo hệ thống利用調整 thông thường.',
      },
    ],
    officialLinks: [
      { label: '保育｜こども家庭庁', url: 'https://www.cfa.go.jp/policies/hoiku/' },
      { label: '子ども・子育て支援制度｜こども家庭庁', url: 'https://www.cfa.go.jp/policies/kokoseido' },
      { label: '幼児教育・保育の無償化｜こども家庭庁', url: 'https://www.cfa.go.jp/policies/kokoseido/mushouka/' },
      { label: 'こども誰でも通園制度について｜こども家庭庁', url: 'https://www.cfa.go.jp/policies/hoiku/daredemo-tsuen' },
      { label: '幼稚園について教えて！｜文部科学省', url: 'https://www.mext.go.jp/kids/find/kyoiku/mext_0001.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Phân biệt đúng loại hình trước khi nộp',
        description: 'Đầu tiên hãy tách rõ 4 nhóm: 認可保育所/hoikuen, 幼稚園/youchien, 認定こども園 và cơ sở ngoài hệ thống công nhận. Nếu nhầm từ đầu, bạn sẽ đi sai đường hồ sơ, sai kỳ tuyển và sai kỳ vọng về thời gian giữ trẻ.',
        documents: [
          'Danh sách cơ sở trong địa phương',
          'Độ tuổi con hiện tại',
          'Nhu cầu thực tế: gửi cả ngày để đi làm hay chỉ cần môi trường giáo dục bán thời gian',
        ],
        tip: 'Đừng hỏi “trường nào nhận con tôi” trước khi trả lời được “tôi cần loại hình nào”.',
      },
      {
        step: 2,
        title: 'Xác định có cần 保育の必要性 hay không',
        description: 'Với hoikuen và nhiều hỗ trợ liên quan, gia đình thường phải chứng minh 保育の必要性 như đi làm, tìm việc, bệnh tật, khuyết tật, mang thai/sau sinh hoặc chăm người thân. Đây là logic cốt lõi quyết định bạn có vào vòng利用調整 hay không.',
        documents: [
          'Tình trạng việc làm của cha mẹ',
          'Lịch đi làm hoặc kế hoạch quay lại làm',
          'Giấy tờ hoàn cảnh đặc biệt nếu có',
        ],
        tip: 'Mỗi city hall có hướng dẫn cụ thể riêng. Đừng dùng checklist của thành phố khác rồi nghĩ sẽ giống hoàn toàn.',
      },
      {
        step: 3,
        title: 'Chuẩn bị 就労証明書 và giấy tờ hộ gia đình',
        description: 'Một trong những giấy dễ trễ nhất là 就労証明書. こども家庭庁 có mẫu chuẩn, nhưng địa phương hoặc trường có thể yêu cầu cách nộp riêng. Gia đình có 2 người đi làm nên chuẩn bị giấy của cả hai càng sớm càng tốt.',
        documents: [
          '就労証明書 của cha/mẹ',
          'Thẻ cư trú, My Number, thông tin địa chỉ',
          'Giấy tờ thuế hoặc thu nhập nếu địa phương yêu cầu',
        ],
        tip: 'Nếu mới đổi việc, làm part-time, tự doanh hoặc chưa có hợp đồng ổn định, hãy hỏi city hall ngay cách chứng minh thay thế. Đây là chỗ hồ sơ người nước ngoài hay bị vướng.',
        image: require('../../../../../assets/content/daily-life/ag_nursery_s3.jpg'),
        imageCaption: '就労証明書 do công ty cấp — xác nhận giờ làm và loại hợp đồng cho hồ sơ gửi trẻ',
      },
      {
        step: 4,
        title: 'Đi tham quan và nộp nhiều nguyện vọng thực tế',
        description: 'Trong môi trường có cạnh tranh chỗ, việc chỉ chọn một trường “đẹp, gần nhà” là rất rủi ro. Nhiều gia đình phải cân bằng giữa khoảng cách, giờ nhận-trả, bữa ăn, ngày nghỉ, hỗ trợ tiếng Nhật, quy định khi trẻ ốm và khả năng đỗ chỗ.',
        documents: [
          'Danh sách trường muốn nộp theo thứ tự',
          'Ghi chú sau khi tham quan',
          'Kế hoạch đi làm thực tế của gia đình',
        ],
        tip: 'Một quyết định thực tế thường tốt hơn một danh sách nguyện vọng quá lý tưởng rồi rơi vào taikuen.',
        image: require('../../../../../assets/content/daily-life/ag_nursery_s4.jpg'),
        imageCaption: 'Tham quan 保育園 và nộp nhiều nguyện vọng để tăng khả năng được nhận',
      },
      {
        step: 5,
        title: 'Hiểu đúng miễn học phí và chi phí còn lại',
        description: 'Dù chế độ miễn học phí cho trẻ 3-5 tuổi đã áp dụng từ lâu, phụ huynh vẫn thường bất ngờ vì còn nhiều khoản phát sinh. Hãy hỏi thẳng trường hoặc city hall về tiền ăn, đồng phục, xe, giờ kéo dài, đồ dùng và phí sự kiện.',
        documents: [
          'Bảng chi phí của trường',
          'Thông tin hỗ trợ miễn giảm của địa phương',
          'Giấy công nhận 保育の必要性 nếu áp dụng',
        ],
        tip: 'Đây là chỗ rất nên hỏi bằng văn bản hoặc email để tránh hiểu sai sau khi nhập học.',
      },
      {
        step: 6,
        title: 'Theo dõi thay đổi năm tài khóa 2026',
        description: 'Từ năm tài khóa 2026, `こども誰でも通園制度` được triển khai trên toàn quốc như một chế độ mới cho mọi gia đình với số giờ giới hạn, không phụ thuộc điều kiện đi làm. Đây là hướng hỗ trợ linh hoạt nhưng không thay thế nhu cầu gửi trẻ dài hạn kiểu hoikuen.',
        documents: [
          'Thông báo của city hall về chế độ mới',
          'Điều kiện số giờ, cách đặt chỗ và loại cơ sở tham gia tại địa phương',
        ],
        tip: 'Nếu gia đình chưa cần gửi trẻ cả ngày nhưng muốn con có chỗ sinh hoạt định kỳ, đây là điểm mới của 2026 rất đáng theo dõi.',
      },
    ],
  };

export default nurseryKindergartenGuide;
