import type { AdminGuide } from '../../../../types/content';

const overstayingIllegalStayProcedures: AdminGuide = {
    id: 'overstaying-illegal-stay-procedures',
    category: 'immigration',
    lastVerified: '2026-05-04',
    priority: 'normal',
    title: 'Overstay / Không hợp pháp — cách phát hiện và xử lý ngay',
    titleJp: 'オーバーステイ（不法滞在）への対応と救済手続き',
    icon: 'warning',
    color: '#E74C3C',
    description: 'Khi visa đã hết hạn mà chưa rời Nhật hoặc chưa được gia hạn = 不法残留 theo 入管法 §70. KHÔNG có thời gian "đệm" tự động. Hậu quả nghiêm trọng (退去強制 + cấm tái nhập 5-10 năm hoặc hơn). Có một số thủ tục Nyukan THƯỜNG xét đến tùy hoàn cảnh — nhưng KHÔNG có gì đảm bảo, KHÔNG có "loophole", và xử lý chậm thường làm tình hình tệ hơn. Tham vấn 弁護士 / 行政書士 / 法テラス CÀNG SỚM CÀNG TỐT.',
    searchKeywords: [
      'overstay',
      'visa hết hạn',
      'ở quá hạn visa',
      '不法残留',
      'fuhou zanryuu',
      'illegal stay Japan',
      'visa quá hạn',
      'overstay Japan',
      '退去強制',
      'taikyo kyousei',
      'deportation',
      '出国命令',
      'shukkoku meirei',
      'departure order',
      '在留特別許可',
      'zairyuu tokubetsu kyoka',
      'special permission to stay',
      '上陸拒否期間',
      'joriku kyohi kikan',
      'entry ban',
      'cấm tái nhập 5 năm',
      'cấm tái nhập 10 năm',
      'tự thú overstay',
      'voluntary surrender',
      'không hợp pháp ở Nhật',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: '不法残留 (overstay) là vi phạm 入管法 §70 — tội hình sự, phạt tới 3 năm tù hoặc 300万円 (hoặc cả hai), kèm 退去強制 + 上陸拒否期間 (cấm tái nhập). 出国命令制度 (入管法 §24-3) áp dụng khi người vi phạm TỰ NGUYỆN ĐẾN báo cáo + thoả mãn các điều kiện cụ thể của 入管法 §24-3 (vd: không có tiền án nặng khác, hợp tác đầy đủ với Nyukan, có khả năng rời nước được) — Nyukan đánh giá từng trường hợp. 在留特別許可 (入管法 §50) là quyền của Bộ trưởng Tư pháp cấp đặc biệt — RẤT HIẾM được áp dụng, không phải "lựa chọn". KHÔNG có "loophole" trong luật. Mọi trường hợp 不法残留 cần tham vấn 弁護士 / 行政書士 CHUYÊN 入管 trước khi đến Nyukan để đảm bảo bảo vệ quyền tốt nhất có thể.',
      sourceVerifiedAt: '2026-05-04',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'BẤT KỲ trường hợp 不法残留 nào — luôn tham vấn 弁護士 / 行政書士 chuyên 入管 TRƯỚC khi đến Nyukan. Khả năng được áp dụng 出国命令 vs bị 退去強制 phụ thuộc nhiều yếu tố cá nhân — KHÔNG nên tự suy đoán.',
        'Có yếu tố nhân đạo (kết hôn với người Nhật, có con Nhật, đang điều trị bệnh nặng) → cần 弁護士 đánh giá khả năng 在留特別許可. KHÔNG tự xin — quá trình phức tạp + tỷ lệ cấp rất thấp.',
        'Có tiền án / tiền sử vi phạm khác (lao động trái phép, làm giả giấy tờ, tham gia 風俗営業) → tình hình phức tạp, BẮT BUỘC 弁護士 trước khi đến Nyukan.',
        'Tài chính khó khăn → liên hệ 法テラス 0570-078374 (Japan Legal Support Center) cho hỗ trợ pháp lý miễn phí hoặc trả góp.',
        'Đang nhập viện / điều trị bệnh nặng khiến không kịp gia hạn → tham vấn 弁護士 về phương án 救済措置 + xem guide visa-emergency-medical-disaster-extension; mang đầy đủ 診断書 + giấy nhập viện.',
        'Bị áp lực từ broker / "agent" hứa "lo được visa khi đã overstay" → CẢNH GIÁC — đa số là lừa đảo. Liên hệ Đại sứ quán Việt Nam / 法テラス / FRESC (外国人在留支援センター) để xác minh.',
      ],
    },
    quickAction: {
      deadline: 'KHÔNG có deadline cho phép trì hoãn — mỗi ngày overstay làm tình hình xấu hơn. Tham vấn 弁護士 / 行政書士 NGAY khi phát hiện visa đã hết hạn (kể cả chỉ 1 ngày). KHÔNG tự đến Nyukan mà chưa tham vấn nếu hoàn cảnh phức tạp.',
      office: 'Tham vấn pháp lý TRƯỚC: 法テラス 0570-078374 / 弁護士会 / 行政書士会 từng tỉnh / FRESC (外国人在留支援センター) 0570-011000. Sau khi có hướng dẫn từ luật sư: Nyukan có thẩm quyền theo nơi cư trú. Đại sứ quán Việt Nam tại Tokyo / Lãnh sự Osaka / Fukuoka có thể giới thiệu luật sư biết tiếng Việt.',
      doNow: [
        'BƯỚC ĐẦU TIÊN: tham vấn 弁護士 / 行政書士 chuyên 入管, KHÔNG tự đi Nyukan. Trường hợp khẩn cấp có thể gọi 法テラス 0570-078374 ngay.',
        'DỪNG NGAY mọi hoạt động lao động — tiếp tục làm việc khi đã overstay = thêm tội 不法就労 + làm tình hình tệ hơn.',
        'Thu thập tài liệu: hộ chiếu, thẻ cư trú cũ (kể cả đã hết hạn), giấy tờ chứng minh hoàn cảnh (診断書 nếu bệnh, 罹災証明書 nếu thảm họa, 婚姻届受理証明書 nếu kết hôn người Nhật, giấy khai sinh nếu có con Nhật).',
        'KHÔNG trốn / đổi địa chỉ / thay đổi tên — bị phát hiện sau làm tình hình nghiêm trọng hơn nhiều.',
        'KHÔNG tin "broker" / "agent" hứa "lo được visa" — đa số là lừa đảo. Chỉ tin 弁護士 / 行政書士 có giấy phép chính thức.',
        'Theo hướng dẫn của luật sư: nếu được tư vấn đi Nyukan tự thú, đem đầy đủ tài liệu + người đại diện hợp pháp đi cùng.',
        'Lưu lại MỌI liên lạc với Nyukan / luật sư — văn bản, biên bản, ngày tháng.',
      ],
      bring: [
        'Hộ chiếu (kể cả khi đã hết hạn)',
        'Thẻ cư trú cũ (kể cả đã hết hạn)',
        'Số điện thoại 弁護士 / 行政書士 đã tham vấn (nếu có)',
        'Giấy tờ chứng minh hoàn cảnh (診断書 / 罹災証明書 / 婚姻届受理証明書 / giấy khai sinh con)',
        '理由書 viết ngắn gọn + trung thực (do luật sư hỗ trợ tốt hơn)',
        'Tiền mặt cho phí dịch vụ luật sư / phí Nyukan',
        'Số điện thoại Đại sứ quán Việt Nam Tokyo (03-3466-3311) / Lãnh sự Osaka',
      ],
      ifLate: 'Đã overstay nhiều tháng / nhiều năm mà chưa xử lý → KHÔNG có cách "tự xóa" lịch sử. Tham vấn 弁護士 NGAY — càng để lâu càng khó xử lý. Bị Nyukan bắt trước khi tự thú = khả năng được 出国命令 thay vì 退去強制 GIẢM mạnh. Hậu quả 退去強制: cấm tái nhập 5 năm (lần đầu) hoặc 10 năm (tái phạm hoặc tội nặng) hoặc vĩnh viễn (tội rất nghiêm trọng) theo 入管法 §5. KHÔNG có "lối thoát dễ" — chỉ có lựa chọn ít tệ hơn so với để Nyukan phát hiện.',
      officialSourceLabels: ['ISA — Overstay & Rescue Measure', '出国命令制度 — Deportation Order System', '在留特別許可 — Special Humanitarian Permission'],
    },
    whoIsThisFor: [
      'Người vừa phát hiện visa mình hết hạn rồi.',
      'Người nhập viện hoặc gặp sự cố nên quên gia hạn trong 2 tháng.',
      'Người muốn biết hậu quả và cách xử lý ngay để giảm thiệt hại.',
      'Người muốn hiểu quyền lợi và lựa chọn nếu bị bắt gặp.',
    ],
    whenToDo: [
      'Ngay khi phát hiện visa hết hạn — đừng chờ thêm ngày nào.',
      'Nếu nhập viện hoặc bệnh nặng: trong vòng 2 tháng từ ngày hết hạn, có thể xin biện pháp cứu trợ (救済措置).',
      'Nếu đã quá 2 tháng: hãy liên hệ ISA để hỏi xem có tùy chọn khác không.',
    ],
    whereToDo: [
      'ISA — cục công an nhập cảnh (出入国在留管理庁). Tìm cục gần nhất tại moj.go.jp.',
      'Gọi điện hoặc đến trực tiếp — nên đi trực tiếp để tìm hiểu tùy chọn.',
      'Không nên chờ sang ngày mai — hành động ngay hôm nay sẽ có lợi hơn.',
    ],
    estimatedTime: 'Nếu xin cứu trợ (救済措置): 1-4 tuần để xét duyệt (có thể được phép ở lại). Nếu tự ra nước ngoài qua 出国命令: ~1 tuần xử lý tại ISA, sau đó cấm nhập cảnh 1 năm.',
    commonMistakes: [
      'Chờ quá lâu mới tự khai báo — thay vì cấm nhập cảnh 1 năm, có thể bị 5 năm hoặc lâu hơn nếu bị bắt.',
      'Không biết có 救済措置 (rescue) nên vội tự rời Nhật mà không cần.',
      'Tiếp tục làm việc khi đã overstay — đây là vi phạm pháp luật thêm, bị phạt và xử lý nặng hơn.',
      'Che giấu tình trạng overstay từ bảo hiểm/ngân hàng — khi được phát hiện sẽ bị xử lý kép.',
      'Không hiểu sự khác biệt giữa 出国命令 (tự rời Nhật) và bị buộc rời — vội đi tự nguyện sai cách có thể mất lợi thế.',
    ],
    faq: [
      {
        question: 'Overstay 1 ngày cũng bị tính không?',
        answer: 'Đúng. Luật Nhật không có thời gian "đệm" — chỉ cần quá 1 ngày hết hạn = bất hợp pháp (不法滞在). Không có ngoại lệ trừ biện pháp cứu trợ (救済措置).',
      },
      {
        question: 'Biện pháp cứu trợ (救済措置) là gì?',
        answer: 'Là cơ chế cứu trợ: nếu bạn **quên** làm gia hạn lần cuối (最後の更新を忘れた) hoặc **nhập viện** khiến vượt quá hạn, trong vòng **2 tháng từ ngày hết hạn**, bạn có thể nộp đơn xin cứu trợ. ISA sẽ xem xét và có thể cấp phép ở lại hoặc gia hạn. Phải nộp trong 2 tháng — quá thời hạn này không được cứu trợ.',
      },
      {
        question: '出国命令 là gì? Có phải tốt không?',
        answer: '出国命令 (lệnh tự rời Nhật) là: nếu bạn **tự nguyện** ra nước ngoài sau khi bị overstay, ISA cho phép bạn rời Nhật một cách "tự nguyện" thay vì bị buộc đi. Khi đó, lệnh cấm nhập cảnh là 1 năm thay vì 5-10 năm (nếu bị bắt). Đây là lựa chọn tốt hơn nếu bạn phải rời Nhật.',
      },
      {
        question: 'Nếu overstay rồi bị bắt thì sao?',
        answer: 'Sẽ có: (1) cảnh báo / phạt tiền, (2) cấm nhập cảnh 5-10 năm hoặc lâu hơn, (3) bị buộc ra nước ngoài, (4) ghi vào hồ sơ pháp lý. Quá trình rất khó chịu và tốn kém. Vì vậy nên xử lý chủ động sớm.',
      },
      {
        question: 'Nếu quá 2 tháng rồi mới phát hiện thì sao?',
        answer: 'Liên hệ ISA ngay để hỏi. Biện pháp cứu trợ không áp dụng nữa, nhưng bạn vẫn có thể xin 出国命令 để rời Nhật tự nguyện với cấm nhập cảnh 1 năm. Tốt hơn là bị bắt rồi bị cấm 5-10 năm.',
      },
      {
        question: 'Tôi vừa phát hiện overstay hôm qua — bây giờ mới nộp rescue, có được không?',
        answer: 'Bạn vẫn có cơ hội vì mới phát hiện. Nộp ngay hôm nay (chưa quá 2 tháng từ ngày visa hết hạn), kèm bằng chứng tại sao quên (giấy xác nhận nhập viện, hóa đơn bệnh viện hoặc lý do chính đáng khác). ISA sẽ xem xét.',
      },
    ],
    counterPhrases: [
      {
        jp: '弁護士に相談したいです。',
        romaji: 'Bengoshi ni soudan shitai desu.',
        vn: 'Tôi muốn tham vấn luật sư.',
        note: 'Câu đầu tiên cần dùng. KHÔNG tự đến Nyukan khi chưa có tư vấn. Gọi 法テラス 0570-078374 hoặc Đại sứ quán Việt Nam 03-3466-3311 để được giới thiệu luật sư.',
      },
      {
        jp: 'ベトナム語の通訳をお願いします。',
        romaji: 'Betonamu-go no tsuuyaku o onegai shimasu.',
        vn: 'Xin thông dịch viên tiếng Việt.',
        note: 'Quyền có thông dịch khi làm việc với Nyukan. KHÔNG ký bất kỳ giấy gì khi chưa hiểu rõ.',
      },
      {
        jp: '在留資格について質問があります。',
        romaji: 'Zairyuu shikaku ni tsuite shitsumon ga arimasu.',
        vn: 'Tôi có câu hỏi về tư cách lưu trú.',
        note: 'Khi gọi 0570-013904 (Foreign Residents Support Center) — câu mở đầu trung tính.',
      },
      {
        jp: '今は答えたくありません。弁護士なしでは話しません。',
        romaji: 'Ima wa kotaetaku arimasen. Bengoshi nashi de wa hanashimasen.',
        vn: 'Tôi không muốn trả lời lúc này. Tôi sẽ không nói khi chưa có luật sư.',
        note: 'Quyền 黙秘 (giữ im lặng) theo 憲法 §38. Áp dụng khi Nyukan / cảnh sát hỏi mà chưa có luật sư hỗ trợ.',
      },
    ],
    keyTerms: [
      {
        term: '不法残留',
        reading: 'ふほうざんりゅう',
        meaningVi: 'lưu trú trái phép (visa đã hết hạn)',
        noteVi: 'Vi phạm 入管法 §70. Phạt tới 3 năm tù hoặc ¥300万 (hoặc cả hai). Kèm 退去強制 + 上陸拒否期間 5-10 năm. KHÔNG có "ngày đệm" — quá 1 ngày là vi phạm. Mỗi ngày overstay thêm làm tình hình tệ hơn.',
      },
      {
        term: '退去強制',
        reading: 'たいきょきょうせい',
        meaningVi: 'trục xuất bắt buộc (cưỡng chế rời Nhật)',
        noteVi: 'Khác 出国命令. Nyukan bắt + tạm giữ tại 入管 facility (vài tuần - vài tháng) → trục xuất về nước. Kèm 上陸拒否 5 năm (lần đầu) / 10 năm (tái phạm hoặc nặng) / vĩnh viễn (đặc biệt nghiêm trọng). Khó xin lại visa Nhật sau này. Tham vấn 弁護士 nếu thấy có rủi ro 退去強制.',
      },
      {
        term: '出国命令',
        reading: 'しゅっこくめいれい',
        meaningVi: 'lệnh rời Nhật tự nguyện (theo 入管法 §24-3)',
        noteVi: 'CÓ THỂ áp dụng khi: (1) tự nguyện đến báo cáo Nyukan; (2) không có tiền án nặng khác; (3) hợp tác đầy đủ; (4) có khả năng tự rời. Nếu Nyukan cấp → 出国準備期間 (4-8 tuần) + cấm tái nhập 1 năm thay vì 5-10 năm. KHÔNG phải "tự động" — Nyukan đánh giá. Tham vấn 弁護士 trước.',
      },
      {
        term: '在留特別許可',
        reading: 'ざいりゅうとくべつきょか',
        meaningVi: 'quyền cho phép ở lại đặc biệt (do Bộ trưởng Tư pháp cấp, 入管法 §50)',
        noteVi: 'RẤT HIẾM được cấp. KHÔNG phải lựa chọn người vi phạm có thể "apply" — là quyền riêng của Bộ trưởng Tư pháp. Thường chỉ xem xét khi có hoàn cảnh nhân đạo cực kỳ đặc biệt (kết hôn người Nhật + có con Nhật + quan hệ thực sự, hoặc điều trị bệnh không thể nhận ở nước về). BẮT BUỘC 弁護士. KHÔNG nên dựa vào.',
      },
      {
        term: '上陸拒否期間',
        reading: 'じょうりくきょひきかん',
        meaningVi: 'thời gian cấm tái nhập Nhật',
        noteVi: 'Theo 入管法 §5. Sau khi rời/bị trục xuất: cấm tái nhập 1 năm (出国命令), 5 năm (退去強制 lần đầu), 10 năm (tái phạm hoặc tội nặng như 不法就労), vĩnh viễn (tội rất nghiêm trọng). Trong thời gian cấm, KHÔNG xin visa Nhật được, kể cả visa du lịch.',
      },
      {
        term: '救済措置',
        reading: 'きゅうさいそち',
        meaningVi: 'biện pháp cứu trợ (trong 2 tháng từ ngày overstay)',
        noteVi: 'Khi có lý do khách quan (quên hạn do tài liệu Nyukan delay, bệnh nặng đột ngột, thảm họa) — Nyukan THƯỜNG xét gia hạn / cấp lại tư cách trong 2 tháng. KHÔNG có gì đảm bảo — Nyukan đánh giá từng trường hợp. Cần 診断書 / 罹災証明書 / bằng chứng khách quan. Tham vấn 弁護士 / 行政書士 trước khi nộp.',
      },
      {
        term: '不法就労',
        reading: 'ふほうしゅうろう',
        meaningVi: 'lao động trái phép (làm việc khi đã overstay)',
        noteVi: 'Vi phạm 入管法 §70 RIÊNG — thêm tội bên cạnh 不法残留. Phạt tới 3 năm tù hoặc ¥300万. Kèm tăng 上陸拒否 từ 5 năm lên 10 năm. NGỪNG NGAY mọi hoạt động trả lương khi phát hiện overstay. Công ty thuê người 不法就労 cũng phạm tội 不法就労助長.',
      },
      {
        term: '法テラス',
        reading: 'ほうテラス',
        meaningVi: 'Japan Legal Support Center — hỗ trợ pháp lý miễn phí',
        noteVi: 'Hotline 0570-078374 (đa ngôn ngữ). Hỗ trợ tư vấn pháp lý miễn phí lần đầu cho người thu nhập thấp. Có thể trả góp phí luật sư. Đặc biệt hữu ích cho trường hợp 不法残留 / 不法就労 khi không đủ tiền thuê luật sư riêng.',
      },
    ],
    officialLinks: [
      { label: 'ISA — Overstay & Rescue Measure', url: 'https://www.moj.go.jp/isa/' },
      { label: '出国命令制度 — Deportation Order System', url: 'https://www.moj.go.jp/isa/applications/procedures/' },
      { label: '在留特別許可 — Special Humanitarian Permission', url: 'https://www.moj.go.jp/isa/applications/procedures/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Phát hiện overstay — kiểm tra ngay visa hạn của bạn',
        description: 'Mở thẻ cư trú (在留カード) hoặc certificate of eligibility (COE) và kiểm tra **有効期限** (ngày hết hạn).\n\n**Nếu hôm nay sau ngày đó = overstay (不法残留).**\n\nVí dụ:\n- Visa hết hạn: 2026-05-10\n- Hôm nay: 2026-05-15\n- Overstay: 5 ngày\n\nDù chỉ 1 ngày hay 100 ngày đều là vi phạm 入管法 §70. KHÔNG có grace period.\n\n**HÀNH ĐỘNG ĐẦU TIÊN: tham vấn 弁護士 / 行政書士 chuyên 入管 NGAY.**\nGọi 法テラス 0570-078374 nếu khó khăn tài chính. Đại sứ quán Việt Nam (03-3466-3311) có thể giới thiệu luật sư biết tiếng Việt.\n\n**KHÔNG tự ý quyết định** giữa các thủ tục Nyukan THƯỜNG xét (vd: 救済措置 trong 2 tháng, 出国命令, 在留特別許可) — mỗi thủ tục có điều kiện riêng + tỷ lệ áp dụng khác nhau + đánh giá hoàn toàn do Nyukan. Luật sư đánh giá hoàn cảnh cá nhân của bạn trước khi đến Nyukan sẽ giúp bảo vệ quyền lợi tốt nhất có thể.\n\n**KHÔNG tiếp tục lao động** — bất kỳ hoạt động trả lương nào khi đã overstay = thêm tội 不法就労, làm tình hình tệ hơn nhiều.',
        documents: ['Thẻ cư trú hoặc COE để kiểm tra ngày hết hạn'],
        tip: 'Nếu không chắc ngày nào, kiểm tra 2 lần. Một khi xác nhận overstay, hành động ngay — không nên chờ thêm.',
      },
      {
        step: 2,
        title: 'Lựa chọn 1: Apply Rescue Measure (Nếu hợp đủ điều kiện)',
        description: '**Điều kiện để apply rescue:**\n- Quên làm gia hạn lần cuối (最後の更新を忘れた)\n- Hoặc bệnh nặng/nhập viện khiến không kịp làm gia hạn\n- Hoặc sự cố lớn (tai nạn, thảm họa, v.v.)\n- **Trong vòng 2 tháng từ ngày hết hạn**\n\n**Nộp tại ISA:**\n- Đơn xin rescue (在留期間更新許可申請) — tải từ ISA website\n- Hộ chiếu + thẻ cư trú\n- Giấy chứng minh lý do (ví dụ: giấy xác nhận từ bệnh viện, hóa đơn, lý do giải trình)\n- Lý do giải trình rõ ràng (理由書) — viết tay: \"Tôi quên không nhận ra visa hết hạn vì [lý do]. Tôi xin cứu trợ.\"\n\n**Kết quả:**\n- Nếu được phê duyệt: gia hạn được cấp phép, bạn ở lại Nhật bình thường\n- Nếu từ chối: sẽ được thông báo, lúc đó bạn chuyển sang tùy chọn 2',
        documents: ['Đơn xin rescue (in từ ISA website)', 'Hộ chiếu', 'Thẻ cư trú', 'Giấy chứng minh lý do', 'Lý do giải trình (理由書)'],
        tip: '救済措置 KHÔNG phải "cứu cánh tự động" — Nyukan đánh giá từng trường hợp, KHÔNG có gì đảm bảo được duyệt. Tham vấn 弁護士 / 行政書士 trước khi nộp để hồ sơ được trình bày đúng. Quá 2 tháng = lựa chọn này không còn áp dụng.',
      },
      {
        step: 3,
        title: 'Lựa chọn 2: Apply 出国命令 (Tự rời Nhật)',
        description: '**Điều kiện:**\n- Đã overstay (dù quá 2 tháng hay không)\n- Muốn tự rời Nhật để giảm hình phạt\n\n**Nộp tại ISA:**\n- Bút điều trần (陳述) hoặc nói chuyện trực tiếp với ISA\n- Hộ chiếu + thẻ cư trú\n- Nói rõ: \"Tôi biết tôi overstay. Tôi muốn áp dụng 出国命令 để tự rời Nhật\"\n\n**Quá trình:**\n- ISA sẽ xác nhận tình trạng overstay và hồ sơ\n- Cấp thẻ 出国準備期間 (chuẩn bị rời Nhật) — thường 4-8 tuần\n- Trong thời gian này, bạn chuẩn bị rời (xin thôi việc, trả nhà, v.v.)\n- Khi sẵn sàng, đến sân bay hoặc cảng, nộp giấy tờ ra nước ngoài\n- Entry ban: **1 năm** (短期入国禁止)\n\n**Hậu quả:**\n- Cấm nhập cảnh 1 năm (có thể xin miễn lệnh sau 1 năm)\n- Không có hình phạt tiền hoặc tù\n- Tốt hơn bị bắt (5-10 năm ban)',
        documents: ['Hộ chiếu', 'Thẻ cư trú', 'Giấy xác nhận overstay từ ISA hoặc xác nhận từ người phát hiện'],
        tip: '出国命令 áp dụng khi Nyukan đánh giá đủ điều kiện theo 入管法 §24-3 — KHÔNG phải "lựa chọn tự động". Nyukan có thể từ chối + chuyển sang 退去強制 nếu thấy không đủ điều kiện. Tham vấn 弁護士 trước khi đến Nyukan để biết hoàn cảnh của bạn có khả năng được áp dụng không.',
      },
      {
        step: 4,
        title: '在留特別許可 — đặc biệt rất hiếm, KHÔNG nên dựa vào',
        description: '在留特別許可 là quyền RIÊNG của Bộ trưởng Tư pháp (theo 入管法 §50) — KHÔNG phải thủ tục bạn "apply" như visa thường. RẤT HIẾM được cấp.\n\n**Hoàn cảnh có thể được Nyukan / Bộ trưởng Tư pháp xét đến:**\n- Kết hôn hợp pháp với người Nhật + có quan hệ thực sự ổn định\n- Có con quốc tịch Nhật + đang nuôi dưỡng trực tiếp\n- Bệnh nặng / điều trị y tế không thể nhận ở nước về\n- Hoàn cảnh nhân đạo cực kỳ đặc biệt khác\n\n**Thực tế:**\n- Số lượng cấp mỗi năm rất hạn chế (theo thống kê 法務省 công bố hàng năm)\n- Quy trình kéo dài (thường 1 năm+)\n- Trong thời gian xét, bạn có thể bị tạm giữ tại 入管 facility hoặc cấp giấy phép tạm cho hoạt động hạn chế\n- KHÔNG có "công thức" — Nyukan đánh giá tổng thể: hành vi quá khứ, hoàn cảnh hiện tại, sự đóng góp cho xã hội Nhật, mối quan hệ gia đình\n\n**BẮT BUỘC có 弁護士 chuyên 入管** — KHÔNG tự xử lý. Tỷ lệ thành công không cao kể cả với luật sư giỏi. KHÔNG nên dựa vào 在留特別許可 như "phương án dự phòng" khi quyết định overstay — đây là biện pháp cuối cùng cho hoàn cảnh đã có sẵn yếu tố nhân đạo mạnh, không phải lựa chọn người vi phạm có thể chọn.',
        documents: ['Giấy chứng minh nhân đạo (kết hôn, con, bệnh, v.v.)', 'Bằng chứng ISA có thể xác minh'],
        tip: 'Đừng chọn tùy chọn này trừ khi bạn thực sự có lý do nhân đạo mạnh mẽ. ISA sẽ xem xét rất kỹ lưỡng.',
      },
      {
        step: 5,
        title: 'Sau khi xử lý — chuẩn bị cho tương lai',
        description: '**Nếu được rescue (tùy chọn 1):**\n- Bạn ở lại Nhật bình thường\n- Cần chuẩn bị tài liệu để gia hạn lần tiếp theo (không nên quên lần nữa!)\n- Set alarm hoặc lịch nhắc nhở 3 tháng trước ngày hết hạn\n\n**Nếu apply 出国命令 (tùy chọn 2):**\n- Chuẩn bị rời Nhật trong 出国準備期間 (4-8 tuần)\n- Xin thôi việc, trả nhà, chuyển hàng\n- Thanh toán thuế, bảo hiểm, tài khoản ngân hàng cuối cùng\n- Sau khi về Việt Nam, ban 1 năm sẽ được gỡ bỏ tự động — có thể quay lại Nhật sau 1 năm nếu muốn\n\n**Nếu apply 在留特別許可 (tùy chọn 3):**\n- Đợi ISA xét duyệt — có thể mất vài tháng\n- Chuẩn bị cho khả năng bị từ chối (lên kế hoạch B)',
        documents: [],
        tip: 'Bất kể xử lý bằng cách nào, sau này nếu muốn quay lại Nhật, hãy tuân thủ quy định một cách nghiêm túc — không muốn lặp lại overstay.',
      },
    ],
  };

export default overstayingIllegalStayProcedures;
