import type { AdminGuide } from '../../../../types/content';

const payslipReading: AdminGuide = {
    id: 'payslip-reading',
    category: 'money',
    lastVerified: '2026-05-02',
    priority: 'high',
    title: 'Cách đọc bảng lương Nhật',
    titleJp: '給与明細の見方',
    icon: 'document-text',
    color: '#1A6B9A',
    description: 'Giải thích từng dòng trên 給与明細 (bảng lương): khoản nào được trả, khoản nào bị khấu trừ và tại sao số tiền vào tài khoản khác với lương hợp đồng.',
    searchKeywords: [
      'đọc bảng lương',
      'hiểu lương Nhật',
      'lương thực nhận',
      '給与明細',
      'kyuuyo meisai',
      'payslip',
      '基本給',
      'kihonkyuu',
      '支給合計',
      '差引支給額',
      '手取り',
      'tedori',
      'take-home pay',
      '残業手当',
      'zangyou teate',
      'overtime',
      '固定残業代',
      'kotei zangyou dai',
      'みなし残業',
      '厚生年金',
      'kousei nenkin',
      '健康保険料',
      '雇用保険',
      '通勤手当',
      'tsuukin teate',
      '標準報酬月額',
      '社会保険料',
      'lương thấp hơn hợp đồng',
      'tại sao lương bị trừ nhiều',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: '労働基準法 §24 (賃金支払の原則) yêu cầu lương trả bằng tiền mặt/chuyển khoản, đầy đủ, hàng tháng, trực tiếp cho người lao động. 給与明細 chi tiết bắt buộc theo 所得税法 §231. 残業手当 hệ số ≥1.25× (≥1.50× vượt 60h/tháng), đêm +0.25×, 休日 ≥1.35×. 社会保険料 chia 健康保険 (~5%), 厚生年金 9.15%, 雇用保険 ~0.55%, 介護 ~0.8% (40-64 tuổi). 通勤手当 miễn thuế đến 150,000円/tháng theo §9 所得税法.',
      sourceVerifiedAt: '2026-05-02',
      nextReviewAt: '2026-12-31',
      riskLevel: 'low',
      whenToAskExpert: [
        'Nghi ngờ bị trả thiếu 残業手当 nhiều tháng / nhiều năm → liên hệ 労働基準監督署 (miễn phí); nếu cần đòi truy lãnh > 2 năm cũ → cần 弁護士.',
        '"固定残業代" trong hợp đồng nhưng làm thực tế nhiều hơn → đối chiếu タイムカード + đòi phần chênh; nếu công ty từ chối → 労基署 hoặc 弁護士.',
        'Bị khấu trừ khoản lạ không có trong hợp đồng (vd 罰金, 損害賠償 đơn phương) → vi phạm 労基法 §24 — báo 労基署.',
        'Lương trả chậm > 1 tháng → 労基署.',
        'Có 2 nơi trả lương + cả 2 đều khấu trừ 社会保険 → có thể đang đóng dư — hỏi 年金事務所 về 二以上事業所勤務届.',
      ],
    },
    quickAction: {
      deadline: 'Đọc + lưu 給与明細 mỗi tháng — không có hạn cố định nhưng nên rà tháng nhận lương đầu tiên + đầu tháng 6 (住民税 áp mới) + đầu tháng 1 (年末調整 hoàn).',
      office: 'HR / 給与担当 công ty: hỏi khoản lạ. 労働基準監督署: bị trả thiếu / khấu trừ trái pháp luật. 税務署 / e-Tax: kiểm tra 源泉徴収 hoặc 確定申告. 年金事務所: hỏi 標準報酬月額.',
      doNow: [
        'So 基本給 trên 給与明細 với hợp đồng — phải khớp.',
        'So 通勤手当 với khoản công ty hứa — không vượt 150,000円/tháng = miễn thuế.',
        'Đếm giờ làm thêm thực tế (タイムカード / PC log) → tính 残業手当 (formula step 4) → so với bảng lương.',
        'Kiểm tra 控除: 健康保険 + 厚生年金 + 雇用保険 + 所得税 (+ 住民税 nếu năm thứ 2+) → cộng = 控除合計.',
        '差引支給額 = 支給合計 − 控除合計 = số chuyển vào tài khoản → đối chiếu với 通帳.',
        'Nếu thấy khoản trừ KHÔNG có trong hợp đồng (社宅費, 食事代, 財形, 組合費, 貸付返済): hỏi HR yêu cầu giải thích bằng văn bản.',
        'Lưu bản giấy hoặc PDF 給与明細 cả năm — cần khi xin visa, vay ngân hàng, 確定申告.',
      ],
      bring: [
        '給与明細 các tháng cần kiểm tra',
        '労働契約書 / 雇用通知書 (đối chiếu lương cơ bản + giờ làm)',
        'タイムカード / 出勤簿 (nếu kiểm 残業)',
        '源泉徴収票 cuối năm',
        'Sổ ngân hàng (đối chiếu 振込額)',
      ],
      ifLate: 'Phát hiện trả thiếu lương / 残業手当 nhiều năm: yêu cầu truy lãnh — quyền theo 労基法 thời hiệu 2 năm (sau 04/2020) hoặc 3 năm với một số trường hợp. Quá hạn → mất quyền đòi. Nên báo 労基署 hoặc 弁護士 SỚM, không đợi nghỉ việc.',
      officialSourceLabels: ['賃金の支払いに関するルール — 厚生労働省'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_payslip_hero.jpg'),
    heroImageCaption: 'Giải thích chi tiết các dòng trong bảng lương 給与明細',
    whoIsThisFor: [
      'Người mới đi làm tại Nhật lần đầu nhận bảng lương và không hiểu các dòng số liệu.',
      'Người muốn kiểm tra lại xem thuế và bảo hiểm có bị tính đúng không.',
      'Người chuẩn bị đàm phán lương hoặc so sánh offer từ nhiều công ty.',
    ],
    whenToDo: [
      'Khi nhận bảng lương hàng tháng — nên đọc kỹ ít nhất vài tháng đầu.',
      'Tháng 12 hoặc tháng 1: kiểm tra xem công ty đã làm 年末調整 chưa và số thuế điều chỉnh có hợp lý không.',
      'Tháng 5-6: 住民税 mới thường áp dụng từ tháng 6, kiểm tra thay đổi trên bảng lương.',
    ],
    whereToDo: [
      'Bộ phận HR/nhân sự hoặc kế toán tiền lương: hỏi khi có khoản trừ hoặc khoản cộng không hiểu.',
      '労働基準監督署: liên hệ nếu nghi ngờ bị trả thiếu lương, thiếu 残業手当 hoặc công ty không giải thích rõ.',
      '税務署 hoặc e-Tax: dùng khi cần tự 確定申告 hoặc kiểm tra số thuế đã khấu trừ.',
    ],
    fees: [
      'Không có phí — đây là quyền được nhận bảng lương chi tiết theo luật 労働基準法.',
    ],
    documentsChecklist: [
      { label: '給与明細 các tháng cần kiểm tra', required: true },
      { label: '労働契約書 hoặc 雇用通知書', required: true, note: 'Đối chiếu lương cơ bản, giờ làm quy định và phụ cấp.' },
      { label: 'Bảng chấm công / タイムカード / PC login records', required: false, note: 'Cần khi kiểm tra 残業手当 hoặc tranh chấp giờ làm.' },
      { label: '源泉徴収票 cuối năm', required: false, note: 'Dùng để kiểm tra 年末調整 và làm 確定申告 nếu cần.' },
    ],
    commonMistakes: [
      'Nhầm 支給合計 (tổng trước khấu trừ) với 差引支給額 (tiền thực nhận) — hai con số này chênh nhau đáng kể.',
      'Không kiểm tra 残業手当 — nhiều người bị trả thiếu lương làm thêm giờ mà không phát hiện.',
      'Nghĩ thuế bị trừ hàng tháng là số thuế cuối cùng — đây chỉ là tạm khấu trừ, số thực tế được quyết toán qua 年末調整 hoặc 確定申告.',
      'Bỏ qua cột 有給残高 (số ngày phép còn lại) — nên theo dõi để dùng hết trước khi nghỉ việc.',
    ],
    faq: [
      {
        question: 'Tại sao lương vào tài khoản ít hơn nhiều so với 基本給 trên hợp đồng?',
        answer: '基本給 là lương cơ bản trước khấu trừ. Số tiền thực nhận (差引支給額) = 支給合計 (lương + phụ cấp) − 控除合計 (bảo hiểm + thuế). Với lương 25万/tháng, tổng khấu trừ thường vào khoảng 3.5–5万 yên tùy tình huống.',
      },
      {
        question: '住民税 bắt đầu bị trừ từ tháng nào và tại sao năm đầu không bị trừ?',
        answer: '住民税 tính trên thu nhập năm trước, thu từ tháng 6 đến tháng 5 năm sau. Người mới sang Nhật năm đầu chưa có thu nhập năm trước nên chưa bị trừ. Từ năm thứ 2 trở đi, tháng 6 sẽ thấy thêm khoản này trên bảng lương — đừng bị bất ngờ.',
      },
      {
        question: 'Làm thêm giờ nhưng không thấy 残業手当 trên bảng lương, phải làm gì?',
        answer: 'Trước tiên: kiểm tra hợp đồng xem có mục "固定残業代" (lương bao gồm sẵn giờ làm thêm nhất định) không. Nếu không có và bạn thực sự làm thêm, hãy đối chiếu với 出勤簿/タイムカード. Nếu sai, trình bày với bộ phận nhân sự. Nếu không giải quyết được, liên hệ 労働基準監督署.',
      },
      {
        question: 'Tháng 12 nhận được tiền điều chỉnh thuế — đó là gì?',
        answer: 'Đó là 年末調整 — quyết toán thuế thu nhập cuối năm. Nếu công ty đã khấu trừ tạm nhiều hơn số thuế thực tế phải nộp, phần chênh lệch được hoàn lại trong bảng lương tháng 12 hoặc tháng 1. Đây là khoản hoàn thuế bình thường, không phải lương thưởng.',
      },
    ],
    counterPhrases: [
      {
        jp: '給与明細の見方を教えていただけますか。',
        romaji: 'Kyuuyo meisai no mikata o oshiete itadakemasu ka.',
        vn: 'Anh/chị giải thích giúp cách đọc bảng lương được không?',
        note: 'Hỏi HR / 給与担当 khi mới vào công ty.',
      },
      {
        jp: 'この控除は何ですか。',
        romaji: 'Kono koujo wa nan desu ka.',
        vn: 'Khoản trừ này là gì?',
        note: 'Chỉ vào dòng khấu trừ không hiểu trên 給与明細.',
      },
      {
        jp: '残業手当の計算が違うようなので確認したいです。',
        romaji: 'Zangyou teate no keisan ga chigau you na node kakunin shitai desu.',
        vn: 'Tôi muốn kiểm tra lại tính lương làm thêm vì có vẻ sai.',
        note: 'Cách diễn đạt nhẹ + có lý do, hỏi HR trước khi báo 労基署.',
      },
      {
        jp: '標準報酬月額はいくらですか。',
        romaji: 'Hyoujun houshuu getsugaku wa ikura desu ka.',
        vn: 'Mức 標準報酬月額 của tôi là bao nhiêu?',
        note: 'Hỏi 給与担当 hoặc 年金事務所 — quan trọng vì ảnh hưởng phí 健康保険 + 厚生年金 + tiền 出産手当金 / 傷病手当金 sau này.',
      },
      {
        jp: '固定残業代に含まれている時間を教えてください。',
        romaji: 'Kotei zangyou dai ni fukumarete iru jikan o oshiete kudasai.',
        vn: 'Cho tôi biết số giờ làm thêm đã gộp trong 固定残業代.',
        note: 'Bắt buộc theo 労基法 — công ty phải nêu rõ. Quá số giờ này = công ty phải trả thêm 残業手当.',
      },
    ],
    keyTerms: [
      {
        term: '給与明細',
        reading: 'きゅうよめいさい',
        meaningVi: 'bảng lương chi tiết',
        noteVi: 'Công ty bắt buộc cấp hàng tháng theo 所得税法 §231 + 労基法. Cấp giấy hoặc PDF qua portal công ty. GIỮ KỸ cả năm — cần khi xin visa gia đình / vay nhà / 確定申告 / tranh chấp lao động. 2 năm sau có thể không xin lại được bản gốc.',
      },
      {
        term: '基本給',
        reading: 'きほんきゅう',
        meaningVi: 'lương cơ bản (theo hợp đồng)',
        noteVi: 'Lương "trên giấy" trước mọi cộng/trừ. KHÔNG phải số tiền vào tài khoản. Phải khớp với 労働契約書. Lương 基本給 cao = 賞与 + 退職金 + 健康保険 + 年金 tính cao hơn (vì các khoản này tính theo 基本給 hoặc 標準報酬月額).',
      },
      {
        term: '手取り',
        reading: 'てどり',
        meaningVi: 'tiền thực nhận (sau khấu trừ)',
        noteVi: 'Tên thân mật của 差引支給額. Số chuyển vào tài khoản. Quy luật chung: 手取り ≈ 75-80% 支給合計 cho người độc thân lương trung bình. Khi nhận offer mới, luôn hỏi cả "支給" và "手取り目安" để so sánh.',
      },
      {
        term: '固定残業代',
        reading: 'こていざんぎょうだい',
        meaningVi: 'lương làm thêm cố định (gộp sẵn vào lương)',
        noteVi: 'Còn gọi みなし残業 / 定額残業代. Công ty thêm "x giờ làm thêm" vào lương cơ bản. NGUY HIỂM nếu không hiểu: nhiều người Việt nhận offer cao thấy "30万円" mà không biết bao gồm 40 giờ 残業. Quá giờ đó công ty PHẢI trả thêm — hợp đồng + bảng lương phải nêu rõ số giờ.',
      },
      {
        term: '標準報酬月額',
        reading: 'ひょうじゅんほうしゅうげつがく',
        meaningVi: 'mức lương cơ sở tính bảo hiểm',
        noteVi: 'Mức cố định nhà nước dùng để tính phí 健康保険 + 厚生年金 + 雇用保険 + 介護保険. Chia 50 cấp. Quyết định 1 năm/lần (tháng 4-6) qua 算定基礎届. Lương tăng nhiều giữa năm + 3 tháng vượt 2 cấp → có thể đổi cấp giữa năm (随時改定 = 月変).',
      },
      {
        term: '厚生年金',
        reading: 'こうせいねんきん',
        meaningVi: 'lương hưu cho người đi làm công ty (9.15% lương)',
        noteVi: 'KHÁC với 国民年金 (cho người không đi làm — 16,980円/tháng cố định 2025). 厚生年金 = 国民年金 + phần thêm theo lương. Công ty trả 50% phần thêm. Người Việt về VN có thể xin 脱退一時金 (hoàn tối đa 5 năm đóng) tại 年金事務所 sau khi mất 住民票.',
      },
      {
        term: '通勤手当',
        reading: 'つうきんてあて',
        meaningVi: 'phụ cấp đi lại',
        noteVi: 'Tiền vé tàu/xe đi làm. Miễn thuế tới 150,000円/tháng (theo 所得税法 §9). Vượt mức = phần dư bị tính thuế. KHÔNG được phép gộp vào 基本給 để giảm thuế cho công ty — đây là vi phạm. 通勤手当 vẫn tính vào 標準報酬月額 (ảnh hưởng phí bảo hiểm).',
      },
      {
        term: '健康保険組合 vs 協会けんく',
        reading: 'けんこうほけんくみあい vs きょうかいけんぽ',
        meaningVi: '2 nhóm bảo hiểm xã hội cho người đi làm',
        noteVi: 'Khác 国保 (国民健康保険). 健康保険組合 (組合健保) do công ty/nhóm công ty lớn tự lập — phí thường thấp hơn + có thêm benefits. 協会けんぽ (全国健康保険協会) do nhà nước quản, cho công ty nhỏ-vừa. Cả 2 đều bảo hiểm 70%, mức trả khi sinh + ốm khác nhau ít. Xem trên 健康保険証 dòng "保険者番号" để biết bạn ở nhóm nào.',
      },
    ],
    officialLinks: [
      { label: '賃金の支払いに関するルール — 厚生労働省', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/index.html' },
      { label: '時間外労働の割増賃金率 — 厚生労働省', url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/menu.html' },
      { label: '協会けんぽ 保険料率 — 全国健康保険協会', url: 'https://www.kyoukaikenpo.or.jp/g7/cat330/sb3150/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Đọc phần 支給 — khoản được trả',
        description: 'Phần trên bảng lương liệt kê tất cả thu nhập trong tháng:\n\n| Mục | Ý nghĩa |\n|---|---|\n| 基本給 | Lương cơ bản theo hợp đồng |\n| 時間外手当 / 残業手当 | Lương làm thêm giờ (bình thường ≥1.25×/giờ; tháng >60h ≥1.50×) |\n| 深夜手当 | Phụ cấp làm đêm 22:00–5:00 (+0.25× so với ca thường) |\n| 休日手当 | Lương làm ngày nghỉ pháp định (≥1.35×) |\n| 通勤手当 | Phụ cấp đi lại (thường bằng tiền xe tháng) |\n| 住宅手当 | Phụ cấp nhà ở (nếu công ty có chính sách) |\n| 家族手当 | Phụ cấp gia đình (nếu khai báo扶養) |\n| **支給合計** | **Tổng thu nhập trước khấu trừ** |\n\n⚠️ 通勤手当 thường không bị tính vào thu nhập chịu thuế nếu trong mức quy định (tối đa 150,000 yên/tháng), nhưng vẫn tính vào cơ sở tính bảo hiểm xã hội.',
        documents: [],
        tip: 'Nếu thấy mục "固定残業代" hoặc "みなし残業" trong hợp đồng, nghĩa là một số giờ làm thêm đã được gộp sẵn vào 基本給 — hỏi HR để biết số giờ cụ thể.',
      },
      {
        step: 2,
        title: 'Đọc phần 控除 — các khoản bị khấu trừ',
        description: 'Phần dưới hoặc bên phải liệt kê các khoản bị trừ khỏi lương:\n\n| Mục | Tỷ lệ tham khảo (令和7年度 / 2025) | Ghi chú |\n|---|---|---|\n| 健康保険料 | ~5.00% lương | Phụ thuộc tỉnh/組合; Tokyo: 4.955% |\n| 介護保険料 | ~0.795% lương | **Chỉ người 40–64 tuổi** |\n| 厚生年金保険料 | 9.15% lương | Cố định toàn quốc |\n| 雇用保険料 | 0.55% lương | Phòng trừ khi thất nghiệp |\n| 所得税 | Tùy thu nhập | Khấu trừ tạm, quyết toán cuối năm |\n| 住民税 | Tùy thu nhập năm trước | **Không trừ năm đầu mới sang Nhật** |\n| **控除合計** | **Tổng khấu trừ** | |\n\nVí dụ: Lương 250,000 yên/tháng, khấu trừ xã hội khoảng 37,250 yên (chưa tính thuế thu nhập và住民税).',
        documents: [],
        tip: '所得税 hàng tháng chỉ là tạm trừ theo bảng 源泉徴収税額表. Cuối năm qua 年末調整 (do công ty làm) số này sẽ được điều chỉnh và hoàn lại nếu trừ nhiều hơn thực tế.',
      },
      {
        step: 3,
        title: 'Kiểm tra 差引支給額 — tiền thực nhận',
        description: '**差引支給額** = 支給合計 − 控除合計\n\nĐây là số tiền chuyển vào tài khoản ngân hàng của bạn (còn gọi là 振込額 hoặc 手取り).\n\nMột số bảng lương còn có thêm:\n| Mục | Ý nghĩa |\n|---|---|\n| 有給残高 | Số ngày phép có lương còn lại |\n| 累計支給 | Tổng lương cộng dồn từ đầu năm (dùng để tính thuế cuối năm) |\n| 標準報酬月額 | Mức lương cơ sở tính bảo hiểm (không thay đổi thường xuyên) |\n\n**Nếu tiền vào tài khoản ít hơn差引支給額 — kiểm tra các khoản trừ thêm ngoài thuế và bảo hiểm:**\n| Khoản | Tên tiếng Nhật | Ghi chú |\n|---|---|---|\n| Tiền nhà tập thể công ty | 社宅費 / 家賃控除 | Thường thấp hơn giá thị trường, nhưng phải có trong hợp đồng |\n| Tiền suất ăn trưa | 食事代 / 給食費 | Chỉ áp dụng nếu công ty có bếp ăn hoặc đặt cơm tập thể |\n| Tiết kiệm qua công ty | 財形貯蓄 | Bạn tự đăng ký, tiền tự động trừ để tiết kiệm |\n| Phí công đoàn | 組合費 | Nếu bạn là thành viên công đoàn nội bộ |\n| Trả khoản vay công ty | 従業員貸付金返済 | Nếu đã vay công ty (tiền tạm ứng mua nhà, thiên tai...) |\n\n⚠️ Các khoản này **hợp pháp nhưng bắt buộc phải có trong hợp đồng hoặc quy định nội bộ** — nếu thấy khoản lạ không ai giải thích, hỏi ngay bộ phận nhân sự bằng văn bản.',
        documents: [],
        image: require('../../../../../assets/content/daily-life/ag_payslip_s3.jpg'),
        imageCaption: '差引支給額 - số tiền thực nhận sau khi trừ thuế, bảo hiểm và khoản khấu trừ',
        tip: 'Lưu tất cả 給与明細 trong năm — bạn cần chúng khi làm 確定申告, xin visa gia đình, vay ngân hàng hoặc tranh chấp lao động.',
      },
      {
        step: 4,
        title: 'Kiểm tra 残業手当 có đúng không',
        description: 'Công thức cơ bản tính lương làm thêm giờ:\n\n**Lương giờ cơ bản** = 基本給 ÷ 所定労働時間/tháng (thường 160–173h)\n\n**Lương làm thêm giờ** = Lương giờ cơ bản × số giờ làm thêm × hệ số\n\n| Loại giờ | Hệ số tối thiểu |\n|---|---|\n| Thường ngày (>所定労働時間) | 1.25× |\n| Tháng vượt 60 giờ (月60時間超) | 1.50× |\n| Làm đêm 22:00–5:00 | +0.25× (cộng thêm) |\n| Ngày nghỉ pháp định (法定休日) | 1.35× |\n| Ngày nghỉ theo hợp đồng (所定休日) | 1.25× |\n\n⚠️ Các khoản 通勤手当, 家族手当, 住宅手当 cần được tính vào lương giờ cơ bản theo quy định, không chỉ dùng 基本給 đơn thuần.\n\n**Ví dụ tính kiểm tra 残業手当:**\nGiả sử hợp đồng: 基本給 200,000 yên + 通勤手当 10,000 yên, 所定労働時間 160 giờ/tháng. Tháng này làm thêm 20 giờ.\n- Lương giờ cơ bản = (200,000 + 10,000) ÷ 160 = **1,313 yên/giờ**\n- 残業手当 phải nhận = 1,313 × 20 × 1.25 = **32,825 yên**\n- Nếu bảng lương ghi 残業手当 thấp hơn đáng kể → đối chiếu với タイムカード và hỏi HR bằng văn bản.',
        documents: ['Bảng chấm công / タイムカード hoặc PC login records', '労働契約書 / 雇用通知書 để đối chiếu số giờ làm quy định'],
        image: require('../../../../../assets/content/daily-life/ag_payslip_s4.jpg'),
        imageCaption: '残業手当 - đối chiếu giờ làm thêm với bảng chấm công và hợp đồng',
        tip: 'Nhiều công ty dùng "固定残業制" gộp sẵn một số giờ thêm vào lương. Nếu thực tế làm nhiều hơn số giờ đó, phần dôi ra vẫn phải được trả thêm.',
      },
    ],
  };

export default payslipReading;
