import type { AdminGuide } from '../../../../types/content';

const pensionExemptionRefund: AdminGuide = {
    id: 'pension-exemption-refund',
    category: 'money',
    lastVerified: '2026-06-20',
    priority: 'high',
    title: '年金, miễn giảm và hoàn nenkin khi về nước',
    titleJp: '年金・免除・脱退一時金の基本',
    icon: 'card',
    color: '#2C3E50',
    description: 'Hướng dẫn thực tế về 国民年金 (lương hưu quốc dân), 厚生年金 (lương hưu công ty), miễn giảm, 学生納付特例, chuyển việc và 脱退一時金 khi rời Nhật. Nội dung viết cho người Việt đang sống hoặc sắp rời Nhật.',
    searchKeywords: [
      'nenkin',
      'lương hưu Nhật',
      'bảo hiểm hưu trí',
      '年金',
      'kokumin nenkin',
      '国民年金',
      'kousei nenkin',
      '厚生年金',
      '年金事務所',
      'nenkin jimusho',
      '脱退一時金',
      'dattai ichijikin',
      'pension refund Japan',
      'hoàn nenkin về nước',
      '免除',
      'menjo',
      '納付猶予',
      'nouhuu yuuyo',
      '学生納付特例',
      'gakusei nouhuu tokurei',
      '追納',
      'tsuinou',
      '年金手帳',
      '基礎年金番号',
      'nenkin số cá nhân',
      'pension exemption student',
      'xin miễn nenkin du học',
      'nenkin khi nghỉ việc',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: '国民年金 + 厚生年金 do 国民年金法 + 厚生年金保険法 quản lý cấp quốc gia, vận hành qua 日本年金機構 (Nenkin Kikou) + 年金事務所 địa phương. 国民年金保険料 cập nhật hàng năm (mức 年度2026 hiện hành công bố 01/04). 脱退一時金 áp dụng cho người đã đóng ≥ 6 tháng, đã mất 住民票 (rời Nhật), trong 2 năm kể từ đủ điều kiện — KHÔNG được nếu đã có 老齢年金 受給権 (tích lũy hưởng lương hưu).',
      sourceVerifiedAt: '2026-05-16',
      nextReviewAt: '2026-11-30',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Đã đóng nenkin 10 năm trở lên → KHÔNG nên xin 脱退一時金 (có quyền hưởng 老齢年金 ở 65 tuổi qua 社会保障協定 — chính phủ VN-Nhật chưa có協定, nhưng có thể đi nước thứ 3) — hỏi 年金事務所 + 国際関連 専門社労士.',
        'Có thời gian đóng nenkin ở nhiều nước (vd VN + Nhật + Đức) → có thể合算 (gộp) qua 社会保障協定 — hỏi 年金事務所 国際業務.',
        'Đã xin 脱退一時金 nhưng bị giữ phần thuế khấu trừ → cần 納税管理人 + 確定申告 ở Nhật để xin hoàn — hỏi 税理士 chuyên hoàn thuế cho người rời Nhật.',
        'Nợ nenkin nhiều tháng + có giấy 督促状 / 差押予告 → KHÔNG bỏ ngơ, đến 年金事務所 ngay xin xét miễn / 分割; ảnh hưởng visa/vĩnh trú nếu nợ kéo dài.',
        'Du học sinh / 技能実習 hết visa chuyển sang công việc khác → đổi từ 国民年金 sang 厚生年金 không tự động — kiểm tra với HR công ty mới + 年金事務所.',
      ],
    },
    quickAction: {
      deadline: '免除 / 納付猶予 / 学生納付特例: trong năm tài khóa hiện tại (T4-T3 năm sau) + truy ngược 2 năm 1 tháng. 脱退一時金: trong 2 năm kể từ ngày mất 住民票 (rời Nhật). 追納 (đóng bù khi đã miễn): trong 10 năm kể từ tháng được miễn.',
      office: '年金事務所 nơi cư trú (cho 国民年金 + 脱退一時金 + 国際). 市役所 (xác nhận 第1号被保険者). HR công ty (cho 厚生年金). Online: ねんきんネット (tra lịch sử).',
      doNow: [
        'Mở 年金手帳 / 基礎年金番号通知書 — ghi nhớ số 基礎年金番号 (10 chữ số).',
        'Kiểm tra mình thuộc loại nào: đi làm công ty (社会保険) → 第2号被保険者 (厚生年金); tự doanh / sinh viên / thất nghiệp → 第1号 (国民年金); vợ/chồng phụ thuộc 第2号 → 第3号 (miễn phí).',
        'Nếu khó khăn tài chính + thuộc 第1号: đến 年金事務所 hoặc 市役所 xin 免除 / 納付猶予 / 学生納付特例 → mang giấy thu nhập / 在学証明書.',
        'Nếu sắp rời Nhật: trước khi đi → đổi địa chỉ ra nước ngoài ở 市役所 + chuẩn bị 脱退一時金請求書 (lấy ở 年金事務所 hoặc tải trang nenkin.go.jp).',
        'Sau khi rời Nhật: gửi 脱退一時金請求書 + bản photo passport (trang xuất cảnh) + 年金手帳 + sổ ngân hàng nước ngoài đến 日本年金機構 trong 2 năm.',
        'Nếu nhận 脱退一時金 厚生年金: bị khấu trừ ~20.42% thuế — xin hoàn qua 確定申告 với 納税管理人 đã đăng ký trước khi rời.',
      ],
      bring: [
        '年金手帳 hoặc 基礎年金番号通知書 (số 基礎年金番号)',
        '在留カード hoặc hộ chiếu',
        'マイナンバー (12 chữ số)',
        'Sổ ngân hàng (cho 還付 hoặc 脱退一時金)',
        '在学証明書 (cho 学生納付特例)',
        '離職票 / 雇用保険受給資格者証 (cho 免除 do thất nghiệp)',
      ],
      ifLate: 'Quá hạn 免除 申請 → có thể truy ngược 2 năm 1 tháng nhưng phải có lý do hợp lý. Quá 2 năm 脱退一時金 → MẤT QUYỀN — không cấp lại. Quá hạn 追納 (10 năm) → không đóng bù được, tháng miễn vẫn tính một phần vào lương hưu sau này. Đang nợ → 年金事務所 sẽ gửi 督促状 → có thể 差押 (siết tài khoản); KHÔNG bỏ ngơ.',
      officialSourceLabels: ['国民年金保険料の免除制度・納付猶予制度 — 日本年金機構'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_pension_hero.jpg'),
    heroImageCaption: '年金 - kiểm tra lịch sử đóng, miễn giảm và 脱退一時金 khi rời Nhật',
    whoIsThisFor: [
      'Người Việt đang đi làm, đi học hoặc làm part-time tại Nhật và chưa hiểu mình đang đóng loại 年金 nào.',
      'Người đang khó khăn tài chính và muốn xin miễn / 納付猶予 thay vì để nợ 年金.',
      'Người sắp về nước và đang phân vân có nên xin 脱退一時金 hay giữ thời gian đóng để tính lương hưu sau này.',
    ],
    whenToDo: [
      'Ngay khi nhận giấy đóng 国民年金 hoặc khi đổi việc để biết mình thuộc 国民年金 hay 厚生年金.',
      'Ngay khi gặp khó khăn tài chính, thất nghiệp hoặc là du học sinh không đủ khả năng đóng.',
      'Trước khi rời Nhật và trong vòng 2 năm sau khi xuất cảnh nếu muốn xin 脱退一時金.',
    ],
    whereToDo: [
      '市役所/区役所: một số thủ tục ban đầu liên quan tới 国民年金 và tình trạng cư trú.',
      '日本年金機構 / 年金事務所: miễn giảm, 学生納付特例, xác nhận tham gia, 脱退一時金 và tra cứu lịch sử đóng 年金.',
      'Công ty đang làm: nếu thuộc 厚生年金 thì việc tham gia / chấm dứt chủ yếu đi qua công ty.',
      'e-Tax / 税務署 và 納税管理人: nếu liên quan hoàn thuế khấu trừ từ 脱退一時金 của 厚生年金.',
    ],
    estimatedTime: 'Miễn giảm và 学生納付特例 nên làm càng sớm càng tốt vì có giới hạn thời gian truy ngược. 脱退一時金 chỉ xin sau khi đã rời Nhật và trong 2 năm kể từ ngày đủ điều kiện; xử lý thực tế mất thêm thời gian bưu chính, xác minh và chuyển khoản quốc tế.',
    fees: [
      '国民年金保険料 hiện hành theo 日本年金機構 cập nhật ngày 01/04/2026 là mức của năm tài khóa 2026; người thuộc 第1号被保険者 phải tự đóng đúng hạn trừ khi được miễn / 納付猶予.',
      'Miễn giảm, 納付猶予 hay 学生納付特例 không phải là "xóa mọi ảnh hưởng" như nhau; mỗi chế độ ảnh hưởng khác nhau tới số lương hưu sau này và khả năng truy đóng (追納).',
      'Nếu xin 脱退一時金 của 厚生年金, có thể có thuế bị khấu trừ; việc xin hoàn phần thuế này thường phải đi qua 納税管理人 và thủ tục thuế riêng.',
    ],
    documentsChecklist: [
      { label: '年金手帳/基礎年金番号通知書 hoặc số年金 cơ bản', required: true },
      { label: 'Giấy tờ cho biết bạn đang ở 国民年金 hay 厚生年金', required: true },
      { label: 'Nếu xin miễn / 納付猶予: giấy tờ thu nhập, thất nghiệp hoặc hoàn cảnh kinh tế', required: false },
      { label: 'Nếu là du học sinh: giấy tờ trường học để xin 学生納付特例', required: false },
      { label: 'Nếu sắp về nước: ngày rời Nhật, địa chỉ ngoài Nhật và tài khoản nhận 脱退一時金', required: false },
      { label: 'Nếu muốn hoàn thuế của 脱退一時金 厚生年金: hồ sơ 納税管理人 và giấy tờ thuế liên quan', required: false },
    ],
    commonMistakes: [
      'Nghĩ 年金 chỉ là khoản bị trừ vô ích và bỏ mặc không xử lý khi khó khăn.',
      'Không phân biệt 国民年金 với 厚生年金, dẫn tới xin sai chỗ hoặc tưởng công ty đang lo hết.',
      'Du học sinh để nợ 国民年金 thay vì xin 学生納付特例.',
      'Người thất nghiệp không xin miễn / 納付猶予 sớm, để mất khoảng thời gian có thể được bảo vệ.',
      'Xin 脱退一時金 mà không hiểu rằng sau khi nhận, lịch sử đóng tương ứng sẽ mất và có thể làm mất cơ hội hưởng lương hưu sau này.',
      'Tưởng cứ về nước là tự động được hoàn lại toàn bộ tiền 年金 đã đóng.',
    ],
    faq: [
      {
        question: 'Ai bắt buộc phải vào 国民年金?',
        answer: '日本年金機構 nêu rõ người sống ở Nhật từ 20 đến 59 tuổi về nguyên tắc đều vào 国民年金. Nếu bạn đi làm thuộc hệ thống công ty và vào 厚生年金 thì phần cơ bản vẫn nằm trong hệ thống 公的年金, nhưng cách tham gia và đóng sẽ đi qua công ty.',
      },
      {
        question: 'Tôi đi làm part-time có phải vào 厚生年金 không?',
        answer: 'Có thể có. 日本年金機構 cập nhật 31/03/2026 rằng từ 令和6年10月, người làm ngắn giờ ở doanh nghiệp từ 51 người trở lên có thể phải tham gia nếu đồng thời đáp ứng các điều kiện như tuần 20 giờ trở lên, lương tháng từ 8.8万円 trở lên, dự kiến làm trên 2 tháng và không phải sinh viên.',
      },
      {
        question: 'Không đủ tiền đóng thì để đó có sao không?',
        answer: 'Không nên. 日本年金機構 có các chế độ 免除, 納付猶予, 学生納付特例 và 産前産後免除. Nếu bạn đủ điều kiện mà không xin, việc để 未納 có thể làm mất bảo vệ về 障害年金 hoặc 遺族年金 và làm xấu lịch sử đóng về sau.',
      },
      {
        question: 'Về nước rồi tôi có lấy lại hết tiền nenkin đã đóng không?',
        answer: 'Không. 脱退一時金 không phải là "trả lại toàn bộ số tiền đã đóng". Đây là khoản tiền 1 lần theo công thức và trần của hệ thống. Trần này đã được nâng từ 5 năm (60 tháng) lên 8 năm (96 tháng) đóng từ 01/04/2026 (年金制度改正法), nên người đóng trên 5 năm nay nhận được nhiều hơn trước. 日本年金機構 cũng nhấn mạnh nếu bạn nhận 脱退一時金 thì lịch sử đóng tương ứng bị xóa, nên phải cân nhắc trước khi xin.',
      },
      {
        question: 'Thời hạn xin 脱退一時金 là bao lâu?',
        answer: '日本年金機構 nêu rõ phải nộp trong vòng 2 năm kể từ ngày bạn đủ điều kiện sau khi rời Nhật. Nộp trước khi xuất cảnh là không đúng quy trình.',
      },
      {
        question: 'Du học sinh có phải đóng không và có cách nào giảm không?',
        answer: 'Du học sinh trong độ tuổi vẫn có thể thuộc 国民年金. Nếu học tại trường thuộc diện áp dụng, bạn nên xin 学生納付特例. Nhật Bản năm 2026 còn đẩy mạnh việc xin online qua liên kết マイナポータル và ねんきんネット cho người đủ điều kiện tiếp tục học.',
      },
    ],
    counterPhrases: [
      {
        jp: '国民年金の免除申請をしたいです。',
        romaji: 'Kokumin nenkin no menjo shinsei o shitai desu.',
        vn: 'Tôi muốn xin miễn 国民年金.',
        note: 'Câu mở đầu tại 年金事務所 hoặc 市役所.',
      },
      {
        jp: '脱退一時金の請求方法を教えていただけますか。',
        romaji: 'Dattai ichijikin no seikyuu houhou o oshiete itadakemasu ka.',
        vn: 'Anh/chị hướng dẫn giúp cách xin 脱退一時金 (tiền hoàn 1 lần)?',
        note: 'Dùng khi sắp về nước.',
      },
      {
        jp: '必要な書類を教えていただけますか。',
        romaji: 'Hitsuyou na shorui o oshiete itadakemasu ka.',
        vn: 'Anh/chị cho tôi biết giấy tờ cần thiết được không?',
      },
      {
        jp: '基礎年金番号がわかりません。教えていただけますか。',
        romaji: 'Kiso nenkin bangou ga wakarimasen. Oshiete itadakemasu ka.',
        vn: 'Tôi không nhớ 基礎年金番号. Anh/chị tra giúp được không?',
      },
      {
        jp: '失業中ですが、免除の対象になりますか。',
        romaji: 'Shitsugyouchuu desu ga, menjo no taishou ni narimasu ka.',
        vn: 'Tôi đang thất nghiệp, có thuộc diện được miễn không?',
      },
      {
        jp: '結果はいつごろ届きますか。',
        romaji: 'Kekka wa itsugoro todokimasu ka.',
        vn: 'Khi nào tôi nhận được kết quả?',
      },
    ],
    keyTerms: [
      {
        term: '国民年金',
        reading: 'こくみんねんきん',
        meaningVi: 'lương hưu quốc dân (cho người không thuộc 厚生年金)',
        noteVi: 'Áp dụng cho: tự doanh, freelance, sinh viên, thất nghiệp, người làm part-time không đủ giờ. Mức 16,980円/tháng (2025; có thể thay đổi). Tự đóng qua 納付書 từ 市役所/年金事務所. KHÁC với 厚生年金 (qua công ty, theo lương).',
      },
      {
        term: '厚生年金',
        reading: 'こうせいねんきん',
        meaningVi: 'lương hưu cho người đi làm công ty',
        noteVi: '~9.15% lương × 2 (bạn 50% + công ty 50%). Đã bao gồm 国民年金 trong đó — không phải đóng riêng. Lương hưu khi 65 tuổi = phần cố định (như 国民年金) + phần theo lương đóng. Khi nghỉ việc → tự động chuyển sang 国民年金 (第1号) — phải đăng ký lại ở 市役所.',
      },
      {
        term: '脱退一時金',
        reading: 'だったいいちじきん',
        meaningVi: 'tiền có thể nhận một phần khi rời Nhật (KHÔNG phải hoàn toàn bộ)',
        noteVi: 'Áp dụng nếu: đã đóng ≥ 6 tháng + mất 住民票 (rời Nhật) + không có 受給権 (chưa đủ điều kiện hưởng lương hưu — < 10 năm). ⚠️ Trần tính tiền đã NÂNG từ 5 năm (60 tháng) lên 8 năm (96 tháng) theo 年金制度改正法, hiệu lực từ 01/04/2026 → người đóng trên 5 năm nay được hoàn nhiều hơn. Phải xin trong 2 năm sau khi rời Nhật. Lưu ý: nếu giữ 再入国許可 và còn ý định quay lại thì chưa xin được. 厚生年金 bị trừ ~20.42% thuế khi nhận — xin hoàn qua 確定申告 với 納税管理人.',
      },
      {
        term: '免除',
        reading: 'めんじょ',
        meaningVi: 'miễn đóng (toàn phần hoặc một phần)',
        noteVi: '4 mức: 全額免除 / 4分の3免除 / 半額免除 / 4分の1免除 — tuỳ thu nhập gia đình. Tháng miễn vẫn được tính một phần khi hưởng lương hưu (vd 全額免除 = 1/2 mức bình thường). KHÁC với 未納 (nợ không xin miễn — KHÔNG được tính). Có thể 追納 sau (trong 10 năm) để được tính full.',
      },
      {
        term: '納付猶予',
        reading: 'のうふゆうよ',
        meaningVi: 'hoãn đóng (cho người 50 tuổi trở xuống, thu nhập thấp)',
        noteVi: 'Khác với 免除. 納付猶予 = chỉ hoãn, không giảm. Tháng 猶予 không được tính khi tính tiền lương hưu, nhưng được tính vào thời gian tham gia (10 năm tối thiểu để có quyền). Phải 追納 trong 10 năm để mới có ảnh hưởng tiền.',
      },
      {
        term: '学生納付特例',
        reading: 'がくせいのうふとくれい',
        meaningVi: 'miễn đóng đặc biệt cho sinh viên',
        noteVi: 'Áp dụng cho sinh viên 第1号被保険者 thu nhập < 128万円/năm + đang học (du học sinh có visa 「留学」 cũng được). Như 納付猶予: chỉ hoãn, không được tính lương hưu — phải 追納 trong 10 năm. Mỗi năm phải xin lại tại 市役所 hoặc 年金事務所 + 在学証明書.',
      },
      {
        term: '追納',
        reading: 'ついのう',
        meaningVi: 'đóng bù sau khi đã miễn/hoãn',
        noteVi: 'Trong 10 năm kể từ tháng được miễn/hoãn. Cần thiết nếu muốn lương hưu sau này nhận đủ. Đóng càng muộn (sau 2 năm) có thể bị tính thêm "加算額" (phí tăng nhẹ). Thường thấy bảng 追納可能額 trên ねんきんネット.',
      },
      {
        term: '年金事務所',
        reading: 'ねんきんじむしょ',
        meaningVi: 'văn phòng lương hưu (chi nhánh Nenkin Kikou)',
        noteVi: 'Khác với 市役所. Đây là cơ quan trung ương cấp quốc gia. Tra "年金事務所 [thành phố]" trên Google → tìm văn phòng gần nhất. Đến đây để: xin miễn, hoàn 脱退一時金, hỏi 国際業務 (合算với nước khác), in 年金定期便 (báo cáo cá nhân).',
      },
      {
        term: '基礎年金番号',
        reading: 'きそねんきんばんごう',
        meaningVi: 'số nenkin cá nhân (10 chữ số)',
        noteVi: 'Số gắn cả đời với 1 cá nhân — dù đổi việc / về nước rồi quay lại. In trên 年金手帳 (sổ xanh / cam cũ) hoặc 基礎年金番号通知書 (giấy mới từ 2022). GIỮ KỸ — cần khi hỏi nenkin / xin 脱退一時金. Mất = xin cấp lại ở 年金事務所.',
      },
    ],
    officialLinks: [
      { label: '国民年金（やさしい日本語）— 日本年金機構', url: 'https://www.nenkin.go.jp/international/simplejapanese/japanese-system/nationalpension/nationalpension.html' },
      { label: '国民年金保険料 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/kokunen/hokenryo/hokenryo.html' },
      { label: '国民年金保険料の免除制度・納付猶予制度 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/kokunen/menjo/20150428.html?id=3770' },
      { label: '国民年金保険料の免除等の申請が可能な期間 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/kokunen/menjo/20150402-01.html' },
      { label: '国民年金保険料の免除・猶予 — 日本年金機構', url: 'https://www.nenkin.go.jp/shinsei/kokunen/menjoyuyo/index.html' },
      { label: '学生納付特例対象校一覧 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/kokunen/menjo/gakutokutaisyouko.html' },
      { label: '令和8年度の学生納付特例手続き案内 — 日本年金機構', url: 'https://www.nenkin.go.jp/oshirase/taisetu/kojin/2026/202604/040103.html' },
      { label: '短時間労働者に対する健康保険・厚生年金保険の適用拡大 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/kounen/tekiyo/jigyosho/tanjikan.html' },
      { label: '短期在留外国人の脱退一時金 — 日本年金機構', url: 'https://www.nenkin.go.jp/service/jukyu/seido/sonota-kyufu/dattai-ichiji/index.html' },
      { label: '脱退一時金を請求する方の手続き — 日本年金機構', url: 'https://www.nenkin.go.jp/service/jukyu/tetsuduki/sonota-kyufu/20140710.html' },
      { label: '退職所得となるもの — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/2725.htm' },
      { label: '退職金を受け取ったとき(退職所得) — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1420.htm' },
    ],
    steps: [
      {
        step: 1,
        title: 'Xác định bạn đang ở 国民年金 hay 厚生年金',
        description: 'Nếu bạn đi làm full-time hoặc thuộc diện công ty phải cho vào xã hội bảo hiểm, thường bạn sẽ ở 厚生年金. Nếu không thuộc diện đó mà sống ở Nhật trong độ tuổi 20-59, bạn thường rơi vào 国民年金. Đừng để bị nhầm vì chỗ này quyết định bạn phải tự đóng hay công ty trừ lương.',
        documents: [
          'Phiếu lương (給与明細)',
          'Thông báo tham gia bảo hiểm xã hội',
          'Giấy từ 年金機構 hoặc 市役所/区役所',
        ],
        tip: 'Nhiều người nghĩ chỉ có “nenkin” chung chung. Thực tế hai nhánh này khác nhau rất nhiều về cách đóng và cách xử lý khi nghỉ việc.',
      },
      {
        step: 2,
        title: 'Điền 国民年金保険料免除・納付猶予申請書 tại 年金事務所',
        description: '**Các trường trên đơn 免除・猶予申請書** (tải PDF: https://www.nenkin.go.jp/shinsei/kokunen/menjoyuyo/menjo.files/mennzyo.pdf hoặc nhận tại quầy 年金事務所):\n\n| Trường | Ghi như thế nào |\n|---|---|\n| 基礎年金番号 | Số từ 年金手帳 hoặc 基礎年金番号通知書 |\n| 氏名 / フリガナ | Tên theo 在留カード; フリガナ viết KATAKANA |\n| 生年月日 | Ngày/tháng/năm sinh (西暦 — dương lịch) |\n| 住所 | Địa chỉ hiện tại khớp với 住民票 |\n| 免除・猶予の種別 | Chọn: 全額免除 / 一部免除 / 納付猶予 |\n| 申請理由 | Lý do: 失業 / 収入減少 / 学生 / その他 |\n| 世帯主氏名 / 配偶者 | Nếu xét thu nhập chung hộ thì cần điền |\n\n日本年金機構 cho phép truy ngược tối đa 2 năm; nộp đơn sớm để không mất khoảng thời gian được bảo vệ.',
        image: require('../../../../../assets/content/daily-life/dl_nenkin_s3.jpg'),
        imageCaption: '年金事務所 — nơi nộp đơn miễn/猶予 và xử lý các thủ tục 国民年金',
        documents: [
          'Đơn miễn/猶予 — tải PDF: https://www.nenkin.go.jp/shinsei/kokunen/menjoyuyo/menjo.files/mennzyo.pdf hoặc nhận tại quầy 年金事務所',
          'Giấy tờ thu nhập hoặc thất nghiệp nếu cần',
          'Thông tin配偶者/世帯主 trong trường hợp xét điều kiện',
        ],
        tip: '未納 và 免除/猶予 là hai trạng thái rất khác nhau. 未納 có thể làm bạn mất quyền bảo vệ khi có sự cố sức khỏe hoặc tử vong trong gia đình.',
      },
      {
        step: 3,
        title: 'Nếu là du học sinh: ưu tiên 学生納付特例',
        description: 'Với nhiều du học sinh, giải pháp đúng không phải im lặng để nợ mà là xin 学生納付特例. 日本年金機構 còn cập nhật trong tháng 3 và 4/2026 rằng người đủ điều kiện có thể nhận hướng dẫn qua マイナポータル và xin online dễ hơn nếu đã liên kết với ねんきんネット.',
        documents: [
          'Giấy tờ trường học',
          'Thông tin trường thuộc danh sách対象校',
          'Tài khoản マイナポータル / ねんきんネット nếu muốn làm online',
        ],
        tip: 'Nếu học trường không nằm trong danh sách 対象校, đừng tự giả định là vẫn dùng được 学生納付特例. Hãy kiểm tra danh sách chính thức trước.',
      },
      {
        step: 4,
        title: 'Chuyển việc hoặc làm part-time: kiểm tra lại tư cách tham gia',
        description: 'Khi đổi công ty, nghỉ việc hoặc chuyển sang part-time, tư cách 年金 của bạn có thể đổi theo. Từ các cải cách đang áp dụng, người làm ngắn giờ tại doanh nghiệp từ 51 người trở lên vẫn có thể vào 厚生年金 nếu đủ điều kiện về giờ, lương và thời hạn làm việc.',
        documents: [
          'Hợp đồng lao động mới',
          'Số giờ làm/tuần',
          'Mức lương tháng theo hợp đồng',
        ],
        tip: 'Nhiều người tưởng làm part-time là chắc chắn không vào 社会保険. Điều đó không còn đúng trong rất nhiều công ty từ sau mở rộng áp dụng.',
      },
      {
        step: 5,
        title: 'Trước khi về nước: cân nhắc kỹ 脱退一時金',
        description: '日本年金機構 nêu rõ nếu bạn là người không có quốc tịch Nhật, đã rời hệ thống bảo hiểm công và rời Nhật, bạn có thể xin 脱退一時金 nếu đáp ứng đủ điều kiện. Nhưng phải nhớ: nhận khoản này đồng nghĩa record tương ứng bị xóa. Nếu sau này bạn quay lại Nhật hoặc có hiệp định an sinh xã hội với nước mình, bài toán có thể khác.',
        documents: [
          'Ngày rời Nhật',
          'Thông tin thời gian đã tham gia 国民年金/厚生年金',
          'Tài khoản nhận tiền ở nước ngoài',
        ],
        tip: 'Đây không phải nút “rút hết cho nhanh”. Với người có ý định quay lại Nhật hoặc cộng dồn thời gian bảo hiểm theo hiệp định, quyết định này cần nghĩ dài hạn hơn.',
      },
      {
        step: 6,
        title: 'Nếu xin 脱退一時金 của 厚生年金: để ý cả phần thuế',
        description: '国税庁 (NTA) xem một số khoản tiền 1 lần liên quan hệ thống 年金 là 退職所得. Nếu không có thủ tục phù hợp, khoản chi trả có thể bị khấu trừ thuế ở mức 20.42%. Nhiều trường hợp muốn lấy lại phần khấu trừ này phải thông qua 納税管理人 và thủ tục thuế riêng sau đó.',
        documents: [
          'Giấy quyết định chi trả 脱退一時金',
          'Chứng từ khấu trừ thuế nếu có',
          'Hồ sơ 納税管理人 nếu muốn xử lý hoàn thuế',
        ],
        tip: 'Rất nhiều người chỉ nhìn số tiền nhận về mà không biết còn bài toán thuế phía sau. Nếu bỏ qua bước này, bạn có thể mất một khoản không nhỏ.',
      },
    ],
  };

export default pensionExemptionRefund;
