import type { AdminGuide } from '../../../../types/content';

const permanentResidencyEijuu: AdminGuide = {
    id: 'permanent-residency-eijuu',
    category: 'immigration',
    lastVerified: '2026-09-21',
    priority: 'normal',
    title: 'Xin vĩnh trú (永住許可申請)',
    titleJp: '永住許可申請の要件と手続き',
    icon: 'home',
    color: '#1A5276',
    description: 'Tư cách 永住者 (vĩnh trú) cho phép ở lại Nhật vô thời hạn và làm bất kỳ công việc nào — đây là tư cách lưu trú ổn định nhất dành cho người nước ngoài không có quốc tịch Nhật. Hồ sơ phức tạp và thời gian xét duyệt dài, nhưng điều kiện có thể đáp ứng sớm hơn nhiều người nghĩ.',
    searchKeywords: [
      'xin vĩnh trú',
      '永住',
      'eijuu',
      '永住者',
      'eijuusha',
      '永住許可',
      '永住許可申請',
      'eijuu kyoka',
      'permanent residency Japan',
      'permanent resident',
      'PR',
      '身元保証人',
      'mimoto hoshounin',
      'người bảo lãnh',
      '住民税',
      'lịch sử thuế',
      '年金',
      'nenkin',
      'lịch sử bảo hiểm',
      '高度専門職',
      'koudo senmonshoku',
      'HSP',
      '日本人の配偶者',
      'continuous residence 10 years',
      '永住取消',
      '永住許可の取消し',
      'thu hồi vĩnh trú',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: '永住許可申請 do ISA xét toàn quốc; đây là hồ sơ xét tổng thể về cư trú, thuế, bảo hiểm, thu nhập, tuân thủ pháp luật và tình trạng hiện tại.',
      sourceVerifiedAt: '2026-09-21',
      nextReviewAt: '2026-10-15',
      riskLevel: 'high',
      whenToAskExpert: [
        'Bạn có kỳ thuế, 年金, bảo hiểm, giao thông hoặc xuất nhập cảnh từng bị trễ/vi phạm.',
        'Bạn đang giữ thời hạn lưu trú ngắn, sắp hết hạn hoặc hồ sơ đang chờ nhưng visa hiện tại sắp hết hạn.',
        'Bạn dùng diện rút ngắn như spouse, 高度専門職 70/80 điểm hoặc hồ sơ gia đình/phụ thuộc phức tạp.',
      ],
    },
    quickAction: {
      deadline: 'Nộp trước ngày hết hạn lưu trú hiện tại; nếu đang chờ 永住 mà visa hiện tại sắp hết hạn, vẫn phải nộp gia hạn riêng trước hạn.',
      office: 'Cục xuất nhập cảnh có thẩm quyền theo nơi cư trú.',
      doNow: [
        'Rà lịch sử thuế, 年金, bảo hiểm và xuất nhập cảnh trước khi đặt mục tiêu nộp.',
        'Dùng checklist ISA đúng diện của bạn, không dùng checklist truyền miệng.',
        'Đặt nhắc hạn gia hạn visa hiện tại trong suốt thời gian chờ 永住.',
      ],
      bring: ['永住許可申請書', 'Ảnh thẻ 4cm x 3cm', 'Hộ chiếu', 'Thẻ cư trú', '理由書', '住民票', 'Giấy tờ thuế/thu nhập/年金/bảo hiểm', '身元保証書'],
      ifLate: 'Nếu visa hiện tại sắp hết hạn, ưu tiên hỏi/nộp gia hạn thời hạn lưu trú; 永住 đang xét không tự kéo dài thời hạn lưu trú.',
      officialSourceLabels: ['永住許可申請 — 出入国在留管理庁', '永住許可に関するガイドライン — 出入国在留管理庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_permanent-residency_hero.jpg'),
    heroImageCaption: '永住許可申請 - chuẩn bị hồ sơ cư trú, thuế và bảo hiểm trước khi nộp',
    whoIsThisFor: [
      'Người đã sống ở Nhật liên tục đủ năm theo điều kiện và muốn ổn định lâu dài.',
      'Người có điểm số Highly Skilled Professional (高度専門職) từ 70+ điểm — đủ điều kiện xin sau 3 năm.',
      'Vợ/chồng của người Nhật hoặc 永住者 đã sống ở Nhật liên tục từ 3 năm — đủ điều kiện sau 3 năm.',
    ],
    whenToDo: [
      'Điều kiện thông thường: sống ở Nhật liên tục 10 năm, trong đó có ít nhất 5 năm làm việc hoặc có tư cách lao động.',
      'Điều kiện rút ngắn: vợ/chồng người Nhật/永住者 (3 năm), Highly Skilled Professional từ 70 điểm (3 năm), 80 điểm (1 năm).',
      '⚠️ Thay đổi từ 24/02/2026: tư cách lưu trú hiện tại phải là loại 5 năm (在留期間5年) — người đang giữ thẻ 3 năm không đủ điều kiện nộp. Trường hợp đang giữ thẻ 3 năm có thời gian chuyển tiếp đến 31/03/2027.',
    ],
    whereToDo: [
      'Cục xuất nhập cảnh (ISA) có thẩm quyền theo nơi cư trú.',
      'Municipal office nơi cư trú: xin giấy chứng nhận thu nhập, thuế cư trú và các giấy liên quan đến hộ gia đình.',
      '税務署: xin chứng nhận thuế quốc gia theo checklist ISA nếu thuộc diện phải nộp.',
      '年金事務所, Nenkin Net, municipal office hoặc công ty: chuẩn bị bằng chứng nộp lương hưu và bảo hiểm y tế.',
    ],
    documentsChecklist: [
      { label: '永住許可申請書', required: true },
      { label: 'Ảnh thẻ 4cm x 3cm', required: true, note: 'Theo chuẩn ảnh của ISA; người dưới 16 tuổi có thể khác.' },
      { label: '理由書', required: true, note: 'Nếu viết ngoài tiếng Nhật, cần bản dịch tiếng Nhật.' },
      { label: '住民票 toàn hộ', required: true, note: 'Không ghi My Number; giấy Nhật thường phải còn trong 3 tháng.' },
      { label: 'Hộ chiếu và 在留カード', required: true },
      { label: 'Giấy chứng minh nghề nghiệp, thu nhập, thuế, lương hưu và bảo hiểm', required: true, note: 'Số năm và loại giấy phụ thuộc tư cách lưu trú; dùng checklist ISA theo diện của bạn.' },
      { label: '身元保証書 và giấy tờ người bảo lãnh', required: true, note: 'Thường là người Nhật, 永住者 hoặc 特別永住者 cư trú tại Nhật.' },
      { label: '永住許可申請セルフチェックシート', required: false, note: 'ISA khuyến nghị dùng và nộp kèm để tự kiểm tra trước khi nộp.' },
    ],
    tips: [
      'Chuẩn bị hồ sơ **trước 6 tháng** so với ngày dự kiến nộp — đủ thời gian xin các giấy chứng nhận thuế, 年金, bảo hiểm và bổ sung nếu thiếu.',
      'Check điểm 高度専門職 tại trang tính điểm chính thức của ISA **trước khi nộp** — điểm tính theo thời điểm nộp, không phải thời điểm đủ điều kiện ban đầu. Nghề nghiệp, bằng cấp, thu nhập đều ảnh hưởng.',
      'Sau khi có 永住, vẫn phải tiếp tục nộp thuế + 国民健康保険 + 年金 đúng hạn. Từ 14/06/2026 cố tình bỏ đóng có thể là lý do thu hồi tư cách 永住者. Nếu gặp khó khăn tài chính → xin miễn giảm tại cơ quan liên quan, không bỏ ngơ.',
    ],
    commonMistakes: [
      'Nộp 永住 nhưng quên gia hạn tư cách lưu trú hiện tại khi sắp hết hạn.',
      'Chuẩn bị giấy tờ theo kinh nghiệm người khác mà không dùng checklist đúng diện của mình.',
      'Có kỳ thuế, 年金 hoặc bảo hiểm nộp trễ nhưng không kiểm tra trước khi nộp.',
      'Nộp giấy chứng nhận Nhật đã quá 3 tháng hoặc giấy nước ngoài không kèm bản dịch tiếng Nhật.',
      'Tưởng đủ số năm cư trú là chắc chắn được cấp; 永住 vẫn là hồ sơ xét tổng thể.',
      'Tưởng có 永住 rồi là "an toàn vĩnh viễn" — từ 14/06/2026 cố ý không nộp thuế/bảo hiểm/年金 hoặc phạm tội nghiêm trọng có thể bị thu hồi tư cách 永住者 (永住許可の取消し).',
      'Chờ "đến khi chắc chắn đủ điều kiện tốt nhất" mới nộp — trong khi ISA đang dự thảo siết thêm điều kiện (thu nhập, tiếng Nhật B1, thời gian vợ/chồng) có thể có hiệu lực từ 2027 hoặc hồi tố một phần từ 2026. Nếu đã đủ điều kiện HIỆN HÀNH, cân nhắc nộp sớm thay vì chờ.',
    ],
    faq: [
      {
        question: 'Đang chờ 永住 mà visa hiện tại sắp hết hạn thì sao?',
        answer: 'Phải nộp 在留期間更新許可申請 trước ngày hết hạn. ISA nêu rõ 永住 đang xét không tự kéo dài tư cách lưu trú hiện tại.',
      },
      {
        question: 'Thời gian xét 永住 là bao lâu?',
        answer: 'ISA công bố thời gian xử lý chuẩn là 4-6 tháng. Nếu thiếu giấy tờ hoặc bị yêu cầu bổ sung, thời gian thực tế có thể dài hơn.',
      },
      {
        question: 'Có nên nộp khi hồ sơ thuế hoặc bảo hiểm chưa sạch không?',
        answer: 'Không nên. Với 永住, lịch sử nộp thuế, lương hưu và bảo hiểm là phần bị kiểm tra rất kỹ. Nên rà trước tại municipal office, 税務署 và 年金事務所.',
      },
      {
        question: '⚠️ MỚI 2026: Có 永住 rồi vẫn có thể bị THU HỒI không?',
        answer: 'Có, theo luật mới. Sửa đổi 入管法 2024 bổ sung quy định 永住許可の取消し (thu hồi vĩnh trú), có hiệu lực từ **14/06/2026** (đã có hiệu lực). ISA có thể xem xét thu hồi tư cách 永住者 trong các trường hợp như: **CỐ Ý (故意) không nộp thuế / 住民税 / 国民健康保険 / 年金 dù có khả năng nộp**; hoặc phạm một số tội cố ý nghiêm trọng (vd trộm cắp, lừa đảo). Điểm quan trọng: nhắm vào hành vi **cố tình** — trường hợp thực sự mất khả năng do bệnh tật, thất nghiệp được loại trừ. Trong một số trường hợp ISA có thể chuyển sang tư cách lưu trú khác thay vì trục xuất. Kết luận thực tế: sau khi có 永住 vẫn phải tiếp tục nộp đầy đủ thuế + bảo hiểm + lương hưu đúng hạn. Nếu gặp khó khăn tài chính → xin 免除 / phân kỳ tại cơ quan liên quan, KHÔNG bỏ ngơ. Tình huống cụ thể: hỏi 行政書士 / luật sư chuyên 入管.',
      },
      {
        question: '⚠️ MỚI 08/2026: Nghe nói ISA sắp siết toàn bộ tiêu chuẩn xét 永住 — có thật không?',
        answer: 'ĐANG DỰ THẢO, CHƯA CHÍNH THỨC. Ngày **04/08/2026** ISA công bố bản rà soát tổng thể 永住許可ガイドライン, lấy ý kiến công khai (パブリックコメント) đến **04/09/2026**. Nội dung dự thảo đáng chú ý: (1) yêu cầu thu nhập hộ gia đình phải trên mức trung bình cả nước, tính cả thân nhân phụ thuộc đang ở nước ngoài; (2) thêm kiểm tra tài sản/lương hưu; (3) yêu cầu MỚI về tiếng Nhật — tương đương CEFR B1; (4) diện vợ/chồng người Nhật/永住者 kéo dài thời gian đủ điều kiện từ 3 năm kết hôn/1 năm cư trú lên **5 năm kết hôn/3 năm cư trú**; (5) lịch sử thuế/bảo hiểm bị tính là yếu tố trừ điểm nặng hơn hiện tại. Mốc hiệu lực chính dự kiến **01/04/2027**, nhưng phần điều kiện thu nhập + nghĩa vụ công có thể áp dụng HỒI TỐ từ **01/04/2026** cho hồ sơ vẫn đang xét tại thời điểm **01/10/2026**. **Cập nhật 21/09/2026**: đã hết hạn góp ý 04/09; theo báo chí ISA dự kiến ban hành bản chính thức khoảng tháng 10/2026, hiện chưa có bản cuối. **Phí nộp hồ sơ 永住 cũng tăng từ 10,000 yên lên 200,000 yên với hồ sơ tiếp nhận từ 01/10/2026** (theo 政令案 ISA 03/07/2026; hồ sơ tiếp nhận đến 30/09/2026 vẫn 10,000 yên). Vì chưa chốt, số liệu/điều kiện cụ thể có thể thay đổi trước khi ban hành — nếu bạn đang cân nhắc nộp 永住 diện vợ/chồng hoặc thu nhập sát ngưỡng, nên nộp sớm hoặc hỏi 行政書士/luật sư về rủi ro chuyển tiếp thay vì chờ.',
      },
    ],
    scenarios: [
      {
        title: 'Đang giữ visa 3 năm — có nộp 永住 được không?',
        situation: 'Tôi ở Nhật 10 năm, visa kỹ thuật 3 năm, không có tiền án tiền sự, thuế và lương hưu đều ổn. Nhưng nghe nói phải có visa 5 năm mới được nộp永住. Đúng không?',
        answer: 'Đúng. Từ **02/2026**, một trong các điều kiện mới là phải đang giữ **tư cách lưu trú 5 năm (在留期間5年)** tại thời điểm nộp đơn 永住. Trường hợp của bạn cần làm **thủ tục gia hạn lên 5 năm trước** (申請先: ISA). Sau khi có thẻ 5 năm mới đủ điều kiện nộp 永住. Nếu sắp hết hạn thẻ 3 năm, hãy nộp gia hạn ngay — không nên chờ đủ điều kiện rồi mới gia hạn vì có thể bị "trống thẻ".',
      },
      {
        title: 'Tự kinh doanh — hồ sơ thuế cần chuẩn bị gì thêm?',
        situation: 'Tôi kinh doanh tự do (個人事業主) đã 6 năm. Hồ sơ thuế, nă金, bảo hiểm đều đúng hạn. Có gì khác với người đi làm không?',
        answer: 'Người tự kinh doanh (個人事業主) cần chuẩn bị thêm: **確定申告書 (bản nộp + bản xác nhận của 税務署)** 3–5 năm gần nhất, **納税証明書 (その1・その2)** từ 税務署, và **事業の概要** (tóm tắt ngành nghề, doanh thu). Điểm ISA chú ý là **tính ổn định thu nhập** — nếu thu nhập dao động lớn hoặc có năm âm, nên chuẩn bị thêm tài liệu giải thích. Không cần giấy tờ công ty như người đi làm, nhưng hồ sơ thuế phải cực kỳ sạch.',
      },
      {
        title: 'Đang xét 永住 bị từ chối, muốn nộp lại',
        situation: 'Tôi bị từ chối 永住 vì "không đủ tín nhiệm (素行不良)". Có thể nộp lại không và sau bao lâu?',
        answer: 'Không có quy định cứng về thời gian chờ sau khi bị từ chối — pháp lý cho phép nộp lại ngay. Nhưng thực tế, nếu lý do từ chối chưa được khắc phục, nộp ngay sẽ lại bị từ chối. Bước quan trọng: **yêu cầu ISA giải thích lý do từ chối** (không có quyền chính thức nhưng họ thường cung cấp thông tin cơ bản), sau đó xác định chính xác vấn đề. Nếu là 素行 (nộp thuế trễ, vi phạm giao thông nhiều lần...): cần ít nhất **1–2 năm lịch sử tốt** sau khi sửa trước khi nộp lại. Hỏi 行政書士 chuyên 永住 để phân tích hồ sơ cụ thể.',
      },
    ],
    counterPhrases: [
      {
        jp: '永住許可申請をしたいのですが、書類を教えてください。',
        romaji: 'Eijuu kyoka shinsei o shitai no desu ga, shorui o oshiete kudasai.',
        vn: 'Tôi muốn nộp đơn xin vĩnh trú, cho tôi biết giấy tờ cần thiết.',
        note: 'Câu mở đầu tại quầy ISA — họ sẽ đưa checklist theo diện của bạn.',
      },
      {
        jp: '在留期間を5年に更新したいです。',
        romaji: 'Zairyuu kikan o gonen ni koushin shitai desu.',
        vn: 'Tôi muốn gia hạn thời hạn lưu trú lên 5 năm.',
        note: 'Từ 02/2026 nộp 永住 yêu cầu phải đang giữ thẻ 5 năm — gia hạn trước nếu đang 3 năm.',
      },
      {
        jp: '審査にはどれくらい時間がかかりますか。',
        romaji: 'Shinsa ni wa dorekurai jikan ga kakarimasu ka.',
        vn: 'Xét duyệt mất bao lâu?',
        note: 'Thực tế 6 tháng đến 1 năm+, ISA không cam kết thời gian chính xác.',
      },
      {
        jp: '審査中ですが、現在の在留期限が切れそうです。',
        romaji: 'Shinsachuu desu ga, genzai no zairyuu kigen ga kiresou desu.',
        vn: 'Hồ sơ đang xét nhưng visa hiện tại sắp hết hạn.',
        note: 'Quan trọng — phải nộp gia hạn (更新) riêng, không nằm trong hồ sơ vĩnh trú.',
      },
      {
        jp: '身元保証人を変更したいです。',
        romaji: 'Mimoto hoshounin o henkou shitai desu.',
        vn: 'Tôi muốn đổi người bảo lãnh.',
        note: 'Khi người bảo lãnh cũ chuyển công việc / sang nước khác / không liên hệ được.',
      },
    ],
    keyTerms: [
      {
        term: '永住者',
        reading: 'えいじゅうしゃ',
        meaningVi: 'người vĩnh trú',
        noteVi: 'KHÁC với 帰化 (kika = nhập quốc tịch). 永住者 vẫn giữ quốc tịch Việt Nam + hộ chiếu VN; chỉ có quyền ở Nhật vô thời hạn + làm bất kỳ công việc nào. Phải đổi 在留カード vật lý mỗi 7 năm (cho người lớn) hoặc 16 tuổi (trẻ em). ⚠️ Không phải "an toàn vĩnh viễn": từ 14/06/2026 (sửa 入管法) cố ý không nộp thuế/bảo hiểm/年金 hoặc phạm tội nghiêm trọng có thể bị thu hồi 永住 — xem mục 永住許可の取消し.',
      },
      {
        term: '永住許可申請',
        reading: 'えいじゅうきょかしんせい',
        meaningVi: 'đơn xin vĩnh trú',
        noteVi: 'Nộp tại ISA. Phí 8,000円 — chỉ trả khi được duyệt (dán印紙 lên giấy). Bị từ chối → mất công + thời gian, không hoàn phí. Có thể nộp lại sau khi cải thiện hồ sơ.',
      },
      {
        term: '身元保証人',
        reading: 'みもとほしょうにん',
        meaningVi: 'người bảo lãnh',
        noteVi: 'Bắt buộc cho hồ sơ 永住. Phải là người Nhật hoặc 永住者 đã sống ở Nhật, có thu nhập ổn định. KHÔNG có trách nhiệm trả nợ pháp lý — chỉ là cam kết hỗ trợ tinh thần. Thường nhờ sếp / bạn thân / vợ-chồng Nhật.',
      },
      {
        term: '継続在留',
        reading: 'けいぞくざいりゅう',
        meaningVi: 'cư trú liên tục',
        noteVi: 'Tiêu chí thời gian: 10 năm cư trú + 5 năm làm việc (chuẩn). Rút ngắn cho diện: 高度専門職 70 điểm = 3 năm, 80 điểm = 1 năm; vợ/chồng Nhật-vĩnh trú = 3 năm hôn nhân + 1 năm cư trú; 定住者 = 5 năm. Rời Nhật >100 ngày/năm hoặc 1 lần >3 tháng có thể reset đồng hồ.',
      },
      {
        term: '独立生計',
        reading: 'どくりつせいけい',
        meaningVi: 'năng lực tài chính độc lập',
        noteVi: 'Tiêu chí thu nhập. Tham khảo: ~3 triệu yên/năm (cho 1 người độc thân; tăng theo số người phụ thuộc — vợ +50 vạn, mỗi con +30 vạn). Từ 06/2026 ISA dùng My Number kiểm tra thực tế lịch sử thuế / 年金 / bảo hiểm, không chỉ dựa giấy tờ.',
      },
      {
        term: '永住許可の取消し',
        reading: 'えいじゅうきょかのとりけし',
        meaningVi: 'thu hồi tư cách vĩnh trú (quy định mới, hiệu lực 14/06/2026)',
        noteVi: 'Sửa đổi 入管法 2024. Từ 14/06/2026 ISA có thể thu hồi 永住者 nếu: CỐ Ý không nộp thuế / 国民健康保険 / 年金 dù có khả năng nộp; hoặc phạm một số tội cố ý nghiêm trọng. Loại trừ trường hợp thực sự mất khả năng do bệnh / thất nghiệp. → Sau khi có 永住 vẫn phải nộp đầy đủ nghĩa vụ công đúng hạn; khó khăn thì xin 免除/分割, không bỏ ngơ. Nguồn: ISA moj.go.jp/isa/05_00045.html.',
      },
      {
        term: '永住許可ガイドライン改訂案',
        reading: 'えいじゅうきょかガイドラインかいていあん',
        meaningVi: 'dự thảo sửa toàn bộ tiêu chuẩn xét vĩnh trú (08/2026, CHƯA chính thức)',
        noteVi: 'ISA công bố 04/08/2026, lấy ý kiến công khai đến 04/09/2026. Dự kiến siết: thu nhập hộ phải trên trung bình cả nước (tính cả thân nhân phụ thuộc ở nước ngoài), thêm kiểm tra tài sản/年金, yêu cầu MỚI tiếng Nhật CEFR B1, diện vợ/chồng kéo dài 3→5 năm kết hôn + 1→3 năm cư trú, lịch sử thuế/bảo hiểm trừ điểm nặng hơn. Hiệu lực chính dự kiến 01/04/2027; phần thu nhập/nghĩa vụ công có thể hồi tố từ 01/04/2026 cho hồ sơ còn treo tại 01/10/2026. CHƯA ban hành chính thức — theo dõi lại quanh 04/09/2026.',
      },
    ],
    officialLinks: [
      { label: '永住許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-4.html' },
      { label: '永住許可に関するガイドライン — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/resources/nyukan_nyukan50.html' },
      { label: '入管法改正（永住許可制度の適正化）— 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/05_00045.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra đủ điều kiện không',
        description: 'ISA xét dựa trên 4 tiêu chí chính:\n\n**1. Thời gian cư trú liên tục:** không được rời Nhật quá 100 ngày/năm hoặc 1 lần quá 3 tháng trong giai đoạn xét.\n\n**2. Tuân thủ pháp luật:** không có tiền án, không vi phạm Luật Xuất nhập cảnh, không nợ thuế hay bảo hiểm.\n\n**3. Năng lực tài chính độc lập:** thu nhập và tài sản đủ để không cần hỗ trợ nhà nước — ~3 triệu yên/năm là tham khảo phổ biến. Từ tháng 6/2026 ISA có thể dùng My Number để kiểm tra thực tế lịch sử nộp thuế và bảo hiểm.\n\n**4. Tư cách lưu trú phải là loại 5 năm** (hiệu lực từ 24/02/2026): người đang giữ thẻ 3 năm không được nộp. Gia hạn lên 5 năm trước rồi mới nộp 永住. Trường hợp đang giữ thẻ 3 năm có thời gian chuyển tiếp đến 31/03/2027 — xác nhận lại với ISA.',
        documents: [],
        tip: 'Kiểm tra lịch sử xuất nhập cảnh trên passport trước — mỗi lần nhập cảnh có đóng dấu. Nếu đã ở Nhật qua nhiều visa, tính tổng thời gian thực tế ở Nhật, không phải thời gian hiệu lực visa.',
      },
      {
        step: 2,
        title: 'Chuẩn bị hồ sơ — phần cá nhân',
        description: 'Hồ sơ cơ bản gồm:\n• Đơn xin 永住許可申請書\n• Lý do xin (理由書) — viết tay hoặc đánh máy, giải thích lý do muốn ở lại lâu dài và đóng góp cho xã hội Nhật\n• Ảnh 4×3 cm\n• Hộ chiếu (tất cả passport đã dùng từ khi sang Nhật)\n• Thẻ cư trú 在留カード\n• Giấy tờ tình trạng gia đình: 住民票 toàn hộ (世帯全員), giấy kết hôn, khai sinh con (nếu có)\n• Nhật ký nhập cảnh (xuất/nhập cảnh đủ theo passport)',
        documents: [
          'Đơn xin 永住許可申請書',
          'Lý do xin (理由書)',
          'Hộ chiếu tất cả đã dùng kể từ khi sang Nhật',
          '在留カード',
          '住民票 (世帯全員分)',
          'Giấy tờ gia đình nếu có',
        ],
        tip: '理由書 không có mẫu cố định — viết trung thực, cụ thể về công việc, gia đình, đóng góp cộng đồng và kế hoạch tương lai tại Nhật. Một trang A4 thường đủ.',
      },
      {
        step: 3,
        title: 'Chuẩn bị hồ sơ — phần tài chính và thuế',
        description: 'Đây là phần quan trọng nhất và thường bị thiếu:\n• 源泉徴収票 3 năm gần nhất (giấy tóm tắt thu nhập và thuế đã nộp do công ty cấp)\n• 確定申告書 控え 3 năm (nếu tự khai thuế)\n• Giấy xác nhận nộp thuế đầy đủ: 納税証明書 その1 và その2 — xin tại tax office (税務署) gần nhà\n• Giấy xác nhận nộp 住民税 đầy đủ: xin tại municipal office\n• Giấy xác nhận đóng 国民健康保険 hoặc 社会保険 — xin tại municipal office hoặc từ công ty\n• Sổ tiết kiệm hoặc sao kê tài khoản 6 tháng gần nhất (chứng minh tài chính)',
        documents: [
          '源泉徴収票 3 năm gần nhất',
          '納税証明書 その1・その2 (từ 税務署)',
          'Giấy xác nhận nộp 住民税 đầy đủ (từ municipal office)',
          'Giấy xác nhận đóng bảo hiểm y tế và 年金',
          'Sao kê tài khoản ngân hàng 6 tháng',
        ],
        tip: 'Nếu có bất kỳ kỳ nào trễ hạn nộp thuế hoặc bảo hiểm — dù chỉ 1 tháng — ISA có thể từ chối toàn bộ đơn. Kiểm tra và thanh toán hết nợ đọng trước khi nộp đơn.',
      },
      {
        step: 4,
        title: 'Nộp hồ sơ và chờ kết quả',
        description: 'Nộp tại ISA có thẩm quyền theo địa chỉ cư trú hoặc theo kênh nộp được ISA chấp nhận nếu bạn thuộc đối tượng dùng được. Thời gian xử lý chuẩn ISA công bố là 4-6 tháng; hồ sơ thiếu hoặc cần bổ sung có thể lâu hơn. Trong thời gian chờ, tư cách lưu trú hiện tại vẫn hiệu lực — nhớ gia hạn đúng hạn nếu hết hạn trong khi đang chờ.\n\nNếu bị từ chối: thường cần chờ cải thiện hồ sơ (thu nhập, tuân thủ thuế, thời gian cư trú thêm) rồi nộp lại sau khi đã xác định điểm yếu.',
        documents: [
          'Toàn bộ hồ sơ từ bước 2 và 3',
          'Phong bì dán tem có ghi địa chỉ của bạn (để ISA gửi kết quả về nhà)',
        ],
        tip: 'Sau khi nhận 永住者, thẻ cư trú có hiệu lực 7 năm và cần gia hạn thẻ vật lý định kỳ — nhưng tư cách lưu trú không hết hạn. Vẫn phải thực hiện các nghĩa vụ như nộp thuế, cập nhật địa chỉ và không vi phạm pháp luật để giữ tư cách này.',
      },
    ],
  };

export default permanentResidencyEijuu;
