import type { AdminGuide } from '../../../../types/content';

const remittance: AdminGuide = {
    id: 'remittance',
    category: 'money',
    lastVerified: '2026-07-11',
    priority: 'normal',
    title: 'Chuyển tiền về Việt Nam',
    titleJp: 'ベトナムへの海外送金',
    icon: 'send',
    color: '#8E44AD',
    description: 'Hướng dẫn chọn dịch vụ chuyển tiền từ Nhật về Việt Nam. Phí, tỷ giá, hạn mức và thời gian nhận thay đổi theo nhà cung cấp.',
    searchKeywords: [
      'gửi tiền về Việt Nam',
      'chuyển tiền về nhà',
      'remittance',
      'ベトナム送金',
      'betonamu soukin',
      '海外送金 ベトナム',
      'kaigai soukin',
      'SBI Remit',
      'Wise',
      'wise transfer',
      'Seven Bank Remit',
      'Western Union',
      'MoneyGram',
      'Revolut',
      '資金移動業者',
      'shikin idou gyousha',
      'Money Transfer Operator',
      '為替レート',
      'kawase reeto',
      'tỷ giá',
      '送金手数料',
      'phí chuyển tiền',
      'SWIFT code',
      'BIC code',
      '家族への仕送り',
      'mục đích gửi tiền',
      '受取人',
      'tên người nhận không dấu',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Mọi dịch vụ chuyển tiền tại Nhật BẮT BUỘC đăng ký với 金融庁 là 銀行 hoặc 資金移動業者 (Funds Transfer Service Provider) theo 資金決済法. Tra danh sách hợp pháp tại trang 金融庁. Chuyển > 100万円/lần ra nước ngoài tự động báo cáo 国税庁 qua 国外送金等調書. Dùng kênh KHÔNG đăng ký (cá nhân trung gian, hawala) = vi phạm 銀行法 + 資金決済法 — rủi ro hình sự.',
      sourceVerifiedAt: '2026-05-16',
      nextReviewAt: '2026-12-01',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Gửi đều > 100万円/lần cho mục đích kinh doanh / đầu tư / mua BĐS ở VN → tham vấn 税理士 quốc tế + 弁護士 trước khi bắt đầu — có thể bị 贈与税 hoặc 申告 nghĩa vụ.',
        'Tiền không đến / mất tích / bị giữ quá 1 tuần → liên hệ dịch vụ với 受付番号; nếu không giải quyết → 金融庁 金融サービス利用者相談室 0570-016811.',
        'Nhận tiền lớn từ VN (vd cha mẹ gửi, thừa kế) > 110万円/năm → có thể bị 贈与税 ở Nhật — hỏi 税理士 hoặc 税務署 trước khi nhận.',
        'Bị dụ dùng "dịch vụ tốc độ cao" qua cá nhân trung gian / Zalo group → KHÔNG dùng, đó là kênh trái phép — báo 金融庁 nếu nghi.',
      ],
    },
    quickAction: {
      deadline: 'Không có hạn cố định, nhưng: giao dịch đầu tiên cần thời gian xác minh (1-3 ngày), khoản lớn có thể chậm thêm. Gửi sớm trước hạn cần tiền.',
      office: 'App / website dịch vụ chuyển tiền đã đăng ký (SBI Remit / Wise / Seven Bank Remit / Western Union qua 7-Eleven). 金融庁 danh sách 資金移動業者. Hotline mỗi dịch vụ riêng cho hỗ trợ.',
      doNow: [
        'Chọn 1 dịch vụ đã đăng ký 金融庁 (SBI Remit / Wise / Seven Bank Remit / Revolut) — KHÔNG dùng cá nhân trung gian / Zalo group.',
        'Đăng ký app / tài khoản + nộp 本人確認 (在留カード + マイナンバー nếu yêu cầu) — mất 1-3 ngày.',
        'Trước mỗi lần gửi: so sánh tổng cost (phí + tỷ giá) qua app/website. Wise thường có tỷ giá tốt; SBI Remit nhanh nhận tiền mặt tại VN; Seven Bank tiện 24h.',
        'Điền thông tin người nhận CHÍNH XÁC: tên không dấu (khớp sổ ngân hàng VN) + tên ngân hàng tiếng Anh + số tài khoản + chi nhánh + SWIFT/BIC.',
        'Khai mục đích: 家族への仕送り (gửi gia đình) / 学費 (học phí) / 個人的なため (cá nhân). Khai trung thực.',
        'Lưu 受付番号 / transaction ID — cần nếu tiền chậm / mất.',
      ],
      bring: [
        '在留カード còn hạn',
        'マイナンバー (12 chữ số — nhiều dịch vụ yêu cầu)',
        'Tài khoản ngân hàng Nhật (cho nạp tiền)',
        'Thông tin người nhận: tên không dấu + ngân hàng + số TK + chi nhánh + SWIFT/BIC',
        'Số điện thoại Nhật (cho OTP)',
        'Email Nhật',
      ],
      ifLate: 'Tiền không đến sau thời gian dự kiến: liên hệ dịch vụ với 受付番号 trong 1 tuần. Quá 1 tuần không phản hồi → escalate lên 金融庁. Sai tên / số TK người nhận: tiền tự hoàn về sau 5-10 ngày, mất phí xử lý ¥1,500-3,000. Dùng kênh trái phép (cá nhân trung gian): KHÔNG có cách lấy lại tiền hợp pháp + có thể bị điều tra.',
      officialSourceLabels: ['Danh sách業者 đăng ký — 金融庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/dl_post-office_s2.jpg'),
    heroImageCaption: 'Gửi tiền quốc tế - so sánh phí, tỷ giá, hạn mức và cách người nhận nhận tiền',
    whoIsThisFor: [
      'Người Việt ở Nhật cần gửi tiền về cho gia đình hoặc tài khoản cá nhân tại Việt Nam.',
      'Người mới đi làm tại Nhật chưa biết nên dùng ngân hàng, dịch vụ remit hay app chuyển tiền.',
      'Người muốn tránh trung gian không rõ pháp lý và kiểm tra đúng thông tin người nhận trước khi gửi.',
    ],
    whenToDo: [
      'Trước khi gửi lần đầu, đăng ký và xác minh danh tính sớm vì có thể mất thời gian.',
      'Kiểm tra phí, tỷ giá và số tiền người nhận thực nhận ngay trước mỗi lần gửi.',
      'Với khoản lớn hoặc giao dịch đầu tiên, nên gửi sớm hơn hạn cần tiền vì có thể bị xác minh bổ sung.',
    ],
    whereToDo: [
      'Ứng dụng hoặc website của dịch vụ chuyển tiền đã đăng ký tại Nhật.',
      'ATM/quầy của ngân hàng hoặc dịch vụ như Seven Bank, SBI Remit, Wise tùy nhà cung cấp.',
      'Danh sách 金融庁 để kiểm tra dịch vụ có đăng ký hợp pháp tại Nhật.',
    ],
    documentsChecklist: [
      { label: 'Thẻ cư trú hoặc giấy tờ định danh được dịch vụ chấp nhận', required: true },
      { label: 'Giấy tờ My Number', required: false, note: 'Một số dịch vụ yêu cầu khi chuyển tiền quốc tế.' },
      { label: 'Tài khoản ngân hàng Nhật hoặc phương thức nạp tiền', required: true },
      { label: 'Thông tin người nhận tại Việt Nam', required: true, note: 'Tên không dấu, ngân hàng, số tài khoản, chi nhánh/SWIFT nếu dịch vụ yêu cầu.' },
      { label: 'Mục đích chuyển tiền', required: true, note: 'Ví dụ: gửi cho gia đình, chi phí sinh hoạt, tiết kiệm cá nhân.' },
    ],
    commonMistakes: [
      'Chỉ nhìn phí gửi mà không so sánh tỷ giá và số tiền người nhận thực nhận.',
      'Nhập tên người nhận không khớp tài khoản Việt Nam.',
      'Gửi qua cá nhân trung gian không rõ pháp lý để được tỷ giá tốt hơn.',
      'Không lưu mã giao dịch/số tham chiếu để tra soát khi tiền chậm về.',
      'Gửi sát hạn cần tiền mà không tính thời gian xác minh giao dịch đầu tiên.',
    ],
    faq: [
      {
        question: 'Nên chọn dịch vụ nào để gửi tiền?',
        answer: 'Không có dịch vụ tốt nhất cho mọi trường hợp. So sánh tổng chi phí gồm phí gửi, tỷ giá, phí nạp tiền, hạn mức và cách người nhận nhận tiền. Chỉ dùng ngân hàng hoặc 資金移動業者 đã đăng ký tại Nhật.',
      },
      {
        question: 'Có cần My Number khi chuyển tiền quốc tế không?',
        answer: 'Có thể cần tùy dịch vụ và hình thức xác minh. Một số dịch vụ chuyển tiền quốc tế tại Nhật yêu cầu giấy tờ liên quan My Number ngoài giấy tờ định danh.',
      },
      {
        question: 'Nếu nhập sai số tài khoản hoặc tên người nhận thì sao?',
        answer: 'Tiền có thể bị giữ, trả về hoặc mất phí xử lý. Trước khi xác nhận, kiểm tra lại tên không dấu, ngân hàng, số tài khoản và chi nhánh/SWIFT nếu dịch vụ yêu cầu.',
      },
    ],
    counterPhrases: [
      {
        jp: '海外送金をしたいです。',
        romaji: 'Kaigai soukin o shitai desu.',
        vn: 'Tôi muốn chuyển tiền quốc tế.',
        note: 'Tại quầy ngân hàng / SBI Remit / Seven Bank.',
      },
      {
        jp: '送金の目的は家族への仕送りです。',
        romaji: 'Soukin no mokuteki wa kazoku e no shiokuri desu.',
        vn: 'Mục đích chuyển tiền là gửi cho gia đình.',
        note: 'Mục đích phổ biến hợp lệ — luôn khai trung thực.',
      },
      {
        jp: '受取人の情報を入力したいです。',
        romaji: 'Uketorinin no jouhou o nyuuryoku shitai desu.',
        vn: 'Tôi muốn nhập thông tin người nhận.',
        note: 'Tên không dấu khớp tài khoản VN + ngân hàng + số TK + chi nhánh + SWIFT.',
      },
      {
        jp: '受付番号を教えてください。',
        romaji: 'Uketsuke bangou o oshiete kudasai.',
        vn: 'Cho tôi biết số tham chiếu giao dịch.',
        note: 'Số transaction ID — cần để tra cứu khi tiền chậm / mất.',
      },
      {
        jp: '送金が届かないようです。状況を確認したいです。',
        romaji: 'Soukin ga todokanai you desu. Joukyou o kakunin shitai desu.',
        vn: 'Tiền chưa đến. Tôi muốn kiểm tra tình trạng.',
        note: 'Gọi hotline dịch vụ hoặc check app với 受付番号. Đợi 3-5 ngày làm việc trước khi báo lỗi.',
      },
    ],
    keyTerms: [
      {
        term: '資金移動業者',
        reading: 'しきんいどうぎょうしゃ',
        meaningVi: 'doanh nghiệp chuyển tiền (đã đăng ký 金融庁)',
        noteVi: 'Cấp phép cho dịch vụ chuyển tiền KHÔNG phải ngân hàng (SBI Remit / Wise / Seven Bank Remit / Revolut / etc.). Phải đăng ký với 金融庁 + tuân thủ AML. Kiểm tra dịch vụ có hợp pháp không qua trang 金融庁. Dùng kênh KHÔNG đăng ký = vi phạm pháp luật + không có cơ chế lấy lại tiền.',
      },
      {
        term: '海外送金',
        reading: 'かいがいそうきん',
        meaningVi: 'chuyển tiền quốc tế (từ Nhật ra nước ngoài)',
        noteVi: 'Bản thân việc gửi tiền sau thuế = KHÔNG đánh thuế ở Nhật. Nhưng > 100万円/lần tự động báo 国税庁 qua 国外送金等調書 — không có nghĩa bạn bị soi thuế, chỉ là thông tin. Nguồn tiền hợp pháp + không trùng nghi vấn = an toàn.',
      },
      {
        term: '為替レート',
        reading: 'かわせレート',
        meaningVi: 'tỷ giá hối đoái',
        noteVi: 'Mỗi dịch vụ có tỷ giá khác. Wise thường gần nhất tỷ giá thị trường (mid-market rate). Ngân hàng truyền thống có spread cao (3-5%). Khi so sánh: KHÔNG chỉ nhìn phí — tính TỔNG (phí + spread × số tiền). Tra "USD/VND" hoặc "JPY/VND" trên Google trước khi gửi.',
      },
      {
        term: '送金手数料',
        reading: 'そうきんてすうりょう',
        meaningVi: 'phí chuyển tiền (cố định)',
        noteVi: 'Phí service charge. SBI Remit ~880円-1,980円 tuỳ số tiền. Wise % theo số tiền. Seven Bank ~1,500-3,500円. Khác với spread tỷ giá (ẩn). Tổng cost thực = 送金手数料 + (số tiền × spread tỷ giá).',
      },
      {
        term: '受取人',
        reading: 'うけとりにん',
        meaningVi: 'người nhận tiền',
        noteVi: 'Phải nhập tên CHÍNH XÁC như trên sổ tài khoản VN (không dấu, đúng thứ tự họ-tên). Sai 1 chữ = ngân hàng VN từ chối → tiền hoàn về sau 5-10 ngày + mất phí xử lý. Tên có chữ "Đ" → viết "D". Họ Việt thường: "NGUYEN VAN A", "TRAN THI B" (viết hoa, không dấu).',
      },
      {
        term: 'SWIFT / BICコード',
        reading: 'スウィフト / ビーアイシーコード',
        meaningVi: 'mã ngân hàng quốc tế (8 hoặc 11 ký tự)',
        noteVi: 'Mã định danh ngân hàng VN trong hệ thống quốc tế. Ví dụ: Vietcombank = BFTVVNVX, Vietinbank = ICBVVNVX, MB Bank = MSCBVNVX. Tra trên website ngân hàng VN hoặc Google "SWIFT [tên ngân hàng]". Sai = tiền không đến hoặc đến nhầm ngân hàng.',
      },
      {
        term: '送金目的',
        reading: 'そうきんもくてき',
        meaningVi: 'mục đích chuyển tiền',
        noteVi: 'Phải khai khi gửi. Mục đích phổ biến hợp lệ: 家族への仕送り (gia đình) / 学費 (học phí) / 個人的なため (cá nhân tiết kiệm) / 不動産購入 (mua BĐS — cần thêm giấy). Khai THẬT — sai có thể bị 金融庁 báo cáo + 国税庁 hỏi.',
      },
      {
        term: '受付番号',
        reading: 'うけつけばんごう',
        meaningVi: 'số tham chiếu giao dịch (transaction ID)',
        noteVi: 'Mã do dịch vụ cấp sau khi gửi thành công. Lưu vào điện thoại / email. Cần khi: (1) Báo người nhận để check; (2) Liên hệ hỗ trợ khi tiền chậm; (3) Lưu cho 確定申告 (chứng minh chuyển tiền cho 扶養). MẤT = khó tra cứu sau.',
      },
    ],
    officialLinks: [
      { label: 'SBI Remit — Gửi tiền về Việt Nam', url: 'https://www.remit.co.jp/en/kaigaisoukin/sendremittance/remittancearea/vietnam/' },
      { label: 'Wise Japan', url: 'https://wise.com/jp' },
      { label: 'Seven Bank — Chuyển tiền quốc tế', url: 'https://www.sevenbank.co.jp/soukin' },
      { label: 'Danh sách業者 đăng ký — 金融庁', url: 'https://www.fsa.go.jp/menkyo/menkyo.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Chọn dịch vụ phù hợp',
        description: 'Các lựa chọn phổ biến gồm SBI Remit, Wise, Seven Bank/Western Union và ngân hàng. So sánh tổng chi phí gồm phí gửi, tỷ giá, phí nạp tiền và cách người nhận nhận tiền.',
        image: require('../../../../../assets/content/daily-life/dl_post-office_s2.jpg'),
        imageCaption: 'ゆうちょ銀行 / Japan Post — một trong những kênh gửi tiền quốc tế quen thuộc với người Việt tại Nhật',
        documents: [],
        tip: 'Chỉ dùng ngân hàng hoặc 資金移動業者 đã đăng ký tại Nhật. Tránh chuyển qua cá nhân trung gian không rõ pháp lý.',
      },
      {
        step: 2,
        title: 'Đăng ký tài khoản & xác minh danh tính',
        description: 'Dịch vụ chuyển tiền tại Nhật phải xác minh danh tính theo quy định chống rửa tiền. Người dùng nước ngoài thường cần thẻ cư trú và có thể cần giấy tờ My Number khi dùng dịch vụ chuyển tiền quốc tế.',
        documents: [
          'Thẻ cư trú (在留カード) hoặc giấy tờ định danh được dịch vụ chấp nhận',
          'Giấy tờ My Number nếu dịch vụ yêu cầu cho chuyển tiền quốc tế',
          'Tài khoản ngân hàng Nhật — để nạp tiền gửi đi (SBI Remit, Wise)',
          'Thông tin tài khoản ngân hàng Việt Nam của người nhận — tên, tên ngân hàng, số tài khoản',
        ],
        tip: 'Seven Bank ghi người ký hợp đồng chuyển tiền quốc tế cần nộp giấy tờ liên quan My Number ngoài giấy tờ xác minh danh tính.',
      },
      {
        step: 3,
        title: 'Điền thông tin giao dịch — không để sai',
        description: '**Thông tin người nhận cần chuẩn bị trước:**\n\n| Trường | Lưu ý |\n|---|---|\n| 受取人氏名 | Tên Latin khớp chính xác với sổ tài khoản Việt Nam (không dấu) |\n| 受取銀行名 | Tên ngân hàng bằng tiếng Anh (VD: Vietcombank, MB Bank) |\n| 支店名 / Branch | Tên chi nhánh nếu dịch vụ yêu cầu |\n| 口座番号 | Số tài khoản (không phải số thẻ ATM) |\n| SWIFT / BICコード | Mã SWIFT của ngân hàng Việt Nam — tra tại trang ngân hàng |\n| 送金目的 | Chọn: 家族への仕送り (gửi cho gia đình) |\n\nKiểm tra lại số tiền người nhận thực nhận (sau phí + tỷ giá) trước khi bấm xác nhận — không thể hủy sau khi đã gửi.',
        documents: [],
        tip: 'Tên người nhận phải khớp chính xác với tên trên tài khoản tại Việt Nam — sai thứ tự tên hoặc thiếu chữ có thể khiến tiền bị giữ hoặc hoàn về mất phí.',
      },
      {
        step: 4,
        title: 'Theo dõi và nhận tiền',
        description: 'Thời gian nhận phụ thuộc dịch vụ, giờ làm việc ngân hàng, xác minh bổ sung và phương thức nhận. Giao dịch đầu tiên hoặc giao dịch lớn có thể mất lâu hơn.',
        image: require('../../../../../assets/content/daily-life/dl_post-office_s3.jpg'),
        imageCaption: 'Theo dõi giao dịch qua app — lưu số tham chiếu để liên hệ hỗ trợ nếu tiền chưa đến',
        documents: [],
        tip: 'Hạn mức và phí thay đổi theo dịch vụ, cấp xác minh và luật hiện hành. Kiểm tra trong app/website chính thức ngay trước khi gửi.',
      },
    ],
  };

export default remittance;
