import type { AdminGuide } from '../../../../types/content';

const residenceCard: AdminGuide = {
    id: 'residence-card',
    category: 'immigration',
    lastVerified: '2026-08-21',
    priority: 'high',
    title: 'Gia hạn visa / thời hạn lưu trú',
    titleJp: '在留期間更新許可申請',
    icon: 'card',
    color: '#185FA5',
    description: 'Thủ tục gia hạn visa (chính thức là 在留期間更新許可申請) — xin tiếp tục ở Nhật với cùng tư cách lưu trú hiện tại. Khác với gia hạn hiệu lực vật lý của 在留カード và khác 在留資格変更 (đổi sang tư cách khác). Thời gian xử lý và hồ sơ có thể khác theo từng Nyukan — nên xác nhận thông tin mới nhất trước khi nộp.',
    searchKeywords: [
      'gia han visa',
      'gia hạn visa',
      'visa hết hạn',
      'visa sắp hết hạn',
      'gia han the cu tru',
      'gia hạn thời hạn lưu trú',
      'gia han hay doi tu cach',
      'visa renewal japan',
      'koushin shinsei',
      'zairyuu kikan koushin',
      '3 thang truoc khi het han',
      'visa han 3 thang',
      'specialty period',
      'tokurei kikan',
      'qua han luu tru',
      'overstay',
      'fuhou zanryuu',
      '在留期間',
      '在留期間更新',
      '在留期間更新許可申請',
      'ざいりゅうきかんこうしん',
      '特例期間',
      'とくれいきかん',
      '在留カード',
      '不法残留',
      'オーバーステイ',
      '6000円',
      '5500円',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Thủ tục 在留期間更新許可申請 do ISA xử lý toàn quốc; giấy tờ phụ thuộc tư cách lưu trú, nơi cư trú/làm việc/học tập và tình trạng hồ sơ.',
      sourceVerifiedAt: '2026-08-21',
      nextReviewAt: '2026-09-25',
      riskLevel: 'high',
      whenToAskExpert: [
        'Bạn sắp hết hạn lưu trú nhưng đã đổi việc, nghỉ học, nợ thuế/bảo hiểm hoặc hoạt động thực tế khác với tư cách đang có.',
        'Bạn không chắc nên gia hạn thời hạn lưu trú hay đổi tư cách lưu trú.',
        'Bạn đã nộp sát hạn, bị yêu cầu bổ sung hoặc có nguy cơ quá hạn.',
      ],
    },
    quickAction: {
      deadline: 'Nếu thời hạn lưu trú hiện tại từ 6 tháng trở lên, thường có thể nộp từ khoảng 3 tháng trước ngày hết hạn; không đợi sát hạn. Hệ thống online không nhận hồ sơ vào đúng ngày hết hạn lưu trú.',
      office: 'Cục xuất nhập cảnh có thẩm quyền hoặc hệ thống online ISA nếu thuộc đối tượng được dùng.',
      doNow: [
        'Kiểm tra ngày hết hạn lưu trú trên thẻ cư trú.',
        'Tải mẫu đúng tư cách lưu trú từ trang ISA tại ngày chuẩn bị nộp.',
        'Nếu định nộp online, nộp trước ngày cuối; nếu đã đến đúng ngày hết hạn, hỏi/nộp tại cục xuất nhập cảnh có thẩm quyền.',
        'Chuẩn bị giấy tờ thuế, bảo hiểm, thu nhập, trường/công ty nếu hồ sơ có yếu tố thay đổi.',
      ],
      bring: ['Thẻ cư trú', 'Hộ chiếu', 'Ảnh thẻ 4cm x 3cm', 'Đơn xin gia hạn', 'Giấy tờ chứng minh hoạt động hiện tại'],
      ifLate: 'Nộp/hỏi ISA càng sớm càng tốt và giải thích trung thực; quá hạn lưu trú là rủi ro nghiêm trọng.',
      officialSourceLabels: [
        '在留期間更新許可申請 — 出入国在留管理庁',
        'Online Residence Application System — ISA',
        'Thông báo sửa phí thủ tục từ 01/04/2025',
      ],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_residence-card_hero.jpg'),
    heroImageCaption: 'Thẻ cư trú (在留カード) — mang theo khi ra ngoài, cập nhật thông tin khi có thay đổi',
    whoIsThisFor: [
      'Người đang ở Nhật với tư cách lưu trú trung/dài hạn và muốn tiếp tục ở Nhật với cùng tư cách hiện tại.',
      'Người đi làm, du học sinh, visa gia đình, kỹ năng đặc định hoặc các tư cách khác sắp hết hạn lưu trú.',
      'Không dùng cho trường hợp muốn đổi sang tư cách khác; khi đó cần xem thủ tục 在留資格変更許可申請.',
      'Không phải thủ tục gia hạn hiệu lực thẻ cư trú vật lý của người vĩnh trú/trẻ em dưới 16 tuổi.',
    ],
    whenToDo: [
      'Nếu thời hạn lưu trú hiện tại từ 6 tháng trở lên, thường có thể nộp từ khoảng 3 tháng trước ngày hết hạn.',
      'Nên chuẩn bị hồ sơ sớm hơn thời điểm nộp vì có thể cần giấy tờ từ công ty, trường, 市役所/区役所 hoặc người bảo lãnh.',
      'Không nên đợi sát ngày hết hạn; nếu thiếu giấy tờ, bạn có thể không kịp bổ sung.',
      'Nếu có lý do đặc biệt như nhập viện hoặc công tác dài ngày, hãy hỏi ISA về khả năng nộp sớm.',
    ],
    whereToDo: [
      'Cục xuất nhập cảnh có thẩm quyền theo nơi cư trú hoặc nơi làm việc/học tập.',
      'Hệ thống online của ISA nếu bạn thuộc đối tượng được phép sử dụng.',
      'Một số trường/công ty/行政書士 có thể hỗ trợ chuẩn bị hồ sơ, nhưng người nộp vẫn cần hiểu nội dung hồ sơ của mình.',
    ],
    estimatedTime: 'Thời gian xét duyệt thay đổi theo hồ sơ và khu vực. Nhiều hồ sơ mất vài tuần đến vài tháng; nếu bị yêu cầu bổ sung giấy tờ sẽ lâu hơn.',
    fees: [
      'Nếu được cấp phép: 6.000 yên khi làm thủ tục thường, hoặc 5.500 yên nếu là online application theo mức ISA áp dụng từ 01/04/2025.',
      'Không nên dựa vào mức phí cũ 4.000 yên hoặc kinh nghiệm của người khác; kiểm tra bảng phí chính thức của ISA trước khi nhận kết quả.',
      'Thông thường phí được nộp khi nhận kết quả được cấp phép, không phải lúc nộp hồ sơ.',
      'LƯU Ý: Chính phủ đang lấy ý kiến một nghị định (政令) mới quy định phí theo BẬC (khoảng 1万–7.5万円 tùy thời hạn còn lại của tư cách lưu trú, thay cho mức cố định 6.000/5.500 yên hiện tại), dự kiến hiệu lực từ 2026-10-01 nhưng tại 2026-08-21 vẫn CHƯA công bố chính thức trên 官報. Nếu bạn nộp hồ sơ gần mốc 10/2026, kiểm tra kỹ mức phí mới nhất tại ISA. Xem chi tiết ở guide [[visa-fee-increase-2025-2026]].',
    ],
    documentsChecklist: [
      { label: 'Đơn xin gia hạn thời hạn lưu trú', required: true, note: 'Tải đúng mẫu theo tư cách lưu trú từ trang ISA.' },
      { label: 'Ảnh thẻ縦4cm × 横3cm', required: true, note: 'Nền trắng hoặc sáng màu đơn sắc (không có bóng), chụp trong 3 tháng gần nhất, không đội mũ, không đeo kính tối.' },
      { label: 'Hộ chiếu', required: true, note: 'Mang bản gốc. Nếu không có hộ chiếu hợp lệ, cần giải thích theo hướng dẫn của ISA.' },
      { label: 'Thẻ cư trú hiện tại', required: true, note: 'Mang bản gốc.' },
      { label: 'Giấy chứng nhận đang làm việc / hợp đồng lao động', required: false, note: 'Thường cần với visa đi làm.' },
      { label: 'Giấy chứng nhận nhập học / bảng điểm / chứng nhận chuyên cần', required: false, note: 'Thường cần với visa du học.' },
      { label: 'Giấy tờ thuế, thu nhập, bảo hiểm', required: false, note: 'Có thể cần tùy tư cách lưu trú và tình trạng hồ sơ.' },
      { label: 'Giấy tờ của người bảo lãnh', required: false, note: 'Có thể cần với 家族滞在 hoặc tư cách phụ thuộc gia đình.' },
      { label: 'Lý do giải trình', required: false, note: 'Nên chuẩn bị nếu có đổi việc, nghỉ học, nợ thuế/bảo hiểm, thu nhập thấp hoặc hồ sơ bất thường.' },
    ],
    tips: [
      'Nộp hồ sơ **ít nhất 3 tháng trước ngày hết hạn visa** — không phải vì bắt buộc nhưng nếu ISA yêu cầu bổ sung giấy tờ (追加書類), bạn có đủ thời gian xử lý mà không bị quá hạn.',
      'Sau khi nộp hồ sơ và được nhận, bạn có thể tiếp tục ở Nhật và đi làm trong **特例期間** (tối đa 2 tháng sau ngày hết hạn visa gốc hoặc đến khi có kết quả). Thẻ cư trú + giấy biên nhận nộp hồ sơ là bằng chứng tình trạng hợp pháp.',
      'Chuẩn bị **lý do giải trình (理由書)** nếu có bất kỳ điểm bất thường nào trong hồ sơ: đổi việc, nghỉ học tạm, nợ thuế/bảo hiểm một kỳ, thu nhập thấp năm qua, hoặc công việc thực tế lệch tư cách lưu trú. ISA đánh giá cao sự minh bạch hơn là hồ sơ "có lỗ hổng nhưng không giải thích".',
    ],
    commonMistakes: [
      'Nhầm lẫn giữa gia hạn thời hạn lưu trú và gia hạn hiệu lực thẻ cư trú.',
      'Đổi việc nhưng quên khai báo với ISA trong trường hợp cần khai báo.',
      'Công việc thực tế không khớp tư cách lưu trú đang có.',
      'Du học sinh làm quá giờ hoặc thiếu chuyên cần nhưng không chuẩn bị giải trình.',
      'Thiếu giấy tờ thuế/bảo hiểm/thu nhập hoặc để địa chỉ trên giấy tờ không khớp.',
      'Nộp sát hạn khiến không kịp bổ sung hồ sơ.',
    ],
    faq: [
      {
        question: 'Nộp hồ sơ rồi có được tiếp tục ở Nhật trong lúc chờ không?',
        answer: 'Nếu nộp đúng hạn trước ngày hết hạn lưu trú, có thể có cơ chế 特例期間 trong một số trường hợp. Tuy nhiên điều kiện cụ thể phụ thuộc hồ sơ, nên hãy kiểm tra hướng dẫn của ISA hoặc hỏi tại quầy khi nộp.',
      },
      {
        question: 'Có được tiếp tục đi làm trong lúc chờ kết quả không?',
        answer: 'Về nguyên tắc bạn chỉ được hoạt động trong phạm vi tư cách lưu trú hiện tại. Nếu công việc/tình trạng đã thay đổi, hãy xác nhận với ISA trước khi tiếp tục làm.',
      },
      {
        question: 'Gia hạn visa có phải lúc nào cũng được cấp không?',
        answer: 'Không. ISA xét hoạt động thực tế, thu nhập, thuế/bảo hiểm, tình trạng học tập/làm việc, quan hệ gia đình và các yếu tố khác tùy tư cách lưu trú.',
      },
      {
        question: 'Nếu bị yêu cầu bổ sung giấy tờ thì sao?',
        answer: 'Chuẩn bị đúng giấy tờ được yêu cầu và nộp trước hạn ghi trong thông báo. Nên giữ bản sao toàn bộ hồ sơ đã nộp.',
      },
      {
        question: 'Phí bao nhiêu?',
        answer: 'Theo ISA, hồ sơ được cấp phép hiện là 6.000 yên nếu làm thủ tục thường và 5.500 yên nếu nộp online. Vẫn nên kiểm tra bảng phí chính thức tại thời điểm nhận kết quả.',
      },
      {
        question: 'Có thể nộp online vào đúng ngày hết hạn không?',
        answer: 'Không nên để đến ngày cuối. ISA nêu hệ thống online không thể dùng để nộp vào đúng ngày hết hạn lưu trú; khi đó cần xử lý tại cục xuất nhập cảnh có thẩm quyền.',
      },
      {
        question: 'Gia hạn visa xong, thẻ mới có phải là 特定在留カード (tích hợp My Number) không?',
        answer: 'Không tự động. Kể từ 14/06/2026, gia hạn thời hạn lưu trú là một trong các thủ tục đủ điều kiện để BẠN chọn xin 特定在留カード thay cho thẻ 在留カード thường — nhưng đây là lựa chọn thêm, không bắt buộc, và hiện phải yêu cầu trực tiếp tại quầy ISA (chưa hỗ trợ chọn qua hệ thống 在留申請オンライン). Việc cấp 特定在留カード có thể mất thêm thời gian xử lý so với thẻ thường. Xem chi tiết ở guide [[specific-residence-card-my-number-2026]].',
      },
    ],
    scenarios: [
      {
        title: 'Đổi công ty giữa năm — có cần làm gì trước khi gia hạn visa?',
        situation: 'Tôi vừa đổi sang công ty mới vẫn cùng ngành IT. Visa hết hạn còn 4 tháng. Có cần làm thêm thủ tục gì không?',
        answer: '**Khai báo đổi việc với ISA trước** (trong vòng 14 ngày sau khi đổi) — đây là bắt buộc theo 在留カード制度. Khai báo online qua Myna Portal hoặc đến ISA trực tiếp. Sau đó khi gia hạn visa, chuẩn bị:\n\n• Giấy tờ từ công ty mới (在職証明書 hoặc hợp đồng lao động)\n• Giấy tờ thuế/bảo hiểm\n• Nếu công ty cũ không phát 源泉徴収票 kịp, xin tạm 在職証明書 hoặc 退職証明書 từ công ty cũ\n\nCùng ngành IT với tư cách 技術・人文・国際業務 thường được xét thuận lợi, nhưng ISA vẫn kiểm tra tính nhất quán giữa công việc và tư cách lưu trú.',
      },
      {
        title: 'Nhận kết quả "cấp phép" nhưng thẻ cũ vẫn đang dùng — phải làm gì tiếp?',
        situation: 'ISA gửi về phong bì kết quả. Mở ra thấy giấy "許可" (cấp phép). Giờ phải làm gì để nhận thẻ mới?',
        answer: 'Trong phong bì có **在留資格認定証明書 hoặc 指定書** — mang theo cùng:\n• Hộ chiếu\n• Thẻ cư trú hiện tại\n• Phí 6.000 yên (hoặc 5.500 yên nếu đã nộp online)\n\nĐến **ISA để nhận thẻ mới trong thời hạn ghi trên giấy thông báo** (thường 2–4 tuần). Thẻ cũ sẽ bị thu lại. Sau khi nhận thẻ mới, kiểm tra kỹ tất cả thông tin trước khi về.',
      },
      {
        title: 'Bị yêu cầu bổ sung giấy tờ — phải xử lý thế nào?',
        situation: 'ISA gửi thư yêu cầu 追加資料 (bổ sung giấy tờ). Deadline 2 tuần nữa. Tôi lo không kịp.',
        answer: '**Ưu tiên 1**: Đọc kỹ thư — ISA liệt kê chính xác tài liệu cần bổ sung. Không gửi thừa, không gửi thiếu.\n\n**Ưu tiên 2**: Nếu không thể có đủ trong thời hạn (ví dụ giấy tờ từ công ty mất thời gian), **liên hệ ISA ngay** để xin gia hạn deadline — họ thường linh hoạt nếu bạn chủ động báo trước.\n\n**Ưu tiên 3**: Nếu yêu cầu không rõ, đến quầy ISA hỏi trực tiếp (mang theo số hồ sơ). Không để thư bổ sung bị bỏ qua — không trả lời đúng hạn có thể dẫn đến từ chối hồ sơ.',
      },
    ],
    counterPhrases: [
      {
        jp: '在留期間更新許可申請をしたいです。',
        romaji: 'Zairyuu kikan koushin kyoka shinsei o shitai desu.',
        vn: 'Tôi muốn nộp đơn gia hạn thời hạn lưu trú.',
        note: 'Câu mở đầu — dùng tên chính thức để Nyukan biết bạn xin gia hạn, KHÔNG phải đổi tư cách.',
      },
      {
        jp: '今までと同じ仕事を続けますが、追加書類は必要ですか。',
        romaji: 'Ima made to onaji shigoto o tsuzukemasu ga, tsuika shorui wa hitsuyou desu ka.',
        vn: 'Tôi tiếp tục cùng công việc trước đây, có cần thêm giấy tờ gì không?',
        note: 'Câu hỏi thực tế. Nếu hoạt động KHÔNG đổi → ít giấy tờ. Nếu đổi việc → có thể cần 在留資格変更 thay vì 更新.',
      },
      {
        jp: 'オンライン申請の対象になりますか。',
        romaji: 'Onrain shinsei no taishou ni narimasu ka.',
        vn: 'Tôi có thuộc đối tượng dùng đơn online không?',
        note: 'Online giảm 500 yên (5,500 thay vì 6,000) — nhưng cần đăng ký trước + KHÔNG nhận đơn vào ngày hết hạn lưu trú.',
      },
      {
        jp: '在留期限が来月末です。特例期間はありますか。',
        romaji: 'Zairyuu kigen ga raigetsu matsu desu. Tokurei kikan wa arimasu ka.',
        vn: 'Hạn lưu trú của tôi đến cuối tháng sau. Có 特例期間 không?',
        note: 'Hỏi rõ về 特例期間 — cơ chế cho phép ở thêm tối đa 2 tháng sau khi hết hạn nếu đã nộp đơn ĐÚNG hạn.',
      },
      {
        jp: '結果が出るまで、今の仕事を続けても大丈夫ですか。',
        romaji: 'Kekka ga deru made, ima no shigoto o tsuzukete mo daijoubu desu ka.',
        vn: 'Trong khi chờ kết quả, tôi có được tiếp tục đi làm không?',
        note: 'Quan trọng — về nguyên tắc tiếp tục trong phạm vi tư cách hiện tại + 特例期間. Nhưng nếu hoạt động thay đổi → phải xác nhận trước.',
      },
      {
        jp: '更新が不許可になった場合、どうすればいいですか。',
        romaji: 'Koushin ga fukyoka ni natta baai, dou sureba ii desu ka.',
        vn: 'Nếu đơn gia hạn không được duyệt thì tôi phải làm gì?',
        note: 'Hỏi trước để biết hướng xử lý. Thường Nyukan sẽ cho thời gian chuẩn bị rời Nhật hoặc thử lại với hồ sơ bổ sung.',
      },
    ],
    keyTerms: [
      {
        term: '在留期間更新許可申請',
        reading: 'ざいりゅうきかんこうしんきょかしんせい',
        meaningVi: 'đơn xin gia hạn thời hạn lưu trú',
        noteVi: 'Tên chính thức. KHÁC 在留資格変更 (đổi sang tư cách khác). Dùng khi muốn TIẾP TỤC cùng tư cách hiện tại. Phí 6,000 yên (5,500 nếu online) — nộp khi nhận kết quả.',
      },
      {
        term: '在留期間',
        reading: 'ざいりゅうきかん',
        meaningVi: 'thời hạn lưu trú (ghi trên 在留カード)',
        noteVi: 'Thường 1 / 3 / 5 năm tùy tư cách và lịch sử. 高度専門職 thường 5 năm; 技人国 1-5 năm; 留学 theo độ dài chương trình; 家族滞在 đi theo người bảo lãnh. Lần gia hạn sau có thể được dài hơn nếu hồ sơ tốt.',
      },
      {
        term: '特例期間',
        reading: 'とくれいきかん',
        meaningVi: 'giai đoạn ngoại lệ (gia hạn tự động trong khi chờ kết quả)',
        noteVi: 'Cơ chế quan trọng. Nếu đã nộp 在留期間更新 ĐÚNG HẠN trước ngày hết hạn → được phép ở thêm tối đa 2 tháng (60 ngày) sau ngày hết hạn cũ trong khi chờ kết quả. Tiếp tục hoạt động trong phạm vi tư cách hiện tại. KHÔNG có 特例期間 nếu nộp muộn.',
      },
      {
        term: '在留資格変更 vs 在留期間更新',
        reading: 'ざいりゅうしかくへんこう vs ざいりゅうきかんこうしん',
        meaningVi: 'đổi tư cách vs gia hạn thời hạn (KHÁC NHAU)',
        noteVi: '更新 = giữ cùng tư cách + xin thêm thời gian. 変更 = đổi sang tư cách khác (vd 留学 → 技人国). Dùng SAI form = hồ sơ bị trả về. Khi hoạt động thay đổi (đổi việc khác ngành, tốt nghiệp đi làm) → cần 変更. Tham khảo [[status-of-residence-change]].',
      },
      {
        term: '不法残留',
        reading: 'ふほうざんりゅう',
        meaningVi: 'ở lại quá hạn (overstay)',
        noteVi: 'Hết 在留期限 (kể cả 特例期間) mà chưa được duyệt = 不法残留. Hậu quả: bị trục xuất + cấm tái nhập 5-10 năm + có thể bị tù theo 入管法 §70. Chủ động đến Nyukan tự thú thường được xử lý nhẹ hơn.',
      },
      {
        term: '3か月前',
        reading: '3かげつまえ',
        meaningVi: '3 tháng trước (thời điểm sớm nhất nộp gia hạn)',
        noteVi: 'Nếu thời hạn hiện tại từ 6 tháng trở lên: thường có thể nộp từ 3 tháng trước ngày hết hạn. Càng sớm càng tốt. Không nên đợi sát hạn — nếu thiếu giấy tờ, không kịp bổ sung.',
      },
      {
        term: '不許可',
        reading: 'ふきょか',
        meaningVi: 'từ chối (đơn gia hạn không được duyệt)',
        noteVi: 'Lý do thường: thuế/bảo hiểm chưa nộp, đổi việc không khai báo, hoạt động không khớp tư cách, thu nhập thấp đối với 家族滞在. Sau 不許可 Nyukan thường cho 30 ngày 出国準備期間 để rời Nhật hoặc thử lại với hồ sơ bổ sung.',
      },
      {
        term: '出国準備期間',
        reading: 'しゅっこくじゅんびきかん',
        meaningVi: 'thời gian chuẩn bị rời Nhật (sau 不許可)',
        noteVi: 'Khoảng 30 ngày Nyukan cho phép ở lại để chuẩn bị rời. Trong giai đoạn này KHÔNG được đi làm. Có thể dùng để nộp lại với hồ sơ tốt hơn nếu Nyukan đồng ý. Liên hệ luật sư / 行政書士 nếu phức tạp.',
      },
    ],
    officialLinks: [
      { label: '在留期間更新許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-3.html' },
      { label: 'Online Residence Application System — ISA', url: 'https://www.moj.go.jp/isa/applications/online/onlineshinsei.html' },
      { label: 'Thông báo sửa phí thủ tục từ 01/04/2025', url: 'https://www.moj.go.jp/isa/01_00518.html' },
      { label: 'Tra cứu cục xuất nhập cảnh gần nhất', url: 'https://www.moj.go.jp/isa/about/region/index.html' },
      { label: '在留資格変更許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-2.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra thời điểm nộp',
        description: 'Theo ISA, nếu thời hạn lưu trú hiện tại từ 6 tháng trở lên, thường có thể nộp từ khoảng 3 tháng trước ngày hết hạn. Trường hợp đặc biệt như nhập viện hoặc công tác dài ngày có thể được xem xét sớm hơn.',
        documents: [
          'Thẻ cư trú hiện tại (在留カード)',
          'Hộ chiếu còn hiệu lực',
          'Ngày hết hạn lưu trú ghi trên thẻ cư trú',
        ],
        tip: 'Đừng chờ sát ngày hết hạn. Nếu nộp đúng hạn, có thể có "特例期間" trong thời gian chờ xét duyệt, nhưng vẫn nên xác nhận với cục xuất nhập cảnh.',
      },
      {
        step: 2,
        title: 'Chuẩn bị hồ sơ theo tư cách lưu trú',
        description: 'Giấy tờ phụ thuộc vào loại visa: đi làm, du học, gia đình, kỹ năng đặc định, v.v. Hãy tải đúng mẫu từ trang ISA cho tư cách lưu trú của bạn.',
        documents: [
          'Đơn xin gia hạn thời hạn lưu trú',
          'Ảnh thẻ縦4cm × 横3cm, nền trắng/sáng, chụp trong 3 tháng gần nhất',
          'Giấy tờ chứng minh hoạt động hiện tại: hợp đồng lao động, giấy chứng nhận đang làm việc, giấy nhập học, bảng điểm, giấy tờ gia đình...',
          'Giấy tờ thu nhập/thuế/bảo hiểm nếu được yêu cầu',
        ],
        tip: 'Tên thủ tục đúng là "在留期間更新許可申請"; không nên gọi chung là gia hạn thẻ cư trú khi tra cứu thông tin chính thức.',
      },
      {
        step: 3,
        title: 'Nộp hồ sơ tại ISA hoặc online nếu đủ điều kiện',
        description: 'Có thể nộp tại cục xuất nhập cảnh có thẩm quyền hoặc qua hệ thống online nếu bạn thuộc đối tượng được phép sử dụng.',
        documents: [
          'Hồ sơ đã chuẩn bị',
          'Thẻ cư trú và hộ chiếu bản gốc',
          'Giấy tờ bổ sung nếu cục yêu cầu',
        ],
        tip: 'Luôn kiểm tra trang chính thức trước ngày nộp vì biểu mẫu, phí và giấy tờ có thể thay đổi.',
        image: require('../../../../../assets/content/daily-life/ag_residence-card_s3.jpg'),
        imageCaption: '出入国在留管理局 — nộp hồ sơ gia hạn lưu trú trực tiếp tại quầy tiếp nhận',
      },
      {
        step: 4,
        title: 'Nhận kết quả và nộp phí',
        description: 'Khi được thông báo kết quả, mang giấy thông báo, hộ chiếu, thẻ cư trú cũ và nộp phí theo hướng dẫn hiện hành để nhận thẻ mới.',
        documents: [
          'Thông báo từ ISA',
          'Hộ chiếu',
          'Thẻ cư trú cũ',
          'Lệ phí: 6.000 yên thủ tục thường hoặc 5.500 yên online theo bảng phí hiện hành nếu được cấp phép',
        ],
        tip: 'Không ghi nhớ phí theo kinh nghiệm cũ. Với hồ sơ online, cũng phải theo đúng cách nộp phí ISA hướng dẫn khi nhận kết quả.',
      },
    ],
  };

export default residenceCard;
