import type { AdminGuide } from '../../../../types/content';

const residenceCardValidity: AdminGuide = {
    id: 'residence-card-validity',
    category: 'immigration',
    lastVerified: '2026-08-21',
    priority: 'normal',
    title: 'Gia hạn hiệu lực thẻ cư trú',
    titleJp: '在留カードの有効期間の更新申請',
    icon: 'id-card',
    color: '#2980B9',
    description: 'Đổi thẻ cư trú vật lý sắp hết hạn (in trên mặt thẻ). KHÁC với gia hạn visa/lưu trú. Chủ yếu dành cho người vĩnh trú, HSP2, hoặc trẻ em đến mốc 16 tuổi. Từ 14/06/2026 có lựa chọn mới 特定在留カード gộp với My Number Card.',
    searchKeywords: [
      'gia hạn thẻ cư trú',
      'đổi thẻ cư trú',
      'thẻ cư trú hết hạn',
      '在留カード',
      'zairyu card',
      'zairyu kaado',
      '有効期間',
      'youkou kikan',
      '更新申請',
      'koushin shinsei',
      '特定在留カード',
      'tokutei zairyu card',
      'My Number Card',
      'マイナンバーカード',
      'card sắp hết hạn',
      'thẻ vật lý',
      'permanent resident card renewal',
      'HSP2 card renewal',
      'trẻ em 16 tuổi đổi thẻ',
      'residence card expiry',
      '入国管理局',
      'nyukoku kanrikyoku',
      'ISA',
      '出入国在留管理庁',
    ],
    legalScope: {
      appliesFrom: '2026-06-14',
      jurisdiction: 'national',
      jurisdictionNote: 'Áp dụng theo hệ thống của ISA trên toàn Nhật; nơi nộp phụ thuộc địa chỉ cư trú và loại thủ tục.',
      sourceVerifiedAt: '2026-08-21',
      nextReviewAt: '2026-11-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Thẻ cư trú sắp hết hạn nhưng bạn không chắc là gia hạn thẻ vật lý hay gia hạn thời hạn lưu trú.',
        'Bạn muốn xin 特定在留カード cùng lúc đổi tư cách, gia hạn, cấp lại hoặc đổi thông tin.',
        'Thông tin trên thẻ/My Number không khớp hoặc bạn đang có hồ sơ cư trú bất thường.',
      ],
    },
    quickAction: {
      deadline: 'Đi trước khi hạn trên mặt thẻ hết. Không gấp nếu còn vài tháng — nhưng đừng để hết hạn rồi mới đi.',
      office: '入国管理局 tại khu vực cư trú của bạn.',
      doNow: [
        'Kiểm tra thật rõ: bạn cần gia hạn THẺ VẬT LÝ hay gia hạn VISA/lưu trú? Hai cái khác nhau.',
        'Mở link ISA chính thức ở dưới, đối chiếu giấy tờ cần thiết tại ngày nộp.',
        'Nếu có My Number Card và muốn gộp → hỏi ISA về 特定在留カード.',
      ],
      bring: ['在留カード hiện tại (bắt buộc)', 'Hộ chiếu (bắt buộc)', 'Ảnh thẻ 4×3cm chụp <3 tháng (bắt buộc)', 'Đơn xin gia hạn (lấy tại quầy hoặc tải từ ISA)', 'My Number Card (chỉ khi xin 特定在留カード)'],
      ifLate: 'Đi ISA ngay. Nói thật. Hết hạn thẻ vật lý không nguy hiểm bằng hết hạn lưu trú/visa — nhưng vẫn nên xử lý sớm.',
      officialSourceLabels: ['在留カードとは？— 出入国在留管理庁', '特定在留カード等交付申請 — 出入国在留管理庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_card-validity_hero.jpg'),
    heroImageCaption: 'Gia hạn hạn hiệu lực vật lý thẻ 在留カード tại ISA',
    whoIsThisFor: [
      'Bạn có visa vĩnh trú hoặc HSP2, thẻ vật lý sắp hết hạn (xem ngày trên mặt thẻ).',
      'Trẻ em người nước ngoài sắp đến 16 tuổi.',
      'Bạn đang làm 1 trong 4 thủ tục sau 14/06/2026 (gia hạn / đổi tư cách / đổi thông tin / đăng ký địa chỉ) và muốn xem có nên xin 特定在留カード hay không.',
      'Không phải bạn nếu: visa/lưu trú sắp hết hạn — đó là thủ tục 在留期間更新許可申請, hoàn toàn khác.',
    ],
    whenToDo: [
      'Vài tháng trước khi thẻ vật lý hết hạn — kiểm tra ngày trên mặt thẻ.',
      'Trước sinh nhật 16 tuổi nếu là trẻ em.',
      'Từ 14/06/2026: nếu định gộp My Number, hỏi ISA về 特定在留カード trước khi quyết định.',
      'Không dùng thủ tục này nếu visa/tư cách lưu trú sắp hết hạn — đó là 在留期間更新許可申請, hoàn toàn khác.',
    ],
    whereToDo: [
      '入国管理局 (ISA) tại khu vực bạn đang sống.',
      'Người đại diện hợp pháp có thể nộp thay cho trẻ em hoặc người ốm — gọi ISA xác nhận trước.',
    ],
    documentsChecklist: [
      { label: 'Đơn xin gia hạn hiệu lực thẻ cư trú', required: true },
      { label: 'Ảnh thẻ 4cm x 3cm', required: true, note: 'Nền trắng/sáng, chụp trong 3 tháng gần nhất.' },
      { label: 'Hộ chiếu', required: true },
      { label: 'Thẻ cư trú hiện tại', required: true },
      { label: 'Giấy tờ người đại diện', required: false, note: 'Có thể cần nếu người đại diện nộp thay.' },
    ],
    tips: [
      'Đặt nhắc nhở **3 tháng trước ngày hết hạn** ghi trên thẻ (góc dưới bên phải mặt trước). Nếu đợi sát hạn và ISA đông, bạn có thể không kịp.',
      'Ảnh thẻ phải chụp **trong vòng 3 tháng**. Nếu ảnh cũ hơn, chụp lại tại cửa hàng ảnh (コンビニ có thể in ảnh đúng kích thước với giá rẻ hơn).',
      'Sau khi nhận thẻ mới, kiểm tra kỹ **tất cả thông tin in trên thẻ** tại quầy trước khi về — họ tên, ngày sinh, quốc tịch, tư cách, hạn. Nếu sai, yêu cầu sửa ngay tại chỗ.',
    ],
    commonMistakes: [
      'Nhầm "gia hạn thẻ vật lý" với "gia hạn visa/lưu trú" — hai thủ tục khác hẳn nhau.',
      'Đợi thẻ hết hạn rồi mới đi → khó đi đâu khi không có thẻ hợp lệ.',
      'Nhận thẻ mới mà quên kiểm tra thông tin → có thể có lỗi đánh máy mà không ai phát hiện.',
      'Ảnh cũ quá 3 tháng hoặc sai kích thước → bị trả về làm lại.',
      'Tưởng phải đổi sang 特定在留カード ngay từ 14/06/2026. Thật ra thẻ hiện hành vẫn có hiệu lực đến hết hạn.',
    ],
    faq: [
      {
        question: 'Thủ tục này có phải gia hạn visa không?',
        answer: 'Không. Đây là gia hạn THẺ VẬT LÝ. Muốn ở Nhật tiếp sau khi visa/lưu trú hết hạn → thủ tục 在留期間更新許可申請, hoàn toàn khác.',
      },
      {
        question: 'Thủ tục này có mất phí không?',
        answer: 'Không — trang ISA ghi rõ "手数料はかかりません" (miễn phí) cho thủ tục gia hạn hiệu lực thẻ vật lý này. Nếu chuyển sang xin 特定在留カード, phí riêng có thể áp dụng cho một số trường hợp (xem mục 特定在留カード bên dưới) — không phải phí của thủ tục gia hạn thẻ thường.',
      },
      {
        question: 'Sau khi nhận thẻ mới cần kiểm tra gì?',
        answer: 'Đọc kỹ: họ tên, ngày sinh, quốc tịch/khu vực, tư cách lưu trú, hạn lưu trú, hạn hiệu lực thẻ. Nếu sai bất cứ thông tin nào, yêu cầu chỉnh ngay tại quầy — đừng đi về rồi mới phát hiện.',
      },
      {
        question: '特定在留カード từ 14/06/2026 có bắt buộc không?',
        answer: 'Không. Thẻ cư trú hiện hành vẫn có hiệu lực sau khi mẫu mới bắt đầu. 特定在留カード là lựa chọn thêm — chỉ xin nếu bạn đang làm 1 trong các thủ tục đủ điều kiện (gia hạn / đổi tư cách / cấp lại / khai báo địa chỉ) và muốn gộp My Number.',
      },
    ],
    scenarios: [
      {
        title: 'Thẻ hết hạn nhưng visa vẫn còn — cần làm gì?',
        situation: 'Visa của tôi hết hạn tháng 12/2026, nhưng thẻ cư trú (在留カード) ghi hạn tháng 9/2026. Tôi cần làm hai thủ tục khác nhau à?',
        answer: 'Đúng — đây là **hai thủ tục độc lập**:\n\n• **Gia hạn hiệu lực thẻ vật lý** (在留カード有効期間更新): làm tại ISA khi thẻ sắp hết hạn ghi trên thẻ. Không thay đổi visa.\n\n• **Gia hạn tư cách lưu trú** (在留期間更新許可申請): làm tại ISA trước khi visa/lưu trú hết hạn. Đây mới là thủ tục "gia hạn visa" mà nhiều người nói.\n\nTrường hợp của bạn: làm thủ tục gia hạn thẻ vật lý trước tháng 9/2026, sau đó làm gia hạn lưu trú trước tháng 12/2026.',
      },
      {
        title: 'Mất thẻ cư trú, xin lại có cần ảnh mới không?',
        situation: 'Tôi bị mất thẻ cư trú và phải đến ISA xin cấp lại. Cần chuẩn bị gì?',
        answer: 'Mang đến ISA: **hộ chiếu**, **ảnh 4×3cm** (chụp trong 3 tháng gần nhất), **đơn 紛失等の届出書 hoặc 在留カード再交付申請書** (tải từ trang ISA hoặc xin tại quầy), và **tờ khai lý do mất** (có thể cần thông báo mất của cảnh sát 紛失届の控え trong một số trường hợp). Phí: **1.300 yên** (tem hoặc cash — hỏi ISA khu vực của bạn). Báo mất trong vòng **14 ngày** để tránh phạt.',
      },
      {
        title: '特定在留カード — có nên đổi không?',
        situation: 'Tôi nghe nói từ 2026 có thẻ 特定在留カード mới. Có bắt buộc phải đổi không? Lợi ích gì?',
        answer: '**Không bắt buộc.** Thẻ cư trú hiện hành vẫn hợp lệ đến hết hạn ghi trên thẻ. 特定在留カード là mẫu thẻ mới tích hợp My Number vào thẻ cư trú, chỉ nộp trực tiếp tại quầy (KHÔNG hỗ trợ nộp online), xử lý mất khoảng 2 tuần (không cấp ngay như thẻ thường). Có thể xin đổi khi đang làm các thủ tục đủ điều kiện (gia hạn, đổi tư cách, cấp lại, khai báo địa chỉ). Về phí: lần làm thủ tục đầu tiên từ 14/06/2026 trở đi thường MIỄN PHÍ; các lần sau (cấp lại, đổi thông tin...) có thể mất 1,900円 (2,600円 nếu nhận qua bưu điện) phí phía ISA + 600円 (800円 nếu có chứng thư điện tử) phí phía J-LIS cho phần My Number. Lợi ích: gộp 2 thẻ thành 1, thuận tiện hơn khi dùng dịch vụ công. Nếu bạn đang gia hạn thẻ vật lý trong thời gian tới, hỏi quầy ISA xem có thể chuyển sang 特定在留カード cùng lúc không.',
      },
    ],
    counterPhrases: [
      {
        jp: '在留カードの有効期間更新申請をしたいです。',
        romaji: 'Zairyuu kaado no yuukou kikan koushin shinsei o shitai desu.',
        vn: 'Tôi muốn xin gia hạn hiệu lực 在留カード.',
        note: 'Câu mở đầu tại quầy 入国管理局.',
      },
      {
        jp: '必要な書類を教えていただけますか。',
        romaji: 'Hitsuyou na shorui o oshiete itadakemasu ka.',
        vn: 'Anh/chị cho tôi biết giấy tờ cần thiết được không?',
      },
      {
        jp: '申請書はどこにありますか。',
        romaji: 'Shinseisho wa doko ni arimasu ka.',
        vn: 'Đơn xin lấy ở đâu ạ?',
      },
      {
        jp: '結果はいつごろ出ますか。',
        romaji: 'Kekka wa itsugoro demasu ka.',
        vn: 'Kết quả khoảng bao giờ có ạ?',
      },
      {
        jp: '受け取りの時に何を持って来ればいいですか。',
        romaji: 'Uketori no toki ni nani o motte kureba ii desu ka.',
        vn: 'Khi đến nhận cần mang theo gì?',
      },
      {
        jp: '手数料はいくらかかりますか。',
        romaji: 'Tesuuryou wa ikura kakarimasu ka.',
        vn: 'Phí thủ tục là bao nhiêu ạ?',
      },
    ],
    keyTerms: [
      {
        term: '在留期間',
        reading: 'ざいりゅうきかん',
        meaningVi: 'thời hạn lưu trú (visa)',
        noteVi: 'Ghi trên mặt thẻ 在留カード (vd "5年", "3年", "1年"). Khi hết hạn phải gia hạn (更新) hoặc đổi tư cách (変更), nếu không sẽ thành overstay.',
      },
      {
        term: '在留資格',
        reading: 'ざいりゅうしかく',
        meaningVi: 'tư cách lưu trú (loại visa)',
        noteVi: 'Vd "技術・人文知識・国際業務", "留学", "家族滞在", "永住者". Quyết định bạn được làm gì ở Nhật. Khác với 在留期間 (chỉ là thời hạn).',
      },
      {
        term: '更新',
        reading: 'こうしん',
        meaningVi: 'gia hạn (cùng loại visa)',
        noteVi: 'Nộp tại 入管 trước khi 在留期間 hết. Khuyến nghị 3 tháng trước hạn — không sớm quá 3 tháng.',
      },
      {
        term: '変更',
        reading: 'へんこう',
        meaningVi: 'đổi tư cách lưu trú',
        noteVi: 'Khi đổi loại visa (vd 留学 → 技人国 sau khi tốt nghiệp). Nộp tại 入管 trước khi visa cũ hết hạn.',
      },
      {
        term: '不法残留',
        reading: 'ふほうざんりゅう',
        meaningVi: 'lưu trú bất hợp pháp (overstay)',
        noteVi: 'Tự động xảy ra khi 在留期間 hết mà chưa gia hạn / đổi tư cách. Hậu quả: bị 退去強制 (trục xuất) + cấm tái nhập 5-10 năm.',
      },
    ],
    officialLinks: [
      { label: '在留カードの有効期間の更新申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00011.html' },
      { label: '在留カードとは？— 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/whatzairyu_00001.html?hl=en' },
      { label: '特定在留カード等交付申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/tokutei.html' },
      { label: 'Tra cứu cục xuất nhập cảnh', url: 'https://www.moj.go.jp/isa/about/region/index.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Đầu tiên: phân biệt 2 thủ tục dễ nhầm',
        description: 'Hai thủ tục KHÁC HẲN nhau:\n\n• **在留期間更新許可申請** = gia hạn VISA / thời hạn lưu trú. Đa số người Việt cần cái này.\n• **在留カードの有効期間の更新申請** = gia hạn HẠN VẬT LÝ thẻ. Chỉ vĩnh trú / HSP2 / trẻ em <16.\n\nMở mặt thẻ — xem ngày nào sắp hết: 在留期間 (visa) hay 有効期限 (thẻ vật lý).',
        documents: [
          'Thẻ cư trú hiện tại',
          'Hộ chiếu',
          'Thông tin tư cách lưu trú hiện tại',
        ],
        tip: 'Người đi làm, du học, gia đình thông thường hay nhầm 2 thủ tục này. Đọc kỹ tên tiếng Nhật trước khi chuẩn bị hồ sơ.',
      },
      {
        step: 2,
        title: 'Chuẩn bị 4 thứ',
        description: 'Theo trang ISA, cần 4 thứ:\n\n1. Đơn xin (lấy tại ISA hoặc tải online)\n2. Ảnh 4×3cm chụp <3 tháng, nền trắng/sáng\n3. Hộ chiếu (bản gốc)\n4. Thẻ cư trú hiện tại\n\nTrẻ em <16 hoặc người đại diện nộp thay → cần giấy tờ thêm; gọi ISA hỏi trước.',
        documents: [
          'Đơn xin gia hạn hiệu lực thẻ cư trú',
          'Ảnh thẻ 縦4cm × 横3cm, nền trắng/sáng, chụp trong 3 tháng gần nhất',
          'Hộ chiếu',
          'Thẻ cư trú hiện tại',
        ],
        tip: 'Trang chính thức ghi thủ tục này không mất phí. Nếu thông tin tại quầy khác, hãy yêu cầu xác nhận và xem họ tính phí theo thủ tục nào.',
      },
      {
        step: 3,
        title: 'Nộp tại 入国管理局',
        description: 'Đến 入国管理局 khu vực bạn cư trú. Lấy số chờ. Khi đến lượt, nói: "在留カードの有効期間更新申請をしたいです." Nộp hồ sơ → nhận giấy hẹn → đi về. Người đại diện hợp pháp có thể nộp thay trong một số trường hợp.',
        documents: [],
        tip: 'Đi trước hạn vài tháng để tránh thẻ hết hiệu lực trong lúc chờ xử lý.',
      },
      {
        step: 4,
        title: 'Nhận thẻ cư trú mới',
        description: 'Sau khi được xử lý, bạn nhận thẻ cư trú mới có hạn hiệu lực mới. Từ 14/06/2026, nếu thuộc thủ tục áp dụng và muốn gộp chức năng My Number Card, hãy hỏi rõ lựa chọn 特定在留カード; nếu không xin 特定在留カード, vẫn có mẫu thẻ cư trú mới không gộp My Number.',
        documents: [
          'Thẻ cư trú cũ',
          'Hộ chiếu',
          'My Number Card nếu xin 特定在留カード theo hướng dẫn của ISA',
        ],
        tip: 'Sau khi nhận thẻ mới, đọc kỹ TẠI QUẦY trước khi đi về: họ tên, ngày sinh, quốc tịch/khu vực, tư cách lưu trú, hạn lưu trú, hạn hiệu lực, và thông tin My Number nếu là 特定在留カード. Sai chữ nào yêu cầu chỉnh ngay.',
      },
    ],
  };

export default residenceCardValidity;
