import type { AdminGuide } from '../../../../types/content';

const residenceCardInfoChange: AdminGuide = {
    id: 'residence-card-info-change',
    category: 'immigration',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Đổi thông tin trên thẻ cư trú',
    titleJp: '住居地以外の記載事項変更届出',
    icon: 'create',
    color: '#8E44AD',
    description: 'Khai báo khi thay đổi họ tên, ngày sinh, giới tính, quốc tịch/khu vực trên thẻ cư trú trong vòng 14 ngày. KHÁC việc đổi địa chỉ (làm tại 市役所). Yêu cầu giấy tờ chứng minh có thể khác theo từng Nyukan và lý do đổi — nên xác nhận trước khi đi.',
    searchKeywords: [
      'doi ten the cu tru',
      'doi ho ten zairyuu',
      'doi quoc tich the cu tru',
      'doi gioi tinh the cu tru',
      'doi ngay sinh the cu tru',
      'doi thong tin the residence',
      'doi ten sau ket hon',
      'doi ten sau ly hon',
      'kekkon ten doi',
      'rikon ten doi',
      'nhap quoc tich Nhat',
      'kika',
      'name change visa',
      'residence card change',
      '14 ngay khai bao',
      '住居地以外',
      '住居地以外の記載事項変更',
      'じゅうきょちいがいのきさいじこうへんこう',
      '記載事項変更',
      '在留カード再交付',
      '氏名変更',
      '帰化',
      '婚姻',
      '訂正',
      'パスポート新規',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Đổi thông tin ngoài địa chỉ trên thẻ cư trú là thủ tục ISA; đổi địa chỉ cư trú vẫn làm tại 市役所/区役所.',
      sourceVerifiedAt: '2026-05-06',
      nextReviewAt: '2026-12-01',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Giấy tờ Việt Nam / Nhật có cách viết tên khác nhau hoặc ngày thay đổi pháp lý không rõ.',
        'Bạn đổi quốc tịch, đổi tên sau kết hôn/ly hôn hoặc giấy tờ nước ngoài cần dịch/chứng nhận.',
        'Đã quá hạn 14 ngày hoặc thông tin trên thẻ, hộ chiếu, ngân hàng không còn khớp.',
      ],
    },
    quickAction: {
      deadline: 'Nộp trong vòng 14 ngày kể từ ngày thay đổi họ tên, ngày sinh, giới tính hoặc quốc tịch/khu vực.',
      office: 'Cục xuất nhập cảnh có thẩm quyền theo nơi cư trú.',
      doNow: [
        'Xác định thay đổi thuộc thông tin ngoài địa chỉ, không phải đổi địa chỉ.',
        'Chuẩn bị giấy tờ chứng minh thay đổi và bản dịch tiếng Nhật nếu cần.',
        'Kiểm tra lại thông tin in trên thẻ sau khi được cập nhật.',
      ],
      bring: ['Thẻ cư trú hiện tại', 'Hộ chiếu', 'Giấy tờ chứng minh thay đổi', 'Bản dịch tiếng Nhật nếu giấy tờ không phải tiếng Nhật', 'Ảnh thẻ nếu được yêu cầu cấp thẻ mới'],
      ifLate: 'Nộp càng sớm càng tốt; nếu quá hạn, ISA có thể yêu cầu văn bản giải thích lý do.',
      officialSourceLabels: ['住居地以外の記載事項変更届出 — 出入国在留管理庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_card-infochange_hero.jpg'),
    heroImageCaption: 'Khai báo thay đổi thông tin cá nhân trên thẻ cư trú',
    whoIsThisFor: [
      'Người có thẻ cư trú và đã đổi họ tên, ngày sinh, giới tính hoặc quốc tịch/khu vực.',
      'Người đổi hộ chiếu hoặc giấy tờ quốc tịch khiến thông tin trên thẻ cư trú không còn khớp.',
      'Người vừa kết hôn/ly hôn hoặc có thay đổi pháp lý về tên cần cập nhật giấy tờ tại Nhật.',
    ],
    whenToDo: [
      'Trong vòng 14 ngày kể từ ngày phát sinh thay đổi thuộc diện khai báo.',
      'Trước khi dùng thẻ cư trú cho thủ tục ngân hàng, bảo hiểm, thuê nhà hoặc ISA tiếp theo nếu thông tin đã khác.',
      'Không dùng thủ tục này để đổi địa chỉ cư trú; địa chỉ là thủ tục riêng tại 市役所/区役所.',
    ],
    whereToDo: [
      'Cục xuất nhập cảnh (ISA) có thẩm quyền theo nơi cư trú.',
      'Có thể kiểm tra mẫu đơn và yêu cầu giấy tờ trên trang ISA trước khi đi.',
    ],
    documentsChecklist: [
      { label: '住居地以外の記載事項変更届出書', required: true },
      { label: 'Thẻ cư trú hiện tại', required: true },
      { label: 'Hộ chiếu', required: true },
      { label: 'Giấy tờ chứng minh thay đổi', required: true, note: 'Ví dụ: hộ chiếu mới, giấy đổi tên, giấy tờ quốc tịch hoặc giấy tờ hộ tịch liên quan.' },
      { label: 'Bản dịch tiếng Nhật', required: false, note: 'Có thể cần nếu giấy tờ chứng minh không phải tiếng Nhật.' },
    ],
    commonMistakes: [
      'Nhầm đổi thông tin cá nhân với đổi địa chỉ cư trú.',
      'Chỉ đổi hộ chiếu/ngân hàng mà quên cập nhật thông tin trên thẻ cư trú.',
      'Không giữ giấy tờ chứng minh ngày thay đổi chính thức.',
      'Đi ISA thiếu bản dịch hoặc giấy tờ gốc chứng minh thay đổi.',
    ],
    faq: [
      {
        question: 'Đổi địa chỉ có phải làm ở ISA không?',
        answer: 'Thông thường không. Đổi địa chỉ cư trú là thủ tục tại 市役所/区役所. Bài này dành cho các mục ngoài địa chỉ như họ tên, ngày sinh, giới tính, quốc tịch/khu vực.',
      },
      {
        question: 'Đổi họ sau kết hôn thì có cần khai báo không?',
        answer: 'Nếu thông tin họ tên trên giấy tờ pháp lý thay đổi và cần cập nhật trên thẻ cư trú, bạn nên khai báo trong thời hạn quy định và mang giấy tờ chứng minh thay đổi.',
      },
      {
        question: 'Nếu giấy tờ chứng minh là tiếng Việt thì sao?',
        answer: 'Có thể cần bản dịch tiếng Nhật tùy hồ sơ và yêu cầu của ISA. Nên chuẩn bị bản dịch và giữ bản gốc để đối chiếu.',
      },
    ],
    counterPhrases: [
      {
        jp: '住居地以外の記載事項変更届出をしたいです。',
        romaji: 'Juukyochi igai no kisai jikou henkou todokede o shitai desu.',
        vn: 'Tôi muốn nộp khai báo thay đổi thông tin (ngoài địa chỉ) trên thẻ cư trú.',
        note: 'Tên đầy đủ của thủ tục — dùng đúng để Nyukan biết bạn đang làm gì.',
      },
      {
        jp: '結婚で氏名が変わりました。新しいパスポートも持って来ました。',
        romaji: 'Kekkon de shimei ga kawarimashita. Atarashii pasupooto mo motte kimashita.',
        vn: 'Tôi đổi họ tên sau kết hôn. Hộ chiếu mới tôi cũng đã mang theo.',
        note: 'Lý do phổ biến nhất. Hộ chiếu mới + giấy đăng ký kết hôn là bằng chứng chính.',
      },
      {
        jp: 'ベトナムの書類は日本語訳と公証付きで用意しました。',
        romaji: 'Betonamu no shorui wa nihongo-yaku to koushou-tsuki de youi shimashita.',
        vn: 'Giấy tờ Việt Nam tôi đã chuẩn bị kèm bản dịch tiếng Nhật và công chứng.',
        note: 'Giấy đổi tên / khai sinh VN thường cần dịch công chứng — không tự dịch.',
      },
      {
        jp: '新しい在留カードはいつ受け取れますか。',
        romaji: 'Atarashii zairyuu kaado wa itsu uketoremasu ka.',
        vn: 'Khi nào tôi nhận được thẻ cư trú mới?',
        note: 'Thường cấp ngay trong ngày hoặc trong vài tuần — tùy Nyukan.',
      },
      {
        jp: '14日を過ぎてしまいましたが、申請できますか。',
        romaji: '14-nichi o sugite shimaimashita ga, shinsei dekimasu ka.',
        vn: 'Tôi đã quá 14 ngày, vẫn nộp được không ạ?',
        note: 'Vẫn nộp được nhưng có thể bị Nyukan ghi nhận chậm — ảnh hưởng hồ sơ tương lai. Nộp ngay + giải thích trung thực.',
      },
    ],
    keyTerms: [
      {
        term: '住居地以外の記載事項変更届出',
        reading: 'じゅうきょちいがいのきさいじこうへんこうとどけで',
        meaningVi: 'khai báo thay đổi thông tin ngoài địa chỉ',
        noteVi: 'Áp dụng cho: 氏名 (họ tên), 生年月日 (ngày sinh), 性別 (giới tính), 国籍・地域 (quốc tịch/khu vực). KHÁC 住居地変更届 (đổi địa chỉ — làm tại 市役所). Deadline 14 ngày. Miễn phí.',
      },
      {
        term: '在留カード再交付',
        reading: 'ざいりゅうカードさいこうふ',
        meaningVi: 'cấp lại thẻ cư trú',
        noteVi: 'Thường tự động đi kèm với 記載事項変更 (Nyukan in thẻ mới). Cũng dùng riêng khi thẻ hư hỏng / mất. Nếu mất thẻ → xem guide [[lost-residence-card]].',
      },
      {
        term: '氏名変更',
        reading: 'しめいへんこう',
        meaningVi: 'thay đổi họ tên',
        noteVi: 'Trường hợp phổ biến: 婚姻 (kết hôn), 離婚 (ly hôn), 訂正 (sửa lỗi cũ), 改名 (đổi tên hợp pháp). CẦN: hộ chiếu mới có tên đã đổi + giấy đăng ký hộ tịch (婚姻届受理証明書 hoặc tương đương) + bản dịch tiếng Nhật.',
      },
      {
        term: '帰化',
        reading: 'きか',
        meaningVi: 'nhập quốc tịch Nhật',
        noteVi: 'Sau khi 帰化 được phê duyệt → mất quốc tịch cũ (Việt Nam không cho phép 2 quốc tịch trong nhiều trường hợp) → KHÔNG còn là người nước ngoài → KHÔNG cần thẻ cư trú nữa. Trong giai đoạn chuyển đổi, vẫn cần khai báo với Nyukan + 市役所. Tham khảo 法務省.',
      },
      {
        term: '婚姻届受理証明書',
        reading: 'こんいんとどけじゅりしょうめいしょ',
        meaningVi: 'giấy chứng nhận đã nộp đơn kết hôn',
        noteVi: 'Lấy tại 市役所 (~350 yên/bản) sau khi 婚姻届 được tiếp nhận. Đây là giấy Nyukan cần để xác nhận lý do đổi tên. Lấy nhiều bản (~3-5 bản) vì nhiều thủ tục khác cũng cần (ngân hàng, công ty, bảo hiểm).',
      },
      {
        term: '14日以内',
        reading: '14にちいない',
        meaningVi: 'trong vòng 14 ngày',
        noteVi: 'Deadline cho 記載事項変更. Tính từ ngày sự kiện xảy ra (ngày kết hôn theo 婚姻届, ngày nhập quốc tịch, ngày đổi tên hợp pháp). Quá hạn = vẫn nộp được nhưng Nyukan có thể ghi nhận → ảnh hưởng hồ sơ 永住 / 変更 sau này.',
      },
      {
        term: '訂正',
        reading: 'ていせい',
        meaningVi: 'sửa lỗi (thông tin sai trên thẻ cũ)',
        noteVi: 'Lý do dùng khi phát hiện Nyukan in sai tên / ngày sinh trên thẻ cũ. Mang giấy tờ gốc (hộ chiếu) để chứng minh thông tin đúng. Sửa lỗi của Nyukan thường KHÔNG phải lỗi của bạn — nên báo sớm.',
      },
      {
        term: '公証翻訳',
        reading: 'こうしょうほんやく',
        meaningVi: 'bản dịch có công chứng',
        noteVi: 'Yêu cầu cho giấy tờ Việt Nam: hộ chiếu Việt cũ, khai sinh, kết hôn, ly hôn. KHÔNG tự dịch + ký — phải qua dịch giả công chứng. Phí tham khảo: 2,000-5,000 yên/trang. Có thể dùng dịch vụ tại Đại sứ quán VN tại Nhật.',
      },
    ],
    officialLinks: [
      { label: '住居地以外の記載事項変更届出 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00009.html' },
      { label: '在留カード再交付申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/nyuukokukanri10_00012.html' },
      { label: '帰化許可申請 — 法務省', url: 'https://www.moj.go.jp/MINJI/minji78.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra thay đổi có thuộc diện khai báo không',
        description: 'Nếu đổi họ tên, ngày sinh, giới tính hoặc quốc tịch/khu vực, cần khai báo trong vòng 14 ngày kể từ ngày thay đổi.',
        documents: [
          'Thẻ cư trú hiện tại',
          'Hộ chiếu',
          'Giấy tờ chứng minh thay đổi: hộ chiếu mới, giấy đổi tên, giấy tờ quốc tịch...',
        ],
        tip: 'Đổi địa chỉ là thủ tục riêng tại 市役所/区役所, không dùng bài này.',
      },
      {
        step: 2,
        title: 'Điền 住居地以外の記載事項変更届出書 và nộp tại ISA',
        description: '**Thông tin cần điền trên đơn** (tải PDF: https://www.moj.go.jp/isa/content/001426705.pdf hoặc nhận tại quầy ISA):\n\n| Trường | Ghi như thế nào |\n|---|---|\n| 氏名 / 在留カード番号 | Tên và số thẻ hiện tại (trước khi đổi) |\n| 生年月日 / 在留資格 | Copy từ thẻ cư trú hiện tại |\n| 変更の内容 | Chọn mục thay đổi: 氏名 / 生年月日 / 性別 / 国籍・地域 |\n| 変更前の記載事項 | Thông tin hiện có trên thẻ |\n| 変更後の記載事項 | Thông tin mới (theo hộ chiếu mới hoặc giấy tờ xác nhận) |\n| 変更年月日 | Ngày thay đổi chính thức (ngày đổi tên, ngày nhập quốc tịch...) |\n| 変更の事由 | Lý do: 婚姻 (kết hôn đổi tên), 帰化 (nhập quốc tịch), 訂正 (sửa lỗi)... |\n\nKèm theo: thẻ cư trú + hộ chiếu mới phản ánh thông tin đổi + giấy tờ chứng minh thay đổi (bản dịch nếu cần).',
        documents: [
          'Đơn khai báo — tải PDF: https://www.moj.go.jp/isa/content/001426705.pdf hoặc nhận tại quầy ISA',
          'Hộ chiếu mới hoặc giấy tờ quốc tịch phản ánh thay đổi',
          'Thẻ cư trú hiện tại',
          'Ảnh縦4cm × 横3cm, nền trắng hoặc sáng màu đơn sắc, chụp trong 3 tháng gần nhất — chỉ khi được yêu cầu cấp thẻ mới',
        ],
        tip: 'Giấy tờ nước ngoài (hộ chiếu Việt Nam, giấy đổi tên) thường cần bản dịch tiếng Nhật có công chứng. Xác nhận yêu cầu cụ thể với cục xuất nhập cảnh trước khi đến.',
      },
      {
        step: 3,
        title: 'Nộp tại cục xuất nhập cảnh',
        description: 'Mang hồ sơ đến ISA có thẩm quyền để cập nhật thông tin.',
        documents: [],
        tip: 'Sau khi nhận thẻ cập nhật, kiểm tra kỹ từng mục trên thẻ.',
      },
    ],
  };

export default residenceCardInfoChange;
