import type { AdminGuide } from '../../../../types/content';

const taxYearEndAdjustmentFiling: AdminGuide = {
    id: 'tax-year-end-adjustment-filing',
    category: 'money',
    lastVerified: '2026-06-20',
    priority: 'high',
    title: 'Thuế, 年末調整, 確定申告 và 扶養',
    titleJp: '税金・年末調整・確定申告・扶養の基本',
    icon: 'receipt',
    color: '#8E44AD',
    description: 'Guide thực tế cho người đi làm ở Nhật: khi nào công ty làm 年末調整, khi nào phải tự làm 確定申告, cách hiểu 扶養 và hồ sơ扶養 thân nhân ở Việt Nam, cùng các thay đổi lớn áp dụng trong mùa khai 2026.',
    searchKeywords: [
      'năm cuối thuế',
      'thuế cuối năm',
      'điều chỉnh thuế',
      '年末調整',
      'nenmatsu chousei',
      'year-end adjustment',
      '扶養',
      'fuyou',
      'người phụ thuộc',
      '扶養控除',
      'fuyou koujo',
      'dependent deduction',
      '配偶者控除',
      'haiguusha koujo',
      '基礎控除',
      'kiso koujo',
      '国外居住親族',
      'kokugai kyojuu shinzoku',
      '送金関係書類',
      '38万円送金',
      '特定親族特別控除',
      'khai phụ thuộc bố mẹ Việt Nam',
      'gửi tiền về Việt Nam khai thuế',
      '扶養控除等申告書',
      '保険料控除申告書',
      '配偶者控除等申告書',
      '20万円 thu nhập phụ',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: '年末調整 do 国税庁 (NTA) quản lý theo 所得税法. Công ty thực hiện 年末調整 cho người lao động đáp ứng điều kiện (đã nộp 扶養控除等申告書 + tổng lương ≤ 20 triệu yên + không thuộc các trường hợp loại trừ). 扶養 cho 国外居住親族 (thân nhân ngoài Nhật) áp dụng theo §57-3 所得税法 + quy tắc bổ sung hiệu lực 01/2023: với người 30-70 tuổi cần thêm điều kiện đặc biệt + giấy 38万円送金書類. Mùa khai 2026 có sửa đổi 基礎控除 + xuất hiện 特定親族特別控除 cho thân nhân 19-23 tuổi.',
      sourceVerifiedAt: '2026-05-16',
      nextReviewAt: '2026-12-31',
      riskLevel: 'high',
      whenToAskExpert: [
        'Khai 扶養 nhiều thân nhân ở Việt Nam mà giấy tờ quan hệ không khớp tên/phiên âm trên hộ chiếu → hỏi 税理士 hoặc 行政書士 trước khi nộp (sai → bị bác + có thể bị 加算税).',
        'Có thu nhập từ VN (lương cũ, tiền cho thuê BĐS, lãi ngân hàng) → 租税条約 VN-Nhật phức tạp, hỏi 税理士.',
        'Bị 税務署 hỏi giải trình về 扶養 đã khai năm trước → KHÔNG tự trả lời, gọi 税理士 trước khi gửi giấy tờ.',
        'Đổi từ công ty trong năm + công ty cũ chưa cấp 源泉徴収票 → đòi công ty cũ trước; nếu không lấy được trong 1 tháng → báo 税務署 theo 源泉徴収票不交付の届出書.',
        'Chuyển 38万円 cho thân nhân 30-70 tuổi mà không phải qua bank transfer chính thức → có thể bị bác 扶養 — hỏi 税理士 cách document hợp lệ.',
      ],
    },
    quickAction: {
      deadline: '年末調整: nộp 扶養控除等申告書 + các form 控除 cho công ty thường vào cuối tháng 11. 確定申告: 16/02 – 15/03 năm sau cho thu nhập năm trước. 還付申告 (chỉ xin hoàn): từ 01/01.',
      office: 'Phòng nhân sự / 給与担当 công ty (cho 年末調整). 税務署 nơi cư trú hoặc e-Tax (cho 確定申告). Tham vấn miễn phí: 確定申告会場 (T2-T3) + NTA tax answer hotline.',
      doNow: [
        'Cuối T11: công ty phát form. Điền 扶養控除等申告書 (ai là phụ thuộc) + 基礎控除申告書 + 配偶者控除等申告書 + 保険料控除申告書 (bảo hiểm xã hội + nhân thọ + iDeCo).',
        'Nếu khai 扶養 cha mẹ ở Việt Nam: chuẩn bị 親族関係書類 (giấy khai sinh + sổ hộ khẩu + bản dịch tiếng Nhật có công chứng) + 送金関係書類 (sao kê chuyển khoản qua bank cả năm).',
        'Nếu thân nhân ở VN 30-70 tuổi: thêm 38万円送金書類 (chứng minh chuyển ≥ 38万円/năm cho mỗi người, từng người riêng).',
        'Nộp tất cả form + giấy tờ cho công ty trước hạn (thường ~20/11).',
        'Tháng 1: nhận 源泉徴収票 — kiểm tra tổng lương + thuế + tổng 控除 đã áp dụng.',
        'Nếu 源泉徴収票 thấy thiếu 控除 hoặc có nguồn thu khác → tự làm 確定申告 từ 16/02 để xin hoàn / khai bổ sung.',
      ],
      bring: [
        'マイナンバー (12 chữ số) của bản thân + người phụ thuộc',
        '源泉徴収票 từ tất cả nơi đã làm trong năm',
        '保険料控除証明書 (gửi từ bảo hiểm nhân thọ / iDeCo / NISA)',
        '住宅ローン残高証明書 (nếu khai vay nhà năm thứ 2 trở đi)',
        '親族関係書類 + 送金関係書類 + bản dịch (nếu khai 扶養 国外)',
        'Sổ ngân hàng (cho 還付)',
      ],
      ifLate: 'Lỡ hạn 年末調整 → tự làm 確定申告 từ 16/02 (KHÔNG mất quyền 控除). Quá 15/03 確定申告: 無申告加算税 15–20% + 延滞税 ~7.3%/năm; tự申告 trước khi 税務署 phát hiện → giảm 加算税 xuống 5%. Khai sai 扶養 国外 mà bị bác → bị truy thu phần thuế đáng lẽ phải nộp + 過少申告加算税 10%.',
      officialSourceLabels: ['年末調整のしかた — 国税庁'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_tax-filing_hero.jpg'),
    heroImageCaption: 'Thuế cuối năm - phân biệt 年末調整, 確定申告 và hồ sơ 扶養',
    whoIsThisFor: [
      'Người đi làm ở Nhật có lương, có thể có 1 hoặc nhiều nguồn thu.',
      'Người muốn khai 扶養 cho vợ/chồng, con hoặc cha mẹ ở Việt Nam.',
      'Người nghe nói “công ty làm thuế hết rồi” nhưng chưa chắc mình có còn phải tự đi 確定申告 hay không.',
    ],
    whenToDo: [
      'Trong năm: nộp 扶養控除等申告書 cho công ty chính và cập nhật khi gia đình thay đổi.',
      'Cuối năm: làm 年末調整 với công ty nếu đủ điều kiện.',
      'Mùa khai năm 2026 cho thu nhập năm 2025: về nguyên tắc từ ngày 16/02/2026 đến 16/03/2026 để nộp 確定申告 theo thông báo của NTA.',
      'Bất kỳ lúc nào nếu bạn có nhiều nguồn thu, không được công ty 年末調整 đầy đủ, hoặc muốn xin hoàn thuế.',
    ],
    whereToDo: [
      'Công ty nơi bạn làm chính: 年末調整, các mẫu扶養, 基礎控除, 配偶者控除, 保険料控除, 住宅ローン控除 năm sau đầu tiên nếu đủ điều kiện.',
      '国税庁/e-Tax hoặc tax office: 確定申告 khi bạn phải tự khai hoặc muốn xin hoàn.',
      'Nếu khai扶養 cho thân nhân ở Việt Nam: công ty hoặc tax filing sẽ yêu cầu bộ giấy chứng minh quan hệ và chứng minh chuyển tiền đúng chuẩn của NTA.',
    ],
    estimatedTime: 'Nếu hồ sơ đơn giản và chỉ có một công ty làm 年末調整, bạn chủ yếu phải nộp giấy cho công ty vào cuối năm. Nếu phải tự làm 確定申告, thời gian thực tế phụ thuộc vào việc bạn đã gom đủ源泉徴収票, chứng từ bảo hiểm, chứng từ chuyển tiền cho thân nhân ở nước ngoài và các khoản thu khác hay chưa.',
    fees: [
      '年末調整 tại công ty không phải là dịch vụ thu phí riêng cho người lao động.',
      'Nộp 確定申告 trực tiếp qua e-Tax hoặc tax office về nguyên tắc không có “phí nộp hồ sơ”, nhưng có thể phát sinh chi phí in ấn, dịch thuật, gửi hồ sơ hoặc phí dịch vụ nếu thuê người làm hộ.',
      'Khai扶養 thân nhân ở nước ngoài thường phát sinh chi phí dịch thuật và chuyển tiền quốc tế, đây là phần nhiều người bỏ quên khi tính toán lợi ích thực tế.',
    ],
    documentsChecklist: [
      { label: '源泉徴収票 từ công ty chính và công ty phụ (nếu có)', required: true },
      { label: 'Các mẫu 年末調整 công ty yêu cầu: 扶養控除等申告書, 基礎控除申告書, 配偶者控除等申告書, 保険料控除申告書...', required: false },
      { label: 'Chứng từ bảo hiểm, iDeCo, bảo hiểm nhân thọ hoặc các khoản được控除 khác', required: false },
      { label: 'Nếu khai扶養 cho thân nhân ở Việt Nam: giấy tờ chứng minh quan hệ thân nhân', required: false, note: 'Giấy khai sinh, kết hôn, sổ hộ khẩu/các giấy tương đương, kèm bản dịch nếu là tiếng nước ngoài.' },
      { label: 'Nếu khai扶養 cho thân nhân ở nước ngoài: giấy tờ chuyển tiền', required: false, note: 'NTA yêu cầu送金関係書類 hoặc 38万円送金書類 tùy trường hợp.' },
      { label: 'Nếu phải tự làm 確定申告: toàn bộ chứng từ thu nhập khác ngoài lương', required: false },
    ],
    commonMistakes: [
      'Nghĩ 年末調整 và 確定申告 là một việc duy nhất.',
      'Tưởng công ty làm 年末調整 thì chắc chắn bản thân không còn nghĩa vụ khai thuế gì nữa.',
      'Khai扶養 thân nhân ở Việt Nam nhưng không có bộ giấy chứng minh quan hệ và chuyển tiền đúng chuẩn NTA.',
      'Không biết quy tắc 30-70 tuổi đối với国外居住親族, dẫn tới khai扶養 sai cho cha mẹ hoặc anh chị em ở Việt Nam.',
      'Có 2 nơi làm việc hoặc có thu nhập phụ mà vẫn nghĩ “dưới 20 man là khỏi quan tâm gì”.',
      'Nhầm giữa thuế thu nhập quốc gia và住民税 của địa phương.',
    ],
    faq: [
      {
        question: '年末調整 là gì và ai được công ty làm?',
        answer: 'NTA giải thích 年末調整 là thủ tục công ty dùng để quyết toán lại thuế thu nhập đã khấu trừ trong năm. Người được làm thường là người đã nộp 扶養控除等申告書 cho công ty và thuộc nhóm đủ điều kiện. Ví dụ, người có lương trên 2,000万円 thì không thuộc đối tượng 年末調整.',
      },
      {
        question: 'Khi nào phải tự làm 確定申告 dù đã đi làm công ty?',
        answer: 'NTA nêu một số trường hợp điển hình: lương năm trên 2,000万円; có thêm thu nhập ngoài lương/退職所得 vượt 20万円; có từ 2 nơi trả lương và phần chưa 年末調整 cộng với thu nhập khác vượt ngưỡng; hoặc công ty không thể làm 年末調整 đầy đủ cho bạn. Ngoài ra, nếu muốn xin hoàn thuế thì bạn cũng có thể phải tự khai.',
      },
      {
        question: 'Khai扶養 cho cha mẹ ở Việt Nam có được không?',
        answer: 'Có thể trong một số trường hợp, nhưng không chỉ cần “gửi tiền về nhà” là đủ. NTA yêu cầu bộ chứng minh quan hệ thân nhân và chứng minh chuyển tiền. Với国外居住親族 từ 30 đến 70 tuổi, quy tắc hiện hành chặt hơn: chỉ một số nhóm mới đủ điều kiện, như du học, người khuyết tật hoặc người được bạn chuyển ít nhất 38万円/năm cho chi phí sinh hoạt hoặc học tập.',
      },
      {
        question: 'Mùa khai năm 2026 có gì mới đáng chú ý?',
        answer: 'Có. NTA đã công bố các thay đổi (令和7年度税制改正) áp dụng cho thu nhập năm 2025: nâng 基礎控除 (48万→58万) + 給与所得控除 tối thiểu (55万→65万) → sàn miễn thuế 所得税 vĩnh viễn lên 123万円 (給与収入); ngưỡng 合計所得 của 扶養親族・配偶者 nâng 48万→58万; và tạo mới 特定親族特別控除 cho thân nhân 19-22 tuổi. Lưu ý: mốc 160万 chỉ áp dụng band thu nhập thấp nhất (gồm phần cộng thêm tạm thời), không phải ngưỡng chung; và 住民税 KHÔNG được giảm theo (基礎控除 của 住民税 vẫn 43万). Những thay đổi này ảnh hưởng trực tiếp đến 年末調整 từ cuối năm 2025 và 確定申告 mùa 2026.',
      },
      {
        question: 'Ngưỡng 20万円 thu nhập phụ nghĩa là khỏi khai hết mọi thứ đúng không?',
        answer: 'Không nên hiểu vậy. NTA giải thích quy tắc 20万円 chỉ là quy định trong một số trường hợp để không phải nộp 確定申告 bắt buộc. Nhưng nếu bạn đã đi khai để xin hoàn thuế hoặc vì lý do khác, các khoản thu nhập liên quan vẫn phải khai đầy đủ. Ngoài ra,住民税 có logic riêng.',
      },
    ],
    counterPhrases: [
      {
        jp: '年末調整の用紙をください。',
        romaji: 'Nenmatsu chousei no youshi o kudasai.',
        vn: 'Cho tôi xin tờ khai 年末調整.',
        note: 'Hỏi 給与担当 / 人事 cuối tháng 10–11.',
      },
      {
        jp: 'ベトナムにいる家族を扶養に入れたいです。',
        romaji: 'Betonamu ni iru kazoku o fuyou ni iretai desu.',
        vn: 'Tôi muốn khai phụ thuộc cho gia đình ở Việt Nam.',
        note: 'Báo công ty từ đầu năm để chuẩn bị 親族関係書類 + 送金関係書類 trước hạn nộp.',
      },
      {
        jp: '源泉徴収票をもう一度発行してください。',
        romaji: 'Gensen choushuuhyou o mou ichido hakkou shite kudasai.',
        vn: 'Xin công ty cấp lại 源泉徴収票.',
        note: 'Trường hợp mất + cần làm 確定申告. Công ty bắt buộc cấp lại theo §226 所得税法.',
      },
      {
        jp: '副業の収入があるのですが、確定申告は必要ですか。',
        romaji: 'Fukugyou no shuunyuu ga aru no desu ga, kakutei shinkoku wa hitsuyou desu ka.',
        vn: 'Tôi có thu nhập từ việc làm thêm, có cần 確定申告 không?',
        note: 'Hỏi 税務署 (mỗi 税務署 có quầy 確定申告相談 miễn phí T2-T3) — > 20万 thu nhập phụ thường phải khai.',
      },
      {
        jp: '海外送金の証明書類は何が必要ですか。',
        romaji: 'Kaigai soukin no shoumei shorui wa nani ga hitsuyou desu ka.',
        vn: 'Tôi cần giấy gì để chứng minh chuyển tiền ra nước ngoài?',
        note: 'Hỏi 給与担当 hoặc 税理士. Cần sao kê bank gốc + tên người nhận + ngày chuyển + tổng cộng ≥ 38万円/người (nếu thân nhân 30-70 tuổi).',
      },
    ],
    keyTerms: [
      {
        term: '年末調整',
        reading: 'ねんまつちょうせい',
        meaningVi: 'điều chỉnh thuế cuối năm (công ty làm thay)',
        noteVi: 'Cuối năm công ty đối chiếu số thuế đã trừ hàng tháng với số thuế thực sự phải đóng → trừ thêm hoặc hoàn lại. Bạn thấy trên 給与明細 tháng 12 thường có dòng "年末調整" với số dương (hoàn) hoặc âm (đóng thêm). Điều kiện: lương ≤ 20 triệu yên + đã nộp 扶養控除等申告書. Người lương > 20 triệu yên phải tự 確定申告.',
      },
      {
        term: '扶養',
        reading: 'ふよう',
        meaningVi: 'người được bạn nuôi/chu cấp (giảm thuế)',
        noteVi: 'KHÔNG đơn giản là "có gửi tiền về". Để khai 扶養 phải: thân nhân thực sự (chứng minh bằng giấy quan hệ), thu nhập của họ thấp dưới ngưỡng 合計所得 (cho thân nhân ở Nhật), và bạn thật sự chu cấp (chứng minh bằng 送金関係書類). ⚠️ Từ thu nhập 2025 (令和7年分) ngưỡng 合計所得 của 扶養親族 đã nâng từ 48万円 lên 58万円 (給与収入 từ 103万 lên 123万) — số cũ 48万 đã lỗi thời. Khai sai → bị truy thu + 加算税.',
      },
      {
        term: '扶養控除等申告書',
        reading: 'ふようこうじょとうしんこくしょ',
        meaningVi: 'tờ khai phụ thuộc (form chính của 年末調整)',
        noteVi: 'Form quan trọng nhất công ty phát đầu năm hoặc khi vào công ty. Liệt kê người phụ thuộc (vợ/chồng, con, cha mẹ). Bạn chỉ được nộp 1 nơi trong năm — chọn công ty chính. Nếu không nộp, công ty áp 乙欄 (trừ thuế cao hơn).',
      },
      {
        term: '配偶者控除',
        reading: 'はいぐうしゃこうじょ',
        meaningVi: 'khoản trừ thuế cho vợ/chồng',
        noteVi: 'Áp dụng khi 合計所得 của vợ/chồng ≤ 58万円/năm (令和7年分 trở đi; trước 2025 là 48万) + cùng nhà với bạn. Khoản trừ 38万円 (chuẩn) hoặc cao hơn nếu vợ/chồng cao tuổi. Khác 配偶者特別控除 (cho vợ/chồng 合計所得 trên 58万 đến 133万円, trừ ít hơn). Ngưỡng có thể thay đổi tiếp — hãy kiểm tra với 給与担当 hoặc 税務署.',
      },
      {
        term: '基礎控除',
        reading: 'きそこうじょ',
        meaningVi: 'khoản trừ cơ bản (ai cũng được)',
        noteVi: 'Khoản trừ thuế áp dụng tự động cho mọi người nộp thuế ở Nhật. Trước 2025: 48万円. Từ thu nhập năm 2025 (khai 2026): sửa lại — 基礎控除 cơ bản nâng 48万→58万, cộng 給与所得控除 tối thiểu (55万→65万) tạo sàn miễn thuế vĩnh viễn 123万円 (給与収入). Nhóm thu nhập thấp nhất còn được cộng thêm tạm thời lên tới 95万 (thành mốc hay nghe là 160万) nhưng phần cộng thêm này GIẢM DẦN theo band và sẽ hết hạn — chỉ 123万 là sàn cố định. ⚠️ Đây là thuế thu nhập (所得税); 住民税 có 基礎控除 RIÊNG vẫn giữ 43万 nên đừng tưởng được giảm 住民税 theo. Bạn không cần xin riêng — công ty tự áp khi 年末調整.',
      },
      {
        term: '国外居住親族',
        reading: 'こくがいきょじゅうしんぞく',
        meaningVi: 'thân nhân sống ở nước ngoài (rất quan trọng với người Việt)',
        noteVi: 'Cha mẹ, con cái, anh em ruột đang ở Việt Nam. Để khai 扶養 cho họ: cần 親族関係書類 (giấy khai sinh + sổ hộ khẩu + bản dịch tiếng Nhật) + 送金関係書類 (sao kê chuyển khoản qua bank). Đặc biệt: thân nhân 30-70 tuổi từ 01/2023 cần thêm điều kiện đặc biệt (du học / khuyết tật / hoặc nhận ≥ 38万円/năm).',
      },
      {
        term: '送金関係書類',
        reading: 'そうきんかんけいしょるい',
        meaningVi: 'giấy tờ chuyển tiền cho thân nhân ở nước ngoài',
        noteVi: 'Bằng chứng bạn thực sự chu cấp. Hợp lệ: sao kê ngân hàng (Wise, Revolut, ngân hàng Nhật, MoneyGram, Western Union…) ghi tên người gửi-nhận + ngày + số tiền + đơn vị. KHÔNG hợp lệ: gửi tiền mặt qua người quen, gửi qua tài khoản người khác. Cần đầy đủ 1 năm tài chính.',
      },
      {
        term: '特定親族特別控除',
        reading: 'とくていしんぞくとくべつこうじょ',
        meaningVi: 'khoản trừ đặc biệt cho thân nhân nhóm 19-23 tuổi (mới từ thu nhập 2025)',
        noteVi: 'Khoản trừ mới có hiệu lực từ mùa khai 2026. Áp dụng cho thân nhân 19-23 tuổi (thường là con sinh viên / em trong tuổi này) có thu nhập VƯỢT ngưỡng 扶養 thường nhưng vẫn trong phạm vi nhất định. Trừ giảm dần theo mức thu nhập. Người Việt có con học đại học ở Nhật bằng tiền bạn → kiểm tra với 給与担当 / NTA.',
      },
    ],
    officialLinks: [
      { label: '令和7年分 年末調整のしかた — 国税庁', url: 'https://www.nta.go.jp/publication/pamph/gensen/nencho2025/01.htm' },
      { label: '年末調整の対象となる人 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/2665.htm' },
      { label: '年末調整のしかた — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/gensen/2662.htm' },
      { label: '給与所得者で確定申告が必要な人 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1900.htm' },
      { label: '令和7年分確定申告期の確定申告会場のお知らせ — 国税庁', url: 'https://www.nta.go.jp/information/other/data/r07/kakushin_kaijo/index.htm' },
      { label: '国外居住親族に係る扶養控除等の適用について — 国税庁', url: 'https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/gensen/kokugai/' },
      { label: '扶養控除 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1180.htm' },
      { label: '配偶者控除 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1191.htm' },
      { label: '基礎控除 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1199.htm' },
      { label: '特定親族特別控除 — 国税庁', url: 'https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/1177.htm' },
      { label: '令和7年度税制改正による所得税の基礎控除の見直し等について — 国税庁', url: 'https://www.nta.go.jp/users/gensen/2025kiso/' },
    ],
    steps: [
      {
        step: 1,
        title: 'Đầu tiên: xác định bạn đang ở nhánh nào',
        description: 'Hãy tự hỏi 3 câu: bạn chỉ có một công ty hay nhiều nơi trả lương? Công ty có làm 年末調整 cho bạn không? Bạn có thu nhập ngoài lương hoặc muốn xin thêm控除/hoàn thuế không? Trả lời ba câu này sẽ quyết định bạn dừng ở 年末調整 hay phải đi tiếp sang 確定申告.',
        documents: [
          'Nguồn thu trong năm',
          'Danh sách công ty đã trả lương',
          'Nguồn thu nhập phụ nếu có',
        ],
        tip: 'Nếu không phân nhánh từ đầu, bạn rất dễ hoặc khai thừa, hoặc tưởng không cần khai nhưng thực ra vẫn phải làm.',
      },
      {
        step: 2,
        title: 'Hiểu đúng 年末調整: công ty đang làm gì cho bạn',
        description: 'NTA nêu rõ 年末調整 là việc công ty đối chiếu số thuế đã khấu trừ trong năm với số thuế thực phải nộp của bạn. Điều kiện cơ bản là bạn đã nộp 扶養控除等申告書 cho công ty đó và thuộc nhóm được làm 年末調整. Đây là lý do một người chỉ nên có một “công ty chính” cho bộ hồ sơ扶養 này.',
        documents: [
          '扶養控除等申告書',
          'Các mẫu 年末調整 công ty phát cuối năm',
          '源泉徴収票 của công ty cũ nếu chuyển việc giữa năm',
        ],
        tip: 'Nếu chuyển việc giữa năm mà không nộp源泉徴収票 của công ty cũ cho công ty mới, công ty mới có thể không 年末調整 đúng và bạn sẽ phải tự đi sửa bằng 確定申告.',
      },
      {
        step: 3,
        title: 'Khi nào phải tự làm 確定申告',
        description: 'NTA liệt kê rõ các trường hợp điển hình: lương năm trên 2,000万円; một nơi trả lương nhưng có thêm thu nhập ngoài lương/退職所得 trên 20万円; nhiều nơi trả lương và phần chưa 年末調整 cộng với thu nhập khác vượt ngưỡng; hoặc công ty không thể年末調整 cho bạn. Ngoài ra, nếu bạn muốn xin hoàn thuế vì thiếu控除 hoặc chưa 年末調整, bạn cũng có thể tự khai.',
        documents: [
          '源泉徴収票 của tất cả nơi trả lương',
          'Chứng từ thu nhập phụ',
          'Chứng từ控除 muốn xin thêm',
        ],
        tip: 'Ngưỡng 20万円 không phải “vé miễn thuế” cho mọi tình huống. Đó chỉ là một điều kiện trong bài toán có phải nộp確定申告 bắt buộc hay không.',
      },
      {
        step: 4,
        title: '扶養: hiểu cho đúng trước khi khai cho gia đình ở Việt Nam',
        description: '扶養 trong thuế không đơn giản là “có gửi tiền về nhà”. Bạn phải xem người đó có thuộc nhóm đủ điều kiện hay không, mức thu nhập của họ, độ tuổi, nơi cư trú và bộ giấy tờ chứng minh quan hệ/chuyển tiền. Đặc biệt với国外居住親族, NTA yêu cầu hồ sơ rất cụ thể.',
        documents: [
          'Giấy tờ chứng minh quan hệ thân nhân',
          'Giấy chuyển tiền',
          'Bản dịch tiếng Nhật nếu giấy tờ là tiếng Việt',
        ],
        tip: 'Đừng nộp giấy tờ photo mờ hoặc giấy tờ quan hệ không khớp tên/phiên âm với hộ chiếu và thẻ cư trú. Đây là lỗi rất hay gặp.',
      },
      {
        step: 5,
        title: 'Điểm khó nhất:扶養 thân nhân ở nước ngoài từ 30 đến 70 tuổi',
        description: 'Theo NTA, từ 30 đến 70 tuổi thì国外居住親族 không đương nhiên được tính扶養. Họ phải thuộc một trong các nhóm được phép, ví dụ người đi du học, người khuyết tật hoặc người mà bạn chuyển ít nhất 38万円/năm cho sinh hoạt/học tập. Nếu không rơi vào các nhóm này thì không được áp dụng扶養控除.',
        documents: [
          '親族関係書類',
          '送金関係書類 hoặc 38万円送金書類',
          '留学ビザ等書類 nếu khai theo diện留学',
        ],
        tip: 'Đây là chỗ nhiều người Việt bị bác扶養 vì chỉ gửi tiền nhỏ lẻ hoặc gửi không đứng tên đúng người nhận.',
      },
      {
        step: 6,
        title: 'Những thay đổi lớn đang áp dụng trong mùa khai 2026',
        description: 'NTA đã công bố các thay đổi cho thu nhập năm 2025 và mùa khai 2026: 基礎控除 được sửa lại, có mức tối đa 95万円 ở nhóm thu nhập thấp; điều kiện所得 của扶養親族 thay đổi; và xuất hiện 特定親族特別控除 cho nhóm thân nhân 19-23 tuổi có所得 vượt ngưỡng扶養 thường nhưng vẫn trong phạm vi nhất định. Nếu bạn dùng kinh nghiệm từ 2024 hoặc sớm hơn để tự ước tính thuế 2026, rất dễ sai.',
        documents: [
          'Tài liệu 年末調整 năm 2025',
          'Bảng控除 mới của NTA',
          'Thông tin thu nhập của người thân nếu khai配偶者控除 hoặc 特定親族特別控除',
        ],
        tip: 'Một thay đổi nhỏ trên giấy có thể làm lệch cả việc bạn được hoàn hay phải nộp thêm. Đừng ước lượng theo “năm ngoái chắc giống năm nay”.',
      },
    ],
  };

export default taxYearEndAdjustmentFiling;
