import type { AdminGuide } from '../../../../types/content';

const trafficAccidentResponse: AdminGuide = {
    id: 'traffic-accident-response',
    category: 'traffic',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Khi gặp tai nạn giao thông',
    titleJp: '交通事故に遭ったとき',
    icon: 'alert-circle',
    color: '#C0392B',
    searchKeywords: [
      'tai nan',
      'tai nan giao thong',
      'jiko',
      'tai nan xe dap',
      'tai nan xe may',
      'tai nan oto',
      'va cham',
      'jinshin jiko',
      'busson jiko',
      '110',
      '119',
      'canh sat',
      'cuu thuong',
      'bao hiem xe',
      'bao hiem xe dap',
      'jibaiseki',
      'ninni hoken',
      'dashcam',
      'drive recorder',
      'hit and run',
      'bo chay',
      'jidan',
      'thuong luong rieng',
      '交通事故',
      '事故',
      '人身事故',
      '物損事故',
      '自賠責保険',
      '任意保険',
      '過失割合',
      '示談',
      '交通事故証明書',
      'ひき逃げ',
      '当て逃げ',
      '救急',
      '警察',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote:
        'Tai nạn giao thông áp dụng 道路交通法 (Luật giao thông đường bộ) toàn quốc — báo cảnh sát là bắt buộc theo §72, kể cả va chạm nhẹ chỉ hỏng xe. 自賠責保険 (bảo hiểm trách nhiệm bắt buộc) áp dụng theo 自動車損害賠償保障法 toàn quốc; xe đạp KHÔNG có 自賠責 nhưng nhiều 都道府県 (Tokyo, Osaka, Saitama, Kanagawa, Nagoya...) bắt buộc 自転車保険 theo điều lệ địa phương. Bồi thường + tỷ lệ lỗi do bảo hiểm tính theo tiền lệ tư pháp — KHÔNG tự thương lượng.',
      sourceVerifiedAt: '2026-05-17',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        '人身事故 (có người bị thương) — luôn có rủi ro 過失運転致死傷罪 hoặc 危険運転致死傷罪 (hình sự). Gọi 当番弁護士 (luật sư trực, miễn phí lần đầu, 弁護士会 hỗ trợ) ngay nếu bị tạm giữ.',
        'ひき逃げ / 当て逃げ (bỏ chạy khỏi hiện trường) — vi phạm hình sự, có thể bị thu hồi visa. Liên hệ luật sư + cảnh sát ngay (đi tự thú trong 24h giúp giảm tội).',
        'Đối phương ép ký 示談 / nhận tiền mặt tại hiện trường — gọi bảo hiểm hoặc 交通事故紛争処理センター trước khi ký bất kỳ giấy gì.',
        'Không có 任意保険 + gây 人身事故 — rủi ro tài chính lớn (自賠責 chỉ trả tối đa 120 vạn yên thương tật, 3,000 vạn yên tử vong; ngoài giới hạn này bạn tự trả). Hỏi luật sư + cân nhắc 法テラス (Hỗ trợ Pháp lý) nếu thu nhập thấp.',
        'Tranh chấp 過失割合 với bảo hiểm đối phương — nhờ 交通事故紛争処理センター (miễn phí) hoặc luật sư chuyên 交通事故.',
        'Là người nước ngoài + có triệu chứng むち打ち (whiplash) kéo dài — chứng minh quan hệ tai nạn ↔ chấn thương khó nếu khám trễ; cần 診断書 trong 1–2 ngày sau tai nạn.',
      ],
    },
    quickAction: {
      deadline:
        'Báo cảnh sát NGAY tại hiện trường (luật bắt buộc — bỏ qua là vi phạm 道交法 §72). Báo bảo hiểm trong vòng vài giờ, KHÔNG để qua đêm. Đi khám trong 1–2 ngày kể cả khi cảm thấy không sao — むち打ち có thể nặng lên sau 24–72h.',
      office:
        '110 (cảnh sát) — toàn quốc, miễn phí. 119 (cứu thương) — nếu có người bị thương. Bảo hiểm: gọi số trên thẻ hợp đồng. 交通事故証明書 cấp bởi 自動車安全運転センター (~1,000 yên/bản). Tư vấn pháp lý: 当番弁護士 miễn phí (gọi qua 弁護士会 địa phương), 法テラス hotline 0570-078374.',
      doNow: [
        'Bật hazard, đẩy xe khỏi lòng đường nếu an toàn, kiểm tra thương tích bản thân và đối phương.',
        'Gọi 119 NẾU có người bị thương (đau, chảy máu, choáng) — KHÔNG tự đánh giá "không sao" với người khác.',
        'Gọi 110 báo cảnh sát kể cả va chạm nhẹ. Câu đầu: "事故です。〇〇で交通事故がありました。"',
        'Chụp ảnh: 4 góc xe, biển số đối phương, vị trí xe, vết phanh, đèn tín hiệu, biển báo, thời tiết. Quay video 360° hiện trường nếu có thể.',
        'Trao đổi: tên, số điện thoại, địa chỉ, biển số, công ty bảo hiểm đối phương. Lấy số điện thoại nhân chứng trước khi họ đi.',
        'Gọi công ty bảo hiểm của bạn (số trên thẻ hợp đồng). Đừng nói tỷ lệ lỗi, đừng hứa tiền — chỉ báo "sự thật khách quan" và để bảo hiểm xử lý.',
      ],
      bring: [
        '在留カード',
        'Bằng lái (運転免許証 / 国際運転免許証 / 自国の免許 + dịch JAF)',
        '車検証 + 自賠責保険証明書 (để trong xe ô tô / xe máy)',
        'Thẻ 任意保険 / 自転車保険 (chụp ảnh sẵn để trong điện thoại)',
        'Điện thoại có pin + dashcam (kiểm tra dashcam ghi đè không — chuyển file sang điện thoại ngay)',
        'Tiền mặt + thẻ (để đi khám sau khi xử lý hiện trường)',
      ],
      ifLate:
        'Đã rời hiện trường mà không báo cảnh sát = vi phạm 道交法 (có thể bị truy tố ひき逃げ / 当て逃げ). Quay lại hiện trường hoặc đến 警察署 / 交番 gần nhất tự thú trong 24h — luật sư nói tự thú sớm giúp giảm tội đáng kể. KHÔNG đợi đối phương tìm bạn. Liên hệ 当番弁護士 trước khi đi.',
      officialSourceLabels: [
        '事故にあったらまずどうする？ — 国土交通省',
        '110番通報6つのポイント — 神奈川県警察',
        '119番緊急通報 — 総務省消防庁',
        '交通事故対応等 — 日本損害保険協会 (SONPO)',
        '交通事故証明書 — 自動車安全運転センター',
      ],
    },
    description: 'Checklist xử lý ngay tại hiện trường tai nạn ở Nhật: cứu người, gọi 119/110, ghi chứng cứ, báo bảo hiểm và lấy 交通事故証明書. KHÔNG tự thương lượng 示談 tại chỗ — luôn để bảo hiểm và cảnh sát ghi nhận.',
    heroImage: require('../../../../../assets/content/daily-life/ag_bicycle-rules_hero.jpg'),
    heroImageCaption: 'Đường dân sinh tại Nhật — khi xảy ra 交通事故, ưu tiên an toàn, cứu người và báo cảnh sát',
    whoIsThisFor: [
      'Người lái ô tô, xe máy, xe đạp hoặc xe thuê tại Nhật.',
      'Người đi bộ, hành khách, người chứng kiến hoặc nạn nhân trong tai nạn giao thông.',
      'Người có bảo hiểm xe, bảo hiểm xe đạp hoặc cần chuẩn bị trước các bước liên hệ bảo hiểm sau tai nạn.',
    ],
    whenToDo: [
      'Ngay khi xảy ra va chạm, dù là người gây tai nạn, nạn nhân hay người chứng kiến.',
      'Khi có người bị thương, có nguy cơ cháy nổ, xe nằm giữa đường hoặc giao thông bị cản trở.',
      'Trong ngày xảy ra tai nạn: báo bảo hiểm, đi khám nếu có đau/choáng và lưu lại toàn bộ chứng cứ.',
    ],
    whereToDo: [
      'Tại hiện trường, nhưng chỉ sau khi đã đứng ở vị trí an toàn và tránh gây tai nạn tiếp theo.',
      'Gọi 119 nếu có người bị thương hoặc cần cứu hộ; gọi 110 để báo cảnh sát về tai nạn.',
      'Sau hiện trường: bệnh viện/phòng khám, công ty bảo hiểm, 自動車安全運転センター hoặc trung tâm tư vấn tai nạn địa phương nếu cần.',
    ],
    estimatedTime: 'Xử lý hiện trường cần làm ngay trong vài phút đầu. Việc khám bệnh, lấy 交通事故証明書, claim bảo hiểm và thương lượng bồi thường có thể kéo dài nhiều ngày đến nhiều tuần.',
    fees: [
      'Gọi 110/119 là cuộc gọi khẩn cấp; không coi đây là dịch vụ tư vấn thông thường.',
      'Chi phí khám chữa bệnh, sửa xe, kéo xe, chứng nhận tai nạn và luật sư phụ thuộc bảo hiểm, lỗi tai nạn và từng trường hợp.',
      'Không tự hứa trả tiền mặt hoặc ký thỏa thuận tại hiện trường trước khi hỏi công ty bảo hiểm/đơn vị tư vấn.',
    ],
    documentsChecklist: [
      { label: 'Thông tin vị trí tai nạn', required: true, note: 'Địa chỉ, giao lộ, biển hiệu gần đó, hướng di chuyển, lane/đường đang đứng.' },
      { label: 'Thông tin đối phương', required: true, note: 'Tên, địa chỉ, số điện thoại, biển số, loại xe, công ty bảo hiểm nếu biết.' },
      { label: 'Ảnh/video hiện trường', required: true, note: 'Chụp xe, vết hư hỏng, vị trí dừng, biển báo, đèn tín hiệu, vết phanh và thời tiết nếu an toàn.' },
      { label: 'Thông tin nhân chứng', required: false, note: 'Tên, số điện thoại và ghi chú lời chứng nếu người chứng kiến đồng ý.' },
      { label: 'Giấy tờ cá nhân và xe', required: false, note: 'Bằng lái, thẻ cư trú, 車検証, 自賠責保険証明書, thông tin 任意保険 hoặc bảo hiểm xe đạp.' },
      { label: '診断書, hóa đơn khám bệnh và 交通事故証明書', required: false, note: 'Cần cho claim bảo hiểm/bồi thường; 交通事故証明書 không cấp nếu không báo cảnh sát.' },
    ],
    commonMistakes: [
      'Rời hiện trường khi chưa cứu người, chưa phòng nguy hiểm và chưa báo cảnh sát.',
      'Nghĩ va chạm nhẹ hoặc chỉ hỏng đồ thì không cần báo cảnh sát.',
      'Đứng giữa đường để chụp ảnh quá lâu, làm tăng nguy cơ tai nạn tiếp theo.',
      'Tự thương lượng tiền mặt hoặc ký giấy nhận lỗi tại chỗ trước khi hỏi bảo hiểm.',
      'Không đi khám vì thấy chỉ đau nhẹ; triệu chứng cổ/lưng/đầu có thể nặng hơn sau đó.',
      'Quên lưu camera hành trình hoặc thông tin nhân chứng trước khi dữ liệu bị ghi đè/mất.',
    ],
    faq: [
      {
        question: 'Tai nạn rất nhẹ, chỉ trầy xe thì có cần gọi cảnh sát không?',
        answer: 'Có. SONPO và các nguồn chính thức đều nhấn mạnh tai nạn giao thông cần báo cảnh sát. Nếu không báo, bạn có thể không lấy được 交通事故証明書 và việc claim bảo hiểm sẽ khó hơn.',
      },
      {
        question: 'Có người bị thương thì gọi 119 hay 110 trước?',
        answer: 'Nếu có người bị thương hoặc nguy hiểm đến tính mạng, ưu tiên gọi 119 hoặc nhờ người xung quanh gọi 119 ngay. Đồng thời phải bảo đảm cảnh sát được báo qua 110; nếu có nhiều người, chia nhau gọi.',
      },
      {
        question: 'Có nên xin lỗi hoặc nhận lỗi ngay tại hiện trường không?',
        answer: 'Có thể nói lời quan tâm như “大丈夫ですか” để kiểm tra tình trạng, nhưng không nên tự nhận tỷ lệ lỗi, hứa bồi thường hoặc ký thỏa thuận. Hãy để cảnh sát ghi nhận sự việc và hỏi công ty bảo hiểm trước.',
      },
      {
        question: 'Bị xe bỏ chạy thì làm gì?',
        answer: 'Không đuổi theo nếu nguy hiểm. Ghi biển số, màu xe, hướng đi, ảnh/video nếu có, gọi 110 và đi khám nếu bị thương. Dashcam và nhân chứng rất quan trọng trong trường hợp này.',
      },
      {
        question: 'Tôi đi xe đạp tông người đi bộ — có cần báo cảnh sát không?',
        answer: 'Có, bắt buộc. 道交法 §72 áp dụng cho xe đạp như xe có động cơ. Nếu có người bị thương, đây là 人身事故 (kể cả là va chạm xe đạp) — có thể bị 過失致死傷罪. Nhiều 都道府県 bắt buộc 自転車保険 — nếu không có, bạn tự trả bồi thường. Đã có án trường hợp người đi xe đạp tông người đi bộ phải bồi thường ~9,500 vạn yên.',
      },
      {
        question: 'Tôi không nói tiếng Nhật giỏi — cảnh sát yêu cầu tôi viết 供述調書 thì sao?',
        answer: 'Có quyền yêu cầu 通訳 (phiên dịch). Nói "ベトナム語の通訳をお願いします". KHÔNG ký bất kỳ giấy gì bạn không hiểu hoàn toàn — kể cả 供述調書. Nếu bị tạm giữ, gọi 当番弁護士 (luật sư trực miễn phí lần đầu) trước khi viết / ký.',
      },
      {
        question: '示談 (thương lượng riêng) có hợp pháp không? Tại sao không nên ký tại hiện trường?',
        answer: '示談 hợp pháp nhưng nên đi qua bảo hiểm. Tại hiện trường bạn bị shock, chưa biết hết thương tích (むち打ち xuất hiện sau 24h), chưa biết hư hỏng xe đầy đủ. Ký 示談 quá sớm = mất quyền claim sau này. Bảo hiểm có người chuyên xử lý — để họ thương lượng giúp.',
      },
      {
        question: 'Không có 任意保険 mà gây tai nạn — có thể bị gì?',
        answer: '自賠責 chỉ trả tối đa 120 vạn yên thương tật / 3,000 vạn yên tử vong và KHÔNG trả tiền sửa xe đối phương / xe mình. Vượt giới hạn này bạn tự trả. Nếu là 人身事故 nặng, số tiền có thể lên hàng triệu yên + ảnh hưởng visa. 法テラス hỗ trợ pháp lý cho người thu nhập thấp — gọi 0570-078374 sớm.',
      },
    ],
    counterPhrases: [
      {
        jp: '事故です。〇〇で交通事故がありました。',
        romaji: 'Jiko desu. Marumaru de koutsuu jiko ga arimashita.',
        vn: 'Có tai nạn. Tại 〇〇 vừa xảy ra tai nạn giao thông.',
        note: 'Câu đầu khi gọi 110. Thay 〇〇 bằng địa chỉ / mốc gần.',
      },
      {
        jp: 'けが人がいます。救急車もお願いします。',
        romaji: 'Keganin ga imasu. Kyuukyuusha mo onegai shimasu.',
        vn: 'Có người bị thương. Cho xin xe cứu thương luôn.',
        note: 'Khi gọi 110 và muốn yêu cầu thêm 119. Cảnh sát có thể liên hệ giúp.',
      },
      {
        jp: '保険会社に連絡してから決めます。今、サインはしません。',
        romaji: 'Hokengaisha ni renraku shite kara kimemasu. Ima, sain wa shimasen.',
        vn: 'Tôi cần liên lạc bảo hiểm trước khi quyết định. Bây giờ tôi không ký.',
        note: 'Từ chối ký 示談 hoặc giấy nhận lỗi tại hiện trường. Lịch sự nhưng cứng rắn.',
      },
      {
        jp: '示談はしません。警察と保険会社を通してください。',
        romaji: 'Jidan wa shimasen. Keisatsu to hokengaisha o tooshite kudasai.',
        vn: 'Tôi không thương lượng riêng. Vui lòng làm việc qua cảnh sát và bảo hiểm.',
        note: 'Khi đối phương ép thương lượng tiền mặt tại chỗ. Lặp lại nhiều lần nếu cần.',
      },
      {
        jp: 'ドライブレコーダーの映像があります。',
        romaji: 'Doraibu rekoodaa no eizou ga arimasu.',
        vn: 'Tôi có camera hành trình (dashcam) ghi lại.',
        note: 'Nói cho cảnh sát + bảo hiểm biết. Chuyển file dashcam sang điện thoại ngay tại hiện trường để tránh bị ghi đè.',
      },
      {
        jp: 'ベトナム語の通訳をお願いします。',
        romaji: 'Betonamu-go no tsuuyaku o onegai shimasu.',
        vn: 'Cho tôi phiên dịch tiếng Việt.',
        note: 'Yêu cầu thông dịch khi viết 供述調書 hoặc khi không hiểu cảnh sát hỏi gì. Đây là quyền — không phải xin xỏ.',
      },
      {
        jp: '当番弁護士を呼んでください。',
        romaji: 'Touban bengoshi o yonde kudasai.',
        vn: 'Vui lòng gọi luật sư trực giúp tôi.',
        note: 'Khi bị tạm giữ vì 人身事故 / ひき逃げ. 当番弁護士 miễn phí lần đầu — cảnh sát phải hỗ trợ liên hệ 弁護士会.',
      },
      {
        jp: '診断書をもらえますか?',
        romaji: 'Shindansho o moraemasu ka?',
        vn: 'Tôi có thể xin giấy chẩn đoán không?',
        note: 'Hỏi khi đi khám sau tai nạn. 診断書 cần cho claim bảo hiểm + chứng minh 人身事故.',
      },
    ],
    keyTerms: [
      {
        term: '人身事故',
        reading: 'じんしんじこ',
        meaningVi: 'tai nạn có người bị thương / tử vong',
        noteVi: 'Khác 物損事故 (chỉ hỏng xe). 人身事故 luôn có rủi ro hình sự (過失運転致死傷罪) — phải có 診断書. Nếu không đi khám trong 1–2 ngày, có thể bị xếp sang 物損事故 và mất quyền claim thương tật.',
      },
      {
        term: '物損事故',
        reading: 'ぶっそんじこ',
        meaningVi: 'tai nạn chỉ hỏng tài sản',
        noteVi: 'Chỉ liên quan dân sự + bảo hiểm. Vẫn phải báo cảnh sát theo 道交法 §72. KHÔNG báo cảnh sát = không được cấp 交通事故証明書 = bảo hiểm rất khó xử lý.',
      },
      {
        term: '自賠責保険',
        reading: 'じばいせきほけん',
        meaningVi: 'bảo hiểm trách nhiệm bắt buộc',
        noteVi: 'Bắt buộc cho ô tô + xe máy theo 自動車損害賠償保障法. CHỈ trả thương tật/tử vong người khác, KHÔNG trả tiền xe. Giới hạn thấp (120 vạn yên thương tật / 3,000 vạn yên tử vong). Xe đạp KHÔNG có 自賠責.',
      },
      {
        term: '任意保険',
        reading: 'にんいほけん',
        meaningVi: 'bảo hiểm tự nguyện (phụ thêm)',
        noteVi: 'Mua thêm ngoài 自賠責, cover phần vượt giới hạn + tiền sửa xe + tài sản đối phương + xe của mình. Cực kỳ nên có — không có = rủi ro hàng chục triệu yên. Phí tham khảo: 5–15 vạn yên/năm tùy tuổi + lịch sử lái xe.',
      },
      {
        term: '過失割合',
        reading: 'かしつわりあい',
        meaningVi: 'tỷ lệ lỗi giữa các bên',
        noteVi: 'Quyết định bồi thường theo %. Vd: 80:20 = bạn lỗi 80%. Tính theo tiền lệ tư pháp + Báo cáo cảnh sát + dashcam + lời nhân chứng. Đừng tự nhận lỗi tại hiện trường — bảo hiểm tính giúp.',
      },
      {
        term: '示談',
        reading: 'じだん',
        meaningVi: 'thương lượng ngoài toà án',
        noteVi: 'Hợp pháp NHƯNG phải qua bảo hiểm và sau khi xác định đầy đủ thương tật/hư hỏng. Ký 示談 sớm = mất quyền claim. Nếu đối phương ép ký tại hiện trường, nói "保険会社を通してください" và từ chối.',
      },
      {
        term: '交通事故証明書',
        reading: 'こうつうじこしょうめいしょ',
        meaningVi: 'giấy chứng nhận tai nạn giao thông',
        noteVi: 'Do 自動車安全運転センター cấp dựa trên hồ sơ cảnh sát. ~1,000 yên/bản. CẦN cho mọi claim bảo hiểm. KHÔNG báo cảnh sát = không có giấy này = bảo hiểm có thể từ chối claim.',
      },
      {
        term: 'ひき逃げ / 当て逃げ',
        reading: 'ひきにげ / あてにげ',
        meaningVi: 'bỏ chạy sau khi gây tai nạn',
        noteVi: 'ひき逃げ = bỏ chạy khỏi 人身事故 (hình sự nặng, có thể tù). 当て逃げ = bỏ chạy khỏi 物損事故 (cũng vi phạm 道交法). Tự thú trong 24h giúp giảm tội. Bị truy tố = rủi ro visa.',
      },
      {
        term: '当番弁護士',
        reading: 'とうばんべんごし',
        meaningVi: 'luật sư trực (miễn phí lần đầu)',
        noteVi: 'Hệ thống của 弁護士会 — luật sư đến gặp người bị tạm giữ trong vòng 24h, lần đầu miễn phí. Khi bị tạm giữ vì 人身事故, nói "当番弁護士を呼んでください" với cảnh sát. KHÔNG viết 供述調書 trước khi gặp luật sư.',
      },
    ],
    officialLinks: [
      { label: '事故にあったらまずどうする？ — 国土交通省', url: 'https://www.mlit.go.jp/jidosha/jibaiseki/accident/correspondence/index.html' },
      { label: '110番通報6つのポイント — 神奈川県警察', url: 'https://www.police.pref.kanagawa.jp/kurashi/110ban_riyo/mesg2005.html' },
      { label: '119番緊急通報 — 総務省消防庁', url: 'https://www.fdma.go.jp/mission/enrichment/kyukyumusen_kinkyutuhou/119.html' },
      { label: '交通事故対応等 — 日本損害保険協会 (SONPO)', url: 'https://soudanguide.sonpo.or.jp/car/q025.html' },
      { label: '交通事故証明書 — 自動車安全運転センター', url: 'https://www.jsdc.or.jp/certificate/tabid/112/Default.aspx' },
      { label: '交通事故紛争処理センター — tư vấn miễn phí 過失割合', url: 'https://www.jcstad.or.jp/' },
      { label: '当番弁護士 — 日本弁護士連合会', url: 'https://www.nichibenren.or.jp/legal_advice/sodan/touban.html' },
      { label: '法テラス — 0570-078374 hỗ trợ pháp lý', url: 'https://www.houterasu.or.jp/' },
      { label: '自転車保険義務化都道府県一覧 — 国土交通省', url: 'https://www.mlit.go.jp/jidosha/anzen/bicycle/insurance.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Dừng lại, bảo vệ mạng người và tránh tai nạn tiếp theo',
        description: 'Dừng xe ngay khi an toàn, bật hazard nếu có, đưa bản thân và người khác ra vị trí an toàn nếu có thể. Nếu có người bị thương, gọi 119 hoặc nhờ người xung quanh gọi. Không di chuyển người bị thương nặng trừ khi đang có nguy cơ bị xe khác tông, cháy nổ hoặc nguy hiểm trực tiếp.',
        documents: ['Vị trí chính xác của tai nạn', 'Số người bị thương', 'Mô tả ngắn tình trạng người bị thương'],
        tip: 'Nếu bạn cũng bị choáng, hãy nhờ người gần đó gọi 119/110 và đứng ở nơi an toàn trước khi chụp ảnh hay trao đổi thông tin.',
      },
      {
        step: 2,
        title: 'Gọi 110 và báo đúng thông tin',
        description: 'Báo cảnh sát rằng có 交通事故, nói rõ thời điểm, vị trí, có người bị thương không, xe liên quan và tình trạng hiện trường. Khi gọi bằng điện thoại di động, hãy đứng yên ở nơi an toàn và không tắt máy vì cảnh sát có thể gọi lại.',
        documents: ['Địa chỉ/giao lộ/landmark', 'Biển số và loại xe nếu thấy được', 'Tên và số điện thoại của người gọi'],
        tip: 'Theo cảnh sát, 110 là số khẩn cấp cho sự kiện hoặc 事故. Nếu chỉ cần tư vấn sau đó, dùng police station hoặc #9110 thay vì gọi 110.',
      },
      {
        step: 3,
        title: 'Ghi chứng cứ và thông tin đối phương',
        description: 'Khi đã an toàn và cảnh sát/119 đã được gọi, chụp ảnh xe, vết hỏng, vị trí, biển báo, đèn tín hiệu, dấu phanh và điều kiện đường. Trao đổi thông tin cơ bản với đối phương, lưu thông tin nhân chứng và bảo vệ dữ liệu dashcam.',
        documents: [
          'Tên, địa chỉ, số điện thoại của đối phương',
          'Biển số, loại xe, công ty bảo hiểm nếu biết',
          'Ảnh/video hiện trường',
          'Thông tin nhân chứng nếu có',
        ],
        tip: 'Không ký giấy 示談, không nhận tiền mặt và không hứa “tự xử lý riêng” tại hiện trường. Việc này có thể ảnh hưởng đến bảo hiểm.',
      },
      {
        step: 4,
        title: 'Báo bảo hiểm và đi khám',
        description: 'Sau khi xử lý hiện trường, gọi công ty bảo hiểm hoặc đại lý càng sớm càng tốt. Nếu có đau đầu, đau cổ/lưng, tê, choáng hoặc va đập mạnh, hãy đi khám sớm và giữ hóa đơn/診断書. MLIT lưu ý nếu khám quá muộn, quan hệ giữa tai nạn và thương tích có thể khó được công nhận.',
        documents: ['Số hợp đồng bảo hiểm', 'Số vụ việc/đồn cảnh sát xử lý nếu có', '診断書 và hóa đơn khám bệnh', 'Ảnh hư hỏng xe/vật dụng'],
        tip: 'Nếu sửa xe, hỏi bảo hiểm trước khi tự đặt sửa lớn. Một số bảo hiểm cần xác nhận thiệt hại trước.',
      },
      {
        step: 5,
        title: 'Lấy 交通事故証明書 và theo dõi hồ sơ',
        description: 'Khi cần claim bảo hiểm/bồi thường, xin 交通事故証明書 qua 自動車安全運転センター theo hướng dẫn. Lưu timeline liên hệ với cảnh sát, bệnh viện, bảo hiểm, garage và đối phương cho đến khi hồ sơ kết thúc.',
        documents: ['Thông tin cảnh sát đã xử lý tai nạn', 'Thông tin người liên quan', 'Hồ sơ khám bệnh/sửa xe', 'Biên nhận và email từ bảo hiểm'],
        tip: '交通事故証明書 không được cấp cho tai nạn không báo cảnh sát. Đây là lý do không nên bỏ qua bước gọi 110 dù tai nạn nhìn có vẻ nhẹ.',
      },
    ],
  };

export default trafficAccidentResponse;
