import type { AdminGuide } from '../../../../types/content';

const visaHighlights2026: AdminGuide = {
    id: 'visa-highlights-2026',
    category: 'visa',
    lastVerified: '2026-05-06',
    title: 'Các diện visa đáng chú ý 2026',
    titleJp: '2026年の注目ビザ・在留資格',
    icon: 'sparkles',
    color: '#8E44AD',
    description: 'Tổng hợp các diện visa và tư cách lưu trú được quan tâm nhiều trong năm 2026: J-Skip, J-Find, Digital Nomad, Start-up, eVISA du lịch và các điểm dễ nhầm. KHÔNG phải mọi diện đều phù hợp cho mọi quốc tịch / mọi hồ sơ — kiểm tra điều kiện cụ thể tại MOFA / ISA trước khi quyết định. Trường hợp phức tạp nên tham vấn 行政書士 / 弁護士.',
    searchKeywords: [
      'visa 2026',
      'visa mới Nhật',
      'J-Skip',
      'J-Find',
      'Digital Nomad Japan',
      'デジタルノマド',
      'Start-up visa',
      '起業ビザ',
      'スタートアップ',
      'JAPAN eVISA',
      'Special Highly Skilled Professional',
      '特別高度人材',
      'Future Creation Individual',
      '未来創造人材',
      '指定活動',
      'Designated Activities',
      'COE',
      '在留資格認定証明書',
      'visa cho người tài năng cao',
      'visa khởi nghiệp',
      'visa làm việc từ xa',
      'visa du lịch điện tử',
      'tổng quan visa Nhật',
      'MOFA visa',
      '外務省ビザ',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Visa và tư cách lưu trú do MOFA (Bộ Ngoại giao) + 出入国在留管理庁 (ISA / Bộ Tư pháp) phối hợp quản lý theo 入管法. MOFA cấp visa sticker (tại Đại sứ quán/Lãnh sự ở nước ngoài); ISA cấp tư cách lưu trú khi nhập cảnh + cấp COE (在留資格認定証明書) trong nước. Điều kiện + quốc gia áp dụng + mức thu nhập + thời gian lưu trú KHÁC nhau theo từng diện và CÓ THỂ thay đổi — phải xác nhận thông tin mới nhất trên trang MOFA + ISA tại thời điểm nộp hồ sơ. Digital Nomad: hiện áp dụng cho ~50+ quốc tịch chỉ định (Việt Nam KHÔNG nằm trong danh sách tại thời điểm 2026-05). J-Find / J-Skip: yêu cầu thu nhập / học vấn cụ thể — không phù hợp cho mọi đối tượng.',
      sourceVerifiedAt: '2026-05-06',
      nextReviewAt: '2026-12-01',
      riskLevel: 'medium',
      whenToAskExpert: [
        'Đang phân vân giữa nhiều diện visa (vd J-Skip vs HSP thường vs work visa) → tham vấn 行政書士 chuyên 入管 để so sánh điều kiện cụ thể với hồ sơ cá nhân.',
        'J-Find: chỉ áp dụng cho người mới tốt nghiệp 5 năm gần đây từ trường được liệt kê — nếu không chắc trường có thuộc danh sách không, hỏi MOFA hoặc 行政書士 trước.',
        'Digital Nomad: kiểm tra quốc tịch + nguồn thu nhập (¥10M+/năm ngoài Nhật) + bảo hiểm (¥10M+ chi trả y tế) trước khi nộp. Việt Nam hiện không trong danh sách áp dụng.',
        'Start-up visa: yêu cầu được municipality cụ thể hỗ trợ — không phải mọi 市 / 都道府県 đều có chương trình. Hỏi trực tiếp municipality mục tiêu trước khi lên kế hoạch.',
        'Trường hợp đang ở Nhật + muốn đổi từ tư cách hiện tại sang J-Skip / J-Find / Digital Nomad → xem guide visa-status-change-detailed-scenarios; có thể không đơn giản.',
        'Nghe quảng cáo "visa mới năm 2026 ai cũng được" trên mạng xã hội / từ broker → CẢNH GIÁC, kiểm tra MOFA trực tiếp hoặc hỏi 行政書士. Đa số "visa siêu dễ" là thông tin sai hoặc lừa đảo.',
      ],
    },
    quickAction: {
      deadline: 'Không có deadline áp dụng chung — mỗi diện có timeline + điều kiện riêng. J-Find: cần tốt nghiệp trong 5 năm gần. Digital Nomad: 6 tháng không gia hạn. Start-up: theo kế hoạch chương trình municipality.',
      office: 'MOFA (Đại sứ quán/Lãnh sự Nhật ở nước cư trú) cấp visa sticker. ISA (出入国在留管理庁) cấp COE + tư cách lưu trú trong Nhật. Tham vấn pháp lý: 行政書士会 từng tỉnh / 弁護士会 / 法テラス 0570-078374.',
      doNow: [
        'Đọc kỹ điều kiện diện visa mục tiêu trên trang MOFA — KHÔNG dựa vào "tóm tắt" trên blog / mạng xã hội.',
        'Kiểm tra quốc tịch của bạn có được áp dụng diện đó không (đặc biệt Digital Nomad — 50+ quốc gia chỉ định).',
        'Kiểm tra điều kiện thực tế (thu nhập, học vấn, tuổi, bảo hiểm) — nếu không đáp ứng, KHÔNG nộp (mất phí + thời gian).',
        'Nếu chọn diện cần COE (J-Skip, Start-up): chuẩn bị hồ sơ qua sponsor/municipality tại Nhật trước khi nộp visa.',
        'Nếu chọn diện ngắn hạn (eVISA tourism, Digital Nomad): chuẩn bị tài liệu trước ngày bay theo timeline MOFA.',
        'Trường hợp không chắc diện nào phù hợp → tham vấn 行政書士 chuyên 入管 (phí ~5-20万円, lợi hơn nộp sai).',
      ],
      bring: [
        'Hộ chiếu còn hạn ≥ 6 tháng',
        'CV + bằng cấp + chứng minh thu nhập (cho diện tài năng cao)',
        'Kế hoạch hoạt động tại Nhật (cho J-Find / Digital Nomad / Start-up)',
        'Bảo hiểm y tế/tai nạn (cho Digital Nomad: ≥¥10M chi trả)',
        'COE (do sponsor ở Nhật xin trước — cho J-Skip / Start-up / work visa)',
        'Giấy tờ municipality hỗ trợ (cho Start-up)',
      ],
      ifLate: 'Quá hạn diện đang giữ (vd Digital Nomad hết 6 tháng) → KHÔNG được gia hạn diện đó (Digital Nomad không gia hạn được). Phải rời Nhật hoặc xin đổi sang diện khác phù hợp. Quá hạn = 不法残留 (xem guide overstaying-illegal-stay-procedures). Tham vấn 行政書士 / 弁護士 trước khi hết hạn nếu cần ở lại lâu hơn.',
      officialSourceLabels: ['Work or Long-term stay — MOFA (2026-01-22)', 'Visas and Landing Permission — MOFA'],
    },
    heroImage: require('../../../../../assets/content/daily-life/ag_visa2026_hero.jpg'),
    heroImageCaption: 'Các diện visa nổi bật và thay đổi quan trọng năm 2026',
    whoIsThisFor: [
      'Người đang tìm hiểu diện visa “mới” hoặc đặc thù trong năm 2026.',
      'Người nghe về J-Skip, J-Find, Digital Nomad hoặc Start-up nhưng chưa rõ diện nào phù hợp.',
      'Người muốn phân biệt visa ngắn hạn, long-term stay và designated activities.',
    ],
    whenToDo: [
      'Trước khi chọn hướng đi hồ sơ, nhất là nếu bạn không thuộc các diện đi làm/du học/truyền thống.',
      'Khi nghe thông tin mạng xã hội về “visa mới Nhật Bản” và muốn kiểm tra tên chính thức cùng phạm vi áp dụng.',
    ],
    whereToDo: [
      'Trang Work or Long-term stay của MOFA để xem các nhóm visa dài hạn hiện hành tính đến ngày 22/01/2026.',
      'Trang visa tổng hợp của MOFA và các FAQ liên quan.',
    ],
    estimatedTime: 'Đây là bài định hướng theo nhóm visa. Hồ sơ thực tế có thể khác nhiều tùy tư cách lưu trú cụ thể và nơi nộp hồ sơ.',
    fees: [
      'Phí visa và lệ phí thủ tục phụ thuộc diện hồ sơ và cơ quan tiếp nhận.',
      'Một số diện dùng COE trước, một số diện là visa ngắn hạn, và một số diện chỉ khả dụng trong phạm vi quốc gia/khu vực nhất định.',
    ],
    documentsChecklist: [
      { label: 'Hộ chiếu', required: true },
      { label: 'CV / bằng cấp / chứng minh thu nhập', required: false, note: 'Quan trọng với các diện tài năng cao, J-Skip, J-Find hoặc Digital Nomad.' },
      { label: 'Kế hoạch hoạt động tại Nhật', required: false, note: 'Hữu ích với Start-up, Digital Nomad hoặc designated activities.' },
      { label: 'COE nếu diện visa dài hạn yêu cầu', required: false },
    ],
    commonMistakes: [
      'Gọi mọi diện mới là “visa mới 2026” dù nhiều diện đã tồn tại từ trước và chỉ được cập nhật lại trên trang hướng dẫn.',
      'Nhầm eVISA du lịch với mọi loại visa ngắn hạn khác.',
      'Nghe quảng cáo “Digital Nomad là sang Nhật làm gì cũng được” trong khi phạm vi hoạt động phụ thuộc đúng diện được cấp.',
      'Không phân biệt “status of residence” với “visa sticker/eVISA”.',
      'Nhầm bảo lãnh sống lâu dài với thăm thân ngắn hạn chỉ vì đều có người nhà ở Nhật.',
    ],
    faq: [
      {
        question: '2026 có visa nào hoàn toàn mới cho mọi người không?',
        answer: 'Không nên hiểu theo kiểu đó. Tính đến ngày 11/04/2026, MOFA đang liệt kê nổi bật các diện như Special Highly Skilled Professional (J-Skip), Designated Activities (Future Creation Individual - J-Find), Digital Nomad và Start-up. Đây là các diện có điều kiện rất khác nhau, không phải ai cũng dùng được.',
      },
      {
        question: 'Digital Nomad có phải visa du lịch không?',
        answer: 'Không. Trên trang Work or Long-term stay của MOFA ngày 22/01/2026, Digital Nomad nằm trong nhóm Designated Activities, khác với short-term tourism visa. Trang visa riêng của MOFA cũng nêu thời gian lưu trú 6 tháng và không gia hạn.',
      },
      {
        question: 'eVISA có dùng cho thăm thân không?',
        answer: 'Không. MOFA FAQ nêu rõ hiện JAPAN eVISA chỉ dùng cho single-entry short-term stay vì mục đích tourism.',
      },
      {
        question: 'J-Find thực chất là gì?',
        answer: 'Trên website MOFA, J-Find là cách gọi phổ biến của diện Designated Activities (Future Creation Individual, Spouse or Child of Future Creation Individual). Đây không phải work visa phổ thông; nó nhắm tới người tốt nghiệp gần đây từ trường đủ điều kiện, muốn sang Nhật để tìm việc, khởi nghiệp hoặc làm hoạt động có thù lao trong phạm vi diện được cấp.',
      },
      {
        question: 'Muốn phân biệt nhanh nên nhìn vào đâu trước?',
        answer: 'Hãy nhìn 3 điểm: mục đích chuyến đi, thời gian ở Nhật và có ý định sống cùng/làm việc hay không. Nếu là sống cùng gia đình lâu dài, nghĩ tới COE và 家族滞在; nếu chỉ sang vài ngày hoặc vài tuần thăm thân thì là 短期滞在; nếu là du lịch trong phạm vi eVISA thì chỉ là tourism ngắn hạn.',
      },
      {
        question: 'Digital Nomad visa cần điều kiện gì và có dành cho người Việt không?',
        answer: 'Điều kiện chính: thu nhập năm từ **¥10,000,000 (10 triệu yên)** trở lên từ nguồn ngoài Nhật Bản, bảo hiểm y tế/tai nạn tối thiểu ¥10M, và hộ chiếu từ một trong **50+ quốc gia** được chỉ định. Hiện **Việt Nam không nằm trong danh sách** này, nên người mang hộ chiếu Việt Nam chưa đủ điều kiện. Visa áp dụng từ tháng 3/2024, thời hạn 6 tháng, không gia hạn, không cho phép làm việc cho công ty Nhật.',
      },
    ],
    counterPhrases: [
      {
        jp: 'この在留資格の条件を教えてください。',
        romaji: 'Kono zairyuu shikaku no jouken o oshiete kudasai.',
        vn: 'Cho tôi biết điều kiện của tư cách lưu trú này.',
        note: 'Hỏi MOFA / Đại sứ quán / ISA về điều kiện cụ thể trước khi quyết định nộp.',
      },
      {
        jp: 'ベトナム国籍でもこのビザを申請できますか。',
        romaji: 'Betonamu kokuseki demo kono biza o shinsei dekimasu ka.',
        vn: 'Người mang quốc tịch Việt Nam có nộp được visa này không?',
        note: 'Đặc biệt cho Digital Nomad — Việt Nam hiện không trong danh sách 50+ quốc tịch áp dụng (kiểm tra MOFA mới nhất).',
      },
      {
        jp: '審査期間と費用はどのくらいですか。',
        romaji: 'Shinsa kikan to hiyou wa dono kurai desu ka.',
        vn: 'Thời gian xét và chi phí khoảng bao nhiêu?',
        note: 'Thay đổi theo diện + theo cục — hỏi cụ thể.',
      },
      {
        jp: '行政書士の紹介はできますか。',
        romaji: 'Gyousei shoshi no shoukai wa dekimasu ka.',
        vn: 'Có thể giới thiệu 行政書士 không?',
        note: 'Liên hệ 日本行政書士会連合会 hoặc 行政書士会 từng tỉnh.',
      },
    ],
    keyTerms: [
      {
        term: 'J-Skip',
        reading: 'ジェイ・スキップ',
        meaningVi: 'Special Highly Skilled Professional (特別高度人材)',
        noteVi: 'Tên thông dụng của diện 特別高度人材 (mở rộng của Highly Skilled Professional thường). Điều kiện: học vấn cao + lương cao (~¥20M+/năm tham khảo, MOFA xác nhận). Cấp 5 năm + path nhanh tới vĩnh trú. KHÔNG phải "visa siêu dễ" — chỉ phù hợp với người có hồ sơ rất mạnh. Phải có COE.',
      },
      {
        term: 'J-Find',
        reading: 'ジェイ・ファインド',
        meaningVi: 'Future Creation Individual (未来創造人材)',
        noteVi: 'Diện Designated Activities cho người mới tốt nghiệp từ trường được liệt kê trong 5 năm gần. Cho phép sang Nhật để tìm việc / khởi nghiệp / hoạt động có thù lao trong phạm vi cho phép. Cần ≥18 tuổi + tiết kiệm cá nhân (mốc tham khảo ~¥200,000). Vợ/chồng/con có thể đi kèm với diện riêng. Không phải work visa thông thường — phạm vi hoạt động hạn chế.',
      },
      {
        term: 'Digital Nomad',
        reading: 'デジタルノマド',
        meaningVi: 'visa làm việc từ xa (Designated Activities)',
        noteVi: 'Diện 特定活動 dành cho người làm remote cho công ty NGOÀI Nhật. Thời hạn 6 tháng, KHÔNG gia hạn được. Điều kiện: quốc tịch trong ~50+ nước chỉ định (Việt Nam HIỆN không trong danh sách 2026-05), thu nhập ¥10M+/năm, bảo hiểm y tế/tai nạn ¥10M+. KHÔNG được làm cho công ty Nhật. KHÔNG phải tourism — khác eVISA.',
      },
      {
        term: 'Start-up',
        reading: 'スタートアップ',
        meaningVi: 'visa khởi nghiệp (đi qua chương trình municipality)',
        noteVi: 'Cấp cho entrepreneur được municipality (市 / 都道府県) ở Nhật hỗ trợ qua chương trình khởi nghiệp. KHÔNG phải "tự đăng ký" — phải nằm trong danh sách chương trình của municipality cụ thể (vd Tokyo, Fukuoka, Kobe có chương trình riêng). Vợ/chồng/con có thể đi kèm. Cần COE.',
      },
      {
        term: 'JAPAN eVISA',
        reading: 'ジャパン・イービザ',
        meaningVi: 'visa điện tử (chỉ cho tourism ngắn hạn)',
        noteVi: 'Hệ thống visa điện tử của MOFA. Hiện CHỈ áp dụng cho: single-entry + short-term stay + mục đích tourism + một số quốc tịch / khu vực. Người Việt: hiện có eVISA tourism 15 ngày (kiểm tra MOFA mới nhất). KHÔNG dùng được cho thăm thân / công việc / học / dài hạn — phải xin visa giấy truyền thống.',
      },
      {
        term: 'Designated Activities',
        reading: '指定活動',
        meaningVi: 'tư cách lưu trú "hoạt động đặc biệt" (特定活動)',
        noteVi: 'Tư cách linh hoạt do Nyukan cấp cho các trường hợp không khớp khuôn mẫu thông thường. Nhiều "loại visa mới 2026" thực ra là 特定活動 với mục đích cụ thể (J-Find, Digital Nomad, medical, một số trường hợp đặc biệt khác). Mỗi loại có điều kiện riêng — phải xem MOFA / ISA cho từng diện cụ thể.',
      },
      {
        term: 'COE',
        reading: 'シーオーイー',
        meaningVi: '在留資格認定証明書 (giấy xác nhận đủ điều kiện cấp tư cách lưu trú)',
        noteVi: 'Tài liệu do ISA cấp khi sponsor / công ty / municipality / cá nhân ở Nhật xin trước. Có COE thì xin visa sticker tại MOFA Đại sứ quán/Lãnh sự dễ + nhanh hơn nhiều. Hết hạn 3 tháng (gia hạn 6 tháng tạm thời theo chính sách hiện hành). Hồ sơ J-Skip / Start-up / work visa / 家族滞在 thường cần COE.',
      },
      {
        term: 'visa sticker',
        reading: 'ビザ・ステッカー',
        meaningVi: 'visa dán lên hộ chiếu (do MOFA cấp tại Đại sứ quán)',
        noteVi: 'KHÁC với 在留資格 (status of residence). Visa sticker chỉ là "vé để nhập cảnh" — khi vào Nhật, ISA cấp 在留カード với 在留資格 thực tế. eVISA là phiên bản điện tử thay sticker cho diện tourism + một số quốc tịch.',
      },
    ],
    officialLinks: [
      { label: 'Work or Long-term stay — MOFA (2026-01-22)', url: 'https://www.mofa.go.jp/j_info/visit/visa/long/index.html' },
      { label: 'Visas and Landing Permission — MOFA', url: 'https://www.mofa.go.jp/j_info/visit/visa/system/index.html' },
      { label: 'Special Highly Skilled Professional / Highly Skilled Professional — MOFA', url: 'https://www.mofa.go.jp/j_info/visit/visa/long/visa16.html' },
      { label: 'Future Creation Individual (J-Find) — MOFA', url: 'https://www.mofa.go.jp/ca/fna/page22e_001037.html' },
      { label: 'Digital Nomad — MOFA', url: 'https://www.mofa.go.jp/ca/fna/pagewe_000001_00046.html' },
      { label: 'Start-up — MOFA', url: 'https://www.mofa.go.jp/ca/fna/page22e_000873.html' },
      { label: 'JAPAN eVISA — MOFA', url: 'https://www.mofa.go.jp/j_info/visit/visa/visaonline.html' },
      { label: 'FAQ about JAPAN eVISA — MOFA', url: 'https://www.mofa.go.jp/j_info/visit/visa/page22e_000999.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'So sánh nhanh: gia đình dài hạn / thăm thân / du lịch / eVISA',
        description: 'Nếu đang rối giữa nhiều khái niệm, hãy so theo 4 câu hỏi: sang để sống cùng hay chỉ sang thăm, ở ngắn hay dài, có cần COE không, và có được dùng eVISA không.',
        documents: [
          'Sống lâu dài với vợ/chồng/con tại Nhật: thường đi theo hướng 家族滞在, xin COE trước ở Nhật rồi xin visa ở nước ngoài.',
          'Thăm thân ngắn hạn: thuộc 短期滞在, không phải visa sống lâu dài và không dùng để đi làm.',
          'Du lịch ngắn hạn: cũng thuộc short-term stay, nhưng mục đích là tourism chứ không phải thăm thân.',
          'eVISA: hiện MOFA nêu rõ chỉ dùng cho single-entry short-term stay vì mục đích tourism trong phạm vi quốc gia/khu vực được áp dụng; không nên nhầm với visa thăm thân hay diện sống lâu dài.',
        ],
        tip: 'Nếu chỉ cần một câu để nhớ: “ở cùng lâu dài” thì nghĩ COE/家族滞在; “sang thăm” thì nghĩ 短期滞在; “du lịch online” mới nghĩ tới eVISA nếu đủ điều kiện.',
      },
      {
        step: 2,
        title: 'J-Skip: diện tài năng cao đặc biệt',
        description: 'Trên trang visa của MOFA, J-Skip tương ứng với Special Highly Skilled Professional. Đây là nhóm long-term stay cho người có nền tảng học vấn, kinh nghiệm và thu nhập ở mức rất cao; hồ sơ thực tế thường đi cùng COE.',
        documents: [
          'Bằng cấp',
          'Kinh nghiệm làm việc',
          'Chứng minh thu nhập/năng lực nếu diện hồ sơ yêu cầu',
          'COE khi nộp visa',
        ],
        tip: 'MOFA ghi rõ hồ sơ Highly Skilled Professional yêu cầu COE. “J-Skip” chỉ là tên gọi phổ biến; khi làm hồ sơ nên bám tên chính thức trên website và mẫu giấy tờ.',
      },
      {
        step: 3,
        title: 'J-Find: Future Creation Individual',
        description: 'MOFA xếp J-Find vào diện Designated Activities cho Future Creation Individual và vợ/chồng/con đi kèm. Theo trang hướng dẫn visa riêng, người nộp phải từ 18 tuổi trở lên, đã tốt nghiệp từ trường đủ điều kiện trong 5 năm gần đây và có khoản tiết kiệm cá nhân đủ sống tại Nhật.',
        documents: [
          'Hộ chiếu',
          'Giấy tờ học vấn/chứng minh đã tốt nghiệp',
          'CV',
          'Mô tả hoạt động dự định tại Nhật',
          'Giấy tờ chứng minh tiết kiệm cá nhân',
        ],
        tip: 'Trang MOFA của J-Find nêu mốc tham chiếu khoảng 200,000 yên tiền tiết kiệm cá nhân và cho phép gia hạn trong phạm vi điều kiện của diện này. Đây không phải con đường thay thế chung cho mọi work visa.',
      },
      {
        step: 4,
        title: 'Digital Nomad',
        description: 'Trang visa riêng của MOFA nêu Digital Nomad dành cho người muốn làm việc từ xa tại Nhật trong thời gian không quá 6 tháng; vợ/chồng hoặc con đi kèm có diện riêng đi theo. Đây là Designated Activities, không phải tourism.',
        documents: [
          'Giấy tờ giải thích hoạt động và thời gian lưu trú',
          'Chứng minh thu nhập năm từ 10 triệu yên trở lên',
          'Bảo hiểm y tế/tai nạn với mức chi trả điều trị từ 10 triệu yên trở lên',
          'COE nếu chọn nộp kèm',
        ],
        tip: 'MOFA ghi rõ thời gian lưu trú là 6 tháng và không gia hạn. Vì vậy đây không phải diện để sang Nhật lâu dài rồi chuyển việc tùy ý.',
      },
      {
        step: 5,
        title: 'Start-up visa',
        description: 'MOFA hiện ghi Start-up dành cho entrepreneur được municipality ở Nhật hỗ trợ, cùng vợ/chồng hoặc con trong phạm vi áp dụng. Hồ sơ của entrepreneur về nguyên tắc phải đi với COE.',
        documents: [
          'COE',
          'Kế hoạch khởi nghiệp',
          'Giấy tờ hỗ trợ từ municipality/chương trình liên quan',
        ],
        tip: 'Không phải chỉ cần “muốn mở công ty” là vào Start-up visa. Điểm cốt lõi là phải nằm trong chương trình hỗ trợ của địa phương phù hợp.',
      },
      {
        step: 6,
        title: 'eVISA và giới hạn của nó',
        description: 'MOFA ghi rõ tính đến 15/12/2025 và áp dụng trong năm 2026, JAPAN eVISA chỉ dành cho single-entry short-term stay vì mục đích tourism trong phạm vi nước/khu vực được phép; với người quốc tịch Việt Nam cư trú tại Việt Nam, eVISA du lịch hiện có thời gian lưu trú 15 ngày.',
        documents: [
          'Hộ chiếu hợp lệ',
          'Điều kiện cư trú và quốc tịch phù hợp hệ thống',
        ],
        tip: 'Nếu đi vì thăm thân, công việc, học tập, làm việc hoặc mục đích dài hạn, đừng nhầm rằng eVISA là đường đi phù hợp.',
      },
    ],
  };

export default visaHighlights2026;
