import type { AdminGuide } from '../../../../types/content';

const visaEmergencyMedicalDisasterExtension: AdminGuide = {
    id: 'visa-emergency-medical-disaster-extension',
    category: 'immigration',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Visa hết hạn trong lúc nhập viện / thảm họa — cách xin giãn thời hạn',
    titleJp: '入院中や災害時の在留期間延長手続き',
    icon: 'medical',
    color: '#27AE60',
    description: 'Thủ tục mở rộng visa khi bạn nhập viện hoặc gặp thảm họa tự nhiên khiến không thể gia hạn đúng hạn. Có 2 hướng chính tùy thời gian điều trị (< 90 ngày: gia hạn 短期滞在 / > 90 ngày: đổi sang 特定活動 medical). Sau thảm họa lớn, 出入国在留管理庁 thường công bố biện pháp đặc biệt áp dụng cho khu vực bị ảnh hưởng — nên xác nhận thông tin mới nhất tại Nyukan.',
    searchKeywords: [
      'visa het han trong vien',
      'visa het han nhap vien',
      'visa medical stay',
      'iryou taizai',
      'visa y te dai han',
      'visa khan cap dieu tri',
      'visa thien tai',
      'visa dong dat',
      'visa lu lut',
      'gia han khi om',
      'gia han khi tham hoa',
      'dai han 90 ngay',
      'extension short-term',
      'doi sang tokutei katsudo y te',
      'medical designated activity',
      'risai shoumeisho',
      '医療滞在',
      '医療滞在ビザ',
      'いりょうたいざい',
      '入院中',
      'にゅういんちゅう',
      '災害時',
      'さいがいじ',
      '特定活動',
      '在留期間延長',
      '短期滞在',
      '診断書',
      '罹災証明書',
      '災害時の出入国管理上の特別措置',
      '国際科',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Gia hạn 短期滞在 và đổi sang 特定活動 (medical) do 出入国在留管理庁 xử lý toàn quốc theo 入管法 §21 và hướng dẫn về 特定活動. Sau thảm họa lớn (震災, 風水害), Nyukan thường ban hành biện pháp đặc biệt (特別措置) áp dụng cho khu vực bị ảnh hưởng — phạm vi và thời gian tùy quyết định của 法務省 / Nyukan tại thời điểm. KHÔNG nhầm 特定活動 (medical) với 在留特別許可 (do Bộ trưởng Tư pháp cấp riêng).',
      sourceVerifiedAt: '2026-05-17',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Điều trị dự kiến > 90 ngày + visa hiện tại sắp hết hạn — cần đổi sang 特定活動 (medical) thay vì gia hạn thông thường. Tham khảo bệnh viện có 国際科 hoặc luật sư.',
        'Bệnh viện KHÔNG có 国際科 và không quen làm hỗ trợ visa — liên hệ Nyukan trực tiếp hoặc 行政書士 chuyên visa y tế.',
        'Đang trên 短期滞在 (visa du lịch 90 ngày) nhập viện — KHÔNG được gia hạn 短期滞在 quá 90 ngày + 90 (tổng 180); sau đó phải đổi tư cách hoặc xin chuyển bệnh viện.',
        'Khu vực bạn sống vừa có thảm họa lớn (đại địa chấn, bão lớn) — kiểm tra trang Nyukan xem có 特別措置 không, KHÔNG tự kết luận.',
        'Visa đã hết hạn vì nhập viện đột ngột không kịp xử lý — đến Nyukan tự thú + giải thích y tế ngay. KHÔNG đợi.',
        'Có nguy cơ bị 不法残留 vì điều trị dài + thiếu giấy tờ y tế — liên hệ luật sư / 法テラス (0570-078374) để bảo vệ quyền lưu trú.',
      ],
    },
    quickAction: {
      deadline: 'Khi phát hiện sẽ ở viện kéo dài → liên hệ Nyukan / bệnh viện 国際科 NGAY, KHÔNG đợi sát hạn. Đối với thảm họa: Nyukan thường công bố hạn ân hạn 30-60 ngày sau ngày phát sinh — nhưng vẫn nên xác nhận sớm.',
      office:
        'Nyukan có thẩm quyền theo nơi cư trú; bệnh viện 国際科 (international section) — nhiều bệnh viện lớn có cán bộ hỗ trợ visa y tế. Số tư vấn 出入国在留管理庁: 0570-013904 (在留資格 inquiry). Hỗ trợ pháp lý miễn phí: 法テラス 0570-078374.',
      doNow: [
        'Báo lễ tân / y tá ngay khi nhập viện: "私は日本のビザを持っています。在留期限はXX月XX日です。" — hỏi xem bệnh viện có 国際科 hoặc cán bộ hỗ trợ visa không.',
        'Yêu cầu bác sĩ viết 診断書 (giấy chẩn đoán) ghi: ngày nhập viện, chẩn đoán, ngày ra viện dự kiến, cần điều trị tiếp tục. Có dấu bệnh viện + chữ ký bác sĩ.',
        'Quyết định hướng xử lý: < 90 ngày → xin gia hạn 短期滞在 / 在留期間更新; > 90 ngày → đổi sang 特定活動 (medical).',
        'Nhờ người nhà / bạn ở Nhật nộp giúp Nyukan nếu bạn không tự đi được. Cần ủy quyền (代理申請).',
        'Đối với thảm họa: theo dõi trang Nyukan + 内閣府防災 xem có 特別措置 không; chuẩn bị 罹災証明書 từ 市役所 nếu có.',
        'Lưu lại MỌI giấy tờ y tế + hóa đơn — cần cho cả Nyukan và bảo hiểm sau này.',
      ],
      bring: [
        'Hộ chiếu + 在留カード',
        '診断書 (bằng tiếng Nhật, có dấu bệnh viện)',
        'Tham khảo: 入院証明書 hoặc 治療継続証明書 (cho điều trị dài)',
        'Chứng minh tài chính (sao kê ngân hàng — cần cho cả 短期滞在 extension và 特定活動)',
        'Đối với thảm họa: 罹災証明書 từ 市役所 (nếu có)',
        '保険証 / 公的医療保険資格確認書 nếu đang dùng bảo hiểm Nhật',
        'Ảnh 4cm × 3cm (cần cho 特定活動 đổi tư cách + thẻ mới)',
      ],
      ifLate:
        'Visa đã hết hạn (不法残留) vì y tế khẩn cấp → KHÔNG hoảng. Đến Nyukan gần nhất tự thú + mang 診断書 + giấy nhập viện. Tự thú do lý do khách quan (y tế / thảm họa) thường được xét nhẹ hơn nhiều — có thể được cấp 特定活動 đặc biệt. KHÔNG nên trốn — bị truy ra = trục xuất + cấm tái nhập 5-10 năm.',
      officialSourceLabels: [
        'ISA — Medical Stay Visa (医療滞在)',
        'Ministry of Foreign Affairs — Medical Stay Visa',
        'ISA — Designated Activities for Medical Stay',
      ],
    },
    whoIsThisFor: [
      'Người nhập viện đột ngột, sắp phẫu thuật và visa sắp hết hạn.',
      'Người sống ở vùng thảm họa (động đất, lũ lụt) cần chuẩn bị khi visa hết hạn.',
      'Người muốn biết quyền lợi y tế tại Nhật khi trên visa ngắn hạn.',
    ],
    whenToDo: [
      'Nếu nhập viện: hỏi bộ phòng khám tại bệnh viện nếu họ có liên hệ ISA hoặc có thể hỗ trợ.',
      'Nếu thời gian điều trị < 90 ngày: có thể extend short-term stay tại ISA.',
      'Nếu thời gian điều trị > 90 ngày: phải đổi sang 特定活動 (medical designated activity).',
      'Không nên chờ sát hạn visa — hành động sớm khi phát hiện sẽ nhập viện lâu.',
    ],
    whereToDo: [
      'Bệnh viện (hospital) có bộ phòng khám quốc tế — họ có liên hệ ISA hoặc địa chỉ ISA gần nhất.',
      'ISA — cục công an nhập cảnh. Nộp trực tiếp hoặc qua bệnh viện nếu bệnh viện hỗ trợ.',
      'Gia đình bạn tại Nhật cũng có thể hỗ trợ nộp tài liệu nếu bạn nằm bệnh.',
    ],
    estimatedTime: '< 90 ngày: 1-2 tuần. > 90 ngày: 2-4 tuần để đổi sang 特定活動. Thời gian có thể kéo dài hơn nếu bệnh viện cần cập nhật hồ sơ.',
    commonMistakes: [
      'Không hỏi bệnh viện — chờ đợi quá lâu cho đến khi gần hết hạn visa.',
      'Không hiểu sự khác biệt giữa extension < 90 ngày vs đổi tư cách > 90 ngày.',
      'Quên khẩn cấp — nên làm càng sớm càng tốt.',
      'Không chuẩn bị giấy chứng minh từ bác sĩ — ISA cần xác nhận ngày nhập viện, ngày ra viện dự kiến, loại bệnh.',
    ],
    faq: [
      {
        question: 'Nếu tôi trên short-term stay visa (90 ngày) và nhập viện, sao?',
        answer: 'Short-term stay (短期滞在) không thể extend, phải đổi sang loại visa khác. Nếu điều trị < 90 ngày nữa, bạn có thể apply extension tạm thời (short-term extension). Nếu > 90 ngày, phải đổi sang 特定活動 (medical stay).',
      },
      {
        question: 'Bệnh viện có thể hỗ trợ làm đơn không?',
        answer: 'Có. Bệnh viện lớn ở Nhật (nhất là những nơi có 国際科 / phòng quốc tế) có nhân viên hỗ trợ visa. Họ có thể: (1) viết giấy xác nhận từ bác sĩ, (2) cho địa chỉ ISA gần nhất, (3) thậm chí hỗ trợ nộp hồ sơ nếu bạn nằm bệnh. Hãy hỏi ngay khi nhập viện.',
      },
      {
        question: 'Bác sĩ phải viết gì trong giấy chứng minh?',
        answer: 'ISA cần: (1) Ngày nhập viện, (2) Loại bệnh/chẩn đoán (nên viết tiếng Anh hoặc Nhật), (3) Ngày ra viện dự kiến (estimated discharge date), (4) Xác nhận rằng bạn cần nằm bệnh liên tục/trị liệu phục hồi. Giấy phải có dấu bệnh viện và chữ ký bác sĩ.',
      },
      {
        question: '在留特別許可 (special permission) là gì?',
        answer: '在留特別許可 là phép ở lại đặc biệt khi bạn cần điều trị > 90 ngày. Thay vì bị từ chối, ISA có thể cấp status \"特定活動\" (designated activities) cho y tế với khoảng thời gian gia hạn tuỳ bệnh (thường 6-12 tháng). Đây không phải \"appeal\" mà là một tùy chọn visa chính thức.',
      },
    ],
    counterPhrases: [
      {
        jp: '私は日本のビザを持っています。在留期限は〇月〇日です。ビザのサポートが必要です。',
        romaji: 'Watashi wa Nihon no biza o motte imasu. Zairyuu kigen wa marutsuki maruka desu. Biza no sapooto ga hitsuyou desu.',
        vn: 'Tôi có visa Nhật. Hạn lưu trú là ngày 〇/〇. Tôi cần hỗ trợ visa.',
        note: 'Câu mở đầu khi báo lễ tân / y tá lúc nhập viện. Thay 〇月〇日 bằng ngày cụ thể.',
      },
      {
        jp: '国際科または外国人サポートの担当はありますか。',
        romaji: 'Kokusaika mata wa gaikokujin sapooto no tantou wa arimasu ka.',
        vn: 'Bệnh viện có Phòng quốc tế hoặc cán bộ hỗ trợ người nước ngoài không?',
        note: 'Bệnh viện lớn ở Tokyo / Osaka / Yokohama thường có. Bệnh viện địa phương có thể không — vẫn nên hỏi.',
      },
      {
        jp: '入院期間が〇か月かかる予定です。在留期間延長か特定活動への変更について相談したいです。',
        romaji: 'Nyuuin kikan ga maru-kagetsu kakaru yotei desu. Zairyuu kikan enchou ka tokutei katsudou e no henkou ni tsuite soudan shitai desu.',
        vn: 'Dự kiến nằm viện 〇 tháng. Tôi muốn tư vấn về gia hạn lưu trú hoặc đổi sang 特定活動.',
        note: 'Câu hỏi cho Nyukan. Nói thẳng thời gian dự kiến để Nyukan tư vấn đúng hướng.',
      },
      {
        jp: '診断書を書いていただけますか。在留期間延長の申請に必要です。',
        romaji: 'Shindansho o kaite itadakemasu ka. Zairyuu kikan enchou no shinsei ni hitsuyou desu.',
        vn: 'Bác sĩ viết giúp tôi giấy chẩn đoán được không? Tôi cần để xin gia hạn lưu trú.',
        note: 'Yêu cầu khi gặp bác sĩ điều trị. 診断書 cần ghi rõ ngày + chẩn đoán + dự kiến ngày ra viện.',
      },
      {
        jp: '家族にビザの申請を代理でしてもらえますか。委任状はどう書きますか。',
        romaji: 'Kazoku ni biza no shinsei o dairi de shite moraemasu ka. Inin-jou wa dou kakimasu ka.',
        vn: 'Người nhà có nộp đơn visa thay tôi được không? Giấy ủy quyền viết thế nào?',
        note: 'Cần khi nằm liệt giường. 代理申請 (ủy quyền) có form mẫu — Nyukan hướng dẫn.',
      },
      {
        jp: '災害特別措置の対象地域に住んでいます。在留期間はどうなりますか。',
        romaji: 'Saigai tokubetsu sochi no taishou chiiki ni sunde imasu. Zairyuu kikan wa dou narimasu ka.',
        vn: 'Tôi sống trong khu vực được áp dụng biện pháp đặc biệt sau thảm họa. Lưu trú sẽ ra sao?',
        note: 'Dùng sau khi xác nhận khu vực mình ở thuộc 特別措置. Nyukan thường có thông báo cụ thể trên website.',
      },
    ],
    keyTerms: [
      {
        term: '特定活動 (医療)',
        reading: 'とくていかつどう (いりょう)',
        meaningVi: 'visa Hoạt động Đặc định cho y tế (cho điều trị > 90 ngày)',
        noteVi: 'Đổi sang tư cách này khi điều trị dài. Thường cấp 6-12 tháng, có thể gia hạn theo nhu cầu y tế. CẦN: 診断書 + 治療継続証明書 + chứng minh tài chính + có người chăm sóc tại Nhật. Người chăm (付添人) cũng có thể xin 特定活動 riêng. KHÁC 医療滞在ビザ (cho người sang Nhật vì y tế từ đầu).',
      },
      {
        term: '医療滞在ビザ',
        reading: 'いりょうたいざいビザ',
        meaningVi: 'visa Lưu trú Y tế (cho người sang Nhật vì điều trị từ đầu)',
        noteVi: 'KHÁC 特定活動 (医療). 医療滞在ビザ dành cho người ở nước ngoài sang Nhật điều trị — xin tại Đại sứ quán + bệnh viện được đăng ký với MOFA. Người đang ở Nhật nhập viện đột ngột thì dùng 特定活動 (医療), không phải 医療滞在ビザ.',
      },
      {
        term: '短期滞在期間延長',
        reading: 'たんきたいざいきかんえんちょう',
        meaningVi: 'gia hạn 短期滞在 (du lịch 90 ngày)',
        noteVi: 'Áp dụng khi đang trên 短期滞在 + cần ở thêm vì y tế. Tổng tối đa thường KHÔNG quá 6 tháng (90 + 90 ngày). Sau đó phải đổi tư cách. CẦN lý do hợp lý (y tế / thảm họa / công việc khẩn cấp) — không tự động được.',
      },
      {
        term: '診断書',
        reading: 'しんだんしょ',
        meaningVi: 'giấy chẩn đoán (do bác sĩ viết, có dấu bệnh viện)',
        noteVi: 'Tài liệu BẮT BUỘC cho mọi extension liên quan y tế. Cần ghi: ngày nhập viện, chẩn đoán (tên bệnh), ngày ra viện dự kiến, lý do cần điều trị tiếp tục. Phí tham khảo: 3,000-10,000 yên/bản (không bảo hiểm cover). Yêu cầu bác sĩ viết tiếng Nhật — Nyukan không chấp nhận tiếng Anh thuần.',
      },
      {
        term: '罹災証明書',
        reading: 'りさいしょうめいしょ',
        meaningVi: 'giấy chứng nhận bị nạn (sau thảm họa)',
        noteVi: 'Lấy tại 市役所 sau thẩm định thiệt hại (1-2 tuần sau thảm họa). Phân cấp: 全壊 / 大規模半壊 / 半壊 / 一部損壊. Nyukan có thể yêu cầu cho 特別措置. Cũng dùng cho miễn thuế, hỗ trợ tài chính, hoãn trả thuê nhà.',
      },
      {
        term: '災害時特別措置',
        reading: 'さいがいじとくべつそち',
        meaningVi: 'biện pháp đặc biệt của Nyukan sau thảm họa',
        noteVi: 'Sau thảm họa lớn (đại địa chấn, bão lụt), Nyukan thường ban hành 特別措置: hạn ân hạn lưu trú 30-60 ngày, miễn phí gia hạn, cấp 特定活動 tạm thời. Phạm vi + thời gian khác nhau từng thảm họa — KHÔNG tự kết luận, xác nhận tại trang Nyukan hoặc gọi 0570-013904.',
      },
      {
        term: '在留特別許可',
        reading: 'ざいりゅうとくべつきょか',
        meaningVi: 'giấy phép lưu trú đặc biệt (do Bộ trưởng Tư pháp cấp)',
        noteVi: 'CHỈ áp dụng khi đã rơi vào tình trạng bị xét trục xuất. KHÁC 特定活動 (medical) thông thường. Phép ngoại lệ hiếm — không tự xin được, Bộ trưởng Tư pháp quyết định case-by-case. Người điều trị dài + visa hết hạn KHÔNG nhất thiết đi đến mức này nếu xử lý sớm.',
      },
      {
        term: '代理申請',
        reading: 'だいりしんせい',
        meaningVi: 'nộp đơn ủy quyền (qua người khác)',
        noteVi: 'Khi nằm liệt giường / không tự đi Nyukan được — người thân hoặc 行政書士 có thể nộp giúp. Cần 委任状 (giấy ủy quyền) ký tay + bản sao CMND người được ủy quyền. Bệnh viện 国際科 cũng có thể hỗ trợ trong một số trường hợp.',
      },
    ],
    officialLinks: [
      { label: 'ISA — Medical Stay Visa (医療滞在)', url: 'https://www.moj.go.jp/isa/applications/status/medicalservices.html' },
      { label: 'Ministry of Foreign Affairs — Medical Stay Visa', url: 'https://www.mofa.go.jp/mofaj/toko/visa/medical/index.html' },
      { label: 'ISA — Designated Activities for Medical Stay', url: 'https://www.moj.go.jp/isa/applications/status/designatedactivities06.html' },
      { label: '在留期間更新許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-3.html' },
      { label: '在留資格変更許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-2.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Nhập viện — hỏi bệnh viện ngay về visa',
        description: 'Khi nhập viện, hãy thông báo cho nhân viên lễ tân hoặc y tá:\n\n**\"Tôi trên visa Nhật Bản. Visa sẽ hết hạn [ngày]. Tôi cần hỗ trợ visa.\"** (\"私は日本のビザを持っています。ビザが [ngày] に満期になります。ビザのサポートが必要です。\")\n\nBệnh viện sẽ:\n- Nếu có 国際科 (phòng quốc tế): họ có full support\n- Nếu không: sẽ cho số điện thoại/địa chỉ ISA gần nhất hoặc hướng dẫn liên hệ ISA\n\nBệnh viện **không thể** \"giúp\" hành chính ISA, nhưng họ có thể viết giấy chứng minh y tế cần thiết.',
        documents: ['Hộ chiếu hoặc thẻ cư trú để bệnh viện ghi lại'],
        tip: 'Không chờ sát hạn visa — hỏi ngay khi vào viện. Bệnh viện sẽ biết quá trình và có thể hỗ trợ document.',
      },
      {
        step: 2,
        title: 'Xác định thời gian điều trị dự kiến',
        description: 'Hỏi bác sĩ/y tá:\n\n**\"Tôi sẽ nằm viện khoảng bao lâu? Ngày ra viện dự kiến khi nào?\"**\n\nBác sĩ sẽ cho ước tính:\n- **< 90 ngày nữa:** Extension short-term (可能性は低いが、可能な場合もある)\n- **> 90 ngày nữa:** Phải đổi sang 特定活動 (medical stay) — ISA sẽ cấp status mới\n\n**Lưu ý:** Ước tính có thể thay đổi — hỏi lại khi tình trạng sức khỏe thay đổi.',
        documents: ['Phác đồ điều trị hoặc ghi chú y tế'],
        tip: 'Báo cho gia đình hoặc bạn bè tại Nhật biết — họ có thể hỗ trợ nộp hồ sơ nếu bạn nằm bệnh nặng.',
      },
      {
        step: 3,
        title: 'Nộp đơn xin extension / đổi tư cách',
        description: '**Trường hợp 1: Điều trị < 90 ngày (Short-term extension)**\n\nBênh viện hoặc bạn nộp tại ISA:\n- Đơn xin extension (短期滞在期間延長許可申請)\n- Giấy chứng minh từ bác sĩ (diagnosis letter)\n- Hộ chiếu + thẻ cư trú\n- Chứng minh tài chính để sống ở Nhật trong thời gian điều trị\n\nThời gian phê duyệt: 1-2 tuần\n\n---\n\n**Trường hợp 2: Điều trị > 90 ngày (Đổi sang 特定活動 — Medical Designated Activity)**\n\nQuá trình phức tạp hơn:\n- Bệnh viện chuẩn bị giấy chứng minh y tế chi tiết\n- Bạn hoặc gia đình nộp 在留資格変更許可申請 (change of status) tại ISA\n- Yêu cầu: Certificate of Eligibility từ ISA kèm giấy y tế\n- ISA sẽ review và cấp thẻ cư trú mới với status 特定活動\n\nThời gian phê duyệt: 2-4 tuần (có thể lâu hơn nếu hồ sơ phức tạp)',
        documents: ['Đơn xin (in từ ISA)', 'Giấy chứng minh từ bác sĩ/bệnh viện', 'Hộ chiếu', 'Thẻ cư trú', 'Chứng minh tài chính'],
        tip: 'Nếu bạn nằm bệnh nặng, gia đình hoặc bạn bè ở Nhật có thể nộp giúp — không nhất thiết phải bạn đi trực tiếp ISA.',
      },
      {
        step: 4,
        title: 'Khi được phê duyệt — chuẩn bị ra viện',
        description: 'Nếu ISA phê duyệt extension/đổi tư cách:\n\n- Nhân viên bệnh viện hoặc ISA sẽ thông báo\n- Bạn sẽ nhận thẻ cư trú mới (nếu đổi tư cách) hoặc giấy xác nhận extension\n- Ngày hết hạn mới sẽ được cập nhật\n\n**Chuẩn bị ra viện:**\n- Bác sĩ sẽ cho toa thuốc, hướng dẫn phục hồi tại nhà\n- Bệnh viện sẽ cho lịch tái khám, tiêm chủng (nếu cần)\n- Thanh toán y tế: kiểm tra xem bảo hiểm y tế của bạn đã cover chưa\n- Thủ tục perks từ chính quyền địa phương (医療費助成 / medical subsidy) nếu có',
        documents: ['Thẻ cư trú mới', 'Giấy ra viện từ bệnh viện', 'Toa thuốc, hướng dẫn phục hồi'],
        tip: 'Lưu lại giấy ra viện và hóa đơn y tế — có thể cần khi nộp thuế hoặc claim bảo hiểm.',
      },
      {
        step: 5,
        title: 'Thảm họa (động đất, lũ lụt) — quyền lợi visa khẩn cấp',
        description: 'Khi thảm họa xảy ra ở Nhật, ISA sẽ tự động cấp **特定活動** (designated activities) cho người nước ngoài bị ảnh hưởng.\n\n**Bạn sẽ được:**\n- Ở lại Nhật mà không phải gia hạn ngay (tự động miễn 30-60 ngày)\n- Cấp status tạm thời 特定活動 nếu cần ở lâu hơn\n- Hỗ trợ từ các trung tâm khẩn cấp (避難所)\n- Bảo hiểm y tế vẫn có hiệu lực cho điều trị thương tích/khẩn cấp\n\n**Không cần làm gì đặc biệt** — ISA sẽ thông báo qua media, hotline, hoặc cục ISA gần nhất.',
        documents: [],
        tip: 'Trong thảm họa, ưu tiên an toàn + sức khỏe trước — visa sẽ được giải quyết sau. Hãy theo hướng dẫn từ chính quyền địa phương và cảnh sát.',
      },
    ],
  };

export default visaEmergencyMedicalDisasterExtension;
