import type { AdminGuide } from '../../../../types/content';

const visaRejectionAppealProcess: AdminGuide = {
    id: 'visa-rejection-appeal-process',
    category: 'immigration',
    lastVerified: '2026-05-17',
    priority: 'normal',
    title: 'Visa bị từ chối và cách kháng cáo / nộp lại',
    titleJp: '在留許可申請が不許可になった場合の対処法',
    icon: 'close-circle',
    color: '#E74C3C',
    description: 'Thủ tục khi visa hoặc 在留資格認定証明書 (COE) bị 不許可. Nhật KHÔNG có process "appeal" chính thức theo nghĩa truyền thống — hướng xử lý phổ biến là sửa hồ sơ + 再申請 (nộp lại). Tỷ lệ kết quả khác nhau theo từng hồ sơ, tư cách và Nyukan — KHÔNG có "công thức đậu". Nên xác nhận thông tin và quy trình mới nhất với Nyukan trước khi nộp lại.',
    searchKeywords: [
      'visa bi tu choi',
      'visa rejected',
      'visa fail',
      'fukyoka',
      'fukyoka shobun',
      'visa khang cao',
      'visa appeal',
      'COE bi tu choi',
      'COE refused',
      'nop lai visa',
      'nop lai don visa',
      're-application visa japan',
      'visa het han vi tu choi',
      'visa fail xu ly',
      '30 ngay chuan bi roi',
      'shukkoku junbi kikan',
      'riyuusho',
      'thu giai trinh',
      'gyousei shoshi',
      'hanh chinh tu phap',
      'gyousei fufuku shinsa',
      'visa thu nhap thap',
      'visa cong viec khong khop',
      '不許可',
      '不許可処分',
      '不許可処分書',
      'ふきょかしょぶん',
      '不許可理由',
      '出国準備期間',
      'しゅっこくじゅんびきかん',
      '再申請',
      '理由書',
      '行政不服審査請求',
      '行政書士',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Quyết định cấp / không cấp tư cách lưu trú là quyền của 出入国在留管理庁 theo 入管法 §22, §22-2, §50. KHÔNG có process "appeal" tương đương tòa án. Có cơ chế 行政不服審査請求 (khiếu nại hành chính, áp 行政不服審査法) nhưng rất hiếm thành công cho visa — chủ yếu xử lý qua 再申請 (nộp lại) với hồ sơ sửa hoặc đổi sang tư cách khác. Sau 不許可, thường được cấp 出国準備期間 (≈30 ngày) để rời Nhật hoặc thử lại.',
      sourceVerifiedAt: '2026-05-17',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        '不許可 lần thứ 2 trở lên với cùng tư cách — có thể vấn đề cơ bản, nên hỏi 行政書士 / luật sư chuyên 入管 thay vì nộp lại theo cảm tính.',
        '不許可 vì lý do liên quan thuế / bảo hiểm / hành chính cũ — cần giải quyết gốc trước khi nộp lại. Tham khảo 法テラス (0570-078374) nếu thu nhập thấp.',
        '不許可 với COE từ ngoài Nhật + người nhà đã chuẩn bị bay — cân nhắc đổi sang 短期滞在 thăm thân hoặc dừng kế hoạch nhập cảnh dài hạn.',
        '不許可 và visa hiện tại sắp hết hạn trong 出国準備期間 — gần như chắc chắn phải rời Nhật. Liên hệ luật sư nếu có hoàn cảnh đặc biệt (có con quốc tịch Nhật, đang điều trị y tế).',
        'Cảm thấy 不許可 không công bằng và muốn 行政不服審査請求 — phải có luật sư hành chính tư vấn trước, cơ hội thắng kiện thấp + tốn thời gian/tiền.',
        'Đang trong 出国準備期間 và muốn thử nộp đơn 在留資格変更 sang tư cách khác — phải nộp TRƯỚC ngày 出国準備 hết hạn. Tham khảo 行政書士.',
      ],
    },
    quickAction: {
      deadline: 'Sau khi nhận 不許可処分書: nếu đang ở Nhật, thường được cấp 出国準備期間 ~30 ngày. Trong khoảng này, phải hoặc (1) rời Nhật, hoặc (2) nộp lại 再申請, hoặc (3) đổi tư cách. KHÔNG đợi đến ngày cuối — chuẩn bị càng sớm càng tốt.',
      office:
        'Nyukan đã xử lý hồ sơ ban đầu (ghi trên 不許可処分書). Số tư vấn 出入国在留管理庁: 0570-013904. 行政書士 chuyên 入管: tìm qua 日本行政書士会連合会. Hỗ trợ pháp lý miễn phí (thu nhập thấp): 法テラス 0570-078374.',
      doNow: [
        'Giữ NGUYÊN 不許可処分書 (không tự ý hủy / bỏ) — đây là tài liệu chính thức cần cho mọi bước tiếp theo.',
        'Đến Nyukan đã xử lý hồ sơ, yêu cầu giải thích lý do cụ thể: "不許可になった理由を詳しく教えていただけますか。" Ghi lại đầy đủ.',
        'Phân tích lý do: thuộc nhóm sửa được (tài chính, giấy tờ, mô tả công việc) hay không sửa được (lịch sử pháp lý, hoạt động không khớp tư cách)?',
        'Nếu sửa được → chuẩn bị 理由書 (thư giải trình) + tài liệu bổ sung giải quyết đúng điểm yếu. KHÔNG chỉ nộp lại bản cũ.',
        'Nếu không sửa được → cân nhắc đổi sang tư cách khác (vd: 技人国 → 特定技能, 留学 → 特定活動 tìm việc) hoặc chuẩn bị rời Nhật.',
        'Trong 出国準備期間: KHÔNG được làm việc (cả với 在留資格 lao động cũ) — chỉ được chuẩn bị rời. Vi phạm = 不法就労.',
      ],
      bring: [
        '不許可処分書 (bản gốc)',
        'Hộ chiếu + 在留カード hiện tại',
        'Toàn bộ hồ sơ đã nộp lần trước (bản sao)',
        'Tài liệu mới giải quyết lý do từ chối (tăng lương, hợp đồng mới, giấy nộp thuế, etc.)',
        '理由書 (thư giải trình bằng tiếng Nhật)',
        'Ảnh thẻ 4×3cm mới (chụp trong 3 tháng)',
      ],
      ifLate:
        '出国準備期間 đã hết và chưa rời Nhật / chưa nộp 再申請 → 不法残留. Đến Nyukan tự thú NGAY + mang lý do hợp lý (y tế, gia đình, hành chính trục trặc). Tự thú thường được xử lý nhẹ hơn so với bị truy ra. KHÔNG trốn — bị bắt = trục xuất + cấm tái nhập 5-10 năm theo 入管法.',
      officialSourceLabels: [
        'ISA — Các loại visa & tư cách lưu trú',
        'ISA — Nếu bị từ chối, cách tìm hiểu chi tiết',
        'Danh sách ISA offices theo khu vực',
      ],
    },
    whoIsThisFor: [
      'Người bị từ chối visa (work, student, spouse, dependent, change of status) và muốn biết cách tiếp theo.',
      'Người muốn hiểu chi tiết lý do bị từ chối trước khi nộp lại.',
      'Người không chắc liệu có thể appeal hay phải nộp lại từ đầu.',
    ],
    whenToDo: [
      'Ngay sau khi nhận thông báo từ chối, hãy liên hệ immigration bureau để hỏi chi tiết lý do.',
      'Không nên nộp lại ngay mà hãy phân tích kỹ vấn đề và chuẩn bị tài liệu bổ sung.',
      'Không có waiting period bắt buộc — có thể nộp lại ngày hôm sau nếu đã sửa được vấn đề.',
    ],
    whereToDo: [
      'Immigration Bureau (ISA / 出入国在留管理庁) — cục công an nhập cảnh có thẩm quyền nơi bạn nộp hồ sơ ban đầu.',
      'Liên hệ để hỏi chi tiết: đương mặt tại quầy hoặc gọi hotline nếu cục có hỗ trợ.',
      'Tương tự như ban đầu nộp tại cùng một cục hoặc trực tuyến nếu áp dụng.',
    ],
    estimatedTime: 'Không có waiting period bắt buộc. Thời gian xét duyệt lần nộp lại phụ thuộc hồ sơ và khu vực, thường từ vài tuần đến vài tháng. Tỷ lệ approved ở lần nộp lại là cao nếu đã sửa được điểm yếu chính.',
    commonMistakes: [
      'Nộp lại ngay mà không hỏi chi tiết lý do bị từ chối từ ISA.',
      'Chuẩn bị lại hồ sơ giống hệt lần trước mà không sửa các vấn đề cơ bản.',
      'Không hiểu rõ ISA muốn kiểm chứng điều gì — ví dụ: thu nhập thực tế, chứng minh công việc khớp visa, hay tài chính đủ để sống ở Nhật.',
      'Nộp lại qua 行政書士 mà không rõ 行政書士 sẽ làm gì cụ thể.',
      'Chờ quá lâu để nộp lại, do vậy có thể bị hết hạn các tài liệu hỗ trợ.',
    ],
    faq: [
      {
        question: 'Không có process "appeal" chính thức sao?',
        answer: 'Đúng. Luật Nhật không có "appeal" để lật ngược quyết định từ chối. Tuy nhiên, bạn có quyền nộp lại hồ sơ bất kỳ lúc nào với tài liệu bổ sung. Nếu không đồng ý quyết định, bạn có thể đề nghị ISA xem xét lại hoặc tìm hiểu về 行政不服審査請求 (administrative objection), nhưng hình thức này rất hiếm được áp dụng cho visa.',
      },
      {
        question: 'Cần bao lâu để nộp lại?',
        answer: 'Không có waiting period bắt buộc. Bạn có thể nộp lại ngày hôm sau nếu đã chuẩn bị tài liệu. Tuy nhiên, nên dành thời gian để hiểu rõ vấn đề và chuẩn bị kỹ càng.',
      },
      {
        question: 'Tỷ lệ approved ở lần nộp lại là bao nhiêu?',
        answer: 'Không có thống kê chính thức, nhưng theo các 行政書士, tỷ lệ approved ở lần nộp lại là cao nếu đã sửa được điểm yếu chính. Những trường hợp "không bao giờ approved" thường liên quan đến vấn đề cơ bản như: không đủ điều kiện visa, hộ chiếu hết hạn, hoặc có vấn đề pháp lý.',
      },
      {
        question: 'Khi nào nên thuê 行政書士?',
        answer: 'Nên thuê khi: (1) bạn không tự hiểu lý do từ chối, (2) tài liệu phức tạp (ví dụ: sponsor company đang gặp khó khăn tài chính), (3) bạn đã nộp lại lần thứ 2 mà vẫn bị từ chối. 行政書士 có kinh nghiệm biết cách cải thiện hồ sơ và giao tiếp với ISA. Tuy nhiên, họ không thể "appeal" hoặc "lật ngược" quyết định.',
      },
      {
        question: 'Nếu bị từ chối 3 lần thì sao?',
        answer: 'Nên tìm hiểu kỹ xem vấn đề cơ bản là gì. Ví dụ: nếu bị từ chối lần 2-3 vì thu nhập quá thấp, có thể bạn không phù hợp với visa hiện tại. Hãy xem xét đổi sang visa khác hoặc đợi cải thiện tình hình tài chính.',
      },
    ],
    counterPhrases: [
      {
        jp: '不許可になった理由を詳しく教えていただけますか。',
        romaji: 'Fukyoka ni natta riyuu o kuwashiku oshiete itadakemasu ka.',
        vn: 'Anh/chị cho tôi biết chi tiết lý do bị từ chối được không?',
        note: 'Câu mở đầu khi gặp Nyukan sau khi nhận 不許可処分書. 不許可処分書 thường chỉ ghi lý do 1 dòng — phải hỏi chi tiết tại quầy.',
      },
      {
        jp: '今後の手続きについて確認したいです。再申請と在留資格変更、どちらが適切でしょうか。',
        romaji: 'Kongo no tetsuzuki ni tsuite kakunin shitai desu. Saishinsei to zairyuu shikaku henkou, dochira ga tekisetsu deshou ka.',
        vn: 'Tôi muốn xác nhận hướng xử lý tiếp. Nộp lại cùng tư cách hay đổi tư cách thì hợp lý hơn?',
        note: 'Nyukan có thể không "khuyến nghị" thẳng nhưng thường nói được hướng nào "có khả năng thấp" để bạn tự cân nhắc.',
      },
      {
        jp: '出国準備期間中の活動制限について教えてください。',
        romaji: 'Shukkoku junbi kikan-chuu no katsudou seigen ni tsuite oshiete kudasai.',
        vn: 'Cho tôi biết giới hạn hoạt động trong giai đoạn chuẩn bị xuất cảnh.',
        note: 'Trong 出国準備期間 (≈30 ngày): KHÔNG được làm việc, KHÔNG được học fulltime. Chỉ chuẩn bị rời hoặc nộp lại hồ sơ.',
      },
      {
        jp: '再申請する場合、補強すべき書類は何ですか。',
        romaji: 'Saishinsei suru baai, hokyou subeki shorui wa nan desu ka.',
        vn: 'Nếu nộp lại, tôi cần củng cố thêm giấy tờ gì?',
        note: 'Nyukan có thể không liệt kê chính xác, nhưng thường gợi ý "nhóm vấn đề" (tài chính / mô tả công việc / hành chính). Ghi lại để chuẩn bị 理由書.',
      },
      {
        jp: '理由書には前回の不許可をどう触れればいいですか。',
        romaji: 'Riyuusho ni wa zenkai no fukyoka o dou furereba ii desu ka.',
        vn: '理由書 (thư giải trình) tôi nên đề cập đến lần từ chối trước như thế nào?',
        note: 'Thường: thừa nhận lần trước, mô tả thay đổi gì đã làm, kèm tài liệu mới. KHÔNG đổ lỗi cho Nyukan, KHÔNG cãi quyết định cũ.',
      },
      {
        jp: '別の在留資格を検討するなら、どんな候補がありますか。',
        romaji: 'Betsu no zairyuu shikaku o kentou suru nara, donna kouho ga arimasu ka.',
        vn: 'Nếu cân nhắc tư cách khác, có những lựa chọn nào?',
        note: 'Nyukan KHÔNG được tư vấn cụ thể, nhưng có thể nói "có nhiều loại tư cách khác — xem trang 在留資格一覧". Cân nhắc kỹ với 行政書士 trước khi quyết định.',
      },
    ],
    keyTerms: [
      {
        term: '不許可処分',
        reading: 'ふきょかしょぶん',
        meaningVi: 'quyết định từ chối chính thức của Nyukan',
        noteVi: 'Khác 不受理 (không tiếp nhận hồ sơ — kỹ thuật). 不許可 = đã xét + không đồng ý. Nhận qua bưu điện hoặc tại quầy. Cấp kèm 不許可処分書 ghi lý do (thường 1 dòng). KHÔNG có hệ thống tự động "appeal lại" — phải xử lý qua 再申請 hoặc 行政不服審査請求.',
      },
      {
        term: '不許可理由',
        reading: 'ふきょかりゆう',
        meaningVi: 'lý do từ chối (ghi trên 不許可処分書)',
        noteVi: 'Thường viết ngắn gọn, kiểu "経済的能力の不足" (thiếu năng lực kinh tế), "活動内容が在留資格に該当しない" (hoạt động không khớp tư cách), "提出書類に不備がある" (tài liệu chưa đầy đủ). Phải đến quầy Nyukan để hỏi chi tiết — họ thường giải thích miệng nhưng không viết thành văn bản chi tiết.',
      },
      {
        term: '出国準備期間',
        reading: 'しゅっこくじゅんびきかん',
        meaningVi: 'giai đoạn chuẩn bị xuất cảnh (~30 ngày sau 不許可)',
        noteVi: 'Tư cách lưu trú đặc biệt cấp sau 不許可 để có thời gian rời Nhật hoặc thử lại. Thường 30 ngày, có thể 31-60 ngày tùy hoàn cảnh. KHÔNG được làm việc trong giai đoạn này (cả công việc cũ). Có thể dùng để nộp 再申請 hoặc 在留資格変更 sang tư cách khác.',
      },
      {
        term: '再申請',
        reading: 'さいしんせい',
        meaningVi: 'nộp lại đơn (sau khi bị 不許可)',
        noteVi: 'KHÔNG có thời gian chờ bắt buộc — nộp ngày hôm sau cũng được. Nhưng nộp lại bản cũ y nguyên = thường tiếp tục bị từ chối. Cần: 理由書 + tài liệu mới giải quyết đúng 不許可理由. Phí 再申請 tính lại từ đầu (~6,000 yên khi được duyệt).',
      },
      {
        term: '理由書',
        reading: 'りゆうしょ',
        meaningVi: 'thư giải trình (kèm 再申請)',
        noteVi: 'Văn bản tự do bằng tiếng Nhật giải thích: (1) lần trước bị 不許可 vì lý do gì, (2) đã sửa thế nào, (3) tài liệu mới chứng minh. Quan trọng để Nyukan hiểu bạn đã giải quyết vấn đề. Viết ngắn gọn 1-2 trang A4, lịch sự. KHÔNG đổ lỗi cho Nyukan, KHÔNG cãi quyết định cũ.',
      },
      {
        term: '行政不服審査請求',
        reading: 'ぎょうせいふふくしんさせいきゅう',
        meaningVi: 'khiếu nại hành chính (theo 行政不服審査法)',
        noteVi: 'Cơ chế chính thức để khiếu nại quyết định hành chính (gồm 入管). Nộp trong 3 tháng kể từ ngày biết quyết định. Xử lý qua 法務省 hoặc 出入国在留管理庁 cấp trên. Tỷ lệ thành công cho visa RẤT THẤP — chủ yếu dùng khi có vi phạm thủ tục rõ ràng từ phía Nyukan. Phải có luật sư hành chính tư vấn trước.',
      },
      {
        term: '行政書士',
        reading: 'ぎょうせいしょし',
        meaningVi: 'chuyên viên hành chính (hỗ trợ hồ sơ visa)',
        noteVi: 'Chuyên viên được 行政書士法 cấp phép. Hỗ trợ chuẩn bị + nộp hồ sơ thay khách. KHÔNG được "appeal" hoặc thay đổi quyết định Nyukan — họ chỉ giúp hồ sơ. Phí tham khảo: 5-20 vạn yên/case visa thường, cao hơn cho visa phức tạp (経営・管理, 高度専門職). Tìm qua 日本行政書士会連合会 hoặc giới thiệu của cộng đồng VN.',
      },
      {
        term: '在留資格変更 vs 再申請',
        reading: 'ざいりゅうしかくへんこう vs さいしんせい',
        meaningVi: 'đổi tư cách vs nộp lại cùng tư cách',
        noteVi: 'Lựa chọn quan trọng sau 不許可. 再申請: cùng tư cách + sửa hồ sơ — phù hợp khi vấn đề kỹ thuật/giấy tờ. 在留資格変更: đổi sang tư cách khác — phù hợp khi hoạt động thực tế không khớp tư cách cũ (vd: 留学 không kịp tốt nghiệp → 特定活動 tìm việc). Quyết định KHÔNG nên tự làm — nên tham khảo 行政書士 hoặc trang [[status-of-residence-change]].',
      },
    ],
    officialLinks: [
      { label: 'ISA — Các loại visa & tư cách lưu trú', url: 'https://www.moj.go.jp/isa/applications/status/index.html' },
      { label: 'ISA — Nếu bị từ chối, cách tìm hiểu chi tiết', url: 'https://www.moj.go.jp/isa/applications/procedures/' },
      { label: 'Danh sách ISA offices theo khu vực', url: 'https://www.moj.go.jp/isa/about/region/index.html' },
      { label: '在留資格変更許可申請 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/procedures/16-2.html' },
      { label: '在留資格一覧 — 出入国在留管理庁', url: 'https://www.moj.go.jp/isa/applications/qaq5.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra thông báo từ chối và lý do chính thức',
        description: 'ISA sẽ gửi **不許可処分書** (thông báo từ chối chính thức) kèm **不許可理由** (lý do từ chối). Tuy nhiên, lý do thường chỉ một dòng ngắn gọn như:\n\n- 「当該大学における勉学態度が不適切である」\n- 「雇用契約書と実際の勤務内容が異なる」\n- 「経済的能力の不足」\n\nLý do này thường **không rõ chi tiết**. Bước tiếp theo là hỏi trực tiếp ISA để hiểu kỹ hơn.',
        documents: ['Thông báo từ chối từ ISA', 'Thẻ cư trú hoặc giấy xác nhận gửi hồ sơ nếu chưa nhận được thẻ'],
        tip: 'Giữ bản gốc thông báo từ chối — bạn sẽ cần khi nộp lại hoặc tương tác với ISA.',
      },
      {
        step: 2,
        title: 'Liên hệ ISA để hỏi chi tiết lý do từ chối',
        description: 'Đến trực tiếp quầy ISA hoặc gọi hotline của cục công an nhập cảnh nơi xử lý hồ sơ của bạn. Hỏi cụ thể:\n\n- **Vấn đề nào là chính?** (tài chính, tư cách không phù hợp, tài liệu thiếu, hay vấn đề khác?)\n- **Cần thêm tài liệu gì để sửa được?**\n- **Có điều kiện cần thỏa mãn gì trước khi nộp lại không?** (ví dụ: tăng đơn vị nhân sự, bổ sung lương)\n- **Người nào/ phòng nào xử lý có thể cung cấp gợi ý không?**\n\n**Lưu ý:** ISA không được "hướng dẫn" chi tiết cách nộp lại, nhưng có thể giải thích lý do từ chối.',
        documents: ['Thông báo từ chối từ ISA', 'Hộ chiếu hoặc thẻ cư trú để xác minh danh tính'],
        tip: 'Nếu nhân viên ISA không giải thích rõ, hãy hỏi người quản lý hoặc tìm hiểu thêm từ 行政書士 có kinh nghiệm với loại visa của bạn.',
      },
      {
        step: 3,
        title: 'Phân tích vấn đề và chuẩn bị kế hoạch nộp lại',
        description: '**Dựa trên lý do từ chối, xác định vấn đề chính:**\n\n| Lý do từ chối | Vấn đề có thể | Cách sửa |\n|---|---|---|\n| Tài chính không đủ | Thu nhập thấp, tiết kiệm ít | Tăng lương, thêm người bảo lãnh, tiết kiệm thêm 3-6 tháng |\n| Công việc không khớp visa | Công việc thực tế khác đơn vị nhân sự khai báo | Điều chỉnh hợp đồng hoặc chuyển bộ phận sao cho khớp |\n| Tư cách không phù hợp | Điều kiện sinh hoạt/công việc đã thay đổi | Đánh giá lại xem visa hiện tại có phù hợp không; có cần đổi sang visa khác? |\n| Tài liệu thiếu | Hộ chiếu hết hạn, bằng cấp không công chứng | Cập nhật/công chứng tài liệu thiếu |\n| Vấn đề pháp lý | Lịch sử hành chính đỏ, nợ thuế | Giải quyết vấn đề pháp lý trước — nộp lại có thể vẫn bị từ chối |\n\nNếu không chắc, hãy tư vấn với 行政書士 chuyên về visa.',
        documents: [],
        tip: 'Đừng nộp lại ngay mà dành 2-4 tuần để chuẩn bị kỹ càng. Nộp lại nhanh mà không sửa được vấn đề chính = tiếp tục bị từ chối.',
      },
      {
        step: 4,
        title: 'Chuẩn bị và nộp lại hồ sơ',
        description: 'Nộp lại với tài liệu bổ sung giải quyết vấn đề chính. Ví dụ:\n\n**Nếu vấn đề tài chính:**\n- Giấy tờ thuế/bảo hiểm mới nhất (最新の給与明細)\n- Biên bản tài khoản ngân hàng (3-6 tháng gần nhất)\n- Giấy xác nhận bảo lãnh tài chính mới (nếu có bảo lãnh)\n- Lý do giải trình: "A company mới tăng lương tôi từ tháng X, dự kiến sẽ ổn định dài hạn"\n\n**Nếu vấn đề công việc:**\n- Hợp đồng lao động sửa đổi (nếu có thay đổi)\n- Giấy xác nhận từ công ty giải thích rõ công việc thực tế\n- Bảng lương hoặc giấy xác nhận từ người quản lý\n\n**Nếu vấn đề tư cách:**\n- Đôi khi không thể sửa — cân nhắc đổi sang visa khác nếu điều kiện cho phép\n\nNộp tại ISA như lần trước (trực tiếp, trực tuyến nếu áp dụng).',
        documents: ['Tài liệu bổ sung giải quyết vấn đề chính', 'Thông báo từ chối lần trước (để tham khảo)', 'Hộ chiếu + thẻ cư trú'],
        tip: 'Kèm theo lá giải trình (理由書) viết rõ ràng: "Lần trước bị từ chối vì [lý do], giờ tôi đã sửa bằng [tài liệu bổ sung]. Mong ISA xem xét lại".',
      },
      {
        step: 5,
        title: 'Theo dõi tiến độ và chuẩn bị cho kết quả',
        description: 'Sau khi nộp, ISA sẽ xét duyệt. Thời gian từ vài tuần đến vài tháng tùy hồ sơ.\n\n**Nếu approved:** ISA sẽ thông báo và cấp thẻ cư trú hoặc COE mới.\n\n**Nếu bị từ chối lần thứ 2:** Đừng nản chí. Tìm tư vấn từ 行政書士 hoặc luật sư để:\n- Xem xét đổi sang visa khác có thể phù hợp hơn\n- Hoặc đợi tình hình cải thiện (ví dụ: tăng lương, công ty ổn định hơn) rồi nộp lại lần thứ 3\n- Hoặc nếu vấn đề là cơ bản (ví dụ: không đủ tư cách), cân nhắc quay về Việt Nam.',
        documents: [],
        tip: 'Hãy lạc quan — nhiều người được approved ở lần nộp lại sau khi sửa được vấn đề chính.',
      },
    ],
  };

export default visaRejectionAppealProcess;
