import type { AdminGuide } from '../../../../types/content';

const visaRejectionAppealProcess: AdminGuide = {
    id: 'visa-rejection-appeal-process',
    category: 'immigration',
    lastVerified: '2026-05-04',
    priority: 'normal',
    title: 'Visa bị từ chối và cách kháng cáo / nộp lại',
    titleJp: '在留許可申請が不許可になった場合の対処法',
    icon: 'close-circle',
    color: '#E74C3C',
    description: 'Thủ tục khi visa hoặc Certificate of Eligibility (COE) bị từ chối. Luật Nhật KHÔNG có thủ tục "appeal" để lật ngược quyết định — chỉ có thể nộp lại hồ sơ với tài liệu bổ sung giải quyết lý do bị từ chối. Kết quả lần nộp lại phụ thuộc đánh giá của Nyukan, KHÔNG có gì đảm bảo. Trường hợp phức tạp nên tham vấn 行政書士 / 弁護士 chuyên về 入管.',
    searchKeywords: [
      'visa bị từ chối',
      'không được visa',
      'từ chối COE',
      'từ chối Certificate of Eligibility',
      '不許可',
      'fukyoka',
      '不許可処分',
      '不許可理由',
      'visa rejection',
      'visa denied',
      're-submit visa',
      'nộp lại visa',
      '再申請',
      'sai shinsei',
      '行政書士',
      'gyousei shoshi',
      '行政不服審査',
      'administrative objection',
      'visa từ chối nhiều lần',
      'lý do bị từ chối visa',
      'COE bị từ chối',
      '在留資格認定 不許可',
      '在留資格変更 不許可',
      '在留期間更新 不許可',
    ],
    legalScope: {
      jurisdiction: 'national',
      jurisdictionNote: 'Quyết định cấp / từ chối visa, COE, gia hạn, đổi tư cách thuộc thẩm quyền của 出入国在留管理庁 theo 入管法. Luật Nhật KHÔNG quy định thủ tục appeal chính thức (như nhiều nước phương Tây). Sau khi nhận 不許可処分書, người nộp có quyền: (1) nộp lại hồ sơ mới — KHÔNG có waiting period; (2) yêu cầu Nyukan giải thích lý do (口頭での説明); (3) trong một số trường hợp giới hạn, có thể nộp 行政不服審査請求 — nhưng thực tế rất hiếm được áp dụng cho visa. Kết quả lần nộp lại phụ thuộc đánh giá của Nyukan tại thời điểm — KHÔNG có gì đảm bảo, KHÔNG có "mẹo" để tăng tỷ lệ duyệt. Trường hợp nghiêm trọng nên có 行政書士 / 弁護士.',
      sourceVerifiedAt: '2026-05-04',
      nextReviewAt: '2026-12-01',
      riskLevel: 'high',
      whenToAskExpert: [
        'Đã bị từ chối ≥ 2 lần liên tiếp — tham khảo 行政書士 / 弁護士 chuyên 入管 trước khi nộp lần 3. Vấn đề có thể nằm ở yếu tố cấu trúc, không phải tài liệu.',
        'Lý do từ chối liên quan tài liệu giả / khai gian / bằng cấp không hợp lệ — cần 弁護士 ngay, KHÔNG tự xử lý.',
        'Lý do từ chối liên quan lịch sử hình sự / 在留違反 cũ — cần 弁護士 đánh giá khả năng và rủi ro trước khi nộp lại.',
        'Công ty bảo lãnh đang gặp khó khăn tài chính / công ty bị đánh giá tiêu cực bởi Nyukan — tham khảo 行政書士 về phương án thay đổi sponsor.',
        'COE bị từ chối khi đang ở nước ngoài (chưa nhập cảnh) — cần phối hợp với Đại sứ quán Nhật + 行政書士 ở Nhật.',
        'Bạn nghi quyết định Nyukan có sai sót về procedural — cân nhắc 弁護士 xem xét 行政不服審査請求 hoặc 行政訴訟 (rất hiếm thành công cho visa, chi phí cao).',
      ],
    },
    quickAction: {
      deadline: 'Không có waiting period cố định để nộp lại. Tuy nhiên: lý do từ chối có thể cần thời gian để khắc phục thực sự (vd: tăng lương, đợi công ty ổn định, công chứng lại bằng) — KHÔNG nên vội nộp lại nếu vấn đề cơ bản chưa được giải quyết.',
      office: 'Nyukan nơi đã nộp hồ sơ ban đầu (thường theo địa chỉ cư trú hoặc địa chỉ công ty bảo lãnh). Số tư vấn 在留資格 chung: 0570-013904 (Foreign Residents Support Center). Tham khảo pháp lý: 行政書士会 từng tỉnh / 弁護士会 / 法テラス 0570-078374 cho người thu nhập thấp.',
      doNow: [
        'Giữ NGUYÊN BẢN 不許可処分書 (giấy từ chối chính thức) — cần khi nộp lại + khi tư vấn 行政書士.',
        'Đến Nyukan trực tiếp xin giải thích lý do từ chối chi tiết (口頭での説明). KHÔNG có ai bắt buộc Nyukan giải thích đầy đủ — nhưng nên hỏi.',
        'Phân tích lý do: vấn đề nằm ở tài chính, tư cách, tài liệu, lịch sử hay yếu tố khác? Có thể khắc phục thực sự không?',
        'Nếu lý do là yếu tố KHÔNG thể khắc phục ngay (vd: chưa đủ điều kiện visa) — KHÔNG nộp lại; cân nhắc đổi loại visa khác hoặc đợi cải thiện hồ sơ.',
        'Nếu lý do có thể khắc phục — chuẩn bị tài liệu BỔ SUNG giải quyết đúng vấn đề (không phải nộp lại y nguyên hồ sơ cũ).',
        'Trường hợp phức tạp (lần thứ 2-3, lý do mơ hồ, sponsor có vấn đề) — tham vấn 行政書士 chuyên 入管 TRƯỚC khi nộp lại.',
        'Viết 理由書 (giải trình) ngắn gọn, trung thực: nêu lý do lần trước bị từ chối + tài liệu bổ sung lần này. KHÔNG cố "thuyết phục" hay "bào chữa" — chỉ nêu sự kiện.',
      ],
      bring: [
        '不許可処分書 (giấy từ chối lần trước) — bản gốc',
        'Hộ chiếu + 在留カード (nếu đang ở Nhật)',
        'Tài liệu BỔ SUNG giải quyết lý do từ chối',
        '理由書 (giải trình) viết tay hoặc đánh máy',
        'Đơn nộp lại theo loại visa (form từ trang Nyukan)',
        'Ảnh 4cm × 3cm mới',
      ],
      ifLate: 'Nếu visa đã hết hạn trong lúc chờ kết quả lần trước → tình trạng phụ thuộc loại visa và thời điểm. Nếu lý do thuộc 不法残留 → đến Nyukan tự thú + giải thích, KHÔNG trốn. Tham vấn 弁護士 / 法テラス trước khi đến Nyukan nếu lo lắng. Mất visa = ảnh hưởng lâu dài đến khả năng quay lại Nhật (cấm tái nhập 5-10 năm theo 入管法).',
      officialSourceLabels: [
        'ISA — Các loại visa & tư cách lưu trú',
        'ISA — Nếu bị từ chối, cách tìm hiểu chi tiết',
        'Danh sách ISA offices theo khu vực',
      ],
    },
    whoIsThisFor: [
      'Người bị từ chối visa (work, student, spouse, dependent, change of status) và muốn biết cách tiếp theo.',
      'Người muốn hiểu chi tiết lý do bị từ chối trước khi nộp lại.',
      'Người không chắc liệu có thể appeal hay phải nộp lại từ đầu.',
    ],
    whenToDo: [
      'Ngay sau khi nhận thông báo từ chối, hãy liên hệ immigration bureau để hỏi chi tiết lý do.',
      'Không nên nộp lại ngay mà hãy phân tích kỹ vấn đề và chuẩn bị tài liệu bổ sung.',
      'Không có waiting period bắt buộc — có thể nộp lại ngày hôm sau nếu đã sửa được vấn đề.',
    ],
    whereToDo: [
      'Immigration Bureau (ISA / 出入国在留管理庁) — cục công an nhập cảnh có thẩm quyền nơi bạn nộp hồ sơ ban đầu.',
      'Liên hệ để hỏi chi tiết: đương mặt tại quầy hoặc gọi hotline nếu cục có hỗ trợ.',
      'Tương tự như ban đầu nộp tại cùng một cục hoặc trực tuyến nếu áp dụng.',
    ],
    estimatedTime: 'Không có waiting period bắt buộc. Thời gian xét duyệt lần nộp lại phụ thuộc hồ sơ và khu vực, thường từ vài tuần đến vài tháng. Kết quả lần nộp lại phụ thuộc đánh giá của Nyukan — KHÔNG có gì đảm bảo, kể cả khi đã bổ sung tài liệu.',
    commonMistakes: [
      'Nộp lại ngay mà không hỏi chi tiết lý do bị từ chối từ ISA.',
      'Chuẩn bị lại hồ sơ giống hệt lần trước mà không sửa các vấn đề cơ bản.',
      'Không hiểu rõ ISA muốn kiểm chứng điều gì — ví dụ: thu nhập thực tế, chứng minh công việc khớp visa, hay tài chính đủ để sống ở Nhật.',
      'Nộp lại qua 行政書士 mà không rõ 行政書士 sẽ làm gì cụ thể.',
      'Chờ quá lâu để nộp lại, do vậy có thể bị hết hạn các tài liệu hỗ trợ.',
    ],
    faq: [
      {
        question: 'Không có process "appeal" chính thức sao?',
        answer: 'Đúng. Luật Nhật không có "appeal" để lật ngược quyết định từ chối. Tuy nhiên, bạn có quyền nộp lại hồ sơ bất kỳ lúc nào với tài liệu bổ sung. Nếu không đồng ý quyết định, bạn có thể đề nghị ISA xem xét lại hoặc tìm hiểu về 行政不服審査請求 (administrative objection), nhưng hình thức này rất hiếm được áp dụng cho visa.',
      },
      {
        question: 'Cần bao lâu để nộp lại?',
        answer: 'Không có waiting period bắt buộc. Bạn có thể nộp lại ngày hôm sau nếu đã chuẩn bị tài liệu. Tuy nhiên, nên dành thời gian để hiểu rõ vấn đề và chuẩn bị kỹ càng.',
      },
      {
        question: 'Tỷ lệ duyệt ở lần nộp lại là bao nhiêu?',
        answer: 'KHÔNG có thống kê công khai. Kết quả lần nộp lại phụ thuộc đánh giá của Nyukan + việc tài liệu bổ sung có thực sự giải quyết lý do từ chối hay không. Trường hợp lý do là yếu tố cấu trúc (không đủ điều kiện visa, hộ chiếu hết hạn, có vấn đề pháp lý) — chỉ nộp lại tài liệu thường không thay đổi kết quả. KHÔNG ai có thể đảm bảo trước.',
      },
      {
        question: 'Khi nào nên thuê 行政書士?',
        answer: 'Nên thuê khi: (1) bạn không tự hiểu lý do từ chối, (2) tài liệu phức tạp (ví dụ: sponsor company đang gặp khó khăn tài chính), (3) bạn đã nộp lại lần thứ 2 mà vẫn bị từ chối. 行政書士 có kinh nghiệm biết cách cải thiện hồ sơ và giao tiếp với ISA. Tuy nhiên, họ không thể "appeal" hoặc "lật ngược" quyết định.',
      },
      {
        question: 'Nếu bị từ chối 3 lần thì sao?',
        answer: 'Nên tìm hiểu kỹ xem vấn đề cơ bản là gì. Ví dụ: nếu bị từ chối lần 2-3 vì thu nhập quá thấp, có thể bạn không phù hợp với visa hiện tại. Hãy xem xét đổi sang visa khác hoặc đợi cải thiện tình hình tài chính.',
      },
    ],
    counterPhrases: [
      {
        jp: '不許可になった理由を教えていただけますか。',
        romaji: 'Fukyoka ni natta riyuu o oshiete itadakemasu ka.',
        vn: 'Cho tôi biết lý do bị từ chối được không?',
        note: 'Câu hỏi tại quầy Nyukan khi đến xin giải thích chi tiết. Nyukan không bắt buộc giải thích đầy đủ, nhưng có thể cho thêm thông tin.',
      },
      {
        jp: '再申請の場合、追加で必要な書類はありますか。',
        romaji: 'Sai shinsei no baai, tsuika de hitsuyou na shorui wa arimasu ka.',
        vn: 'Nếu nộp lại, có cần thêm tài liệu gì không?',
        note: 'Hỏi để hiểu Nyukan kỳ vọng tài liệu nào — họ không "hướng dẫn" cụ thể nhưng có thể nêu loại tài liệu liên quan.',
      },
      {
        jp: '今回の不許可は記録に残りますか。',
        romaji: 'Konkai no fukyoka wa kiroku ni nokorimasu ka.',
        vn: 'Lần từ chối này có được ghi vào hồ sơ không?',
        note: 'Có — mọi quyết định Nyukan đều được lưu. Lần nộp lại Nyukan sẽ thấy lịch sử. Trung thực là cách tốt nhất.',
      },
      {
        jp: '行政書士に相談したいのですが、紹介してください。',
        romaji: 'Gyousei shoshi ni soudan shitai no desu ga, shoukai shite kudasai.',
        vn: 'Tôi muốn tham vấn 行政書士, xin giới thiệu.',
        note: 'Liên hệ 日本行政書士会連合会 hoặc 行政書士会 từng tỉnh. Cũng có thể qua 法テラス 0570-078374 cho trường hợp khó khăn tài chính.',
      },
      {
        jp: '別の在留資格に変更できますか。',
        romaji: 'Betsu no zairyuu shikaku ni henkou dekimasu ka.',
        vn: 'Tôi có thể đổi sang loại visa khác không?',
        note: 'Hỏi Nyukan / 行政書士 — đôi khi đổi loại visa phù hợp hơn nộp lại cùng loại đã bị từ chối.',
      },
    ],
    keyTerms: [
      {
        term: '不許可',
        reading: 'ふきょか',
        meaningVi: 'từ chối (đối với đơn xin visa / COE / gia hạn / đổi tư cách)',
        noteVi: 'Quyết định chính thức của Nyukan: KHÔNG cấp visa hoặc tư cách lưu trú. Khác với "保留" (giữ lại để xét tiếp). Ghi trên 不許可処分書 gửi đến người nộp. Lý do thường ngắn — có thể đến Nyukan xin giải thích chi tiết hơn (口頭での説明).',
      },
      {
        term: '不許可処分書',
        reading: 'ふきょかしょぶんしょ',
        meaningVi: 'thông báo từ chối chính thức (giấy quyết định)',
        noteVi: 'Văn bản chính thức của Nyukan thông báo quyết định 不許可. Ghi: tên người nộp, loại đơn, lý do từ chối (thường ngắn 1 dòng), ngày ra quyết định. GIỮ NGUYÊN BẢN — cần khi nộp lại + khi tham vấn 行政書士 / 弁護士.',
      },
      {
        term: '不許可理由',
        reading: 'ふきょかりゆう',
        meaningVi: 'lý do từ chối (do Nyukan đưa ra)',
        noteVi: 'Lý do ghi trên 不許可処分書 — thường rất ngắn (vd: "経済的能力の不足"). Lý do chi tiết KHÔNG có sẵn — phải đến Nyukan xin giải thích (口頭での説明). Nyukan KHÔNG bắt buộc giải thích đầy đủ. Trường hợp lý do mơ hồ, tham vấn 行政書士 để phân tích.',
      },
      {
        term: '再申請',
        reading: 'さいしんせい',
        meaningVi: 'nộp lại đơn (sau khi bị từ chối)',
        noteVi: 'KHÔNG phải "appeal" — chỉ là nộp đơn MỚI với tài liệu bổ sung. Không có waiting period bắt buộc. KHÔNG có gì đảm bảo lần này được duyệt — kết quả phụ thuộc xem tài liệu bổ sung có giải quyết lý do từ chối hay không + đánh giá của Nyukan.',
      },
      {
        term: '理由書',
        reading: 'りゆうしょ',
        meaningVi: 'giải trình (do người nộp viết)',
        noteVi: 'Lá giải trình kèm hồ sơ nộp lại. Nội dung: nêu lý do lần trước bị từ chối + tài liệu bổ sung lần này đã giải quyết vấn đề thế nào. TRUNG THỰC + ngắn gọn — KHÔNG cố "thuyết phục" / "bào chữa" / "kể khổ". Nyukan đánh giá trên tài liệu thực tế, không trên lời văn.',
      },
      {
        term: '行政書士',
        reading: 'ぎょうせいしょし',
        meaningVi: 'người làm thủ tục hành chính (có giấy phép)',
        noteVi: 'Chuyên gia có thể hỗ trợ chuẩn bị hồ sơ visa, viết 理由書, nộp giúp Nyukan. KHÔNG phải luật sư — không đại diện tại tòa. Phí ~5万-30万円/case tùy độ phức tạp. KHÔNG ai có thể "đảm bảo" được duyệt — cẩn thận với quảng cáo "100% đậu". Tra qua 日本行政書士会連合会 hoặc 行政書士会 từng tỉnh.',
      },
      {
        term: '弁護士',
        reading: 'べんごし',
        meaningVi: 'luật sư',
        noteVi: 'Khác 行政書士. Có thể đại diện tại tòa nếu cần kiện hành chính (行政訴訟). Cần khi: lịch sử hình sự / 在留違反 cũ, lo lắng visa bị thu hồi, cân nhắc 行政不服審査請求. Phí cao hơn 行政書士 (~30万-100万円). Tra qua 弁護士会 từng tỉnh hoặc 法テラス cho người thu nhập thấp.',
      },
      {
        term: '行政不服審査請求',
        reading: 'ぎょうせいふふくしんさせいきゅう',
        meaningVi: 'yêu cầu xem xét lại quyết định hành chính',
        noteVi: 'Thủ tục yêu cầu cơ quan cấp trên xem xét lại quyết định của Nyukan. Áp dụng trong 3 tháng kể từ khi nhận thông báo. Trên thực tế RẤT HIẾM được áp dụng cho visa — Nyukan thường giữ nguyên quyết định. Trường hợp nghiêm túc muốn dùng — bắt buộc cần 弁護士. KHÔNG phải "appeal" Tây phương.',
      },
    ],
    officialLinks: [
      { label: 'ISA — Các loại visa & tư cách lưu trú', url: 'https://www.moj.go.jp/isa/applications/status/index.html' },
      { label: 'ISA — Nếu bị từ chối, cách tìm hiểu chi tiết', url: 'https://www.moj.go.jp/isa/applications/procedures/' },
      { label: 'Danh sách ISA offices theo khu vực', url: 'https://www.moj.go.jp/isa/about/region/index.html' },
    ],
    steps: [
      {
        step: 1,
        title: 'Kiểm tra thông báo từ chối và lý do chính thức',
        description: 'ISA sẽ gửi **不許可処分書** (thông báo từ chối chính thức) kèm **不許可理由** (lý do từ chối). Tuy nhiên, lý do thường chỉ một dòng ngắn gọn như:\n\n- 「当該大学における勉学態度が不適切である」\n- 「雇用契約書と実際の勤務内容が異なる」\n- 「経済的能力の不足」\n\nLý do này thường **không rõ chi tiết**. Bước tiếp theo là hỏi trực tiếp ISA để hiểu kỹ hơn.',
        documents: ['Thông báo từ chối từ ISA', 'Thẻ cư trú hoặc giấy xác nhận gửi hồ sơ nếu chưa nhận được thẻ'],
        tip: 'Giữ bản gốc thông báo từ chối — bạn sẽ cần khi nộp lại hoặc tương tác với ISA.',
      },
      {
        step: 2,
        title: 'Liên hệ ISA để hỏi chi tiết lý do từ chối',
        description: 'Đến trực tiếp quầy ISA hoặc gọi hotline của cục công an nhập cảnh nơi xử lý hồ sơ của bạn. Hỏi cụ thể:\n\n- **Vấn đề nào là chính?** (tài chính, tư cách không phù hợp, tài liệu thiếu, hay vấn đề khác?)\n- **Cần thêm tài liệu gì để sửa được?**\n- **Có điều kiện cần thỏa mãn gì trước khi nộp lại không?** (ví dụ: tăng đơn vị nhân sự, bổ sung lương)\n- **Người nào/ phòng nào xử lý có thể cung cấp gợi ý không?**\n\n**Lưu ý:** ISA không được "hướng dẫn" chi tiết cách nộp lại, nhưng có thể giải thích lý do từ chối.',
        documents: ['Thông báo từ chối từ ISA', 'Hộ chiếu hoặc thẻ cư trú để xác minh danh tính'],
        tip: 'Nếu nhân viên ISA không giải thích rõ, hãy hỏi người quản lý hoặc tìm hiểu thêm từ 行政書士 có kinh nghiệm với loại visa của bạn.',
      },
      {
        step: 3,
        title: 'Phân tích vấn đề và chuẩn bị kế hoạch nộp lại',
        description: '**Dựa trên lý do từ chối, xác định vấn đề chính:**\n\n| Lý do từ chối | Vấn đề có thể | Cách sửa |\n|---|---|---|\n| Tài chính không đủ | Thu nhập thấp, tiết kiệm ít | Tăng lương, thêm người bảo lãnh, tiết kiệm thêm 3-6 tháng |\n| Công việc không khớp visa | Công việc thực tế khác đơn vị nhân sự khai báo | Điều chỉnh hợp đồng hoặc chuyển bộ phận sao cho khớp |\n| Tư cách không phù hợp | Điều kiện sinh hoạt/công việc đã thay đổi | Đánh giá lại xem visa hiện tại có phù hợp không; có cần đổi sang visa khác? |\n| Tài liệu thiếu | Hộ chiếu hết hạn, bằng cấp không công chứng | Cập nhật/công chứng tài liệu thiếu |\n| Vấn đề pháp lý | Lịch sử hành chính đỏ, nợ thuế | Giải quyết vấn đề pháp lý trước — nộp lại có thể vẫn bị từ chối |\n\nNếu không chắc, hãy tư vấn với 行政書士 chuyên về visa.',
        documents: [],
        tip: 'Đừng nộp lại ngay mà dành 2-4 tuần để chuẩn bị kỹ càng. Nộp lại nhanh mà không sửa được vấn đề chính = tiếp tục bị từ chối.',
      },
      {
        step: 4,
        title: 'Chuẩn bị và nộp lại hồ sơ',
        description: 'Nộp lại với tài liệu bổ sung giải quyết vấn đề chính. Ví dụ:\n\n**Nếu vấn đề tài chính:**\n- Giấy tờ thuế/bảo hiểm mới nhất (最新の給与明細)\n- Biên bản tài khoản ngân hàng (3-6 tháng gần nhất)\n- Giấy xác nhận bảo lãnh tài chính mới (nếu có bảo lãnh)\n- Lý do giải trình: "A company mới tăng lương tôi từ tháng X, dự kiến sẽ ổn định dài hạn"\n\n**Nếu vấn đề công việc:**\n- Hợp đồng lao động sửa đổi (nếu có thay đổi)\n- Giấy xác nhận từ công ty giải thích rõ công việc thực tế\n- Bảng lương hoặc giấy xác nhận từ người quản lý\n\n**Nếu vấn đề tư cách:**\n- Đôi khi không thể sửa — cân nhắc đổi sang visa khác nếu điều kiện cho phép\n\nNộp tại ISA như lần trước (trực tiếp, trực tuyến nếu áp dụng).',
        documents: ['Tài liệu bổ sung giải quyết vấn đề chính', 'Thông báo từ chối lần trước (để tham khảo)', 'Hộ chiếu + thẻ cư trú'],
        tip: 'Kèm 理由書 (giải trình) viết ngắn gọn + trung thực: "Lần trước bị từ chối vì [lý do], lần này bổ sung [tài liệu]". KHÔNG cố "thuyết phục", KHÔNG kể khổ. Nyukan đánh giá trên tài liệu thực tế.',
      },
      {
        step: 5,
        title: 'Theo dõi tiến độ và chuẩn bị cho kết quả',
        description: 'Sau khi nộp, ISA sẽ xét duyệt. Thời gian từ vài tuần đến vài tháng tùy hồ sơ.\n\n**Nếu được duyệt:** ISA sẽ thông báo và cấp thẻ cư trú hoặc COE mới.\n\n**Nếu bị từ chối lần thứ 2:** \n- Tham vấn 行政書士 / 弁護士 chuyên 入管 — vấn đề có thể nằm ở yếu tố cấu trúc, không phải tài liệu\n- Cân nhắc đổi sang loại visa khác nếu điều kiện cho phép\n- Hoặc đợi cải thiện tình hình thực tế (vd: tăng lương ổn định 6+ tháng, công ty hồi phục) rồi nộp lại\n- Nếu vấn đề cơ bản (không đủ điều kiện visa) — cân nhắc kế hoạch dài hạn khác (đổi visa, về VN tạm)',
        documents: [],
        tip: 'KHÔNG có "mẹo" hay "công thức" để đảm bảo lần nộp lại được duyệt. Đánh giá hoàn toàn do Nyukan. Trường hợp khó nên tham vấn 行政書士 / 弁護士 thay vì tự suy đoán.',
      },
    ],
  };

export default visaRejectionAppealProcess;
